packages/lesswrong/components/posts/PostsPage/PostsPagePostFooter.tsx
packages/lesswrong/lib/collections/posts/fragments.ts
packages/lesswrong/lib/collections/users/custom_fields.ts
packages/lesswrong/lib/collections/users/fragments.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

We tested this out on the EA Forum for ~10 days to see if it would encourage more PMs. Only 2 PMs were attributed to it, and ~100 users used it to view the author's profile. Since it didn't move the needle we're just going to remove it for now.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202564745379694) by [Unito](https://www.unito.io)

[EA Forum only] remove post author card

---

packages/lesswrong/components/ea-forum/StickiedPosts.tsx

Based on a request from Lizka:
> Could we add a hover-over for "Pinned Posts" ?
It could read: "The Forum Team thinks these posts and threads should stay at the top of the Frontpage for a while"
https://cea-core.slack.com/archives/C038J512SD8/p1657114395636789

[EA Forum only] add tooltip text on the Pinned Posts heading

---

packages/lesswrong/server/notificationCallbacks.tsx

Fixes [this Asana issue](https://app.asana.com/0/inbox/1202509647380319).
Here we fix the bug by adding a separate hook for `updateAfter`.
We check `hasCoauthorPermission === false` instead of `!hasCoauthorPermission` as it's possible for `hasCoauthorPermission` to be `undefined` in some cases where the post is only partially updated. Ideally, it would probably be best to retype these update hooks throughout the whole codebase with a parameter of type `Partial<DbPost>` instead of `DbPost`, but this is quite a big job worthy of it's own ticket.
We've also switched from `updateMutator` to `Posts.rawUpdateOne`; we don't want to retrigger the hooks here and this seems better semantically as well. The bug on lw-deploy also seemed to be caused by `updateMutator` not actually updating the record …

Fix coauthor notifications

---

packages/lesswrong/components/sequences/LargeSequencesItem.tsx
packages/lesswrong/components/sequences/SequencesGridItem.tsx
packages/lesswrong/components/sequences/SequencesHoverOver.tsx
packages/lesswrong/components/titles/SequencesPageTitle.tsx
packages/lesswrong/lib/collections/sequences/fragments.ts
packages/lesswrong/lib/collections/sequences/helpers.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

It was a bit sad that the sequence items on the frontpage don't link to the full collection page for their respective collections. After thinking about whether/how to change that, or maybe creating a new Collection item, I thought it'd actually work best if I gave each sequence an anchor-tag that could be directly linked to.
SequencesGridItem now checks if the sequence has a canonicalCollectionSlug, and if so links to the _id of the sequence on that collection page.
...
Additionally, this PR makes it so on a sequence page, if the sequence has a canonicalCollectionSlug, the page's subtitle links to the collection instead of the sequence itself (which was sort of useless anyway).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202571406254813) by …

SequencesGridItem links to collection page

---

packages/lesswrong/components/common/LinkCard.tsx
packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
packages/lesswrong/components/posts/PostsPage/PostsTopSequencesNav.tsx
packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
packages/lesswrong/components/sequences/LargeSequencesItem.tsx
packages/lesswrong/components/sequences/SequencesHoverOver.tsx
packages/lesswrong/components/sequences/SequencesSmallPostLink.tsx
packages/lesswrong/lib/routes.ts

– SequencesSmallPostLink now links you to the proper sequence url for a post
– SequenceGridItems now don't have clickable hoverovers
– Reverted the logged-in user frontpage experience (so that they don't accidentally tune out the curated sequences before we have a chance to make them better. This also fixes a bug where people where logged in users were seeing the Recommended Reading on mobile, despite having tried to filter it out)
– Adds /highlights to the sidebar

Fix highlights bugs

---

packages/lesswrong/components/sequences/LargeSequencesItem.tsx
packages/lesswrong/components/sequences/SequencesSmallPostLink.tsx

Slightly increase checkbox size, decrease padding beneath each large sequence item.
New:
Old:

Tweaks sequence styles

---

packages/lesswrong/components/sequences/BooksItem.tsx

Removing the AB test for LargeSequencesItem, since a) it seemed basically like an obvious improvement, b) there were some bugs of how different components interacted with different versions of the A/B test, and either I had to started applying the AB-test all over the place, or just remove it. Seemed better to do the latter.

Remove LargeSequencesItem AB test 

---

packages/lesswrong/components/common/withRecordPostView.tsx
packages/lesswrong/components/sequences/BooksItem.tsx
packages/lesswrong/components/sequences/BooksProgressBar.tsx
packages/lesswrong/components/sequences/CollectionsPage.tsx
packages/lesswrong/components/sequences/SequencesSmallPostLink.tsx

Previous attempt introduced infinite(?) refetch loop, breaking R:A-Z (and possibly other collections) due to the rerenders.  Using only client-side state to eliminate the need for a network request (which causes the rerenders).
Tested locally in branches off both `master` and `lw-deploy`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202579087041445) by [Unito](https://www.unito.io)

implement live-updating post read progress using client-side state

---

packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx

These are removed in master but for some reason the change isn't in LW Deploy. Brings lw-deploy and master in sync.

Remove curated sequences from lw deploy

---

packages/lesswrong/themes/siteThemes/eaTheme.ts

[Asana task](https://app.asana.com/0/628521446211730/1200830492067961/f)
Before and after:
The suggested fix of using `font-variant: all-small-caps` doesn't seem to actually help. It looks like the problem actually exists somewhere in the font itself, because even trying to explicity enable old-style numerals with `font-feature-settings: "onum"` doesn't seem to make a difference.
The most direct solution is probably just to make the letters uppercase and to reduce the font size which should avoid any bugs in the font, and protect us from changes to the font in the future. We can do directly in the EAForum style config, since the bug isn't present in the font used by LW:
(A post in the dev database where this case be tested: [http://localhost:3000/s/bCEttNRSTJDZyGEeT/p/6MhznGtuiCivvPmf2](ht …

Fix smallcaps styling for sequence titles on EA forum

---

packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx

Makes it so you can sort comments/posts in a SunshineNewUsersInfo by either karma or postedAt date (previously it was just sorted by karma)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202581202967092) by [Unito](https://www.unito.io)

sunshine sort comments + reviewedByUser name

---

packages/lesswrong/server/voteServer.ts

Got a report of a mysterious bug that only seemed to prevent voting on [this post](https://forum.effectivealtruism.org/posts/SbwWBhi6T6qZwxu2X/the-righteous-mind-book-review). Turns out this was caused by one of the votes being associated with a `userId` that doesn't have a matching user. Not sure how that happened, but this should fix the immediate issue.

fix a small bug preventing voting on a few posts

---

packages/lesswrong/components/tagging/FilterMode.tsx
packages/lesswrong/components/tagging/TagFilterSettings.tsx
packages/lesswrong/components/tagging/usePersonalBlogpostInfo.tsx

[Asana task](https://app.asana.com/0/628521446211730/1202422289278835/f)
This PR adds a "Default" label to the FilterMode when the filter is set to 0. For now, I've only added this to the EAForum - it seems a little unneccesary on LW since there's already a "+0" button that can be clicked. Enabling it for LW would be very simple though; we'd just need to remove `userHasNewTagSubscriptions(currentUser) &&` at line 240.
I also included 2 more small changes here:
* A fix for a minor bug where buttons sometimes have to be clicked twice to reset the filter to default due to `inputTime` not being reset.
* A change to the tooltip text on the EAForum from "Latest Posts" to "Frontpage Posts". "Latest Posts" makes sense on LW because the section is titled "Latest", but it doesn't make sense on the …

Show 'Default' label on tag filters that are set to 0

---

packages/lesswrong/components/posts/PostsItem2.tsx
packages/lesswrong/components/posts/PostsItem2MetaInfo.tsx
packages/lesswrong/components/posts/PostsItemIcons.tsx

Made by JP & Jim pairing
Changes the width-allocation between post title and coauthors when one or both is long and has ellipses, fixing a case where there was a range of screen widths in which most of the width went to coauthors and very little title was shown. Also makes it so that the post icons don't reserve extra space for their margins if there are no post icons.
Previously:
Now:
Normal:
LessWrong:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202610376404388) by [Unito](https://www.unito.io)

Fix titles being squeezed with many coauthors

---

packages/lesswrong/components/sequences/EACoreReading.tsx

Noticed this on prod when investigating a different issue. Not sure how this happened?

[EA Forum only] fix UI bug with core sequences

---

packages/lesswrong/components/tagging/AddTag.tsx
packages/lesswrong/components/tagging/AllTagsAlphabetical.tsx
packages/lesswrong/components/tagging/AllTagsPage.tsx
packages/lesswrong/components/tagging/NewTagPage.tsx
packages/lesswrong/components/tagging/TagPage.tsx
packages/lesswrong/components/tagging/TagPageButtonRow.tsx
packages/lesswrong/lib/collections/tags/collection.ts

I've left it visible for logged out users. This may not be the optimal solution. Ideally I'd have some greyed out thing perhaps?

[EA] Prevent users who cannot edit or create Topics from seeing edit or new topic buttons

---

packages/lesswrong/components/posts/TableOfContents/ToCColumn.tsx

The Welcome Box currently doesn't show on posts that don't have a table of contents.
With the fix, it does.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202611495419029) by [Unito](https://www.unito.io)

fix display of welcome box on posts without a ToC

---

packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
packages/lesswrong/components/ea-forum/users/modules/EAUsersProfileTabbedSection.tsx

This fixes a bug where sometimes your drafts would be collapsed by default when viewing your own profile. Also fixes a bug I encountered around the collapsable tab body while changing my page zoom.

[EA Forum only] drafts should be expanded by default when viewing your own profile

---

packages/lesswrong/lib/collections/posts/helpers.ts
packages/lesswrong/server/notificationCallbacks.tsx
packages/lesswrong/server/voteServer.ts

I was creating a new event on prod by duplicating an existing one, and I ran into an error like this. It didn't prevent the event from being created, but the event had no votes on it.
```
["TypeError: Cannot read property 'map' of null","    at getConfirmedCoauthorIds (/Users/sarah/EAForum/packages/lesswrong/lib/collections/posts/helpers.ts:280:27)","    at createVote (/Users/sarah/EAForum/packages/lesswrong/server/voteServer.ts:85:7)","    at addVoteServer (/Users/sarah/EAForum/packages/lesswrong/server/voteServer.ts:43:23)","    at performVoteServer (/Users/sarah/EAForum/packages/lesswrong/server/voteServer.ts:218:44)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at LWPostsNewUpvoteOwnPost (/Users/sarah/EAForum/packages/lesswrong/server/callbacks/postC …
```

fix bug that prevents self-vote when duplicating an event

---

packages/lesswrong/components/search/SearchBarResults.tsx

Reported by Lizka on #forum-smalls
Before and after:

Fix user search 'top' property on xs screens

---

packages/lesswrong/themes/stylePiping.ts

This PR adds the typical numbering convention for nested ordered lists used by Google Docs, Slack, and most of other places.

Nested ordered list styling

---

package.json
packages/lesswrong/components/walledGarden/GardenCodeWidget.tsx
packages/lesswrong/lib/vulcan-forms/schema_utils.ts
packages/lesswrong/server/scripts/voteMigration.ts
yarn.lock

Upgrade Typescript to the latest version (4.7.4). Fixes a few small things that the new version complains about that the old one didn't (a missing await in an ancient migration, `keyof` potentially allowing `symbol`, and spreading a non-object as object props with no effect).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202625452806054) by [Unito](https://www.unito.io)

Upgrade Typescript to 4.7.4

---

packages/lesswrong/lib/collections/sequences/schema.ts

We had someone set it for a number of sequences. Some admin was apparently guessing and just filling it in according to their guess. Best to add a tooltip.

Add tooltip to canonicalCollectionSlug on sequences

---

packages/lesswrong/components/tagging/TagPage.tsx

This PR collapses topic descriptions on the EA Forum at the 'Further Reading' heading if it exists, or the 'Bibliography' heading otherwise.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202578080349578) by [Unito](https://www.unito.io)

Collapse topic descriptions at 'Further reading' / 'Bibliography'

---

build.js
packages/lesswrong/client/autoRefresh.ts

If you triggered two rebuilds concurrently, the first of which succeeds and the second of which fails, this could lead to a case where connected browser tabs enter a refresh loop. Only affects development.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202610274687750) by [Unito](https://www.unito.io)

Fix a bug in development autorefresh that could cause a refresh loop

---

packages/lesswrong/components/messaging/MessageItem.tsx

Reported by Lizka. Before and after:

Fix sizing of images in private messages

---

packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx
packages/lesswrong/lib/collections/users/fragments.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

This is per request from Lizka: "Could mods/admins see links people add to their profiles when we hover over new users in the sidebar?"
Jonathan and I figured this would cover it, by coloring the links that appear in the bio, and also listing any `website` link if the user has that filled in.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202634934338948) by [Unito](https://www.unito.io)

Add link coloring and website link to sunshine new user hoverover

---

packages/lesswrong/components/tagging/TagPage.tsx

The error occurs when the tag has no content.
Reported on slask by Lizka and Pablo: created a new entry for [Conjecture](https://forum.effectivealtruism.org/topics/conjecture) (the AI safety org) but when I click on it I get the following error:
`Error: TypeError: Cannot read properties of undefined (reading 'includes')`

Fix 'undefined' error when tag page has no content

---

packages/lesswrong/components/comments/CommentsItem/CommentBody.tsx
packages/lesswrong/components/common/ContentItemBody.tsx
packages/lesswrong/components/common/ContentItemTruncated.tsx
packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
packages/lesswrong/components/posts/PostsHighlight.tsx
packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/components/questions/Answer.tsx
packages/lesswrong/components/sequences/SequencesPage.tsx
packages/lesswrong/components/users/UsersProfile.tsx
packages/lesswrong/lib/publicSettings.ts

for https://github.com/ForumMagnum/ForumMagnum/issues/5075
Add `nofollow` to all links in content created by users with less than 10 karma. The threshold is configurable. Applied at render time so when they gain karma their links change retroactively.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202615985522670) by [Unito](https://www.unito.io)

add nofollow to links by users with less than 10 karma

---

packages/lesswrong/components/posts/PostsPage/PostActions.tsx

Removing an old version of the edit post link (without the collaborative editing logic) that was added back to `PostActions` by accident in [this PR](https://github.com/ForumMagnum/ForumMagnum/pull/5263).
Broken:
Fixed:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202627380433526) by [Unito](https://www.unito.io)

remove redundant edit post link

---

packages/lesswrong/components/search/SequencesSearchHit.tsx

When I first made the sequence search PR I only tested it from the home page. Without adding a "/" at the beginning of the url, the url is appended to the current url, which most of the time was wrong.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202652463871414) by [Unito](https://www.unito.io)

Fixed link in sequence search hit

---

packages/lesswrong/components/posts/PostsPage/WelcomeBox.tsx
packages/lesswrong/components/posts/TableOfContents/ToCColumn.tsx
packages/lesswrong/server/utils/httpUtil.ts

The Welcome Box was behaving erratically.  The div the WelcomeBox was nested in would sometimes appear inside of `gap3`, so I though it was a [client-server rendering mismatch issue](https://github.com/vercel/next.js/issues/7417).  However, there was another issue where the welcome box would show up at the very bottom of the page (beneath all the comments), because the `tocActivated` class was not being applied.  Digging in, this was because:
1. the abTestGroup was not being correctly assigned, because
1. the clientId was not getting picked up by the abTestGroup assignment logic, because
1. it was using the `useCookies` hook, which missed the cookie, because
1. that hook relies on the cookies passed in to `CookiesProvider`, which in turn relies on `getAllCookiesFromReq`, and that was …

fix cookie handling

---

packages/lesswrong/server/analytics/postgresConnection.ts
packages/lesswrong/server/analyticsWriter.ts

To make migrations easier and safer, this PR adds the ability to configure a "mirror" database (really a second destination) so the analytics will stream to two places.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202571304226634) by [Unito](https://www.unito.io)

Add ability to have a mirror postgres DB

---

packages/lesswrong/components/users/UsersEditForm.tsx
packages/lesswrong/lib/collections/users/custom_fields.ts
packages/lesswrong/lib/collections/users/schema.ts
packages/lesswrong/server/vulcan-lib/mutators.ts

lesswrongteam let me know if you don't want this and I'll forum gate it. My argument in favor: most users who want to change their displayName also want to change their slug, many of them pretty strongly. Although I think it's reasonably to have a "formerly known as" field or something, I don't think using the slug is the right way to do it, and it should probably not be mandatory.
This PR also prevents admins from accidentally adding upper case letters to slugs, which is how I got started on this rabbit hole.
This leads to an error on the resetStore call, as apollo's attempt to rerun the `{slug: 'outdatedSlug'}` query will now fail. I decided I didn't mind the rare console error here, but I could be persuaded to find a more elegant solution. (I can't find anything in the apollo docs …

Update slug on displayName update

---

packages/lesswrong/lib/collections/posts/custom_fields.ts
packages/lesswrong/lib/collections/posts/fragments.ts
packages/lesswrong/lib/collections/sequences/helpers.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

Previously, if you were viewing a post in the context of a non-canonical sequence, and it was either the first or last post, trying to navigate to the previous/next post (i.e. crossing the boundary to another sequence in the collection) would take you to the post before it in its canonical sequence, rather than to the last/first post of the previous/next sequence in the contextual collection.  i.e. going "back" from `The Bottom Line`, in the Sequences Highlights (sequence: `Pitfalls of Human Cognition`) would take you to `One Argument Against An Army`, rather than `Twelve Virtues of Rationality` (as the last post of the `Thinking Better on Purpose` sequence).
This fixes that behavior.
Tested the matrix:
(first | middle | last sequence) x (first | middle | last post) x ("previous" | "next" …

fix navigation between posts in a non-canonical collection-sequence, and between those sequences

---

packages/lesswrong/lib/routes.ts
packages/lesswrong/lib/vulcan-core/appContext.ts
packages/lesswrong/lib/vulcan-lib/routes.ts
packages/lesswrong/server/apolloServer.ts
packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
packages/lesswrong/testing/routes.tests.ts

Makes it so that the server answers certain pageloads with a streaming response, sending part of the `<head>` block prior to doing server-side rendering. This allows the client to start downloading the main stylesheet and the Javascript bundle immediately, before SSR has started. If the client already has these cached this won't do anything, but if they don't (because this is their first visit since the last server version change), this will significantly speed up their pageload.
This is restricted to a handful of whitelisted pages (including the front page and `/allPosts`, but not including post pages) because this sort of streaming response has a nasty caveat: once you've started sending a response, you can't change your mind about the response's status code or http headers. So if a …

Preload stylesheet and bundle during SSR

---

packages/lesswrong/server/callbacks/userCallbacks.tsx

[Asana task](https://app.asana.com/0/628521446211730/1202473655524358/f)
We don't need a create hook here because the user is initially created without a display name, and then a display name is automatically set from the username chosen after being redirected back to the forum from auth0 (this will trigger the same update hook to make sure both the username and the display name are unique).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202671002894426) by [Unito](https://www.unito.io)

Enforce display name uniqueness when updating

---

packages/lesswrong/components/sequences/BooksItem.tsx
packages/lesswrong/components/sequences/CollectionsPage.tsx
packages/lesswrong/components/sequences/LargeSequencesItem.tsx
packages/lesswrong/lib/collections/books/fragments.ts
packages/lesswrong/lib/collections/books/schema.ts
packages/lesswrong/lib/collections/collections/fragments.ts
packages/lesswrong/lib/collections/collections/schema.ts
packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

[Asana task](https://app.asana.com/0/628521446211730/1202662252311003/f)
This PR implements 2 features for the intro curriculum collection page requested by Jesse:
* Showing chapter names
* Hiding the 'Start Reading' button
It's slightly inconsistent that one setting is 'show' whilst the other is 'hide'. In an ideal world they'd both match, but I choose to do it like this for the sake of backwards compatability with LW and so that we don't need to run a migration.
Showing chapter names:
Hiding the 'Start Reading' button:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202671022343464) by [Unito](https://www.unito.io)

Intro curriculum improvements

---

packages/lesswrong/components/sequences/LargeSequencesItem.tsx

This PR fixes some small spacing issues on the handbook page reported by Max on Slack. The changes are localised to the EA forum.

Fix text spacing on EA handbook page

---

packages/lesswrong/components/editor/EditorFormComponent.tsx

[Asana task](https://app.asana.com/0/628521446211730/1202410434172092/f)
Originally I thought this was a feature request, but it turned out to just be a bugfix.
`this.getStorageHandlers().reset` already clears the session storage, but we then call `this.setState` which triggers a callback chain and resets the value in session storage using the value cached by the editor. We can prevent this from happening by simply clearing the cached value to an empty string first.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202676768502606) by [Unito](https://www.unito.io)

Reset autosave after publication

---

packages/lesswrong/components/posts/PostsPage/PostsPageWrapper.tsx
packages/lesswrong/lib/utils/errorUtil.ts

Previously you got an app.operation_not_allowed error. Normal site behavior is to return 404 in these cases, usually to avoid leaking the information about whether a page by that name even exists. In our case, I think it's just a better user experience, though I could be convinced we should return a custom page. The current experience where you get an angry red error message in machine readable language I definitely don't like.

Return 404 on disallowed draft access

---

packages/lesswrong/components/sequences/BooksItem.tsx
packages/lesswrong/components/sequences/BooksProgressBar.tsx

Previously the BooksProgressBar was accidentally positioned above the subtitle, so it looked like this:
Now it looks like this instead:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202704024066734) by [Unito](https://www.unito.io)

BooksItem subtitle is above progress

---

packages/lesswrong/server/rss.ts

Co-authored-by: Will Howard <w.howard256+github@gmail.com>
User reported that setting a karma threshold of 125 on an exported RSS feed resulted in posts with >75 karma being included in the feed.  Seems like the karma threshold cutoffs hadn't been updated to account for the higher levels of karma available as selections for RSS feeds.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202710592412451) by [Unito](https://www.unito.io)

fix karma threshold rounding cutoffs.

---

packages/lesswrong/components/votes/VoteAgreementIcon.tsx

An old version of firefox displays the agreement voting UI weirdly. After experimenting a bit it looked like the offending span wasn't actually necessary (doesn't seem to change rendering on modern chrome browsers)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202692328890782) by [Unito](https://www.unito.io)

Fix firefox 91 voting ui bug

---

packages/lesswrong/lib/collections/sequences/helpers.ts

A user reported that post navigation was incorrect when going to the next post from "The Ritual": it was taking them to "Beginnings: An Introduction", which was the first post in the last book in R:A-Z, rather than "Minds: An Introduction", which was the first post in the correct "next" book.
Wrong behavior:
Correct behavior:
Also confirmed that none of the previous test cases from the first PR attempting to fix the navigation broke.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202710651780213) by [Unito](https://www.unito.io)

fix book ordering for post navigation within a collection

---

packages/lesswrong/components/editor/EditorTopBar.tsx
packages/lesswrong/components/posts/PostsEditForm.tsx

Part of the Collaborative editor feature was to change the phrase "Save Draft" to "Preview", which was meant to help convey that collaborative docs autosave. I personally find this confusing, because it is still totally a thing that I sometimes want to save drafts (which get logged as minor updates rather than patches, and which update the actual post document, which doesn't necessarily happen when autosaving in collaborative mode)
This PR reverts that, but also updates the "saved" text at the top of the page to say "Auto Saved", and with a hoverover saying a bit more about how collaborative editor autosaves. Also fixes unnecessary hover-highlight for the "saved" "button" which isn't really clickable. …

Switch preview back to save

---

packages/lesswrong/components/editor/LocalStorageCheck.tsx
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/themeType.ts

In response to a user having overlooked the restore-saved-content button (which is pretty subtle), make it more prominent. Screenshot:
This is against `lw-deploy` because in `master` the localStorage works differently (an on-page-load modal popup which is a little broken).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202673132004235) by [Unito](https://www.unito.io)

Make the restore-saved-content notice more prominent

---

packages/lesswrong/components/common/NavigationEventSender.tsx
packages/lesswrong/components/common/withGlobalKeydown.tsx
packages/lesswrong/components/hooks/useOnFocusTab.ts
packages/lesswrong/components/notifications/NotificationsMenu.tsx
packages/lesswrong/components/notifications/NotificationsMenuButton.tsx

Co-Authored-By: jpaddison3 <jp@centreforeffectivealtruism.com>
Makes it so that when you navigate or focus on a tab, it rechecks for notifications. This prevents spurious notifications if you open background tabs while you have an unread message and read the notification before visiting those tabs.
(Also fix in a missing dependency list on `useGlobalKeydown` because we initially had a bug caused by a missing dependency list and looked for instances of the same thing. In this case it doesn't matter much, just a few spurious event-handler attachments.)

Messages icon refreshes on navigate and focus

---

packages/lesswrong/components/common/NewFeatureTooltip.tsx
packages/lesswrong/components/tagging/SubscribeButton.tsx
packages/lesswrong/lib/components.ts

[Asana task](https://app.asana.com/0/628521446211730/1202391450244268/f)
This PR implements a "new feature" tooltip, which can be placed above, below, left or right of any particular component.
The usage on the `SubscribeButton` component is only an example for testing - I'll remove this before deploying.
I also tried an approach where we generate each of the `-left`, `-right`, `-top` and `-bottom` classes programatically, but this made the code a lot more complicated and a lot less readable. I think it's a lot easy to reason about if we just do it manually like this, even if it does mean updating a couple of different places when making changes.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202720109557676) by [Unito](https://www.unito.io)

New feature tooltip 2

---

packages/lesswrong/components/Layout.tsx

Logged in non-admin users currently still hold space for where the sunshine sidebar is supposed to be, which isn't the intended behavior (though looks like it's been this way for 2 years). This fixes it.
Correct layout when logged out: 
Wrong layout when logged in: 
After this PR: 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202718910210019) by [Unito](https://www.unito.io)

Fix sunshine layout

---

packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
packages/lesswrong/components/form-components/CoauthorsListEditor.tsx
packages/lesswrong/components/posts/PostSubmit.tsx
packages/lesswrong/components/posts/PostsTitle.tsx

The existing tooltips on the edit post form around adding co-authors was outdated and confusing, so we made a small improvement. I think this is still kind of confusing so we should revisit how to explain this complicated feature here in the future.
Also on the EA Forum user profile, we now show the user's scheduled posts under their drafts.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202720109303159) by [Unito](https://www.unito.io)

improve co-author feature tooltip, [EA Forum only] list future posts in user profile

---

packages/lesswrong/components/tagging/TagPage.tsx

Fixes #5108
Co-Authored-By: Jonathan Mustin <jmustin@centreforeffectivealtruism.com>

Don't add sortedBy=null to URL when clicking on tag page ToC

---

packages/lesswrong/components/common/TabNavigationMenu/TabNavigationItem.tsx
packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
packages/lesswrong/components/localGroups/TabNavigationEventsList.tsx
packages/lesswrong/lib/abTests.ts
packages/lesswrong/themes/forumTheme.ts
packages/lesswrong/themes/themeType.ts

The left sidebar of the front page shows nearby events, but it's not very useful because you can't look at it and tell whether the events are near you and on a day when you'll be free. This PR redesigns the sidebar so that there are now two lines per event rather than one, with the second line showing the city name and the date.
This is set up as an A/B test; half of users will see no change, half of users will see the modified version. I'll consider it successful if people in the modified-sidebar group click through and RSVP to events at a noticeably higher rate. (Reminder, you can see and override your A/B test groups by going to `/abTestGroups`)
In addition, for LW only (other forums not affected), this changes the order of some sidebar items, tweaks padding and icon sizes, and removes …

Two-line version of events sidebar and restyle LW sidebar

---

packages/lesswrong/components/messaging/MessageItem.tsx
packages/lesswrong/components/messaging/ProfilePhoto.tsx
packages/lesswrong/lib/collections/messages/fragments.ts
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

This PR adds profile photos to private message threads, on the EA Forum only. Perhaps most controversially, it adds a placeholder icon for users without a photo, since the alternatives felt either clunky UI-wise or too involved to be worth the effort.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202730790513560) by [Unito](https://www.unito.io)

[EA Forum only] Add profile images to private messages

---

packages/lesswrong/components/votes/VoteArrowIcon.tsx

Causes bug in both animation and stuff tooltips on firefox android, just removing the element for now, will allow for proper fix later

disable buggy tooltip wrapper

---

packages/lesswrong/components/votes/VoteArrowIcon.tsx

This should fix the issue. I didn't have time to dig into exactly why this broke it in the first place, but this is probably worth investigating at some point. My general feeling is that if a component is broken by wrapping it in `({ children }) => children` then there's probably something fishy going on in that component that should be rectified.

Fix vote animations

---

packages/lesswrong/components/comments/CommentsListSection.tsx
packages/lesswrong/components/posts/PostsPage/PostsPagePostFooter.tsx
packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
packages/lesswrong/components/tagging/AddPostsToTag.tsx
packages/lesswrong/components/tagging/AddTagButton.tsx
packages/lesswrong/components/tagging/TagPageButtonRow.tsx

Hides various bits of UI from the print view that don't make sense to have on a printed page.

Hide various buttons and UI from the print view

---

packages/lesswrong/components/comments/CantCommentExplanation.tsx
packages/lesswrong/lib/collections/posts/custom_fields.ts
packages/lesswrong/lib/collections/posts/fragments.ts
packages/lesswrong/lib/collections/users/helpers.tsx
packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

for this issue: https://github.com/ForumMagnum/ForumMagnum/issues/5344
The following features already existed:
* the ability to lock comments on a post completely
* the ability to lock replies to a comment completely until a certain date
so I have just added the ability to block replies on a post to accounts created after a certain date (any date, not necessarily the createdAt date of the post). I could also add the same thing to individual comments fairly easily if anyone thinks that would be useful
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202725388297843) by [Unito](https://www.unito.io)

Add ability to lock post comments to new accounts

---

.gitignore
build.js
jest.config.ts
packages/lesswrong/client/autoRefresh.ts
packages/lesswrong/lib/executionEnvironment.ts
packages/lesswrong/lib/routeUtil.tsx
packages/lesswrong/server/apolloServer.ts

This allows multiple instances of the site to be run locally on different ports (needed whilst developing LessWrong/EAForum crossposting).
For instance, you can run a second instance on port 4000 with a local database with: `SERVER_PORT=4000 MONGO_URL="mongodb://localhost:27017/eaforum" ./build.js -run -watch --settings ../ForumCredentials/lw-settings-dev.json`
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202791329591921) by [Unito](https://www.unito.io)

Allow running the site on a different port in dev mode

---

packages/lesswrong/components/sequences/BooksItem.tsx
packages/lesswrong/components/sequences/BooksProgressBar.tsx
packages/lesswrong/lib/collections/books/fragments.ts
packages/lesswrong/lib/collections/books/schema.ts
packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

This allows you to create books that use the old SequencesGrid layout, and toggle off the progress bar. This is primarily to enable a "further reading" section that feels distinct from most of the collection, but it seemed good to design it in such a way it could be applied to other problems we might run into.
Here's an example of what the UI could look like:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202720213880637) by [Unito](https://www.unito.io)

Book item sequence grid

---

packages/lesswrong/server/scripts/mergeAccounts.ts
scripts/mergeUsers.sh

We received a request from a user to merge some accounts.  On checking the migration script, discovered that quite a few collections were missing.  Before running it, would appreciate a sanity-check on the added collections (and on those we're specifically not merging, i.e. `LWEvents` and `GardenCodes`).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202774083246896) by [Unito](https://www.unito.io)

update migration script

---

.platform/nginx/nginx.conf

The CDN I am testing (Cloudfront) requires the `gzip_proxied: any` directive to serve compressed files (see [here](https://iwader.co.uk/post/enabling-gzip-compression-on-nginx), it's actually the inclusion of the "via" header which causes nginx to drop compression, this may apply to other CDNs too)
NOTE: I have not tested this, and I am aware that it's slightly dodgy to deploy an nginx config change without testing it first, but I think this one is simple enough that it's unlikely to cause any problems. I am going to set up a non-master test environment to test brotli compression and some other things anyway, so if you're not happy with deploying this then I can wait and test it there first. It's just that that will take a while to set up and I wanted to get the basic setup working right …

Edit nginx.conf to allow proxies to use gzip

---

packages/lesswrong/components/sequences/BooksItem.tsx
packages/lesswrong/lib/collections/books/fragments.ts
packages/lesswrong/lib/collections/books/schema.ts
packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

Jim had left a comment about this which I meant to address but forgot in this PR: https://github.com/ForumMagnum/ForumMagnum/pull/5391
> Nitpick: This field name is a noun phrase, but it should be a verb phrase because it's a flag. A correct name would be something like showAsGrid or displaySequencesAsGrid.
> (This is one of the unwritten conventions that fails to show up in style guides because it's hard to articulate, but which most programmers pick up linguistically.)

Change sequencesGridDisplay to displaySequencesAsGrid

---

packages/lesswrong/components/common/HeadTags.tsx

Twitter cards have been broken since [this deployment](https://github.com/ForumMagnum/ForumMagnum/pull/5358), our (me and jimrandomh ) best guess was that our `meta` tags are actually correct but something about the ordering or page load time is confusing the twitter web crawler.
While I had an Elastic Beanstalk environment set up to test other stuff I thought I may as well try and fix it, and it seems like reordering the tags has done so 🤷‍♂️. I'm not that confident in this because the twitter card validator was also getting confused by the SSL certificate of my test env so I couldn't get reliable results, but here is one example of it working with this change
From test environment (card appears, even though it's a new post):
From production (cards don't appear for posts newer than a few …

Change order of twitter card header

---

packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx
packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/server/callbacks/commentCallbacks.ts
packages/lesswrong/server/callbacks/postCallbacks.ts
packages/lesswrong/server/callbacks/userCallbacks.tsx

I wanted to remove the duplicate bio before deploying, but also did a light code review and cleaned up some other things.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202803251988291) by [Unito](https://www.unito.io)

remove duplicate bio in sunshine user info component

---

packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
packages/lesswrong/lib/analyticsEvents.tsx
packages/lesswrong/lib/collections/users/recommendationSettings.ts
packages/lesswrong/server/recommendations.ts

On LessWrong, as part of the epistemics marathon, we are temporarily changing recommendations to focus on rationality content.
Also updating the analytics contexts in the recommendations section.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202804002332672) by [Unito](https://www.unito.io)

Filter recommendations to return only rationality content on LessWrong

---

packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
packages/lesswrong/components/sequences/CollectionsItem.tsx
packages/lesswrong/components/sequences/LWCoreReading.tsx

A previous PR to display the Sequences Highlights on frontpage accidentally broke the mobile display for the library page, which users the same component. (It was important for the frontpage display to hide the collection description on mobile, but we don't want that behavior in the library) 
This changes the mechanism for hiding it. I've done a resize test on both home page and /library.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202811052590828) by [Unito](https://www.unito.io)

Fix hidden descriptions on mobile library

---

packages/lesswrong/components/sequences/BooksProgressBar.tsx
packages/lesswrong/components/sequences/SequencesSmallPostLink.tsx

The collections page progess bars are currently using the "light" colour palette. Max has requested for the EA forum to use the "main" colour palette instead. LessWrong is unaffected.

Use a darker color palette for progress bars on the EA forum

---

packages/lesswrong/components/Layout.tsx

Parens were wrapped around the wrong clause, 'tis fixed now.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202818145434940) by [Unito](https://www.unito.io)

Fix AF sunshineSidebar conditional

---

packages/lesswrong/components/editor/EditorFormComponent.tsx
packages/lesswrong/components/form-components/WrappedSmartForm.tsx
packages/lesswrong/components/sequences/LargeSequencesItem.tsx

A couple of weeks ago we added the ability to show chapter titles on the collections page for the new EA intro curriculum. After some discussion on Slack, Max and Jesse decided they wanted to change the way this works a little to make the titles use styling like the sequences page, instead of using the chapter description to get bold/italic text. This is implemented in this PR.
Whilst testing this, I also realised that it's not currently possible to set the body of an editable field (posts/chapter descriptions/etc.) to an empty string, so that's also implemented in this PR - let me know if there's any reason that this is a bad idea.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202802357058115) by [Unito](https://www.unito.io)

Better chapter titles

---

packages/lesswrong/lib/collections/posts/helpers.ts

Closes #5437 
I _think_ this should fix the issue, but I'd really appreciate if somebody (darkruby501 perhaps?) could test this out against the LW database at some point as the only way I was able to reproduce the bug was by manually breaking a post directly in the database. It is possible that the cause could actually be something else.
Interestingly, it already works correctly [on GreaterWrong](https://www.greaterwrong.com/posts/bJ2haLkcGeLtTWaD5/welcome-to-lesswrong).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202802328286855) by [Unito](https://www.unito.io)

Fix coauthors erroneously showing as pending

---

build.js
packages/lesswrong/server/apolloServer.ts

Statically compress the client bundle just after it is built when running in production, then check for this compressed version when serving the file. This gets it down from 2.1MB to 1.6MB.
Very long explanation of why I'm doing it this way:
"But Will," I hear you cry, "weren't we going to use a CDN to do the brotli compression for us? Thus compressing every response without requiring any code changes". Yes that was the plan, and some CDNs do claim to do brotli compression for you, but:
* There is only one which will actually _convert_ gzip to brotli, Cloudflare (based on [this](https://community.cloudflare.com/t/compression-with-gzip-and-brotli/297664)), and it's not suitable because it only caches based on file extension not MIME type
* From testing on Cloudfront it seems like it's …

Brotli compress bundle.js

---

packages/lesswrong/components/sequences/LargeSequencesItem.tsx

Jesse requested less margin on chapter titles on the collections page:
Before/after:

Less margin on collections page chapter titles

---

packages/lesswrong/lib/collections/sequences/helpers.ts

Reported by Lizka. When a sequence is not in a collection, `canonicalCollectionSlug` will be undefined and `getSequenceCollectionBooks` will fetch a random collection. This can currently be seen on https://forum.effectivealtruism.org/s/JuwQwdLugR63ux2P8/p/dYiJLvcRJ4nk4xm3X which links to the EA handbook as the next post, despite not being in a relevant sequence.

Fix sequence links for sequences that aren't in collections

---

packages/lesswrong/components/notifications/NotificationsMenu.tsx

Fixes a bug introduced in https://github.com/ForumMagnum/ForumMagnum/pull/4769 which caused the private-messages-count badge in the notifications drawer to disappear a ~second after the drawer is opened.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202804002860037) by [Unito](https://www.unito.io)

Fix new-private-messages-count badge from disappearing after the notification drawer is opened

---

packages/lesswrong/components/notifications/NotificationsMenu.tsx

Corresponds to this Sentry error: https://sentry.io/organizations/lesswrong/issues/3479588959/?project=1301611&query=is%3Aunresolved&statsPeriod=14d
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202803941048646) by [Unito](https://www.unito.io)

Fix keyboard-shortcut handling of the notifications menu drawer close button

---

packages/lesswrong/components/common/withDialog.tsx

I'm not sure what this line's purpose was, but it prevents modals from closing.

HOTFIX remove line that prevents modal closing

---

packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx

This makes the new permissions buttons in the sunshine sidebar a bit more aesthetic/convenient, and makes the snooze10 button more prominent.
Also, reverses the order of the tags on new-post-items, so that the hoverovers aren't as annoying when I'm trying to move my cursor to the middle of the hoverover.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202834851431261) by [Unito](https://www.unito.io)

Styling improvements for New User and New Post in sunshine sidear

---

packages/lesswrong/server/zohoUtils.ts

Seems like the EAGx events are in separate modules, so we need to query those when looking for EAG application data to import.

[EA Forum only] check EAGx events when importing your profile

---

packages/lesswrong/components/Layout.tsx

This cleans up the conditional rendering Layout, with the convention that seems least-bad to me.
I think forum-specific rendering often ends up getting particularly cluttery, and conditional rendering gets cluttery. I think generally as soon as you end up with 2+ clauses in a condition, that condition should be moved out into a separate variable or function.
This also standardizes on "renderX" instead of a mix of "renderX" and "showX" (at least in this particular file)

Conditional rendering refactor in Layout

---

packages/lesswrong/components/posts/PostsListSettings.tsx
packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsList.tsx
packages/lesswrong/lib/collections/posts/custom_fields.ts

This branch has two improvements to curations on the EA forum after talking with Lizka.
First, it restricts the ability to approve curated posts to admins (sunshine regiment can still suggest), and second, it adds a "curated" option to the all posts page settings (like on LessWrong):
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202859247143411) by [Unito](https://www.unito.io)

Curation improvements

---

packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsList.tsx

Request from Lizka to always show curation suggestions at the top of the side bar on the EA forum. The current behaviour is to show it below the fold if a post has been curated in the last 2.5 days.

Always show curated suggestions at top of sidebar on EA forum

---

packages/lesswrong/components/posts/PostsAnalyticsPage.tsx
packages/lesswrong/components/shortform/ShortformPage.tsx

Changes the Shortform page and the post analytics page.

Remove notices about two features being new now that they are no longer new

---

yarn.lock

Co-authored-by: jimrandomh <jim@jimrandomh.org>
Probably someone accidentally committed this line from the master lockfile.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202793756313071) by [Unito](https://www.unito.io)

Remove erroneous yarn lock record for ckeditor bundle

---

packages/lesswrong/components/editor/PostSharingSettings.tsx

Fixes the lw-deploy branch in preparation for end of Great Divergence. Previously there was a hard-coded reference the lw team email.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202859246964891) by [Unito](https://www.unito.io)

Use moderation email setting in sharing setting notice

---

packages/lesswrong/components/localGroups/CommunityMap.tsx
packages/lesswrong/components/seasonal/HomepageCommunityMap.tsx
packages/lesswrong/themes/defaultPalette.ts

Previously the map looks like this:
I don't like a couple things about this:
1. The individual-pins mostly aren't relevant and blow out everything else. 
1. The individual pins also feel bigger than they need to be.
1. When lots of pins are near each other, I can't tell how many there are, they look like a giant blob
1. The individuals and events are the same color(ish) and hard to tell apart.
When you turn off individuals, it looks like this:
This PR:
– changes the color of individuals
– makes individuals into a smaller icon
– hides individuals by default on the frontpage
– perhaps controversially, adds some translucency to icons so that when multiple of them are stacked on top of each other, there's more visual cue about the density being higher. (note: I slightly increased the opacity …

Make map use three different colors

---

packages/lesswrong/components/common/TabNavigationMenu/EventsList.tsx

This used to be like 3, and I think went up to 4 during the pandemic due to some weirdness in how online events worked. I have no idea how it got up to 7, that seems like a silly number.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202859889525580) by [Unito](https://www.unito.io)

Reduce count of events in sidebar

---

packages/lesswrong/components/recommendations/CuratedContentItem.tsx
packages/lesswrong/themes/createThemeDefaults.ts

Currently the close button on the spotLight item doesn't work because it's lower z-index than the overall card. This fixes that.

fix zIndex on close button on spotlight item (curatedContentItem)

---

packages/lesswrong/components/community/modules/LocalGroups.tsx
packages/lesswrong/components/localGroups/CommunityHome.tsx
packages/lesswrong/components/localGroups/CommunityMap.tsx
packages/lesswrong/components/localGroups/CommunityMapWrapper.tsx
packages/lesswrong/components/seasonal/HomepageCommunityMap.tsx

Adds a "showGroupsByDefault" field to the map, which is true by default to match existing usage but can be overridden. Changes the HomepageCommunityMap to only show events, and use the default map positioning which looks nicer.
Leaves in the request for user's location because we want to nudge people to opt into that this week.

Don't zoom or show groups on HomepageCommunityMap

---

packages/lesswrong/server/vulcan-lib/apollo-server/authentication.tsx

ACX Meetup Organizer accounts were created with an `email` field, but the existing password reset functionality only checks the `emails[].address` field.  This means that organizers who had accounts created for them are unable to recover those accounts.
This is a patch to check both fields.  Long-term, we should migrate away from the `emails` field entirely.

check email field for password resets

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/seasonal/HomepageCommunityMap.tsx
packages/lesswrong/lib/collections/users/custom_fields.ts

Primarily pass in the props for showing the hide map button frontpage map (and hide it when it is set)
plus clean up some unused fields in user site customizations

Adds hideMap button to frontpage map (plus site customization clean up)

---

packages/lesswrong/components/messaging/NewConversationButton.tsx
packages/lesswrong/lib/collections/conversations/collection.ts

I noticed that the "Message" button was no longer appearing in user profiles when logged out, so I fixed it
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202873082540888) by [Unito](https://www.unito.io)

message button should appear for logged out users

---

packages/lesswrong/components/localGroups/CommunityMap.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202879502405576) by [Unito](https://www.unito.io)

Fix white-on-white text in the community map popup in dark mode

---

packages/lesswrong/components/common/MaintenanceBanner.tsx
packages/lesswrong/components/ea-forum/EAHome.tsx
packages/lesswrong/components/ea-forum/MaintenanceBanner.tsx
packages/lesswrong/components/form-components/TagSelect.tsx
packages/lesswrong/lib/components.ts

I ended up making it non-dismissable for simplicity's sake, seeing as JP said we should only show it for a few hours before a short maintenance window anyway
There are 3 server settings you can set to make it show up:
* showMaintenanceBanner: boolean - it won't appear without this
* maintenanceBannerTime: string (which can be parsed by new Date(...), e.g. '2022-08-30T10:54:00Z') - the time at which the maintenance is scheduled, it won't appear if this is not set, or if the current time is more than 5 minutes after this
* maintenanceBannerExplanationText: string - arbitrary string to add to the end of the message, ", we anticipate this will take around 30 minutes" in the screenshot, optional …

Add maintenance banner

---

packages/lesswrong/components/common/LoadMore.tsx
packages/lesswrong/components/hooks/useIsFirstRender.tsx

I did this fix because I've got an inkling that it might be a/the cause of a more complex bug I'm trying to figure out. It'll also be nice to get rid of these nasty console errors though. I'm not 100% sure that this is the cause of _all_ the hydration errors we have, but it does seem to fix all of the ones that I can easily reproduce on localhost.
The bug itself is dependant on SSR time, so in order to reproduce locally you may need to slow down your local server. This can be done easily by adding `await new Promise(resolve => setTimeout(resolve, 5000));` to `server/vulcan-lib/apollo-ssr/renderPage.tsx` at line 176 before we create `App`.
The issue is that we fetch data from the DB during SSR and render it, then once we're on the client we refetch the data over the network. This means …

Fix hydration errors related to 'load more' button

---

scripts/runProduction.sh

Make this truly enormous, since possibly heap snapshots use the node heap itself!  Only for use on r6i.large instances, which have 16gb ram.

Max old space size12800

---

packages/lesswrong/components/Layout.tsx

Removes usage of `isMobile` which seems to be the problem. Replaces with breakpoints.

Fix frontpage mobile homepage map ui bug

---

packages/lesswrong/components/common/ErrorAccessDenied.tsx
packages/lesswrong/components/editor/PostCollaborationEditor.tsx
packages/lesswrong/components/users/WrappedLoginForm.tsx

Previously the access denied pages were a bit of a mess on the lw-deploy branch, when viewed on the EA Forum view. The main issue was that there was no width to contain the login buttons, so they flexed across the whole dang page. Now we add a max width. While we're at it, replace some div'd text with Typography.
I also addressed my own PR comment and combined the access denied message in PostCollaborationEditor with ErrorAccessDenied.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202873012790743) by [Unito](https://www.unito.io)

Fix access denied styling

---

packages/lesswrong/lib/collections/posts/schema.tsx

This is the agree-disagree voting system. Has been discussed on slack.
I've left the default for new Forums as non-two axis, I could be persuaded that we should default all Forums to use two-axis, but ¯\\\_(ツ)_/¯

Enable two axis voting on the EA Forum

---

packages/lesswrong/components/alignment-forum/AFLibraryPage.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/routes.ts

It used to work fine for AF to share a library with LW, but when I added the new hardcoded collections on LW I forgot to ensure they didn't appear on AF.
This PR adds a new AFLibraryPage component so they can afford to move in different directions. (I weakly think this is preferable to adding a forum-gate within a single Library page, but could be argued otherwise)

Add AFLibraryPage [Alignment Forum only]

---

packages/lesswrong/server/callbacks/alignment-forum/alignmentCommentCallbacks.ts
packages/lesswrong/server/callbacks/commentCallbacks.ts
packages/lesswrong/server/migrations/2021-04-28-populateCommentDescendentCounts.ts
packages/lesswrong/server/utils/commentTreeUtils.ts

Fix a memory leak which periodically kills causes LW server instances to die, causing 504s. The problem is that `updateParentsSetAFtrue` can recurse infinitely if searching for a null `parentCommentId` returns a result, leaking at a rate of one stack-frame per mongodb roundtrip until the process dies.
Fix rewrites `updateParentsSetAFtrue` (and `updateChildrenSetAFfalse`, which was right next to it and looked a little sketchy) to use preexisting, safer utility functions for getting the comment ancestor-chain and descendents. (Then moves those utility functions into a new file to break an import-cycle, and armors `getCommentAncestorIds` against the possibility of parent-comment-reference cycles in the database.)
This bug was introduced in …

Fix memory leak in AF setting/clearing functions

---

packages/lesswrong/server/notificationCallbacks.tsx

I'm just sending the standard "new message" notification because this is much simpler than creating a whole new notification type, lmk if you think it would be worth adding a new notification
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202927039940203) by [Unito](https://www.unito.io)

Send notification when added to conversation

---

packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx

We had removed them during ACX Everywhere. Returning them now, and adding a little spacing to help distinguish curated from recommendation posts.

Return recommendations to lesswrong

---

packages/lesswrong/server/apolloServer.ts

We send the start of the page with `<script defer src="/js/bundle.js...` before rendering the whole page so the browser starts downloading bundle.js straight away. At some point nginx started buffering this bit of the response so this stopped working so the browser had to wait for the whole page to load, this fixes it (I have tested in Elastic Beanstalk)
I think the proximate cause of this breaking was [this](https://github.com/ForumMagnum/ForumMagnum/pull/5447) change to allow compression, in that if I remove the header that allows compression it also stops nginx from buffering. Although I did test that at the time and confirmed that it was still working... I would guess the full explanation is something like "nginx buffers up to x bytes, and the compression change plus something else …

Disable nginx buffering for pages with prefetching

---

jest.config.ts
package.json
yarn.lock

Currently, any errors that are thrown in Jest tests are reported with incorrect line numbers. This happens because Jest doesn't use our tsconfig, but instead transpiles TS to JS using `esbuild-jest` which uses `babel`, and this isn't configured to create sourcemaps. Changing this configuration is simple, but unfortunately `esbuild-jest` [needs to set](https://github.com/aelbore/esbuild-jest/blob/daa5847b3b382d9ddf6cc26e60ad949d202c4461/src/index.ts#L25) the `sourceContent` setting in `esbuild` which, due to [a bug](https://github.com/evanw/esbuild/issues/682), isn't publically exposed in older versions, so we need to upgrade.
I've tested dev builds and prod builds and I can't find any regressions from the upgrade, but let me know if you think there's anything else that we might need to …

Fix incorrect line numbers in test errors

---

packages/lesswrong/components/ea-forum/users/EAGApplicationImportForm.tsx
packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
packages/lesswrong/components/posts/DraftsList.tsx
packages/lesswrong/components/users/ReportUserButton.tsx

1. Removes the 50 karma threshold for the "Report user" button appearing on user profiles, based on Lizka's suggestion
2. Fixes the EA Forum profile drafts list to use the profile user rather than the current user
3. Hides the CKEditor fields in the EAG import form for now, to make the rest of the form functional until I have time to implement a proper fix for those fields

a few small fixes, mostly EAF only

---

packages/lesswrong/components/tagging/TagSubforumPage.tsx

We will want to show them on staging, and, for better or for worse, staging has `isProduction` set to true. I've checked, and there are no topics on production that have the `isSubforum` flag set to true.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202967649332943) by [Unito](https://www.unito.io)

Remove dev-gating of Subforums

---

packages/lesswrong/components/common/Home2.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionFeed.tsx

This existed for LW already, this just makes it generic
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202969162734416) by [Unito](https://www.unito.io)

Track when Recent Discussion is scrolled into view

---

packages/lesswrong/lib/collections/posts/constants.ts
packages/lesswrong/lib/collections/posts/helpers.ts
packages/lesswrong/server/search/utils.ts

Previously: due to our algolia paragraph splitting, our code had to do some jiu-jitsu to get all the paragraphs it wanted to delete, when it tried to remove a post from algolia. That fanciness started failing apparenly, and we were not removing spam posts from algolia.
Turns out you can avoid that fanciness by typing `distinct: false` into your algolia query. Algolia will now return all the paragraphs, and then you can just delete them all.
While writing this we discovered: https://github.com/ForumMagnum/ForumMagnum/issues/5641, but declined to fix it at the same time as we ran out of pairing time and that one is much less important.
Coauthored with Jim.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202950551000154) by …

Fix deletion of multi-paragraph posts from Algolia

---

packages/lesswrong/server/fmCrosspost/crosspost.ts
packages/lesswrong/server/fmCrosspost/resolvers.ts

Relevant Slack thread: https://app.slack.com/client/T3ERD8FQT/C75BWSNBH/thread/C75BWSNBH-1663086521.834869
Adds a user-agent to crossposting API requests. This is something we want anyways (because it makes the requests distinctive in logs/Sentry), but also maybe works around a problem with an overzealous AWS firewall config.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202975927639748) by [Unito](https://www.unito.io)

Add user-agent to crossposting API requests

---

packages/lesswrong/lib/collections/tags/schema.ts
packages/lesswrong/server/callbacks/commentCallbacks.ts
packages/lesswrong/server/resolvers/tagResolvers.ts

This is something I missed in #5638
I am fairly soon going to make it so that subforum comments _do_ show up in recent discussion for members of the subforum, which will probably involve refactoring this. But this is more important so it makes sense to merge it straight away
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202976031445303) by [Unito](https://www.unito.io)

Stop subforum comments from showing up in recent discussion

---

packages/lesswrong/components/form-components/sortableList.tsx

Addressing the [lint error](https://github.com/ForumMagnum/ForumMagnum/runs/8261432218?check_suite_focus=true).  I think this is a bug in eslint; Typescript itself has no problem recognizing them as valid imports in the same import from that module (without splitting out the separate `import type` for the two types).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202955236615244) by [Unito](https://www.unito.io)

fix sortable list typing

---

packages/lesswrong/components/editor/PostCollaborationEditor.tsx
packages/lesswrong/components/editor/PostSharingSettings.tsx
packages/lesswrong/components/posts/PostsEditForm.tsx
packages/lesswrong/lib/collections/posts/helpers.ts
packages/lesswrong/lib/notificationTypes.tsx
packages/lesswrong/server/ckEditor/ckEditorCallbacks.ts

This fixes some permissions-issues and confusing redirects that surround collaborative editing.
There are two pages for editing posts – the PostsEditForm and the PostCollaborationEditor. The former is for people who have the permission to edit all the other post-related fields (i.e. post authors and admins). The latter is for people who've been shared on the post for collaborative editing (and doesn't allow for the ability to actually submit changes so they appear publicly)
The goal here is that:
1. Whenever you should have full edit permissions on a post, you should always get redirected to /editPost. 
1. Whenever you don't have full edit permissions on a post, you get redirected to /collaborateOnPost …

Clean up collaborateOnPost redirect/permissions bugs

---

packages/lesswrong/components/comments/CommentOnPostWithReplies.tsx
packages/lesswrong/components/comments/CommentPermalink.tsx
packages/lesswrong/components/comments/CommentWithReplies.tsx
packages/lesswrong/components/comments/CommentsNode.tsx
packages/lesswrong/components/comments/CommentsTimeline.tsx
packages/lesswrong/components/comments/CommentsTimelineSection.tsx
packages/lesswrong/components/common/withRecordPostView.tsx
packages/lesswrong/components/review/ReviewPostComments.tsx
packages/lesswrong/components/shortform/ShortformThreadList.tsx
packages/lesswrong/components/tagging/SubforumCommentsThread.tsx
packages/lesswrong/components/tagging/TagSubforumPage.tsx
packages/lesswrong/lib/collections/comments/views.ts
packages/lesswrong/lib/components.ts
packages/lesswrong/server/callbacks/commentCallbacks.ts

This fixes the following bugs:
* lastSubthreadActivity and descendentCount were not being set correctly on comments due to using rawUpdateOne instead of rawUpdateMany
* In the subforum discussion section it was possible for a reply to appear as a top level comment as we were just sorting by postedAt. This changes it to sort only the top comments by postedAt and use CommentWithReplies to render the replies
I was also planning to add an option for sorting by recent discussion in the subforum, this will involve fixing the problem of comment threads jumping to the bottom whenever you reply to them. The `CommentWithReplies` change turned out to be big enough that I think it's worth splitting that into a separate PR …

Refactor subforum discussion section for loading many comments + fix bugs in setting lastSubthreadActivity and descendentCount

---

packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts
packages/lesswrong/server/editor/make_editable_callbacks.ts

A recent PR (I think #5654?) made some changes relating to createdAt, but I think didn't run `yarn run generate`. This PR just does that without worrying about introducing any other features.
It seems to introduce some errors I haven't thought through yet.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202986379706705) by [Unito](https://www.unito.io)

Run yarn-run-generate for the new createdAt setup

---

packages/lesswrong/components/editor/EditorTopBar.tsx
packages/lesswrong/server/fmCrosspost/tokens.ts

Changed the presence list to have a maximum number of shown users, so it doesn't explode when there's lots of them. Also cleans up styling in other minor ways.
Here are two screenshots with four users:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202991651098846) by [Unito](https://www.unito.io)

Fix presence list large number of users

---

packages/lesswrong/components/common/MixedTypeFeed.tsx
packages/lesswrong/components/hooks/useOrderPreservingArray.test.tsx
packages/lesswrong/components/hooks/useOrderPreservingArray.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionFeed.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionTag.tsx

This adds a hook `useOrderPreservingArray` to keep elements that have already been returned in the same order on refetch, and uses it in the Recent Discussion section on the front page so you can reply to comments without the post jumping to the top
The main purpose of this is to do the same thing in the subforum discussion section, but that is waiting on #5676 being merged
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202985086843718) by [Unito](https://www.unito.io)

Add useOrderPreservingArray hook and fix recent discussion jumping when you reply

---

packages/lesswrong/components/messaging/NewConversationButton.tsx
packages/lesswrong/components/sunshineDashboard/SunshineSendMessageWithDefaults.tsx

I had accidentally put the moderator flag into all new conversations, instead of just ones from the sunshine sidebar, which broke non-admin ability to message users. This fixes it so it's only passed in from the sunshine sidebar.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202998772001881) by [Unito](https://www.unito.io)

Fix moderator validation bug

---

packages/lesswrong/components/editor/PostCollaborationEditor.tsx
packages/lesswrong/components/posts/MoveToDraft.tsx
packages/lesswrong/components/posts/PostsEditForm.tsx
packages/lesswrong/components/posts/PostsPage/PostActions.tsx
packages/lesswrong/lib/collections/posts/collection.ts
packages/lesswrong/lib/collections/posts/helpers.ts
packages/lesswrong/server/ckEditor/ckEditorCallbacks.ts

The full version (with metadata) and the collaborative version (body only) of the post editor redirect to each other, reflecting whether you have sufficient permissions to edit the metadata or not. However the redirect conditions didn't always match, which can cause a redirect loop (seen here: https://sentry.io/organizations/lesswrong/discover/lesswrong:d15779b356e3442d837c0e5de83e16b0/?environment=production&field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1301611&query=&sort=-timestamp&statsPeriod=24h&yAxis=count%28%29). Change the redirect condition in `PostsEditForm` to use the recently introduced `canUserEditPost` utility function, making it match the redirect in the other direction.
NOTE: The previous change gave explicitly-shared …

Fix redirect loop in the editor for secondary authors

---

packages/lesswrong/server/fmCrosspost/requestHandlers.ts

Crossposting is currently failing with the error `app.validation_error`. After digging into it deeper, it turns out that this is because `posts.userId` is defined in the schema as only being insertable by admins (it usually gets set by a callback after validation), so it fails when the account we crosspost _to_ is not an admin (we did test with a mix of admin/non-admin accounts, but evidently we only posted _from_ non-admins, not _to_ non-admins).
We could just adjust the schema to account for this, but my feeling is that it's better to just disable the validation here. This should be safe, since this code path is inside one of the API calls and we've already done a _ton_ of manual validation before we get here - if anything's not right, we'll have aborted already.
My main worry with …

Disable createMutator validation when creating a crosspost

---

packages/lesswrong/components/form-components/MuiTextField.tsx

Current our form component converts falsey values into an empty string. This PR fixes this for the case of "0" integers. It is plausible we should fix it in some more general way but I'm not sure what work the conversion was doing that I might accidentally break.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203034020537487) by [Unito](https://www.unito.io)

Properly display "0" for number input fields

---

packages/lesswrong/components/editor/Editor.tsx

Bug introduced in: https://github.com/ForumMagnum/ForumMagnum/commit/f0cb371a81e0bfc89eb4fc158183612871e44bd9
Caused by a subtle timing interaction between rerenders causing CkEditor to update its contents, and CkEditor onChange events reporting state changes. Deferring setValue() can cause exogenous editor changes to get reverted.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202950500656787) by [Unito](https://www.unito.io)

Fix a bug that caused editors in forms to not clear if submitted during the autosave delay window

---

packages/lesswrong/components/ea-forum/EventBanner.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203043665804550) by [Unito](https://www.unito.io)

Event banner: get higher resolution images because retina

---

packages/lesswrong/components/votes/AgreementVoteAxis.tsx

The tooltip for the disagree button has the wrong text on it.
Fixed:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203050632407304) by [Unito](https://www.unito.io)

fix tooltip text for disagree button

---

packages/lesswrong/components/ea-forum/EventBanner.tsx

I can't believe I wrote that bug.
Problem: we change the display of the homepage event banner based on a render-time setting.get() call. But we get the image ID from an initialization-time setting.get(). Thus image ID will only change on deploys, but the display of the banner will change ~5 minutes after the setting is updated in the DB.
This converts everything to be render-time, meaning we can deploy banner updates without deploys.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203043780289044) by [Unito](https://www.unito.io)

Event banner: Get event image setting on render to allow for db setting updates

---

packages/lesswrong/components/spotlights/CurrentSpotlightItem.tsx
packages/lesswrong/components/spotlights/SpotlightEditorStyles.tsx
packages/lesswrong/components/spotlights/SpotlightItem.tsx
packages/lesswrong/components/spotlights/SpotlightsPage.tsx
packages/lesswrong/lib/collections/spotlights/collection.ts
packages/lesswrong/lib/collections/spotlights/fragments.ts
packages/lesswrong/lib/collections/spotlights/schema.ts
packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts
packages/lesswrong/lib/generated/viewTypes.ts
packages/lesswrong/server/spotlightCron.ts

Adds custom titles and subtitles for spotlight items (the "Petrov Day" title in the example was originally a much longer "[LW Petrov Day 2022 (Monday, 9/26)](http://localhost:3000/posts/KTEciTeFwL2tTujZk/lw-petrov-day-2022-monday-9-26)").
Also adds a duration (measured in days), so that some spotlights can last longer or shorter than 3 days.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203060590064194) by [Unito](https://www.unito.io)

Add duration, customTitle and customSubtitle to Spotlights

---

packages/lesswrong/components/editor/CKCommentEditor.tsx
packages/lesswrong/components/editor/CKPostEditor.tsx
packages/lesswrong/components/editor/Editor.tsx
packages/lesswrong/components/editor/EditorFormComponent.tsx
packages/lesswrong/components/shortform/ShortformSubmitForm.tsx
packages/lesswrong/lib/editor/make_editable.tsx

This does the following:
- makes non-default placeholder text work again (for the whole site)
- fixes the styling of the comment box in the mobile view of subforums
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203056693645708) by [Unito](https://www.unito.io)

Fix some styling bugs caused by Great Divergence

---

packages/lesswrong/components/posts/PostsPage/PostsPageCrosspostWrapper.tsx

This PR fixes read times for posts that are crossposted from elsewhere. It's possible (probable?) that more fields will need to be added to `overrideFields` in the future, but I'm not sure exactly which right now.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203050787101586) by [Unito](https://www.unito.io)

Fix crosspost read times

---

packages/lesswrong/lib/collections/comments/views.ts
packages/lesswrong/server/emailComponents/EmailComment.tsx

* Removed `commentsOnTag` view which is no longer used (hasn't been used for 3 weeks so should be safe to remove)
* Replace all checks for `!== TagCommentType.Subforum` with `=== TagCommentType.Discussion` as all comments are now one or the other
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203058444608204) by [Unito](https://www.unito.io)

Cleanup from migrating subforum comments onto tag

---

packages/lesswrong/components/recommendations/RecommendationsPage.tsx
packages/lesswrong/components/spotlights/SpotlightHistory.tsx
packages/lesswrong/lib/components.ts

I kept wanting click the "recommendations" header on the frontpage to get to the spotlights page. I also separately think the Recommendations page should mirror whatever's in the Recommendations section, and thirdly think it'll be somewhat convenient for users to occasionally be able to check what a recent spotlight was if they didn't finish reading it and forgot what it was.
So... I made a quick update to the Recommendations page to include a spotlight section, and when you click on the spotlight-section-title if you're an admin/sunshine it takes you to the /spotlights page.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203068373639285) by [Unito](https://www.unito.io)

Spotlights history on Recommendations page

---

packages/lesswrong/components/spotlights/SpotlightHistory.tsx
packages/lesswrong/lib/collections/spotlights/permissions.ts

Allow sunshines to edit spotlights, and remove unused class that's currently breaking the /recommendations page
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203069577405780) by [Unito](https://www.unito.io)

Minor spotlight fixes

---

packages/lesswrong/server/emailComponents/NewPostEmail.tsx

Top row: new info (inserted in `NewPostEmail`).  Bottom row: old info (manually edited into the post body; won't be added to new posts going forward).  Both displayed for styling comparison.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203061107972590) by [Unito](https://www.unito.io)

update NewPostEmail to include podcast info for posts with podcasts

---

packages/lesswrong/components/sunshineDashboard/ModerationLog.tsx

For some reason this only happens when either opening the notifications sidebar, or opening and then closing karma notifications.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203068013127898) by [Unito](https://www.unito.io)

npe in moderation log

---

.github/workflows/cypress.yaml
package.json
yarn.lock

Cypress was timing out connecting to our server before our server started up, leading to intermittent failures. It seems like probably our server startup has gotten slower over time, leading to this happening more often. This is easy to fix, we just wait on the server starting up before launching the tests. Add a new dev dependency, `wait-on` to do so.
Also: JP couldn't build bcrypt from source for some reason. Fix that by upgrading to a bcrypt version that has a binary for m1 macs.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203074083971768) by [Unito](https://www.unito.io)

Cypress test timeout fix

---

packages/lesswrong/server/ckEditor/ckEditorCallbacks.ts

We currently have a bug where draft posts that are publically editable are inaccessible the first time they're accessed with a sharing key. This is what happens:
* The user visits the `collaborateOnPost` page with a valid sharing key
* We validate this at lines 100 and 101 which evaluate to true
* We add the user to the `linkSharingKeyUsedBy` array in mongo at line 108, but don't update our `post` local variable
* We filter the post with `accessFilterSingle` which fails because the post is a draft and hasn't been explicitly shared with the user
* The endpoint returns `null` so we display a "You don't have permission" message
* The next time the user visits the page the filter will work because they'll have been added to the `linkSharingKeyUsedBy` array already. Note that we can't simply …

Don't double check document permissions after checking collab permissions

---

packages/lesswrong/server/mapsUtils.ts

I originally included this in https://github.com/ForumMagnum/ForumMagnum/pull/5512, but wanted to move it over into a separate PR so that the ACX migration PR could get merged safely without having to think too hard.
I don't actually remember how to replicate the situation where `googleLocation` or `time` are missing.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203069747846957) by [Unito](https://www.unito.io)

Add missing param checks for getLocalTime

---

packages/lesswrong/components/comments/CommentsTimeline.tsx
packages/lesswrong/components/comments/CommentsTimelineSection.tsx

This fixes two bugs:
* when you tapped in and out of the text box the timeline view could end up the wrong size due to not accounting for window.scrollY when measuring it's position
* the address bar pushed the text box off the end of the page
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203079720982588) by [Unito](https://www.unito.io)

Fixes to mobile view of subforums

---

packages/lesswrong/server/spotlightCron.ts

Noticed some errors being thrown locally when running a dev server by the new spotlight cron job.  Turns out it was using the wrong spotlight item to get the current spotlight item's index, in order to get the next spotlight item's position.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203076959328456) by [Unito](https://www.unito.io)

fix spotlight item used to get next spotlight item position

---

packages/lesswrong/components/comments/CommentsNewForm.tsx
packages/lesswrong/components/comments/CommentsTimelineSection.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionFeed.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionTag.tsx
packages/lesswrong/lib/collections/comments/helpers.ts
packages/lesswrong/lib/collections/comments/schema.ts
packages/lesswrong/lib/collections/comments/views.ts
packages/lesswrong/lib/collections/tags/schema.ts
packages/lesswrong/server/callbacks/commentCallbacks.ts
packages/lesswrong/server/emailComponents/EmailComment.tsx
packages/lesswrong/server/resolvers/tagResolvers.ts

The only relevant change is in packages/lesswrong/lib/collections/comments/helpers.ts, everything else is just to fix an import cylce
Previously it would incorrectly send you to the discussion page
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203082626760282) by [Unito](https://www.unito.io)

Use correct link for subforum reply notifications

---

packages/lesswrong/components/spotlights/SpotlightItem.tsx
packages/lesswrong/components/spotlights/SpotlightsPage.tsx

Shows the total duration of all spotlights in the "upcoming" and "draft" sections. Also tweaks the styling of the SpotlightItems to have less paragraph padding (see Immoral Mazes for example). Updates the text shadow
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203089466506158) by [Unito](https://www.unito.io)

Spotlight duration and minor styling updates.

---

packages/lesswrong/lib/collections/users/formGroups.ts
packages/lesswrong/lib/collections/users/permissions.ts
packages/lesswrong/lib/collections/users/schema.ts

This makes it so users can deactivate their own accounts instead of having to message an admin.
Also fixes a bug where deactivated users couldn't edit their profile (so that they can reactivate their account if they want)

Users can self-deactivate

---

packages/lesswrong/components/comments/CommentsListSection.tsx

On LessWrong's end, it was feeling too prominent for EA comments to be the very first thing you saw in the comment's feed.
(Theoretically this could be forum-gated, but... seemed fair if we were lowering the prominence of EAF comments that EAF lower the prominence of ours :P)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203075934975682) by [Unito](https://www.unito.io)

Move crosspost comments below comments

---

packages/lesswrong/components/comments/CommentsNewForm.tsx
packages/lesswrong/components/comments/CommentsTimelineSection.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionFeed.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionTag.tsx
packages/lesswrong/components/search/CommentsSearchHit.tsx
packages/lesswrong/lib/collections/comments/helpers.ts
packages/lesswrong/lib/collections/comments/index.ts
packages/lesswrong/lib/collections/comments/schema.ts
packages/lesswrong/lib/collections/comments/types.ts
packages/lesswrong/lib/collections/comments/views.ts
packages/lesswrong/lib/collections/tags/helpers.ts
packages/lesswrong/lib/collections/tags/schema.ts
packages/lesswrong/server/callbacks/commentCallbacks.ts
packages/lesswrong/server/emailComponents/EmailComment.tsx
packages/lesswrong/server/resolvers/tagResolvers.ts
packages/lesswrong/server/search/algoliaDocuments.d.ts
packages/lesswrong/server/search/utils.ts

Previously it only worked for posts.
Another way of doing this would be to put the url in the search hit, although that would introduce the possibility of the results getting out of sync if we change the url structure, which is why I didn't do that. I wouldn't mind changing to that way if anyone knows of any problems with the way I've done it (e.g. it costs more, adding more fields degrades the search quality)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203092851132284) by [Unito](https://www.unito.io)

Make algolia comment search work for subforums, topic discussion, events, groups

---

packages/lesswrong/server/vulcan-lib/utils.ts
packages/lesswrong/themes/stylePiping.ts

This PR fixes an issue in copy-pasted content from Google Docs' publish-to-web view. That view uses an inline style of `list-style-type: none` on `ul`s and `ol`s to allow for their custom bullets, which, when pasted into CKEditor, caused bullets to look like indents.
Fixes https://github.com/ForumMagnum/ForumMagnum/issues/5531
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203084020603583) by [Unito](https://www.unito.io)

Fix missing bullets in Google Docs publish-to-web paste

---

packages/lesswrong/components/tagging/TagPage.tsx
packages/lesswrong/components/tagging/TagSubforumPage.tsx
packages/lesswrong/lib/collections/tags/fragments.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts
packages/lesswrong/lib/utils/truncateTagDescription.ts

This PR adds a right sidebar element on desktop which displays the topic's contents, excluding things like footnotes and references. As with the welcome box, it's removed on smaller screens.
This PR also includes changes from a recent run of yarn generate that didn't make it into master, in [this commit](https://github.com/ForumMagnum/ForumMagnum/commit/e4e0722de2c27b6a13f264a25f48127ca1d58a75).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202983749947406) by [Unito](https://www.unito.io)

Subforum wiki sidebar

---

packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx

The approach here is just to show a more appropriate message rather than to do anything too fancy. I also added a `maxWidth` as it makes the wrapping a bit more sane with the longer message.
LessWrong as the author:
LessWrong as a different user:
EA Forum as the author:
EA Forum as a different user:
These posts still aren't visible to logged-out users, but I feel like this is potentially the correct behaviour anyway(?):
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203075369278820) by [Unito](https://www.unito.io)

Show different messages for logged-out users viewing a crosspost fr a new account

---

packages/lesswrong/components/tagging/TagSubforumPage.tsx

Fixed an issue on mobile which caused the discussion section to extend offscreen.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203111863920502) by [Unito](https://www.unito.io)

Fix subforum mobile styling issue

---

packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
packages/lesswrong/components/ea-forum/users/modules/EAUsersProfileTags.tsx
packages/lesswrong/lib/components.ts

We have some users [enthusiastically](https://forum.effectivealtruism.org/users/jakubkraus07-gmail-com) adding topics to their profiles, so now we're only showing the first 4 by default. Also fixed an issue you wouldn't see the updated topics list until after a refresh.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203110077863494) by [Unito](https://www.unito.io)

[EA Forum only] truncate profile tag list

---

packages/lesswrong/server/recommendations.ts

A couple months ago Ruby and I made the frontpage recommendations section only show rationality posts. This adds world-modeling back into the mix. (The overall goal here is still to counterbalance the deluge of AI content and give new users better training data of what LessWrong is about)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203095749711773) by [Unito](https://www.unito.io)

Include worldmodeling in recommendations

---

packages/lesswrong/components/spotlights/SpotlightItem.tsx
packages/lesswrong/components/spotlights/SpotlightStartOrContinueReading.tsx

Makes the text-editor for the description match the exact styling of the displayed description, and does some other minor nice-to-have improvements for spotlight styling:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203112170972554) by [Unito](https://www.unito.io)

Improve spotlight styles

---

packages/lesswrong/components/form-components/ImageUpload.tsx
packages/lesswrong/components/sequences/SequencesNewForm.tsx
packages/lesswrong/components/sequences/SequencesPage.tsx

A few things were wrong with sequence banner images:
– the crop ratio was way off, making it hard to size images correctly so you could easily see the most interesting bits
– the sequence-text overlapped a lot with the image in a way that also tended to blot out the most interesting bits in the middle
– the sequence editor sizing was just... broken somehow.
Here's the new resulting image:
Compared to before:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203114573810684) by [Unito](https://www.unito.io)

Sequence Banner image sizing

---

packages/lesswrong/components/tagging/TagPageButtonRow.tsx
packages/lesswrong/components/tagging/TagSubforumButton.tsx
packages/lesswrong/components/tagging/TagSubforumPage.tsx
packages/lesswrong/lib/collections/tags/fragments.ts
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

From the topic page to the subforum, we (JP and I) decided to just replace the discussion link since:
* Tag discussion is rarely used
* It could be confusing for people to have both, Yonatan mentioned being confused about the purpose of the subforums given that tag discussion exists. My impression is that we want Discussion to be about the wiki article but this isn't clearly communicated to users atm
I think it would be good (for all tags, not just subforums) to move "Discussion" to the side bar and call it "Wiki article discussion" or something, but for the existing subforums we have I think it's fine to just remove it entirely (there is 1 discussion comment on Software Engineering and 0 on Bioethics)
From the subforum to the topic page:
I don't love this way of doing it, I think it …

Link to subforum from topic page and vice versa

---

packages/lesswrong/components/hooks/useForeignCrosspost.ts

When displaying a crosspost on the foreign site, we show the TOC as generated on the site where the post was created. This includes the comment count, which will be wrong when displayed on the foreign site. This PR replaces the comment count with the correct local number.
It's also now possible to test crosspost PRs locally by starting two servers with `yarn ea-start` and `yarn ea-start-xpost-dev`, then the two sites will be available at `localhost:3000` and `localhost:4000`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203133181749503) by [Unito](https://www.unito.io)

Fix crosspost TOC comment count

---

packages/lesswrong/components/posts/PostsTitle.tsx

On Lizka's request, I think this looks better on LW too so I haven't forum gated it
Before/after EA forum:
Before/after LW:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203149747717316) by [Unito](https://www.unito.io)

Lighten pin icon

---

packages/lesswrong/components/notifications/NotificationsMenu.tsx

Bug was introduced in: [https://github.com/ForumMagnum/ForumMagnum/commit/668e4cb6eb4e3966299a9a4499d980d879d58cb9#diff-a768b8236f6e93117a2214[…]9f6c946f4c6de725a452e38R122](https://github.com/ForumMagnum/ForumMagnum/commit/668e4cb6eb4e3966299a9a4499d980d879d58cb9#diff-a768b8236f6e93117a2214503b6be2f2b74527e1d9f6c946f4c6de725a452e38R122)
The bug is that `SwipeableDrawer` does things even if `open` is false (eg it could be mid-way through a close animation), so conditionally removing it from the page is incorrect.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203126860388372) by [Unito](https://www.unito.io)

Fix the notification drawer open/close animations

---

packages/lesswrong/components/messaging/ConversationPage.tsx
packages/lesswrong/components/messaging/NewConversationButton.tsx
packages/lesswrong/components/sunshineDashboard/SunshineSendMessageWithDefaults.tsx

This begins to actually replace the mod template message variables with their substance. (i.e. {{displayName}} turns into the user's display name).
compared to:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203147494390793) by [Unito](https://www.unito.io)

Template message variable replacement

---

packages/lesswrong/components/messaging/InboxNavigation.tsx

It was a bit annoying to get to the /moderatorInbox page, and this adds a link on the /inbox page.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203146922573777) by [Unito](https://www.unito.io)

Add link to mod inbox

---

packages/lesswrong/components/hooks/useForeignCrosspost.ts
packages/lesswrong/components/posts/PostsPage/PostsPageCrosspostComments.tsx
packages/lesswrong/lib/collections/posts/schema.tsx
packages/lesswrong/server/fmCrosspost/crosspost.ts
packages/lesswrong/server/fmCrosspost/denormalizedFields.ts
packages/lesswrong/server/fmCrosspost/requestHandlers.ts
packages/lesswrong/server/fmCrosspost/resolvers.ts
packages/lesswrong/server/fmCrosspost/types.ts
packages/lesswrong/server/fmCrosspost/validationHelpers.ts

Crossposting events currently doesn't work correctly - the crossposting happens, but the foreign site thinks it's just a normal post. Most of the work in this PR is just generalizing the way that denormalized fields are handled so that we can simply add new denormalized fields to the `denormalizedFieldKeys` array in the future (as we do with `isEvent` here).
We also need to add a _ton_ of fields to `overrideFields` on the frontend to make sure we fetch all the normalized data correctly. Part of me feels like this could move directly onto the schema like `overrideOnForeignCrosspost: true` or something, but then it becomes a lot less localized and more difficult to reason about. I'm not 100% either way.
Note that, even with these changes, crossposted events still won't show up on when …

Fix crosspost events

---

packages/lesswrong/lib/collections/comments/fragments.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

We said on Slack that we'd deprioritise this bug, but Lizka found another affected case today that was a lot more serious as it prevented us from interacting with some flagged content. I spent some more time digging in to it and I'm pretty sure this is the correct solution (it seems to fix the issue on local).
The problem is that we don't send the `_id` with the `contents` field on the `CommentsList` fragment, which means that the Apollo cache falls over when it tries to normalize the data.
0/10 would not debug again.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203166368566648) by [Unito](https://www.unito.io)

Fix sunshine sidebar causing various frontpage stuff to not load

---

packages/lesswrong/server/scripts/algoliaConfigureIndexes.ts

This is based on a report by Lizka, where she noticed that the search results would prioritize matching headings in the post body over matching on the post title. I agreed that we weigh matching a post title more. So I'm reverting us back to the default ranking order, as we think that gives us better results.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203184952762555) by [Unito](https://www.unito.io)

revert algolia posts index ranking to default order (before the custom rankings)

---

packages/lesswrong/themes/defaultPalette.ts

I noticed that the moderator comment hoverover is too transparent, so I replaced the color. Hopefully it looks the same.
- - -
Before:
- - -
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203187825160269) by [Unito](https://www.unito.io)

update moderator comment background color

---

packages/lesswrong/server/scripts/mergeAccounts.ts
scripts/mergeUsers.sh

People often end up with duplicate accounts sharing an email, and it'd be helpful if we could merge those in a way that actually removes the duplication so they can then actually edit their accounts without throwing validation errors.
This PR also makes it so that the mergeAccounts function specifies sourceUserId and targetUserId, because I frequently had to go looking up which was which, which I found annoying. (I personally access the command by searching my command line history, and grab the last instance of it). So, now it looks like:
```
scripts/serverShellCommand.sh "Globals.mergeAccounts({sourceUserId:'vperH823EjMoAnzAz', targetUserId:'bneALscHnCXsr8QRu', dryRun:false})"
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203050878789260) by …

mergeAccounts removes duplicate emails and displayNames

---

packages/lesswrong/server/scripts/mergeAccounts.ts

Currently causing a type error on master.

Fix invalid 'source' in mergeAccounts script

---

packages/lesswrong/components/form-components/ImageUpload.tsx
packages/lesswrong/lib/collections/localgroups/schema.ts

A while back, we changed localgroup banner images from being full width to using fixed dimensions, and at the time I updated the `croppingAspectRatio` to match. But currently most banner images are still full width and use the new wider aspect ratio, so I'm fixing the localgroup case by just passing in a custom `croppingAspectRatio`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203202265719335) by [Unito](https://www.unito.io)

fix localgroup banner img cropping

---

migrate.js
packages/lesswrong/server/migrations/meta/PgStorage.ts
packages/lesswrong/server/migrations/meta/umzug.ts

This PR adds the two features that we discussed on the initial migrations PR:
1. Each migration run now takes place inside a single transaction, so a failed migration with revert any previous successful migrations as well.
2. Migration ordering is enforced. Trying to run migrations out of order will result in a prompt being shown to the user where they can choose to either exit the migration run to fix the problem manually, force the migration to be executed anyway (strongly discouraged in prod, but almost certainly userful on dev), or automatically rename the out-of-order migration file to the current timestamp. In the deploy pipeline, we'll always want to choose the first option, so we can just run `yes n | yarn migrate up`, for instance. …

Postgres migration transactions

---

packages/lesswrong/components/posts/PostReadCheckbox.tsx
packages/lesswrong/components/posts/PostsItem2.tsx
packages/lesswrong/components/sequences/ChaptersItem.tsx
packages/lesswrong/components/sequences/SequencesSmallPostLink.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/server/tableOfContents.ts
packages/lesswrong/themes/createThemeDefaults.ts

A few people complained about the move to using SequencesSmallPostLink on Sequences pages. This reverts to using PostsItem2, but adds an optional checkbox for PostsItem2 so that reading a sequence still gives more sense of forward progression.
At the same time, refactors the checkboxes into their own component, shared between PostsItem2 and SequencesSmallPostLink, and lets people click on the checkbox to mark as read or unread. (A few people had asked for this too)
Note: I considered having the checkbox housed within the "border" of the PostsItem, but then the combination of checkbox + karma felt a bit cluttered.

Sequences use PostsItem again, checkbox refactor

---

packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
packages/lesswrong/components/feeds/newFeedButton.tsx
packages/lesswrong/components/users/UsersProfile.tsx

I got slightly annoyed at not being sure if users already had an RSSFeed when I went to create their RSSFeed. Added a small bit of UI (only affects admins)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203204196576520) by [Unito](https://www.unito.io)

Show existing rss feeds

---

packages/lesswrong/components/messaging/NewMessageForm.tsx

Couple issues here:
1. We shouldn't have been checking the existence of `templateQueries` for deciding whether to skip the template query, since it would always exist when `NewMessageForm` was rendered in the context of `ConversationPage` (unlike in `SunshineUserMessages`).  Check that a template ID exists instead, which is the thing we actually use to fetch it.
2. For some reason `useSingle` is returning `loading: true` even when `skip: true`, which meant that it would persistently show the loading state for the message box... but this only happened for server-side renders (i.e. the conversation page is loaded directly or in a new tab, rather than navigated-to).  Not actually sure what's going on there, and feels like a dangerous sort of thing to leave not figured out.
┆Issue is …

fix message input box loading for ssr with no template queries

---

packages/lesswrong/components/sunshineDashboard/ModerationDashboard.tsx
packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUsersList.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUsersProfileInfo.tsx
packages/lesswrong/components/sunshineDashboard/SunshineReportedContentList.tsx
packages/lesswrong/components/sunshineDashboard/SunshineReportedItem.tsx
packages/lesswrong/components/sunshineDashboard/SunshineSendMessageWithDefaults.tsx
packages/lesswrong/components/sunshineDashboard/SunshineSidebar.tsx
packages/lesswrong/components/sunshineDashboard/SunshineUserMessages.tsx
packages/lesswrong/components/sunshineDashboard/UsersReviewInfoCard.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/server/callbacks/sunshineCallbackUtils.tsx
packages/lesswrong/server/migrations/2022-08-11-snoozeUntilContentCount.ts

Pulls out all the moderator actions into one component that can be shared between UsersReviewInfoCard and SunshineNewUsersInfo. 
Also adjusts the structure of UsersReviewInfoCard slightly.

Refactor moderator actions

---

packages/lesswrong/components/comments/CommentsItem/CommentBody.tsx
packages/lesswrong/components/tagging/TagPreviewDescription.tsx

Bug was introduced in https://github.com/ForumMagnum/ForumMagnum/pull/5922/commits/02265d3e1988da1327c8c52596d65d39327b545c which changed a CSS class name but missed some styling that was attached to it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203246867607266) by [Unito](https://www.unito.io)

Fix grey styling of "read more" in comments

---

packages/lesswrong/components/recentDiscussion/RecentDiscussionSubscribeReminder.tsx

This PR allows logged out users to sign up for the EA Forum's digest. We didn't do anything to reduce the number of sign ups from bots, because Ollie and I were not sure if that would actually be an issue.

[EA Forum only] logged out users can sign up for forum digest

---

packages/lesswrong/lib/collections/posts/formGroups.ts
packages/lesswrong/lib/collections/posts/schema.tsx

We've been getting a lot of requests from users via intercom to add other users as coauthors on their posts.  Let's try making the option much more visible.  (Edit: now in its own form group, so as not to draw additional attention to the crossposting feature, which we're not sure we want users to be thinking about "by default".)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203231835889020) by [Unito](https://www.unito.io)

set advanced options first and open by default

---

packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx

Sometimes we want to dismiss a user from the review queue without marking them as having been reviewed (which snoozing them would do), such as in the case of a new user with a post which either we or they have turned back into a draft after publishing.  (Maybe also for users who have not-obviously-spammy bios but haven't left any comments.). This gives us the opportunity to review their next published post before it goes live.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203261902334988) by [Unito](https://www.unito.io)

dismiss user without review

---

packages/lesswrong/components/common/TabNavigationMenu/EventsList.tsx
packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
packages/lesswrong/components/form-components/TagMultiselect.tsx
packages/lesswrong/components/search/SearchPageTabbed.tsx

We're going down to two events in the sidebar, and removing the links to the Community page sections. The feature banner isn't quite visible above the fold yet though.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203253848439495) by [Unito](https://www.unito.io)

[EA Forum only] clean up the sidebar links

---

packages/lesswrong/components/common/LWClickAwayListener.tsx
packages/lesswrong/components/common/withDialog.tsx
packages/lesswrong/components/posts/PostsPage/PostsPageActions.tsx
packages/lesswrong/components/tagging/AddTagButton.tsx
packages/lesswrong/components/tagging/SubforumNotificationSettings.tsx
packages/lesswrong/components/users/KarmaChangeNotifier.tsx
packages/lesswrong/lib/components.ts

The default for `ClickAwayListener` was to listen for mouseUp events, whereas most other components listen for onClick. This resulted in some fiddle logic you had to do to make it work correctly because mouseUp is fired before onClick, e.g. look at the logic that was in `packages/lesswrong/components/tagging/SubforumNotificationSettings.tsx` before this change:
```Typescript
const handleOpen = (event) => {
setOpen(true);
setAnchorEl(event.currentTarget);
};
const handleClose = (e) => {
if (e && anchorEl?.contains(e.target)) {
return;
}
setOpen(false);
};
const handleToggle = (e) => {
if (open) {
handleClose(null); // When closing from toggle, force a close by not providing an event
} else {
handleOpen(e);
}
};
```
If you clicked on the bell to close the popout `handleClose` would be …

Fix "bug" in ClickAwayListener

---

packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
packages/lesswrong/lib/crud/withMulti.ts

Count the user's posts rather than rely on `user.postCount`, because the latter doesn't include posts that the user coauthored.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203248853856142) by [Unito](https://www.unito.io)

[EA Forum only] fix post count on user profile

---

packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUserPostsList.tsx

I totally forgot to actually run the function instead of literally linking people to "postGetPageUrl(post)#comments". Fixed.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203275001936264) by [Unito](https://www.unito.io)

Fix links to post comments

---

packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx

Due to some changes introduced in #5932 (I think), the MUI Input field was rendering three textfields and failing to hide two of them (as intended). 
This problem goes away if you change rowsMax to rows (instead rendering a different field), which requires also changing how scrollbar-hidden works. @oetherington is working on a more comprehensive solution.

Fix ui bugs for notes field

---

packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewPostsList.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUserPostsList.tsx
packages/lesswrong/lib/collections/moderatorActions/schema.ts
packages/lesswrong/lib/collections/posts/fragments.ts
packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

Makes it possible to flag users when reviewing their posts.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203274281315749) by [Unito](https://www.unito.io)

flag user from sunshine post item

---

packages/lesswrong/client/themeProvider.tsx
packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx
packages/lesswrong/lib/utils/generateClassName.ts
packages/lesswrong/server/material-ui/themeProvider.tsx

I think this _should_ fix the problems caused by JSS adding `-nnn` suffixes to some internal components. For now, I've just removed suffixes in all cases - it's theoretically possible that this could lead to collisions, but I can't see any case where this would happen unless we start having multiple components with exactly the same name which seems bad for a whole variety of different reasons.
If you think this could be too dangerous then let me know and we can just add some extra logic here. Either we could add a suffix for everything, or we could keep track of a dictionary of class names and only add a suffix (and maybe issue a console warning?) when we actually find a concrete collision. …

Fix class name generation

---

packages/lesswrong/components/form-components/FMCrosspostControl.tsx
packages/lesswrong/lib/collections/posts/schema.tsx

Only shows up when the target of the crossposting is the EA Forum. I couldn't think of a super elegant way to check for that, let me know if you think of a nicer one.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203281891282059) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203281891282059

Crosspost tooltip, message written by Lizka

---

packages/lesswrong/lib/editor/utils.test.ts
packages/lesswrong/server/resolvers/revisionResolvers.ts

Fixes #5942 
See the comment in the code for an explanation of why the bug happens.
The one thing we have to be careful about here is that `convertToRaw` doesn't make any internal references to ids once they're generated as this approach would leave these references dangling right now. From [the code](https://github.com/HubSpot/draft-convert/blob/master/src/convertFromHTML.js), this seems to be safe, but it's something to look out for in the future.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203294639619194) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203294639619194

Fix inifite reload loop caused by unstable DraftJS block keys

---

packages/lesswrong/server/utils/renderJssSheetImports.ts

We're currently not loading any CSS when printing if the user's theme is set to "auto" because the CSS `@import`s which check `prefers-color-scheme` also specify `screen`.
This seems to be the correct thing to do, since the spec doesn't specify how `prefers-color-scheme` should work when printing, instead leaving it up to user agents to implement how they wish ([context](https://github.com/w3c/csswg-drafts/issues/3522#issuecomment-463300486)).
We can work around this by just adding a separate `@import` for printing that loads the light theme.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203307608606644) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203307608606644

Fix printing with auto theme

---

packages/lesswrong/components/common/Header.tsx
packages/lesswrong/components/community/modules/LocalGroups.tsx
packages/lesswrong/components/community/modules/OnlineGroups.tsx
packages/lesswrong/components/form-components/ImageUpload.tsx
packages/lesswrong/components/posts/PostsAnalyticsPage.tsx
packages/lesswrong/components/posts/PostsPage/PostsPodcastPlayer.tsx
packages/lesswrong/components/search/ExpandedSequencesSearchHit.tsx
packages/lesswrong/components/search/ExpandedTagsSearchHit.tsx
packages/lesswrong/components/themes/useTheme.tsx
packages/lesswrong/components/votes/VoteAgreementIcon.tsx
packages/lesswrong/components/votes/VoteArrowIcon.tsx
packages/lesswrong/components/votes/voteColors.ts
packages/lesswrong/server/styleGeneration.tsx
packages/lesswrong/themes/cssVars.ts
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/themeType.ts
packages/lesswrong/themes/userThemes/darkMode.ts

The simplest way to handle this seems to just be to not use `useTheme` in these contexts.
I added a `requireCssVar` function that provides a css variable for a particular theme item that will respect changes to the theme on the client side, and won't directly read the wrong theme during SSR.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203286431838161) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203286431838161

Fix bad uses of 'useTheme' during SSR

---

packages/lesswrong/components/votes/OverallVoteAxis.tsx

Currently the overall/approve voting tooltip shows approval + agreement voting, which is very confusing. This changes the display to only show total approval voting.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203326817222886) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203326817222886

Fix approval votecount tooltip

---

packages/lesswrong/components/posts/PostsItem2.tsx

Fixes the width issues that happen on sequence pages when you include the checkboxes:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203318920920588) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203318920920588

Fix postsItem2 checkbox width

---

packages/lesswrong/components/votes/OverallVoteAxis.tsx

Reverts ForumMagnum/ForumMagnum#6035
Quoting myself:
> This PR is based on an incorrect understanding about how votes are stored in the DB. Voters who vote on approval and agreement only end up inserting 1 non-cancelled vote into the db. Therefore this vote will ignore their vote when counting approval votes.
>
> For simplicity I will revert this PR. I believe the correct approach is to add another denormalizedCountOfReferences.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203340241850254) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203340241850254

Revert "Fix approval votecount tooltip"

---

packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx

This was accidentally lost during a [refactor](https://github.com/ForumMagnum/ForumMagnum/commit/7a1940b87fc4321e22f66f97511a42c98ac841f3). Adding it back in, which makes sunshine user notes less likely to get lost. (Note: with the hook restored, the notes still aren't perfectly preserved. It seems to reliably lose the last few characters. But, the currently live LW branch seems to reliably lose everything you typed)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203348618420846) by [Unito](https://www.unito.io)

Restore missing useEffect hook

---

packages/lesswrong/components/form-components/ImageUpload.tsx

I don't remember why this wasn't enabled before, but Alex ran into issues with the auto-cropping so I'm just enabling users to crop.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203350191985938) by [Unito](https://www.unito.io)

[EA Forum only] enable cropping for event images

---

packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx

Re-orders and changes icon/tooltip for the "remove from queue" button.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203368232345387) by [Unito](https://www.unito.io)

Move and change icon/tooltip for the "remove from queue" mod button.

---

packages/lesswrong/server/commandLine.ts
packages/lesswrong/server/serverStartup.ts

Do not default users to run postgres against their local machine, do not throw if they do not set a postgres connection string
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203368257901109) by [Unito](https://www.unito.io)

Better Postgres-less server running

---

packages/lesswrong/components/posts/PostsPage/PostsPageCrosspostWrapper.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203369087791905) by [Unito](https://www.unito.io)

Do not return 404 if the foreign x-post was moved to draft, but the post was hosted here

---

packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
packages/lesswrong/components/posts/PostsAnalyticsPage.tsx
packages/lesswrong/components/users/EditProfileForm.tsx
packages/lesswrong/components/users/UsersEditForm.tsx
packages/lesswrong/components/users/UsersProfile.tsx
packages/lesswrong/lib/collections/users/helpers.tsx
packages/lesswrong/lib/vulcan-users/permissions.ts
packages/lesswrong/server/resolvers/analyticsResolvers.ts

Also refactor userCanEditUser — previously the name and (absent) types were very ambiguous.
You may want to look at this PR commit-by-commit.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203358436921680) by [Unito](https://www.unito.io)

Allow coauthors to access post analytics

---

packages/lesswrong/components/notifications/NotificationsMenu.tsx

Turns out the MUI code that makes the notification drawer stay just off the edge of the screen wasn't very good.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203375795143263) by [Unito](https://www.unito.io)

Revert "Fix the notification drawer open/close animations"

---

packages/lesswrong/lib/components.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203376478754204) by [Unito](https://www.unito.io)

add missing import for AFSuggestPostsItem component

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx

Instapaper is a site that bookmarks and reformats posts for later reading. It has a complex and undocumented heuristic for detecting where the body of the post is. At some point recently (maybe related to comment-on-selection), its heuristic stopped correctly identifying LW post bodies, and some Instapaper users complained.
According to an email from Instapaper, adding the `instapaper_body` class to the element we want it to detect as the body should override the heuristic and make the body-extraction work correctly again.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203357013785153) by [Unito](https://www.unito.io)

Add instapaper_body class to post body, so that Instapaper will detect it correctly

---

packages/lesswrong/components/comments/CommentsListSection.tsx
packages/lesswrong/components/posts/PostsCommentsThread.tsx
packages/lesswrong/components/tagging/TagDiscussionSection.tsx

On post pages, there's a message that says "Highlighting [n] new comment since [date]". It only counted new root comments. Make it count all new comments.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203357109395411) by [Unito](https://www.unito.io)

Fix comment count in "highlighting new comments since" message

---

packages/lesswrong/components/posts/PostReadCheckbox.tsx

Caused by misinterpreting `postsRead` in `ItemsReadContextType` as a set, rather than a mappign where true, false, and missing are three distinct meanings.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203281300564029) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203281300564029

Fix mark-as-unread in PostReadCheckbox

---

packages/lesswrong/components/tagging/TagPage.tsx
packages/lesswrong/components/tagging/TagPreview.tsx

This is required now because we're about to add a bunch of subtags to the Animal Welfare topic. In the long run I think we should make it so that all tags with lots of subtags are subforum, which will then have a box in the sidebar showing all the subtags (this is still so be decided). But this change is just to stop the topic page looking bad while subforums are in development
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203393507104721) by [Unito](https://www.unito.io)

Truncate subtags list in topic page

---

packages/lesswrong/components/posts/PostsPage/PostsPageCrosspostWrapper.tsx

Follow-on to #6097.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203375234767702) by [Unito](https://www.unito.io)

Defend against scenario where foreign forum is down when rendering crossposted post

---

packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
packages/lesswrong/components/ea-forum/advice/AdvisorsPage.tsx
packages/lesswrong/lib/collections/advisorRequests/permissions.ts
packages/lesswrong/lib/index.ts

In trying to get this out before my vacation, apparently I didn't test it properly. The two fixes here are:
1. Added `permissions.ts` for `AdvisorRequests`, so now the tracking actually works for non-admins
2. Stopped creating duplicate documents per user due to extra calls to `createJobAdView()`
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203389756015931) by [Unito](https://www.unito.io)

[EA Forum only] fix job ad bugs

---

packages/lesswrong/components/editor/Editor.tsx
packages/lesswrong/components/editor/EditorFormComponent.tsx

Not 100% sure what caused the regression, since as far as I can tell none of the relevant (editor/contents) code has been changed since I wrote & tested the podcasters logic.
This stops us from trying to submit the `contents` of a post when editing it if it's a ckEditor post and we don't have a ckEditor reference.  The only time that currently comes up is if it's a podcaster editing the post, since they're the only group that have permissions to edit posts (as a collection, such that they can add a podcast episode) but don't have permissions to edit the contents of the post itself.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203396033599208) by [Unito](https://www.unito.io)

don't try to submit contents in post edits when a podcaster is adding an episode

---

packages/lesswrong/server/callbacks/sunshineCallbackUtils.tsx
packages/lesswrong/server/callbacks/votingCallbacks.ts

Creates forum-specific automod rules, such that the EA forum can implement a different rule from LW for deciding whether to put a comment in moderation or not.
Also, make the LW rule a bit tighter.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203396296068735) by [Unito](https://www.unito.io)

forum-specific comment automod, and stricter LW rule

---

packages/lesswrong/server/vulcan-lib/utils.ts

This should fix issue #6134, hopefully pending a more complete analysis of what sanitization is leaving out in terms of accessibility.
I couldn't test this locally beyond pasted images.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203397796395069) by [Unito](https://www.unito.io)

Fix alt tags

---

package.json
scripts/brigaderCheck.ts
tsconfig.json

This week we've had (unsurprinsingly) an alarming number of alegations of vote brigading so here's a quick and dirty script to check for it.
Running `yarn brigader-check <POST_ID>` will show a formatted table output with all of the users who have an unusually large number of downvotes on the given post.
Users with a particularly large number can be inspected further with `yarn brigader-check <POST_ID> <USER_ID>` which will more clearly show how many downvotes they gave to particular users.
There's plenty of room for improvement here, but it's probably already saved me over an hour this morning.
This should probably be incorporated into an admin page at some point, but it's not particularly efficient at the moment and it's pretty miserable not being able to `JOIN`, so I feel like that's a …

Add script to check for brigading

---

packages/lesswrong/components/editor/EditorFormComponent.tsx
packages/lesswrong/components/editor/PostCollaborationEditor.tsx
packages/lesswrong/components/editor/PostVersionHistory.tsx
packages/lesswrong/lib/collections/revisions/collection.ts

Co-authored-by: jpaddison3 <jp@centreforeffectivealtruism.org>
Useful for recovering if CkEditor crashes. Also makes the "restore this revision" button in the revision-history popup conditionally visible based on whether you have permission to use it (as opposed to only having read or comment access).

Secondary post authors in collab editor can access version history

---

packages/lesswrong/components/common/ErrorAccessDenied.tsx
packages/lesswrong/components/posts/PostsPage/PostsPageWrapper.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203413131050069) by [Unito](https://www.unito.io)

Add better explanation when a post is inaccessible

---

packages/lesswrong/components/comments/CommentFrame.tsx
packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
packages/lesswrong/lib/collections/comments/fragments.ts
packages/lesswrong/lib/collections/comments/schema.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

Adds back the ability to make "invisible" mod comments that was originally introduced in https://github.com/ForumMagnum/ForumMagnum/pull/5992 and later removed for breaking crossposts.  Now that we're using a regular REST API to fetch crosspost data instead of a GraphQL query which throws errors on unknown fields (like a newly-added `hideModeratorHat` which one forum has deployed but the other doesn't), this should be safe.
This needs needs the EA forum to deploy last week's PR for using that new API, though it should be safe for LW to deploy this (since the EA forum has deployed the route itself, and LW is already using the new API, so won't break if we add a new field).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203414603091674) by …

add back the ability to hide moderator comments

---

packages/lesswrong/components/votes/EmojiReactionVoteOnComment.tsx
packages/lesswrong/components/votes/OverallVoteAxis.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/voting/votingSystems.tsx

We're focusing some effort on promoting Giving Tuesday / effective giving on the EA Forum. We're planning on running a "Where are you donating this year, and why?" open thread, and want to enable some good vibes by letting people react to comments.
I'd like to get this out soon to unblock Lizka. I mimicked the existing "react ballots" voting system and updated the UI.
~~Unfortunately, the tooltips on the standard voting component are pretty annoyingly in the way of the first user to emoji react, but after that you can hover over the other reacts and add yours more easily. I might try to fix this interaction, could be a separate PR though.~~
I addressed this by just separating out the emoji reactions UI from the standard voting UI, since that was confusingly tied together anyway. Now you …

add emoji reaction voting system

---

packages/lesswrong/components/common/MixedTypeFeed.tsx
packages/lesswrong/components/hooks/useOrderPreservingArray.tsx

We have intermittently seen a bug where items in the recent discussion feed were duplicated. This should fix that
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203412794552927) by [Unito](https://www.unito.io)

Deduplicate mixed type feeds

---

packages/lesswrong/components/common/MixedTypeFeed.tsx
packages/lesswrong/components/posts/PostsListSortDropdown.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionThread.tsx
packages/lesswrong/components/tagging/TagSubforumPage2.tsx
packages/lesswrong/lib/mongoCollection.ts
packages/lesswrong/lib/subforumSortings.ts
packages/lesswrong/server/resolvers/tagResolvers.ts
packages/lesswrong/server/utils/feedUtil.ts

This PR implements the mixed type feed for the new subforum page. Most of the code is just refactoring the `MixedTypeFeed` GraphQL queries to allow more arbitrary sorting than is needed for the recent discussions section.
Fow now, the "New Post" and "New Discussion" buttons don't do anything since I'm not sure exactly how we want to handle this - I think it makes sense to do that in a separate PR anyway. (Also, maybe they should have different icons).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203420879434471) by [Unito](https://www.unito.io)

Subforums mixed type feed

---

packages/lesswrong/components/comments/CommentWithReplies.tsx
packages/lesswrong/components/tagging/TagSubforumPage2.tsx
packages/lesswrong/lib/collections/comments/fragments.ts
packages/lesswrong/lib/collections/comments/schema.ts
packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts
packages/lesswrong/server/resolvers/tagResolvers.ts
packages/lesswrong/server/utils/feedUtil.ts

This PR implements pinned comments for subforums.
It uses a new `subforumStickyPriority` field (similar to how sticky post prioritisation works) which is used to set the index that the comment will be returned at. For our purposes we just want to set the value to `0`, but it could be used to add multiple stickied comments if needed in the future.
For the sake of expediting the process, this value currently needs to be set directly in the database, but if we use this in the future we could think about actually adding a proper UI.
For now, we're showing the name of the subforum next to the pin icon. This is probably redundant but it felt too bare without any text there. Maybe it could just say "Sticky" or "Pinned" instead? Or it could just stay as it is - I'm not going to lose sleep over …

Subforum pinned comments

---

packages/lesswrong/components/tagging/SubforumNotificationSettings.tsx
packages/lesswrong/components/tagging/TagSubforumPage2.tsx
packages/lesswrong/lib/collections/userTagRels/collection.ts

Here are the changes to the subforum notification settings. It's very possible that I misunderstood what the actual desired behaviour should be - I presumed "Post notifications on/off" just meant the existing setting, but feel free to correct if wrong. I figured the best thing to do is probably just to create the PR and if I misunderstood you can correct me here rather than slowing everything down checking in slack. This whole notification setup seems kind of complicated and I don't really know what's going on 😅.
Also, recent feedback from Lizka about notifcations that should maybe influence whay we do here: "I joined. I really didn't want EG to appear in my profile. I knew I should fix that so I went to edit my profile, unchecked the topic there, realized that it probably also subscribed …

Subforum notification updates

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/comments/CommentPermalink.tsx
packages/lesswrong/components/comments/CommentsItem/CommentsItemDate.tsx
packages/lesswrong/components/comments/CommentsNode.tsx
packages/lesswrong/components/common/TabNavigationMenu/SubforumsList.tsx
packages/lesswrong/components/tagging/TagPageRouter.tsx
packages/lesswrong/components/tagging/TagSubforumPage2.tsx
packages/lesswrong/lib/collections/tags/helpers.ts
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/routeUtil.tsx
packages/lesswrong/lib/routes.ts

- Route topics that are subforums to the v2 subforum page
- Redirect links to the v1 subforum to the v2 version
- Switch over tag and comment links to point to the correct url
- Some other small fixes that don't deserve their own PR
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203435533179907) by [Unito](https://www.unito.io)

Roll out subforums v2

---

packages/lesswrong/server/callbacks/sunshineCallbackUtils.tsx

Currently automod is triggering on the same user(s) for largely the same set of posts/comments, because it's not that rare for a user to post a few comments, trigger automod (i.e. low average karma content, which will happen frequently if someone posts a bunch of comments in a row without people voting on them in between), and then have some upvotes come in which end that automod action.  We don't especially want the same content to get checked again if it got upvoted enough to leave the danger zone.
Also, ignore the most recent content item for each rule we check, since it artificially down-weights averages.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203423089878989) by [Unito](https://www.unito.io)

make sure automod only considers content posted after the last relevant ended action, if any

---

packages/lesswrong/components/comments/SingleLineComment.tsx

A refactoring of comment-collapsing in the side-comments branch made the `forceSingleLine` option on `CommentsNode` part of `CommentTreeOptions`, making it heritable. Which is fine except that in `SingleLineComment`, the hover-preview inherits tree options from the comment that's being hovered. It explicitly handles this case by passing `forceNotSingleLine: true`... except that if both `forceSingleLine` and `forceNotSingleLine` are true, then `forceSingleLine` wins.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203454447813559) by [Unito](https://www.unito.io)

Fix hover-preview of single-line comments being also single line

---

packages/lesswrong/lib/components.ts

Missing import was breaking post actions in SunshineNewUsersProfileInfo (and possibly in other places).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203460778229124) by [Unito](https://www.unito.io)

fix missing import

---

packages/lesswrong/components/sunshineDashboard/ModerationDashboard.tsx
packages/lesswrong/lib/vulcan-users/permissions.ts

I believe this was an unintentional oversight. Also note the slight increase in type intelligence about `PermissionableUser` to allow any user fragment that has the requisite fields to be passed in.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203461667068555) by [Unito](https://www.unito.io)

Allow non-admin mods to see the moderation dashboard

---

packages/lesswrong/lib/collections/posts/views.ts
packages/lesswrong/lib/scoring.ts
packages/lesswrong/server/updateScores.ts

This is a first pass at improving the "magic" sorting for subforum comments. It took longer than expected due to experimenting with a few different methods, but I think this is definitely the cleanest I found, and it should make it relatively straight forward to make further tweaks to the algorithm, which I'm sure we'll want to do as this is still very simplistic. Here, we're taking advantage of the fact that the `score` field for subforum comments is never actually used anywhere else, so we can just change the formula for calculating it without needing to add a new field.
For now, all we're doing is adding a karma boost for the first N-hours after the comment is posted with a quadratic drop-off:
The parameters are configurable with database settings, but I've set the defaults to a 20 …

Add score boost for subforum comments

---

packages/lesswrong/themes/stylePiping.ts

Fixes https://github.com/ForumMagnum/ForumMagnum/issues/6196.
We allow custom widths on figures (including tables) in CKEditor. This has footgun potential if the fixed width exceeds the parent width, which has come up several times now (most recent instance pictured below, others [here](https://cea-core.slack.com/archives/C01Q279LKCK/p1624651025009900) and [here](https://cea-core.slack.com/archives/C02U2783GUC/p1663038306658959)).
This PR adds a max-width property to fix that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203468621301885) by [Unito](https://www.unito.io)

Add max-width property to figures in posts

---

packages/lesswrong/lib/sql/AddFieldQuery.ts
packages/lesswrong/lib/sql/index.ts

This should make writing migrations a lot quicker. After add field `foo` to collection `Bar`, we can just do
```
export const up = async ({db}: MigrationContext) => {
const {sql} = new AddFieldQuery(Bar.table, "foo").compile();
await db.none(sql);
}
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203466697968528) by [Unito](https://www.unito.io)

Add AddFieldQuery class

---

packages/lesswrong/server/callbacks/postCallbacks.ts
packages/lesswrong/server/scripts/algoliaExport.ts
packages/lesswrong/server/search/utils.ts

Prompted by a user trying to add a nonexistent tag to a post (that existed in the search engine but not the DB), I made the post-submission callback resilient to that, then tried rerunning `algoliaCleanIndex` for the first time in a long time. I fixed a case that would crash indexing in the posts collection (there's a 2010 post with malformed HTML that crashes the HTML-to-markdown converter), and added better logging to keep track of how it's doing.

Small improvements to Algolia index-pruning script

---

packages/lesswrong/components/review/FrontpageReviewWidget.tsx
packages/lesswrong/components/review/ReviewVotingPage.tsx

We're going to require 2+ positive votes for posts to go to the review phase this year.  Update wording (& add a new FAQ entry) to reflect that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203476502665797) by [Unito](https://www.unito.io)

update wording for many votes posts need to go to review phase

---

packages/lesswrong/lib/voting/votingSystems.tsx

There seems to be a bug, possibly introduced by [], characterized by the error `Invalid vote type in calculateVotePower: undefined`.  Pretty sure this fixes it (I couldn't figure out how to actually repro the issue myself).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203477804953732) by [Unito](https://www.unito.io)

fix undefined vote type fallthrough

---

packages/lesswrong/components/posts/PostsEditForm.tsx

Recent PRs to add support for [anonymous link-sharing](https://github.com/ForumMagnum/ForumMagnum/pull/4927) and a [new ToS](https://github.com/ForumMagnum/ForumMagnum/pull/6215/files#diff-1760ab6a36c559ac11e2b48fb15eff6bb8158ecda3fa8c56c8be29ff1f9cd4f8R103) were merged in, but together they generated a type error, where `PostsAcceptTos` requires a non-null `currentUser` but the anonymous link-sharing post created the possibility of a null `currentUser` at that point in the control flow (the tests for the first one had passed a couple days ago, and the second one was merged in after that, is my current theory for how that happened).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203477842651432) by [Unito](https://www.unito.io)

fix type issue from two PRs with conflicting assumptions

---

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx

The route for the "Review for 20XX" UI element on CommentsItem previously linked to `/reviews/${year}`. That route format was basically deprecated going forward, but we need to continue supporting it for the 2018 and 2019 reviews.

Update review route

---

packages/lesswrong/lib/voting/votingSystems.tsx

from slack:
>voting on comments appears to be a bit broken right now:
> - on posts I can do one vote (up/down, or agree/disagree), but then I can’t change it after that (or add both an agree and and upvote)
> - on subforums I can’t vote on threads at all, and I have the same problem as above voting on the replies to posts
This fixes the acute problem, although there are still some bugs in the new client side voting thing. If you cast a lot of votes quickly you can end up with a number that doesn't make sense

Fix comment voting bugs

---

packages/lesswrong/lib/collections/comments/schema.ts
packages/lesswrong/lib/voting/votingSystems.tsx

`getVotingSystemForDocument` would previously return the default voting system so agreement votes would be ignored
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203481267548313) by [Unito](https://www.unito.io)

Fix agreement voting on subforums

---

packages/lesswrong/themes/themeNames.ts

Consider this, like, an open source contribution from a user who wants the feature.
I checked this out on an assortment of LW-specialized pages, but of course I can't do a perfect job testing without your data. However, I expect the combination of y'all already having dark mode, and us having caught the small issues with useTheme to make this very low risk.
This does *not* set the default to be auto. Just allows users (such as myself) to select it as an option from the dropdown.
The benefit of this is that I won't have to burn my eyes reading LW at 9pm hours after sundown, while also maintaining my nice, sunny UI during the day. About 50% of users have a computer that changes theme based on time of day according to my scientific poll: …

Enable auto as an option for LW users set their theme to

---

packages/lesswrong/components/review/PostsItemReviewVote.tsx

Previously if you voted a post at "0", it wouldn't show up in the postslist, and would just say "vote". Now it is different:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203484217604758) by [Unito](https://www.unito.io)

Display non-review-votes vs 0-review-votes differently

---

packages/lesswrong/components/review/ReviewVotingPage.tsx

– changes the name of "Needs Vote" sorting option to not be misleading, and include a tooltip
– removes "sort by vote total" except during the Review Phase
– changes AF vote total sorting to require being on LW, rather than Not EA Forum (since if other non-EA-forum Forum Magnum sites want to do a review they wouldn't be able to use AF karma)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203484266597388) by [Unito](https://www.unito.io)

Rename "Needs Vote", add tooltip

---

packages/lesswrong/lib/alignment-forum/comments/views.ts
packages/lesswrong/lib/types/collectionTypes.ts
packages/lesswrong/lib/vulcan-core/default_resolvers.ts

We've had occassional issues where AF admins loading the front page of LW caused extremely slow queries (full table scans on `comments`).  After some investigation, I realized that the trigger was having 10 or more comments suggested for alignment, and some more digging revealed that default resolver logic wasn't passing through view-derived parameter options for the `count` query that only gets run when `enableTotal: true` and there are at least as many documents returned as the `limit`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203484348434834) by [Unito](https://www.unito.io)

pass through index hint for enableTotal count queries

---

README.md
scripts/postinstall.sh

Note that postinstall will not fail your install for not having perl. The addition raises the salience of needing perl so you are better prepared for needing to write your first migration.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203497377055713) by [Unito](https://www.unito.io)

Add note to README, postinstall.sh about perl

---

packages/lesswrong/lib/sql/Query.ts
packages/lesswrong/unitTests/sql/SelectQuery.tests.ts

Small bug in query builder selectors when using `{$eq: null}` or `{$ne: null}` which blocks migrating sequences. These currently get compiled as `"x" = NULL` and `"x" <> null`, but they should be `"x" IS NULL` and `"x" IS NOT NULL`.

Fix null comparison bug in query builder

---

packages/lesswrong/components/tagging/usePersonalBlogpostInfo.tsx

Introduced in: https://github.com/ForumMagnum/ForumMagnum/commit/da2686822264944f7b59f3e39bd0ee98308f0947
I did a few regex-searches looking for other instances of the same file but didn't find any outside of this file.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203525976937303) by [Unito](https://www.unito.io)

Fix typos introduced by a single-to-double-quotes conversion hitting apostrophes

---

packages/lesswrong/components/tagging/FilterMode.tsx

Previously:
Now:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203527696864551) by [Unito](https://www.unito.io)

Fix too much margin on filter mode cards

---

packages/lesswrong/components/ea-forum/EASequencesHome.tsx
packages/lesswrong/components/tagging/FilterMode.tsx
packages/lesswrong/components/tagging/TagSubforumPage2.tsx
packages/lesswrong/lib/collections/comments/views.ts
packages/lesswrong/lib/components.ts

Fixing a few console errors:
1. missing key error on subforum page caused by empty fragment
2. validate DOM nesting error on sequences page
3. missing `importComponent` call for `SequencePreview`
4. `isMobile` causing SSR issues with Material UI on the homepage filter section — replaced with breakpoints
5. Removed a duplicate index on comments
6. Investigated but didn't fix an SSR issue with MUI Tabs; left a TODO comment here: https://github.com/ForumMagnum/ForumMagnum/commit/40a8c3e51adfd256ae6306f17b1a15b26efb4e56
Fixes #6192
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203526503968868) by [Unito](https://www.unito.io)

Console error fixes

---

packages/lesswrong/components/Layout.tsx

Removes the normal sidebar, allowing the collection page to display properly with it's new ToC.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203537654348270) by [Unito](https://www.unito.io)

Fix table of contenets for highlights and eaHandbook

---

packages/lesswrong/server/editor/utils.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203546286091065) by [Unito](https://www.unito.io)

Don't initialize mathjax on the server when running migrations

---

packages/lesswrong/components/posts/PostsPage/PostActions.tsx

I kept accidentally duplicating my event while trying to edit it, which I found pretty annoying. Not sure how intentional putting the "duplicate event" button on top was but this seems like an improvement to me. Can ForumGate it if EA folk have strong preferences.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203542357000302) by [Unito](https://www.unito.io)

Edit post is always at top

---

packages/lesswrong/components/review/FrontpageReviewWidget.tsx
packages/lesswrong/lib/collections/posts/views.ts
packages/lesswrong/lib/reviewUtils.tsx
packages/lesswrong/server/notificationCallbacks.tsx
packages/lesswrong/server/recommendations.ts

This makes it so that:
– during the last day of each phase, there's a warning about the number of hours remaining.
– makes it so that each phase of the review shows the right combination of posts, refactoring things to avoid magic numbers that had previously gotten out of sync.
– fixes a minor UI issue.
And, throughout the phase, the hoverover has an indication on how many hours are remaining
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203550276692339) by [Unito](https://www.unito.io)

Final day warning

---

packages/lesswrong/components/review/ReviewVoteTableRow.tsx

During the review phase, all posts had an unnecessary 140 px width which looked super weird. I removed it, and checked how it looked in the other two phases. Seemed to be fine.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203551100684073) by [Unito](https://www.unito.io)

ChangeWidthOfReviewVotes

---

packages/lesswrong/components/review/ReviewVoteTableRow.tsx
packages/lesswrong/components/review/ReviewVotingPage.tsx

This allows users to see whether a post has gotten 1 or 2+ positive votes, so they can make sure to upvote things that need them.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203557461267479) by [Unito](https://www.unito.io)

NominationCount

---

packages/lesswrong/lib/collections/comments/views.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203558824642214) by [Unito](https://www.unito.io)

If a comment request is missing post ID, throw an exception rather than generating a crazy-slow DB query

---

packages/lesswrong/components/review/ReviewVoteTableRow.tsx

I.... was totally wrong to remove these lines, this code was doing an important thing. It looked wrong because I hadn't run the updateReviewVotes script yet, but once you do you want the line-length fixed to 140px.
Should have respected Arnold's Fence from 2021 which I'd forgotten the purpose of.
Reverts ForumMagnum/ForumMagnum#6296
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203566049030586) by [Unito](https://www.unito.io)

Revert "ChangeWidthOfReviewVotes"

---

packages/lesswrong/components/community/modules/LocalGroups.tsx
packages/lesswrong/components/community/modules/OnlineGroups.tsx
packages/lesswrong/components/tagging/SidebarMembersBox.tsx
packages/lesswrong/components/tagging/SubforumMember.tsx
packages/lesswrong/components/tagging/SubforumMembersDialog.tsx
packages/lesswrong/components/votes/EmojiReactionVoteOnComment.tsx
packages/lesswrong/lib/collections/tags/fragments.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/siteThemes/eaTheme.ts
packages/lesswrong/themes/themeType.ts
packages/lesswrong/themes/userThemes/darkMode.ts

In the subforum members list, we're now always displaying the organizers at the top, and marking them with a tag.
Dark mode:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203566005132954) by [Unito](https://www.unito.io)

[EA Forum only] pin subforum organizers to the top of the members list

---

packages/lesswrong/components/localGroups/GroupsMap.tsx

Someone from the EA Germany group asked me why there are no stars on the [standalone groups map](https://forum.effectivealtruism.org/groups-map?zoom=4&lat=51&lng=10). Turns out there was a bit of refactoring that missed that component.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203571805318348) by [Unito](https://www.unito.io)

fix displaying groups on the standalone groups map

---

packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx

https://github.com/ForumMagnum/ForumMagnum/commit/b091f826c16a098d07d0e8d27f5ed561e88154c2 modified the post header on question posts to count answers and their replies separately from non-answer comments, with the comment count being
```
post.commentCount - countAnswersAndDescendents(answers)
```
The trick is that if an answer is deleted:true, deletedPublic:true, then it's in the answers list (as a deleted-answer placeholder), but not included in post.commentCount.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203574035516829) by [Unito](https://www.unito.io)

Fix negative comment counts on question posts

---

scripts/runProduction.sh

This was causing an error when we tried changing the postgres password because a cached version of Credentials was being used
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203578855443735) by [Unito](https://www.unito.io)

Remove Credentials repo before restarting server

---

packages/lesswrong/server/callbacks/sunshineCallbackUtils.tsx

Occassionally we'll get a user in the moderation queue due to the `NEGATIVE_KARMA_USER_ALERT` moderator action, when they haven't been active on the site in years, because someone recently downvoted one of their posts or comments, and they were either already at negative karma or that tipped them over.  These users are pretty pointless to moderate since they aren't active on the site.
Changes this so that we only trigger the rule if they have:
- enough posts and comments that them being a "negative karma user" is meaningful
- any recent posts at all
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203525510787726) by [Unito](https://www.unito.io)

only moderate negative karma users who were recently active

---

packages/lesswrong/components/users/UsersProfile.tsx

It's often pretty annoying to need to go into a DB client to fetch a user's id from their slug.  Just add a "copy to clipboard" icon next to `Register RSS` (already an admin-only option).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203558310382418) by [Unito](https://www.unito.io)

show user id on users profiles to admins

---

packages/lesswrong/components/comments/CommentOnPostWithReplies.tsx
packages/lesswrong/components/comments/CommentWithReplies.tsx
packages/lesswrong/components/comments/CommentsNode.tsx
packages/lesswrong/components/comments/commentTree.ts
packages/lesswrong/components/posts/PostsItem2.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionTag.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionThread.tsx
packages/lesswrong/components/review/ReviewPostComments.tsx

We have a `markAsRead` callback that gets triggered when you expand a comment tree. It primarily records a post view, but also triggers several UI changes at once — unread comment styling disappears for all comments on the post, the post highlight length can change, and longer comments are truncated to a single line, which can easily cause the comment you're looking at to jump off-screen.
I get the impression that some of this is a UI bug (the jumping offscreen in particular seems like it), but in any case the value add of recording a post view doesn't feel worth the swarm of UI updates, which all feel unexpected and unwanted to me as a user. This PR opts to remove that markAsRead callback entirely.
Note that there are two places where a local callback coincidentally called markAsRead …

Fix UI jumps caused by expanding comment tree

---

packages/lesswrong/lib/vulcan-core/default_resolvers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203598713233724) by [Unito](https://www.unito.io)
We had an issue where a bot crawling the GreaterWrong front page clicking Next a bunch of times, led to GreaterWrong making API requests to us with very large `skip` parameters. These were rapid enough and slow enough to bring down the DB.
This adds a maximum value of 2000 to the `offset` parameter in graphql queries. I believe the offset is never used by ForumMagnum itself, only by third-party API users, which will now be limited in how many pages deep they can query.

Add a maximum value for offset

---

packages/lesswrong/components/comments/ModerationGuidelines/EAModerationGuidelinesContent.ts
packages/lesswrong/components/posts/PostsHighlight.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionTag.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionThread.tsx
packages/lesswrong/components/tagging/TagSubforumPage2.tsx

This PR includes a few things:
1. Rename subforum "thread" to "discussion"
2. When subforum threads appear in Recent Discussion, they should have a distinctive header so it's clear what they are
3. Decrease the font sizes for posts in the subforum feed, so that they don't feel larger/heavier than discussion threads (this will be iterated upon when we add titles to subforum threads)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203590527405072) by [Unito](https://www.unito.io)

some UI improvements around subforum threads/discussions

---

packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
packages/lesswrong/components/ea-forum/TargetedJobAdSection.tsx

We're replacing the old job ads with one new one (more to come in Jan), plus now the ad no longer displays after the application deadline.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203614975418603) by [Unito](https://www.unito.io)

[EA Forum only] update list of job ads

---

packages/lesswrong/server/scripts/convertImagesToCloudinary.ts

Some browsers do not display images from insecure URLs if the page is loaded over HTTPS. We were previously using the insecure URL, which would cause these images to not load.
To replicate:
1. Find an image online that uses srcset (I used the one from [this page](https://css-tricks.com/a-guide-to-the-responsive-images-syntax-in-html/#using-srcset))
2. Drag it into a comment
3. Post the comment
4. Wait for the hook to run and upload to cloudinary
5. Reload the page
6. Observe that the image in the comment is not visible
I think this was introduced by #6138 
This PR is just to prevent the issue going forward, we will need a separate PR to fix the old stuff that was migrated
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203619144301402) by …

fix cdn https

---

packages/lesswrong/components/posts/AddToCalendar/makeUrls.ts

Been seeing this log pop up occassionally lately:
```
ReferenceError: window is not defined
at makeICSCalendarUrl (/usr/src/app/packages/lesswrong/components/posts/AddToCalendar/makeUrls.ts:74:87)
at makeUrls (/usr/src/app/packages/lesswrong/components/posts/AddToCalendar/makeUrls.ts:102:8)
at AddToCalendarButton (/usr/src/app/packages/lesswrong/components/posts/AddToCalendar/AddToCalendarButton.tsx:111:16)
```
Seems like we're referencing `window` during SSR sometimes.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203609024562840) by [Unito](https://www.unito.io)

don't reference window during ssr when generating ICS url

---

packages/lesswrong/components/comments/CommentsNode.tsx

Truncated/single-line comments remain that way even when scrolling to them after clicking "See in context".
**Original Behavior (after clicking "See in context")**
**New Behavior (after clicking "See in context")**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203609311025327) by [Unito](https://www.unito.io)

expand truncated and single-line comments after scrolling from See in context

---

packages/lesswrong/lib/sql/Query.ts
packages/lesswrong/unitTests/sql/SelectQuery.tests.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203626563247360) by [Unito](https://www.unito.io)

Allow 'in' comparisons with an empty value array

---

packages/lesswrong/server/callbacks/commentCallbacks.ts

We've had instances of spammers getting around moderation by creating unobjectionable comments, then editing them to contain spam. This PR causes those edits to contribute to the 'snooze' counter, the same as creating new posts and comments.
Fixes https://github.com/ForumMagnum/ForumMagnum/issues/4948
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203631351792292) by [Unito](https://www.unito.io)

Comment edits decrement snooze count

---

packages/lesswrong/lib/sql/SelectQuery.ts
packages/lesswrong/unitTests/sql/SelectQuery.tests.ts
packages/lesswrong/unitTests/sql/pipeline.tests.ts

This is a quick airport fix.
Someone reported via email a few days ago that sorting `allPosts` by "All Time" and "Recent Comments" was broken. This fixes that, and probably some other bugs too.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203635072261309) by [Unito](https://www.unito.io)

Emulate mongo behaviour when sorting nulls

---

packages/lesswrong/client.js
packages/lesswrong/client/clientStartup.ts
packages/lesswrong/client/datadogRum.ts
packages/lesswrong/lib/publicSettings.ts

See also this [credentials PR](https://github.com/centre-for-effective-altruism/ForumCredentials/pull/11), description copied from there:
> Real User Monitoring is moderately expensive, $1.80/1k sesssions and we have about 20k sessions/day (~$1000/month overall), so we may want to sample it down a bit. I have left the rate at 100% initially to see if it ends up being useful for debugging individual user issues, but if not we're not getting much value out of it we can reduce it to like 10%
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203594881396109) by [Unito](https://www.unito.io)

Add sample rate settings for datadog tracing

---

packages/lesswrong/lib/collections/posts/views.ts
packages/lesswrong/lib/sql/Query.ts
packages/lesswrong/unitTests/sql/SelectQuery.tests.ts

Another airport fix.
This one fixes sorting by `topAdjusted` (and some other minor bugs too). It includes:
- Implementing `$ifNull`
- Better handling of `$arrayElemAt` (this is still a bit janky and can almost certainly be further improved in the future, but for now I just want to kill this bug ASAP)
- Making synthetic field names resolvable
- A better index for `topAdjusted` (still isn't perfect, but it's better than what we were using before)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203634886862408) by [Unito](https://www.unito.io)

Fix topAdjusted sort

---

packages/lesswrong/components/review/ReviewVoteTableRow.tsx

Robert had suggested a code refactor for this that used `??` instead of `||`, but `||` was actually important here so that we didn't use the default `0` for quadraticVote
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203653880626696) by [Unito](https://www.unito.io)

Fix old review vote display

---

packages/lesswrong/lib/collections/users/collection.ts
packages/lesswrong/server/ckEditor/ckEditorCallbacks.ts

$addToSet hasn't been implemented in postgres yet, so fall back to doing the array spreading trick for now
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203656432056991) by [Unito](https://www.unito.io)

Add workaround for collaborative editing link sharing

---

packages/lesswrong/components/alignment-forum/AlignmentForumHome.tsx
packages/lesswrong/components/common/HeaderSubtitle.tsx
packages/lesswrong/components/review/FrontpageReviewWidget.tsx
packages/lesswrong/lib/reviewUtils.tsx
packages/lesswrong/themes/siteThemes/alignmentForumTheme.ts

After discussing with Oli it seemed probably net-positive to put the Review widget on the Alignment Forum. The Widget and Review Page already seems to work as expected (it filters for AF posts just by virtue of being on the Alignment Forum).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203668207941147) by [Unito](https://www.unito.io)

Add Review to Alignment Forum

---

packages/lesswrong/lib/collections/sequences/views.ts

I guess we just had this typo in the views and never noticed until now...
Fixes [this asana issue](https://app.asana.com/0/628521446211730/1203657517138944/f)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203710517594313) by [Unito](https://www.unito.io)

fix a typo affecting a couple Sequences views

---

packages/lesswrong/server/notificationCallbacks.tsx

We've gotten multiple reports of being spammed by these emails, so I'm temporarily stopping them until I have time to debug it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203715767696837) by [Unito](https://www.unito.io)

[EA Forum only] temporarily stop sending "event updated" emails

---

packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
packages/lesswrong/components/ea-forum/TargetedJobAdSection.tsx

Add six new job ads to the rotation, plus display the deadline when it's within two days from now.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203718160144346) by [Unito](https://www.unito.io)

[EA Forum only] add next batch of job ads

---

packages/lesswrong/components/comments/CommentsItem/CommentBottomCaveats.tsx
packages/lesswrong/lib/collections/comments/fragments.ts
packages/lesswrong/lib/collections/comments/views.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

In the event we turn on "hideUnreviewedAuthorComments". This dramatically improves the experience from "wtf happened to my comment" to "oh, I guess I need to wait". It is nevertheless not beautiful.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203753740008359) by [Unito](https://www.unito.io)

Allow users to see their own unreviewed comments

---

packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx

To match functionality added to the LW user profile [earlier](https://github.com/ForumMagnum/ForumMagnum/pull/6302).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203746748098306) by [Unito](https://www.unito.io)

admins can also copy userId from EAF profile

---

packages/lesswrong/components/review/KarmaVoteStripe.tsx
packages/lesswrong/components/review/ReviewQuickPage.tsx
packages/lesswrong/components/review/ReviewVoteTableRow.tsx
packages/lesswrong/components/review/ReviewVotingPage.tsx
packages/lesswrong/lib/collections/comments/helpers.ts
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/routes.ts

This PR 
– adds a "sort by karma vote" option to the /reviewVoting page
– changes the Quick Review Page UI to help highlight posts you've previously karma voted on, as follows: Instead of just grabbing the top 12 posts by AF Vote Total, it grabs the top 25 posts by Vote Total, and then sorts the ones you've voted on to the top. 
– fixes a random bug where the Quick Review Page wasn't loading on the Alignment Forum.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203761102119602) by [Unito](https://www.unito.io)

Review karma-vote UI

---

packages/lesswrong/components/comments/CommentsItem/CommentBottomCaveats.tsx
packages/lesswrong/components/comments/CommentsNewForm.tsx
packages/lesswrong/lib/collections/comments/views.ts
packages/lesswrong/lib/crud/cacheUpdates.ts
packages/lesswrong/lib/publicSettings.ts

Previously I was too worried about hiding comments which had gone live and received discussion before this setting was enabled. Now we will be able to set the date to the day we deploy the setting, and then only future comments will be hidden.
In order to make this efficient, I've added a `{postedAt:1}` to the default index.
Also: the prior behavior for new user comments was that they would be posted and then disappear into the void until a refresh. This PR fixes that with a bundleIsServer check.
*I am making the assumption that the only time `Comments.getParameters()` is called on the client is for Mingo.* I believe that is correct, but if I'm wrong it could allow people to see these comments. …

hideUnreviewedAuthorComments becomes a date after which we will hide comments

---

packages/lesswrong/components/review/ReviewsLeaderboard.tsx
packages/lesswrong/themes/createThemeDefaults.ts

Turned out this created a horrible interaction when you expanded the list, and was a dumb idea. Reverting it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203761737828272) by [Unito](https://www.unito.io)

Remove sticky positioning from reviewLeaderboard

---

packages/lesswrong/components/review/FrontpageReviewWidget.tsx
packages/lesswrong/components/review/UserReviewsProgressBar.tsx

Moves the timeRemaining to the right, so that it doesn't look as clunky next to the checkboxes
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203754920464044) by [Unito](https://www.unito.io)

Rearrange timeRemaining section on FrontpageReviewWidget

---

packages/lesswrong/components/sunshineDashboard/ModerationDashboard.tsx
packages/lesswrong/components/sunshineDashboard/UsersReviewInfoCard.tsx

I kept finding it annoying to scan for the non-flagged users on the /moderation page, which made it harder to get at least some user-processing done at times when I didn't have the spoons for serious mod processing.
Hard to share a screenshot without exposing semi-private mod information, but basically makes the names of the flagged users in the table-of-contents red, and gives a red border to flagged user info-boxes
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203747906391745) by [Unito](https://www.unito.io)

Flag UI on moderation page

---

packages/lesswrong/server/notificationCallbacks.tsx

Putting up this PR because it may take a while to figure out the correct policy on this, and in the meantime it's still important to stop notifications for spam comments on subforums (which we have seen a few of)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203713080775614) by [Unito](https://www.unito.io)

Block notifications from unreviewed users for subforum comments

---

packages/lesswrong/components/common/NewFeaturePulse.tsx
packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
packages/lesswrong/lib/components.ts

This PR adds a `NewFeaturePulse` component, designed to draw user attention to icons, and adds it to the podcast icon on posts. The result is an animated surrounding circle that pulses twice when the page loads. This only happens once per user, handled via cookies.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203650697950835) by [Unito](https://www.unito.io)

Podcast Feature Highlight

---

packages/lesswrong/lib/collections/comments/schema.ts
packages/lesswrong/lib/collections/posts/schema.tsx
packages/lesswrong/lib/collections/tags/schema.ts
packages/lesswrong/lib/crud/cacheUpdates.ts
packages/lesswrong/lib/types/collectionTypes.ts
packages/lesswrong/lib/utils/viewUtils.ts
packages/lesswrong/lib/vulcan-core/default_resolvers.ts
packages/lesswrong/lib/vulcan-lib/collections.ts
packages/lesswrong/server/recommendations.ts
packages/lesswrong/server/resolvers/postResolvers.ts
packages/lesswrong/server/rss.ts
packages/lesswrong/server/sideComments.ts
packages/lesswrong/server/tableOfContents.ts
packages/lesswrong/server/utils/feedUtil.ts

Refactor the views system a bit. Makes various places around the code-base that get the default view, use the view system via a more purposeful entry point instead. This disarms a footgun which I ran into in another branch, which was the motivation for doing this now: the thing you got back from `Collection.getParameters({}).selector` was *almost* a ready-to-use mongodb selector, except it can have `viewFieldNullOrMissing` in it if the particular collection's default view contains that. Existing usages lucked out of hitting this case, but some new code did.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203618950006734) by [Unito](https://www.unito.io)

Refactor views

---

packages/lesswrong/components/review/ReviewVotingPage.tsx

People who have "do not collapse comments to single line" are gonna have a bad time on the /reviewVoting page during the VOTING phase. This is fixable, but for immediate future I'm throwing up a warning about it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203769653931663) by [Unito](https://www.unito.io)

Add warning for people expanding singleline comments

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203609232846999) by [Unito](https://www.unito.io)

Non-AF posts loaded through AF redirect to LW

---

packages/lesswrong/components/comments/CommentsListMeta.tsx
packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
packages/lesswrong/components/icons/SettingsButton.tsx
packages/lesswrong/components/icons/SortButton.tsx
packages/lesswrong/components/posts/AllPostsPage.tsx
packages/lesswrong/components/posts/DraftsList.tsx
packages/lesswrong/components/users/UsersProfile.tsx
packages/lesswrong/lib/components.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203713947945019) by [Unito](https://www.unito.io)
* **Remove italic:** You rarely see italic used on buttons, menu items, product labels. It's usually preferred to use lighter colors and smaller font sizes if you want to deemphasise something.
* **Change icon:** The `sort` icon seems more suitable than the settings cog (I prefer the up down icon even more (see Asana screenshot below) but there was none in the Mui library so I started with the one they call `Sort`)

Sorted by UI: remove italic + change icon

---

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
packages/lesswrong/components/comments/SingleLineComment.tsx
packages/lesswrong/components/tagging/TopTagIcon.tsx

Fix embarrassing oversight, as well as more minor oversight. Here are both changes in one view:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203774583281319) by [Unito](https://www.unito.io)

Add icon to expanded comment on homepage, better no-icon view

---

packages/lesswrong/lib/reviewVoteUpdate.ts

reviewVoteUpdate.ts has a commented-out-query, designed to be run on NosqlBooster. I forgot to include the AF column, and wanted a bit of reminder text to help me avoid a footgun in NosqlBooster.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203778062260374) by [Unito](https://www.unito.io)

Add AF to review sample query

---

packages/lesswrong/components/comments/SideCommentIcon.tsx
packages/lesswrong/components/posts/PostActions/SetSideCommentVisibility.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203777333851032) by [Unito](https://www.unito.io)

Prevent side-comment icons from causing horiz scroll on mobile

---

packages/lesswrong/components/tagging/TopTagIcon.tsx

Not all of these are definitely going to be changed (Global Catastrophic Risk and Taking Action haven't been fully decided on yet), but as this will only be used for core tags there's no downside to adding them all now
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203789788301955) by [Unito](https://www.unito.io)

Add icons for new core tags

---

packages/lesswrong/lib/sql/Pipeline.ts
packages/lesswrong/lib/sql/SelectQuery.ts
packages/lesswrong/unitTests/sql/SelectQuery.tests.ts

This is a low priority bug but it ended up being pretty straight forward so I fixed it anyway.
After fixing it I found another related bug, but it's even lower priority and more complicated so [I added it to Asana](https://app.asana.com/0/628521446211730/1203768639931060/f).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203785448439126) by [Unito](https://www.unito.io)

Fix /topic/random page regression

---

packages/lesswrong/components/common/LatestPostsDiscussion.tsx

This is how it looked before:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203791931749992) by [Unito](https://www.unito.io)

Fix permanent discussion loading dots for logged out view

---

packages/lesswrong/lib/sql/Query.ts
packages/lesswrong/unitTests/sql/SelectQuery.tests.ts

This should fix the following bug reported on intercom:
> For some reason urls to my website both with https:// in front or even adding a www don’t seem to work
The bug due to incorrect casting of JSON strings when retrieved from inside a deep JSON object in Postgres. Previously we generated `("fmCrosspost"->'foreignPostId')::TEXT`, but this should be `("fmCrosspost"->>'foreignPostId')::TEXT` otherwise the cast to `TEXT` adds quotes around the actual string value. The cast to `TEXT` isn't technically needed anymore, but it doesn't hurt and removing it will make the code more complicated.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203789663692948) by [Unito](https://www.unito.io)

Fix casting of deep JSON strings

---

packages/lesswrong/components/posts/PostsList2.tsx

This PR fixes a bug reported on Slack by Lizka.
We show curated posts at the top of the home page feed, but hide them if they've already been read (but always show at least one even it's already been read). This is done by using 2 `PostsList2` components (the first just for curated posts and the second for the main feed) which are both wrapped in a single `HideRepeatedPostsContext` which prevents any post from being displayed multiple times.
The bug here is that we register posts as being shown in the context _before_ checking if we should hide them because they're a curated post that's already been read. This means that a post that gets hidden from the curated posts lists because it's already been read will also be hidden from the main feed, even if it should ordinarily be shown.

Fix HideRepeatedPostContext removing viewed curated posts from main post feed

---

packages/lesswrong/components/search/SearchBarResults.tsx

Removes the broken "af: true" button shown in this screenshot.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203778975319947) by [Unito](https://www.unito.io)

Remove broken search-refinement UI in AF search bar

---

packages/lesswrong/server/callbacks/alignment-forum/alignmentCommentCallbacks.ts

Should fix an issue where, if a comment is promoted to AF and brings its parents in a thread along with it, those comments don't get included in the comment count displayed on AF.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203777808097563) by [Unito](https://www.unito.io)

Recompute afCommentCount whenever comments move to/from AF

---

packages/lesswrong/components/review/ReviewsLeaderboard.tsx

It seemed like noticing "You were in the top 10" might be motivating for people trying to climb the leaderboard. The top 5 mostly consists of LessWrong team, who professionally review things, so there were fewer opportunities to notice yourself there.
Only affects the Review/LessWrong.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203813129081953) by [Unito](https://www.unito.io)

Increase Review Leaderboard default display to 10

---

packages/lesswrong/server/scripts/acceptMigrations.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203819946073465) by [Unito](https://www.unito.io)

Allow acceptsSchemaHash to use single quotes

---

packages/lesswrong/components/themes/useTheme.tsx
packages/lesswrong/lib/crud/withUpdate.tsx

This was leading to a bug where EA Forum developers who had set a theme on the LW version of localhost could not leave that theme.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203796962370363) by [Unito](https://www.unito.io)

Correctly remove theme cookie

---

packages/lesswrong/components/tagging/subforums/SidebarSubtagsBox.tsx

For visual simplicity, this PR truncates the 'Posts in this space are about' section to the first 8 topics, with a 'show all' link to display the full list.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203792410532330) by [Unito](https://www.unito.io)

Truncate subforum topics list

---

packages/lesswrong/components/search/SearchPageTabbed.tsx
packages/lesswrong/themes/themeType.ts

The relevant line is `"Quotes" and -minus signs are supported.`. PR best viewed with whitespace off.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203797018070141) by [Unito](https://www.unito.io)

Info icon with tooltip mentioning advanced search features on tabbed search page

---

.git-blame-ignore-revs
packages/lesswrong/lib/crud/withCreate.tsx
packages/lesswrong/lib/vulcan-core/default_mutations.ts
packages/lesswrong/server/vulcan-lib/apollo-server/graphqlTemplates.ts

Small quality of life improvements for devs. My syntax highlighter didn't like some graphql files, I'm guessing it applies to other VSCodes as well. Note the fun `.git-blame-ignore-revs`, ([documentation](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view)) which is maybe overkill here, but which I was excited to try out.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203832561106031) by [Unito](https://www.unito.io)

Add mutation debug loggers, format gql to avoid breaking syntax highlighting

---

packages/lesswrong/components/common/Header.tsx
packages/lesswrong/components/hooks/useUnreadNotifications.ts
packages/lesswrong/components/notifications/NotificationsMenu.tsx
packages/lesswrong/components/notifications/NotificationsMenuButton.tsx
packages/lesswrong/server.ts
packages/lesswrong/server/resolvers/notificationResolvers.ts

When you revisited an old tab, it would refresh your notifications (good) but not refresh your current-user object with its `lastNotificationsCheck` field; it would then use the stale last-checked date to decide that you had unread notifications, and show a number badge on the bell icon. This PR fixes that by moving the unread notifications count to a dedicated resolver, which always has an up to date `lastNotificationsCheck` because it runs server side.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203834707673252) by [Unito](https://www.unito.io)

Fix spurious bell-icon notifications when revisiting old tabs

---

packages/lesswrong/components/form-components/FormComponentPostEditorTagging.tsx
packages/lesswrong/components/tagging/FooterTagList.tsx
packages/lesswrong/lib/collections/posts/schema.tsx
packages/lesswrong/server/callbacks/postCallbacks.ts

Previously this UI only worked on post creation, now it works for editing drafts too (which is presumably how most time is spent editing posts).
I've made it still fall back to the FooterTagList for published posts because it includes information about all tagRel votes, not just ones done by the editing user, which is more likely to be necessary with posts that have been public for a while (and have had tags added by moderators)
There are edge cases with drafts where multiple people could vote on tags before it's published, in which case e.g. a tag may not be fully removed by changing it in the edit form, but I don't expect this to be that common
vs what it looks like for published posts:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/120383910307520 …

Enable improved tag editing in post edit form for drafts

---

packages/lesswrong/lib/sql/Query.ts
packages/lesswrong/unitTests/sql/SelectQuery.tests.ts

Per Will, it's preferable to always use (e.g.) `IS TRUE` over `= TRUE` in postgres. This PR replaces that automatically, in the same way as we already do for null cases.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203792267311289) by [Unito](https://www.unito.io)

Enforce 'IS TRUE/FALSE' over '= TRUE/FALSE' in postgres queries

---

packages/lesswrong/server/callbacks/postCallbacks.ts

This makes it so that accepting the TOS isn't required to create a shortform.
When testing, note that the bug only affects users who create their first shortform - adding a new shortform after the initial post is created bypasses this check anyway because its technically only adding a comment.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203844820934017) by [Unito](https://www.unito.io)

Don't require the user to accept TOS to post a shortform

---

.eslintrc.js
packages/lesswrong/components/editor/DraftJSEditor.tsx
packages/lesswrong/components/form-components/TagFlagToggleList.tsx
packages/lesswrong/components/posts/PostsAnalyticsPage.tsx
packages/lesswrong/components/posts/PostsEditForm.tsx
packages/lesswrong/components/posts/PostsNewForm.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUsersProfileInfo.tsx
packages/lesswrong/server/usedMuiStyles.ts

We had `<NoSSR>` components from `react-no-ssr` and from `@material-ui/core` and were split 50/50 between them. Also split 50/50 between being capitalized as `NoSsr` or `NoSSR` (orthogonal to which import was used). Make it consistent, using only the react-no-ssr one, capitalized `NoSSR`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203841381024678) by [Unito](https://www.unito.io)

Be consistent about which <NoSSR> we use

---

packages/lesswrong/components/common/LWTooltip.tsx
packages/lesswrong/components/localGroups/LocalGroupsList.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203850370498212) by [Unito](https://www.unito.io)

Fix LWTooltip eating its contents if no title is provided

---

packages/lesswrong/components/sunshineDashboard/ModerationDashboard.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUserPostsList.tsx

– on the moderation page, puts an icon for "has posts that are awaiting review before appearing on the site" in the table-of-contents
– always shows the "number of comments" data for new user posts
– show linkpost message on new user posts.

Minor UI improvements to new-user-queue

---

packages/lesswrong/unitTests/unitTestSetup.ts

The schema check unit test sometimes spuriously fails in CI due to hitting the 15 second jest timeout but I've not been able to reproduce the failure locally. This PR is an effort to try to fix it by increasing the timeout from 15 to 20 seconds. This may or may not fix the problem, but since the failures seem to be random I figure we may as well try this before spending a ton of time trying to debug it properly.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203846126372413) by [Unito](https://www.unito.io)

Increase unit test jest timeout

---

packages/lesswrong/lib/sql/PgCollection.ts
packages/lesswrong/server/vendor/synced-cron/synced-cron-server.ts

The cron history code detects duplicate database entries by allowing the insert query to throw a duplciate key error which it then catches and handles. However, `PgCollection` also sees this error and logs it to the console before it gets caught by the cron code which leads to a lot of log spam. This PR adds a "quiet" mode so we can disable Postgres error logging for this query.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203860417886965) by [Unito](https://www.unito.io)

Cron history log spam

---

packages/lesswrong/lib/collections/posts/views.ts
packages/lesswrong/lib/sql/Query.ts
packages/lesswrong/lib/utils/viewUtils.ts
packages/lesswrong/unitTests/sql/SelectQuery.tests.ts

This PR fixes pingbacks on the EA Forum which were broken when we migrated posts to Postgres. The solution here is to add a new mongo-like operator that is only used when we're in Postgres which can correctly generate the SQL without requiring schemas for deep JSON objects. This is a bit of a hack, but it's also pretty rare in the code base.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203859716354875) by [Unito](https://www.unito.io)

Fix pingbacks in Postgres

---

packages/lesswrong/server/fmCrosspost/resolvers.ts

I just created like a million test crossposts and now running the server without an x-post server running is a dumpster fire. This fixes that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203868589167062) by [Unito](https://www.unito.io)

Quiet log spam from x-post server not running

---

packages/lesswrong/components/books/Book2018Landing.tsx

Now: 
Previously: 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203901530487967) by [Unito](https://www.unito.io)

Fix 2018 books buy button

---

packages/lesswrong/lib/utils/viewUtils.ts
packages/lesswrong/server/resolvers/recentDiscussionFeed.ts
packages/lesswrong/server/utils/feedUtil.ts

TL;DR look at the code, `viewFieldAllowAny`.
***
In #6618, we introduced the concept of `mergeSelectors`, which fixed a bug with merging selectors with `$and` and `$or`. `mergeSelectors` replaced two[^1] places where we merged selectors. One place, in views, we used `_.merge`, which was a recursive merge, and also did some other fanciness. The other place was in `queryWithCutoff` in `feedUtil.ts`, where we were simply doing a spread merge, ie:
```ts
const merged = {
...selector1,
...selector2
}
```
In our `mergeSelectors` function, we used `_.merge` for the non-boolean-conjuctor parts of the selectors. It turns out the fanciness of `_.merge` introduced a bug. We were, in `recentDiscussionFeed.ts` relying on the non-fanciness of the spread method. Specifically, we were doing, in the end: …

Fix shortforms being hidden in recent discussion

---

packages/lesswrong/lib/SwitchingCollection.ts
packages/lesswrong/server/serverStartup.ts

We currently have in issue on dev where the user appears to be logged out when the server restarts, but is logged in after refreshing. This is caused by the page making the new request before the `SwitchingCollection` has had a change to poll the value in `mongo2pg_lock` meaning it thinks it's still a `MongoCollection` even after being migrated. The fix here is just to wait for the first poll to finish before allowing the server to start listening for requests.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203920886786302) by [Unito](https://www.unito.io)

Fix logout on server refresh

---

packages/lesswrong/components/comments/CommentsListSection.tsx
packages/lesswrong/components/sunshineDashboard/ModerationLog.tsx
packages/lesswrong/lib/collections/users/fragments.ts
packages/lesswrong/lib/collections/users/views.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

Adds a link to the moderation page at the bottom of post pages.
My guess is EAForum doesn't currently want this (they had previously hidden the moderation page from non-admins since it otherwise wasn't very discoverable and some people found it jarring to find out their moderation decisions were public). I can either forum-gate this for EA Forum, or remove the admin-gate for the /moderation page. 
Also fixes a bug in the /moderation page where people who'd only banned users from their personal blogposts weren't showing up. 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203897826008742) by [Unito](https://www.unito.io)

Moderation page link

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/lib/collections/posts/permissions.ts

We were running into some posts from unapproved users, who were nonetheless getting comments. Previously, unapproved posts were hidden at the frontend client level, and the view level, but not the post permissions level. This hid unapproved posts from most places you might normally find them, but somehow people keep finding little edge cases and start commenting before admins have approved.
This PR puts logic into Posts.checkAccess. 
I've tested that this results in:
– the post author can see the post
– an admin can see the post
– a random user cannot see the post (this is a change from status quo)
– post author can see the post on their user profile
– an admin can see the post on their user profile
– a random user cannot see the post on their user profile (this is a change from status …

Hide Unapproved Posts

---

packages/lesswrong/server.ts
packages/lesswrong/server/callbacks/commentCallbacks.ts
packages/lesswrong/server/deleteUserContent.ts

In the cases where we get users who want more than just account deactivation.
There's a couple open questions here:
- whether the comments should have `deletedPublic: true`, and if so, what the `deletedReason` should be
- whether we do in fact want to do this via `updateMutator` rather than e.g. `Collection.rawUpdateMany`.  I think we do, since that better preserves data integrity (i.e. callbacks get run as intended, etc).  Unfortunately this does make batch-updates impossible, which is why I also added a short sleep in between updates (to avoid hammering the server too hard).
- whether to do anything other than mark the user as `deleted` afterwards
Plausibly we also want to have this automatically run the `exportUserData` script first by default. …

script to delete user content when they request account deletion

---

packages/lesswrong/components/comments/CommentFrame.tsx
packages/lesswrong/components/comments/CommentWithReplies.tsx
packages/lesswrong/components/comments/CommentsNode.tsx
packages/lesswrong/components/tagging/subforums/SubforumSubforumTab.tsx

Previously:
Too small margins. Now they're all 32px.
Coauthored with @s-cheng
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203930648132696) by [Unito](https://www.unito.io)

Fix subforum feed margins

---

packages/lesswrong/components/comments/CommentOnSelection.tsx

Safari's reader mode can't handle post bodies being inside a `span` for comment-on-selection.  Changing that to a `div` fixes it, without any (obvious to me) side effects.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203942329172659) by [Unito](https://www.unito.io)

turn commentOnSelection span into a div for safari reader mode

---

packages/lesswrong/components/tagging/subforums/SubforumSubforumTab.tsx

Previously the post list wasn't respecting the default sort order (ex. when I tried to set Community's list to "Magic").
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203942661767003) by [Unito](https://www.unito.io)

fix subforum sorting in the list layout view

---

packages/lesswrong/server/scripts/migrateCollections.ts
scripts/loadDbSettings.ts

Copying the `databaseId` field from `DatabaseMetadata` requires a special case cast because we're storing a string directly in a JSONB field. I missed this in the initial PR since the dev database doesn't have a `databaseId`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203930424057421) by [Unito](https://www.unito.io)

Add special case for copying databaseId from DatabaseMetadata

---

packages/lesswrong/components/comments/CommentOnSelection.tsx
packages/lesswrong/components/posts/PostsPage/PostBody.tsx
packages/lesswrong/lib/betas.ts

Co-authored-by: "Jonathan Mustin" <jcmustin@gmail.com>
The only problem we could find with side comments was that they introduce a horizontal scroll on mobile, so we just hide the button on mobile. This UI is required for the highlights project which will use the same toolbar
This PR makes side comments opt in, we could also just enable them fully if everyone. I don't anticipate any further changes before enabling them so this probably makes sense, but I thought people might want to try it on staging/prod before committing to enabling it fully
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203962583336773) by [Unito](https://www.unito.io)

Enable side comments on EA forum (as opt in)

---

packages/lesswrong/integrationTests/metatest.tests.ts
packages/lesswrong/integrationTests/moderation.server.tests.ts
packages/lesswrong/integrationTests/voting.tests.ts
packages/lesswrong/lib/mongo2PgLock.ts
packages/lesswrong/lib/sql/UpdateQuery.ts
packages/lesswrong/server/callbacks/votingCallbacks.ts
packages/lesswrong/server/sqlConnection.ts

A few fixes for tests that seem to have been broken in various Postgres migrations. The tests didn't fail on any particular migration branch, but there seems to be some interaction where they fail when the migrations are all merged together.
This includes pulling some of the code from #6611 to prevent errors from running the same queries concurently on multiple threads (which Jest does).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203976951017643) by [Unito](https://www.unito.io)

Fix tests 2023-02-15

---

packages/lesswrong/components/spotlights/SpotlightItem.tsx
packages/lesswrong/components/spotlights/SpotlightStartOrContinueReading.tsx

Currently:
New:
It's still a bit too tight, but I didn't feel like making a drastic change here.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203972060639705) by [Unito](https://www.unito.io)

Fix spotlight author mobile margin

---

packages/lesswrong/server/callbacks/commentCallbacks.ts
packages/lesswrong/server/deleteUserContent.ts

Needed to pass in an admin user explicitly for handling comments with children.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203963855083342) by [Unito](https://www.unito.io)

fix deleteUserContent script

---

packages/lesswrong/components/comments/CommentsItem/CommentsItemDate.tsx
packages/lesswrong/lib/reactRouterWrapper.tsx

Previously `furtherContext: "dateIcon"` would only be set if `scrollOnClick` was true (which in practice means when clicked on from the post page), which means it was impossible to measure how often this was being clicked outside the posts page
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203989509940726) by [Unito](https://www.unito.io)

Add eventProps option to Link, and use to always capture furtherContext in CommentsItemDate

---

packages/lesswrong/server/notificationCallbacksHelpers.tsx
packages/lesswrong/server/repos/UsersRepo.ts

Co-authored with @oetherington 
We were investigating a different event-related bug and ran into this one, where we weren't properly handling `$geoNear` for PG. It threw a user-facing error and prevented the event from being created.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203980231106780) by [Unito](https://www.unito.io)

fix a bug that can prevent publishing an event

---

packages/lesswrong/lib/reactRouterWrapper.tsx

We were getting a log like this because `eventProps` was passed all the way through to the DOM element
```
React does not recognize the `eventProps` prop on a DOM element...
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203996626197653) by [Unito](https://www.unito.io)

Fix log due to passing eventProps into DOM

---

packages/lesswrong/components/posts/PostsTimeBlock.tsx
packages/lesswrong/components/tagging/PostsTagsList.tsx

This might be a controversial idea, but seemed easy to just whip up a PR to showcase it. If either @darkruby501 or @jpaddison3 don't like it, can either give up on it or forum-gate.
But, after creating my PostsTagsList for the LW Review, I found myself wishing I could use it in some other contexts. I think it'd be reasonable to have it on the AllPosts page, so you can see what the tag distribution each month was, and possibly filter tags if you want:
You might want instead to do some fancier thing that has something more like fully-fledged tag-filters. A problem with the current implementation is it only shows you the post-totals for the posts that you've already loaded. 
I think it might make sense to only show this if you've set a custom limit in the url, i.e. by clicking on a month …

Add PostsTagsList to All Posts Timeblock

---

packages/lesswrong/server/loadDatabaseSettings.ts

As written, any errors thrown from database queries run in `loadDatabaseSettingsPostgres` weren't getting caught.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203997411654152) by [Unito](https://www.unito.io)

await call to load db settings for try/catch'

---

packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsItem.tsx
packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsList.tsx
packages/lesswrong/lib/collections/posts/fragments.ts
packages/lesswrong/lib/collections/posts/views.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

This has curated suggestion items let you know if there's existing audio for the post, and let's you filter the list to show only posts with audio:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203951917547416) by [Unito](https://www.unito.io)

add audio to suggest curated

---

packages/lesswrong/lib/collections/lwevents/collection.ts
packages/lesswrong/server/scripts/migrateCollections.ts

Still haven't 100% decided whether or not to run this script locally or on AWS, but either way this script seems to actually work unlike the old one (at the expense of not being able to read some old historical data whilst it's still being copied over, but this seems fine for LWEvents in a way that it wouldn't be for other collections).
Part 2 in #6694
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203977063021944) by [Unito](https://www.unito.io)

EA PG LWEvents Part 1

---

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
packages/lesswrong/components/comments/SingleLineComment.tsx
packages/lesswrong/components/questions/Answer.tsx
packages/lesswrong/lib/collections/comments/schema.ts

This is just a quick change to make the UI feel more consistent, plus I thought it was weird for [this comment](https://forum.effectivealtruism.org/posts/99tnp7Jpts7Gssq7J/transitioning-to-an-advisory-role?commentId=gFmhPZwQXvxnsC6Ap#comments) to be marked as "promoted". It's possible there are two different use cases here and we should have both "pinned" and "promoted" comments, but since this feature is rarely used as-is that seems unlikely to be prioritized.
See more related discussion in [this slack thread](https://cea-core.slack.com/archives/CJY3ZKP62/p1676921967213059).
Old:
-----
New:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204009069511717) by [Unito](https://www.unito.io)

rename "promoted" comments to "pinned" comments

---

packages/lesswrong/lib/sql/UpdateQuery.ts
packages/lesswrong/server/repos/ConversationsRepo.ts
packages/lesswrong/server/repos/LocalgroupsRepo.ts
packages/lesswrong/server/repos/VotesRepo.ts
packages/lesswrong/server/repos/index.ts
packages/lesswrong/server/scripts/mergeAccounts.ts
packages/lesswrong/unitTests/sql/UpdateQuery.tests.ts

There are several queries in the `mergeAccounts` script that don't work properly in postgres. This PR fixes these issues.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203995349834364) by [Unito](https://www.unito.io)

Fix merge accounts script in postgres

---

packages/lesswrong/lib/collections/conversations/permissions.ts

Still need to debug what exactly happened to create a conversation without any participantIds, but it shouldn't cause all other conversations to fail to load (which is what currently happens).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204009092931211) by [Unito](https://www.unito.io)

conversations missing participant ids crash the moderatorInbox

---

packages/lesswrong/components/sunshineDashboard/CommentKarmaWithPreview.tsx
packages/lesswrong/components/sunshineDashboard/ModeratorUserInfo/ContentSummaryRows.tsx
packages/lesswrong/components/sunshineDashboard/PostKarmaWithPreview.tsx

Make it easier to skim for newer content in the moderator sidebar/page
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204042294687164) by [Unito](https://www.unito.io)

Highlight new comments/posts on sunshine info

---

packages/lesswrong/server/scripts/convertImagesToCloudinary.ts

We're serving totally uncompressed images to users, which causes two problems:
1. significantly runs up our Cloudinary bills, since they charge through the nose for bandwidth usage (& site traffic has been going up a bunch lately)
2. probably makes for a pretty slow loading experience for users with mediocre internet connections
This is the "bare-minimum level of effort" patch; we could also do [format optimization](https://cloudinary.com/documentation/image_optimization#how_to_optimize_image_format) if we want.  I've tested this change in dev and it works fine, though it's not retroactive and I'm not sure it's worth writing a migration.
Happy to forum-gate if the EA forum doesn't want this change (or wants to test it out first, and/or have a more fine-tuned optimization).
┆Issue is …

set image quality to auto when mirroring image to cloudinary

---

packages/lesswrong/lib/collections/moderatorActions/helpers.ts

This removes vote "voteCount > 20" trigger for new user review (for both EA Forum and LessWrong), and removes the mapLocation trigger for non-EAForum forums, since in practice I'd never seen that help with voter fraud detection.
(I think it'd be good to use the new ModerationAction callbacks to trigger for users with more specific sets of voter-fraud-warning-signs, but that should be handled separately from the way it's handled here)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204092261760368) by [Unito](https://www.unito.io)

Remove voting and mapLocation triggers for review

---

packages/lesswrong/components/sunshineDashboard/ModeratorUserInfo/UserReviewStatus.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx

This moves some UI about new users into a shared component between SunshineNewUsersInfo and UsersReviewInfoCard
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204035859778667) by [Unito](https://www.unito.io)

Move new-user-info to shared UI

---

packages/lesswrong/server/manualMigrations/migrationUtils.ts
packages/lesswrong/server/scripts/migrateCollections.ts

A couple of problems came up whilst migrating DebouncerEvents to Postgres on staging and prod that didn't happen in dev. This PR fixes them:
- Sometimes createdAt is an int instead of a date
- Some of the selectors in getNextBatchByCreatedAt are wrong
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204055608269261) by [Unito](https://www.unito.io)

Debouncer events pg improvements

---

packages/lesswrong/server/scripts/convertImagesToCloudinary.ts

Apparently cloudinary's `url` manipulation spits out an `http` url by default (😡).  Didn't notice any issues in testing because they get auto-upgraded, mostly, but now there's a case in prod where it isn't being auto-upgraded.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204101353297904) by [Unito](https://www.unito.io)

make cloudinary urls use https

---

packages/lesswrong/components/community/Community.tsx
packages/lesswrong/components/community/modules/CommunityMembers.tsx
packages/lesswrong/components/community/modules/LocalGroups.tsx
packages/lesswrong/components/community/modules/OnlineGroups.tsx
packages/lesswrong/components/localGroups/LocalGroupPage.tsx
packages/lesswrong/components/posts/EventsUpcoming.tsx
packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx

Sentence case + small font size and weight changes to:
- Post header additional info
- Connect page
---
Before
After
---
Before
After
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204099973327274) by [Unito](https://www.unito.io)

More font-weight + sentence case tweaks

---

packages/lesswrong/components/vulcan-forms/FormComponent.tsx

A recent change made it such that form inputs could become `inline-block` and end up next to each other. This fixes that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204099854253225) by [Unito](https://www.unito.io)

fix form input layout

---

packages/lesswrong/components/sunshineDashboard/SunshineSendMessageWithDefaults.tsx
packages/lesswrong/components/sunshineDashboard/SunshineUserMessages.tsx

Replaces the "here's the total number of conversations" UI in the UsersReviewInfoCard, with a more specific list of individual mod conversations, which includes a direct link to each conversation.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204109652776465) by [Unito](https://www.unito.io)

Moderator pm UI

---

packages/lesswrong/components/sunshineDashboard/SunshineNewPostsList.tsx

SunshineNewPostsList only loads 10 posts, which has resulted in people being surprised that there's actually a lot more posts after we thought we were done processing it. This adds a load more.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204108754290816) by [Unito](https://www.unito.io)

Load more on SunshineNewPostsList

---

packages/lesswrong/components/form-components/FormComponentPostEditorTagging.tsx
packages/lesswrong/components/form-components/TagMultiselect.tsx
packages/lesswrong/components/search/TagsSearchAutoComplete.tsx
packages/lesswrong/components/tagging/AddTag.tsx
packages/lesswrong/components/tagging/AddTagButton.tsx
packages/lesswrong/components/tagging/FooterTagList.tsx
packages/lesswrong/components/tagging/TagSearchHit.tsx
packages/lesswrong/lib/collections/tags/permissions.ts

When we restricted voting on the "Community" topic, we started excluding it from the search results list. However, that also meant that users who had removed it as a frontpage filter could not longer re-add it. Here I'm fixing that by only excluding topics from the search results list when we are in a voting context, because by default users should be able to search for and find those topics.
Also fixed a related bug that actually **did** allow logged out users to search for "Community" and apply it to their frontpage.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204102367460112) by [Unito](https://www.unito.io)

users should be able to add the community topic filter to their frontpage

---

packages/lesswrong/server/emailComponents/EmailComment.tsx

Introduced in: [aafcfbad51520c9883c2e9602052483dddf998a8](https://github.com/ForumMagnum/ForumMagnum/commit/aafcfbad51520c9883c2e9602052483dddf998a8)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203860521514231) by [Unito](https://www.unito.io)

Fix missing space between author and title in EmailComment

---

packages/lesswrong/lib/collections/tags/permissions.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204125856401286) by [Unito](https://www.unito.io)

fix admins/mods ability to vote on community tag

---

packages/lesswrong/lib/collections/posts/helpers.ts
packages/lesswrong/server/resolvers/postResolvers.ts

Before the bug: Side-comment generation attempts to parse `null` using cheerio, generating an exception, which is swallowed. (Mostly swallowed. It showed up in Sentry I think.) The annotated HTML used by side-comments is null, so side-comments are disabled.
After the bug: Side-comment generation handles the `null` case by treating it as empty-string. The annotated HTML used by side-comments is empty-string, which takes precedence over the cross-post fetching code.
The fix: Handle the crosspost-with-missing-body case directly in the `sideComments` resolver.

Fix missing crosspost bodies due to null-vs-empty-string distinction with cheerio parsing

---

packages/lesswrong/components/posts/PostsListSettings.tsx

Requested by Lizka on Slack. It now matches the other checkbox labels, and doesn't mention the frontpage.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204097565097300) by [Unito](https://www.unito.io)

Make label for all posts page community setting consistent with other labels

---

Dockerfile
scripts/postinstall.sh

Nodejs changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.15.0
The thing that actually prompted me to do this was wanting to get rid of the warning on startup that reads
```
(node:2658) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time (Use `node --trace-warnings ...` to show where the warning was created)
```
which is removed in node 18.13. There are also some CVEs in versions between 18.12 and 18.15, but none of them look likely to be relevant (given that our server doesn't do its own SSL termination).
Note that the corresponding version number on a *dev* machine isn't affected by this; to do that upgrade you'd run `nvm install 18.15; nvm use 18`. …

Upgrade from node 18.12 to 18.15

---

packages/lesswrong/components/messaging/ConversationPage.tsx
packages/lesswrong/components/messaging/ConversationTitleEditForm.tsx
packages/lesswrong/components/messaging/ConversationWrapper.tsx
packages/lesswrong/components/messaging/MessageItem.tsx
packages/lesswrong/server/callbacks/messageCallbacks.ts

Previously: If you clicked Submit on the private-message conversation page with a blank message, it would send an empty message; some-but-not-all display and notifications of this message would be suppressed due to it being empty.
Now: If you click Subnit on the private-message conversation page with a blank message, it says "You cannot send an empty message" (almost identical to how it's handled if you try to  submit an empty comment on a post page.)
Also fixed up some doc-comments, an implicit any, and an awkward indirect construction of `terms`, while I was in the neighborhood.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204139963091783) by [Unito](https://www.unito.io)

Prevent sending empty private messages

---

packages/lesswrong/components/users/WrappedLoginForm.tsx

(LW specific, debug builds only) When you typed into one of the text fields on the login or signup form, you'd get a console warning about elements switching from unmanaged to managed, because the initial value given to the text input field was `undefined` but should have been `""`. Fix that by initializing the text boxes to `""` instead of `undefined`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204149797131079) by [Unito](https://www.unito.io)

Fix console warnings on the login form

---

packages/lesswrong/lib/instanceSettings.ts
packages/lesswrong/lib/vulcan-lib/collections.ts

It's currently difficult for EA Forum developers to test the site in LessWrong mode and vice versa because changing the `forumType` instance setting also changes the database type between Postgres and Mongo. This PR adds an optional instance setting called `forceCollectionType` of type `CollectionType` which can be used to separate this logic. That is, adding `"forceCollectionType": "pg"` as an instance setting for the EA Forum will allow us to set the `forumType` to `"LessWrong"` whilst still using Postgres, and LessWrong can use `"forceCollectionType": "mongo"` to test the site in EA Forum mode without needing all collections in Postgres.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204149385538374) by [Unito](https://www.unito.io)

Add `forceCollectionType` instance setting

---

packages/lesswrong/components/comments/ModerationGuidelines/ModerationGuidelinesBox.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204140242205691) by [Unito](https://www.unito.io)

Fix links inside moderation guidelines being unclickable if they also expand/collapse

---

packages/lesswrong/components/linkPreview/PostLinkPreview.tsx
packages/lesswrong/lib/crud/withSingle.ts

In development, it's fairly common for cross-synced RSS posts to contain links to real LessWrong posts. Attempting to load link-previews for those (which happens on the front page, because of Recent Discussion) produces voluminous console-error output, which can drown out real problems.
There was an existing `allowNull` option on the single resolver, which wasn't fully wired up. Wire it up the rest of the way, then pass allowNull in each of the link-preview queries, check for the null case explicitly, and case logMissingLinkPreview to give a less-excessive message about it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204150284798288) by [Unito](https://www.unito.io)

Explicit handling for missing link-previews

---

packages/lesswrong/components/posts/PostsListSettings.tsx

NB: this affects LW, @darkruby501. I doubt you will find it controversial.
Currently:
After this PR (the EA screenshot includes redesign):
@agnesstenlund you may want to look at this and go, "oh god this needs work". This goal of this PR is to make this less awful on the margin.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204195481855044) by [Unito](https://www.unito.io)

Fix awful mobile view of posts list settings to be somewhat less awful

---

packages/lesswrong/client/logging.ts
packages/lesswrong/components/common/Header.tsx
packages/lesswrong/components/common/SearchBar.tsx
packages/lesswrong/components/hooks/useOnNavigate.tsx
packages/lesswrong/lib/components.ts

On LW (but not EAF), the error `Missing component: TargetedJobAdSection` would appear in the client console. (Nothing is actually broken, though.) This was caused by unnecessary double-forum-gating in `components.ts`. Cleaned that up, and added a block-common to `components.ts` about why forum-gating isn't necessary in that file.
On all, the error `Async before callbacks should not return undefined. Please return the document/data instead` would appear 3x on client-navigation. This was caused by `useOnNavigate` using some janky Vulcan callbacks machinery that it didn't need, and passing `undefined` in a slot where some recently-introduced defensive programming wants to see a real value. Fix the error message by refactoring that area, replacing the Vulcan callback with a simple array. …

Fix two common spurious console-error messages

---

packages/lesswrong/components/ea-forum/EAHome.tsx
packages/lesswrong/components/ea-forum/EAHomeMainContent.tsx

This is what I meant by my PR comment on #6797 - we currently always render the `frontpageNode` even when it's not actually used. This PR changes it to render only when displayed.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204203525515822) by [Unito](https://www.unito.io)

Avoid rendering frontpage node unless it's actually needed

---

packages/lesswrong/components/posts/EAPostsItem.tsx

This PR indicates which posts have unread comments in the posts list:
[Figma](https://www.figma.com/file/OD4vJlLuWriHqG1WJXY4LV/Q1.1-2023?node-id=1208-13531&t=ep269ockHaCP0JcT-0)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204203039431269) by [Unito](https://www.unito.io)

EA New comment indicator

---

packages/lesswrong/components/ea-forum/EAHomeMainContent.tsx
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/themeType.ts
packages/lesswrong/themes/userThemes/darkMode.ts

Fixes [this issue](https://stackoverflow.com/questions/70446857/safari-linear-gradient) with linear-gradient on Safari on old iPhones
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204199000456546) by [Unito](https://www.unito.io)

fix topics bar fade on iOS Safari

---

packages/lesswrong/components/ea-forum/EAHomeCommunityPosts.tsx
packages/lesswrong/components/posts/PostsItemIcons.tsx
packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx

Before:
-----
After (styling matches the "View more" links at the top of the topic-specific post lists, functionality is the same as before):
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204207359211641) by [Unito](https://www.unito.io)

update community posts section "View more" styling, revert personal blogpost icon back to grey

---

packages/lesswrong/components/ea-forum/EAHomeMainContent.tsx

Changing the topics bar tabs from using the core topics default ordering to the one in [this doc](https://docs.google.com/document/d/1VBG6Uzpuagaf79n3QoTDFIEzN_YBH6KKWIqSdJO3X7w/edit#).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204207151483023) by [Unito](https://www.unito.io)

reorder topics bar tabs

---

packages/lesswrong/lib/betas.ts

We [enabled them](https://github.com/ForumMagnum/ForumMagnum/pull/6680) a month ago, but as per @SharangP's suggestion we are going to disable them (at least for now, will likely revisit in the future).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204228263467340) by [Unito](https://www.unito.io)

[EA Forum only] disable side-comments and comment-on-selection

---

packages/lesswrong/components/posts/EAPostsItem.tsx
packages/lesswrong/components/posts/PostsTimeBlock.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionThread.tsx
packages/lesswrong/components/sunshineDashboard/SunshineListItem.tsx
packages/lesswrong/lib/collections/posts/sortOrderOptions.tsx

Changes in this PR:
- Limit post titles to a single line
- Make comments expandable (this required an extra level of div nesting, so the diff looks a lot worse than it actually is)
- Fix the casing and date format on the all posts page (requested by Lizka)
- Sans serif for sunshine sidebar post titles
- Add a hyphen to "inflation-adjusted" (as requested by Lizka)
- Fix a bug where curated posts could be shown twice in the posts list

More EA redesign improvements

---

packages/lesswrong/components/common/TabNavigationMenu/FeaturedResourceBanner.tsx
packages/lesswrong/components/common/TabNavigationMenu/SubforumsList.tsx
packages/lesswrong/components/common/TabNavigationMenu/TabNavigationFooterItem.tsx
packages/lesswrong/components/common/TabNavigationMenu/TabNavigationItem.tsx
packages/lesswrong/components/common/TabNavigationMenu/TabNavigationMenu.tsx
packages/lesswrong/components/common/TabNavigationMenu/TabNavigationSubItem.tsx
packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
packages/lesswrong/themes/siteThemes/eaTheme.ts

This PR adds the new styles for the left-hand menu on the forum:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204215865270850) by [Unito](https://www.unito.io)

EA Left menu redesign

---

packages/lesswrong/components/posts/EAPostsItem.tsx

This PR removes the tag from the `EAPostsList`. For now, I've just commented it out as we're likely to experiment with adding it back in the future.

Remove EAPostsList tag

---

packages/lesswrong/components/posts/EAPostsItem.tsx
packages/lesswrong/components/posts/PostsItemIcons.tsx
packages/lesswrong/components/posts/PostsTitle.tsx
packages/lesswrong/components/questions/Answer.tsx
packages/lesswrong/components/questions/AnswersList.tsx

This PR updates the position of icons in the post title to match the same logic as on production. This is mainly just reverting parts of commit 5c316e751b52992d4c4b8de81b0c32fb9aede817. This also fixes the current bug where the curated star isn't shown on mobile.
Whilst I was looking at questions, I also went ahead and fixed the serif fonts in the answers section that should be sans-serif:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204229583378376) by [Unito](https://www.unito.io)

Redesign post icon positioning

---

packages/lesswrong/components/posts/PostsItemIcons.tsx
packages/lesswrong/components/posts/PostsTitle.tsx

This PR changes the curated star so that it's blue when it's on the left, but grey when it's on the right.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204230739737930) by [Unito](https://www.unito.io)

Fix curated star color

---

packages/lesswrong/lib/collections/votes/schema.ts
packages/lesswrong/server/callbacks/votingCallbacks.ts
packages/lesswrong/server/scripts/mergeAccounts.ts

EAF is re-evaluating how we calculate karma, and we found that recalculating karma for all users would cause lots of discrepancies from their current karma values. (See Table 6 in [this dashboard](https://app.hex.tech/9e4abdcd-b18c-49ca-acfc-3ec5249ddb1a/hex/19c39d4d-f783-4dab-8899-5ad8c54ee9b6/draft/logic).) While investigating this discrepancy, I discovered some bugs in `recomputeKarma()` and one bug that allowed post coauthor votes to award karma to all the post's authors. (I also found additional discrepancies that could not be explained by these, so I expect there are other voting-related bugs remaining.)
I haven't dug this deep into our voting before, so it's possible that some of these are not bugs and are intentional. …

coauthors cannot award karma to themselves or other post authors, plus fixes to recomputeKarma

---

package.json
packages/lesswrong/components/common/IntercomWrapper.tsx
packages/lesswrong/lib/vendor/react-intercom.js
yarn.lock

react-intercom produces a console warning about it using React's
componentWillReceiveProps, which is deprecated. Looking at the package
to see if it can be fixed with a version upgrade, I found that the
package (which lives at https://github.com/nhagen/react-intercom) has a
notice in its readme that says:
>> This package is no longer maintained
>
> This is an unofficial package, is not maintined by Intercom, and now should now be considered deprecated. I can not recommend using external dependencies to manage adding simple scripts to your page. Please refer to official Intercom documentation for installation instructions.
>
> Installing Intercom (and other similar third party scripts) is trivial without using a package like react-intercom. Using an unofficial dependency to do so may be …

Vendor react-intercom

---

packages/lesswrong/lib/collections/posts/fragments.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

In today's episode of why I hate Apollo: we currently have a bug where hovering over a link in a post preview will crash the entire recent discussions section if it's an internal link to a heading in that post. This is due to the fragment not containing the revision id. (You can test this on the dev database using the post http://localhost:3000/posts/fzRHvwwe2Jcz3sEHB/coauthor-voting-test).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204299594282647) by [Unito](https://www.unito.io)

Add _id to contents in HighlightWithHash fragment to fix caching bug

---

packages/lesswrong/server/debouncer.ts
packages/lesswrong/server/notificationCallbacks.tsx

Slack thread: https://app.slack.com/client/T3ERD8FQT/CJUN2UAFN/thread/CJUN2UAFN-1680045850.371559?cdn_fallback=1
The bug is introduced in a1de8c79d7b275619fb73de31c8b8f56ec1282df. Prior to this, if `EventDebouncer.recordEvent` is called with optional parameter `data` omitted, the resulting entry in the `debouncerEvents` collection has `pendingEvents: [null]`. This case is used by `curationEmailDelay`, which sends the non-admin version of the curation email 20 minutes after admins get it. That event-type doesn't use the data field because the post ID is already in the `key` field. However if the `pendingEvents` field is missing (as opposed empty or having a null in it), then when `_dispatchEvent` runs `console.log(``Handling ${events.length} grouped ${this.name} events)` it throws:
``` …
```

Fix sending of curation emails on LW

---

packages/lesswrong/server/authenticationMiddlewares.ts

This should allow GreaterWrong users to log in to EA Forum again.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204235263854497) by [Unito](https://www.unito.io)

Allow third party API users to authenticate via Auth0 access tokens.

---

packages/lesswrong/components/ea-forum/EAHomeMainContent.tsx
packages/lesswrong/components/posts/PostsTitle.tsx

This PR updates the topics bar to set the active tab via a query param. This allows us to return to the selected tab when the user clicks the back button, and to reset the tab to the Frontpage when clicking on the EA Forum logo.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204296064423690) by [Unito](https://www.unito.io)

topics bar returns to the selected tab when clicking "back", and goes to Frontpage tab when clicking logo

---

packages/lesswrong/components/sunshineDashboard/CommentKarmaWithPreview.tsx
packages/lesswrong/components/sunshineDashboard/PostKarmaWithPreview.tsx

When I made "new content" in the New User card show up as bold green, I accidentally got rid of the ability to easily scan for draft comments. This reworks the styling so you can identify drafts that are new-since-last-reviewed.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204222197420808) by [Unito](https://www.unito.io)

Clearer draft posts in new user info

---

packages/lesswrong/server/migrations/20230405T104221.debate_fields_hotfix.ts

These fields don't currently exist in Postgres due to a bug in commit cbc0699227622f1f85799d0815460c6e898a16f8.
This is preventing logins with Google, which just result in a blank page with a 500 error message.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204338517416228) by [Unito](https://www.unito.io)

Add migration for missing debates fields in users table

---

packages/lesswrong/components/comments/CommentsItem/CommentUserName.tsx
packages/lesswrong/components/posts/PostsPage/PostsAuthors.tsx
packages/lesswrong/components/posts/PostsPage/PostsCoauthor.tsx
packages/lesswrong/components/users/UsersName.tsx
packages/lesswrong/components/users/UsersNameDisplay.tsx
packages/lesswrong/components/users/UsersNameWrapper.tsx
packages/lesswrong/lib/collections/users/helpers.tsx

I have moved the icons down into the UsersNameDisplay component, which should make it easier to add the sprout icon to other places in future if we want to. I have only added it to post authors and coauthors for now
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204331207242035) by [Unito](https://www.unito.io)

Add sprout icon to post authors

---

packages/lesswrong/components/sunshineDashboard/FirstContentIcons.tsx
packages/lesswrong/components/sunshineDashboard/ModerationDashboard.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.tsx
packages/lesswrong/components/sunshineDashboard/UsersReviewInfoCard.tsx
packages/lesswrong/lib/collections/users/views.ts
packages/lesswrong/lib/components.ts

LessWrong is enabling review-required for new user's first comments. To go with this, we've added a comment icon in the same places that there's a post icon, to help us prioritizing reviewing users with new comments.
We've also added sorting to put these users higher up.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204334528936103) by [Unito](https://www.unito.io)

Add "Comment Icon" for Users Awaiting Review

---

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx

Fixes a minor bug introduced in https://github.com/ForumMagnum/ForumMagnum/pull/6872 which moved the menu class from CommentsItem into CommentsItemMeta
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204339504065002) by [Unito](https://www.unito.io)

Fix comments item menu opacity

---

packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx

New users need their first posts approved and are shown a tooltip saying we'll process usually within 24 hours. With the new influx, we'll change it to 72 hours since we need more time.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204327180176978) by [Unito](https://www.unito.io)

Change users awaiting approval notice from 24 -> 72 hours

---

packages/lesswrong/components/sequences/SequencesPage.tsx

Users need to be able to edit chapters in sequences that they own, so as to be able to add posts to them (since adding posts to sequences routes through editing chapters).
Need to verify that this is compatible with the other intended changes in https://github.com/ForumMagnum/ForumMagnum/pull/6839

fix chapter editing permission for users who own a sequence

---

packages/lesswrong/components/tagging/subforums/SubforumSubforumTab.tsx

Currently it's broken if there is no explicit sorting set
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204341550728192) by [Unito](https://www.unito.io)

Add default sorting back in to core topic pages

---

packages/lesswrong/components/posts/EAPostsItem.tsx

For now, we are hiding the reading time on post items for crossposts, because they will always say "1 min". Once crossposting is reworked, and we have the correct reading time, we can readd it.
Addresses https://github.com/ForumMagnum/ForumMagnum/issues/6880
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204344405658383) by [Unito](https://www.unito.io)

[EA Forum only] hide xpost reading time on post items

---

packages/lesswrong/components/search/SearchPageTabbed.tsx

This is a feature request from Lizka back in December that's been annoying me whilst I've been working on the search page. It now scrolls to the top of the results list when you choose a different results page.
[Relevant docs](https://www.algolia.com/doc/api-reference/widgets/scroll-to/react/)
[Asana](https://app.asana.com/0/628521446211730/1203630532352852/f)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204351861823248) by [Unito](https://www.unito.io)

Scroll to the top when changing search results page

---

packages/lesswrong/components/comments/CommentsNewForm.tsx
packages/lesswrong/components/editor/Editor.tsx
packages/lesswrong/components/posts/PostsNewForm.tsx

This PR makes it a bit more clear on LessWrong that comments and posts will be subject to more scrutiny than usual to new users.
It shouldn't have visible effects on EA Forum.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204356571295583) by [Unito](https://www.unito.io)

LessWrong specific warning for posts and comment moderation

---

packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx

This update from 'remove from queue' makes it (as originally intended) so that if applied to a user that's previously been approved, they no longer have the ability to make posts appear live without being approved by a moderator.
It also makes it so they properly appear in the recently-reviewed-users list, so it's easier to reverse the change if you want.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204356994402888) by [Unito](https://www.unito.io)

Make remove from queue prevent future posts from appearing

---

package.json
packages/lesswrong/lib/collections/posts/schema.tsx
packages/lesswrong/lib/collections/sequences/helpers.ts
packages/lesswrong/lib/loaders.ts
packages/lesswrong/lib/utils/schemaUtils.ts
packages/lesswrong/lib/utils/typeGuardUtils.ts
packages/lesswrong/lib/voting/votingSystems.tsx
packages/lesswrong/server/callbacks/messageCallbacks.ts
packages/lesswrong/server/resolvers/tagResolvers.ts
packages/lesswrong/server/voteServer.ts
yarn.lock

This crosses a major version; see https://github.com/graphql/dataloader/releases/tag/v2.0.0 for changes. The main change is that the timing of promise resolution has changed, in a way that avoids N+1 select in some cases. This also adds Typescript definitions, and changes how error handling works. We convert calls to loadMany to go through a wrapper, loadByIds, to change that error handling again to something friendlier.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204317164541382) by [Unito](https://www.unito.io)

Upgrade dataloader to 2.2.2

---

packages/lesswrong/components/sunshineDashboard/ModeratorUserInfo/UserReviewStatus.tsx

Broken because https://github.com/ForumMagnum/ForumMagnum/pull/6927 + showing the user name wrapper when `reviewedAt` exists, rather than both `reviewedAt` and `reviewedByUserId`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204368121055824) by [Unito](https://www.unito.io)

fix reviewed by display for users who were removed from the review queue

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/seasonal/HomepageMap/HomepageCommunityMap.tsx

Don't ask for the user location on the frontpage when rendering the community map.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204368865091039) by [Unito](https://www.unito.io)

don't ask for user location on frontpage

---

packages/lesswrong/server/useractivities/cron.ts

There is a bug in the frontpage algorithm job where rows get dropped by the `assertTableIntegrity` function due to having the wrong start and end date, this doesn't happen on every run, but like 30% of the time. Currently the algorithm is pretty broken because of this so I have set the parameters to effectively disable it
I think I've tracked this down to being caused by the job running twice every time, and sometimes the second job does `assertTableIntegrity` when the first job is halfway through updating the rows. I've added a random wait to test this theory, and also stopped actually deleting rows in assertTableIntegrity so that I can set the parameters back to the right values. I'm around 70% confident that this will fix the problem. If it does then I may try and track down why the …

Attempt to debug frontpage algorithm job

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/community/modules/CommunityMembersFullMap.tsx
packages/lesswrong/components/localGroups/LocalGroupPage.tsx
packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/themes/createThemeDefaults.ts
packages/lesswrong/themes/siteThemes/eaTheme.ts
packages/lesswrong/themes/themeType.ts

When we updated the top padding in `Layout.tsx`, that affected some groups/events-related pages, since many of those try to offset the default padding to be flush with the top of the page. For example, see how [this event's](https://forum.effectivealtruism.org/events/dMLhFC6tkwCTG57TP/ea-anu-discussion-dinner) banner image is cut off at the top. This PR updates the spacing on those pages.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204356068911951) by [Unito](https://www.unito.io)

fix top margin on a groups/events pages

---

packages/lesswrong/components/posts/EAPostsItem.tsx

Voting on a tag rel from the `EAPostsItem` component currently navigates to the post page. This PR stops this from happening.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204373215095169) by [Unito](https://www.unito.io)

Prevent tag rel votes from navigating to the post page

---

packages/lesswrong/components/sequences/ChaptersEditForm.tsx

For historical/technical reasons, there's a UI to add posts to sequences and, beneath it, an Add Draft Post button to open a different UI, in a modal, to add *draft* posts to sequences. The UI to add posts allows you to add multiple posts and rearrange them before you save the new list of posts all at once. In contrast, the modal to add *draft* posts adds the post and saves the list immediately. Because of this, if you add/rearrange posts in the first UI and don't save yet, and then you add a draft post, the saving of the draft post uses the old list, overwriting the changes you previously made.
This PR prevents that by disabling the the Add Draft Post button when there are unsaved changes in the first UI. If the user clicks on the button anyway, an explanatory message "Save your changes …

Improve UI for adding draft posts to sequences

---

packages/lesswrong/components/sunshineDashboard/ModeratorUserInfo/UserReviewStatus.tsx

Fixes a typo in the date formatting introduced in https://github.com/ForumMagnum/ForumMagnum/commit/6bf6ef52439ce57b87f16b087dc499240e827032  (`mm` is minutes, `MM` is months)
Screenshot of bug:

Fix "banned until" date format

---

packages/lesswrong/server/callbacks/commentCallbacks.ts
packages/lesswrong/server/callbacks/postCallbacks.ts
packages/lesswrong/server/callbacks/revisionCallbacks.ts
packages/lesswrong/server/tagging/tagCallbacks.ts
packages/lesswrong/server/tagging/tagsGraphQL.ts
packages/lesswrong/server/voteServer.ts

Need to allow users who are blocked from voting (due to being new/low karma) to self-vote via e.g. callbacks on new comments/posts/tags.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204386384847658) by [Unito](https://www.unito.io)

unblock automatic self-voting for low karma users

---

packages/lesswrong/components/comments/SingleLineComment.tsx

Fix single-line comments looking jankily misaligned when some of the comments have short bodies. This is caused by having used a flex-box without paying attention to grow/shrink behavior.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204368634001806) by [Unito](https://www.unito.io)

Fix misaligned single-line comments

---

packages/lesswrong/lib/collections/books/collection.ts
packages/lesswrong/lib/collections/chapters/collection.ts
packages/lesswrong/lib/collections/collections/collection.ts
packages/lesswrong/server/scripts/collectionMigrationFilters.ts
packages/lesswrong/server/scripts/migrateCollections.ts

See the EA forum version of this PR: https://github.com/ForumMagnum/ForumMagnum/pull/6120
LW also has some legacy test data in `Books`, `Collections`, and `Sequences` (the last of which isn't being migrated in this PR, but I figured it out while I working on the rest of it), which needs to be filtered out.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204417300804581) by [Unito](https://www.unito.io)

Migrate LW 'Books', 'Chapters' and 'Collections' to Postgres: Part 1/2

---

packages/lesswrong/components/comments/CommentsItem/CommentBody.tsx
packages/lesswrong/components/common/ContentItemBody.tsx
packages/lesswrong/components/posts/PostsPage/PostBody.tsx

The way we were doing this before (manually in PostBody and CommentBody) was causing an SSR mismatch
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204422452213173) by [Unito](https://www.unito.io)

Fix SSR by replacing strawpoll blocks in contentitembody

---

packages/lesswrong/lib/collections/advisorRequests/collection.ts
packages/lesswrong/lib/collections/bans/collection.ts
packages/lesswrong/lib/collections/emailTokens/collection.ts
packages/lesswrong/lib/collections/featuredResources/collection.ts
packages/lesswrong/lib/collections/gardencodes/collection.ts
packages/lesswrong/lib/collections/legacyData/collection.ts
packages/lesswrong/lib/collections/moderationTemplates/collection.ts
packages/lesswrong/lib/collections/petrovDayLaunchs/collection.ts
packages/lesswrong/lib/collections/podcastEpisodes/collection.ts
packages/lesswrong/lib/collections/podcasts/collection.ts
packages/lesswrong/lib/collections/reports/collection.ts
packages/lesswrong/lib/collections/rssfeeds/collection.ts
packages/lesswrong/lib/collections/spotlights/collection.ts
packages/lesswrong/server/scripts/migrateCollections.ts

See the EA forum version of this PR: https://github.com/ForumMagnum/ForumMagnum/pull/6237
We already did the `Migrations` collection, though.
Also, fixing a bug in the `migrateCollections` script, which does an early `return` out of the loop over collections in `copyData` if there are no records in that collection, instead of a `continue`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204419759297265) by [Unito](https://www.unito.io)

migrate trivial collections

---

packages/lesswrong/components/sunshineDashboard/ModerationDashboard.tsx
packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx
packages/lesswrong/components/sunshineDashboard/ModeratorUserInfo/UserReviewStatus.tsx
packages/lesswrong/components/sunshineDashboard/SunshineUserMessages.tsx
packages/lesswrong/components/sunshineDashboard/UsersReviewInfoCard.tsx
packages/lesswrong/lib/collections/moderatorActions/helpers.ts
packages/lesswrong/lib/collections/users/helpers.tsx
packages/lesswrong/server/callbacks/moderatorActionCallbacks.ts
packages/lesswrong/server/callbacks/sunshineCallbackUtils.tsx
packages/lesswrong/server/callbacks/votingCallbacks.ts

This PR fixes various bugs:
– fixes a display bug where typing in the notes field caused the "conversations with this user" UI to replicate endlessly. This was due to _two_ issues, and we only fixed one of them. One issue is that typing into the notes field makes lots of calls to the DB that cause the component to refreshed (I think it might be correct to make all the calls to the DB, but not sure why the component refreshed). The second problem was a bug in the UI code that I don't quite understand, but changing from the manual function I'd previously written to using the filter function fixes it.
– referral links were sometimes really long and displayed weird. This truncates them but also makes them into actual links you can click if you want, or right-click to copy link.
– the …

Fix various sunshine bugs + rate limits prevent further warning-flags

---

packages/lesswrong/components/sequences/BooksProgressBar.tsx
packages/lesswrong/components/sequences/CollectionsPage.tsx

This adds wordcount, and approximate pagecount and read-time, to Books and Collections. For books, it's (somewhat) hidden behind a tooltip. For collections it's only shown in the console log, to avoid looking too intimidating.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204298143568771) by [Unito](https://www.unito.io)

Add read-time to BooksProgressBar and collection

---

packages/lesswrong/components/vulcan-forms/FormWrapper.tsx
packages/lesswrong/lib/crud/withSingle.ts

The vulcan-forms refactoring PR (https://github.com/ForumMagnum/ForumMagnum/pull/6878) broken the edit-user form when editing users other than yourself (but not when editing yourself). This is because, when switching from the `withSingle` HoC to the `useSingle` hook, there was a case that `withSingle` handled that `useSingle` didn't: when no documentId is passed, but a slug is passed instead. Tightening the typechecking on both the `useSingle` and `FormWrapper` components confirmed that `UsersEditForm` and `EditProfileForm` were affected, but nothing else in the codebase was.
Fix by extending `useSingle` to be able to take a slug.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204427311388790) by [Unito](https://www.unito.io)

Fix the account-edit form for cross-user editing

---

packages/lesswrong/components/sunshineDashboard/ModeratorUserInfo/UserReviewStatus.tsx

My altAccounts UI was accidentally in a css styling that hid the lower half of it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204427555530668) by [Unito](https://www.unito.io)

Remove styling for altAccounts to fix bug

---

packages/lesswrong/components/editor/CKPostEditor.tsx
packages/lesswrong/components/posts/PostsPage/PostActions.tsx
packages/lesswrong/components/users/UsersMenu.tsx
packages/lesswrong/components/users/ViewSubscriptionsPage.tsx
packages/lesswrong/lib/collections/users/schema.ts
packages/lesswrong/lib/editor/make_editable.tsx
packages/lesswrong/lib/notificationTypes.tsx
packages/lesswrong/server/callbacks/postCallbacks.ts
packages/lesswrong/server/notificationTypesServer.tsx
packages/lesswrong/server/voteServer.ts

Rename debate to dialogue everywhere that's user-facing, block voting on dialogue responses on the server (since otherwise it can be done via API, via GreaterWrong, etc), and add more helpful instructions in the post editor placeholder/hint text for dialogues.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204444662353048) by [Unito](https://www.unito.io)

Debate dialogue cleanup

---

packages/lesswrong/components/comments/CommentsNode.tsx
packages/lesswrong/components/sunshineDashboard/ContentRejectionDialog.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUserCommentsList.tsx

Two minor UI improvements to the New User dashboard.
I'm not 100% sure if it's right to use "expandByDefault" to force comments to not be collapsed. I think in most cases where we'd want comments expanded by default, we also want them un-collapsed by default. The alternative is to build a separate "uncollapse by default". I think the terminology here is a bit confusing and annoying (I think what expandByDefault normally means is 'not-truncate-by-default', and it's unfortunate that expand is a reasonable antonym for "not expanded" and "not truncated")
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204445403449587) by [Unito](https://www.unito.io)

User Dashboard expand all comments, and display rejection reasons more nicely

---

packages/lesswrong/components/posts/PostsPage/PostsPageTitle.tsx
packages/lesswrong/components/votes/PostsVote.tsx
packages/lesswrong/components/votes/VoteArrowIcon.tsx

**Two fixes**
1. Karma alignment (affects LW too, since LW was also misaligned).
It's still not perfectly centered horizontally and I'm pulling my hair trying to fix it (says it still has 1px leftpadding after I removed the 1px leftpadding)
2. Post title size (has been bugging me that it's the same size as the h1 title inside of posts. We could make the headings smaller instead too, if this feels overly large)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204440401374055) by [Unito](https://www.unito.io)

Karma alignment + Post title font size

---

packages/lesswrong/server/voteServer.ts

We accidentally made it so dialog-participants couldn't submit a dialog post or comments, because it included a self-upvote that we'd mistakenly blocked. This fixes that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204465820056794) by [Unito](https://www.unito.io)

Fix dialog voting bug

---

packages/lesswrong/components/comments/CommentActions/CommentActions.tsx

This allowed non-admin users to see the author of deleted comments, so we're removing that menu option.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204461975098820) by [Unito](https://www.unito.io)

hide "Subscribe to posts by <author>" from menu of deleted comment

---

packages/lesswrong/server/languageModels/modGPT.ts

Basically, if a comment is deleted, no need to ask ModGPT about it
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204463636394508) by [Unito](https://www.unito.io)

[EA Forum only] ModGPT should skip deleted comments

---

packages/lesswrong/components/posts/PostsItemIntroSequence.tsx

`PostsItemIntroSequence` can optionally display a sequence image and the positioning of this image is currently pretty badly broken in Firefox due to a bug with the interaction between `height: 100%` and `width: auto`. This can be seen, for instance, in the introduction section of [the existential risk topic page](https://forum.effectivealtruism.org/topics/existential-risk?tab=wiki).
How it should look (in Chrome):
Currently in Firefox:
After this change:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204426430263270) by [Unito](https://www.unito.io)

Fix image position in Firefox for `PostsItemIntroSequence`

---

packages/lesswrong/lib/collections/commentModeratorActions/collection.ts
packages/lesswrong/lib/collections/comments/collection.ts
packages/lesswrong/lib/collections/postRelations/collection.ts
packages/lesswrong/lib/collections/posts/collection.ts
packages/lesswrong/lib/collections/readStatus/collection.ts
packages/lesswrong/lib/collections/revisions/collection.ts
packages/lesswrong/lib/collections/tagFlags/collection.ts
packages/lesswrong/lib/collections/tagRels/collection.ts
packages/lesswrong/lib/collections/tags/collection.ts
packages/lesswrong/lib/collections/userTagRels/collection.ts
packages/lesswrong/lib/collections/votes/collection.ts
packages/lesswrong/lib/helpers.ts
packages/lesswrong/server/callbacks/sunshineCallbackUtils.tsx
packages/lesswrong/server/manualMigrations/migrationUtils.ts
packages/lesswrong/server/scripts/migrateCollections.ts

In `Comments`, `Messages`, and `Revisions`, we had a few records with null-terminating characters (`\u0000`) which can't be represented as a string, and therefore couldn't be inserted into the `jsonb`-typed `contents` field in postgres.
In `ReadStatuses`, we had some records with `postId` values that weren't actual post IDs.  Some of those were post slugs, for some reason, which meant those are recoverable; others were random junk.  (Some of them were the string "null", which unfortunately is also a valid post slug.  I chose to exclude those, since that post was a draft and I doubt that's what those ReadStatuses were actually meant to point at.)
In `Votes` we had some imported agentFoundations votes which had `userId` shaped like `{ _str: $userId }`.
Collections in dev were migrated …

LW migrate posts, comments, tags, revisions, readstatuses, votes, etc

---

packages/lesswrong/components/recommendations/ConfigurableRecommendationsList.tsx
packages/lesswrong/components/recommendations/RecommendationsAlgorithmPicker.tsx
packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx

As per [this asana task](https://app.asana.com/0/628521446211730/1204155311038150/f), we're removing the "continue reading" and "bookmarks" portions of the "Recommendations" section on the home page, removing the customization options, and renaming it to be "Classic posts".
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204467013781286) by [Unito](https://www.unito.io)

[EA Forum only] hide continue reading and bookmarks from home page

---

packages/lesswrong/server/notificationCallbacks.tsx

This PR makes it so that post coauthors are treated the same way as the primary post author, with respect to comment notifications.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204480584712847) by [Unito](https://www.unito.io)

post coauthors get comment notifications by default

---

packages/lesswrong/components/posts/EAPostsItem.tsx
packages/lesswrong/components/posts/PostActions/PostActionsButton.tsx
packages/lesswrong/components/posts/PostsItemTrailingButtons.tsx

This PR moves the bookmark icon out of the EA Forum's post item into the three dots menu, and moves the three dots menu icon into the post item.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204480829488979) by [Unito](https://www.unito.io)

[EA Forum only] move bookmark icon out of post item, replace with three dots menu

---

packages/lesswrong/server/fmCrosspost/resolvers.ts

The frontpage of the forum was failing to load occasionally due to crosspost requests hanging (this could only happen when a crosspost appears in recent discussion). I don't know the underlying cause of the requests hanging, presumably it's a problem on the LW servers, but I've added a timeout so the page will load at least.
I have set this to 15s based on:
- the overall gateway timeout is 30s, so we want it to be much less than this to not risk hitting it
- in datadog 15s looks like about the upper limit of successful crosspost requests

Add timeout to crosspost requests so frontpage still loads

---

packages/lesswrong/components/comments/CommentPermalink.tsx
packages/lesswrong/components/comments/CommentWithReplies.tsx
packages/lesswrong/components/comments/CommentsNode.tsx
packages/lesswrong/components/comments/SideCommentIcon.tsx
packages/lesswrong/components/posts/PostsPreviewTooltip.tsx
packages/lesswrong/components/sunshineDashboard/CommentKarmaWithPreview.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUserCommentsList.tsx

So... last week I made a PR that used the "expandByDefault" flag (previously used to ensure comments weren't truncated) to also force comments to not be collapsed, because I needed some way to do that.
Then I turned around and immediately noticed a situation where I _do_ want them truncated, but don't want them collapsed.
So, this goes ahead and splits up that functionality, and makes comment hoverovers use the "forceUnCollapsed" flag but not the forceUnTruncated one.
I'm not thrilled with the names here but was lining them up to match with forceSingleline. Feel free to suggest alternatives. I capitalized both the "Un" and the "Collapsed" because otherwise the words blurred together too much for me. …

Separate out untruncate and uncollapse comments (and make comment hoverpreviews "forceUnCollapsed")

---

packages/lesswrong/lib/collections/tags/collection.ts
packages/lesswrong/server/recommendations.ts

This PR just handles the frontpage recommendations section. Post page recommendations are handled separately in the `posts-page-recommendations` branch.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204491599442865) by [Unito](https://www.unito.io)

Exclude april fools day posts from recommendations

---

packages/lesswrong/lib/collections/posts/views.ts

Bug reported for smalls. Some events (such as https://forum.effectivealtruism.org/events/e9zLaDDNupnciRhvy/presentation-and-discussion) are not showing up on the events page.
Suprisingly, it looks like this is actually just a legit bug in the selector that wasn't caused by the Postgres migration. When filtering by location, we include events that are either within the user's configured distance or are marked as `globalEvent`. Many online events, however, have a null `mongoLocation` and so are never returned. The change here is to include events with a null `mongoLocation`, but only if they're also marked as `onlineEvent`.
Maybe the hope was that such events would also be marked as `globalEvent`, but empirically that is often not the case. …

Show online events where mongoLocation is null

---

packages/lesswrong/components/posts/EAPostsItem.tsx
packages/lesswrong/components/posts/PostActions/PostActionsButton.tsx

Addressing @agnesstenlund's comments in https://github.com/ForumMagnum/ForumMagnum/pull/7033, as well as adjusting the post item for logged out users (who can't see the three dots menu)
Logged in view:
-----
Logged out view:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204490813164384) by [Unito](https://www.unito.io)

[EA Forum only] followup UI tweaks after removing post item bookmark icon

---

packages/lesswrong/client/datadogRum.ts
packages/lesswrong/client/datadogStart.ts
packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/CookieBanner/CookieBanner.tsx
packages/lesswrong/components/common/CookieBanner/CookieDialog.tsx
packages/lesswrong/components/common/CookieBanner/geolocation.ts
packages/lesswrong/components/common/IntercomWrapper.tsx
packages/lesswrong/components/common/hocTypes.ts
packages/lesswrong/components/hooks/useCookiesWithConsent.ts
packages/lesswrong/lib/cookies/callbacks.ts
packages/lesswrong/lib/cookies/cookies.ts
packages/lesswrong/lib/cookies/utils.ts

In this PR:
- forum gating
- geolocation gating
- logging an analytics event when a user accepts/declines
- some other refactoring
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204497406590711) by [Unito](https://www.unito.io)

Add geolocation to cookie banner (plus other cleanup)

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx

Dialogues would previously show `1 min read` (~0 words), because they were based on the post's contents' wordCount (which would be only the word count of the first dialogue response, because of how dialogues work).
This doesn't solve for showing read times in e.g. `EAPostsItem`, though, since you don't have all the comments that make up the dialogue contents there.  (That might have to be changed regardless when fixing the hover-over preview, which doesn't currently work for similar reasons.)
Not urgent, @jpaddison3 (if you want to think about this).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204492739799669) by [Unito](https://www.unito.io)

Show correct read time and word count for dialogues

---

packages/lesswrong/components/posts/AllPostsPage.tsx
packages/lesswrong/components/posts/DraftsList.tsx
packages/lesswrong/components/sequences/SequenceDraftsList.tsx
packages/lesswrong/components/users/UsersProfile.tsx

Revert a bunch of places where we replaced the gear icon with the double arrows (up & down, indicating sort), to make sure LW no longer has the double arrows icon.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204506521200113) by [Unito](https://www.unito.io)

replace double arrows icon with gear icon on LW

---

packages/lesswrong/components/posts/PostsAcceptTos.tsx
packages/lesswrong/components/vulcan-forms/Form.tsx
packages/lesswrong/server/callbacks/postCallbacks.ts
packages/lesswrong/server/resolvers/userResolvers.ts

Currently, if you enter some text into the new post/edit post/new question/etc. pages and then click the checkbox to accept the TOS, all the text you entered will be deleted.
If you've already accepted the TOS, you can test this easily with `UPDATE "Users" SET "acceptedTos" = FALSE WHERE slug = '...'`.

Prevent form inputs from clearing after accepting the TOS

---

packages/lesswrong/server/scripts/algoliaExport.ts
packages/lesswrong/server/search/utils.ts

We now mark some comments and posts from users as rejected. These should not show on the main site but currently are still in search. This attempts to fix it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204510383359734) by [Unito](https://www.unito.io)

Exclude Rejected Content from Search

---

packages/lesswrong/lib/sql/AddFieldQuery.ts
packages/lesswrong/lib/sql/DropFieldQuery.ts
packages/lesswrong/server/migrations/meta/utils.ts

When I tried to drop a field, the [migration](https://github.com/ForumMagnum/ForumMagnum/actions/runs/4866025205/jobs/8677068931?pr=7105) on staging gave me this error:
Error: Migration 20230502T160034.drop_noComicSans_from_Users.ts (up) failed: Original error: Field "noComicSans" does not exist in the schema
Hopefully this PR will fix that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204518808397947) by [Unito](https://www.unito.io)

fix dropping a field thats not in the schema

---

packages/lesswrong/components/comments/SingleLineComment.tsx
packages/lesswrong/components/ea-forum/EATermsOfUsePage.tsx
packages/lesswrong/components/search/SequencesSearchHit.tsx
packages/lesswrong/components/tagging/TagPage.tsx
packages/lesswrong/components/tagging/subforums/TagSubforumPage2.tsx
packages/lesswrong/components/users/NewUserCompleteProfile.tsx

This PR switches some more serif fonts to sans-serif. It probably doesn't need a full design review, but FYI @agnesstenlund.
- Date on the terms of service page
- Sub-topic/parent topic on the tage page:
- Karma and time in single-line versions of answers (ie; in recent discussions):
- Topic titles on "subforum" page (I don't know what we call this now subforums are dead?):
- Sequence titles in search results:
- Profile completion page for new users (I also removed the italics - awaiting controversy):
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204513592864765) by [Unito](https://www.unito.io)

[EA] More sans serif

---

packages/lesswrong/server/migrations/20230502T083210.add_shortformFrontpage.ts

Removes redundant (& slow) update operation which is already taken care of by Postgres when adding a new column with a `DEFAULT` value.

Remove unnecessary line from shortformFrontpage migration

---

packages/lesswrong/components/posts/PostsItemIcons.tsx
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/themeType.ts

**Why?**
At a glance curated posts look too much like pinned posts, which we think may lead to people ignoring them.
**Before**
**After**
Dark mode
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204522650370154) by [Unito](https://www.unito.io)

Yellow curated icon

---

packages/lesswrong/components/hooks/useCookiesWithConsent.ts

There is an infinite loop happening somehow involving this code path. I haven't been able to reproduce it, but commenting it out should stop it at least, and the behaviour in Google Tag Manager that this is supposed to trigger is disabled currently anyway
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204534744604089) by [Unito](https://www.unito.io)

Disable useEffect to fix infinite loop in useCookiePreferences

---

packages/lesswrong/components/common/CookieBanner/geolocation.ts

We were getting a [rate limit response](https://ipapi.co/ratelimited/) on the unpaid plan. I did find a bug where multiple requests could be made per page load due to new requests being made when existing ones were in flight. This was only ~5 per page load though, so I still think this rate limit was spurious seeing as it should allow 30,000 requests per month (and we cache the response for 48 hours)
Anyway, this PR adds an api key for the paid plan (which allows 60,000 requests per month, and allows us to track usage). It also fixes the problem of having multiple requests in flight

Add api key and fix thundering herd for ipapi

---

packages/lesswrong/client/reCaptcha.ts
packages/lesswrong/components/hooks/useCookiesWithConsent.ts
packages/lesswrong/lib/cookies/callbacks.ts
packages/lesswrong/lib/cookies/cookies.ts

The things here are:
- There was no expiry date set on COOKIE_CONSENT_TIMESTAMP_COOKIE or  COOKIE_PREFERENCES_COOKIE which meant they expired when the browser was closed, I've added an expiry date
- There were a bunch of cookies being set under the .google.com domain by google recaptcha, only when you log in (I previously thought these were to do with the actual google login). It would be nice if we could mark these as essential but the [advice](https://measuredcollective.com/gdpr-recaptcha-how-to-stay-compliant-with-gdpr/) is that they are fairly strongly unessential. I have made it so you need to accept cookies for recaptcha to work
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204537616639694) by [Unito](https://www.unito.io)

Add expiry date to cookie preferences and handle reCaptcha cookies

---

packages/lesswrong/lib/collections/comments/schema.ts

We've had this error in the logs for a long time:
`Cannot return null for non-nullable field Comment.suggestForAlignmentUsers`
The issue seems to be that canRead for was set to 'members' rather than 'guests', which meant that it returned null (rather than an empty array), meanwhile arrayOfForeignKeysField defines the graphql field type to be non-nullable.
Apart from log spam, the result is that the "There are ${n} comments pending acceptance to the Alignment Forum.  View them on LessWrong." message wasn't showing up for anyone who was logged out.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204535770213073) by [Unito](https://www.unito.io)

fix permission on suggestForAlignmentUsers causing graphql errors

---

packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx

Ruby found the old wording somewhat confusing.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204526745118499) by [Unito](https://www.unito.io)

Change wording of first post moderation

---

packages/lesswrong/server/notificationCallbacks.tsx

This seems to be triggering because, when someone new RSVPs to an event without a defined endTime, the endTime on the old post is null but the endTime on the new post is undefined, and moment(null) is not the same as moment(undefined).  I'm guessing migrating posts changed something about how missing/null fields work here.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204543039575511) by [Unito](https://www.unito.io)

don't trigger notifications for event updates on events with unset times

---

packages/lesswrong/client.js
packages/lesswrong/client/reCaptcha.ts
packages/lesswrong/client/reCaptchaStart.ts

The `initReCaptcha` function was running on import which caused it to run on the server when it shouldn't
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204544175364068) by [Unito](https://www.unito.io)

Stop recaptcha from running on the server

---

packages/lesswrong/server/scripts/backfillParentTags.ts
packages/lesswrong/server/voteServer.ts

I ran into two issues when working with posts in [this topic](https://forum.effectivealtruism.org/topics/criticism-of-work-in-effective-altruism):
1. I noticed some had the newly created "criticism of work in ea" parent tag, but not the original "criticism of ea orgs" child tag. The `backfillParentTags` script is supposed to only apply the parent tag to posts tagged with the child tag. The bug seems to be that it wasn't excluding tags that had been unapplied to the post.
2. I tried to downvote the parent tag since it was misapplied, but ran into the error `Voted-on document does not have an author userId?`. I think it's actually fine that `TagRels` can have no `userId`? I don't know what it means for a `TagRel` to have an "author". So I just made this a valid case and removed the error. …

fix issues with backfilled tagrels

---

packages/lesswrong/lib/collections/comments/collection.ts
packages/lesswrong/lib/collections/comments/schema.ts
packages/lesswrong/lib/collections/posts/schema.tsx
packages/lesswrong/lib/editor/make_editable.tsx
packages/lesswrong/lib/vulcan-users/permissions.ts

Currently, the body of deleted content is available in the Apollo cache that's embedded in the HTML during SSR. This is a long-standing problem, as is evidenced by Jim's comment in the code from mid-2021.
This PR adds a new permissions function to disallow this, but we still make the content available to admins, mods and the original author.
By default, I've applied this to all fields that use `make_editable`, but it's plausible that there's some reason I've not thought about that means we should restrict to to fewer fields, or apply it to more.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204535640179844) by [Unito](https://www.unito.io)

Permission-gate fields when content is deleted

---

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx

Makes it so moderators can reply to comments even if they'd normally be hidden
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204542190588141) by [Unito](https://www.unito.io)

Moderators can reply to hidden comments

---

packages/lesswrong/lib/collections/posts/schema.tsx

Posts that (incorrectly) have `deletedDraft: true` while `draft: false` will fail to render for non-admin, non-owner users.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204566177525356) by [Unito](https://www.unito.io)

make coauthors field optional for graphql

---

packages/lesswrong/components/ea-forum/EAHome.tsx
packages/lesswrong/components/shortform/ShortformListItem.tsx

Previously there were no analytics events for when a shortform was toggled open or closed
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204570208978787) by [Unito](https://www.unito.io)

Add analytics to frontpage shortform

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/server/fmCrosspost/denormalizedFields.ts
packages/lesswrong/server/fmCrosspost/types.ts

This PR makes two changes:
- Denormalize the `question` field on posts for crossposts
- Hide the table of contents for foreign crossposted questions
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204572381085819) by [Unito](https://www.unito.io)

Improve crossposted questions

---

packages/lesswrong/components/users/EAUserTooltipContent.tsx

The new user pop-over on the EA forum currently always pluralizes "posts" and "comments" even if the user only has one.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204574780357189) by [Unito](https://www.unito.io)

Fix pluralization of posts and comments in EA user tooltip

---

packages/lesswrong/components/comments/CommentActions/DeleteCommentDialog.tsx
packages/lesswrong/components/common/CookieBanner/CookiePolicy.tsx
packages/lesswrong/components/common/CookieBanner/CookieTable.tsx
packages/lesswrong/components/ea-forum/users/EAGApplicationImportForm.tsx
packages/lesswrong/components/tagging/TagRevisionItemFullMetadata.tsx
packages/lesswrong/components/users/UsersViewABTests.tsx

This PR fixes more places with serif fonts on the EA forum:
- Tag edit titles in recent discussions
- Delete comment popup
- A/B test page
- The date on the cookie notice page (to match the date on the terms of use page)
- Section headings for the cookie table
- EAG import page
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204574705208863) by [Unito](https://www.unito.io)

[EA] Even more sans serif

---

packages/lesswrong/server.ts
packages/lesswrong/server/authenticationMiddlewares.ts
packages/lesswrong/server/scripts/mongoQueryToSQL.ts

For github logins specifically, we get back a number as a profile ID, and the query builder doesn't like that:
```
SQL Error for Users at position undefined:
cannot cast jsonb string to type integer:
`SELECT "Users".* FROM "Users" WHERE ("services"->'github'->'id')::INTEGER =  $1 LIMIT $2
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204592710372018) by [Unito](https://www.unito.io)

fix bug with numeric profile ids

---

packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx
packages/lesswrong/lib/collections/moderatorActions/helpers.ts
packages/lesswrong/server/callbacks/votingCallbacks.ts

This is a bunch of spaghetti and we're probably going to overhaul it imminently, but right now we have some users getting "lost" when removed from the review queue.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204606732152965) by [Unito](https://www.unito.io)

fix users getting lost when removed from the review queue

---

packages/lesswrong/client/datadogRum.ts
packages/lesswrong/components/hooks/useCookiesWithConsent.ts
packages/lesswrong/lib/cookies/callbacks.ts

There is a `useEffect` inside `useCookiePreferences` which automatically updates the "cookie_preferences" cookie if the value is different to what is being used in the code. This was intended to be called when a user first visits the site (or, rarely, when they move countries), so if the user is in a GDPR country like the uk it should set the cookie to '["necessary"]', and if they are in e.g. the US it should set it to '["necessary", "functional", "analytics"]'. This is required because Google Tag Manager only has access to the "cookie_preferences" cookie to determine whether to trigger google analytics (i.e. it can't directly tell what country the user is in)
There was a bug in this where it would sometimes get stuck in an infinite loop of trying to update the cookie, and in doing so …

Fix infinite loop when auto-updating users cookie preferences

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/components/recommendations/PostsPageRecommendationItem.tsx
packages/lesswrong/components/recommendations/PostsPageRecommendationsList.tsx
packages/lesswrong/server/recommendations/CollabFilterStrategy.ts

Changes in this PR:
- Better payout of posts recommendations on mobile from [Agnes' design in slack](https://cea-core.slack.com/archives/C03G0AQ925P/p1683873865021309?thread_ts=1683802025.109309&cid=C03G0AQ925P)
- Slightly less of a relevancy boost for curated posts (they already have a massive boost from the fact that they generally have super high karma)
- More relevancy boost for tag similarity (this is actually a bug fix - it was meant to be 1.5, but it was actually 1 because of a default value for a React prop)
- Hide recommendations on drafts, shortforms, debates and deleted posts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204602046743876) by [Unito](https://www.unito.io)

Posts recommendations improvements

---

.github/workflows/deployEAProd.yaml
packages/lesswrong/server/apolloServer.ts
packages/lesswrong/server/botRedirect.ts

We have created a separate environment (see [here](https://forum-bots.effectivealtruism.org/)) for bots to use to try and mitigate some of the site stability issues we have been having recently. This PR adds an automatic redirect based on the user agent of the request. 
There are 3 new settings introduced to configure this behaviour:
Database public settings:
- `botSite.url`: This is the URL of the site where the bots are redirected
- `botSite.userAgentRegexes`: This is a record where the keys are regex patterns matching request paths and the values are arrays of regex patterns matching user agents (see code for an example if this is confusing)
Public instance settings (required because the bot site shares a db with the production site)
- `botSite.redirectEnabled`
I have gone with a …

Add middleware to redirect bots to a different environment

---

packages/lesswrong/components/comments/CommentsItem/useCommentLink.tsx

A user reported:
> A somewhat common sequence of actions is "click lw post" –> "press comments (adding #comments to the URL)" –> "press the URL to a specific comment (adding ?comment-id to the URL)" –> "copy paste my current URL to share a link to the comment".
The problem is that #comments is still at the end of the URL, so when someone follows that link, they go to the top of the comment-section. It's totally invisible that there's a specific comment above the post. Maybe they'll read the top comment instead, thinking that the link led to that. Or maybe they'll just think that the sender of the link failed to link to a specific comment, and close the tab.
> Example of a fix: When you click the link to a specific comment, that removes #comment from the end of the current URL.
This makes …

Comment-permalink doesn't inherit a hash from the current URL

---

packages/lesswrong/components/posts/PostsNewForm.tsx

When you create a new post from the new post page, a flash message appears saying "Post created." This includes when the new post is being saved as a draft with the Save Draft buttom. A user reported this as having scared them, since they thought they had created a non-draft post when they only meant to save a draft.
Change the message to say "Draft created" instead if it's a draft.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204607654941169) by [Unito](https://www.unito.io)

Post created flash message draft

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx

A user reported that old Sequences posts, which are supposed to have a version dropdown for viewing the old version without R:A-Z edits, no longer seemed to have the old versions accessible. There were two bugs both breaking this. The first was a data integrity issue, where in mongodb the `fieldName` on some `Revisions` was `["contents"]` rather than `"contents"`, which, when translated into postgres, caused those revisions to no longer show up in the history because they had the field name `"{contents}"`. I fixed that with a one-off SQL migration:
```
update "Revisions" set "fieldName"='contents' where "fieldName"='{contents}';
```
(I don't know whether any EA Forum posts have the same issue; it's worth a quick check with `select count(*) from "Revisions" where …

Fix post-pages showing the newest version of post bodies when they should be showing a historical version

---

packages/lesswrong/server/callbacks/postCallbacks.ts

You don't get to use that regex every day. It's a fun one.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204633037683998) by [Unito](https://www.unito.io)

Ban emojis in post titles

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx

Hide recommendations on posts pages when the post is an event
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204637315044927) by [Unito](https://www.unito.io)

Hide recommendations on events

---

packages/lesswrong/components/comments/CommentsItem/CommentBottomCaveats.tsx
packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx

Once a comment has been rejected, it no longer makes sense to say "this comment will be hidden", because in the circumstances where you can actually see the comment it's, well, visible. (And should have a rejection reason listed)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204632763423053) by [Unito](https://www.unito.io)

Hide "this comment will not be visible"

---

packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx
packages/lesswrong/server/callbacks/rateLimits.ts

Also removed unused import
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204640168209195) by [Unito](https://www.unito.io)

Change default rate limit expiry to three weeks (21 days)

---

packages/lesswrong/components/notifications/EmailPreview.tsx
packages/lesswrong/server/emails/renderEmail.tsx

Saving the html version of every single email we send has been enormously bloating LWEvents.  (We send e.g. many copies of every single curated post to everyone who's subscribed to curated posts.)
The only thing we were even using it for was for displaying in `/debug/emailHistory`, and if necessary we could externalize the logic to render the html into a script so we could do it on demand.  (This could give us something different if any of the relevant components or logic had changed since the email was sent, but we also have 15 days of log retention in Mailgun, so 🤷.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204652805861189) by [Unito](https://www.unito.io)

dont save email html in lwevents

---

packages/lesswrong/lib/collections/moderatorActions/schema.ts
packages/lesswrong/server.ts
packages/lesswrong/server/scripts/mongoQueryToSQL.ts
packages/lesswrong/server/users/cron.ts

LessWrong has decided that we'll have rate limits expire by default after three weeks (so they don't persist indefinitely), but when they do so, the user gets returned to the review queue and we can do a quick little assessment of whether it should be reapplied.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204640281484759) by [Unito](https://www.unito.io)

Expired rate limit returns to queue

---

packages/lesswrong/lib/collections/posts/fragments.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

Somehow votingSystem got removed from the posts fragments. This adds it back in.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204672744683836) by [Unito](https://www.unito.io)

Fix votingSystem fragment bug

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/lib/abTests.ts

This PR removes the AB test for posts page recommendations and rolls the feature out to all users. This should probably be merged after #7239.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204671482797510) by [Unito](https://www.unito.io)

Rollout posts page recommendations to all users

---

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
packages/lesswrong/components/votes/NamesAttachedReactionsVoteOnComment.tsx

For the "react-with-name-attached" voting experiment, moves the add-react icon next to the rest of the reacts, and slightly updates the padding/styling of the react display.
I think there are some further improvements to be had here where the add-react button only appears on hoverover, but it involves weaving some code throughout CommentsItem and I think I want to hold off until we're a bit clearer on this being the right direction for reacts, and/or that the overall experiment will continue.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204672703695497) by [Unito](https://www.unito.io)

Move react button to bottom-right

---

packages/lesswrong/lib/collections/subscriptions/mutations.ts

Going to any tag page results in an error.  I think this is because of a missing value in `defaultSubscriptionTypeTable` for tags.  (In any case, adding the value for tags fixed it.)
We should type the `document` input for `useNotifyMe` more strictly, probably?
cc @oetherington (w.r.t. https://github.com/ForumMagnum/ForumMagnum/pull/6823)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204680681986306) by [Unito](https://www.unito.io)

add tags to default subscription types

---

packages/lesswrong/components/search/ExpandedUsersSearchHit.tsx
packages/lesswrong/components/users/UsersProfileImage.tsx
packages/lesswrong/components/votes/PostsVote.tsx

A couple small fixes in this PR:
1. Updated the user search results tab to use the new profile img component, so now it's more colorful :)
-----
2. Adjusted the position of the voting tooltip hover text so that it's better aligned (below is how it looked before the fix, now it's vertically centered with the karma)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204649212005591) by [Unito](https://www.unito.io)

[EA Forum only] update profile imgs in search results, fix position of voting tooltips

---

.github/workflows/deployEABeta.yaml

The audio stuff is all in the master branch (but only enabled on the beta site) so it's simpler to just deploy from ea-deploy
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204684526397964) by [Unito](https://www.unito.io)

Make the beta site deploy based on ea-deploy

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/lib/collections/posts/helpers.ts

We wanted to include posts from [this sequence](https://forum.effectivealtruism.org/sequences/dg852CXinRkieekxZ) in the initial rollout of AI audio (otherwise only posts after 2023-05-01 are included). Unfortunately the way the sequences architecture is set up doesn't make this completely straightforward (you can't just get a sequenceId from the post), so I have opted to just match against a list of post ids. I've added the ones we want as a setting (of which there are about 50). A benefit of this slightly hacky approach is that we can easily allow arbitrary posts in future
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204684918914943) by [Unito](https://www.unito.io)

Allow specific (classic) posts to have the type 3 player

---

packages/lesswrong/lib/collections/posts/schema.tsx
packages/lesswrong/lib/voting/namesAttachedReactions.tsx
packages/lesswrong/lib/voting/votingSystems.tsx
packages/lesswrong/lib/vulcan-users/permissions.ts

This PR allows LessWrong users to set their posts to use the react voting system. 
It adds an optional "userCanActivate" flag for votingSystems. Admins can set a post to any voting system, users can only use ones with that flag. I have the LW reacts system set to "isLW" so that it appears for LW users.
I've set it so that the field appears for all users on LW but not EA Forum, and on LW it appears in the advancedOptions group rather than the adminOptions group.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204688782308565) by [Unito](https://www.unito.io)

Allow LessWrong users to use react voting system

---

packages/lesswrong/lib/collections/posts/schema.tsx
packages/lesswrong/lib/voting/namesAttachedReactions.tsx
packages/lesswrong/lib/voting/votingSystems.tsx
packages/lesswrong/lib/vulcan-users/permissions.ts

I accidentally merged a PR before it was reviewed. Here it is again.
This PR allows LessWrong users to set their posts to use the react voting system.
It adds an optional "userCanActivate" flag for votingSystems. Admins can set a post to any voting system, users can only use ones with that flag. I have the LW reacts system set to "isLW" so that it appears for LW users.
I've set it so that the field appears for all users on LW but not EA Forum, and on LW it appears in the advancedOptions group rather than the adminOptions group.
Reverts ForumMagnum/ForumMagnum#7267
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204689353490292) by [Unito](https://www.unito.io)

Revert "Revert "Allow LessWrong users to use react voting system""

---

packages/lesswrong/components/editor/RateLimitWarning.tsx

For the RateLimitWarning, I had used a function for updating momentJs fromNow styling. It had appeared to (correctly) only apply to a particular component. It turns out it... very briefly appears on all other fromNow components on pages with long load times. I'm removing it for now. Hopefully will find another way to style it nicely later.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204690748945064) by [Unito](https://www.unito.io)

Remove momentjs fromNow styling

---

packages/lesswrong/server/sqlConnection.ts

Trivial PR that adds a console-log of something I want to check. Am going to force-merge this.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204695311709555) by [Unito](https://www.unito.io)

Log postgres connection pool limit on startup, on the theory that the envvar might have gotten lost somewhere

---

packages/lesswrong/lib/collections/posts/views.ts

Posts in the "Suggestions for Curated" list were sorted by `createdAt`, rather than `postedAt`. So when a moderator tried to curate a post today that had spent a year in its author's drafts folder, he couldn't find it, because you had to click Load More twice. Change it to be sorted by `postedAt`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204694424361946) by [Unito](https://www.unito.io)

Posts suggested for curation should be sorted by post date, not creation date

---

scripts/startup/buildUtil.js

https://github.com/ForumMagnum/ForumMagnum/pull/7218 relied on a private ssh key in credentials repo not being publicly readable, but git doesn't have the ability to transmit file-read-access, so by default the file was publicly readable on each device that downloaded the latest LessWrongCredentials repo.
This PR adds a fix which updates the file to have the correct permissions.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204718155313484) by [Unito](https://www.unito.io)

Set sshKey to no-access automatically

---

.platform/nginx/nginx.conf
packages/lesswrong/server/apolloServer.ts
packages/lesswrong/server/expressServer.ts
packages/lesswrong/server/hsts.ts

This PR makes some small changes to our HTTP headers for SEO and general security reasons.
- We add an HSTS header
- We remove the "x-powered-by" header that Express adds
- We turn off nginx server_tokens, which disables the "server" header and removes the nginx version from error messages, etc.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204685032791575) by [Unito](https://www.unito.io)

HTTP header updates

---

packages/lesswrong/server/datadog/tracer.ts

I can receive data from this locally but not in staging for some reason. I'm trying removing the IS_DOCKER check because it works without that locally
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204726913305647) by [Unito](https://www.unito.io)

Try removing host from StatsD to get it to send data from staging

---

migrate.js

(Hopefully) fix `migrate.js` so it works after the ssh-tunnel-related changes. (Seems to work locally but the GitHub Actions execution environment is different enough that it might or might not work).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204727776622420) by [Unito](https://www.unito.io)

Hopefully fix migrate script changed connection-config handlign

---

packages/lesswrong/components/comments/CommentsNewForm.tsx

Makes success/completion event contain duration, no longer requiring matching with the start event. Also includes commentId for joining
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204718484302316) by [Unito](https://www.unito.io)

Small changes to Comment Submit tracking

---

packages/lesswrong/server/editor/conversionUtils.ts

Currently if you are a non-admin and you give us HTML (for example as part of an RSS import) we don't process the HTML for LaTeX. 
I did this because I wasn't totally confident that MathJax wouldn't open up some weird XSS attack, but I think the risk is relatively low, and the benefits seem worth it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204541711102061) by [Unito](https://www.unito.io)

Process LaTeX for sanitized HTML

---

packages/lesswrong/lib/collectionIndexUtils.ts
packages/lesswrong/lib/utils/asyncUtils.ts
packages/lesswrong/server/deleteUserContent.ts

When a new server starts up, it sends a bunch of `CREATE INDEX IF NOT EXIST` queries. In theory, these are usually no-ops. However, it sends _all of them at once_. In a local-development-server context, this can lead to an extremely-long pageload, if that pageload happens to land while the index-create queries are running, since even if the queries aren't doing anything, they are nevertheless depleting the client's connection pool.
This makes it so that the on-startup index creation (a) is delayed slightly longer from startup, (b) is limited to one at a time, and (c) has a 500ms sleep between index-create operations.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204694919949439) by [Unito](https://www.unito.io)

Space out postgres ensure-index calls

---

packages/lesswrong/lib/make_voteable.ts

Found while investigating why comment-submission is slow. Impact unclear.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204731542786925) by [Unito](https://www.unito.io)

Don't try to update vote-counts for votes on the wrong collection

---

packages/lesswrong/lib/collections/posts/formGroups.ts
packages/lesswrong/lib/collections/posts/schema.tsx
packages/lesswrong/lib/voting/namesAttachedReactions.tsx
packages/lesswrong/lib/voting/votingSystems.tsx

This PR a) makes it so on LessWrong and Alignment forum, posts have a 50/50 chance of getting reacts vs regular voting, an b) it's more obvious that this is a thing you can configure.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204748637404153) by [Unito](https://www.unito.io)

Randomize reacts/default-voting on LW

---

packages/lesswrong/components/posts/ReadHistoryPage.tsx
packages/lesswrong/server/repos/PostsRepo.ts
packages/lesswrong/server/resolvers/postResolvers.ts

This involved a surprising amount of `apollo-client` magic involving fetch-policies, and a deleted sidetrack into what happens with `__typename` if you had the fetch-policy wrong.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204748935673484) by [Unito](https://www.unito.io)

/history page (EA forum gated) has a Load More

---

packages/lesswrong/components/votes/NamesAttachedReactionsVoteOnComment.tsx

Reacting was weirdly slow. Oli found it was because we weren't using the optimistic document from voteProps
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204749616300407) by [Unito](https://www.unito.io)

Fix react voting optimisticResponse

---

packages/lesswrong/components/common/ForumIcon.tsx
packages/lesswrong/components/posts/EAPostsItem.tsx
packages/lesswrong/components/posts/PostsPage/PostsPageDate.tsx
packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
packages/lesswrong/components/posts/usePostsItem.ts

This is part of a [larger set of changes](https://www.figma.com/file/d09iVzNSpZp9GyWGcfkWmX/Q2.2-2023?type=design&node-id=13-10576) that we're planning for updating the design of the post page header. This PR includes a few small pieces of it, including reordering some of the info and changing the audio icon.
-----
Before:
-----
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204729605648949) by [Unito](https://www.unito.io)

[EA Forum only] a few small adjustments to the post page header

---

packages/lesswrong/components/tagging/CoreTagIcon.tsx

The slug for the biosecurity tag has changed which means the icon is currently broken:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204753039628539) by [Unito](https://www.unito.io)

Fix biosecurity tag icon

---

packages/lesswrong/server/akismet.ts

The `checkForAkismetSpamCompleted` analytics event has revealed that the akismet callback seems to be responsible for the overwhelming majority of tail-latency when creating comments.  Two possibilities here:
1. it's because of the `LWEvents.find` call in `constructAkismetReport` (it can't realistically be the `Users.findOne` or `Posts.findOne`, since if those were pathological we'd notice it elsewhere)
2. it's on akismet's side (the `checkSpam` call)
Rather than spend a bunch of time debugging this, let's just... stop checking with akismet for already-reviewed users (who are enormously unlikely to be spammers).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204761985192252) by [Unito](https://www.unito.io)

skip akismet check for reviewed users

---

packages/lesswrong/lib/collections/posts/schema.tsx

I don't think we're getting data fast enough and I don't think even enough that we'll have the sample size to make interesting comparisons. So for LW, making reacts the default.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204762309301555) by [Unito](https://www.unito.io)

[LW] No more randomization. Just enable reacts on all posts.

---

packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx

Just increases the line-height from 5 to 10, since I frequently wanted to see a bit more.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204747945742024) by [Unito](https://www.unito.io)

Expand the size of the notes field in ModeratorActions

---

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx

Makes the dotted line for inline reacts only appear on hoverover
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204763724026475) by [Unito](https://www.unito.io)

Dotted line appears on hover

---

packages/lesswrong/server/karmaChanges.ts
packages/lesswrong/server/resolvers/revisionResolvers.ts

Saves on the order of 20ms of CPU time per front-page render.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204763572886022) by [Unito](https://www.unito.io)

Speed up html-to-text by using its compile() function to bake its config options

---

packages/lesswrong/lib/editor/make_editable.tsx

Hoping that this would encourage more use of `@` and `#` and therefore cross-post connections.
This is just a suggested draft. @jpaddison3
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204666520364436) by [Unito](https://www.unito.io)

suggested hint for using autocompletes in posts, EAF

---

packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx

Moderators will sometimes accidentally dismiss someone from the moderation queue and leave them with a pending comment that is now stuck in purgatory until they post again. This PR adds a warning.
We've not forum gated this @b0b3rt but let me know if you want us to.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204770878883980) by [Unito](https://www.unito.io)

Add warning to "remove from queue" if user has comments

---

packages/lesswrong/server/sqlConnection.ts

We were getting the error `Failed to connect to postgres:  Requested database setting before settings loaded` on staging, for obvious reasons. I'm surprised this was working locally though
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204793531163796) by [Unito](https://www.unito.io)

Use instance setting rather than db setting for idle timeout

---

packages/lesswrong/server/fmCrosspost/crosspost.ts

If a user tries to create a crosspost but it fails because they don't have enough karma on the foreign forum then they often try to unset the option to crosspost on the original post. This fails because it tries to delete the foreign post, which doesn't exist because creation failed. This PR changes this behaviour to instead just log a warning in the console without throwing an exception.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204790610813348) by [Unito](https://www.unito.io)

Don't throw an error when removing a crosspost if the foreign post doesn't exist

---

packages/lesswrong/server.ts

I forgot to import this in https://github.com/ForumMagnum/ForumMagnum/pull/7327 , so old entries are not getting cleared (which is fine, but the table will get pretty bloated eventually)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204793787758065) by [Unito](https://www.unito.io)

Import cron job to clear PageCache table

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx

This PR adds a reading progress bar to the top of post pages. Your reading progress is hard to tell just via the normal browser scroll bar, because it includes the height of the comments section.
https://github.com/ForumMagnum/ForumMagnum/assets/9057804/f00a11fd-483d-4e8d-bc34-4426ad0278c6
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204770096587016) by [Unito](https://www.unito.io)

[EA Forum only] display reading progress bar at the top of the post page

---

packages/lesswrong/components/votes/lwReactions/AddInlineReactionButton.tsx
packages/lesswrong/components/votes/lwReactions/InlineReactSelectionWrapper.tsx

Previously, mousing over the add-inline-react button would highlight all duplicates of the text you selected, to make it easier to see how much you had to expand the selection in order to get a unique string. 
This caused a minor bug on Chrome and Firefox, and a major bug on Firefox. (It'd mess with the selection in random ways, and on Firefox this caused the selection listener to think it needed to disappear the button)
This wasn't that important an effect in the first place, so I'm just removing the effect. I'm also moving the regex that checks for duplicate strings up a level into the InlineReactSelectionWrapper, so that the button greys out if it doesn't have a valid selection.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204797381430122) by …

Rework inline reaction button hover effect

---

packages/lesswrong/components/sunshineDashboard/moderationLog/ModerationLog.tsx
packages/lesswrong/lib/collections/comments/schema.ts

The permissions for userId were changed here:
https://github.com/ForumMagnum/ForumMagnum/commit/cfa7edd9f507d189d1446b548b2fd454d8ad7a20 
To make it so only admins and owners could see the name of deleted users. This made the /moderation page deleted comments section much more confusing on LessWrong.
This PR forum-gates that change. @oetherington I'm interested in more context on what the goal was for the other PR.
Also changes the name of the "user" column to "comment author" to be more clear.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204800045533320) by [Unito](https://www.unito.io)

ForumGate DeletedCommentUser

---

packages/lesswrong/lib/collections/posts/views.ts
packages/lesswrong/lib/scoring.ts
packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx

We can't see a clear effect of this in the A/B test and disabling the cache slows things down a lot for logged out users. We may also remove this for logged in users soon, but I want to deploy this before deciding on that because of the performance cost
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204805154446524) by [Unito](https://www.unito.io)

Disable slower frontpage for logged out users (and reenable cache)

---

packages/lesswrong/lib/sql/sqlClient.ts

I noticed that since adding the shared page cache I occasionally get loads of html dumped into the terminal when there is a slow query, this slows down the server quite a lot. I've added a limit of 5000 characters to prevent this.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204807318728469) by [Unito](https://www.unito.io)

Truncate slow query log to avoid dumping entire html pages

---

packages/lesswrong/components/posts/PostsPage/PostsAuthors.tsx
packages/lesswrong/components/posts/PostsPage/PostsCoauthor.tsx
packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
packages/lesswrong/components/users/UsersName.tsx
packages/lesswrong/components/users/UsersNameDisplay.tsx

`EAUsersProfile` already handles tracking the message source, so this PR just adds the `from` param to the links to authors' profiles in the post page header.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204790134610344) by [Unito](https://www.unito.io)

track when messages are sent to a post author

---

packages/lesswrong/lib/collections/posts/views.ts

This issue was reported as: Tag page https://www.alignmentforum.org/tag/holden-karnofsky contains a link to https://www.alignmentforum.org/lw/cbs/thoughts_on_the_singularity_institute_si/ which is broken. Actually, the link was to http://www.lesswrong.com/lw/cbs/thoughts_on_the_singularity_institute_si/ . The `PostLinkPreviewLegacy` component changed the http->https and the lesswrong.com->alignmentforum.org, then failed to have a working hover preview and making a broken link when clicked.
This changes the `legacyIdPost` resolver so it still works even if the default view contains `af:true` (ie, if it's being used by AF). This makes the link preview on that tag page work, and makes the alignmentforum version of the legacy post link function as a redirect to LW like it should.
┆Issue is …

Fix links in LW legacy format being broken on AF

---

packages/lesswrong/components/sunshineDashboard/ModeratorUserInfo/AltAccountInfo.tsx
packages/lesswrong/components/sunshineDashboard/ModeratorUserInfo/UserReviewStatus.tsx

This fixes an issue that caused false-negatives in alt-accounts detection in the moderation UI. Looking at the current moderation queue, there was in fact a user in there right now with a banned alt account that wasn't being picked up before, which is picked up with this patch applied.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204811244185683) by [Unito](https://www.unito.io)

Alt-accounts notice in moderation UI uses all client IDs instead of only the first one

---

packages/lesswrong/components/votes/lwReactions/InlineReactSelectionWrapper.tsx
packages/lesswrong/components/votes/lwReactions/NamesAttachedReactionsVoteOnComment.tsx

* Don't use a regex (which has special-character problems) for counting strings
* Make reaction hover fixed-width again
* Make the 2px space between reaction icons hoverable
* Add a hoverable spacer below the reactions list, so that the mouse can cross to the popup
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204811136120000) by [Unito](https://www.unito.io)

Improvements to the reaction hover

---

packages/lesswrong/lib/voting/namesAttachedReactions.tsx
packages/lesswrong/lib/voting/votingSystems.tsx
packages/lesswrong/server/voteServer.ts

Discussed in Slack thread: https://app.slack.com/client/T3ERD8FQT/CJUN2UAFN/thread/CJUN2UAFN-1686461489.244579?cdn_fallback=2
Antireactions make sense as a way for bystanders to remove unfair critical reacts, but when someone uses them to remove reacts from their own comments, it feels lame. Don't let users do that.

You cannot antireact to reactions on your own comments

---

packages/lesswrong/components/sunshineDashboard/RejectContentButton.tsx
packages/lesswrong/components/sunshineDashboard/RejectContentDialog.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUsersList.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/server/callbacks/commentCallbacks.ts
packages/lesswrong/server/callbacks/postCallbacks.ts

PR updates rejections to:
– have the rejected reasons list now shows all reasons (rather than the top 6), but highlights the top 6 to help make it easier to parse.
– updates the rejection default message
– refactors the rejection default message into a function shared between posts and comments (I hope to also eventually make it visible from the rejection dialog, but didn't get to that as part of this PR)
– renames ContentRejectionDialog to RejectContentDialog so that it's easier to find near RejectContentButton
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204791158184097) by [Unito](https://www.unito.io)

Rejection reasons refactor

---

packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx
packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/lib/collections/users/helpers.tsx

Prevents users from commenting on other users' shortform containers (both client-side by removing the comment box, and server-side with permissions). Also adds a message to the top of shortform container posts which reads: "This is a special post for short-form writing by Username. Only they can create top-level comments. Comments here also appear on the Shortform Page and All Posts page."
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204811769104437) by [Unito](https://www.unito.io)

No commenting on other users' shortform containers, and add a notice

---

packages/lesswrong/components/recommendations/PostsPageRecommendationsList.tsx
packages/lesswrong/components/recommendations/RecommendationsList.tsx
packages/lesswrong/components/recommendations/withRecommendations.ts

- NoSSR the recommendations list
- Add a batchKey to recommendations queries so other queries don't get stuck behind them
This (the NoSSR part) will unfortunately make recommendations much slower to load in absolute terms (time from refreshing the page to recommendations appearing). But seeing as they are by far the slowest thing to load at the moment (usually at least as slow as everything else combined) I think it is worth it. Also this frees us up to experiment with recommendations without having to immediately worry about the performance impact.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204807805772387) by [Unito](https://www.unito.io)

Mitigate performance cost of post recommendations

---

packages/lesswrong/server/authenticationMiddlewares.ts

I was able to replicate _a_ bug where it tried to log me in to the wrong account and this fixed it, but I don't know if it's the same bug. I think this is correct but there's also a lot of decade-old conflicting documentation about how this is supposed to work so it's hard to be certain. My current feeling is that this is safe to merge, but that we should keep an eye on it and be ready to revert in case of bug reports.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204818946771360) by [Unito](https://www.unito.io)

Fix google account selection with auth0

---

packages/lesswrong/components/common/ForumDropdown.tsx
packages/lesswrong/components/common/ForumDropdownMultiselect.tsx
packages/lesswrong/components/posts/PostsLayoutDropdown.tsx
packages/lesswrong/components/posts/PostsListSortDropdown.tsx
packages/lesswrong/lib/components.ts

I wanted to use `ForumDropdown` for https://github.com/ForumMagnum/ForumMagnum/pull/7403, but it didn't support multiselect. So in this PR I've created a multiselect version (`ForumDropdownMultiselect`) that is largely the same as `ForumDropdown` was, and now `ForumDropdown` is just a wrapper on top of that. This is so that I didn't have to change the places where `ForumDropdown` was used, plus I think the single select version will be used more overall so it would be good to keep that interface clean.
Apologies, the diff is pretty annoying to read, but I promise most of the code is the same. This is also to reduce the size of https://github.com/ForumMagnum/ForumMagnum/pull/7403 before I publish that for review.
Example from my other branch: …

add a multiselect option for ForumDropdown

---

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
packages/lesswrong/themes/userThemes/darkMode.ts

The highlighting effect for inline reacts overrode the darkmode text-color style. This PR unsets the text color, and improves the highlighting color so it looks nicer on darkmode.
BEFORE:
AFTER:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204821802491204) by [Unito](https://www.unito.io)

Darkmode inline reacts

---

packages/lesswrong/lib/betas.ts

Elasticsearch is currently fully deployed to the beta site, but only the backend is enabled on prod - the frontend is still calling Algolia. This change switches us fully over to ES.
FYI @SharangP
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204828186095851) by [Unito](https://www.unito.io)

Ship elasticsearch on the EA forum

---

.platform/nginx/nginx.conf

Increase nginx timeouts for `/api/notificationEvents`. This might be sufficient to make server-sent events work in prod, but more likely we will also need to make a similar change to our Elastic Beanstalk config to address timeouts there.
Co-Authored-By: Robert Mushkablat <bobert.mushky@gmail.com>
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204820883492753) by [Unito](https://www.unito.io)

Increase nginx timeouts for /api/notificationEvents

---

.platform/nginx/nginx.conf

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204836328831969) by [Unito](https://www.unito.io)

Add missing semicolons around nginx timeouts

---

packages/lesswrong/components/common/TemplateComponent.tsx

We've been finding ourselves wanting analytics on things that didn't have tracking added at the time of creation. As an easy way to encourage, adding the tracking imports to remind people.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204837386135904) by [Unito](https://www.unito.io)

Import useTracking/captureEvent into component template to encourage use

---

packages/lesswrong/server.ts
packages/lesswrong/server/updateScores.ts

We were seeing some instances of very old comments not being ordered correctly when sorted by magic. This was because (80% confident this was the only problem) they were being filtered out when updating because the difference between oldScore and newScore wasn't big enough in absolute terms, even though in relative terms it was significant.
I've changed the calculation to use a threshold that is relative to the power of one vote _at the time the comment was posted_, rather than a fixed value.
I've only updated the postgres version.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204834086579434) by [Unito](https://www.unito.io)

Make updateScoreInactiveDocuments correctly update very low scores

---

packages/lesswrong/components/tagging/TagPage.tsx
packages/lesswrong/components/tagging/subforums/SubforumWikiTab.tsx
packages/lesswrong/lib/utils/truncateTagDescription.ts

Lizka recently requested the ability to truncate tag descriptions on the tag page. This already exists as the field `descriptionTruncationCount` which is the number of paragraphs to show, but this is only implemented for LessWrong and not for the EA Forum which uses a different truncation algorithm. This PR adds this field to the EA Forum's algorithm.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204828374041525) by [Unito](https://www.unito.io)

Implement tags descriptionTruncationCount for the EA Forum

---

packages/lesswrong/server.ts
packages/lesswrong/server/recommendations/recommedationsCron.ts
packages/lesswrong/server/repos/PostRecommendationsRepo.ts

The performance of post recommendations is a lot worse than it could be because we generate a _lot_ of data in the database (the table is currently about 1.3GB and growing fast). Some of this data is useful, but a lot of it is not. This PR adds a cron job to remove old records:
- We remove all generated recommendations that are at least 1 day old and that were never observed by the user (ie; they never came above the fold). This is about 85% of all the data. I think this should be fine to do since we mostly care about the ratio of observed recommendations to clicks, rather than unobserved recommendations to clicks.
- We remove recommendations that were never clicked that were last recommended >3 months ago. This won't currently delete any recommendations as posts page recommendations are …

Create cron job to clear stale recommendations

---

packages/lesswrong/components/alignment-forum/AlignmentForumHome.tsx
packages/lesswrong/lib/collections/posts/schema.tsx

AlignmentForum recent discussion was displaying no comments, until you hit "load more".
Robert and I looked into it and found the break was introduced in this commit:
https://github.com/ForumMagnum/ForumMagnum/commit/1486309fa6a0ab958640429521c4f01b28d7972b
and that reverting `manyOrNone` to `many` caused it to start displaying normally again.
This was really fucking weird, and we still don't know why exactly. But, the result of switching to "manyOrNone" is that somehow the commentsLimit would sometimes be `null` (instead of undefined, which would have gotten properly assigned a default value by the destructuring). 
It's separately the case that AlignmentForum should probably migrate to use RecentDiscussionFeed, but RecentDiscussionFeed was broken on AF for different reasons (which seem …

Fix AF recent discussion

---

packages/lesswrong/lib/collections/users/schema.ts
packages/lesswrong/server/migrations/20230615T100000.migrate_commentSorting.ts

Previously the one called "magical algorithm" was actually sorting by "top", and there was no way to actually sort by magic. I've also added all of the other sortings in as options except "deleted"
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204833142590457) by [Unito](https://www.unito.io)

Fix commentSorting options for users

---

packages/lesswrong/components/posts/usePostsUserAndCoauthors.ts
packages/lesswrong/components/recommendations/PostsPageRecommendationItem.tsx
packages/lesswrong/lib/collections/posts/permissions.ts
packages/lesswrong/server/emailComponents/EmailPostAuthors.tsx

We sometimes get reports that users see errors like `e.coauthors is null` in various posts lists (front page, `/allPosts`, etc).  This happens if a post has `deletedDraft: true` but also `draft: false`; in this case, the post is not filtered out of result sets(?) but blows up because the `coauthors` resolver generates a non-nullable type despite the field being nullable (because `canRead` is set to only `documentIsNotDeleted`).
There are several issues:
1. We sometimes have posts with `deletedDraft: true` but also `draft: false` (this is not a valid invariant)
2. We seem to be returning those posts to users who aren't the author??? (this PR fixes that in `Posts.checkAccess`)
3. For fields which don't have `guest` permissions for `canRead`, we don't correctly generate types with `|null`. …

use null-safe access for coauthors field

---

build.js
scripts/startup/autoRefreshServer.js
scripts/startup/buildUtil.js

This got broken by some refactoring, after which the try-catch in `isServerReady` (which is only supposed to catch connection errors due to the server not having bound the port yet) was suppressing a missing-import error.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204858408620152) by [Unito](https://www.unito.io)

Fix auto-refresh in development environments

---

packages/lesswrong/server/search/elastic/ElasticConfig.ts
packages/lesswrong/server/search/elastic/ElasticQuery.ts

We recently had a bug report where a search for "communism" (with and without quotes) was returning results for "community". This happens because elasticsearch stems both words into "commun", which is fine without quotes but totally incorrect with quotes.
This PR adds explicit mappings for all full-text fields to index them with two separate analyzers; one with stemming and synonyms and one without. Normal queries do not need to change, and we can now fix the bug when searching with quotes by simple appending `.exact` to the field names. That is, the field `body` now contains the stemmed and synonynmed value, and `body.exact` has the unstemmed version.
This PR requires running `Globals.elasticConfigureIndexes()`. I've already done this on dev, but not staging or prod. It _is_ safe to run …

Add exact elasticsearch mapping

---

.github/workflows/deployEADev.yaml
packages/lesswrong/client/serverSentEventsClient.ts

Ollie and I tested this on the staging server, which has the same load balancer and Cloudfront settings as prod, with a live-updating DM conversation and it seemed to all work.
Co-Authored-By: Oetherington <ollie@etherington.xyz>
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204845108679608) by [Unito](https://www.unito.io)

Server-sent events auto reconnect on error

---

packages/lesswrong/components/comments/CommentsViews.tsx
packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/components/posts/PostsPage/PostsPageWrapper.tsx
packages/lesswrong/lib/collections/users/schema.ts
packages/lesswrong/lib/commentViewOptions.ts

This PR updates the names in the comment sort options for the EA forum to use sentence-case and to match the wording used for post sort options ([relevant slack thread](https://cea-core.slack.com/archives/C038J512SD8/p1686660670228429)).
It also does some internal plumbing just to tidy this code up, and to prevent having duplicated options between the posts page and the user settings page.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204854735977136) by [Unito](https://www.unito.io)

Update comment sort names

---

packages/lesswrong/components/linkPreview/HoverPreviewLink.tsx
packages/lesswrong/lib/executionEnvironment.ts
packages/lesswrong/lib/reactRouterWrapper.tsx
packages/lesswrong/lib/routeUtil.tsx
packages/lesswrong/server/pingbacks.ts

Co-Authored-By: Robert Mushkablat <bobert.mushky@gmail.com>
We noticed we were accidentally redirecting links to greaterwrong back to lesswrong, because greaterwrong was in the list of whitelisted domains (for hover-preview purposes).  This fixes that, and also fixes the existing issue with our `Link` implementation, which would only work for links pointing to the same host (and silently drop the rest on the floor).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204820722843350) by [Unito](https://www.unito.io)

Don't redirect GreaterWrong links to onsite equivalents in link hover-preview

---

packages/lesswrong/components/tagging/TagFlagItem.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204868401646548) by [Unito](https://www.unito.io)

Tag-flag tooltip is clickable (because in at least one case it contains a link)

---

packages/lesswrong/lib/collections/posts/schema.tsx

https://github.com/ForumMagnum/ForumMagnum/pull/7310 made it so that, if the forum-type is LW, posts are assigned a random voting system at creation time. Unfortunately this was done with `schemaDefaultValue`, making schema-generation nondeterministic if the forum type was LW. At the time I thought that this had narrowly avoided breaking schema generation by the luck of schemas being generated with a forum-type of `default`. My current understanding is that that was not true; instead, what was happening was that unit tests in CI would run with a forum-type of `EAForum`, which is consistent so it works, but if your local development environment was set to LW rather than EA Forum, then generating migrations locally would flip a coin. If you got the bad flip your schema would have a spurious …

Unfuck schema-generation

---

packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
packages/lesswrong/components/posts/PostsPage/ContentType.tsx
packages/lesswrong/components/tagging/AddTag.tsx
packages/lesswrong/components/tagging/TagHistoryPageTitle.tsx
packages/lesswrong/components/tagging/TagPageTitle.tsx
packages/lesswrong/lib/routes.ts

This is to make it easier for search engines to work out that this is the top level page for topics. There was also a big mess of redirects in the `routes` file so I've cleaned that up to make this easier to change in future.
For reviewers: It's definitely worth testing all the redirects and different site settings work. I have done this but it would be very annoying if this broke some links so it's worth retesting
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204871160153557) by [Unito](https://www.unito.io)

Change /topics/all to /topics on EA Forum (for SEO)

---

packages/lesswrong/server/search/elastic/ElasticExporter.ts

Currently, it's difficult/impossible to reconfigure indexes on staging/prod because there's so much data that we hit the kibana timeout before the process can complete (we don't hit the timout on dev because there's not enough data).
This PR changes the reconfigure script to build the new indexes asynchronously, and then adds a separate command to delete the orphaned indexes once all the data has been copied and the aliases have been switched.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204866535171725) by [Unito](https://www.unito.io)

Reconfigure existing elastic indexes asynchronously

---

packages/lesswrong/server/search/elastic/ElasticConfig.ts
packages/lesswrong/server/search/elastic/ElasticExporter.ts

Agnes noticed that underscores in usernames make them tricky to search for. With this PR, all of "Ben West", "ben_west", "ben__west" and "benwest" will be able to match the account "ben__west". This may end up being too lenient, but I think it should be fine.
So far, I've only configured the indexes on dev.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204862698896921) by [Unito](https://www.unito.io)

Add shingle elasticsearch mapping for username fields

---

packages/lesswrong/server/vulcan-lib/apollo-ssr/pageCache.ts

https://github.com/ForumMagnum/ForumMagnum/pull/7449 changed it to use the hash of the server bundle rather than the client bundle, but only on lookup so the cache has been broken since then
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204881408094445) by [Unito](https://www.unito.io)

Use server bundle hash in cacheStore

---

packages/lesswrong/lib/collections/posts/schema.tsx

The `unreadDebateResponseCount` resolver contains an N+1 select, in fetching comments in order to count how many unread debate comments there are. This works out to one spurious (predictably empty result set) DB query per marked-as-read query appearing on the front page.
Filter that to only run the query for posts that are at least debate posts.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204879982299869) by [Unito](https://www.unito.io)

Don't try to fetch debate-responses for counting if not a debate-post

---

packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx

This got dropped by accident from SunshineNewUsersInfo when I pulled it out of UserReviewMetadata
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204885909437739) by [Unito](https://www.unito.io)

Add ratelimit info to SunshineNewUsersInfo

---

packages/lesswrong/server/notificationCallbacks.tsx

Fixes a bug where, if a user has a `null` in their `emails` field, sending curation emails breaks (for everyone).
Also changes the behavior of the admin-preview version of the curation email, to make it easier to notice when sending has failed: rather than sending a preview version to admins and sending to everyone else 20 minutes later, it sends a preview version to admins and to everyone *including admins* 20 minutes later. So admins get two copies (the first copy having "[Admin preview]" in the subject line), and ideally will notice if they get the first but not the second.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204868016554763) by [Unito](https://www.unito.io)

Fix crash in findUsersToEmail when a user has a null in their list of emails

---

packages/lesswrong/lib/routes.ts

We don't want these pages showing up in search results, there's not much point in looking at them. Reported via [slack](https://cea-core.slack.com/archives/C038J512SD8/p1687020239458399).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204885242770700) by [Unito](https://www.unito.io)

[EA Forum only] noindex tag history and discussion pages

---

packages/lesswrong/server/tagging/tagCallbacks.ts

A very small thing, in response to an error spotted in Sentry, where a user on a phone tried to submit a tag-edit where the name field was edited to blank, producing an internal exception rather than a sensible error message.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204877434177086) by [Unito](https://www.unito.io)

Better validation of tag-renames

---

packages/lesswrong/lib/collections/posts/schema.tsx

https://github.com/ForumMagnum/ForumMagnum/pull/7468 created a confusing UI experience for people creating posts, since people would see a "voting system" field that says "Two axis voting", but which gets automagically changed to "Reacts" after submitting the form, i.e:
This PR removes the canCreate field, since AFAICT in the current regime it's basically incorrect to think of it as something you can control while creating. But I'm not 100% sure this is the right solution and interested in takes from @jimrandomh

Remove canCreate options from votingSystem.

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx

This PR adds a background to the post page audio icon when the player is open, to make it look like a stateful toggle button. This helps users understand that they can click to close the player.
-----
-----
On LW:
-----
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204885944481758) by [Unito](https://www.unito.io)

make audio icon look like a toggle button

---

packages/lesswrong/components/common/HomeLatestPosts.tsx

Using the current time (from the clock) inside React components is unsafe, because it changes every time the render function runs. Taking that time, adjusting it by an offset, and putting it into a query parameter means that query is then different each time, potentially leading to a double (or even triple) query. (In practice, in instrumentation, I usually saw it run only once, occasionally twice. But the times it ran twice, it slows down the front-page SSR enough to notice.)

Fix issue where latest-posts list was sometimes double-fetched

---

packages/lesswrong/components/common/HeadTags.tsx

I intended for only pages with no other title to have the long title "Effective Altruism Forum", and for other pages to have "EA Forum as a suffix". Currently this is broken for post and tag pages because they have custom title components
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204915793574405) by [Unito](https://www.unito.io)

Use short title on pages with a title component

---

packages/lesswrong/server/search/elastic/ElasticExporter.ts

Currently, the elastic exporter uses a create operation which throws an error if the document already exists in the index. It should use an upsert instead.
You can test this with, for instance, `./scripts/serverShellCommand.sh "Globals.elasticExportCollection('Tags')"`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204918310821560) by [Unito](https://www.unito.io)

Elastic export should use upsert instead of create

---

packages/lesswrong/server/serverStartup.ts

All our collections are switched. I tested locally running `yarn start-dev-db` and `start-prod-db` with this change (preventing connection to mongodb), and they worked. Once this is deployed, we should be able to turn off the mongodb servers.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204921126170796) by [Unito](https://www.unito.io)

LW no longer needs to connect to mongodb

---

packages/lesswrong/components/sunshineDashboard/ModerationDashboard.tsx
packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx
packages/lesswrong/components/sunshineDashboard/ModeratorUserInfo/UserAutoRateLimitsDisplay.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUserCommentsList.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx
packages/lesswrong/components/sunshineDashboard/UsersReviewInfoCard.tsx
packages/lesswrong/lib/instanceSettings.ts

This PR
– adds a word-break wrap to user bios so if they have a longass word in their bio it doesn't make the ModerationDashboard have a crazy wide width.
– makes it so the ModerationDashboard has a max width, so if any future size-breaking bugs happen there is a fallback
– switches from hiding the "return user to review queue" button if they're already in the review-queue, to greying it out (so it's less confusing about what's going on)
– fixes the labeling of the lastMonthDownvoterCount in the recent karma tooltip
– truncates bios in the moderation user info components so that longass bios don't take up multiple screen-heights by default (you can click to expand them)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204919980703974) by …

Fix various bugs in moderation queue

---

packages/lesswrong/components/sunshineDashboard/CommentKarmaWithPreview.tsx
packages/lesswrong/components/sunshineDashboard/PostKarmaWithPreview.tsx

Adds postedAt dates to the posts/comments in the Moderation Dashboard, when you view the user's recent posts/comments as a list showing the titles (instead of the default view which just shows karma)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204931598496473) by [Unito](https://www.unito.io)

Sunshine user contents show postedAt

---

packages/lesswrong/components/editor/EditorFormComponent.tsx
packages/lesswrong/components/editor/LastEditedInWarning.tsx

I think at some point this UI got broken. I think it's supposed to appear if your default-editor is ckEditor, and your post is currently not using ckEditor markup. Instead of comparing to your default editor, it was comparing to the initial editor-type, which meant that most users in most circumstances wouldn't end up seeing the UI to switch back to ckEditor.
I'm _not_ very confident in my understanding of what this code is supposed to be doing, but I know that for users who crosspost via RSS (and therefore the post is html), they have no way to convert to ckEditor.
For reference: 
This code (and surrounding component) when through a major refactor during https://github.com/ForumMagnum/ForumMagnum/pull/5644/files. The previous code said:
```
const editorWarning =
!editorOverride
&& …
```

Let users change editor back to ckeditor from html/markdown

---

packages/lesswrong/server/vulcan-lib/apollo-ssr/pageCache.ts

I have a suspicion the db-level caching is broken again, but there isn't enough info in the logs to confirm this easily (especially: we only log misses but not hits)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204935831939330) by [Unito](https://www.unito.io)

Add better logs to page cache to investigate bug

---

packages/lesswrong/components/posts/EAPostsItem.tsx
packages/lesswrong/components/posts/PostsHighlight.tsx
packages/lesswrong/components/posts/PostsTitle.tsx

- Visited posts should no longer show a purple "Continue reading" link in recent discussion (image of the bug attached).
- Clicking on the curated star should now take you to the curation page instead of to the post
Old:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204940886855703) by [Unito](https://www.unito.io)

[EA] Small fixes for and from JP

---

packages/lesswrong/components/quickTakes/QuickTakesCollapsedListItem.tsx
packages/lesswrong/components/quickTakes/QuickTakesListItem.tsx

This PR changes the typography in collapsed quick takes to match expanded quick takes, and adds a bottom margin underneath expanded quick takes.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204925953274488) by [Unito](https://www.unito.io)

Quick takes styling tweaks

---

packages/lesswrong/server/emailComponents/EmailComment.tsx

Reported for smalls. Currently you get a href like `https:///posts/<postId>/<postSlug>`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204954637221070) by [Unito](https://www.unito.io)

Make URL in 'New comment' email absolute

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/ForumIcon.tsx
packages/lesswrong/components/common/Header.tsx
packages/lesswrong/components/icons/closeMenuIcon.tsx
packages/lesswrong/components/icons/menuIcon.tsx

This PR adds a new icon that displays in the left side of the site header when the left menu is open. This is to help communicate to users that clicking it will close the menu rather than open another menu.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204922029100571) by [Unito](https://www.unito.io)

[EA Forum only] add icon for closing the left menu

---

packages/lesswrong/components/common/NewFeaturePulse.tsx
packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx

The audio icon in the posts page header is current misplaced when the new feature pulse is shown.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204957574856668) by [Unito](https://www.unito.io)

Fix position of audio icon when new feature pulse is shown

---

packages/lesswrong/components/common/useClickableCell.tsx

Cmd+click (or ctrl+click) is currently broken for the `EAPostsList`, and other components that use `useClickableCell`. This PR fixes the bug.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204955561433113) by [Unito](https://www.unito.io)

Fix cmd+click in `useClickableCell`

---

packages/lesswrong/components/notifications/NotificationTypeSettings.tsx
packages/lesswrong/components/notifications/NotificationsList.tsx
packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx
packages/lesswrong/components/search/PostsListEditorSearchHit.tsx
packages/lesswrong/components/sequences/SequencesPage.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx
packages/lesswrong/components/users/KarmaChangeNotifierSettings.tsx

FYI @agnesstenlund 
- Capitalize titles on the sequence page (instead of all uppercase)
- Fix serif on quick takes content warning
- Fix serif on vote count for unreviewed posts in sunshine sidebar
- Fix serif on "Link" button when adding posts to a sequence
- Fix serif for notification settings
- Fix serif for notifications "Load more" button
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204955177920355) by [Unito](https://www.unito.io)

EA Forum typography tweaks

---

packages/lesswrong/components/ea-forum/digest/EditDigest.tsx
packages/lesswrong/components/ea-forum/digest/EditDigestTableRow.tsx
packages/lesswrong/lib/collections/digests/helpers.ts

Some updates to the digest tool based on feedback from Lizka:
1. Hide read times for crossposts (I initially tried to show the right read time, but it's going to take a bit more work so for now I will hide them)
2. Display the publish date for each post, to take into account when looking at the post karma
3. Updated the sort order to remove the "your vote" criteria
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204947641498419) by [Unito](https://www.unito.io)

[EA Forum only] digest tool: hide xpost read times, display publish date, update sort

---

packages/lesswrong/lib/collections/posts/views.ts
packages/lesswrong/server.ts
packages/lesswrong/server/scripts/generateInflationAdjustedKarmaReport.ts

Because of the way this is set up it's surprisingly hard to get the numbers on inflation adjusted karma. I'm adding this script in case we need to do so again
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204963535610901) by [Unito](https://www.unito.io)

Add script to generate report on inflation adjusted karma

---

packages/lesswrong/lib/collections/moderatorActions/schema.ts
packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts
packages/lesswrong/server/voteServer.ts

Co-Authored-By: RickiHeicklen [ricki.heicklen@gmail.com](mailto:ricki.heicklen@gmail.com)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204947905096322) by [Unito](https://www.unito.io)
Put a user in the moderator queue if they have downvoted 9 of a specific other user's comments/posts within 2 minutes. (The 10th vote is actually the vote that triggers the user to be added to the queue, since the rate limit evaluation is backwards-looking.)
This is intended to catch cases of suspected targeted downvoting, where a user downvotes another user quickly, likely to rate limit that user.

implementing flagging suspected targeted downvoting for moderation

---

cypress/e2e/set_username.cy.js
packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/ForumIcon.tsx
packages/lesswrong/components/common/Header.tsx
packages/lesswrong/components/common/HeaderSubtitle.tsx
packages/lesswrong/components/common/SearchBar.tsx
packages/lesswrong/components/community/Community.tsx
packages/lesswrong/components/community/modules/CommunityMembers.tsx
packages/lesswrong/components/ea-forum/SiteLogo.tsx
packages/lesswrong/components/notifications/NotificationsMenuButton.tsx
packages/lesswrong/components/search/SearchBarResults.tsx
packages/lesswrong/components/search/SearchPageTabbed.tsx
packages/lesswrong/components/users/KarmaChangeNotifier.tsx
packages/lesswrong/components/users/UsersMenu.tsx
packages/lesswrong/themes/siteThemes/eaTheme.ts

This PR includes most of the changes from this [Figma](https://www.figma.com/file/d09iVzNSpZp9GyWGcfkWmX/Q2.2-2023?node-id=130%3A7096&mode=dev). There are various UI improvements to the site header, many of which reduce its visual size/prominence. [This other small PR](https://github.com/ForumMagnum/ForumMagnum/pull/7499) is also related.
Specific changes:
1. Header height is smaller 🙌 , and is consistent between screen sizes
2. Logo is smaller, particularly on mobile
3. User menu button was moved to the far right, and changed from the user's display name to their profile image (or placeholder if they don't have one)
4. Replaced the magnifying glass icon with the HeroIcons version
5. All icons on the right side are now a lighter grey
Old:
New:
-----
This also gives us a bit more …

[EA Forum only] updates to the site header, mostly to reduce the size

---

package.json
packages/lesswrong/lib/react-headroom/index.d.ts
packages/lesswrong/lib/react-headroom/index.tsx
packages/lesswrong/lib/react-headroom/shouldUpdate.ts
yarn.lock

tl;dr: adding `import { EA_FORUM_HEADER_HEIGHT } from './common/Header';` to `Layout.tsx` borked migrations because `migrate.js` uses `ts-node` to import the server code, which has some differences in behavior from `esbuild`, and a bunch of transitive dependencies caused that new import to bring in `react-headroom`, which was a vendored JSX (rather than TSX) file.
This PR only converts `react-headroom` to Typescript, with no functional changes (i.e. untangling those imports, which can be done in a follow-up PR).
For more detail, see this slack thread: https://app.slack.com/client/T3ERD8FQT/CJUN2UAFN
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204974955468522) by [Unito](https://www.unito.io)

convert react-headroom to typescript to unblock migrations using ts-node

---

packages/lesswrong/components/votes/ReactionsPalette.tsx

The current design of the reactions palette hides half of the reactions behind a scrollbar, but the scrollbar is invisible and it's extremely easy to not realize it's there. This fixes that using the standard trick of setting the size such that there's a half-row at the bottom.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204966787974460) by [Unito](https://www.unito.io)

Make the scrollability of the reactions palette detectable

---

packages/lesswrong/server.ts
packages/lesswrong/server/scripts/removeRsvp.ts

We had a smalls request to remove an RSVP from an event, but there's currently not an easy way to do this (or at least, I couldn't find one).
This PR adds a quick and dirty admin script that can be used as `./scripts/serverShellCommand.sh "Globals.removeRsvp('<postId>', 'userNameOrId')"`.
I already ran this on the event in question so no more action is needed there.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204955417496507) by [Unito](https://www.unito.io)

Add admin script to remove an RSVP

---

packages/lesswrong/components/sequences/SequencesPage.tsx
packages/lesswrong/components/tagging/EAAllTagsPage.tsx
packages/lesswrong/components/tagging/TagPage.tsx
packages/lesswrong/themes/siteThemes/eaTheme.ts

This PR adjusts three pages to account for the new shorter site header. Below are screenshots of the current (broken) versions.
-----
Sequence page
-----
All Topics page (I think this issue predates the header change but I also fixed this)
-----
Topic page (non-core) with banner
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204983808434504) by [Unito](https://www.unito.io)

[EA Forum only] adjust topic and sequence pages for shorter top bar

---

packages/lesswrong/components/common/Header.tsx
packages/lesswrong/components/ea-forum/EAButton.tsx
packages/lesswrong/components/users/UsersAccountMenu.tsx
packages/lesswrong/lib/components.ts

This PR just contains the updates to the logged out user view of the site header from [this figma](https://www.figma.com/file/d09iVzNSpZp9GyWGcfkWmX/Q2.2-2023?node-id=130%3A7156&mode=dev). Basically it's just changing the login and sign up links to button styles, and I also used this opportunity to create an `EAButton` component to help standardize our buttons. I haven't replaced any other buttons yet - if @agnesstenlund is good with this PR then we can start replacing existing buttons in future PRs.
Old:
New:
-----
Old:
New:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204981481008522) by [Unito](https://www.unito.io)

[EA Forum only] updates for logged out user site header

---

packages/lesswrong/components/users/UsersMenu.tsx

This PR makes all the options in our user menu sentence case (which @agnesstenlund was [good with doing](https://cea-core.slack.com/archives/C038J512SD8/p1687880841336809)), plus moves the "Account settings" option to the bottom of its section (since I think it makes more sense for it to be there). ([Related discussion in slack](https://cea-core.slack.com/archives/C03R2G12W2K/p1688766037735089))
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205005367105654) by [Unito](https://www.unito.io)

[EA Forum only] small updates to site header user menu

---

packages/lesswrong/components/posts/EAPostsItem.tsx
packages/lesswrong/components/posts/PostsTitle.tsx

Small fix to make sure that clicking on an author's name in the post item doesn't also redirect you to the post page
EDIT: Also noticed that the icons to the right of the post title have the same issue, fixed that as well
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205004550099564) by [Unito](https://www.unito.io)

[EA Forum only] fix post item author link, and icons to the right of the post title

---

packages/lesswrong/components/posts/PostsTitle.tsx

Bug reported via intercom, [see in slack here](https://cea-core.slack.com/archives/C038J512SD8/p1688743800612029):
"when I try to add a new post to my sequence, halfway through typing its name the screen disappears and is replaced with a mostly-blank screen"
@oetherington Looks like this was due to the post search results having `null` tags - this seems to fix it but let me know if you'd prefer to fix it some other way
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205005014372329) by [Unito](https://www.unito.io)

[EA Forum only] fix adding posts to sequences

---

packages/lesswrong/components/common/SearchBar.tsx
packages/lesswrong/components/users/UsersMenu.tsx
packages/lesswrong/themes/siteThemes/eaTheme.ts

This is a small PR to update the styling of the search icon in the site header to match the other icons. [Relevant figma here](https://www.figma.com/file/d09iVzNSpZp9GyWGcfkWmX/Q2.2-2023?node-id=130%3A7137&mode=dev). It's based off of https://github.com/ForumMagnum/ForumMagnum/pull/7547 but that's just for convenience since they both touch header styling - you don't need to read that one.
Basically I made the search icon into an `IconButton` so that it gets the background on hover, and made all our icon buttons backgrounds squares rather than circles:
I figured this switch to `IconButton` was fine to keep for LW as well, since it just makes their site header icons more consistent with each other. I left it with the default circle background on hover:
┆Issue is synchronized with this …

style updates to site header search icon

---

packages/lesswrong/lib/editor/mentionsConfig.tsx

This fixes a bug that prevented mentions from working on the EA Forum after the elasticsearch migration due to the `initIndex` method not being implemented. This is tested and working with both elasticsearch and algolia.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205008558589696) by [Unito](https://www.unito.io)

Fix @ mentions on the EA forum

---

packages/lesswrong/components/votes/ReactionsPalette.tsx
packages/lesswrong/lib/voting/reactions.tsx

This moves the percentage-likelihood reacts below the fold, so they're still there but less overwhelming looking.
Also removes the "reacts feedback" button, since not many people were using it and it was also adding to overwhelm.
compared to what it previously looked like:
When expanded, it looks like this:
compared to the original which looked like this:
I also moved the "confused" reaction to the bottom row since it had rarely been used, moved "seen" up to the top row since it had been used occasionally and is a fairly standard react. I removed "thanks" and "empathy" from the bottom row since they already appeared earlier in the list (the only reason I included them originally was to fill up the bottom row.  …

React Palette simplification

---

packages/lesswrong/components/search/CommentsSearchHit.tsx
packages/lesswrong/components/search/PostsSearchHit.tsx
packages/lesswrong/components/search/SearchBarResults.tsx
packages/lesswrong/components/search/SequencesSearchHit.tsx
packages/lesswrong/components/search/TagsSearchHit.tsx
packages/lesswrong/components/search/UsersSearchHit.tsx
packages/lesswrong/components/search/types.ts

I often find it annoying to have to scroll down to posts on mobile when I search for something, so I've moved them up one place. I have also done a bit of refactoring to make this easier to reorder in future
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205009196789184) by [Unito](https://www.unito.io)

Reorder search results to put posts higher up

---

packages/lesswrong/server/fmCrosspost/denormalizedFields.ts
packages/lesswrong/server/fmCrosspost/types.ts

In response to a bug reported on [intercom](https://app.intercom.com/a/inbox/xycbzvda/inbox/shared/all/conversation/69456500022260?view=List)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205013879648421) by [Unito](https://www.unito.io)

denormalize crosspost url field, so that link icon appears in post item

---

packages/lesswrong/lib/collections/moderatorActions/schema.ts

From 9 to 4. On the EA Forum only.

Lower the threshold of DMs sent before blocking

---

packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx

On mobile, clicking the actions button (three dots) in a post's header, sometimes causes the menu to pop up partially out of the screen bounds.
This fixes it by autoplacing the menu so that it floats to the left of the button on small screens.
Admittedly the current implementation of autoPlace would cause it to float to the left even in some medium screens where this isn't necessary. But calculating the exact threshold seems like an overkill, and probably doesn't matter for most screens anyway.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204996732530760) by [Unito](https://www.unito.io)

fix  three dots menu in post header gets cropped in mobile

---

packages/lesswrong/server/search/elastic/ElasticConfig.ts
packages/lesswrong/server/search/elastic/ElasticQuery.ts

This PR adds a couple more small Elastic improvements:
- Adds an 'exact' sub-field on shingle fields. This mainly affects searching for users by name and fixes a regression from when we switched to using a shingle mapping here.
- Improves the queries generated for prefix matching, most notably by using the `exact` subfields. This means that, for instance, "moderat" will match "moderators".
The dev indexes are already reconfigured, but not prod or staging yet.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205064375376985) by [Unito](https://www.unito.io)

Even more elastic improvements

---

packages/lesswrong/lib/collections/posts/schema.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205096815589684) by [Unito](https://www.unito.io)

Set the default voting system on the EA Forum to `eaEmojis`

---

packages/lesswrong/components/posts/PostsItemDate.tsx

Currently, the date on brand new posts is displayed as "now ago". This PR changes it to just say "now".
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205097157254502) by [Unito](https://www.unito.io)

Show 'now' instead of 'now ago' for brand new posts

---

packages/lesswrong/components/posts/EAPostsItem.tsx

We have a weird bug on live where, after clicking on a post item title to view the post page, you have to click back twice to get back to the previous page. I think this was because of the duplicate links (on the title and the post item).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205098240737666) by [Unito](https://www.unito.io)

[EA Forum only] fix post item title link

---

packages/lesswrong/components/comments/CommentsNode.tsx
packages/lesswrong/components/posts/PostsHighlight.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionThread.tsx

The EA Forum team is thinking about ways we can improve / overhaul the "Recent Discussion" section of the front page. In this PR, I'm just adding tracking for when users click to expand comments and posts that appear in that section. After looking at how people use it, we might lean more heavily into focusing on comments or posts.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205087557572721) by [Unito](https://www.unito.io)

add a bit more analytics to Recent Discussion

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/admin/AdminToggle.tsx
packages/lesswrong/components/admin/useAdminToggle.ts
packages/lesswrong/components/users/UsersMenu.tsx
packages/lesswrong/lib/collections/users/schema.ts
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/permissions.ts

Add an option to disable being an admin/moderator, and claim it back. To keep track of when a user is an admin but has their powers disabled, we add a `realAdmins` group. This edits the actual user object to be a not-moderator not-admin to ensure that admins testing this way can see any permissions-related bugs accurately.
(Future work: EA Forum had a design for this feature using a floating button in the bottom left, rather than it being in the user menu, for quick toggle.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205068060513013) by [Unito](https://www.unito.io)

Users who are admins+moderators can disable their powers for testing and reclaim them

---

packages/lesswrong/components/community/modules/SearchResultsMap.tsx
packages/lesswrong/server/search/elastic/ElasticService.ts
packages/lesswrong/server/search/elastic/SearchQuery.ts
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/themeType.ts

Thsis PR fixes 2 issues on the /community/map page:
- No results are currently shown because the search query sends no query string. The elastic backend expects _some_ query to be sent, even if it's the empty string. The change here is to just allow requests with no query and to interpret this as being an empty string.
- We force the username in results to always be black whatever color scheme is in use, as the background is always white. It's currently white text on a white background in dark mode.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205123522713969) by [Unito](https://www.unito.io)

Community map fixes

---

packages/lesswrong/components/sequences/SequencesPage.tsx

Not sure how long this has been the case, but our sequence page default banner img was broken, presumably because it's a LW-specific URL.
-----
I just used our default event banner img here:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205130367194740) by [Unito](https://www.unito.io)

add a default sequence banner img for EA Forum

---

packages/lesswrong/components/comments/PopularComment.tsx
packages/lesswrong/components/questions/Answer.tsx

This PR fixes the wrapping of EA emojis on question answers and in the popular comments section.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205137455448510) by [Unito](https://www.unito.io)

Fix display of EA emojis on question answers

---

migrate.js

I tried to check `yarn migrate executed staging` and it secretly checked `dev` instead. Seems like we should be able to run `pending` and `executed` on any env.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205136795028357) by [Unito](https://www.unito.io)

update migrate so we can check pending/executed for any env

---

packages/lesswrong/components/recommendations/PostSideRecommendations.tsx
packages/lesswrong/lib/collections/users/recommendationSettings.ts
packages/lesswrong/lib/postSideRecommendations.tsx
packages/lesswrong/server/recommendations.ts
packages/lesswrong/server/recommendations/RecommendationService.ts

By default, if a recommendation strategy returns too few results we automatically switch to using a different strategy until we have enough. This works well for recommendations under the post where we just want something like "more posts you might be interested in", but it works less well for right-hand side recommendations where we use more specific requirements like "more from <some specific tag>". This can result in us displaying posts as having a particular tag that they don't actually have.
This PR adds a `disableFallbacks` parameter to prevent this happending, and also hides the right-hand side recommendations section if no relevant results are found.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205137834917437) by …

Add option to disable fallback strategies for recommendations

---

packages/lesswrong/lib/abTests.ts
packages/lesswrong/lib/postSideRecommendations.tsx

- Change the AB test groups to be 50/50 instead of 20/80
- Temporarily disable "More from the forum"
- Update missing URLs for "More from the forum"
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205113153610414) by [Unito](https://www.unito.io)

RHS recommendations updates

---

packages/lesswrong/server/callbacks/votingCallbacks.ts

With auto ratelimits now in place, there doesn't seem to be value in having users get added to the review queue for getting downvoted a bit or for hitting negative karma.  I'm open to keeping it around with much stricter thresholds but there isn't a very convenient way to directly translate a user becoming affected by an auto ratelimit into them getting put into the review queue.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205114535574626) by [Unito](https://www.unito.io)

stop automod from putting users into the review queue

---

packages/lesswrong/components/search/SearchPageTabbed.tsx

This PR fixes a bug where trying to search using the search box in the navigation bar doesn't work whilst on the search page.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205138131933274) by [Unito](https://www.unito.io)

Fix searching from the navbar on the search page

---

packages/lesswrong/components/posts/PostsEditForm.tsx
packages/lesswrong/components/posts/PostsNewForm.tsx
packages/lesswrong/lib/collections/users/fragments.ts
packages/lesswrong/server/callbacks/rateLimitCallbacks.ts
packages/lesswrong/server/rateLimitUtils.ts
packages/lesswrong/server/resolvers/userResolvers.ts

Currently events are subject to rate limits, but it's common for users with 0 karma to make events for their meetups and it's kind of a pain for them to have to limit them to 2-postings-per-week. 
I've never actually seen Event Spam and if it came up I think we could just handle it via manual moderation, so for now am just filtering out events.
Edit by @b0b3rt: this now also doesn't check the rate limit in post callbacks or in the resolver field returned to the client for displaying the rate limit info, in the case the post is an event.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205129723463029) by [Unito](https://www.unito.io)

Events are not rate limited

---

packages/lesswrong/components/ea-forum/digest/EditDigest.tsx
packages/lesswrong/components/ea-forum/digest/EditDigestHeader.tsx
packages/lesswrong/components/ea-forum/digest/EditDigestTableRow.tsx
packages/lesswrong/components/form-components/FormComponentDateTime.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/server/callbacks/digestCallbacks.tsx

This PR updates the "Edit digest" page, such that clicking on the start or end date turns it into an input that lets you edit it. It's not pretty but this is an internal admin page, and we should rarely need to change these dates. It's also nice that it's quick to do, and the post list updates when the date picker closes.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205154958486831) by [Unito](https://www.unito.io)

[EA Forum only] allow users to edit the digest's start and end dates

---

packages/lesswrong/lib/collections/posts/helpers.ts

On Monday we are going to enable the type 3 audio player for all posts over 100 karma
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205159905561401) by [Unito](https://www.unito.io)

Add setting to enable type 3 audio on old posts

---

packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx

This
– makes it so on LessWrong, there is no pulse for audio (this is partly because we didn't especially want it on LW in the firstplace, and in particular didn't want it for AI-audio which isn't as good, and, partly because of a display bug where it was causing the UI to display out of alignment with the rest of the header info)
– makes it so if audio hasn't been created yet, the button is grey instead of green. We plan to also make it so that when the audio is created by AI, it continues to appear grey, but I don't yet know the url associated with the AI audio so haven't configured that part yet)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205046656055649) by [Unito](https://www.unito.io)

LW nonhuman audio podcast styling

---

packages/lesswrong/server/scripts/algoliaConfigureIndexes.ts

It was previously impossible to search for some zero-karma users, which made it impossible to add them as coauthors or share them on things.
This puts "desc(karma)" lower in the list of priorities.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205129699534134) by [Unito](https://www.unito.io)

Exact matches prioritized above karma in user search

---

packages/lesswrong/server/repos/UsersRepo.ts

A user who'd only logged in with Github before reported an issue resetting his password.  Turns out that if you try to `jsonb_set` a path that doesn't exist in the object (i.e. `'{password, bcrypt}'`, where `password` doesn't exist for a user if they didn't register with native auth), it simply returns the record unchanged(!).
Possibly there's a more elegant way of doing this, but meh.  Tested both cases (users with pre-existing passwords, and users without).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205130508550715) by [Unito](https://www.unito.io)

fix password reset for oauth users who didn't have a password before

---

packages/lesswrong/components/form-components/FormComponentPostEditorTagging.tsx
packages/lesswrong/components/tagging/TagsChecklist.tsx
packages/lesswrong/lib/collections/tags/fragments.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

- Use the short name for post types on the edit post page
- Include `isPostType` in `TagEditFragment`
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205173543354966) by [Unito](https://www.unito.io)

EA Post types fixes

---

packages/lesswrong/components/posts/LinkPostMessage.tsx
packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx

The negative margin was causing this issue in recent discussion:
This PR fixes that. I still think it looks much better with the negative margin in the posts page itself, and also that it isn't worth refactoring to remove it by reducing the margin above because that will affect a lot of other things, so I have left it in there. Here is a screenshot with and without in case anyone things we should remove it entirely:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205159241305306) by [Unito](https://www.unito.io)

Remove negative margin on LinkPostMessage everywhere except the posts page

---

packages/lesswrong/components/search/ExpandedUsersSearchHit.tsx
packages/lesswrong/components/search/SearchPageTabbed.tsx
packages/lesswrong/lib/betas.ts
packages/lesswrong/lib/routes.ts
packages/lesswrong/lib/search/algoliaUtil.ts

Enabling ElasticSearch on LessWrong, as well as switching over to the new tabbed search page!
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205163040460247) by [Unito](https://www.unito.io)

cut over search to elastic and use new search page for LW

---

packages/lesswrong/server/resolvers/revisionResolvers.ts

Fixes https://github.com/ForumMagnum/ForumMagnum/issues/7101 .
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205166541466750) by [Unito](https://www.unito.io)

prevent social previews of comment titles from being in SHOUTING ALL CAPS

---

packages/lesswrong/components/sunshineDashboard/ModeratorUserInfo/RecentlyActiveUsers.tsx

Creates a toggle so that you can hide users with < 5 karma from the "Recently Active Users" page, which lets you more easily distinguish whether longterm users have been inappropriately rate-limited

Hide low karma users from recently active users

---

packages/lesswrong/components/sunshineDashboard/ModeratorUserInfo/RecentlyActiveUsers.tsx
packages/lesswrong/lib/rateLimits/constants.ts
packages/lesswrong/lib/rateLimits/types.ts
packages/lesswrong/lib/rateLimits/utils.ts
packages/lesswrong/server/repos/VotesRepo.ts
packages/lesswrong/unitTests/autoRateLimit.tests.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205187056495265) by [Unito](https://www.unito.io)

fix once per week rate limit and only count unique downvotes on net negative content

---

packages/lesswrong/server/callbacks/digestCallbacks.tsx

Fantastic bug.
When we update the date on a digest we also update the date of the neighbouring digest to match. However, this is done in a callback and uses update mutator, which means we then run the call backs on the neighbouring digest... which then runs the callback on the original digest which then runs the callback on the neighbouring digest, etc. etc.
The only way to stop the loop is to restart the server.
This is what happens to the database CPU usage:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205199488992193) by [Unito](https://www.unito.io)

Fix infinite loop when changing digest date

---

packages/lesswrong/components/messaging/ConversationItem.tsx

This PR fixes particpant names overflowing for messages with many participants, as well as fixing font descendors being cutoff by the line height.
The change is _not_ currently forum gated.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205176790333015) by [Unito](https://www.unito.io)

Fix text overflow for usernames on messages with many participants

---

packages/lesswrong/components/ea-forum/EAButton.tsx
packages/lesswrong/components/ea-forum/digest/ConfirmPublishDialog.tsx
packages/lesswrong/components/ea-forum/digest/EditDigestPublishBtn.tsx

This is just a small PR to use the `EAButton` component in the digest tool. I also used this opportunity to update the `EAButton` a bit, to handle more options.
Old:
New:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205187578427442) by [Unito](https://www.unito.io)

[EA Forum only] use EAButton in digest tool

---

packages/lesswrong/components/common/TypeformEmbeds.tsx
packages/lesswrong/components/ea-forum/EASurveyBanner.tsx

We currently hide the survey banner whenever the popup is closed, but we should probably only hide it if the form is actually submitted
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205213894299210) by [Unito](https://www.unito.io)

Hide ea survey banner on submit instead of on close

---

packages/lesswrong/components/sequences/ChaptersList.tsx
packages/lesswrong/components/sequences/SequencesPage.tsx
packages/lesswrong/lib/collections/chapters/views.ts

Currently we have a lot of sequences where all the chapters have `number` as `null`, so it's up to the whims of postgres as to the order they are returned in. Maybe this was fine in mongo because insert order was preserved but now it's become a problem with the migration.
In any case, in this PR I've added:
- ordering by createdAt if there is no `number`
- defaulting to the next number rather than `null` when creating a new chapter
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205211935665496) by [Unito](https://www.unito.io)

Improve default ordering of chapters in sequences

---

packages/lesswrong/lib/cookies/cookies.ts

We got a bug report that someone couldn't close the banner because they had rejected cookies. It's fine to make this specific cookie "necessary" as it's not used by a third party and isn't tracking any sensitive data.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205222866224988) by [Unito](https://www.unito.io)

Make cookie to hide survey banner necessary

---

packages/lesswrong/components/comments/PopularComment.tsx
packages/lesswrong/components/votes/EAEmojisVoteOnComment.tsx

Fixes 2 issues with the display of emojis:
- Removes usage of `Array.at` which isn't supported on older browsers
- Fixes wrapping on small screens in the popular comments section
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205222419105170) by [Unito](https://www.unito.io)

EA emoji display fixes

---

packages/lesswrong/components/common/LWPopper.tsx
packages/lesswrong/components/common/PopperCard.tsx
packages/lesswrong/components/dropdowns/DropdownItem.tsx
packages/lesswrong/components/dropdowns/posts/PostActions.tsx
packages/lesswrong/components/dropdowns/posts/PostActionsButton.tsx
packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx

An alternative to #7554 (which was reverted in #7627).
This PR enables the Popper.js' flip modifier to automatically flip the popper of PostHeader's ActionsButton.
It uses flip rather than preventOverflow, because the latter affects vertical overflow as well (which causes unwanted behavior when scrolling).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205158502782984) by [Unito](https://www.unito.io)

enable  flip in post header's actions popper

---

packages/lesswrong/components/users/NewUserCompleteProfile.tsx

This PR is just cleaning up the styling a bit on the new user registration page (the one where you pick your username). This should basically not affect LW.
Old, desktop:
New, desktop:
-----
Old, mobile:
New, mobile:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205234270505745) by [Unito](https://www.unito.io)

clean up new user registration page a bit

---

packages/lesswrong/components/events/modules/VirtualProgramCard.tsx

I happened to look at the EA.org [VP page](https://www.effectivealtruism.org/virtual-programs) and noticed that the dates are not the same as on our [Events page](https://forum.effectivealtruism.org/events), so I adjusted them to match:
I'll plan to remove this exception from the code in September.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205224877330073) by [Unito](https://www.unito.io)

[EA Forum only] fix VP dates for August

---

packages/lesswrong/components/ea-forum/users/EAUsersMetaInfo.tsx

Makes this uBlock Origin rule work:
```
###karma-info
```
(Note the three #s)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205234927034524) by [Unito](https://www.unito.io)

[EA] Add an id to the EAUsersProfile karma info to make it easier to block

---

packages/lesswrong/server/rateLimitUtils.ts

Oops.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205253932954282) by [Unito](https://www.unito.io)

fix case for stricter rate limit checks when there are no applicable votes on content

---

packages/lesswrong/components/editor/EditorFormComponent.tsx
packages/lesswrong/components/posts/PostsEditForm.tsx
packages/lesswrong/components/posts/PostsNewForm.tsx
packages/lesswrong/components/posts/TableOfContents/DynamicTableOfContents.tsx
packages/lesswrong/components/posts/TableOfContents/index.ts
packages/lesswrong/lib/collections/posts/collection.ts
packages/lesswrong/lib/editor/make_editable.tsx
packages/lesswrong/server/tableOfContents.ts

This adds a Table of Contents to both the PostsNewForm and the PostsEditForm. It updates when autosave triggers (i.e. when you're idle for 3 seconds)
It does not currently make the headings click-to-scroll.

Add Table of contents to post editor

---

packages/lesswrong/lib/collections/comments/views.ts

Introduces a 5-day cutoff for quick takes on the frontpage
The current frontpage has a quick take from ten days ago, and my subjective opinion is that this algorithm gave a better result by not including it. @SharangP
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205253669390494) by [Unito](https://www.unito.io)

[EA] Date cutoff for frontpage quick takes

---

packages/lesswrong/components/revisions/CompareRevisions.tsx

Previously extremely long tag-diffs just took up and extremely-lot-of-space in Recent Discussion. This truncates them.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205272756576574) by [Unito](https://www.unito.io)

Click to expand long tag diffs

---

packages/lesswrong/components/posts/EAPostsItem.tsx
packages/lesswrong/themes/siteThemes/eaTheme.ts

Plus, bonus: sans serif titles for chapters
Before
After
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205253687555060) by [Unito](https://www.unito.io)

[EA] Fix overflow of `EAPostsItem`s with checkboxes on mobile sequences

---

packages/lesswrong/components/sunshineDashboard/SunshineNewUsersProfileInfo.tsx

When viewing a user's profile, we often want to look at the sunshine info without actually unapproving them.  Now that we have a separate button inside that very component for putting users back into the review queue, it's time to just change it to "Expand" (with no effects on the user).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205279922724179) by [Unito](https://www.unito.io)

replace unapprove with expand for sunshine info on user profiles

---

packages/lesswrong/components/hooks/useNotifyMe.ts

The bell icon next to the Subscribe button remains in an infinite loading state if you SSR a tag page directly, rather than navigate to one from elsewhere on LessWrong, while logged out.  I'm pretty sure this comes from useNotifyMe, which does the following:
```
// Get existing subscription, if there is one
const {results, loading, invalidateCache} = useMulti({
terms: {
view: "subscriptionState",
documentId: document._id,
userId: currentUser?._id,
type: subscriptionType,
collectionName,
limit: 1,
},
collectionName: "Subscriptions",
fragmentName: "SubscriptionState",
enableTotal: false,
skip: !currentUser
});
if (loading) {
return {
loading: true,
};
};
```
Unfortunately, Apollo returns loading: true when you set skip: true.
Bug:
Fixed: …

fix infinite loading spinner for sub status icon when no logged-in user

---

packages/lesswrong/lib/rateLimits/constants.ts

This makes it so 2000+ karma users require more unique downvoters to get the 1 comment/day rate limit
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205289569941450) by [Unito](https://www.unito.io)

Update auto rate limits so 2000+ users have more leeway

---

packages/lesswrong/components/common/HeadTags.tsx

I've already added this setting to the bot site so this should work as soon as it's deployed
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205292469553819) by [Unito](https://www.unito.io)

Add site wide noindex setting (for use on bot site)

---

packages/lesswrong/components/hooks/useAnalytics.ts
packages/lesswrong/server/analytics/hybridViews.ts
packages/lesswrong/server/analytics/postViewTimesHybridView.ts
packages/lesswrong/server/analytics/postViewsHybridView.ts

- Making the indexes consistent with the ones in the database
- A fix for a bug that caused the graph to reload after SSR due to the timezone being different on the client and the server
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205304458665184) by [Unito](https://www.unito.io)

Some bug fixes for the author analytics page

---

packages/lesswrong/components/common/HomeLatestPosts.tsx
packages/lesswrong/lib/collections/tags/collection.ts
packages/lesswrong/server/resolvers/recentDiscussionFeed.ts

Recently, we've been getting waves of translations jamming up recent discussions. This PR excludes the 'translation' tag from showing up there.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205296287378882) by [Unito](https://www.unito.io)

Exclude posts tagged with 'translation' from recent discussions

---

packages/lesswrong/lib/cookies/cookies.ts

We were slightly over-zealous on the first pass of this, as none of these cookies are a particular privacy concern, and not being able to set them has caused problems for some users. GDPR [states](https://gdpr.eu/cookies/) that strictly necessary cookies "are essential for you to browse the website and use its features", and gives the example of a cookie to remember the contents of a shopping cart as an example. All of these are about this level of necessary-ness
In the medium run (within a week or so) we are also planning to make all these use localStorage instead, mainly to avoid the wrong version getting cached. But this is a smaller change in the meantime to let people hide banners without accepting cookies …

Change most non-privacy-concern cookies from functional to necessary

---

packages/lesswrong/components/common/BotSiteBanner.tsx
packages/lesswrong/components/ea-forum/EAHome.tsx
packages/lesswrong/lib/components.ts

Adding a banner to https://forum-bots.effectivealtruism.org/ , mainly so people who realise their bots are being redirected there will understand why if they go to the url. Also, even though the site has `noindex` tags set now it doesn't seem to have come through to google yet so people might still end up there accidentally
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205319779514740) by [Unito](https://www.unito.io)

Add banner to bot site

---

packages/lesswrong/lib/collections/posts/schema.tsx

Previously the behaviour was:
- You couldn't change the value of `question` after a post was created
Now the behaviour is:
- You can change a post to a question and vice versa
- If there are comments on a post and then you change it to a question, they stay as comments and not answers
- If there are answers on a question and then you change it to a post, they don't appear on the post
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205320150444945) by [Unito](https://www.unito.io)

[EA] Allow changing a post to a question and vice versa

---

packages/lesswrong/components/bookmarks/VoteHistoryTab.tsx
packages/lesswrong/lib/collections/votes/fragments.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

Comments on the vote history page (/saved#votehistory) weren't properly associated with their posts, so their permalinks were just to the root domain (issue #7698), and their menus were missing options (issue #7699). Changing the comment fragment from CommentsList to CommentsListWithParentMetadata solves this.
(I didn't really intend to solve these issues, but stumbled into it when looking at forumType conditionals.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205348359134582) by [Unito](https://www.unito.io)

Fix comment-post association on VoteHistoryTab

---

packages/lesswrong/lib/voting/reactions.tsx

This is a single-character change that removes a mistaken apostrophe in the description for the "combative" reaction.
Formerly: "This seems more combative than it needs to be to communicate it's point."
The fix: "This seems more combative than it needs to be to communicate its point."
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205331965720846) by [Unito](https://www.unito.io)

Fix typo in the "combative" reaction description text

---

packages/lesswrong/components/seasonal/HomepageMap/HomepageMapFilter.tsx

Meetups month link on the homepage community map was pointed to a post from 2022, instead of the most recent post.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205360319850296) by [Unito](https://www.unito.io)

fix meetups month link

---

packages/lesswrong/components/books/Book2020Animation.tsx

Our version of JSS has a bug, [later patched](https://github.com/cssinjs/jss/commit/5ba7a653aad162fa5b00ab80d9c2f29e0a741baa), which caused referenced rules inside media queries not to be found. As a result, the only effect of the rules I've removed were to cause console errors.
Things I've done to test that there's no regression:
- Tried adding the rules correctly, and noticing that it caused a visual bug
- Inspected the resultant css and noticed that the current code does not accurately select the elements it's trying to select
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205360018082647) by [Unito](https://www.unito.io)

Fix console errors due to JSS bug

---

packages/lesswrong/components/seasonal/HomepageMap/HomepageCommunityMap.tsx
packages/lesswrong/components/seasonal/HomepageMap/acxEvents.ts

This makes it much more obvious during testing that we forgot to update the hardcoded list of events.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205369525086421) by [Unito](https://www.unito.io)

hide old acx events from the frontpage map

---

packages/lesswrong/server/editor/conversionUtils.ts
packages/lesswrong/unitTests/editorUtils.tests.ts

https://github.com/ForumMagnum/ForumMagnum/issues/7392 modified `dataToWordCount` to have a stage where it looks for a section-heading containing the string "Appendix", and exclude everything after that from the word-count. In order to do this, it goes through an extra format-conversion step; where before it would go from the original format (usually CkEditor HTLM) to Markdown, and after it would go from original to Markdown then to HTML. Unfortunately, there's an unrelated bug in our HTML-to-Markdown conversion (or perhaps in our Markdown-to-HTML conversion) which causes LaTeX statements to wind up double- escaped, making them syntactically invalid, so on posts containing affected LaTeX (such as https://www.lesswrong.com/posts/zkfmhWQXsZweijmzi/causality-and-a-cost-semantics-for-neural-ne …

Make word-counter resilient to LaTeX errors (including those introduced by conversions)

---

packages/lesswrong/lib/collections/posts/schema.tsx

Members can change the deletedDraft flag on their posts, which makes sense because sometimes they'll want to delete their posts. But nothing stops them from changing a deleted post back to un-deleted, if they craft the right request. That's bad, right? Because sometimes admins delete bad posts, and intend that they stay deleted.
So this pull request adds an onUpdate check to DbPost.deletedDraft that prevents members changing deletedDraft=true to deletedDraft=false.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205356093820558) by [Unito](https://www.unito.io)

Prevent non-admins un-deleting posts

---

packages/lesswrong/themes/siteThemes/lesswrongTheme.ts

On the LessWrong top right users menu, the lower part of the letter g is slightly cut off (tested in Chrome and Firefox on MacOS, and in Chrome on Android):
Increasing the MuiMenuItem lineheight of the lesswrongTheme from 1em to 1.1em solves this, so this is a single-line change that does that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205349474051802) by [Unito](https://www.unito.io)

Solve LW menu item height being too short for the letter 'g'

---

packages/lesswrong/lib/rateLimits/constants.ts

- Add a new rule that limits posts based on recent post karma. We'd previously removed this because it was punishingly unfair (imagine you have one dogpiled comment), but Ray & I think this is a little fairer and Ray thinks we need it
- Edit some text to be more accurate
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205390507243991) by [Unito](https://www.unito.io)

Add -30 recent karma post rate limit

---

packages/lesswrong/components/posts/PostSubmit.tsx

When users submitted feedback requests for posts that hadn't been saved yet, we immediately created an intercom event and attempted to reference a post id that didn't exist yet.  Move that event into the success callback after submission goes through.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205381659548116) by [Unito](https://www.unito.io)

fix undefined post ids in feedback requests for unsaved posts

---

packages/lesswrong/components/ea-forum/EAHome.tsx
packages/lesswrong/components/ea-forum/EAHomeMainContent.tsx
packages/lesswrong/components/recommendations/LWRecommendations.tsx
packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
packages/lesswrong/components/spotlights/DismissibleSpotlightItem.tsx
packages/lesswrong/components/spotlights/SpotlightItem.tsx
packages/lesswrong/components/spotlights/SpotlightStartOrContinueReading.tsx
packages/lesswrong/lib/collections/spotlights/views.ts
packages/lesswrong/lib/collections/tags/fragments.ts
packages/lesswrong/lib/components.ts

Lizka and I discussed adding this along with the regular spotlight during the hackathon.
We need to create spotlights for the intro sequences on prod, which shouldn't be hard. And probably get 100% coverage?
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205390132689074) by [Unito](https://www.unito.io)

[EA] Add a spotlight for the intro sequence for the frontpage selected topic

---

packages/lesswrong/components/tagging/FooterTagList.tsx
packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx

We're finding these pretty noisy and we don't get any use out of them.  Forum-gated in case the EA forum wants to keep them, but easy to change if not.  Merging in quickly because we want to delete all the corresponding historical records from the database and don't want new ones going in after that happens.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205400266975571) by [Unito](https://www.unito.io)

filter out analytics events not used by lw

---

.github/workflows/cypress.yaml
.github/workflows/unitTests.yaml

We no longer need to spawn mongo service containers in CI pipelines
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205400940389219) by [Unito](https://www.unito.io)

Don't spawn mongo service contains in CI

---

packages/lesswrong/server/search/elastic/ElasticQuery.ts
packages/lesswrong/server/search/elastic/ElasticService.ts

This PR builds on #7613 to improve highlighting of results for advanced search queries (ie; queries with quotes). Currently, we use a "default" query for highlighting which means that the highlight for quoted queries containing multiple words often only shows one of the necessary words. This can be confusing, and even though the query is correct we've had users reporting that they think it's wrong because the highlight is misleading.
This PR improves the quality of the query used for highlighting advanced queries to ensure that quoted spans are highlighted correctly. The primary mechanism for this is by using the `*.exact` mappings for the relevant fields, switching to the "simple" analyzer, and using a `match_phrase` query. I also switched the highlighter from the default "unifed" …

Improve highlighting of results for advanced search queries

---

packages/lesswrong/server/partiallyReadSequences.ts

This fixes a bug in continue reading, which broken during during the switch over to Postgres, in this commit:
https://github.com/ForumMagnum/ForumMagnum/commit/7f94ee0bf8ffb7b55d86d9c76f0194d6749e3cb9
(Looks like @oetherington accidentally changed the return type in the postgres half of the if-tree)
Since now we're not even using Mongo, I removed the mongo half completely. (@b0b3rt said this was fine, although on the off chance anyone is like 'wait no please keep mongo functionality', let me know)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205407128751306) by [Unito](https://www.unito.io)

Fix continue reading bug

---

packages/lesswrong/components/posts/PostsPage/PostsPageTitle.tsx

Previously:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205400645941199) by [Unito](https://www.unito.io)

[EA] Use nowrap span to prevent an orphaned link icon

---

packages/lesswrong/components/comments/DebateResponseBlock.tsx

On the theory that what some users want is to have a dialogue, then have someone take it and edit it, and that what the editor will probably do is copy-paste the dialogue into the New Post page or Google Docs, I tried that copy paste. It mostly worked, but usernames and comment-timestamps appeared next to each other with no space. So, add a space (and reduce the margin by the corresponding amount.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205429046726704) by [Unito](https://www.unito.io)

Fix a missing between username and date when copy-pasting out of dialogues

---

packages/lesswrong/lib/collections/comments/schema.ts

We changed the name from debate to dialog to be less combative-oriented
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205429000725955) by [Unito](https://www.unito.io)

changed name from debate to dialogue

---

packages/lesswrong/components/users/EAUserTooltipContent.tsx

Because of the way that numbers work, we currently display the amount of user karma incorrectly in the EA user tooltip if the user has more than 1000 karma and the hundreds digit is 0.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205404109751164) by [Unito](https://www.unito.io)

Fix formatting of karma >1000 in EA user tooltip

---

packages/lesswrong/components/common/AnalyticsClient.tsx
packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx

- LW don't want A/B test groups in their events because it bloats the raw analytics table
- Un-forum-gate the change introduces in https://github.com/ForumMagnum/ForumMagnum/pull/7800 to filter out SSr events due to health checks or bots
I have made a followup ticket to unify this checking for bot user agents with the check in `botRedirect.ts`: https://app.asana.com/0/1124817936128791/1205442383981364/f
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205442417171610) by [Unito](https://www.unito.io)

Forum-gate adding A/B test groups to analytics events, un-forum-gate filtering out junk SSR events

---

packages/lesswrong/components/comments/DebateResponse.tsx
packages/lesswrong/components/messaging/MessageItem.tsx

Inspired by Jim's "copy pasting update" in https://github.com/ForumMagnum/ForumMagnum/pull/7817
I wanted to be able to copy-paste DMs and have it look reasonable. This involved slightly changing the formatting in a way that seems fine to me:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205437442141902) by [Unito](https://www.unito.io)

Add space to DM convo

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/Header.tsx
packages/lesswrong/lib/publicSettings.ts
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/themeType.ts

Add text to the site header advertising career week.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205451056108330) by [Unito](https://www.unito.io)

[EA] Career week header banner

---

packages/lesswrong/components/common/Header.tsx
packages/lesswrong/components/common/HeaderSubtitle.tsx
packages/lesswrong/lib/routes.ts

Remove the careers week event link from the page header on pages with a subtitle.
Unfortunately, some pages (most notably the post page) lie about having a subtitle by providing a component that always returns null. I've disabled this for the EA forum on posts pages - there may be other pages with this problem that we can fix as we find them.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205454290211877) by [Unito](https://www.unito.io)

Careers week header improvements

---

packages/lesswrong/components/comments/DebateResponse.tsx
packages/lesswrong/components/votes/lwReactions/NamesAttachedReactionsVoteOnComment.tsx
packages/lesswrong/lib/collections/posts/fragments.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts
packages/lesswrong/lib/voting/votingSystems.tsx
packages/lesswrong/server/voteServer.ts

We previously made it so only dialogue participants could react to dialogResponse comments, but the "add react" button was still visible for everyone. This hides it for non-participants.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205447188819595) by [Unito](https://www.unito.io)

Hide React button for non-participants in dialogues

---

packages/lesswrong/lib/notificationTypes.tsx

Changing the icon of new debate notifications to match the frontpage debate icon. 
(Currently it's the same as the comment notification icon, which is annoying when scanning notifications)

change debate icon in notification

---

packages/lesswrong/components/Layout.tsx

This hides the frontpage map. It leaves in most of the relevant infrastructure so that it's easier to turn on next time. (I think we maybe actually want to switch this to work more like Petrov Day, where you enter a start-date and end-date into a database setting, and then it naturally turns off without intervention later on, but, will tackle that later)
Right now the map has been up ~2 weeks, which I think is roughly what we intended (although we hadn't made an explicit plan for teardown)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205459543658177) by [Unito](https://www.unito.io)

Hide ACX Frontpage map

---

packages/lesswrong/server/search/elastic/ElasticConfig.ts
packages/lesswrong/server/search/elastic/ElasticExporter.ts
packages/lesswrong/server/search/elastic/ElasticQuery.ts
packages/lesswrong/server/search/elastic/parseQuery.ts

This PR fixes several search bugs. In particular:
- Search for users now has a much better balance between searching for exact name matches and boosting relevancy by karma
- Fixed a bug with hyphenated words in the query parser
- Added an apostrophe filter which greatly improves searching for quick takes posts
In particular, the following searches for users which have been reported as problematic now produce much more sane results:
```
will howard
will macaskill
william macaskill
michael thurston
social hermit
claire zabel
```
and the following searches for posts:
```
centre for long-term resilience
lizka quick takes
```
This requires re-indexing (which I've so far only done on dev):
1) Run `Globals.elasticConfigureIndexes()` which runs an _async_ reindex
2) Wait for the reindex to …

Various search fixes

---

packages/lesswrong/server/rateLimitUtils.ts
packages/lesswrong/server/repos/VotesRepo.ts

Debate responses aren't voted on. I believe (though only spent 5 minutes checking) is the place to exclude debate responses from comments when checking autoratelimit rules.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205469594964997) by [Unito](https://www.unito.io)

Don't count debateResponses for rate limits

---

packages/lesswrong/components/ea-forum/users/EAUsersProfileImage.tsx

When viewing the user profile of a user who you do not have permission to edit (ie; it's not you and you're not an admin), there's currently too little padding between the image and the username due to a class not being applied in the right place (thanks Agnes for spotting this!)
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205451146100636) by [Unito](https://www.unito.io)

Fix missing bottom padding on EA users profile image

---

packages/lesswrong/components/questions/NewAnswerCommentQuestionForm.tsx

When answering question posts, you can click a focus mode button to remove most of the content of the page. It's the full-screen icon button (middle-right):
When you click it, it covers most of the content of the page with a large white rectangle:
```
whitescreen: {
display: "none",
position: "absolute",
left: -300,
width: 3000,
top: 0,
height: 5000,
backgroundColor: theme.palette.panelBackground.default,
zIndex: theme.zIndexes.questionPageWhitescreen,
}
```
This blocks out the content, but makes the scrollbars widen, as the page is now much bigger:
Instead, we can make the box have position "fixed" and inset 0 (inset is CSS shorthand to set the top, right, bottom, and left values all at once), making the box fit exactly over wherever the user is on the page.
```
whitescreen: {
display: …
```

Improve dimensions of answer/comment focus mode

---

packages/lesswrong/lib/vulcan-lib/utils.ts

See: https://www.lesswrong.com/posts/6rnWQW8HtHoavPDiu/weekly-incidence-vs-cumulative-infections?commentId=2hfbGb2w5md7MSrRL
This adds MathML tags to the tag-whitelist in the sanitizer, along with (non-deprecated) attributes for those tags. I generated this by going through https://developer.mozilla.org/en-US/docs/Web/MathML/Element and copy-pasting element and attribute names. I don't believe any of the tags/attributes allowed here can have scripts in them (but there is nonzero risk of error on that).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205446460391328) by [Unito](https://www.unito.io)

Allow MathML in the HTML sanitizer (for RSS crossposters)

---

packages/lesswrong/components/common/SearchBar.tsx
packages/lesswrong/components/search/SearchAutoComplete.tsx
packages/lesswrong/components/search/SearchPage.tsx
packages/lesswrong/components/search/SearchPageTabbed.tsx
packages/lesswrong/components/tagging/AddTag.tsx
packages/lesswrong/lib/search/algoliaUtil.ts
packages/lesswrong/server/search/elastic/elasticSettings.ts
packages/lesswrong/server/voteServer.ts

This redirects everything that was previously checking `isAlgoliaEnabled()` to instead check `isSearchEnabled()`. Once this is merged, we can then take Algolia API keys out of our server config, which will stop the server from trying to write to Algolia, so that we can shut down the Algolia account and stop paying for it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205245163602186) by [Unito](https://www.unito.io)

Stop writing to Algolia now that we've switched to ElasticSearch

---

packages/lesswrong/server/repos/CommentsRepo.ts

This PR adds a simple recency bonus to comments in the popular comments algorithm with an exponential backoff. The `recencyFactor` may need some fine tuning, but this default seemed reasonable to me in testing. We limit popular comments to comments created in the last week, so `EXTRACT(EPOCH FROM CURRENT_TIMESTAMP - c."postedAt")` will be a value between 0 (for a brand new comment) and 604800 (for a one week old comment).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205484191926291) by [Unito](https://www.unito.io)

Add recency factor to popular comments algorithm

---

packages/lesswrong/lib/collections/spotlights/schema.ts

A previous EA Forum PR can made spotlight imageFade into a schemaDefaultValue, which breaks our schema hash system. This changes it to use the same logic we used on the voting system.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205511997344779) by [Unito](https://www.unito.io)

Fix spotlight imageFade default value

---

packages/lesswrong/components/comments/DebateTypingIndicator.tsx
packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/server/resolvers/typingIndicatorsResolvers.ts

This cleans up a few things about TypingIndicators
– we were previously sending off TypingIndicator updates every 300 ms, which added up to enough requests to get IP addresses rate limited. This reduces the update throttle-interval to every 15000 ms. (It's plausible to me it should literally be the same as the period that we display the indicator, which is 20000 ms, but I wasn't sure, seemed probably good to design it so we can easily tweak them independently but they live next to each other so it's easy to think about how they relate)
– there were two versions of the "isDialogueParticipant" function, and this trims out one of them.
– adds a comment flagging that we're currently using a somewhat simplified trigger for the typing indicator. …

Reduce typing indicator rate-limit risk, and streamline duplicate isDialogueParticipant

---

packages/lesswrong/lib/rateLimits/constants.ts

My current take is that it's "technically reasonable" for users with <5 karma to be rate limited on their own posts, but, a) I think other LW team members disagreed and I don't feel very strongly about it, b) I think the costs of having to model that some-but-not-all rate limits affect your own posts was more confusing and costly than it was worth.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205513917126221) by [Unito](https://www.unito.io)

All LW rate limits don't affect your own posts

---

packages/lesswrong/components/comments/DebateResponse.tsx

I found that sometimes I really wanted to make a debate response that felt more separated from my previous response. I do _also_ sometimes want to be able to write out multiple chains of responses that add up to one big essay. Here I'm experimenting with a slight margin in between them, which I think probably works okay for both use cases.
Not 100% sure this is good, PR review can include deciding that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205513876390415) by [Unito](https://www.unito.io)

Debate response styling is separated slightly

---

packages/lesswrong/components/form-components/TagMultiselect.tsx
packages/lesswrong/components/search/SearchAutoComplete.tsx
packages/lesswrong/components/search/TagsSearchAutoComplete.tsx

We have a search facet that filters out `wikiOnly` tags when tagging a post. This is defined using the `filters` parameter on the search endpoint which was never implemented when we switched to elasticsearch. For the sake of keeping the API simple, I switched the frontend to instead use the `facetFilters` parameter which is already supported by the backend.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205510920760427) by [Unito](https://www.unito.io)

Fix `wikiOnly` tags being shown in search when faceted out

---

packages/lesswrong/server.ts
packages/lesswrong/server/scripts/checkPostForSockpuppetVoting.ts

We were worried about users potentially voting on a post (or its comments) multiple times via sockpuppet accounts. I wrote this script to help us investigate. It's not totally done, but the part that compares client IDs should be done, and that seems like a good start.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205453648499772) by [Unito](https://www.unito.io)

add script for checking a post for sockpuppet voting

---

packages/lesswrong/components/hooks/useUnreadNotifications.ts

Disabling right now because it's not a great experience showing up on all tabs for all notifications. Will re-enable it when we figure out a better ontology, i.e. showing it only on dialogue pages for new dialogue content, or only showing it on the page where a user is actively in a conversation and got a new DM.

disable favicon badge on new notifications

---

packages/lesswrong/server/search/elastic/ElasticQuery.ts

Searching for some posts would fail with:
```The length [1172188] of field [org.elasticsearch.search.fetch.subphase.highlight.SearchHighlightContext$Field@6df18257] in doc[sHGxvJrBag7nhTQvb]/index[posts_1690498279910] exceeds the [index.highlight.max_analyzed_offset] limit [1000000]. To avoid this error, set the query parameter [max_analyzed_offset] to a value less than index setting [1000000] and this will tolerate long field values by truncating them.```
Eg the query "invu" which should return https://www.lesswrong.com/posts/sHGxvJrBag7nhTQvb/invulnerable-incomplete-preferences-a-formal-statement-1 as a result.
This applies the suggested change, and it does indeed cause the search to no longer fail. (The value of `1000000` is a default value in the index config, which we don't …

Fix search failing when query returns a very-long post

---

packages/lesswrong/components/titles/PostsPageHeaderTitle.tsx
packages/lesswrong/lib/routes.ts

This component only ever returned `null` in the case where it was used as a subtitle. Presumably in the past it has returned something different but now those cases are gone.
See also [this discussion](https://github.com/ForumMagnum/ForumMagnum/pull/7843#discussion_r1320354295), where @oetherington and @jpaddison3 noticed the same thing, this was causing some problems with our new `currentEvent` subtitle because it wouldn't show if PostsPageHeaderTitle was used as a subtitle component.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205514826364770) by [Unito](https://www.unito.io)

Remove subtitle-ability of PostsPageHeaderTitle component

---

packages/lesswrong/components/form-components/FormComponentDateTime.tsx

Previously it would throw an error if you tried to type, now it lets you type and shows a red line if you type an invalid date
Known issues with this:
1. The error doesn't actually block you from submitting the form (it just submits with the last valid value)
2. If you clear the input, then type an invalid date, then click clear again, it will not clear the second time
Both of these are relatively hard to fix, so I think it's worth merging like this. We could also make it so you can't type at all which would avoid these bugs
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205524926291485) by [Unito](https://www.unito.io)

Fix typing in date picker

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/server/serverSentEvents.ts

There were two additional bugs with TypingIndicators
1. TypingIndicators were accidentally triggering the "reload all debateResponse comments" refetch, because that didn't check for the new eventType field
2. The "time to check for new TypingIndicators" wasn't properly updating because it was using the createdAt date for TypingIndicators (which never changes) rather than the lastUpdated field (which does)
This had previously resulted in, every time the typingIndicator throttle triggered, it'd _both_ receive a typingIndicators message (even if there weren't new ones) and would refetch all the comments.

Fix typingIndicator getting sent repeatedly

---

packages/lesswrong/server/repos/PostsRepo.ts

There's currently a bug where we show everyone who _ever_ added a reaction to a post even if they then removed that reaction. Note that this only affects reactions on posts, not on comments.
Can be seen very clearly on [https://forum.effectivealtruism.org/s/vw6tX5SyvTwMeSxJk/p/JYEAL8g7ArqGoTaX6](https://forum.effectivealtruism.org/s/vw6tX5SyvTwMeSxJk/p/JYEAL8g7ArqGoTaX6) and [https://forum.effectivealtruism.org/posts/w59DkYCJYqaYDpEqG/mistakes-flukes-and-good-calls-i-made-in-my-multiple-careers](https://forum.effectivealtruism.org/posts/w59DkYCJYqaYDpEqG/mistakes-flukes-and-good-calls-i-made-in-my-multiple-careers), for instance.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205556044262353) by [Unito](https://www.unito.io)

Exclude un-reactors from reactor lists on posts

---

packages/lesswrong/components/events/modules/VirtualProgramCard.tsx

This PR is mostly to update the Precipice VP card dates, since it's switched to being every 3 months now. Intro and In-Depth are still monthly.
I also updated some of the styling to match the other event cards.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205562824323497) by [Unito](https://www.unito.io)

[EA Forum only] update VP event cards (Precipice is every 3 months now)

---

packages/lesswrong/components/hooks/usePaginatedResolver.ts

For paginated resolvers, we actually render a cached version of the result rather than the return value from `getQuery`. This change makes the list refresh even if the length is the same which fixes the current bug where you can't vote on comments in the "Popular comments" section. Eventually, I'd like to work out how we can remove this caching layer and use the result directly, but I don't have time at the moment so this will do for now.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205568534950570) by [Unito](https://www.unito.io)

Fix voting bug on popular comments

---

build.js
packages/lesswrong/server/analyticsWriter.ts
packages/lesswrong/server/apolloServer.ts
packages/lesswrong/server/branchDb.ts
packages/lesswrong/server/cronUtil.ts
packages/lesswrong/server/search/elastic/ElasticClient.ts
packages/lesswrong/server/serverStartup.ts
packages/lesswrong/server/sqlConnection.ts
scripts/startup/autoRefreshServer.js

Adds `yarn eslint` to esbuild's `onStart`, so we get linting as well as type checking on saves that trigger hot reload.  Also cuts down on some historical console logs that seem like they're more noisy than they're worth.
Co-authored-by: jimrandomh <jim@jimrandomh.org>

add lint to esbuild and reduce console log spam

---

packages/lesswrong/components/ea-forum/EABestOfPage.tsx
packages/lesswrong/components/posts/EAPostsItem.tsx
packages/lesswrong/components/recommendations/PostBottomRecommendations.tsx
packages/lesswrong/server/repos/PostsRepo.ts
packages/lesswrong/server/repos/helpers.ts
packages/lesswrong/server/resolvers/postResolvers.ts

Adds new recommendation algorithm to avoid using the digest:
- Highlights this month on the best-of page now uses posts that were created this month that have been curated (this could be posts that were curated this month but are any age, if we want more results)
- "Recommended by the Forum team this week" under posts is now "Curated and popular this week", which selects any posts curated this week, and if there are less than 3 (which there usually are) we just pick the highest karma non-community posts to make up the difference

Non digest recommendation algorithms

---

packages/lesswrong/server.ts
packages/lesswrong/server/scripts/convertAllPostsToEAEmojis.ts
packages/lesswrong/server/sqlConnection.ts

This PR adds a manual script to convert all historical posts to the new EA emojis voting system. Note that we only actually convert posts with the "default" voting system or the "twoAxis" voting system. The prod database currently has 3 posts with different experimental voting systems (LNbzDCgCH2py3cnJv, whEmrvK9pzioeircr and yMptv5msFnnfESCqm) which we leave as they are.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205585559880934) by [Unito](https://www.unito.io)

[EA] Convert all posts to use EA emoji reactions

---

packages/lesswrong/components/votes/EAReactsSection.tsx
packages/lesswrong/lib/voting/eaEmojiPalette.ts

It's currently possible to both agree and disagree with a single comment or post which is incorrect.
I've not made any attempt to change existing places where this has happened because:
1. We don't know whether the user actually wanted to agree or disagree
2. There's only 13 such votes in the entire database which seems acceptable
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205591491093968) by [Unito](https://www.unito.io)

Make agree/disagree emojis mutually exclusive in `eaEmojis` voting system

---

packages/lesswrong/components/search/SearchAutoComplete.tsx
packages/lesswrong/components/tagging/AddPostsToTag.tsx
packages/lesswrong/server/search/elastic/ElasticQuery.ts
packages/lesswrong/server/search/elastic/ElasticService.ts
packages/lesswrong/unitTests/elastic/elasticService.tests.ts

We had a bug report from Lizka that the search box for adding tags directly from the tags page wasn't working. It turns out this was due to the elasticsearch backend not supporting negated facets. Upon furth inspection, it also turns out that there's a bug that's been here for the last three years when a test tag ID from lesswrong was hard coded into the filter instead of using the actual current tag ID for filtering results, so I fixed that too.
I also added dark mode styling for the search box:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205598261006312) by [Unito](https://www.unito.io)

Fix adding posts on tag page

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/TabNavigationMenu/NavigationStandalone.tsx
packages/lesswrong/components/common/TabNavigationMenu/TabNavigationItem.tsx
packages/lesswrong/components/common/TabNavigationMenu/TabNavigationMenu.tsx
packages/lesswrong/components/common/excerpts/PostExcerpt.tsx
packages/lesswrong/components/ea-forum/EABestOfPage.tsx
packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx
packages/lesswrong/components/hooks/useCurrentCuratedPostCount.ts
packages/lesswrong/components/hooks/useForeignCrosspost.ts
packages/lesswrong/components/hooks/useRecentOpportunities.ts
packages/lesswrong/components/posts/LinkPostMessage.tsx
packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/components/recommendations/CuratedPostsList.tsx
packages/lesswrong/components/recommendations/PostBottomRecommendations.tsx
packages/lesswrong/lib/betas.ts
packages/lesswrong/lib/collections/posts/views.ts
packages/lesswrong/server/repos/PostsRepo.ts
packages/lesswrong/server/resolvers/postResolvers.ts

This PR addresses the issuses and changes requested for the current batch of new features:
- Popular comments
- Un beta-gate the popular comments section
- Best of page
- Rename "featured video" to "featured videos"
- Show curated stars on "highlights this month" posts
- Boost relevant tags in lists of recommendad opportunities on best of page and frontpage RHS
- Bottom of post recommendations
- Exclude the current post from "more from the author"
- Exclude read posts from "curated and popular this week"
- Reduce vertical padding
- Recent discussions
- Fix color of link post link
- Fix display of crosspost bodies in recent discussions
- Main navigation menu
- Fix main menu item link hit boxes
- Fix main menu top margin on pages other than the frontpage
- Frontpage RHS
- Align the toggle …

EA New feature tweaks

---

packages/lesswrong/components/ea-forum/EABestOfPage.tsx
packages/lesswrong/components/editor/EditTitle.tsx
packages/lesswrong/lib/routes.ts

* "View more" on best of page is now 14px instead of 16px
* Best of page now have a subtitle in the top bar (like events and groups)
* Draft post titles are now the same size as published titles
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205632392729320) by [Unito](https://www.unito.io)

UI nitpicks post October release

---

packages/lesswrong/components/posts/PostSubmit.tsx

We've had a couple experiences where people have accidentally published dialogues without meaning to.  Interpose a confirmation modal for dialogues (forum-gated to LessWrong) to make this less likely to happen.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205635740868647) by [Unito](https://www.unito.io)

publishing requires confirmation for lw dialogues

---

packages/lesswrong/server/scripts/convertImagesToCloudinary.ts

We've had a lot of reports over the last couple of days of users having errors when creating posts, and this leading to posts being created multiple times due to re-clicking "Submit". I've still not been able to replicate the error, but the stack traces say it's a "TypeError: Invalid URL" error happening at `new URL` in `urlNeedsMirroring`. This can happen for anything that isn's a valid URL like `null` or `undefined` or `www.google.com` (without "https://"). The safest thing to do seems to just be to catch the error and continue in this situation - the worst thing that can happen is that a valid URL doesn't get mirrored, but if this happens then the URL probably isn't valid anyway.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205648580044189) by …

Skip mirroring images with invalid URLs

---

packages/lesswrong/components/comments/CommentsItem/useCommentLink.tsx
packages/lesswrong/components/vulcan-core/ScrollToTop.tsx

Fix comment-permalinks to comments inside the same post not scrolling to show the comment (#7939). Also comment-permalinks no longer eat the back-button history entry when you click them.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205662224216137) by [Unito](https://www.unito.io)

Fix comment permalink scroll

---

packages/lesswrong/lib/helpers.ts
packages/lesswrong/lib/random.ts

Fun fact: If you create a post named "Test" in the dev DB (on a development laptop with slowish round trip time to the database), it takes over a minute, because it's checking whether slugs `test-1`, `test-2`, `test-3`, ... `test-300` are taken.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205645380841975) by [Unito](https://www.unito.io)

Fix an issue where getUnusedSlug can be very slow if there are many posts with the same slug-prefix

---

packages/lesswrong/components/common/excerpts/ContentExcerpt.tsx
packages/lesswrong/lib/editor/ellipsize.tsx

The new EA recent discussions section is broken on some versions of ios because safari is terrible:
I don't actually have an affected device to test on, but this _should_ fix it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205650438705574) by [Unito](https://www.unito.io)

Fix ea recent discussions truncation

---

packages/lesswrong/server/repos/PostsRepo.ts

Hovering over EA emojis currently shows the users who selected that emoji ordered by the amount of karma they have from most to least. This PR changes this to instead order them by the date they added the emoji from oldest to newest.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205651707912184) by [Unito](https://www.unito.io)

Order EA emoji users by date

---

packages/lesswrong/components/recentDiscussion/EARecentDiscussionItem.tsx

Adds an analytics context to `EARecentDiscussionItem` - diff is ugly because of indentation changes.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205649190883484) by [Unito](https://www.unito.io)

Add analytics context to EARecentDiscussionItem

---

packages/lesswrong/server/notificationCallbacks.tsx

Previously, if someone made a ton of dialogue responses, they would all show up as notifications for the collaborators in the dialogue (i.e you might get like 50 notifications). This makes it so you only get at most one notification until you check your notifications again.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205671835070464) by [Unito](https://www.unito.io)

Only send dialogue notifications if you haven't checked your previous dialogue notifications

---

packages/lesswrong/server/editor/make_editable_callbacks.ts

We're calling out to `convertImagesInObject` for pretty much all post mutations, including `lastCommentedAt` being updated (which happens whenever a user comments).  Local motivation is that this was interacting badly with a separate bug which caused images to break, but let's not do that for no reason anyways.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205672400037309) by [Unito](https://www.unito.io)

don't reupload images if a post's html hasn't changed

---

packages/lesswrong/components/common/HeadTags.tsx

Twitter's "summary_large_image" card currently shows only an image with no title/description/etc, so we only ever use "summary". Before Twitter made this change, we switched between "summary" and "summary_large_image" based on the `useSmallImage` prop. Twitter is getting backlash about this, so they might revert (in which case we might also revert).
See: https://news.ycombinator.com/item?id=37782945
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205664146372173) by [Unito](https://www.unito.io)

Switch Twitter link-card style

---

packages/lesswrong/components/dropdowns/posts/ResyncRssDropdownItem.tsx
packages/lesswrong/lib/crud/withUpdate.tsx

For reasons I'm not entirely clear on, after submitting the Resync RSS form (which does a `useUpdate`) and doing the client-side cache updates, an exception would get thrown from Apollo internals. Turn off the client-side cache update in this case, since we're going to refetch everything anyways.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205663790729794) by [Unito](https://www.unito.io)

Fix post-resync refresh after using the Resync RSS button

---

packages/lesswrong/server/fmCrosspost/resolvers.ts

This PR caches foreign post bodies on the local server. For now I've set the TTL to 30-minutes which is just a number picked out of thin air. For me, a cache hit here reduces the render time of the post page for foreign crossposts from ~9 seconds to ~6 seconds.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205663310683292) by [Unito](https://www.unito.io)

Cache foreign crosspost bodies on the local server

---

packages/lesswrong/lib/collections/userRateLimits/index.ts
packages/lesswrong/lib/collections/userRateLimits/permissions.ts

Currently, only admins can create user rate limits - this PR also gives this power to sunshine regiment members.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205650700567755) by [Unito](https://www.unito.io)

Allow sunshineRegiment users to create user rate limits

---

packages/lesswrong/components/recommendations/PostBottomRecommendations.tsx
packages/lesswrong/server/recommendations/MoreFromAuthorStrategy.ts

Adds coauthored posts to the "more from the author" recommendations section under posts. Coauthored posts are shown below posts where the user is the main author.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205657959292808) by [Unito](https://www.unito.io)

Show coauthored posts in 'more from the author' recommendations

---

packages/lesswrong/components/recentDiscussion/EARecentDiscussionItem.tsx

Fixes an overflow bug I missed in #7974 which only showed up when testing with prod data.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205679758420845) by [Unito](https://www.unito.io)

Prevent horizontal overflow in EA recent discussions items

---

packages/lesswrong/components/editor/EditorFormComponent.tsx

Currently you can make a dialogue without participants, and then that creates a broken document that tries to run the post-fixers but breaks. This makes dialogues always collaborative, which IMO makes sense.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205686016326658) by [Unito](https://www.unito.io)

Make dialogues always collaborative

---

packages/lesswrong/components/posts/AllPostsList.tsx
packages/lesswrong/lib/analyticsEvents.tsx

The props for `AnalyticsContext` are currently typed as `any`. This is kind-of correct since it can actually take any props (well, at least anything that's JSON.stringify-able), but it means it ends up being rather confusing to use for several reasons:
- If you want to know what props are set by other components your only option is to grep the codebase which is annoying and error prone
- Some props such as `listContext` are officially deprecated but you won't know this unless you read the comment on `AnalyticsContext` (which, prior to this PR, is a normal comment and not a doc comment so your editor is unlikely to help you here)
- In some cases, the props are spelt wrong (`pageSubsectionContext` instead of `pageSubSectionContext` or `pageSection` instead of `pageSectionContext`)
This PR …

Strongly type props for `AnalyticsContext`

---

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
packages/lesswrong/components/common/ForumIcon.tsx

Fixes the size of the pinned comment icon on the EA users profile - I've just made it the same size as the pinned post icon.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205689835498665) by [Unito](https://www.unito.io)

Fix size of pinned comment icon on EA user profile

---

packages/lesswrong/components/comments/PopularCommentsList.tsx

Fixes a type error that was caused by an incompatability between #7945 and #7994 which were merged at roughly the same time.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205709950302972) by [Unito](https://www.unito.io)

Fix analytics typecheck in PopularCommentsSection

---

packages/lesswrong/server/fmCrosspost/crosspost.ts
packages/lesswrong/server/fmCrosspost/denormalizedFields.ts
packages/lesswrong/server/fmCrosspost/requestHandlers.ts
packages/lesswrong/server/fmCrosspost/types.ts

Crossposting has been broken for a while, seems to be due to URL field returning null and that not being allowed according to the validator. The change to make to URL not required was insufficient.
Fix here works by making optional values in `DenormalizedCrosspostValidator` be `PartialWithNull`. Some errors in other places due to DatabaseTypes not being correctly generated with null, we fixed those via typecasting for now.
Paired on this with RobertM (he did the navigating).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205704659159395) by [Unito](https://www.unito.io)

Fix Crossposting, 2023-10-11

---

packages/lesswrong/components/comments/CommentsItem/CommentBody.tsx
packages/lesswrong/lib/voting/namesAttachedReactions.tsx
packages/lesswrong/lib/voting/votingSystems.tsx

Fixes a crash of the `/moderation` page, introduced by my recent changes to inline-react highlighting.
(I'm confused how this one made it past the type-checker; `getCommentHighlights` is defined in `votingSystems.tsx` to take an optional `voteProps`, but then instantiated in `namesAttachedReactions.tsx` with that prop being required, which should be a mismatch.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205722316103083) by [Unito](https://www.unito.io)

Fix a null-reference crash in inline-reacts highlighting on /moderation

---

packages/lesswrong/server/repos/PostsRepo.ts

This PR is a subset of this more comprehensive PR, that just adds a LEFT JOIN which makes the dialogue list roughly work for now: 
other PR:
https://github.com/ForumMagnum/ForumMagnum/pull/8016/files
If someone pushes the other PR all the way through (looks like it involves migrations stuff I'm too tired to think about right now), this PR is unnecessary, but we could maybe merge it for now to get the list working.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205723041076211) by [Unito](https://www.unito.io)

Hotfix for dialogue list

---

packages/lesswrong/components/votes/lwReactions/InlineReactHoverableHighlight.tsx

Was using the wrong css style for the color of the dashed underline.  I think this is using the intended color (it's the one that's inside of the `dashed500` style); it does look less overwhelming/cluttered.
Wrong:
Fixed:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205724537725182) by [Unito](https://www.unito.io)

fix color of dashed underlines for inline reacts

---

packages/lesswrong/lib/voting/vote.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205732658622170) by [Unito](https://www.unito.io)

Fix crash when inline-reacting to an AF comment that you haven't otherwise voted on

---

packages/lesswrong/server/recommendations.ts

Fixes a bug where "Test crosspost" (a draft) was appearing in recommendations because it had `defaultRecommendation` set to true. I have also set that specific one to false in the meantime
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205731054101862) by [Unito](https://www.unito.io)

Hide draft default recommendations
