- packages/lesswrong/lib/editor/EditorFormComponent.jsx
Has a slightly bad "<br/>" because I wasn't sure how you wanted to handle padding of arbitrary components
> Activate editor is a slightly prettier button

- packages/lesswrong/lib/collections/posts/custom_fields.js
- packages/lesswrong/lib/component-replacements/LWPostsEditForm.jsx
- packages/lesswrong/lib/editor/EditorFormComponent.jsx
- packages/lesswrong/styles/_posts.scss
- EditTitle component (matches title formatting)
- EditUrl component (URL is hidden by default, button for linkposts)
- htmlBody is hidden except for admins
- Activate Editor only shows for legacy == true posts
> Prettier EditPost UI

- packages/lesswrong/lib/component-replacements/LWUsersProfile.jsx
This time it should be correct.
> Hide "Send message" button if logged out (#89)

- packages/lesswrong/components/comments/CommentsEditForm.jsx
- packages/lesswrong/components/comments/CommentsItem.jsx
- packages/lesswrong/components/common/DialogGroup.jsx
- packages/lesswrong/components/sunshineDashboard/ReportItem.jsx
- packages/lesswrong/components/sunshineDashboard/ReportsList.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineDashboard.jsx
- packages/lesswrong/lib/collections/reports/collection.js
- packages/lesswrong/lib/collections/reports/permissions.js
- packages/lesswrong/lib/collections/reports/schema.js
- packages/lesswrong/lib/collections/reports/views.js
- packages/lesswrong/lib/components.js
- packages/lesswrong/lib/modules/fragments.js
- packages/lesswrong/lib/routes.js
This is silly, but seems to be the best way to actually do the thing
> Revert 98 revert 97 reports

- packages/vulcan-accounts/imports/ui/components/Field.jsx
- packages/vulcan-accounts/imports/ui/components/LoginForm.jsx
Username or Email field now autofocuses when you click the login button.
> Made login form autofocus

- packages/lesswrong/components/users/UsersMenu.jsx
> New Post item in UsersMenu

- packages/vulcan-lib/lib/modules/validation.js
- packages/vulcan-lib/lib/server/mutations.js
- packages/vulcan-users/lib/server/on_create_user.js
My editor did some autolinting. The relevant line is `if (autoValue !== null) {`
Fixes a massive bug. Ultra-high priority.
> Fixed the bug (false !== null)

- packages/lesswrong/components/users/UsersProfile.jsx
Just a little QoL boost for the icon-confused.
> Give title tags to ambiguous icons on user page

- packages/lesswrong/styles/_comments.scss
- packages/lesswrong/styles/_posts.scss
Made vote buttons in lists black by default, active downvote icons red, active icons heavy, and when one is active the other fades out
> More prominent vote buttons

- packages/lesswrong/components/comments/CommentsItem.jsx
- packages/lesswrong/components/comments/CommentsNode.jsx
- packages/lesswrong/styles/_comments.scss
Resolves https://github.com/Discordius/Lesswrong2/issues/124 and issue #2 here: http://lesswrong.com/r/discussion/lw/pgp/feedback_on_lw_20/dxof
> Comment collapsing

- packages/lesswrong/lib/events/server.js
Removes a commented out line of code.
> Remove comment from server.js

- packages/example-forum/lib/server/posts/callbacks/other.js
- packages/lesswrong/lib/collections/posts/callbacks.js
Notes for testing:
* Creating a new post should increment the post count by 1
* Creating a new draft should not increment the post count
* Publishing a draft should increment the post count by 1
* Converting a published post to a draft should decrease the post count by 1
> Do not include drafts in user post count. fixes #488

- packages/lesswrong/components/messaging/InboxNavigation.jsx
Fix for issue #153 (which turned out to be mostly irrelevant, since it's pretty much impossible to get to that page without having notifications anymore, but I'd already done most of this)
> Notifications page no longer blank when no notifications

- README.md
- package.json
- packages/lesswrong/lib/collections/comments/tests.js
- packages/lesswrong/lib/collections/posts/tests.js
- packages/lesswrong/testing/utils.js
- packages/lesswrong/testing/voting.tests.js
Update readme with content from https://www.lesswrong.com/posts/gDYaJ5TEiEEj7SH66/lw-open-source-getting-started
> Update readme with content from LessWrong post

- packages/lesswrong/components/common/Home.jsx
> proper "or" operator instead of bitwise

- packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx
- packages/lesswrong/components/comments/recentDiscussionThread.jsx
- packages/lesswrong/components/posts/PostsCommentsThreadWrapper.jsx
Reverts LessWrong2/Lesswrong2#689
> Revert "Show-Parent-Comment for nested comments"

- packages/lesswrong/lib/modules/alignment-forum/callbacks.js
- packages/lesswrong/lib/modules/fragments.js
– can't self upvote
– client callbacks work correctly
> afVoting fixes

- packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx
- packages/lesswrong/components/comments/CommentsVote.jsx
- packages/lesswrong/components/comments/RecentCommentsItem.jsx
- packages/lesswrong/server/legacy-redirects/routes.js
- packages/lesswrong/server/scripts/debuggingScripts.js
> Slow comment rendering; and, fix broken inbound legacy post links that omit the slug

- packages/lesswrong/components/Layout.jsx
- packages/lesswrong/lib/events/server.js
Should not require any settings changes on the LW side, unless desired.
> Get intercom app id from settings

- packages/lesswrong/components/editor/CommentEditor.jsx
- packages/lesswrong/components/form-components/MuiTextField.jsx
- packages/lesswrong/lib/collections/users/custom_fields.js
Fix a couple spammy error messages in the browser console that were bothering me.
> Fix log spam

- packages/lesswrong/components/common/VoteButton.jsx
(Accidentally depends on the other PR, will fix. This one only makes a two-line change to VoteButton.jsx that's pretty obviously a bug fix)
> Fix mobile voting

- packages/lesswrong/components/common/CloudinaryImage.jsx
(Fixes logged-out user view of the front page).
> Cloudinary: Don't pass "auto" size when size omitted

- packages/lesswrong/components/localGroups/LocalGroupMarker.jsx
- packages/lesswrong/styles/_localgroups.scss
Fix double scrollbar and double 'X' in event map markers.
> Event map glitches

- packages/lesswrong/components/common/Home.jsx
- packages/lesswrong/components/posts/PostsPage.jsx
- packages/lesswrong/components/posts/PostsSingleSlug.jsx
- packages/lesswrong/components/sequences/BooksItem.jsx
- packages/lesswrong/components/sequences/ChaptersList.jsx
- packages/lesswrong/components/sequences/CollectionsNavigation.jsx
- packages/lesswrong/components/sequences/RecommendedReading.jsx
- packages/lesswrong/components/sequences/RecommendedReadingWrapper.jsx
- packages/lesswrong/components/sequences/SequencesGrid.jsx
- packages/lesswrong/components/sequences/SequencesHome.jsx
- packages/lesswrong/components/sequences/SequencesNavigation.jsx
- packages/lesswrong/components/sequences/SequencesNavigationLink.jsx
- packages/lesswrong/components/sequences/SequencesPage.jsx
- packages/lesswrong/lib/modules/utils/theme.js
- packages/lesswrong/styles/_posts.scss
- packages/lesswrong/styles/_sequences.scss
Fix some styling issues. Enable SSR in places. Refactor. Some SCSS->JSS.
> Sequences enhancements

- packages/lesswrong/components/editor/EditorFormComponent.jsx
- packages/lesswrong/server/scripts/brokenLinksReport.js
I broke the Draft-JS styling while fixing the Markdown styling. Oops.
> Fix editor styles, broken links report script v2

- README.md
Fixes #1085: The LW2 API is not documented
> Add mention of GraphiQL to README.md

- packages/lesswrong/server/legacy-redirects/routes.js
- packages/lesswrong/testing/voting.tests.js
As usual, this default is LW style, so no changes to y'all's settings file will be necessary.
> Add setting for flexible legacy redirects

- packages/lesswrong/components/search/SearchPagination.jsx
> Fix formatting glitches in search-result pagination widget

- packages/lesswrong/components/Layout.jsx
- packages/lesswrong/components/posts/EventsPast.jsx
- packages/lesswrong/components/posts/EventsUpcoming.jsx
- packages/lesswrong/components/posts/PostsDaily.jsx
Fixes some error messages appearing in the browser console. May also have fixed broken styling on the past/future events pages.
> Fix console errors

- packages/lesswrong/components/common/SearchBar.jsx
- packages/lesswrong/components/search/SearchBarResults.jsx
> Fix white-on-white text in AF search

- packages/lesswrong/components/comments/CommentsItem/CommentBody.jsx
- packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx
- packages/lesswrong/components/comments/CommentsNode.jsx
- packages/lesswrong/components/comments/RecentCommentsItem.jsx
- packages/lesswrong/components/common/FormatDate.jsx
- packages/lesswrong/components/questions/AnswerCommentsList.jsx
- packages/lesswrong/components/users/UsersNameDisplay.jsx
- packages/lesswrong/styles/_comments.scss
- packages/lesswrong/styles/main.scss
note: comes with the sort of css changes that are likely to fuck shit up if I don't doublecheck that they're reasonable.
> frontpage answer woes

- packages/lesswrong/components/sequences/CoreReading.jsx
Fixes a cosmetic problem with the hover effect of the big collections card on front page desktop.
> Fix sizing of BigCollectionsCard on front page desktop

- packages/lesswrong/styles/_editor.scss
fixes https://github.com/LessWrong2/Lesswrong2/issues/1284
> Slightly clearer LaTeX docs

- packages/lesswrong/components/posts/AlignmentCrosspostMessage.jsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.jsx
- packages/lesswrong/lib/components.js
> Alignmentforum Crosspost message

- packages/lesswrong/server/scripts/invites.js
Remove mention of beta from invite and password reset emails
> Remove mention of beta from invite and password reset emails

- package-lock.json
- packages/lesswrong/components/questions/NewQuestionDialog.jsx
- packages/lesswrong/components/sunshineDashboard/LastCuratedDate.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsList.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineListCount.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewCommentsList.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewPostsList.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersList.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineReportedContentList.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineSidebar.jsx
- packages/lesswrong/lib/collections/comments/fragments.js
- packages/lesswrong/lib/collections/posts/custom_fields.js
- packages/lesswrong/lib/collections/users/callbacks.js
- packages/lesswrong/lib/collections/users/custom_fields.js
- packages/lesswrong/lib/components.js
- packages/lesswrong/lib/modules/fragments.js
– if a Sunshine list has more than 10 things in it, it displays the number of items
– sunshines by default don't see the UnreviewedComments unless they turn on a setting
– sunshine curated section displays the last curated item
– fixes random bug with the question dialog related to the new revisions
> Sunshine List Improvements

- packages/lesswrong/components/comments/CommentsItem/CommentDeletedMetadata.jsx
- packages/lesswrong/components/questions/AnswerCommentsList.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewUserCommentsList.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewUserPostsList.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.jsx
- packages/lesswrong/lib/collections/comments/fragments.js
- packages/lesswrong/lib/collections/comments/views.js
- packages/lesswrong/lib/collections/posts/custom_fields.js
- packages/lesswrong/lib/collections/posts/views.js
> Sunshine Spam is visible

- packages/lesswrong/lib/collections/users/karmaChangesGraphQL.js
- packages/lesswrong/lib/collections/votes/views.js
- packages/lesswrong/lib/karmaChanges.js
> Karma-change notifier respects AF karma distinction

- packages/lesswrong/components/common/MetaInfo.jsx
- packages/lesswrong/components/sunshineDashboard/SidebarHoverOver.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineReportedItem.jsx
- packages/lesswrong/lib/collections/posts/views.js
- packages/lesswrong/lib/modules/fragments.js
- packages/lesswrong/themes/createThemeDefaults.js
> Fix various sunshineSidebar thingies

- packages/lesswrong/lib/collections/posts/fragments.js
> Add vote count to PostsBase fragment

- packages/lesswrong/components/sunshineDashboard/SunshineNewUserCommentsList.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewUserPostsList.jsx
- packages/lesswrong/lib/collections/posts/views.js
> Fix new users's new posts

- packages/lesswrong/components/posts/PostSubmit.jsx
- packages/lesswrong/components/posts/PostsEditForm.jsx
- packages/lesswrong/components/posts/PostsNewForm.jsx
- packages/lesswrong/components/questions/NewQuestionDialog.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.jsx
- packages/lesswrong/lib/collections/posts/fragments.js
- packages/lesswrong/lib/collections/posts/schema.js
- packages/lesswrong/lib/components.js
Users now have the option to uncheck a "moderators can promote" checkbox on their posts, which determines whether it can be promoted to frontpage.
> Submit to frontpage

- packages/lesswrong/components/editor/EditorFormComponent.jsx
- packages/lesswrong/server/editor/make_editable_callbacks.js
- packages/lesswrong/server/migrations/2019-02-06-fixBigPosts.js
> Fixing LaTeX to HTML rendering

- packages/lesswrong/components/alignment-forum/AFApplicationForm.jsx
> AF ApplicationForm can cancel

- packages/lesswrong/components/sunshineDashboard/SunshineListItem.jsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.jsx
> Tweak New User Info

- packages/lesswrong/components/posts/DeleteDraft.jsx
> DeleteDraft works on non-drafts

- packages/lesswrong/lib/collections/users/views.js
> New Users require 12 votes

- packages/lesswrong/lib/collections/posts/views.js
> Hide unreviewed user's posts from new posts list

- packages/lesswrong/lib/collections/comments/schema.js
- packages/lesswrong/lib/collections/posts/schema.js
- packages/lesswrong/lib/modules/callbacks.js
- packages/lesswrong/lib/modules/utils/schemaUtils.js
- packages/lesswrong/server/rss.js
(Additional information in commit messages.)
> Four assorted bugfixes, found via Sentry

- packages/lesswrong/lib/collections/posts/views.js
> Don't hide unreviewed users in drafts view

- packages/lesswrong/components/common/FormatDate.jsx
- packages/lesswrong/components/posts/PostsItem2.jsx
- packages/lesswrong/components/posts/PostsItemDate.jsx
- packages/lesswrong/lib/components.js
In PostsItem, if a post is curated, show the curation date instead of the post date, and when hovered show both dates.
Currently crashes. Putting this up as [WIP] while I switch to something more urgent.
> Show curated date

- packages/lesswrong/components/common/Home.jsx
- packages/lesswrong/components/search/SearchBarResults.jsx
Reverts LessWrong2/Lesswrong2#1878
> Revert "Add SunshineSidebar to Home.jsx, fix search results spacing on EA Forum"

- packages/lesswrong/components/async/EditorForm.jsx
- packages/lesswrong/components/async/editor-plugins/LinkButton/AddLinkForm.jsx
- packages/lesswrong/components/async/editor-plugins/LinkButton/index.js
- packages/lesswrong/components/async/editor-plugins/linkifyPlugin.js
- yarn.lock
This vendors two files from the draft-js-anchor-plugin that we already depended on
> Fixes a bunch of bugs related to linkify and stuff

- packages/lesswrong/components/comments/recentDiscussionThread.jsx
- packages/lesswrong/components/comments/recentDiscussionThreadsList.jsx
- packages/lesswrong/components/common/Header.jsx
- packages/lesswrong/lib/collections/posts/fragments.js
Some small optimizations suggested by looking at the log of queries generated by a logged-out front page view.
> Some minor optimizations of the front page's mongodb usages

- packages/lesswrong/components/common/TabNavigationMenu.jsx
My fixes for the Alignment forum caused a minor problem with the width of the community section item, this fixes that
> Fix width of community section item on mobile nav

- packages/lesswrong/components/common/CloudinaryImage.jsx
- packages/lesswrong/components/posts/PostsItem2.jsx
- packages/lesswrong/components/recommendations/RecommendationsList.jsx
- packages/lesswrong/components/sequences/BottomNavigationItem.jsx
- packages/lesswrong/lib/collections/collections/helpers.js
- packages/lesswrong/lib/collections/users/custom_fields.js
- packages/lesswrong/lib/modules/utils/toDictionary.js
- packages/lesswrong/server/partiallyReadSequences.js
- packages/lesswrong/server/recommendations.js
* Fix a vertical alignment problem when PostsItem2 is hovered
* Sequence images are SSRed
* Fix a crash in sequence bottom-nav when next/prev leads to a post with no sequence
* Continue-reading links use sequence URLs
* Include non-sequence collection/book posts in continue reading (untested)
> Polish and bugfixes relating to Continue Reading

- packages/lesswrong/components/users/UsersAccount.jsx
- packages/lesswrong/lib/collections/users/custom_fields.js
Also don't try to use google maps without the API key.
> Hide settings for fora that don't need them

- packages/lesswrong/components/posts/PostSubmit.jsx
- packages/lesswrong/components/posts/PostsEditForm.jsx
> Change published-post button label to "Move to drafts"

- packages/lesswrong/themes/createThemeDefaults.js
Fixes #1759. Thanks to @roryokane for investigating this (and apologies for how long it sat waiting in our issue tracker.)
> Fix misaligned first lines of code blocks

- packages/lesswrong/components/recommendations/ContinueReadingList.jsx
Fixes #2078. When the Continue Reading section has more entries in it than are shown (more than 3), adds a Show All link to show the rest.
> Show All link on continue reading list

- packages/lesswrong/server/recommendations.js
Fixes a bug (that never reached production) which caused not having any recommendations, which was introduced as an attempt to fix a bug where an empty database would crash rather than give an empty recommendation list. Test with: empty local database, dev database.
> Fix samplePosts function

- package-lock.json
- package.json
- packages/lesswrong/client/ga.js
- packages/lesswrong/components/Layout.jsx
- packages/lesswrong/components/comments/SingleLineComment.jsx
- packages/lesswrong/lib/registerSettings.js
- packages/lesswrong/server/recommendations.js
Based off of #2093 because I didn't pay attention. So merge after that one, I guess
> Fix single line comment deleted rendering

- packages/lesswrong/components/common/TabNavigationMenu.jsx
- packages/lesswrong/lib/routes.js
Fairly confident we'll want this (motivated partly by wanting to be able to include 'Shortform' as a minor menu item
> minorNavItems

- packages/lesswrong/components/comments/CommentsItem/CommentUserName.jsx
- packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx
- packages/lesswrong/components/comments/SingleLineComment.jsx
- packages/lesswrong/components/users/UserNameDeleted.jsx
- packages/lesswrong/lib/components.js
When a post/comment is by a deleted author, centralize handling of that in `UsersNameDeleted`. Change the text from [deleted] to [anonymous].
> Change [deleted] to [anonymous]

- packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx
- packages/lesswrong/components/comments/CommentsItem/CommentsItemDate.jsx
- packages/lesswrong/components/comments/RecentCommentsItem.jsx
- packages/lesswrong/lib/components.js
- packages/lesswrong/styles/_comments.scss
CommentsItem and RecentCommentsItem each had some fairly complicated handling for the date+permalink section, which looked like a copy-paste followed by divergence. Extract that bit into a shared component, and bring them into sync. Also removes some SCSS in the process.
> Clean up some copy-pasting between CommentsItem and RecentCommentsItem

- packages/lesswrong/components/posts/AllPostsPage.jsx
- packages/lesswrong/components/posts/EventsPast.jsx
- packages/lesswrong/components/posts/EventsUpcoming.jsx
- packages/lesswrong/components/posts/PostsDailyList.jsx
- packages/lesswrong/lib/registerSettings.js
This was copy-pasted in a somewhat shocking number of places. Not dealing with that particular piece of technical debt right now.
> Daily view: Change default from 5 days to 10

- packages/lesswrong/components/common/LoadMore.jsx
- packages/lesswrong/components/common/queryStatusUtils.js
- packages/lesswrong/components/posts/EventsUpcoming.jsx
- packages/lesswrong/components/posts/PostsDailyList.jsx
- packages/lesswrong/components/posts/PostsDay.jsx
- packages/lesswrong/components/posts/PostsListSettings.jsx
- packages/lesswrong/components/shortform/ShortformTimeBlock.jsx
Fixes bug introduced in #2160 where switching settings in PostsListSettings no longer caused PostsDailyList to dim. Adds loading indicator to LoadMore.
> Better loading behavior for allPosts timeframes

- packages/lesswrong/lib/collections/posts/views.js
Presumably this requires migrations stuff to happen which I'm still a bit confused about
> hideShortformPosts

- packages/vulcan-accounts/imports/ui/components/Field.jsx
- packages/vulcan-accounts/imports/ui/components/LoginFormInner.jsx
This was caused by merging the Vulcan repo into the LW repo with one PR not synced from github.
> Re-merge vulcan-accounts custom fields

- packages/lesswrong/components/posts/PostsPage/PostsPageWrapper.jsx
- packages/lesswrong/lib/collections/posts/fragments.js
- packages/lesswrong/lib/components.js
- packages/lesswrong/lib/modules/fragments.js
- packages/vulcan-admin/lib/modules/fragments.js
- packages/vulcan-core/lib/client/start.jsx
- packages/vulcan-forms/test/components.test.js
- packages/vulcan-lib/lib/modules/fragments.js
- packages/vulcan-lib/lib/server/apollo-server/apollo_server.js
- packages/vulcan-users/lib/modules/fragments.js
Fix a fragment issue that made the sequence navigation not appear on sequences pages when addressed by their slug routes.
> Slug sequence navigation fix

- packages/lesswrong/components/comments/CommentsItem/RetractCommentMenuItem.jsx
- packages/vulcan-core/lib/modules/containers/withUpdate.js
- packages/vulcan-core/lib/modules/index.js
Continuing the HoCs-to-hooks conversion.
> Add `useUpdate`, use it in one test case

- packages/lesswrong/components/icons/SettingsIcon.jsx
- packages/lesswrong/components/recommendations/RecommendationsAlgorithmPicker.jsx
- packages/lesswrong/components/recommendations/RecommendationsAndCurated.jsx
Provides tooltips, and labels things in a way I think is more intuitive
> Slightly less confusing recommendations settings

- packages/lesswrong/components/comments/SingleLineComment.jsx
- packages/lesswrong/components/votes/CommentsVote.jsx
- packages/lesswrong/lib/collections/comments/helpers.js
creates a "Comments.getKarma" helper that should (henceforth) be used when displaying comment karma on the front end
> fix singleLine Alignment karma

- packages/lesswrong/components/posts/PostsTimeframeList.jsx
- packages/lesswrong/lib/collections/posts/parameters.js
Clean up some Vulcan spaghetti that caused day-boundaries to be wrong and the most recent posts to be missing from All Posts.
> Clean up Vulcan's timezone handling mess

- packages/lesswrong/components/editor/EditorFormComponent.jsx
The previous custom writing prompt accidentally broke regular commenting (as opposed to shortform commenting). Fixes that.
(Also fixes a few UI bugs)
> fix editorHIntTextBug

- packages/lesswrong/components/common/ContentItemBody.jsx
- packages/lesswrong/components/editor/EditorFormComponent.jsx
- packages/lesswrong/components/linkPreview/HoverPreviewLink.jsx
Fixes
– marginal improvement in our ratio of "actual good code comments" and "commenting countersignalling"
– element.innerHtml did weird things with special characters
– try/catch for HoverLinkPreview
> Various master bug fixes

- packages/lesswrong/components/common/Home2.jsx
- packages/lesswrong/components/localGroups/CommunityMap.jsx
- packages/lesswrong/lib/collections/posts/views.js
- packages/lesswrong/lib/collections/users/custom_fields.js
- packages/lesswrong/lib/modules/fragments.js
Basically ready, but not confident we actually want to do this
> Add map to frontpage and fix small filter bug

- packages/lesswrong/components/posts/PostsItem2.jsx
- packages/lesswrong/components/posts/PostsPreviewTooltip.jsx
- packages/lesswrong/components/posts/PostsTitle.jsx
Not sure this is the best way to fix the broken "PostsItem title expand", but seems to work slightly better on average.
> replace hover-title with tooltip-title

- packages/lesswrong/components/linkPreview/PostLinkPreview.jsx
- packages/lesswrong/lib/components.js
- packages/lesswrong/lib/routes.js
Adds a route for handling greaterwrong commenturls
> greaterwrong hover preview comments

- packages/lesswrong/components/linkPreview/HoverPreviewLink.jsx
> Don't use `Link` tags for relative links

- packages/lesswrong/components/common/LWPopper.jsx
- packages/lesswrong/components/users/UsersMenu.jsx
Cleaning up some confusing elements, adding icons, and adding a link to shortform page if it exists for that user
> Rework UserProfile menu

- packages/lesswrong/components/posts/PostsPage/PostsTopSequencesNav.jsx
Fixes this issue:
https://files.slack.com/files-pri/T3ERD8FQT-FP96CP32L/image__2_.png
> cleanup mobile sequence nav

- packages/lesswrong/server/logging.js
- packages/vulcan-lib/lib/server/apollo-server/apollo_server.js
> Remove timber cruft

- packages/lesswrong/components/editor/EditorFormComponent.jsx
ckEditor is broken enough that I don't feel comfortable even giving it to beta users. Hopefully will return to live-beta after a day or two of testing and bug-fixes.
> Admin-Gate ckEditor

- packages/lesswrong/lib/collections/notifications/views.js
(temporary fix for lack-of-af-notifications until we develop a better system)
> enable all notifications on Alignment Forum

- packages/lesswrong/server/emailComponents/EmailWrapper.jsx
- packages/lesswrong/server/emails/renderEmail.js
> Devel version of revert recent email theme changes

- packages/lesswrong/components/posts/PostsPage/PostsTopSequencesNav.jsx
Spacing was slightly off, this makes it a bit better
> Fix spacing for top sequences nav

- packages/lesswrong/components/notifications/NotificationEmailPreviewPage.jsx
- packages/lesswrong/server/emails/renderEmail.js
- packages/lesswrong/server/notificationBatching.js
Adapt NotificationEmailPreviewPage to, if given a postId in the query, show the email that would result from its curation.
> Add ability to preview curation emails

- packages/lesswrong/components/posts/AllPostsPage.jsx
- packages/lesswrong/components/posts/PostsTimeBlock.jsx
- packages/lesswrong/components/posts/PostsTimeframeList.jsx
This branch makes it so if you click on a timeframe-title on the allPosts page, it'll take you to a url that shows _only_ that particular timeframe, with a limit of 100 posts (i.e. to quickly see all posts in 2018)
> Timeblock Page

- packages/lesswrong/components/common/SectionTitle.jsx
- packages/lesswrong/components/posts/PostsPage/PostsPageTitle.jsx
- packages/lesswrong/themes/eaTheme.js
The margin-top in PostsPageTitle-question Ray and I both couldn't figure out why it was there, so, defying Chesterton's Fence, we removed it.
> Small spacing tweaks to make the Forum look nicer

- packages/lesswrong/components/recommendations/Recommendations2018Review.jsx
- packages/lesswrong/components/recommendations/RecommendationsAlgorithmPicker.jsx
Replaces "show 'From the Archives'" with "show 2018 review"
> hide 2018 Review on frontpage

- packages/lesswrong/server/notificationCallbacks.js
> Stagger curation emails (email admins immediately, everyone else after 20min)

- packages/lesswrong/components/posts/Nominations2018.jsx
- packages/lesswrong/server/recommendations.js
Minor tweaks to what gets shown in the frontpage and /nominations review sections
> Update review filtering

- packages/lesswrong/components/recommendations/Recommendations2018Review.jsx
Users with 1000 karma get a prompt to nominate posts on the frontpage
> review call-to-action

- packages/lesswrong/components/posts/AlignmentCrosspostMessage.jsx
- packages/lesswrong/components/posts/LinkPostMessage.jsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.jsx
- packages/lesswrong/components/posts/PostsPage/PostsRevisionMessage.jsx
- packages/lesswrong/themes/createThemeDefaults.js
Refactoring some styles into the typography object (in preparation for adding a new one for the Review Phase)
> refactor contentNotice typography

- packages/lesswrong/components/common/FlashMessages.jsx
- packages/lesswrong/components/common/withMessages.js
- packages/vulcan-core/lib/modules/components/App.jsx
withMessages was using an invalid import path, this fixes it. Also fixes an open bug where post edit forms where failing to navigate away after form submit.
> Fix withMessages bugs

- packages/lesswrong/components/posts/PostsPage/PostActions.jsx
Pretty simple PR we should be able to merge at midnight without much risk.
(the Review Phase PR also includes this change, which we can merge into devel and then master on Monday after more reflection)
> remove nomination button [hotfix]

- packages/lesswrong/server/editor/make_editable_callbacks.js
Today we observed a weird failure, where submitting posts/comments using CkEditor or markdown (but not draftjs) failed with a timeout in the graphql request. This problem didn't replicate on lessestwrong or local installs, didn't peg the CPU before timing out, and went away on server restart.
One theory of what happened is that `mathjax-node-page` is actually preserving some state between calls (it shouldn't be), and that there is some bad LaTeX input which causes all subsequent invocations of mjpage to silently fail. This hotfix adds a ten-second timer around `mjpage`, and if it ever times out, records it in Sentry and captures the HTML that it was running on, to confirm the theory and give us a test case.
> [Hotfix] Add instrumentation to detect if mjpage times out

- packages/lesswrong/components/review/FrontpageReviewPhase.jsx
- packages/lesswrong/server/recommendations.js
Makes it so demon threads won't take over the frontpage review section
> Frontpage Review Random Sampling

- packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx
- packages/lesswrong/components/comments/RecentComments.jsx
- packages/lesswrong/components/comments/RecentDiscussionThread.jsx
- packages/lesswrong/components/comments/SingleLineComment.jsx
- packages/lesswrong/components/common/SectionTitle.jsx
- packages/lesswrong/components/form-components/SectionFooterCheckbox.jsx
- packages/lesswrong/components/posts/PostsList2.jsx
- packages/lesswrong/components/review/ReviewPostForm.jsx
- packages/lesswrong/components/review/Reviews2018.jsx
- packages/lesswrong/lib/collections/comments/views.js
- packages/lesswrong/lib/collections/posts/views.js
- packages/lesswrong/styles/_comments.scss
Updates Reviews Page with:
– sorting
– default sorts by fewest reviews (note: if "expand new comments" is checked, new comments will still be sorted to top
– adds a "nominations" section (a list of all nomination comments, sorted by karma)
– adds a "reviews" section (all review comments, sorted by karma)
> Review Page UI

- packages/lesswrong/components/posts/PostsItem2.tsx
- packages/lesswrong/components/posts/PostsTitle.jsx
– slightly updates the "read" opacity for all users
– switches the admin experimental bold to a different experimental bold
> Different bold

- packages/lesswrong/components/editor/EditorFormComponent.jsx
- packages/lesswrong/components/editor/SelectVersion.jsx
Explains what the hell is going on and why
> Comment on select version

- packages/lesswrong/components/posts/PostsTitle.jsx
Since people have been complaining a lot about the previous bold update, tweaking the "second experiment" to err a bit more on the side of "not noticeable enough" rather than "nope, still too bold".
(Not sure this is the right call, can check in with peeps on Monday about the options before merging)
> bold update

- packages/lesswrong/components/posts/PostsTitle.jsx
> Bold update [hotfix]

- packages/lesswrong/components/review/FrontpageReviewPhase.jsx
Samples the 2018 review randomly instead of from high karma
> Fix review sampling hotfix

- packages/lesswrong/lib/betas.js
Alas. I still think it's great (modulo resolution issues on some monitors). But if everyone hates it seems like it's time to go.
(note: this leaves in the infrastructure for now because it's kinda a pain to set up and take down)
> Remove bold experiment

- packages/lesswrong/components/posts/PostsPage/PostsRevisionMessage.jsx
Changes the wording to be less unclear.
> Improve link to latest Revision

- package.json
- yarn.lock
Fixes a weird DOM mismatch with a div in p tag
> Pin material UI again

- packages/lesswrong/components/review/ReviewPostButton.jsx
A nested 'a' tag was throwing an error
> fix 'a within a' tag

- packages/lesswrong/components/common/HomeLatestPosts.jsx
(recreated this PR because it had accumulated a high number of merge conflicts for a PR that only changed one line)
> increase frontpage post count

- .gitignore
- .meteorignore
- scripts/benchmarkIncrementalStart.sh
- scripts/benchmarkServerStart.sh
- scripts/benchmarkUnitTests.sh
- scripts/clean.sh
- scripts/measureBundleSize.sh
Adds a set of scripts for benchmarking bundle size, unit tests, cold server startup, and incremental update.
> Add benchmarking scripts

- packages/lesswrong/components/common/HomeLatestPosts.jsx
Ben suggested "12", and I wanted to check how 13 felt first.
> 13 posts on frontpage

- packages/lesswrong/components/review/ReviewPostButton.jsx
- packages/lesswrong/components/users/ReviewVotingPage.tsx
I accidentally broke the regular right-column positioning while fixing Daniel Filan's issue. This repairs that, and also adds a "write a review" button, which I think had been missing.
> Review button, + fix right column

- packages/lesswrong/components/comments/CommentsList.jsx
- packages/lesswrong/components/review/PostReviewsAndNominations.jsx
- packages/lesswrong/components/users/ReviewVotingPage.tsx
Rearranges the voting post metadata so that reviews are more prominent
> Partial expanded reviews

- .travis.yml
> Update travis node version

- packages/lesswrong/components/tagging/TagPage.jsx
- packages/lesswrong/components/tagging/TagPageTitle.jsx
- packages/lesswrong/lib/collections/tagRels/collection.js
- packages/lesswrong/lib/collections/tagRels/views.js
- packages/lesswrong/lib/collections/tags/collection.js
- packages/lesswrong/lib/routes.js
- packages/lesswrong/server/tagging/tagCallbacks.js
* Fully implement tag-deleting, expose it to the UI, and fix buggy callbacks
* Tag slug updates properly when tags are renamed
* Add subtitle link from tag pages to tags list
* Fix relevant-sorting on tag pages
* Better loading-state display on tag pages
> Various bits of tagging polish

- packages/lesswrong/components/users/UsersMenu.jsx
Also removes "[beta]" flag from shortform button
> newSequences for 1000+ karma

- packages/lesswrong/components/review/FrontpageVotingPhase.jsx
corresponding to:
https://github.com/LessWrong2/Lesswrong2/pull/2845
(note, that one accidentally introduced two extra spaces, which I'm submitting another small PR to fix)
> Update cta hotfix

- packages/ddp-server/.npm/package/.gitignore
- packages/ddp-server/.npm/package/README
- packages/ddp-server/.npm/package/npm-shrinkwrap.json
- packages/ddp-server/README.md
- packages/ddp-server/crossbar.js
- packages/ddp-server/crossbar_tests.js
- packages/ddp-server/livedata_server.js
- packages/ddp-server/livedata_server_tests.js
- packages/ddp-server/package.js
- packages/ddp-server/server_convenience.js
- packages/ddp-server/session_view_tests.js
- packages/ddp-server/stream_server.js
- packages/ddp-server/writefence.js
See https://github.com/meteor/meteor/issues/10468
> Hopefully fix crash in `ddp-server/stream_server`

- packages/lesswrong/server/callbacks/votingCallbacks.ts
(note: the migration for snooze hasn't been run)
> fix voting new-user-review callback

- packages/lesswrong/components/common/SectionSubtitle.jsx
- packages/lesswrong/components/posts/PostsTimeBlock.jsx
- packages/lesswrong/components/recommendations/RecommendationsAndCurated.jsx
- packages/lesswrong/components/review/FrontpageNominationPhase.jsx
- packages/lesswrong/components/review/FrontpageReviewPhase.jsx
- packages/lesswrong/components/review/FrontpageVotingPhase.jsx
> Remove left-margins from Recommendations

- packages/lesswrong/components/admin/migrations/MigrationsDashboard.tsx
- packages/lesswrong/components/admin/migrations/MigrationsDashboardRow.tsx
- packages/lesswrong/server/migrations/migrationsDashboardGraphql.js
Also some quality of life css improvements
> Add column for the last run date of a migration

- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
- packages/lesswrong/components/sequences/CoreReading.jsx
https://app.intercom.io/a/apps/wtb8z7sj/inbox/inbox/all/conversations/25677994622
> Clarify HPMOR text

- packages/lesswrong/lib/registerSettings.js
- packages/lesswrong/lib/scoring.ts
- packages/lesswrong/server/updateScores.js
The EA Forum would like to slow down the homepage a bit. We'll experiment with changing the time decay factor, which should be a setting anyway.
> Add time decay setting

- packages/lesswrong/components/shortform/ShortformTimeBlock.jsx
It was slightly off, now it is nicer
> fix shortform padding for allPosts

- packages/lesswrong/components/common/Header.tsx
- packages/lesswrong/components/common/HomeLatestPosts.tsx
- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
- packages/lesswrong/components/ea-forum/EAHomeHandbook.tsx
- packages/lesswrong/components/ea-forum/SiteLogo.tsx
- packages/lesswrong/components/form-components/MultiSelectButtons.tsx
- packages/lesswrong/components/posts/PostsPage/PostsTopSequencesNav.tsx
- packages/lesswrong/lib/components.ts
- packages/lesswrong/themes/eaTheme.ts
Two are LW-relevant. I added the missing type registration to EAHomeHandbook. And I fixed an alignment issue on LW PostsTopSequencesNav that I had caused by switching Times to Warnock Pro.
> Smalls done around merging

- packages/lesswrong/lib/collections/posts/custom_fields.ts
- packages/lesswrong/lib/collections/sequences/schema.ts
- packages/lesswrong/lib/collections/users/custom_fields.ts
Apparently admins that weren't sunshines couldn't access some things
> fix admin-accessible fields

- packages/lesswrong/components/common/TabNavigationMenu/TabNavigationMenu.tsx
- packages/lesswrong/components/common/TabNavigationMenu/TabNavigationSubItem.tsx
- packages/lesswrong/components/localGroups/EventTime.tsx
- packages/lesswrong/components/localGroups/TabNavigationEventsList.tsx
- packages/lesswrong/components/posts/PostsItemDate.tsx
- packages/lesswrong/themes/createThemeDefaults.ts
> Event times

- packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx
- packages/lesswrong/components/tagging/FooterTagList.tsx
Note: this correctly updates tags, but currently doesn't refresh the tag-list in the sunshine sidebar to show them properly after you add one.
> Add tagging to sunshines

- packages/lesswrong/components/posts/PostsPreviewTooltip.tsx
- packages/lesswrong/components/tagging/TagHoverPreview.tsx
- packages/lesswrong/components/tagging/TagPage.tsx
- packages/lesswrong/components/tagging/TagPreview.tsx
- packages/lesswrong/components/tagging/TagRelCard.tsx
> Fix tag hover over

- packages/lesswrong/components/questions/NewRelatedQuestionForm.tsx
- packages/lesswrong/lib/collections/users/custom_fields.ts
- packages/lesswrong/themes/eaTheme.ts
- tsconfig.json
Only LW-relevant one is changing text in notification settings, which I made after a user mentioned they were confused what "subscribed posts" meant.
> Smalls improvements built up since last merge

- packages/lesswrong/components/tagging/TagPage.tsx
Remove the "there are no posts with this tag" message
> loading tag posts

- packages/lesswrong/components/posts/SpreadsheetPage.tsx
> Update Link DB styles

- packages/lesswrong/components/common/HomeLatestPosts.tsx
Adds in the captureEvent required to track who's clicking the tag filter settings icon
> Add tracking to tag filter settings

- packages/lesswrong/components/common/HomeLatestPosts.tsx
- packages/lesswrong/components/tagging/FilterMode.tsx
- packages/lesswrong/components/tagging/TagFilterSettings.tsx
- packages/lesswrong/lib/filterSettings.ts
> improve tag-filter tooltips

- packages/lesswrong/components/common/SeparatorBullet.tsx
- packages/lesswrong/components/common/SubscribeWidget.tsx
- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
Made this last night, not sure if it's an improvement but I like it slightly more:
– button somewhat greener (custom green designed to match the feel of the "unread comments" green)
– moved curated buttons more to the left
> Frontpage Widget Tweaks

- packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx
> improve new sunshine ui

- packages/lesswrong/server/callbacks/rateLimits.ts
> Fix broken unit tests caused by a validation function with the wrong return type

- packages/lesswrong/components/tagging/AddTagButton.tsx
- packages/lesswrong/components/tagging/FooterTagList.tsx
- packages/lesswrong/components/tagging/TagFilterSettings.tsx
- packages/lesswrong/lib/betas.ts
- packages/lesswrong/lib/collections/tagRels/collection.ts
- packages/lesswrong/lib/collections/tags/collection.ts
Based off https://github.com/LessWrong2/Lesswrong2/pull/3027 (soft filters), which is required because it's where the `suggestedAsFilter` field (for promoted tags) comes from.
> Ungate tags

- packages/lesswrong/components/posts/PostsList2.tsx
25 seemed around the sweet spot, after playing around a bit.
> Reduce loadMore to 25

- packages/lesswrong/components/seasonal/CoronavirusFrontpageWidget.tsx
- packages/lesswrong/lib/collections/posts/views.ts
- packages/lesswrong/server/recommendations.ts
[known issue: this seems to be sampling heavily from the top-karma posts, despite what I *thought* was the correct inputs to avoid that problem.]
> Sampled Frontpage Coronavirus Questions

- packages/lesswrong/components/posts/PostsPage/PostActions.tsx
- packages/lesswrong/components/tagging/EditTagsDialog.tsx
- packages/lesswrong/components/tagging/FooterTag.tsx
- packages/lesswrong/lib/components.ts
Adds a menu item and modal-dialog for post tags.
> Edit Tags menu item

- packages/lesswrong/components/posts/PostsListSortDropdown.tsx
- packages/lesswrong/components/tagging/TagPage.tsx
- packages/lesswrong/components/tagging/TagPreview.tsx
- packages/lesswrong/components/tagging/TagRelCard.tsx
- packages/lesswrong/lib/editor/ellipsize.tsx
> Tag hoverover truncation + Tag Page typography update

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
> AnalyticsTracking for Tagging #1

- packages/lesswrong/components/tagging/TagPage.tsx
1) capture sorting + num posts, 2) capture Read More click of wiki 3) better section context capturing 4) Rename Continue Reading to Read More
> Analytics Tracking  for Tagging 2

- packages/lesswrong/components/tagging/AllTagsPage.tsx
- packages/lesswrong/components/tagging/TagsListItem.tsx
- packages/lesswrong/lib/components.ts
This adds a hoverover to the AllTagsPage, and very slightly increases the padding of TagsListItems.
There may be more stuff we want here but this seemed like an obvious first step.
> AllTagsPage Small Rework

- packages/lesswrong/components/posts/TableOfContents/TableOfContentsList.tsx
Makes it so when you click on a table-of-contents item, it updates the url (making it easier to send links to specific sections of a post)
> table of contents update hash

- packages/lesswrong/components/tagging/FilterMode.tsx
Changes "-/+ infinity" to "Hidden" and "Required", makes them a little greenish, and also changes the "X" to a "Remove Filter" since it was confusing for some users.
> Filter Mode UI updates

- packages/lesswrong/components/search/SearchBarResults.tsx
- packages/lesswrong/components/search/SearchPage.tsx
- packages/lesswrong/components/search/TagsSearchHit.tsx
- packages/lesswrong/components/search/UsersSearchHit.tsx
- packages/lesswrong/lib/collections/tags/collection.ts
- packages/lesswrong/lib/collections/tags/helpers.ts
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/index.ts
- packages/lesswrong/server/search/utils.ts
> search tags

- packages/lesswrong/components/tagging/AddTag.tsx
- packages/lesswrong/components/tagging/AllTagsPage.tsx
- packages/lesswrong/components/tagging/TagPreview.tsx
- packages/lesswrong/components/tagging/TagSearchHit.tsx
- packages/lesswrong/components/tagging/TagsListItem.tsx
- packages/lesswrong/lib/collections/tags/collection.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/server/search/utils.ts
Creates a "view all tags" link in the "+ Add Tag menu", and then tried to clean up /tags/all slightly so it was less bad for users to see it.
> Add tag link

- packages/lesswrong/lib/alignment-forum/graphql.ts
- packages/lesswrong/lib/collections/chapters/permissions.ts
- packages/lesswrong/lib/collections/posts/custom_fields.ts
- packages/lesswrong/lib/collections/posts/schema.ts
- packages/lesswrong/lib/collections/users/collection.ts
- packages/lesswrong/lib/collections/users/custom_fields.ts
- packages/lesswrong/lib/i18n-en-us/en_US.ts
- packages/lesswrong/lib/make_voteable.ts
- packages/lesswrong/lib/types/collectionTypes.d.ts
- packages/lesswrong/lib/utils/schemaUtils.ts
- packages/lesswrong/server/resolvers/commentResolvers.ts
- packages/lesswrong/server/resolvers/diffResolvers.ts
- packages/lesswrong/server/rss.ts
- yarn.lock
Fix a bunch of cases where we used `Users.restrictViewableFields` instead of `accessFilterSingle` or `accessFilterMultiple`
> Fix access filters

- packages/lesswrong/components/common/HomeLatestPosts.tsx
- packages/lesswrong/components/tagging/AddTagButton.tsx
- packages/lesswrong/components/tagging/FilterMode.tsx
- packages/lesswrong/components/tagging/TagFilterSettings.tsx
> tag filter show/hide

- packages/lesswrong/styles/main.scss
> Intercom hiding hotfix

- packages/lesswrong/components/common/TabNavigationMenu/TabNavigationFooterItem.tsx
> Adjust padding on bottom nav-button to avoid linebreak

- packages/lesswrong/lib/types/collectionTypes.d.ts
- packages/lesswrong/server/tableOfContents.ts
> Fix ToC comment-count including hidden comments

- packages/lesswrong/components/common/withRecordPostView.tsx
- packages/lesswrong/components/posts/PostsPage/PostActions.tsx
- packages/lesswrong/server/tableOfContents.ts
> Mark as read/unread menu item checks/updates the client-side read-status cache

- packages/lesswrong/components/common/HomeLatestPosts.tsx
- packages/lesswrong/components/common/SectionTitle.tsx
- packages/lesswrong/components/recommendations/ContinueReadingList.tsx
- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
- packages/lesswrong/components/recommendations/RecommendationsList.tsx
- packages/lesswrong/components/review/FrontpageNominationPhase.tsx
- packages/lesswrong/components/review/FrontpageReviewPhase.tsx
- packages/lesswrong/components/review/FrontpageVotingPhase.tsx
- packages/lesswrong/components/seasonal/CoronavirusFrontpageWidget.tsx
- packages/lesswrong/components/sequences/BooksItem.tsx
- packages/lesswrong/components/sequences/SequencesGrid.tsx
- packages/lesswrong/components/sequences/SequencesGridItem.tsx
- packages/lesswrong/components/sequences/SequencesGridWrapper.tsx
- packages/lesswrong/components/tagging/TagFilterSettings.tsx
Reverts LessWrong2/Lesswrong2#3135
> Revert "Frontage Recommendations Rework"

- packages/lesswrong/components/common/HomeLatestPosts.tsx
- packages/lesswrong/components/common/SectionTitle.tsx
- packages/lesswrong/components/recommendations/ContinueReadingList.tsx
- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
- packages/lesswrong/components/recommendations/RecommendationsList.tsx
- packages/lesswrong/components/review/FrontpageNominationPhase.tsx
- packages/lesswrong/components/review/FrontpageReviewPhase.tsx
- packages/lesswrong/components/review/FrontpageVotingPhase.tsx
- packages/lesswrong/components/seasonal/CoronavirusFrontpageWidget.tsx
- packages/lesswrong/components/sequences/BooksItem.tsx
- packages/lesswrong/components/sequences/SequencesGrid.tsx
- packages/lesswrong/components/sequences/SequencesGridItem.tsx
- packages/lesswrong/components/sequences/SequencesGridWrapper.tsx
- packages/lesswrong/components/tagging/TagFilterSettings.tsx
Reverts LessWrong2/Lesswrong2#3201
> Revert "Revert "Frontage Recommendations Rework""

- packages/lesswrong/server/tableOfContents.ts
┆Issue is synchronized with this [Trello card](https://trello.com/c/EKyLp8mL) by [Unito](https://www.unito.io/learn-more)
> Add null check to cheerio handling

- packages/lesswrong/components/tagging/FilterMode.tsx
- packages/lesswrong/lib/routes.ts
(After deploy, really.)
* The filter for strong weight was displayed as 30, but updated as 25. Make it consistent.
* The /tags post is LW-AF specific. On the EA Forum, make it redirect to /tags/all for now.
┆Issue is synchronized with this [Trello card](https://trello.com/c/W0YKVH3f) by [Unito](https://www.unito.io/learn-more)
> Fixes discovered during merge

- packages/lesswrong/lib/instanceSettings.ts
- packages/lesswrong/lib/publicSettings.ts
- packages/lesswrong/server/databaseSettings.ts
┆Issue is synchronized with this [Trello card](https://trello.com/c/rTzgxlOw) by [Unito](https://www.unito.io/learn-more)
> Document setting types

- packages/lesswrong/components/posts/PostsPage/PostActions.tsx
┆Issue is synchronized with this [Trello card](https://trello.com/c/88NCaYus) by [Unito](https://www.unito.io/learn-more)
> Move to Personal Blog doesn't remove curatedDate

- deploy.sh
This should allow us to deploy again.
> Pin mup in `deploy.sh`(and hopefully fix deploying)

- packages/lesswrong/themes/stylePiping.ts
Example of a post with a styling problem: https://www.lesswrong.com/s/EBuZhwCrYuJGp7ax4/p/jn8256ajXff6KuNPu
> Fix weird-looking horizontal rules in HPMOR sequence

- packages/lesswrong/components/common/HeadTags.tsx
Fix a crash on 404 pages, introduced by me in https://github.com/LessWrong2/Lesswrong2/pull/3247 (not yet on production).
> Fix crash on 404 page

- packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx
- packages/lesswrong/components/tagging/CoreTagsChecklist.tsx
> Tweak new post core tags ui

- packages/lesswrong/components/tagging/FooterTag.tsx
> Experimental tag styles to see what happens

- packages/lesswrong/components/comments/RecentDiscussionThread.tsx
- packages/lesswrong/components/common/withRecordPostView.tsx
- packages/lesswrong/components/posts/PostsItem2.tsx
Broken on devel when I merged https://github.com/LessWrong2/Lesswrong2/pull/3272 . Caused by incorrectly routing the `post` argument. I think something happened like <refactor> <test> <refactor more> <go away and come back> <yep, I remember testing this>.
> Fix read-status

- packages/lesswrong/lib/betas.ts
Ungates wiki editing, tag management and tag revisions.
> Ungate Wiki Editing

- packages/lesswrong/components/tagging/TagsListItem.tsx
Pairs with hotfix PR: https://github.com/LessWrong2/Lesswrong2/pull/3312
> Remove reviewed by user (paired with another hotfix)

- packages/lesswrong/components/search/SearchPage.tsx
Removes a strip of gray on small screens
> fix grey artifact on search page

- packages/lesswrong/components/comments/CommentsNewForm.tsx
Previous loading state implementation was hacky, this one is slightly less hacky
> Less dumb implementation of the Comments submission loading

- packages/lesswrong/components/posts/PostsPage/PostActions.tsx
- packages/lesswrong/components/spuriousChange.ts
- packages/lesswrong/components/tagging/AllTagsPage.tsx
- packages/lesswrong/components/tagging/TagHoverPreview.tsx
- packages/lesswrong/themes/stylePiping.ts
- yarn.lock
Supercedes #3328.
Adds post count to items, includes some styling fixes, and replaced tag name with current name.
> All Tags Portal Plus

- package.json
- yarn.lock
Fixes a node-version incompatibility that broke yarn install for me.
> Update bcrypt package

- packages/lesswrong/lib/collectionUtils.ts
- packages/lesswrong/lib/collections/posts/custom_fields.ts
- packages/lesswrong/lib/collections/sequences/schema.ts
- packages/lesswrong/lib/collections/users/custom_fields.ts
- packages/lesswrong/lib/collections/users/karmaChangesGraphQL.ts
- packages/lesswrong/lib/collections/users/schema.ts
- packages/lesswrong/lib/editor/make_editable.tsx
- packages/lesswrong/lib/make_voteable.ts
- packages/lesswrong/lib/types/collectionTypes.d.ts
- packages/lesswrong/lib/utils/schemaUtils.ts
- packages/lesswrong/server/resolvers/karmaChangeResolvers.ts
Enforces basic typing over schema/custom_fields files.
> Typescript-annotate collection metadata

- packages/lesswrong/lib/collections/users/collection.ts
- packages/lesswrong/lib/vulcan-lib/collections.ts
- packages/lesswrong/lib/vulcan-lib/utils.ts
- packages/lesswrong/lib/vulcan-users/permissions.ts
- packages/lesswrong/server/callbacks.ts
- packages/lesswrong/server/vulcan-lib/apollo-server/apollo_server.ts
- packages/lesswrong/server/vulcan-lib/findbyids.ts
- packages/lesswrong/server/vulcan-users/graphql_context.ts
- packages/lesswrong/server/vulcan-users/main.ts
Optimize and refactor some miscellaneous small things (on the order of 200ms) that showed up in SSR profiling.
> Misc optimizations

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/comments/RecentDiscussionThread.tsx
- packages/lesswrong/components/localGroups/CommunityMap.tsx
- packages/lesswrong/components/localGroups/LocalGroupsList.tsx
- packages/lesswrong/components/posts/PostsList2.tsx
- packages/lesswrong/components/posts/PostsTimeBlock.tsx
- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
- packages/lesswrong/components/sequences/SequencesGridItem.tsx
- packages/lesswrong/lib/routes.ts
- packages/lesswrong/themes/alignmentForumTheme.ts
- packages/lesswrong/themes/createThemeDefaults.ts
- packages/lesswrong/themes/lesswrongTheme.ts
Makes the background lighter, and adds some faint box shadows to help with the resulting contrast issues.
> Lighter Grey Background

- packages/lesswrong/lib/routes.ts
/tags now redirects to /tags/all instead of old post.
> Add redirect

- packages/lesswrong/components/comments/RecentDiscussionThread.tsx
- packages/lesswrong/components/posts/PostsItemMeta.tsx
- packages/lesswrong/components/tagging/FooterTag.tsx
- packages/lesswrong/components/tagging/FooterTagList.tsx
> Add tags to recent discussion

- packages/lesswrong/components/tagging/TagProgressBar.tsx
- packages/lesswrong/components/tagging/TagSearchHit.tsx
- packages/lesswrong/lib/collections/posts/views.ts
Switch out spreadsheet for link to /allPosts
> Update Progress Bar

- package.json
- public/lesswrong-editor/src/ckeditor.js
> Add rebuild-reinstall-ckeditor yarn command

- packages/lesswrong/components/tagging/FooterTag.tsx
- packages/lesswrong/components/tagging/TagSmallPostLink.tsx
- packages/lesswrong/components/tagging/TagVoteActivity.tsx
- packages/lesswrong/lib/collections/votes/fragments.ts
Changes the UI of the /tagVoting page to make it more presentable, and lets anyone view the page.
I'm not 100% sure about the performance of the page, and whether I made it worse – on localhost, the page generally takes a very long time to load (even before I added my changes). I don't trust my ability to check locally.
> Tag Voting For All

- packages/lesswrong/components/search/CommentsSearchHit.tsx
- packages/lesswrong/components/search/TagsSearchHit.tsx
- packages/lesswrong/server/scripts/algoliaConfigureIndexes.ts
- packages/lesswrong/server/search/utils.ts
Adds a snippet to Tag Search Items. I _think_ I have done this correctly but that it requires re-running an algolia script.
> Tag Snippet

- packages/lesswrong/lib/vulcan-core/default_resolvers.ts
> Fix slug querying crash

- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
removes the tag progress bar from frontpage
> Actually Remove Progress Bar

- packages/lesswrong/lib/vulcan-core/default_resolvers.ts
Found while cleaning out my git stash. In the `multi` resolver, if `enableTotal` is true, we do a `find` followed by a `count`. But if the `find` returned fewer results than the provided `limit`, then the count is unnecessary, because we can just use the length of the result set. This saves a bit of database traffic in a bunch of different places.
> Skip count query when regular query returns fewer than limit results

- packages/lesswrong/components/tagging/TagPage.tsx
- packages/lesswrong/themes/stylePiping.ts
Also slightly adjusts the rendering of the "Read More" text
> Better wiki page header styling

- packages/lesswrong/lib/components.ts
Hotfix version of https://github.com/LessWrong2/Lesswrong2/pull/3525
> [HOTFIX] Fix AF crash when an event is moved to AF

- packages/lesswrong/components/comments/CommentsList.tsx
- packages/lesswrong/components/tagging/TagDiscussionSection.tsx
- packages/lesswrong/components/tagging/TaggingDashboard.tsx
- packages/lesswrong/components/tagging/TagsDetailsItem.tsx
> Add option to collapse tag descriptions

- packages/lesswrong/components/localGroups/GatherTown.tsx
> Garden tooltip

- packages/lesswrong/components/localGroups/GatherTown.tsx
Turns the Gather Message into a Database field, and updates it to be accurate
> Update Gather message

- packages/lesswrong/components/localGroups/GatherTown.tsx
Creates a database setting that, when true, shows the Garden widget to people with 100+ karma.
> garden can be public

- packages/lesswrong/components/walledGarden/GardenCodeWidget.tsx
- packages/lesswrong/components/walledGarden/PomodoroWidget.tsx
- packages/lesswrong/components/walledGarden/PortalBarGcalEventItem.tsx
- packages/lesswrong/components/walledGarden/WalledGardenPortal.tsx
- packages/lesswrong/components/walledGarden/WalledGardenPortalBar.tsx
> Refine Gather Portal Bar Styling

- packages/lesswrong/components/walledGarden/GardenCodeWidget.tsx
- packages/lesswrong/components/walledGarden/PortalBarGcalEventItem.tsx
Two pretty small changes:
1) change https to HTTP in GardenCodes
2) Alter Gcal links to open "save to your own calendar" mode
1 commit, only touches those files.
> Merge Master into Devel (accidental)

- packages/lesswrong/components/walledGarden/GatherTownIframeWrapper.tsx
- packages/lesswrong/components/walledGarden/WalledGardenPortal.tsx
> Collapse garden bar

- packages/lesswrong/components/walledGarden/GatherTownIframeWrapper.tsx
This makes it so the Firefox Gather Town can share screen.
> firefoxScreenshare

- packages/lesswrong/lib/vulcan-lib/callbacks.ts
Fix case-sensitivity issue in runCallbacksAsync that disabled some async vote callbacks
> [HOTFIX] Fix vote callbacks

- packages/lesswrong/components/posts/DeleteDraft.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.tsx
- packages/lesswrong/lib/crud/withCreate.tsx
- packages/lesswrong/lib/crud/withMulti.ts
- packages/lesswrong/lib/crud/withSingle.ts
- packages/lesswrong/lib/crud/withUpdate.tsx
Also tighted up some type annotations that would have caught this particular thing.
(This crash was in a recent refactoring PR that is in devel, and hasn't yet made it to prod, I think.)
> Fix a crash when opening the posts-menu introduced by recent refactors

- packages/lesswrong/lib/routes.ts
> Fix group post backgrounds

- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
Minor PR to update the URL used for the groups link. Shouldn't affect LW
> update hub link

- packages/lesswrong/lib/crud/withMulti.ts
- packages/lesswrong/lib/crud/withSingle.ts
```
[GraphQL error]: Message: app.missing_document, Location: line 2, col 3, Path: tag
```
But where, dangit!?
This PR fixes that.
> Add logs to determine source of errorred GQL request

- packages/lesswrong/components/walledGarden/GatherTown.tsx
- packages/lesswrong/server/gatherTownCron.ts
Rewrites the cronjob that connects to GatherTown and gets a list of users, to reflect the new protocol.
Unfortunately, this code is now very brittle; the protocol is binary, in a way that suggests field offsets are likely to change, and almost any change will cause this start producing gibberish. But for now, it's working again.
> Fix GatherTown user tracker

- packages/lesswrong/server/gatherTownCron.ts
Fixes two issues affecting the GatherTown connected user tracker:
* A field that was always zero in the test data I looked at, turned out to be the length of a string which was sometimes empty-string and sometimes the literal string "null". If it was the latter, subsequent messages in the same packet would be misaligned, losing the rest of the users in the list.
* I was inconsistent with whether a field was named `id` or `playerId`, causing users to be treated as though they had null IDs and deduplicated when they should've been distinct
> [HOTFIX] Fix GatherTown connected-user tracking

- packages/lesswrong/server/resolvers/revisionResolvers.ts
Fixes https://github.com/LessWrong2/Lesswrong2/issues/3555 .
> Hide spoilers in single-line comments

- packages/lesswrong/themes/stylePiping.ts
I prefer this with the current line length. For some reason I just have a really bad reaction to seeing the new font-size in reality (even though I think I didn't when we tried it out a while ago).
> Resize recent discussion text once more

- packages/lesswrong/components/users/KarmaChangeNotifier.tsx
> Fix overlapping text in karma-change notification if you get 3 digits of karma at once

- packages/lesswrong/components/ea-forum/EAHome.tsx
- packages/lesswrong/components/ea-forum/SmallpoxBanner.tsx
- packages/lesswrong/lib/components.ts
Sam has reviewed the code and it only applies to the EA Forum, but feel free to look at it as well.
> Add a banner for smallpox eradication day on the EA Forum

- packages/lesswrong/components/review/FrontpageReviewPhase.tsx
- packages/lesswrong/components/review/NominatePostMenuItem.tsx
> Nominate CTA button [hotfix]

- packages/lesswrong/components/books/BookLanding.tsx
- packages/lesswrong/components/review/BookCheckout.tsx
Capture event when:
- Someone presses "pre-order"
- Someone presses "read a sample"
> Add Tracking to  Book Stuff

- packages/lesswrong/components/ea-forum/EAHome.tsx
- packages/lesswrong/components/posts/AllPostsPage.tsx
- packages/lesswrong/server/gatherTownCron.ts
Oli made some changes in the process of submitting LW code to the EA Forum (a process we're trying out). Some of those changes changes deserve to be upstreamed.
> Submit Oli's EA changes upstream

- packages/lesswrong/components/review/FrontpageReviewPhase.tsx
- packages/lesswrong/components/review/Nominations2019.tsx
> nominations page update

- packages/lesswrong/components/notifications/SubscribeTo.tsx
- packages/lesswrong/components/tagging/TagDiscussionButton.tsx
- packages/lesswrong/components/tagging/TagPage.tsx
Removes labels from the buttons and hides "help improve this tag" on small screens.
> [HOTFIX] Fix tag buttons row overflow

- packages/lesswrong/components/walledGarden/GardenCodesItem.tsx
- packages/lesswrong/components/walledGarden/GardenCodesList.tsx
- packages/lesswrong/components/walledGarden/GardenEventDetails.tsx
- packages/lesswrong/components/walledGarden/GatherTown.tsx
- packages/lesswrong/components/walledGarden/GatherTownIframeWrapper.tsx
- packages/lesswrong/components/walledGarden/WalledGardenMessage.tsx
- packages/lesswrong/components/walledGarden/WalledGardenPortal.tsx
- packages/lesswrong/components/walledGarden/WalledGardenPortalBar.tsx
- packages/lesswrong/lib/collections/gardencodes/views.ts
- packages/lesswrong/lib/components.ts
> Walled Garden Improvements Dec 15 - same as other PR but on Master

- packages/lesswrong/components/books/BookFrontpageWidget.tsx
- packages/lesswrong/components/books/BookLanding.tsx
> Add book shipping text below order button

- packages/lesswrong/components/walledGarden/WalledGardenPortal.tsx
- packages/lesswrong/components/walledGarden/WalledGardenPortalBar.tsx
Reverts NY's changes except keeping how onboarding text comes from a wiki page
> Undo NY's Garden Changes Hotfix

- packages/lesswrong/components/walledGarden/WalledGardenPortal.tsx
Just reorders elements on the page to better suit contents rewrite.
> Minor garden onboarding improvements

- .travis.yml
I accidentally deleted the Github Token that was necessary to deploy via travis. This should add it back in and unbreak deploys.
> New travis GitHub token

- packages/lesswrong/components/review/ReviewVoteTableRow.tsx
- packages/lesswrong/components/review/ReviewVotingPage.tsx
I accidentally left an extraneous JSS class in a previous PR
> remove backIcon

- packages/lesswrong/components/common/LWTooltip.tsx
- packages/lesswrong/components/review/ReviewVoteTableRow.tsx
- packages/lesswrong/components/review/ReviewVotingPage.tsx
- packages/lesswrong/lib/collections/posts/fragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
> Karma votes on reviewVoting

- packages/lesswrong/components/review/ReviewVoteTableRow.tsx
- packages/lesswrong/components/review/ReviewVotingPage.tsx
Note: I noticed the PostsHighlight component behaving a bit weirdly (I had a hard time predicting when it'd display a 'see more' message, and when it'd truncate things). I decided not to spend time looking into that, and picked some parameters (300 words) that seemed to mostly work well. I think that was the right call for now.
> Review Expand-Post Rework

- packages/lesswrong/server/gatherTownCron.ts
Bumps the version number on connect from 3 to 5 (if you send the wrong version number it assumes you're a stale tab and sends a "refresh" message and nothing else). Updates struct offsets to the new protocol. Replaces the `gatherTownWebsocketServer` database setting with making the correct http request to figure it out automatically, so it won't break whenever we pay for a server upgrade or a server upgrade expires.
> [HOTFIX] Fix the GatherTown user-tracking bot

- packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsList.tsx
I think 2 days is too short. It's plausibly that 3 days is too long. Let's try 2.5 days?
> Curation 2.5 day interval

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
> Add a sequences link to EA sidebar

- packages/lesswrong/components/linkPreview/HoverPreviewLink.tsx
- packages/lesswrong/components/linkPreview/PostLinkPreview.tsx
- packages/lesswrong/lib/components.ts
- packages/lesswrong/server.ts
- packages/lesswrong/server/editor/make_editable_callbacks.ts
- packages/lesswrong/server/resolvers/arbitalPageData.ts
> Add Arbital hover previews!

- packages/lesswrong/lib/collections/lwevents/views.ts
- packages/lesswrong/server/cronUtil.ts
- packages/lesswrong/server/gatherTownCron.ts
> Handle case where multiple GatherTown bots have different version numbers and share the DB

- packages/lesswrong/components/books/BookFrontpageWidget.tsx
- packages/lesswrong/components/books/BookLanding.tsx
- packages/lesswrong/components/common/Home2.tsx
- packages/lesswrong/components/review/BookCheckout.tsx
Changes: 
1. Remove book ad from frontpage
2. Hide "Buy (International)" button and add text 
3. Add shipping speed notification for international orders
> Multiple changes to book banner

- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.tsx
- packages/lesswrong/lib/collections/users/custom_fields.ts
- packages/lesswrong/lib/collections/users/fragments.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
This adds a simple notes field to new users that shows up in the sunshine sidebar.
> Sunshine user notes

- packages/lesswrong/components/posts/PostsTitle.tsx
Fixes bug introduced in #4096 that caused a crash in the sequence editor.
> Fix post list editor search hit icon display

- packages/lesswrong/components/review/BookCheckout.tsx
Not in use, adds a file to bundle that's ~3%. Commented out because we might use it again for pre-orders later this year.
> Comments out stripe button code from Books page

- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx
Co-authored-by: Raemon <Raemon@users.noreply.github.com>
> Make flag status persist under snoozing

- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx
(actually created by Jacob, I just wanted the PR to make it easier to check the diff)
> Auto-sign and date mod comments

- packages/lesswrong/components/posts/AllPostsPage.tsx
> Make the description of allPosts site-specific

- README.md
- packages/lesswrong/client/start.tsx
- packages/lesswrong/components/common/SubscribeDialog.tsx
- packages/lesswrong/components/form-components/WrappedSmartForm.tsx
- packages/lesswrong/components/vulcan-forms/Form.tsx
- packages/lesswrong/components/vulcan-forms/FormWrapper.tsx
- packages/lesswrong/lib/types/schemaTypes.ts
- packages/lesswrong/lib/utils/schemaUtils.ts
- packages/lesswrong/lib/vulcan-lib/components.tsx
- packages/lesswrong/server/vulcan-lib/mutators.ts
And some general cleaning up.
Already reviewed in: https://github.com/centre-for-effective-altruism/EAForum/pull/183
> Add some documentation for paradigms inherited from Vulcan

- packages/lesswrong/components/comments/CommentsNewForm.tsx
- packages/lesswrong/components/messaging/ConversationPage.tsx
- packages/lesswrong/components/tagging/history/TagHistoryPage.tsx
- packages/lesswrong/components/vulcan-core/ScrollToTop.tsx
- packages/lesswrong/lib/routes.ts
- packages/lesswrong/lib/vulcan-lib/routes.ts
* Title on tag-history page links to main tag page (fixes #4146)
* Fix a merge conflict in CommentsNewForm
* PM conversations page starts out scrolled to bottom
> Fix a merge conflict that breaks type checking, and a couple small bug fixes

- packages/lesswrong/components/posts/PostsEditForm.tsx
- packages/lesswrong/components/posts/PostsNewForm.tsx
Reverts LessWrong2/Lesswrong2#4161
> Revert "Make it so popup and submission only occur when posting, not drafting."

- packages/lesswrong/components/posts/PostsEditForm.tsx
- packages/lesswrong/components/posts/PostsNewForm.tsx
Reverts LessWrong2/Lesswrong2#4164
> Revert "Revert "Make it so popup and submission only occur when posting, not drafting.""

- package.json
- packages/lesswrong/components/posts/PostSubmit.tsx
- packages/lesswrong/components/posts/PostsEditForm.tsx
- packages/lesswrong/components/posts/PostsNewForm.tsx
- packages/lesswrong/components/posts/SubmitToFrontpageCheckbox.tsx
- packages/lesswrong/components/questions/NewQuestionDialog.tsx
- yarn.lock
This PR introduces a feedback request button that appears to users with 100+ karma on new post forms and drafts.![image](https://user-images.githubusercontent.com/7250541/132267158-4662da7c-ed3d-4b27-b1db-0c7f9610eeb6.png)
It requires corresponding configuration on Intercom to trigger a message upon "requested-feedback" events.
It introduces an issue with CSS for post form buttons on small screens whereby button order gets reversed for some reason. Will fix that separately.
> Feedback request button

- packages/lesswrong/lib/collections/posts/custom_fields.ts
Already reviewed here: https://github.com/centre-for-effective-altruism/EAForum/pull/190
> [EA-Only] Add guard to prevent defaulting events to frontpage

- packages/lesswrong/server/resolvers/petrovDayResolvers.ts
> Petrov day 2021a

- packages/lesswrong/components/seasonal/PetrovDayButton.tsx
- packages/lesswrong/components/seasonal/PetrovDayWrapper.tsx
- packages/lesswrong/server/resolvers/petrovDayResolvers.ts
Fix up the graphql query in resolver plus used of state variable
> Petrov day 2021b

- packages/lesswrong/components/seasonal/PetrovDayButton.tsx
- packages/lesswrong/server/resolvers/petrovDayResolvers.ts
> Petrov day 2021d

- packages/lesswrong/components/seasonal/PetrovDayWrapper.tsx
Fixed the flash of Missile Incoming before the EA Forum data has come back
> Fix petrov button timer

- packages/lesswrong/components/sequences/SequencesPage.tsx
See https://github.com/centre-for-effective-altruism/EAForum/pull/193
> dont show draft sequences to people who arent the author

- packages/lesswrong/components/posts/TableOfContents/TableOfContentsRow.tsx
- packages/lesswrong/components/tagging/TagRevisionItem.tsx
- packages/lesswrong/components/tagging/history/TagHistoryPage.tsx
- packages/lesswrong/components/users/UsersMenu.tsx
- packages/lesswrong/lib/alignment-forum/displayAFNonMemberPopups.ts
- packages/lesswrong/lib/collections/collections/helpers.ts
- packages/lesswrong/lib/collections/comments/collection.ts
- packages/lesswrong/lib/collections/comments/schema.ts
- packages/lesswrong/lib/collections/posts/custom_fields.ts
- packages/lesswrong/lib/collections/posts/validate.ts
- packages/lesswrong/lib/collections/sequences/helpers.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/server/callbacks/chapterCallbacks.ts
- packages/lesswrong/server/partiallyReadSequences.ts
- packages/lesswrong/server/recommendations.ts
- packages/lesswrong/server/scripts/algoliaExport.ts
- packages/lesswrong/server/search/utils.ts
* Remove misleading "isDeleted" field on comments
* Tag history page no longer has a discussion-page link for every revision
* Fix bug which made it so cmd+click on New Post button didn't open in a new tab
* Continue Reading can no longer display inaccessible draft posts
* Sequence next/prev links skip over draft posts
> Assorted bugfixes

- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
- packages/lesswrong/lib/routes.ts
This adds a contact us page for LW, matching the EA Forum.
> Add LW contact page

- packages/lesswrong/components/sequences/CoreReading.tsx
Introduced in: https://github.com/ForumMagnum/ForumMagnum/commit/980fe3094280cab76135d12979ed78a0ad05ef1a
> Fix broken link to R:A-Z

- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
- packages/lesswrong/server/logging.ts
- scripts/deploy.sh
Tests failing on master to deploy merge but I want this change
> More bookmarks when other sections closed

- packages/lesswrong/components/users/UsersProfile.tsx
- packages/lesswrong/lib/collections/users/fragments.ts
- packages/lesswrong/lib/collections/users/schema.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- scripts/generateTypes.sh
A user reached out to me with a request to change his username so his profile wouldn't show up in google search results. My finger slipped and now we have a better way to do that.
> Add noindex option to profiles

- packages/lesswrong/components/books/Book2018Landing.tsx
- packages/lesswrong/components/books/Book2019Animation.tsx
- packages/lesswrong/components/books/Book2019Landing.tsx
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/routes.ts
This a) creates a mockup landing page for the 2019 LW books, b) changes some names of components and adds urls to support books for multiple years.
> 2019 Books Landing Page

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/lib/collections/users/fragments.ts
- packages/lesswrong/lib/collections/users/schema.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/server/emails/renderEmail.tsx
Created in pair programming session with @jcmustin .
> Save last-used timezone on user objects and use it in emails

- packages/lesswrong/components/tagging/FilterMode.tsx
- packages/lesswrong/server/callbacks/votingCallbacks.ts
* Fix broken link when you click on Personal Blog in tag filters 
* Undrafting a post immediately updates its score 
* Fix positioning of the FilterMode hover-over
> 3 small bugfixes

- packages/lesswrong/components/editor/EditorFormComponent.tsx
Hi there! This is my first attempt at submitting a pull request, I hope I did it correctly.
My goal is to fix [this issue](https://github.com/ForumMagnum/ForumMagnum/issues/4304). The change is small and simple, so I don't think it's likely to break anything.
Please let me know if I did everything right, or if there's something that I should've done differently - I want to get good at this.
> Fix question form width on mobile.

- packages/lesswrong/lib/collections/posts/constants.ts
We want people to notice the post more than they are, and we have the infrastructure for icons already thanks to @jcmustin.
> Add a review post icon to the EA Forum

- packages/lesswrong/components/review/FrontpageReviewWidget.tsx
Fixes some bad rendering of the FrontpageReviewWidget on mobile
> hide date on mobile

- packages/lesswrong/components/review/ReviewVotingPage.tsx
Fixed a production bug when implemented locally.
> [Hotfix] Null-safe access

- packages/lesswrong/components/review/FrontpageReviewWidget.tsx
- packages/lesswrong/components/review/LatestReview.tsx
- packages/lesswrong/components/review/ReviewVotingPage.tsx
- packages/lesswrong/lib/components.ts
Makes the latest review show up on the frontpage, hopefully improving engagement with reviews.
A thing I notice that surprised me a bit is that PostsPreviewTooltipSingleWithComment wasn't currently imported into components.ts. I imported it, and it seems to work fine, but wondering why that was.
> Latest Review

- packages/lesswrong/components/review/FrontpageReviewWidget.tsx
- packages/lesswrong/components/review/ReviewVoteTableRow.tsx
- packages/lesswrong/components/review/ReviewVotingPage.tsx
- packages/lesswrong/lib/collections/posts/fragments.ts
- packages/lesswrong/lib/collections/posts/schema.ts
- packages/lesswrong/lib/collections/posts/views.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/lib/reviewUtils.ts
- packages/lesswrong/server/migrations/2021-12-13-updateQuadraticVotes.ts
- packages/lesswrong/server/migrations/index.ts
This is an initial version of a voteMigration script. It doesn't do all the things we might want it to do (i.e. doesn't do any fancy normalization).
I think it's good enough for the Preliminary Vote phase but we need to figure something better out for the Final Voting Phase.
> reviewVoteScore migration

- packages/lesswrong/components/review/FrontpageReviewWidget.tsx
- packages/lesswrong/components/review/LatestReview.tsx
- packages/lesswrong/components/review/ReviewPostButton.tsx
- packages/lesswrong/components/review/ReviewVotingButtons.tsx
Adds analytics contexts to a few places, and fixes a random lint error that came up.
> analytics context for review

- packages/lesswrong/components/books/Book2018Landing.tsx
- packages/lesswrong/components/books/Book2019Animation.tsx
- packages/lesswrong/components/books/Book2019FrontpageWidget.tsx
- packages/lesswrong/components/books/Book2019Landing.tsx
- packages/lesswrong/components/common/Home2.tsx
- packages/lesswrong/components/review/BookCheckout.tsx
- packages/lesswrong/components/vulcan-core/App.tsx
- packages/lesswrong/lib/components.ts
This puts the books on the frontpage and updates the books/2019 landing page
> Books 2019 Launch [wip]

- packages/lesswrong/components/localGroups/LocalGroupPage.tsx
- packages/lesswrong/components/titles/LocalgroupPageTitle.tsx
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/routes.ts
I noticed that the title and description tags were not properly set for the group page and the event page, so I updated them.
> update group page and event page meta tags

- packages/lesswrong/components/review/ReviewVotingPage.tsx
This makes it possible to sort the posts on the Review Dashboard in different ways:
> Review Dashboard sorting

- packages/lesswrong/server/voteServer.ts
Adam Scholl says he was hitting the limit, seems worth increasing them then.
> Increase vote rate limits

- packages/lesswrong/components/posts/BookmarksPage.tsx
> Continue Reading lives on bookmarks page

- packages/lesswrong/components/review/ReviewVoteTableRow.tsx
- packages/lesswrong/components/review/ReviewVotingPage.tsx
Changes this:
To look like this, which I think will address Jacob's feeling of 'looks broken somehow'
> mobile UI for ReviewVoteTableRow

- packages/lesswrong/lib/collections/posts/constants.ts
- packages/lesswrong/lib/collections/posts/views.ts
> Hide the "new start here" post if you are logged in

- packages/lesswrong/lib/collections/posts/views.ts
I meant to address this change JP suggested in the last Final Voting PR, doing a quick merge since it's nonfunctional and was essentially already approved.
> fix final voting view comment

- packages/lesswrong/components/review/ReviewPostComments.tsx
- packages/lesswrong/components/review/ReviewVotingButtons.tsx
- packages/lesswrong/components/review/ReviewVotingPage.tsx
- packages/lesswrong/lib/reviewUtils.ts
> Points total on Voting Page [draft]

- packages/lesswrong/components/review/ReviewVotingPage.tsx
I got the ordering of the "Karma Vote" sorting wrong, which resulted in a broken "Review Vote" sorting. This PR fixes that.
> Fix sorting for "Needs Vote"

- packages/lesswrong/components/review/ReviewVotingPage.tsx
I accidentally put the loading-spinner in a place it couldn't show up. Also, the voteTotal wasn't loading properly if you navigated to the page from the frontpage.
> Fix loading bugs [urgent]

- packages/lesswrong/lib/reviewUtils.ts
Ray is still free to argue for the commit in: https://github.com/ForumMagnum/ForumMagnum/pull/4510
> Revert accidental direct push "remove addDay"

- packages/lesswrong/components/review/FrontpageReviewWidget.tsx
Changes text of CTA button for final voting phase
> Cast Final Votes button

- packages/lesswrong/components/common/Home2.tsx
We ran out of books, and they weren't selling that well anyway, so time to remove the banner
[edit: Oli apparently doesn't think we should remove it yet]
> Remove book banner [LW Only]

- packages/lesswrong/server/utils/feedUtil.ts
The Recent Discussion feed has a couple widgets (eg RecentDiscussionSubscribeReminder) which are mixed in at numeric offsets (ie slot #6), when the list is otherwise sorted by date. This caused that section to fail to load and show an error message if there weren't enough posts for that slot to exist.
> Fix Recent Discussion feed failing to load when no posts

- packages/lesswrong/components/review/FrontpageBestOfLWWidget.tsx
Adds a more prominent button, and makes the entire image a click-target.
> Donate button on frontpage

- packages/lesswrong/components/review/FrontpageBestOfLWWidget.tsx
- packages/lesswrong/components/sequenceEditor/EditSequenceTitle.tsx
- packages/lesswrong/themes/createThemeDefaults.ts
> Merge master into LW Deploy

- packages/lesswrong/lib/collections/posts/views.ts
This adds 'endTime' to the indexes for various event-related views.
> Update event indexes

- packages/lesswrong/components/common/TabNavigationMenu/TabNavigationMenu.tsx
- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
- packages/lesswrong/components/events/modules/EventCards.tsx
The EA Forum (i.e. Max and I) will be exploring how we can better facilitate people taking significant actions. We are adding this link to our sidebar as a quick way to get some information on what opportunities people are interested in.
> [EA Forum only] link to "Take Action" tag from the sidebar

- README.md
- packages/lesswrong/components/form-components/FormComponentDateTime.tsx
> Make event start/end date keyboard editable #573

- packages/lesswrong/components/editor/CKPostEditor.tsx
- packages/lesswrong/components/editor/ReactCKEditor.tsx
working on this with darkruby501
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1201981619837029) by [Unito](https://www.unito.io)
> Editor autocomplete: override mention configuration at init time (prototype)

- packages/lesswrong/lib/collections/users/custom_fields.ts
> Make bio 12 lines instead of 4

- packages/lesswrong/components/seasonal/AprilFools2022.tsx
> "what's this" update for April Fools

- packages/lesswrong/components/seasonal/AprilFools2022.tsx
- packages/lesswrong/server/callbacks/votingCallbacks.ts
This fixes some merge conflicts in master, and resolves some discrepancies between master and lw-deploy. (Some work for April Fools 2022 was done based off master and some in lw-deploy)
> Fix merge conflicts and discrepancies re: April Fools 2022

- packages/lesswrong/components/seasonal/AprilFools2022.tsx
This is intended to fix some merge conflicts on the lw-deploy side of a master/lw-deploy conflict. I previously tried to repair them just on the master side (see this PR https://github.com/ForumMagnum/ForumMagnum/pull/4754) but it didn't quite iron out all the problems.
This PR copies the master version of AprilFools2022.tsx into a branch based off lw-deploy. I've tested merging master into this with a clone of the branch.
> Copy master april fools into lw-deploy

- packages/lesswrong/components/common/Home2.tsx
- packages/lesswrong/components/seasonal/AprilFools2022.tsx
- packages/lesswrong/components/users/UsersNameDisplay.tsx
- packages/lesswrong/components/votes/OverallVoteAxis.tsx
- packages/lesswrong/components/votes/PostsVote.tsx
- packages/lesswrong/lib/collections/users/fragments.ts
- packages/lesswrong/lib/collections/users/views.ts
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/generated/viewTypes.ts
- packages/lesswrong/server/callbacks/votingCallbacks.ts
This removes most Good Heart code from the codebase. It leaves the AprilFools2022 component for the time being. It also leaves 'goodHeartTokens' in the custom_fields file so that we can continue to display the UsersProfile good heart UI, until we've actually paid out the money (in a couple weeks)
> Remove most code from April Fools 2022 (master branch)

- packages/lesswrong/lib/betas.ts
Closes #4690. We want to show this off as we push forward with tag features.
> Ungate new tag subscriptions on the EA Forum

- cypress/integration/posts/edit_post.spec.js
- packages/lesswrong/components/editor/EditTitle.tsx
- packages/lesswrong/components/editor/EditorFormComponent.tsx
- packages/lesswrong/components/notifications/CommentOnYourDraftNotificationHover.tsx
- Clicking away from the title input on post edit form causes the title to be saved
- Notifications for in-line comments now display appropriate message for author and others
- Version History button only appears for posts that have been saved (doesn't show on New Question/Post forms)
> Minor Improvements to Collaborative Editing

- cypress/plugins/index.js
@jimrandomh has a theory that by creating new mongodb connections every time, we were violating an assumption of mongodb's, which is that you only get consistency within each connection, and only eventual consistency across connections. So maybe we were racing with ourselves. Use a connection singleton to prevent that. Mayyyybe this fixes it.
Also a simpler fix is to, instead of dropping the collection before each test, simple truncate it. It will at least stop us from seeing the most common error message `ns not found`.
^^^^ If the above doesn't sound confidence-inspiring, it shouldn't. We're at like 40% that we've fixed it. But we should merge it to see.
> Hopefully maybe fix intermittent cypress errors

- packages/lesswrong/components/posts/PostsPage/PostActions.tsx
- packages/lesswrong/components/search/SearchBarResults.tsx
- packages/lesswrong/components/search/SearchPage.tsx
- packages/lesswrong/components/tagging/AddTag.tsx
- packages/lesswrong/components/tagging/AllTagsAlphabetical.tsx
- packages/lesswrong/components/tagging/AllTagsPage.tsx
- packages/lesswrong/components/tagging/NewTagPage.tsx
- packages/lesswrong/components/tagging/NewTagsList.tsx
- packages/lesswrong/components/tagging/TagHistoryPageTitle.tsx
- packages/lesswrong/lib/collections/tags/helpers.ts
- packages/lesswrong/lib/routes.ts
Co-Authored-By: jpaddison3 <jp@centreforeffectivealtruism.org>
> rename more things related to tagging config var

- packages/lesswrong/components/common/HomeLatestPosts.tsx
- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
- packages/lesswrong/components/posts/PostsItemIcons.tsx
- packages/lesswrong/components/recentDiscussion/RecentDiscussionTag.tsx
- packages/lesswrong/components/revisions/TagPageRevisionSelect.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineSendMessageWithDefaults.tsx
- packages/lesswrong/components/tagging/EditTagPage.tsx
- packages/lesswrong/components/tagging/FilterMode.tsx
- packages/lesswrong/components/tagging/FooterTag.tsx
- packages/lesswrong/components/tagging/SingleLineTagUpdates.tsx
- packages/lesswrong/components/tagging/TagDiscussion.tsx
- packages/lesswrong/components/tagging/TagDiscussionButton.tsx
- packages/lesswrong/components/tagging/TagDiscussionPage.tsx
- packages/lesswrong/components/tagging/TagFilterSettings.tsx
- packages/lesswrong/components/tagging/TagPageButtonRow.tsx
- packages/lesswrong/components/tagging/TagRelCard.tsx
- packages/lesswrong/components/tagging/TagVoteActivity.tsx
- packages/lesswrong/components/tagging/TagsListItem.tsx
- packages/lesswrong/components/tagging/WikiGradeDisplay.tsx
- packages/lesswrong/components/users/KarmaChangeNotifier.tsx
- packages/lesswrong/lib/collections/comments/helpers.ts
- packages/lesswrong/lib/collections/tags/helpers.ts
- packages/lesswrong/server/tagging/tagCallbacks.ts
Renaming lots of links, plus I did a search for \btag\b and read through a whole lotta search results.
> Even more tag renaming

- packages/lesswrong/components/community/modules/CommunityMembers.tsx
- packages/lesswrong/components/messaging/ConversationPage.tsx
This PR just adds event tracking for sending a message in a conversation, and searching for people on the Community Members tab.
> Track messages sent and Community Members tab searches

- packages/lesswrong/components/posts/PostsPage/PostActions.tsx
- packages/lesswrong/components/posts/SubmitToFrontpageCheckbox.tsx
See discussion here: https://cea-core.slack.com/archives/C75BWSNBH/p1651179231355559
> make post on front page message more intuitive

- packages/lesswrong/components/posts/AddToCalendar/AddToCalendarButton.tsx
This PR is to address an issue where the AddToCalendar dropdown didn't always appear on top of other components.
> update AddToCalendar dropdown to use LWPopper

- packages/lesswrong/components/editor/PostVersionHistory.tsx
Adds some analytics for opening the Version History dialog, and for restoring a version.
> Restore version button analytics

- packages/lesswrong/components/ea-forum/EASequencesHome.tsx
- packages/lesswrong/themes/siteThemes/eaTheme.ts
This PR is just for addressing any stying issues before we deploy the new theme picker code.
> [EA Forum only] fix styling issues from theme picker

- packages/lesswrong/components/form-components/LocationFormComponent.tsx
- packages/lesswrong/components/localGroups/EventNotificationsDialog.tsx
- packages/lesswrong/components/posts/PostsItemComments.tsx
- packages/lesswrong/components/themes/ThemePickerMenu.tsx
- packages/lesswrong/components/users/WrappedLoginForm.tsx
- packages/lesswrong/server/vulcan-lib/apollo-ssr/pageCache.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
- packages/lesswrong/themes/defaultPalette.ts
- packages/lesswrong/themes/globalStyles/globalStyles.ts
- packages/lesswrong/themes/siteThemes/eaTheme.ts
- packages/lesswrong/themes/stylePiping.ts
- packages/lesswrong/themes/themeNames.ts
- packages/lesswrong/themes/themeType.ts
Fix some theming issues found post-merge.
> Theming fixes

- packages/lesswrong/server/authenticationMiddlewares.ts
This updates the oauth provider to use email.
> Ben migration to sync email fields

- packages/lesswrong/components/community/modules/CommunityMembers.tsx
- packages/lesswrong/components/community/modules/LocalGroups.tsx
- packages/lesswrong/components/form-components/PrefixedInput.tsx
- packages/lesswrong/themes/siteThemes/eaTheme.ts
- packages/lesswrong/themes/userThemes/darkMode.ts
Mostly small adjustments to account for theme picker. Small thing that affects other forums is that I adjusted the comment and answer border colors in dark mode, to be more visible.
> more style adjustments for EA Forum

- packages/lesswrong/components/users/UsersProfile.tsx
- packages/lesswrong/themes/siteThemes/eaTheme.ts
This is mostly EA Forum only. A few small UI adjustments / fixes.
> fix EA Forum downvote color, adjust Message button

- packages/lesswrong/components/tagging/TagEditsByUser.tsx
- packages/lesswrong/server/apolloServer.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/renderUtil.ts
Fixes: https://github.com/ForumMagnum/ForumMagnum/issues/4945
> Page responses should have an html tag

- packages/lesswrong/lib/types/collectionTypes.ts
- packages/lesswrong/server/callbacks/votingCallbacks.ts
For posts with co-authors, give each author karma/sqrt(numAuthors) each.
> Share karma among co-authors

- .github/workflows/deployEADev.yaml
- packages/lesswrong/components/editor/PostSharingSettings.tsx
This is into collabEditor, in anticipation of a imminent merge to master.
> Use /Contact link, not lesswrong-specific email

- scripts/postinstall.sh
Let the dev build work on [NixOS](https://en.wikipedia.org/wiki/NixOS), which has weird binary paths.
> Generalize hashbang for postinstall.sh [dev build]

- packages/lesswrong/components/community/modules/CommunityMembers.tsx
- packages/lesswrong/components/users/UsersProfile.tsx
Also increased the # users per page on the EA Forum's Community Members map
> hide user map location on LW profiles

- packages/lesswrong/components/sunshineDashboard/AFSuggestCommentsList.tsx
- packages/lesswrong/components/sunshineDashboard/AFSuggestPostsList.tsx
- packages/lesswrong/components/sunshineDashboard/AFSuggestUsersList.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewTagsList.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineReportedContentList.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineSidebar.tsx
Already merged into `master` but that now requires a migration to merge into lw-deploy. To get this fix applied faster, I'm gonna merge the same branch straight into lw-deploy
> Af suggested users fixes

- packages/lesswrong/components/posts/HideFrontPagePostButton.tsx
- packages/lesswrong/server/hidePostMutation.ts
Noticed this bug with #5022 while testing on staging. My bad for not fixing it when I fixed [this](https://github.com/ForumMagnum/ForumMagnum/pull/5022/commits/8a6460a1390d9fbb77471f561e66c685d8c7329e).
> Fix case where posts would not get hidden if user did not already have a hidden list

- public/lesswrong-editor/src/ckeditor.js
Fixes a comment that was out of date.
> Fix CkEditor documentation

- packages/lesswrong/server/register-mui-styles/index.ts
- packages/lesswrong/server/styleGeneration.tsx
I think I figured it out, just had to give them all `stylePriority: -1`
> fix register-mui-styles color issue

- packages/lesswrong/components/recentDiscussion/RecentDiscussionTagRevisionItem.tsx
Probably I should just make this a setting, but Lizka wants to make changes now.
> Give Lizka the higher bar for topic updates given to Pablo

- packages/lesswrong/components/sunshineDashboard/ModerationLog.tsx
- packages/lesswrong/components/vulcan-core/Datatable.tsx
The /moderation page's loadMore feature wasn't properly working. I fixed it, and while I was at it slightly improved the styling.
> /moderation loadMore and styling

- packages/lesswrong/components/ea-forum/users/EAGApplicationImportForm.tsx
This is just adding some analytics to the EAG application import form that was just released.
> [EA Forum only] add some analytics around EAG application import form

- packages/lesswrong/lib/collections/posts/schema.tsx
Fixes a small issue introduced by #5152
> Fix broken link

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/sequences/CollectionsPage.tsx
- packages/lesswrong/components/sequences/SequencesHighlightsCollection.tsx
- packages/lesswrong/components/sequences/SequencesSmallPostLink.tsx
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/routes.ts
This adds a collection page for "Sequences Highlights", a subset of the sequences.
> Sequences Highlights

- packages/lesswrong/components/posts/PostsItemWrapper.tsx
I went to fix the scrollbars on the sequence chapter editor, and then gave it an overall cleanup.
> Fix styling on sequence chapter editor

- packages/lesswrong/components/users/UsersProfile.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202564827962526) by [Unito](https://www.unito.io)
> fix bad import from merge conflict resolution

- packages/lesswrong/components/alignment-forum/AlignmentForumHome.tsx
- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
- packages/lesswrong/components/sequences/CuratedSequences.tsx
- packages/lesswrong/components/sequences/SequencesGridItem.tsx
- packages/lesswrong/lib/components.ts
Adds Curated Sequences to the logged in frontpage on LessWrong. Also refactors things into a CuratedSequences component which I intend to update with more complex behavior soon.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202565010684320) by [Unito](https://www.unito.io)
> Recommended sequences

- packages/lesswrong/lib/collections/tags/schema.ts
https://github.com/ForumMagnum/ForumMagnum/pull/5202
> Resubmit: Fix topic creation

- packages/lesswrong/components/posts/PostSubmit.tsx
Based on a request from Lizka: https://cea-core.slack.com/archives/C038J512SD8/p1657194404067589
> [EA Forum only] lower feedback karma threshold to 200

- packages/lesswrong/lib/collections/tags/collection.ts
Is currently a bad user experience for those under 10 karma, PR coming to fix that.
> [EA] Stop Topic Spampocalypse by karma-gating Topics

- packages/lesswrong/lib/collections/tags/collection.ts
In testing, I nicely fixed a bug and then forgot to commit the results 🤦‍♂️
> [EA] Topic spampocalypse fix

- packages/lesswrong/components/posts/PostsItem2.tsx
- packages/lesswrong/components/posts/PostsItem2MetaInfo.tsx
- packages/lesswrong/components/posts/PostsItemIcons.tsx
Reverts ForumMagnum/ForumMagnum#5259
Breaks mobile
> [Hotfix] Revert "Fix titles being squeezed with many coauthors"

- packages/lesswrong/components/posts/PostSubmit.tsx
[Asana](https://app.asana.com/0/628521446211730/1202599588470699/f). Someone was confused and thought that the feedback might be from the users with whom they had shared the draft.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202615551272485) by [Unito](https://www.unito.io)
> Add tooltip to request feedback button

- packages/lesswrong/components/posts/PostsPage/WelcomeBox.tsx
- packages/lesswrong/components/posts/TableOfContents/ToCColumn.tsx
> fix styling for screen resizing

- packages/lesswrong/components/posts/PostsPage/WelcomeBox.tsx
- packages/lesswrong/components/posts/TableOfContents/ToCColumn.tsx
https://github.com/ForumMagnum/ForumMagnum/pull/5296
> same changes for lwdeploy

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/lib/routes.ts
> Make /handbook the new intro curriculum

- packages/lesswrong/components/editor/Editor.tsx
- packages/lesswrong/components/editor/EditorFormComponent.tsx
- packages/lesswrong/components/editor/PostSharingSettings.tsx
This just goes through and cleans  up some lint errors in the editor files – unused variables, unused code, inconsisten null checks.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202687007470641) by [Unito](https://www.unito.io)
> Cleanup Editor files

- packages/lesswrong/components/sequences/EACoreReading.tsx
Changes the author from Aaron to CEA
> [EA Only] Change handbook author

- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202723077458477) by [Unito](https://www.unito.io)
> [EA Only] New topics tooltip

- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
- packages/lesswrong/components/sequences/CollectionsItem.tsx
- packages/lesswrong/components/sequences/LWCoreReading.tsx
This adds a Highlights collection item at the top of the frontpage for LW.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202793275345805) by [Unito](https://www.unito.io)
> Highlights on Frontpage

- packages/lesswrong/lib/collectionUtils.ts
See related: https://app.slack.com/client/T3ERD8FQT/C75BWSNBH/thread/C75BWSNBH-1660606251.390009
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202804037692311) by [Unito](https://www.unito.io)
> Add more logging when mismatched indexes are found

- packages/lesswrong/components/recommendations/CuratedContentItem.tsx
- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
Cleans up a few extraneous lines
> Remove unused code, comment out unused items for CuratedContentItem

- packages/lesswrong/components/form-components/FormComponentNumber.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
- packages/lesswrong/components/sequences/LargeSequencesItem.tsx
- packages/lesswrong/lib/collections/posts/fragments.ts
- packages/lesswrong/lib/collections/posts/schema.tsx
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
Remerge after resetting master
See #5465 for the original PR
> Remerge fix handbook read times

- packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx
Remerge after resetting master branch
See #5488 for original PR
> Remerge smaller permissions buttons

- packages/lesswrong/components/editor/localStorageHandlers.ts
> Remove unused code from getLSHandlers

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
- packages/lesswrong/components/seasonal/HomepageCommunityMap.tsx
- packages/lesswrong/lib/components.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202852429917480) by [Unito](https://www.unito.io)
> Add map to frontpage for ACX Everywhere

- packages/lesswrong/components/seasonal/HomepageCommunityMap.tsx
On the previous PR #5507 I had forgotten to implement the "only render on home page" check. This adds that.
> Fix HomepageCommunityMap route-checking

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/ea-forum/AdvisorCard.tsx
- packages/lesswrong/components/ea-forum/AdvisorsPage.tsx
- packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
Quick merge of master to address https://github.com/ForumMagnum/ForumMagnum/pull/5589
> Merge master into LW-Deploy Fix mobile acx map display

- packages/lesswrong/components/Layout.tsx
It's served it's time. Time to go back to normal.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202941763158639) by [Unito](https://www.unito.io)
> Remove frontpage map from LessWrong

- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
- packages/lesswrong/components/recommendations/curatedContents.ts
> Update spotlight to Babble and Prune [LW Only]

- packages/lesswrong/server/callbacks/alignment-forum/alignmentCommentCallbacks.ts
- packages/lesswrong/server/callbacks/commentCallbacks.ts
- packages/lesswrong/server/migrations/2021-04-28-populateCommentDescendentCounts.ts
- packages/lesswrong/server/utils/commentTreeUtils.ts
> Merge master 09 08 22

- packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
- packages/lesswrong/components/posts/DraftsList.tsx
I will probably not merge this PR directly, but merge it into collab-editing-to-master instead, once approved.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202950501470778) by [Unito](https://www.unito.io)
> Use DraftsList on EAUsersProfile

- packages/lesswrong/lib/components.ts
No idea how this worked for LW
> Add missing component import

- packages/lesswrong/components/tagging/TagPage.tsx
- packages/lesswrong/lib/collections/tags/schema.ts
Co-authored-by: Sarah Cheng <sarah.cheng@centreforeffectivealtruism.org>
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202989770139777) by [Unito](https://www.unito.io)
> Allow setting an explicit descriptionTruncationCount on the EA Forum

- packages/lesswrong/components/posts/PostsEditForm.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202991645217344) by [Unito](https://www.unito.io)
> Fix crosspost editing after being broken by great divergence

- packages/lesswrong/components/editor/CollabEditorPermissionsNotices.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202991707846365) by [Unito](https://www.unito.io)
> Collaboration Notice styles

- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
- packages/lesswrong/components/recommendations/curatedContents.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202992275588790) by [Unito](https://www.unito.io)
> Multiagent models spotlight

- packages/lesswrong/components/tagging/TagSubforumPage.tsx
- packages/lesswrong/lib/collections/tags/fragments.ts
Kinda trolling with the coauthors, but we're all on a call
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202997225441184) by [Unito](https://www.unito.io)
> Fix tag edit fragment and title-case subforum title

- packages/lesswrong/server/notificationCallbacks.tsx
Users who RSVPed to events with no location set got an email saying the event had changed, every time someone else RSVPed. Caused by this terrible hack in `updateMutator` (which is worked around rather than removed, for now, because taking it out introduces big risks of its own):
```
// FIXME: Filtering out null-valued fields here is a very sketchy, probably
// wrong thing to do. This originates from Vulcan, and it's not clear why it's
// doing it. Explicit cast to make it type-check anyways.
document = pickBy(document, f => f !== null) as any;
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202997935937601) by [Unito](https://www.unito.io)
> Don't send spurious notifications about events changing every time someone RSVPs

- packages/lesswrong/components/ea-forum/advice/AdvisorCard.tsx
- packages/lesswrong/components/ea-forum/advice/AdvisorsPage.tsx
- packages/lesswrong/components/ea-forum/advice/CommunityMemberCard.tsx
- packages/lesswrong/components/messaging/ProfilePhoto.tsx
- packages/lesswrong/lib/collections/users/views.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- Show more community members
- Only show those who have a bio written
- Add new advisor
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203000069103570) by [Unito](https://www.unito.io)
> [EA Forum only] some small updates to advisors page, incl adding new advisor

- packages/lesswrong/components/editor/PostSharingSettings.tsx
world's most boring PR
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203002798740507) by [Unito](https://www.unito.io)
> Fix "Copy-Link" in post sharing to include url base/prefix

- packages/lesswrong/components/comments/CommentsTimelineSection.tsx
- packages/lesswrong/components/tagging/SubforumCommentsThread.tsx
- packages/lesswrong/components/tagging/SubforumSubscribeSection.tsx
- packages/lesswrong/components/tagging/TagSubforumPage.tsx
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/filterSettings.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202997053679280) by [Unito](https://www.unito.io)
> Add join button to subforum

- packages/lesswrong/components/form-components/PodcastEpisodeInput.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203017539659012) by [Unito](https://www.unito.io)
> fix podcast episode input for posts

- packages/lesswrong/components/form-components/PodcastEpisodeInput.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203017636282236) by [Unito](https://www.unito.io)
> Merge master 09 20 2022

- packages/lesswrong/components/common/TabNavigationMenu/SubforumsList.tsx
- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
- packages/lesswrong/lib/collections/tags/views.ts
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/generated/viewTypes.ts
This PR adds links to your subforums in the sidebar, under Topics. This is mostly for our beta test, and will probably change in the future.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203018777287606) by [Unito](https://www.unito.io)
> link to your subforums in the sidebar

- packages/lesswrong/lib/collections/tags/fragments.ts
- packages/lesswrong/lib/collections/tags/schema.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/lib/notificationTypes.tsx
- packages/lesswrong/server/notificationCallbacks.tsx
- packages/lesswrong/server/notificationTypesServer.tsx
- packages/lesswrong/server/tagging/tagCallbacks.ts
Elika's most important request.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203019058646129) by [Unito](https://www.unito.io)
> Notify subforum mods of new users joining their groups

- packages/lesswrong/components/editor/Editor.tsx
- packages/lesswrong/components/form-components/MuiTextField.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203039718589590) by [Unito](https://www.unito.io)
> Merge master 09 23 2022

- packages/lesswrong/components/ea-forum/advice/AdvisorsPage.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203041121623375) by [Unito](https://www.unito.io)
> [EA Forum only] link to Harshu's forum profile

- packages/lesswrong/components/ea-forum/EventBanner.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203043621564776) by [Unito](https://www.unito.io)
> Eliminate mobile margin on event banner

- packages/lesswrong/components/ea-forum/EventBanner.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203043760710146) by [Unito](https://www.unito.io)
> [EA] Deploy event banner resolution fix

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/seasonal/PetrovDayButton.tsx
- packages/lesswrong/lib/petrovHelpers.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203044261654447) by [Unito](https://www.unito.io)
> Add display of users above threshold to Petrov Day UI

- packages/lesswrong/components/recommendations/CuratedContentItem.tsx
- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
- packages/lesswrong/components/recommendations/curatedContents.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203044313226308) by [Unito](https://www.unito.io)
> Create a spotlight for petrov day

- packages/lesswrong/lib/petrovHelpers.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203045447514826) by [Unito](https://www.unito.io)
> fix no karma launch permission

- packages/lesswrong/lib/petrovHelpers.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203045409405856) by [Unito](https://www.unito.io)
> Merge master 09 26 2022

- packages/lesswrong/lib/collections/users/schema.ts
Accidentally left in testing code therefore not hiding the opt out button
> fix opt out button hiding

- packages/lesswrong/lib/collections/users/schema.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203050491291934) by [Unito](https://www.unito.io)
> Hardcode petrovBeforeTime to fix bug

- packages/lesswrong/components/posts/PostsPage/PostsPageCrosspostWrapper.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203072086971447) by [Unito](https://www.unito.io)
> Fix crossposts not having a table of contents

- packages/lesswrong/components/posts/PostsPage/PostsPageCrosspostWrapper.tsx
Bug reported by Eli
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203080570453109) by [Unito](https://www.unito.io)
> Fix crosspost link-posts

- packages/lesswrong/lib/collections/tags/helpers.ts
- packages/lesswrong/lib/vulcan-lib/utils.ts
- packages/lesswrong/server/notificationTypesServer.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203083438083102) by [Unito](https://www.unito.io)
> Fix links in subforum new user email notifications to be absolute

- packages/lesswrong/lib/collections/posts/collection.ts
- packages/lesswrong/lib/collections/posts/schema.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203096911256317) by [Unito](https://www.unito.io)
> revert a couple post field permissions

- packages/lesswrong/components/posts/PostsPage/PostsPodcastPlayer.tsx
🤦
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203110083651194) by [Unito](https://www.unito.io)
> check actual ref value

- packages/lesswrong/lib/routes.ts
Fixes #5175
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203077330765987) by [Unito](https://www.unito.io)
> Add some missing page titles

- packages/lesswrong/components/tagging/TagPage.tsx
Fixes #5536
Co-Authored-By: Jonathan Mustin <jonathan.mustin@centreforeffectivealtruism.org>
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203077259271541) by [Unito](https://www.unito.io)
> Correctly show old versions of tags on tag pages

- package.json
- packages/lesswrong/lib/apollo/links.ts
- yarn.lock
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203116062301381) by [Unito](https://www.unito.io)
> Fix fetch in apollo HTTP link for SSR on node <18

- packages/lesswrong/components/community/modules/CommunityBanner.tsx
- packages/lesswrong/components/community/modules/LocalGroups.tsx
- packages/lesswrong/components/community/modules/OnlineGroups.tsx
- packages/lesswrong/components/events/modules/HighlightedEventCard.tsx
- packages/lesswrong/components/form-components/SingleTagItem.tsx
- packages/lesswrong/components/users/UsersProfile.tsx
- packages/lesswrong/themes/defaultPalette.ts
- packages/lesswrong/themes/siteThemes/alignmentForumTheme.ts
- packages/lesswrong/themes/siteThemes/eaTheme.ts
- packages/lesswrong/themes/stylePiping.ts
- packages/lesswrong/themes/themeType.ts
- packages/lesswrong/themes/userThemes/darkMode.ts
* Increased link contrast in AF site theme
* Fixed white-on-white in private messages
* Fixed white-on-white in EA Forum-specific events UI
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202992093263911) by [Unito](https://www.unito.io)
> Fix various dark mode color issues

- packages/lesswrong/server/search/algoliaDocuments.d.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203133858302332) by [Unito](https://www.unito.io)
> Remove unused postSequenceId

- packages/lesswrong/components/users/KarmaChangeNotifier.tsx
- packages/lesswrong/lib/collections/comments/helpers.ts
- packages/lesswrong/lib/collections/users/fragments.ts
- packages/lesswrong/lib/collections/users/karmaChangesGraphQL.ts
- packages/lesswrong/server/karmaChanges.ts
Co-authored-by: jpaddison3 <jp@centreforeffectivealtruism.org>
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203133223526186) by [Unito](https://www.unito.io)
> Make links to subforum comments from karma change notification work

- packages/lesswrong/lib/betas.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202992072947485) by [Unito](https://www.unito.io)
> Remove admin gate on EA Forum dark mode

- packages/lesswrong/lib/betas.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203143326031371) by [Unito](https://www.unito.io)
> Re-gate dark mode on EA Forum

- packages/lesswrong/components/tagging/TagSubforumButton.tsx
- packages/lesswrong/lib/collections/tags/schema.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203143798398202) by [Unito](https://www.unito.io)
> Fix showing subforum unread count as null

- packages/lesswrong/lib/collections/users/schema.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203146201265972) by [Unito](https://www.unito.io)
> hide new user guidelines ack field in user profile form

- .ebextensions/99datadog.config
- Dockerfile
- build.js
- package.json
- packages/lesswrong/components/ea-forum/StickiedPosts.tsx
- packages/lesswrong/components/posts/PostsTitle.tsx
- packages/lesswrong/lib/apollo/links.ts
- packages/lesswrong/server/datadog/tracer.ts
- packages/lesswrong/server/serverStartup.ts
- yarn.lock
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203150859337837) by [Unito](https://www.unito.io)
> [EA] Deploy datadog tracing

- .github/workflows/unitTests.yaml
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203150936613941) by [Unito](https://www.unito.io)
> Stop unit tests from re-running on PRs to ea-deploy

- packages/lesswrong/server/fmCrosspost/crosspost.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203169786271610) by [Unito](https://www.unito.io)
> Fix ability to create/edit events (broken by a no-crossposting check)

- .github/actions/setupEnvironment/action.yaml
- .github/workflows/cypress.yaml
- .github/workflows/unitTests.yaml
- package.json
- packages/lesswrong/server/migrations/meta/PgStorage.ts
- packages/lesswrong/server/migrations/meta/umzug.ts
- yarn.lock
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203198626829692) by [Unito](https://www.unito.io)
> Better pg workflows

- packages/lesswrong/lib/sql/Type.ts
This fixes a bug I found while doing https://github.com/ForumMagnum/ForumMagnum/pull/5925 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203214871832436) by [Unito](https://www.unito.io)
> Postgres: Fix sql array default bug

- packages/lesswrong/server/tableOfContents.ts
I had accidentally merged a revert here, and am restoring it.
https://github.com/ForumMagnum/ForumMagnum/pull/5929/commits/514d9948cdbcfce278a8ca7c1a195523c3a74dbd
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203240885229050) by [Unito](https://www.unito.io)
> Revert accidentally reverted toc changes

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/comments/CommentsTimeline.tsx
- packages/lesswrong/components/comments/CommentsTimelineSection.tsx
- packages/lesswrong/components/common/Header.tsx
- packages/lesswrong/components/posts/PostsItem2.tsx
- packages/lesswrong/components/posts/PostsItemTooltipWrapper.tsx
- packages/lesswrong/components/posts/PostsList2.tsx
- packages/lesswrong/components/posts/PostsListSortDropdown.tsx
- packages/lesswrong/components/posts/PostsNewForm.tsx
- packages/lesswrong/components/tagging/TagSubforumPage.tsx
- packages/lesswrong/components/tagging/TagSubforumPostsSection.tsx
- packages/lesswrong/lib/collections/comments/views.ts
- packages/lesswrong/lib/collections/posts/fragments.ts
- packages/lesswrong/lib/collections/posts/schema.tsx
- packages/lesswrong/lib/collections/posts/views.ts
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/lib/routes.ts
- packages/lesswrong/lib/vulcan-lib/routes.ts
- packages/lesswrong/server/callbacks/postCallbacks.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203251398213801) by [Unito](https://www.unito.io)
> [EA] Deploy subforum posts section

- packages/lesswrong/components/tagging/TagSubforumPage.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203252433540353) by [Unito](https://www.unito.io)
> Make comment links work with tab layout

- .github/workflows/unitTests.yaml
- .gitignore
- build.js
- cypress/plugins/index.js
- package.json
- packages/lesswrong/lib/executionEnvironment.ts
- packages/lesswrong/server/apolloServer.ts
- packages/lesswrong/server/createTestingPgDb.ts
- scripts/createIntegrationPgDb.sh
- scripts/seedIntegrationDb.sh
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203254348008398) by [Unito](https://www.unito.io)
> PG Test DB Creation

- packages/lesswrong/components/common/withDialog.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203255767184442) by [Unito](https://www.unito.io)
> fix useOnNavigate import

- packages/lesswrong/server/notificationBatching.tsx
- packages/lesswrong/server/notificationTypesServer.tsx
There was an edge case for email notifications of subforum comments where there could be 0 comments by the time the email is sent (e.g. if they have been deleted), in which case we want to skip sending the email. This adds the ability to do that
Things which would be good to do but which I haven't done in this PR:
- Add `skip` functions for other notification types which have these edge cases
- Make loading data for emails more efficient, a lot of data gets loaded twice currently (once for the subject, once for the body) and now with the `skip` function the data is loaded 3 times for subforum comment notifications. This would be nice to fix but this bit of code is not performance critical atm …
> Add ability to skip sending email notifications

- .github/workflows/cypress.yaml
- .github/workflows/unitTests.yaml
- cypress/plugins/index.js
- packages/lesswrong/lib/sql/tests/testingSqlClient.ts
- packages/lesswrong/server/createTestingPgDb.ts
- packages/lesswrong/server/serverStartup.ts
- packages/lesswrong/server/sqlConnection.ts
- scripts/createIntegrationPgDb.sh
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203278223044586) by [Unito](https://www.unito.io)
> Postgres: Database service containers in workflows

- packages/lesswrong/components/moderationTemplates/ModerationTemplatesPage.tsx
- packages/lesswrong/lib/collections/moderationTemplates/collection.ts
- packages/lesswrong/lib/collections/moderationTemplates/fragments.ts
- packages/lesswrong/lib/collections/moderationTemplates/index.ts
- packages/lesswrong/lib/collections/moderationTemplates/permissions.ts
- packages/lesswrong/lib/collections/moderationTemplates/schema.ts
- packages/lesswrong/lib/collections/moderationTemplates/views.ts
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/lib/generated/viewTypes.ts
- packages/lesswrong/lib/index.ts
- packages/lesswrong/lib/routes.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203254669030146) by [Unito](https://www.unito.io)
> Make Template Messages/Comments a collection (and make a page for them)

- packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx
- packages/lesswrong/components/sunshineDashboard/RateLimitDialog.tsx
- packages/lesswrong/lib/components.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203280951696416) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203280951696416
> dialog for rate limit end date customization

- packages/lesswrong/components/search/ExpandedSequencesSearchHit.tsx
- packages/lesswrong/components/search/ExpandedTagsSearchHit.tsx
Mostly to make sure the background color properly flips
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203274077548752) by [Unito](https://www.unito.io)
> [EA Forum only] a couple search page color fixes for dark mode

- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx
- packages/lesswrong/components/sunshineDashboard/UsersReviewInfoCard.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203281922086291) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203281922086291
> Change "deleted" posts to "drafts" in mod tools

- packages/lesswrong/components/search/ExpandedUsersSearchHit.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203282917154127) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203282917154127
> [EA Forum only] track when user search leads to a message

- build.js
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203286692807950) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203286692807950
> Mark csso as external

- packages/lesswrong/components/comments/CommentFrame.tsx
- packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
- packages/lesswrong/lib/collections/comments/fragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203282313748296) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203282313748296
> remove new fragment field which is breaking crossposted posts

- packages/lesswrong/components/common/HeadTags.tsx
- packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
- packages/lesswrong/lib/collections/users/schema.ts
Addresses #5679
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203295613413975) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203295613413975
> smaller link preview image for user profile page

- packages/lesswrong/components/tagging/TagSubforumPage.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203265423290044) by [Unito](https://www.unito.io)
> Fix width jittering in subforum

- packages/lesswrong/components/shortform/ShortformSubmitForm.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203326252079651) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203326252079651
> Fix shortform prompt

- packages/lesswrong/components/sunshineDashboard/UsersReviewInfoCard.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203332031293770) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203332031293770
> put referrer and landing page on separate lines in moderation dashboard

- packages/lesswrong/server/callbacks/commentCallbacks.ts
This PR addresses #5949
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203338608518883) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203338608518883
> user's own comment on post doesn't appear unread

- packages/lesswrong/components/form-components/ImageUpload.tsx
- packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203350268100033) by [Unito](https://www.unito.io)
> [EA] deploy enabling event img cropping

- packages/lesswrong/components/common/CitationTags.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/lib/components.ts
A [recent forum post](https://forum.effectivealtruism.org/posts/erh7FydqcmwiriYzv/google-scholar-is-now-listing-some-ea-forum-posts) pointed out that we're now being indexed by Google Scholar, but we don't have the correct meta tags for citations to work correctly. This PR should fix this, but apparently it can take anywhere from a few days up to 9 months for the changes to be reflected on Google Scholar, so we'll have to wait and see...
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203336364100685) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203336364100685
> Add citation meta tags

- migrate.js
- scripts/runProduction.sh
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203358306903180) by [Unito](https://www.unito.io)
> Fix PG_URL handling for database migrations during deploy

- migrate.js
- scripts/runProduction.sh
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203358389065183) by [Unito](https://www.unito.io)
> Fetch correct credentials when running migrations in deploy pipeline

- packages/lesswrong/server/migrations/meta/umzug.ts
- scripts/runProduction.sh
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203358366219650) by [Unito](https://www.unito.io)
> Avoid using 'yes' in run script - AWS EB hates it

- scripts/runProduction.sh
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203358372450309) by [Unito](https://www.unito.io)
> Temporarily disable migrations on deploy

- .github/workflows/eaDailyDevReplica.yaml
- scripts/eaReplicateDevDb.sh
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203361747652119) by [Unito](https://www.unito.io)
> Fix EA daily dev replica PG_URL

- packages/lesswrong/components/recentDiscussion/RecentDiscussionSubscribeReminder.tsx
Requested by Lizka on Slack
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203363096203537) by [Unito](https://www.unito.io)
> Update EA Forum digest description

- packages/lesswrong/server/resolvers/tagHistoryFeed.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203373225888734) by [Unito](https://www.unito.io)
> Remove subforum comments from tag history

- packages/lesswrong/themes/stylePiping.ts
Fixes #6069.
Bug introduced by: https://github.com/ForumMagnum/ForumMagnum/pull/5805
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203355514482292) by [Unito](https://www.unito.io)
> Fix indented ordered list styles

- packages/lesswrong/lib/components.ts
- scripts/runProduction.sh
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203376609711705) by [Unito](https://www.unito.io)
> Deploy fix for missing component import for AF admins

- packages/lesswrong/server/usedMuiStyles.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203384276144946) by [Unito](https://www.unito.io)
> Fix MUI checkbox SSR

- packages/lesswrong/lib/collections/users/schema.ts
A request from the forum suggestions thread and endorsed by Lizka
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203386023520173) by [Unito](https://www.unito.io)
> s/VP/Virtual Program

- .github/workflows/deployEAStagingPG.yaml
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203391848669257) by [Unito](https://www.unito.io)
> Update EA PG staging deploy branch

- packages/lesswrong/components/tagging/TagSubforumPage2.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203394147567655) by [Unito](https://www.unito.io)
> Subforum: Make sure banner image renders correctly at all sizes

- packages/lesswrong/components/hooks/useForeignCrosspost.ts
- packages/lesswrong/server/fmCrosspost/routes.ts
- packages/lesswrong/server/fmCrosspost/types.ts
Follow up to [this PR](https://github.com/ForumMagnum/ForumMagnum/pull/6024).  Should only be merged in after the EA Forum deploys the previous one.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203333096522793) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201302964208280/1203333096522793
> switch to using new getCrosspost route functionality

- packages/lesswrong/server/callbacks/sunshineCallbackUtils.tsx
Request from Lizka, backed up by data from @Recursing.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203414536734299) by [Unito](https://www.unito.io)
> [EA] Change automod downvote threshold to 10

- packages/lesswrong/components/common/SectionButton.tsx
- packages/lesswrong/components/tagging/TagSubforumPage2.tsx
The buttons: 
Also add some margin for those buttons.
The new discussion box:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203430532697821) by [Unito](https://www.unito.io)
> Enable functionality of subforum "new" buttons

- packages/lesswrong/components/posts/PostsListSortDropdown.tsx
- packages/lesswrong/components/tagging/TagSubforumPage2.tsx
- packages/lesswrong/components/tagging/TagTableOfContents.tsx
Just some small fixes
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203434299012730) by [Unito](https://www.unito.io)
> Subforum: cleanup ready for launch

- packages/lesswrong/components/comments/CommentPermalink.tsx
- packages/lesswrong/components/tagging/TagSubforumPage2.tsx
This is mainly to keep links in notifications working
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203437217658356) by [Unito](https://www.unito.io)
> Make subforum v2 discussion comment links work

- packages/lesswrong/components/tagging/SubforumNotificationSettings.tsx
- packages/lesswrong/components/tagging/TagSubforumPage2.tsx
- packages/lesswrong/lib/collections/userTagRels/collection.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203437367672668) by [Unito](https://www.unito.io)
> [EA] Deploy subforum notification updates and comment permalinks

- packages/lesswrong/components/form-components/TagMultiselect.tsx
- packages/lesswrong/components/search/SearchAutoComplete.tsx
- packages/lesswrong/components/tagging/TagSubforumPage2.tsx
- packages/lesswrong/lib/collections/comments/schema.ts
- packages/lesswrong/lib/collections/tags/helpers.ts
- packages/lesswrong/server/search/algoliaDocuments.d.ts
- packages/lesswrong/server/search/utils.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203440106618250) by [Unito](https://www.unito.io)
> Subforums: Fix some easy bugs

- packages/lesswrong/components/tagging/TagSubforumPage2.tsx
All I've done is moved the SubforumFeed out of a function
This fixes the following bugs:
- comments/posts jump to the top of the feed when you reply to them
- loading new pages is sometimes glitchy
In future we should refactor many of the components in this page out into their own files
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203450626273916) by [Unito](https://www.unito.io)
> Move SubforumFeed out of function to fix bugs

- packages/lesswrong/components/comments/CommentsNode.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/components/vulcan-core/App.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203454608308828) by [Unito](https://www.unito.io)
> Fix comment-permalink updating after within-page navigation with a notification

- packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203461153803083) by [Unito](https://www.unito.io)
> Usernames in side-comments can't wrap

- .github/actions/runMigrations/action.yaml
- .github/workflows/deployEADev.yaml
- .github/workflows/deployEAProd.yaml
- .github/workflows/deployEAStagingPG.yaml
- migrate.js
- scripts/runProduction.sh
Take 2 of running migrations on deploy, this time using Github actions as discussed.
Relevant action run on staging: [https://github.com/ForumMagnum/ForumMagnum/actions/runs/3582644305/jobs/6027110834](https://github.com/ForumMagnum/ForumMagnum/actions/runs/3582644305/jobs/6027110834)
Also, TIL that if you put "github" in a branch name, it will automatically be capitalized as "GitHub" when you create a pull request.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203464678405979) by [Unito](https://www.unito.io)
> PG migrations in GitHub action

- packages/lesswrong/lib/sql/CreateIndexQuery.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203466384738688) by [Unito](https://www.unito.io)
> Use GIN indexes for array fields

- packages/lesswrong/components/comments/CommentsListSection.tsx
- packages/lesswrong/components/comments/CommentsNewForm.tsx
- packages/lesswrong/components/comments/ModerationGuidelines/EAModerationGuidelinesContent.ts
- packages/lesswrong/components/comments/ModerationGuidelines/ModerationGuidelinesBox.tsx
- packages/lesswrong/components/comments/ModerationGuidelines/ModerationGuidelinesEditForm.tsx
- packages/lesswrong/components/tagging/TagDiscussionSection.tsx
- packages/lesswrong/components/tagging/TagSubforumPage2.tsx
- packages/lesswrong/lib/collections/tags/collection.ts
- packages/lesswrong/lib/collections/tags/formGroups.ts
- packages/lesswrong/lib/collections/tags/fragments.ts
- packages/lesswrong/lib/collections/tags/helpers.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/server/resolvers/tagResolvers.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203465623979622) by [Unito](https://www.unito.io)
> Add moderation guidelines to subforum

- packages/lesswrong/lib/utils/truncateTagDescription.ts
Fixes [this bug in Asana](https://app.asana.com/0/628521446211730/1203114337013322/f) that was annoying me whilst working on subforums.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203465590432588) by [Unito](https://www.unito.io)
> Fix SSR for tag truncation

- packages/lesswrong/server/scripts/migrateCollections.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203466703935777) by [Unito](https://www.unito.io)
> Save legacy data during PG migrations

- packages/lesswrong/components/comments/PopupCommentEditor.tsx
- packages/lesswrong/components/common/Home2.tsx
- packages/lesswrong/components/review/FrontpageReviewWidget.tsx
- packages/lesswrong/components/review/PostsItemReviewVote.tsx
- packages/lesswrong/components/review/ReviewVoteTableRow.tsx
- packages/lesswrong/components/review/ReviewVotingPage.tsx
- packages/lesswrong/components/review/ReviewVotingWidget.tsx
- packages/lesswrong/lib/collections/posts/schema.tsx
- packages/lesswrong/lib/reviewUtils.tsx
- packages/lesswrong/lib/routes.ts
Updates Review code to work in 2021
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203442438933980) by [Unito](https://www.unito.io)
> Cleanup Review Code

- packages/lesswrong/integrationTests/notificationCallbacks.tests.ts
- packages/lesswrong/server/notificationCallbacks.tsx
There was some weirdness with the diffs in https://github.com/ForumMagnum/ForumMagnum/pull/6209, so recreating the PR in a fresh branch descended from master.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203470048225435) by [Unito](https://www.unito.io)
> Fix review nomination notifications

- packages/lesswrong/lib/collections/books/collection.ts
- packages/lesswrong/lib/collections/chapters/collection.ts
- packages/lesswrong/lib/collections/collections/collection.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203472506455597) by [Unito](https://www.unito.io)
> EA PG books migration part 2 (2)

- packages/lesswrong/lib/collections/books/collection.ts
- packages/lesswrong/lib/collections/chapters/collection.ts
- packages/lesswrong/lib/collections/collections/collection.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203472646511439) by [Unito](https://www.unito.io)
> Temporary postgres revert

- packages/lesswrong/lib/collections/books/collection.ts
- packages/lesswrong/lib/collections/chapters/collection.ts
- packages/lesswrong/lib/collections/collections/collection.ts
This reverts commit ed5c084e3a0ca4d56218e7097fc758f07f2db364, reversing changes made to 9738f0c195c79c1491f25a5680c4015b8b3e03f7.
> Revert "Merge pull request #6219 from ForumMagnum/pg-temp-revert"

- packages/lesswrong/components/posts/PostsAcceptTos.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203476007974372) by [Unito](https://www.unito.io)
> Make TOS message un-clickable

- packages/lesswrong/components/review/PostsItemReviewVote.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203470422980931) by [Unito](https://www.unito.io)
> Fix label and improve styling on PostsItem vote

- packages/lesswrong/components/review/FrontpageReviewWidget.tsx
- packages/lesswrong/components/review/LatestReview.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203470018349585) by [Unito](https://www.unito.io)
> Tweak style of the LatestReview component

- packages/lesswrong/server/callbacks/postCallbacks.ts
- packages/lesswrong/server/fmCrosspost/resolvers.ts
Users are currently presented with an unhelpful `Failed to create crosspost` error when their attempt to crosspost fails because of the new ToS requirement.  This isn't a proper fix but at least makes it clear what the user needs to do to fix the issue.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203478200468118) by [Unito](https://www.unito.io)
> surface legible error for TOS requirement causing crosspost failures from LW

- packages/lesswrong/lib/collections/comments/schema.ts
- packages/lesswrong/lib/voting/votingSystems.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203481484985660) by [Unito](https://www.unito.io)
> [EA] Deploy agreement voting fix for subforums

- packages/lesswrong/lib/betas.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203483482485273) by [Unito](https://www.unito.io)
> Un-beta-gate side comments (on LW)

- packages/lesswrong/components/ea-forum/users/EAGApplicationImportForm.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203484571758226) by [Unito](https://www.unito.io)
> [EA Forum only] fix error when typing in EAG application import form

- packages/lesswrong/components/ea-forum/TargetedJobAdSection.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203484710802225) by [Unito](https://www.unito.io)
> [EA Forum only] fix new job ad test for users who saw the prev job ad test

- packages/lesswrong/lib/collections/advisorRequests/collection.ts
- packages/lesswrong/lib/collections/bans/collection.ts
- packages/lesswrong/lib/collections/emailTokens/collection.ts
- packages/lesswrong/lib/collections/featuredResources/collection.ts
- packages/lesswrong/lib/collections/gardencodes/collection.ts
- packages/lesswrong/lib/collections/legacyData/collection.ts
- packages/lesswrong/lib/collections/migrations/collection.ts
- packages/lesswrong/lib/collections/moderationTemplates/collection.ts
- packages/lesswrong/lib/collections/petrovDayLaunchs/collection.ts
- packages/lesswrong/lib/collections/podcastEpisodes/collection.ts
- packages/lesswrong/lib/collections/podcasts/collection.ts
- packages/lesswrong/lib/collections/reports/collection.ts
- packages/lesswrong/lib/collections/rssfeeds/collection.ts
- packages/lesswrong/lib/collections/spotlights/collection.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203481386855037) by [Unito](https://www.unito.io)
> EA PG Migrate Trivial Collections (Part 2)

- packages/lesswrong/components/common/HomeLatestPosts.tsx
Adds curated to Latest Posts during the review.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203512486818311) by [Unito](https://www.unito.io)
> Add curated to latest posts

- packages/lesswrong/components/tagging/TagSubforumPage2.tsx
The latest in my quest to make people understand what "New Thread" does
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203496150093799) by [Unito](https://www.unito.io)
> Add tooltips to subforum buttons

- .github/actions/runMigrations/action.yaml
- .github/workflows/deployEADev.yaml
- .github/workflows/deployEAProd.yaml
- build.js
- jest.config.ts
- migrate.js
- package.json
- packages/lesswrong/lib/executionEnvironment.ts
- packages/lesswrong/server/ckEditor/ckEditorWebhook.ts
- packages/lesswrong/server/ckEditor/postEditorConfig.ts
- packages/lesswrong/server/commandLine.ts
- packages/lesswrong/server/migrations/20221207T030042.books_toc_title.ts
- packages/lesswrong/server/migrations/meta/utils.ts
- packages/lesswrong/server/runServer.ts
- packages/lesswrong/server/serverStartup.ts
Fixes the current issues with migrations to allow us to deploy to EA Forum staging/prod. This is currently EA Forum specific - more work will be needed here when LW migrate to Postgres, but I haven't got enough context on how their site is configured to forward-plan right now.
Relevant action run: [https://github.com/ForumMagnum/ForumMagnum/actions/runs/3679091431/jobs/6223129735](https://github.com/ForumMagnum/ForumMagnum/actions/runs/3679091431/jobs/6223129735)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203537562919586) by [Unito](https://www.unito.io)
> Fix EA Forum Deployments

- packages/lesswrong/lib/collections/clientIds/collection.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203518940330942) by [Unito](https://www.unito.io)
> Set ClientIds collectionType to pg

- packages/lesswrong/server/repos/AbstractRepo.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203549682598688) by [Unito](https://www.unito.io)
> Allow the SQL client to be null on LessWrong

- packages/lesswrong/unitTests/sql/AddFieldQuery.tests.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203549828721338) by [Unito](https://www.unito.io)
> Unit tests for AddFieldQuery

- packages/lesswrong/lib/collections/comments/voting.ts
- packages/lesswrong/lib/collections/tagRels/collection.ts
- packages/lesswrong/lib/make_voteable.ts
- packages/lesswrong/lib/voting/tagRelVoteRules.tsx
- packages/lesswrong/server/votingGraphQL.ts
To alleviate confusion about why users' votes are failing
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203496737758797) by [Unito](https://www.unito.io)
> Better error messages on voting failure

- .github/workflows/deployLWDevel.yaml
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203557191634853) by [Unito](https://www.unito.io)
> deploy lessestwrong on merge to master

- migrate.js
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203571919571731) by [Unito](https://www.unito.io)
> Set the SQL client to use the migration transaction

- packages/lesswrong/server/callbacks/sequenceCallbacks.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203571986437316) by [Unito](https://www.unito.io)
> New sequence hotfix

- packages/lesswrong/components/icons/giveIcon.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203572320889409) by [Unito](https://www.unito.io)
> Fix effective giving icon in light mode

- packages/lesswrong/components/icons/giveIcon.tsx
- public/lesswrong-editor/yarn.lock
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203572350488287) by [Unito](https://www.unito.io)
> [EA] deploy effective giving icon fix

- packages/lesswrong/lib/sql/Query.ts
- packages/lesswrong/unitTests/sql/SelectQuery.tests.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203580007869850) by [Unito](https://www.unito.io)
> Fix array queries that search inside a field

- packages/lesswrong/lib/sql/Query.ts
- packages/lesswrong/unitTests/sql/SelectQuery.tests.ts
- scripts/runProduction.sh
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203580097456513) by [Unito](https://www.unito.io)
> [EA] deploy array queries hotfix

- packages/lesswrong/components/tagging/TagSubforumPage2.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203581623658677) by [Unito](https://www.unito.io)
> [EA] Avoid double top padding in welcome box of subforums

- packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
Removing 3 jobs that have closed from the ad rotation
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203581865976867) by [Unito](https://www.unito.io)
> [EA Forum only] remove closed job ads

- packages/lesswrong/components/editor/Editor.tsx
- packages/lesswrong/components/editor/PostSharingSettings.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203584140331490) by [Unito](https://www.unito.io)
> Make editor sharing error forum specific

- packages/lesswrong/components/common/SubscribeDialog.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203588818286958) by [Unito](https://www.unito.io)
> Fix RSS dialog styling in dark mode

- packages/lesswrong/lib/collections/posts/fragments.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203591288705274) by [Unito](https://www.unito.io)
> Fix stale version shown after edit-post submission saving as draft

- packages/lesswrong/lib/SwitchingCollection.ts
- packages/lesswrong/lib/collections/commentModeratorActions/collection.ts
- packages/lesswrong/lib/collections/comments/collection.ts
- packages/lesswrong/lib/collections/postRelations/collection.ts
- packages/lesswrong/lib/collections/posts/collection.ts
- packages/lesswrong/lib/collections/readStatus/collection.ts
- packages/lesswrong/lib/collections/revisions/collection.ts
- packages/lesswrong/lib/collections/tagFlags/collection.ts
- packages/lesswrong/lib/collections/tagRels/collection.ts
- packages/lesswrong/lib/collections/tags/collection.ts
- packages/lesswrong/lib/collections/tags/views.ts
- packages/lesswrong/lib/collections/userTagRels/collection.ts
- packages/lesswrong/lib/collections/votes/collection.ts
- packages/lesswrong/lib/mongoCollection.ts
- packages/lesswrong/lib/scoring.ts
- packages/lesswrong/lib/sql/PgCollection.ts
- packages/lesswrong/lib/sql/Query.ts
- packages/lesswrong/lib/sql/Table.ts
- packages/lesswrong/lib/sql/tests/testingSqlClient.ts
- packages/lesswrong/server/karmaChanges.ts
- packages/lesswrong/server/migrations/20221220T125246.fix_index_uniqueness.ts
- packages/lesswrong/server/migrations/meta/utils.ts
- packages/lesswrong/server/repos/VotesRepo.ts
- packages/lesswrong/server/repos/index.ts
- packages/lesswrong/server/updateScores.ts
- packages/lesswrong/unitTests/sql/SelectQuery.tests.ts
- packages/lesswrong/unitTests/switchingCollection.tests.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203584092660152) by [Unito](https://www.unito.io)
> EA Forum: Migrate posts to Postgres - Part 1

- packages/lesswrong/lib/collections/clientIds/collection.ts
- packages/lesswrong/lib/sql/tests/testingSqlClient.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203584141809235) by [Unito](https://www.unito.io)
> Switching ClientIds collectionType to PG - for real this time

- packages/lesswrong/lib/collectionIndexUtils.ts
- packages/lesswrong/lib/collections/posts/views.ts
- packages/lesswrong/lib/sql/PgCollection.ts
- packages/lesswrong/lib/sql/Table.ts
- packages/lesswrong/lib/sql/TableIndex.ts
- packages/lesswrong/lib/sql/tests/testHelpers.ts
- packages/lesswrong/lib/sql/tests/testingSqlClient.ts
- packages/lesswrong/lib/types/collectionTypes.ts
- packages/lesswrong/unitTests/sql/TableIndex.tests.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203596192377008) by [Unito](https://www.unito.io)
> Fix creation of Postgres indexes with custom names

- packages/lesswrong/components/tagging/RightSidebarColumn.tsx
- packages/lesswrong/components/tagging/TagSubforumPage2.tsx
- packages/lesswrong/components/tagging/subforums/SubforumIntroBox.tsx
- packages/lesswrong/lib/components.ts
As per design here: https://www.figma.com/file/lYIUu1lWDFpjJKp4nLqny7/EA-Forum-Prototypes-2?node-id=1894%3A526&t=0zLXZeU3QBUQnmZE-0
The only thing I've changed is using a cross icon instead of "dismiss" to dismiss it
> Add subforum intro box

- packages/lesswrong/components/posts/PostsItemComments.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203575607701498) by [Unito](https://www.unito.io)
> Fix misaligned comment icons in all-posts page shortform

- packages/lesswrong/components/editor/EditorTopBar.tsx
Co-Authored-By: Sarah Cheng <sarah.cheng@centreforeffectivealtruism.com>
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203572123120915) by [Unito](https://www.unito.io)
> Editor top bar mode dropdown allows you to use admin powers

- packages/lesswrong/server/migrations/20221224T171407.add_comment_title.ts
- schema/accepted_schema.sql
- schema/schema_changelog.json
This [deployment](https://github.com/ForumMagnum/ForumMagnum/actions/runs/3772175613) was failing because the migrations were out of order. Going to force merge this to get it working again
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203610136291994) by [Unito](https://www.unito.io)
> Reorder migrations

- packages/lesswrong/lib/collections/userTagRels/collection.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203614278567730) by [Unito](https://www.unito.io)
> small fix for subforum notification text

- packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
- packages/lesswrong/components/ea-forum/TargetedJobAdSection.tsx
- packages/lesswrong/lib/collections/userTagRels/collection.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203618907389416) by [Unito](https://www.unito.io)
> [EA] deploy updated job ads list

- packages/lesswrong/lib/sql/PgCollection.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203625937570861) by [Unito](https://www.unito.io)
> Show trace when reporting a slow Postgres query

- packages/lesswrong/lib/sql/Query.ts
- packages/lesswrong/unitTests/sql/SelectQuery.tests.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203626243979495) by [Unito](https://www.unito.io)
> Better array search sql

- packages/lesswrong/lib/sql/Query.ts
- packages/lesswrong/unitTests/sql/SelectQuery.tests.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203626346670578) by [Unito](https://www.unito.io)
> Fix incorrect syntax

- packages/lesswrong/lib/sql/Query.ts
- packages/lesswrong/unitTests/sql/SelectQuery.tests.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203626571586138) by [Unito](https://www.unito.io)
> [EA] deploy fix for $in comparisons with an empty array

- packages/lesswrong/components/ea-forum/EAForumWrappedPage.tsx
Adds analytics contexts to interactive sections of the forum wrapped page.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203627307638115) by [Unito](https://www.unito.io)
> Wrapped page analytics

- packages/lesswrong/lib/sql/UpdateQuery.ts
- packages/lesswrong/unitTests/sql/UpdateQuery.tests.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203629510899397) by [Unito](https://www.unito.io)
> Fix incrementing null values

- packages/lesswrong/server/repos/VotesRepo.ts
Co-authored-by: Jim Babcock <jim@jimrandomh.org>
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203631058420083) by [Unito](https://www.unito.io)
> Fix karma changes group by clause

- .github/actions/runMigrations/action.yaml
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203631422695166) by [Unito](https://www.unito.io)
> Migration CI fix

- packages/lesswrong/server/migrations/meta/PgStorage.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203631302403717) by [Unito](https://www.unito.io)
> Exclude 'downed' migrations from the list of executed migrations

- packages/lesswrong/components/posts/PostsItem2.tsx
- packages/lesswrong/server/resolvers/userResolvers.ts
1. Post item no longer expands too wide
2. Comments on other users' shortforms don't count in your own shortforms count
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203631482820078) by [Unito](https://www.unito.io)
> fix postitem width for Wrapped

- .github/workflows/cypress.yaml
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203641433123082) by [Unito](https://www.unito.io)
> Skip cypress tests (hopefully temporarily)

- packages/lesswrong/components/tagging/FooterTag.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203654940584177) by [Unito](https://www.unito.io)
> Add missing styling to auto-applied tag robot icon

- packages/lesswrong/components/comments/CommentsItem/CommentsItemDate.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203648672495878) by [Unito](https://www.unito.io)
> Fix frontpage subforum comment links

- packages/lesswrong/server/serverStartup.ts
- scripts/serverShellCommand.sh
Co-authored-by: Jim Babcock <jim@jimrandomh.org>
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203631186654688) by [Unito](https://www.unito.io)
> Fix --wait for serverShellCommand

- packages/lesswrong/lib/collections/images/collection.ts
- packages/lesswrong/lib/collections/localgroups/collection.ts
- packages/lesswrong/lib/collections/moderatorActions/collection.ts
- packages/lesswrong/lib/collections/reviewVotes/collection.ts
- packages/lesswrong/lib/collections/sequences/views.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203674741561905) by [Unito](https://www.unito.io)
> Pg updates and fixes

- packages/lesswrong/lib/sql/Query.ts
- packages/lesswrong/unitTests/sql/SelectQuery.tests.ts
This PR enables us to migrate Conversations and Messages to Postgres. Once this is done, the only remaining collections will be the 4 problematic ones: LWEvents, DebouncerEvents, DatabaseMetadata and Users.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203695212113553) by [Unito](https://www.unito.io)
> PG Fixes for messages

- packages/lesswrong/components/events/modules/VirtualProgramCard.tsx
Updates the VP deadline and start dates to match what's [here](https://www.effectivealtruism.org/virtual-programs), also update the logic to more closely match what the program uses for their dates.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203667707273338) by [Unito](https://www.unito.io)
> [EA Forum only] update virtual program dates

- packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
- packages/lesswrong/components/ea-forum/TargetedJobAdSection.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203669145451192) by [Unito](https://www.unito.io)
> [EA Forum only] add two more job ads

- packages/lesswrong/components/ea-forum/TargetedJobAdSection.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203696137581131) by [Unito](https://www.unito.io)
> fix small job ad bug

- build.js
- packages/lesswrong/client/autoRefresh.ts
- packages/lesswrong/server/apolloServer.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203609408702343) by [Unito](https://www.unito.io)
> Improve the reliability of auto-refresh in development

- packages/lesswrong/lib/sql/PgCollection.ts
This is already fixed in https://github.com/ForumMagnum/ForumMagnum/pull/6443 but I'm putting it in it's own PR so it isn't blocked by the rest of that one
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203705227177309) by [Unito](https://www.unito.io)
> Fix postgres count bug

- packages/lesswrong/server/manualMigrations/2023-01-10-revertSubforumNotifSettings.ts
- packages/lesswrong/server/manualMigrations/index.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203695807939027) by [Unito](https://www.unito.io)
> Turn subforum notifications off for users who had them enabled automatically

- packages/lesswrong/components/posts/PostsAnalyticsPage.tsx
This is a stopgap until we make analytics fast
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203706083082411) by [Unito](https://www.unito.io)
> Update PostsAnalyticsPage.tsx to tell users to reload if they get an error

- packages/lesswrong/server/recommendations.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203713447983651) by [Unito](https://www.unito.io)
> Exclude read posts from recommendations

- packages/lesswrong/components/review/FrontpageReviewWidget.tsx
- packages/lesswrong/components/review/NewLongformReviewForm.tsx
- packages/lesswrong/components/review/ReviewDashboardButtons.tsx
- packages/lesswrong/components/review/ReviewPhaseInformation.tsx
- packages/lesswrong/components/review/ReviewQuickPage.tsx
- packages/lesswrong/components/review/ReviewVotingPage.tsx
- packages/lesswrong/components/review/UserReviewsProgressBar.tsx
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/routes.ts
So... I just wanted to add a button for writing a "longform review", which is basically just a post. But this turned out to be kinda straw-breaks-camels-back for Review UI complexity. I rearranged some things. Here is the resulting screenshots:
Advanced Dashboard:
Frontpage:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203718116377753) by [Unito](https://www.unito.io)
> Longform Review

- packages/lesswrong/components/tagging/subforums/SubforumSubforumTab.tsx
- packages/lesswrong/components/tagging/subforums/SubforumWikiTab.tsx
- packages/lesswrong/components/tagging/subforums/TagSubforumPage2.tsx
- packages/lesswrong/lib/collections/tags/helpers.ts
- packages/lesswrong/lib/components.ts
This PR is mainly splitting out the wiki and subforum tabs into separate components
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203663485332186) by [Unito](https://www.unito.io)
> More subforum refactoring

- packages/lesswrong/lib/collections/conversations/collection.ts
- packages/lesswrong/lib/collections/messages/collection.ts
- packages/lesswrong/lib/collections/notifications/collection.ts
- packages/lesswrong/lib/collections/sequences/collection.ts
- packages/lesswrong/lib/collections/subscriptions/collection.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203721247186655) by [Unito](https://www.unito.io)
> Set messages, etc. to 'pg' collection type

- packages/lesswrong/components/notifications/NotificationsItem.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203715259868360) by [Unito](https://www.unito.io)
> Capture notification link click analytics

- packages/lesswrong/lib/collections/comments/views.ts
I failed to test this until staging.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203761032251318) by [Unito](https://www.unito.io)
> Fix unreviewed comment hiding for logged out users

- packages/lesswrong/components/posts/PingbacksList.tsx
- packages/lesswrong/components/review/ReviewPostComments.tsx
- packages/lesswrong/components/review/ReviewQuickPage.tsx
- packages/lesswrong/components/review/ReviewVotingExpandedPost.tsx
– hides the giant clunky "review" form that's secretly a button, since on the Quick Review page people typically click the "review" button on the posts list
– hides empty comment-lists on the ReviewPostComments 
– shows fewer pingbacks by default, so that it's easier to see that a post has recent comments
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203761551220647) by [Unito](https://www.unito.io)
> UI improvements to Quick Review

- packages/lesswrong/components/review/FrontpageReviewWidget.tsx
- packages/lesswrong/components/review/ReviewVotingPage.tsx
- packages/lesswrong/components/review/ReviewsLeaderboard.tsx
- packages/lesswrong/components/review/ReviewsList.tsx
- packages/lesswrong/components/review/ReviewsPage.tsx
- packages/lesswrong/lib/components.ts
- packages/lesswrong/themes/createThemeDefaults.ts
I'd held off on making a Review leaderboard because it required loading all the reviews, which seemed crazy. Then I realized... that's not actually more comments that we often load on post pages.
So, gone ahead and made a leaderboard
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203747486529602) by [Unito](https://www.unito.io)
> Review Leaderboard

- packages/lesswrong/components/review/FrontpageReviewWidget.tsx
- packages/lesswrong/components/review/ReviewPostComments.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203762836568321) by [Unito](https://www.unito.io)
> Fix placeholder reviews in voting phase

- packages/lesswrong/components/users/NewUserCompleteProfile.tsx
Per Lizka and Julia's recommendation.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203769066594796) by [Unito](https://www.unito.io)
> [EA] Help throwaway accounts name themselves

- packages/lesswrong/server/notificationCallbacks.tsx
Fixed whilst pairing with Sarah.
This PR fixes 2 bugs (one from Postgres, and one that was probably preexisting):
- Emails were being sent spuriously due to a comparison between `null` and `undefined`. This is caused by Postgres and it's possible (probable?) that there are more instances of this in the codebase, but there's probably no better way to fix them that just cleaning them up as and when the bugs are found.
- We now compare `googleLocation` instead of `mongoLocation` because the `mongoLocation` is a denormalized field that gets updated before the callback, so the values are always equal.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203774957295612) by [Unito](https://www.unito.io)
> Fix event update emails

- packages/lesswrong/components/tagging/subforums/SubforumSubforumTab.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203782443041740) by [Unito](https://www.unito.io)
> Fix bug where hiding intro post hides all posts

- packages/lesswrong/components/common/NewFeaturePulse.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203785230237642) by [Unito](https://www.unito.io)
> Fix pointer events bug in podcast button

- packages/lesswrong/lib/collections/comments/views.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203778150700454) by [Unito](https://www.unito.io)
> Fix delete-without-trace comments being shown

- packages/lesswrong/components/icons/giftIcon.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203785459387068) by [Unito](https://www.unito.io)
> Fix EA Forum Wrapped icon color in dark mode

- packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203785909622934) by [Unito](https://www.unito.io)
> [EA Forum only] update job ads list

- packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203790877120215) by [Unito](https://www.unito.io)
> [EA Forum only] remove Anthropic job ad

- packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
- packages/lesswrong/components/tagging/TopTagIcon.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203791217823835) by [Unito](https://www.unito.io)
> [EA] deploy job ads update

- packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
Should fix issue where authors are replying to unreviewed comments
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203775079166612) by [Unito](https://www.unito.io)
> Unreviwed comments cannot be replied to

- packages/lesswrong/lib/utils/typeGuardUtils.ts
- packages/lesswrong/themes/themeNames.ts
- packages/lesswrong/themes/themeType.ts
Thanks @b0b3rt for the iterator type code.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203797461451469) by [Unito](https://www.unito.io)
> Apply TupleSet treatment to theme names

- packages/lesswrong/server/voteServer.ts
Fixes a race condition in vote-cancellation, which can lead to the same vote getting double-cancelled, affecting the karma of the user (but not the post/comment) that's being voted on. Experimenting with some console-logs in front of the vote-cancel callback, this is pretty easy to trigger on a development instance with high webserver-to-database latency. It was probably harder, but still possible, to trigger in production.
Requesting @oetherington as reviewer because `findOneAndUpdate` and its atomicity may be a corner case with respect to mongo-to-postgres conversion (the only other place it's used is `debouncerEvents`) and this shouldn't merge until we're sure that operation works correctly. …
> Fix race condition in vote-cancellation

- cypress/e2e/voting/vote_on_post.cy.js
- packages/lesswrong/components/votes/VotingPatternsWarningPopup.tsx
- packages/lesswrong/components/votes/withVote.ts
- packages/lesswrong/integrationTests/tagging.tests.ts
- packages/lesswrong/integrationTests/voting.tests.ts
- packages/lesswrong/lib/collections/moderatorActions/schema.ts
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/server/callbacks/commentCallbacks.ts
- packages/lesswrong/server/callbacks/postCallbacks.ts
- packages/lesswrong/server/callbacks/revisionCallbacks.ts
- packages/lesswrong/server/manualMigrations/2021-05-09-selfVoteOnTagRevisions.ts
- packages/lesswrong/server/tagging/tagCallbacks.ts
- packages/lesswrong/server/tagging/tagsGraphQL.ts
- packages/lesswrong/server/voteServer.ts
- packages/lesswrong/server/votingGraphQL.ts
Users who vote on content by the same user more than ten times in a 3-minute interval will get a popup that looks like this:
This is rate-limited to trigger no more than once per hour. This will also add an automod notice to the moderator notes.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203769498070629) by [Unito](https://www.unito.io)
> Users who vote >10x in 3min on the same user get a warning popup

- packages/lesswrong/server.ts
- packages/lesswrong/server/exportUserData.ts
Export user data for GDPR purposes.
Expected usage: `./scripts/serverShellCommand.sh 'Globals.exportUserData({slug: "some-user-slug"}, "userdata.json")'`
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203822273743723) by [Unito](https://www.unito.io)
> Create export user data script

- packages/lesswrong/lib/collections/users/schema.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203837088469722) by [Unito](https://www.unito.io)
> Fix type generation bug in subforumPreferredLayout

- packages/lesswrong/lib/collections/votes/collection.ts
Co-authored-by: jpaddison3 <jp@centreforeffectivealtruism.org>
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203840271939752) by [Unito](https://www.unito.io)
> Tighten permissions on Votes

- packages/lesswrong/components/payments/AdminPaymentsPage.tsx
- packages/lesswrong/lib/collections/users/views.ts
- packages/lesswrong/lib/routes.ts
Makes it so you can filter down the list of names when searching.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203794016409332) by [Unito](https://www.unito.io)
> Add search to admin-payments

- packages/lesswrong/components/review/FrontpageReviewWidget.tsx
- packages/lesswrong/components/review/ReviewPhaseInformation.tsx
- packages/lesswrong/components/review/ReviewVotingPage.tsx
- packages/lesswrong/components/review/ReviewVotingProgressBar.tsx
- packages/lesswrong/components/review/UserReviewsProgressBar.tsx
- packages/lesswrong/lib/components.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203848918662667) by [Unito](https://www.unito.io)
> Voting checkboxes

- packages/lesswrong/components/hooks/useUnreadNotifications.ts
- packages/lesswrong/lib/collections/notifications/views.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203849284316753) by [Unito](https://www.unito.io)
> Fix slow queries against the notifications collection

- packages/lesswrong/components/books/Book2019Animation.tsx
- packages/lesswrong/components/books/BookAnimation.tsx
- packages/lesswrong/components/collections/CollectionsCardContainer.tsx
- packages/lesswrong/components/comments/CommentsListMeta.tsx
- packages/lesswrong/components/common/DefaultStyleFormGroup.tsx
- packages/lesswrong/components/common/LWPopper.tsx
- packages/lesswrong/components/common/LWTooltip.tsx
- packages/lesswrong/components/common/NewFeatureTooltip.tsx
- packages/lesswrong/components/form-components/MuiTextField.tsx
- packages/lesswrong/components/localGroups/LocalGroupsList.tsx
- packages/lesswrong/components/messaging/NewConversationButton.tsx
- packages/lesswrong/components/spotlights/SpotlightEditorStyles.tsx
- packages/lesswrong/components/tagging/AddTagButton.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203848820192914) by [Unito](https://www.unito.io)
> Fix type of children props away from any's and towards ReactNode's

- migrate.js
Save me from myself.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203859348549138) by [Unito](https://www.unito.io)
> Footgun fix: better error message with swapped arguments for migration command

- README.md
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203832677008910) by [Unito](https://www.unito.io)
> Migrations Readme update

- packages/lesswrong/server/scripts/convertImagesToCloudinary.ts
That log might've seemed reasonable if it only fired on post.contents edit, but it turns out it fires for every makeEditable field any every updated object, which is a bit too much. We can turn it back on by enabling a debugger.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203858973200561) by [Unito](https://www.unito.io)
> Reduce image log spam

- cypress/e2e/moderation/ban_user.cy.js
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203865698537271) by [Unito](https://www.unito.io)
> Comment out ban_user cypress test (flaky)

- packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203870405665583) by [Unito](https://www.unito.io)
> [EA Forum only] add final round of job ads

- packages/lesswrong/lib/reviewVoteUpdate.ts
- packages/lesswrong/server.ts
- packages/lesswrong/server/scripts/reviewGetResultsPost.ts
- reviewResultsPost.txt
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203873159955230) by [Unito](https://www.unito.io)
> Best of LessWrong, fix lint issues

- packages/lesswrong/lib/reviewUtils.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203874136439894) by [Unito](https://www.unito.io)
> Hide review widget on EA Forum

- packages/lesswrong/lib/collections/cronHistories/collection.ts
Part 1 in #6522 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203783527574628) by [Unito](https://www.unito.io)
> EA PG CronHistory - Part 2

- packages/lesswrong/lib/collections/cronHistories/collection.ts
This is a redo of #6523 which I merged into the part 1 branch instead of into master 🙃
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203875021109481) by [Unito](https://www.unito.io)
> EA PG CronHistory - Part 2 (2)

- packages/lesswrong/lib/collections/posts/collabEditingPermissions.ts
- packages/lesswrong/lib/collections/posts/helpers.ts
Co-authored-by: s-cheng <sarah.cheng@centreforeffectivealtruism.org>
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203877276768815) by [Unito](https://www.unito.io)
> Coauthors can edit posts

- migrate.js
This whole script is kind of a mess and should probably be rewritten at some point.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203874870201165) by [Unito](https://www.unito.io)
> Fix pending and create modes in migrate script

- packages/lesswrong/components/form-components/FormComponentPostEditorTagging.tsx
- packages/lesswrong/components/tagging/TagSearchHit.tsx
- packages/lesswrong/lib/collections/tags/permissions.ts
Missed change that should've been in #6581
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203920005289770) by [Unito](https://www.unito.io)
> Hide community tag in Post Topics section

- packages/lesswrong/lib/collections/tags/subforumHelpers.ts
Per request from @SharangP, we are changing the default layout here until we have the improved the card view UI.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203942456431723) by [Unito](https://www.unito.io)
> change default subforum layout

- packages/lesswrong/lib/collections/sessions/collection.ts
Part 1 is in #6636.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203895085337469) by [Unito](https://www.unito.io)
> EA PG Session - Part 2

- packages/lesswrong/lib/collections/databaseMetadata/collection.ts
Part 1 in #6645 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203912813821182) by [Unito](https://www.unito.io)
> EA PG DatabaseMetadata - Part 2

- cypress/plugins/index.js
- packages/lesswrong/lib/collections/users/collection.ts
- packages/lesswrong/server/createTestingPgDb.ts
Part 1 in #6497.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203757628446289) by [Unito](https://www.unito.io)
> EA PG Users Part 2

- packages/lesswrong/components/common/TabNavigationMenu/SubforumsList.tsx
There was a limit of 10 being applied somewhere 😞
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203971680486583) by [Unito](https://www.unito.io)
> Load more core topics in sidebar

- packages/lesswrong/components/search/SearchPageTabbed.tsx
- packages/lesswrong/server/scripts/algoliaConfigureIndexes.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203962774367414) by [Unito](https://www.unito.io)
> Remove isSubforum search filter and add Core filter

- packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203980191298528) by [Unito](https://www.unito.io)
> [EA Forum only] remove Alvea job ad

- packages/lesswrong/components/search/SearchPageTabbed.tsx
- packages/lesswrong/server/scripts/algoliaConfigureIndexes.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203980453705582) by [Unito](https://www.unito.io)
> [EA] deploy removing Alvea job ad

- packages/lesswrong/components/comments/CommentOnSelection.tsx
- packages/lesswrong/components/comments/CommentsItem/CommentsItemDate.tsx
- packages/lesswrong/components/form-components/FormComponentPostEditorTagging.tsx
- packages/lesswrong/components/posts/PostSubmit.tsx
- packages/lesswrong/components/posts/PostsNewForm.tsx
- packages/lesswrong/components/posts/PostsPage/PostBody.tsx
- packages/lesswrong/components/posts/SubmitToFrontpageCheckbox.tsx
- packages/lesswrong/components/search/SearchPageTabbed.tsx
- packages/lesswrong/components/vulcan-forms/FormGroup.tsx
- packages/lesswrong/lib/betas.ts
- packages/lesswrong/lib/collections/posts/formGroups.ts
- packages/lesswrong/lib/forumTypeUtils.ts
- packages/lesswrong/lib/reactRouterWrapper.tsx
- packages/lesswrong/server/scripts/algoliaConfigureIndexes.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203995898730112) by [Unito](https://www.unito.io)
> [EA] deploy post edit form UI tweaks, fix for event publishing bug

- packages/lesswrong/components/ea-forum/EAHomeCommunityPosts.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204017541496878) by [Unito](https://www.unito.io)
> Show 5 Community posts on the frontpage

- packages/lesswrong/lib/collections/debouncerEvents/collection.ts
Part 1 in #6685 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203968346377923) by [Unito](https://www.unito.io)
> EA PG DebouncerEvents - Part 2

- packages/lesswrong/lib/sql/Query.ts
- packages/lesswrong/unitTests/sql/SelectQuery.tests.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204083346108872) by [Unito](https://www.unito.io)
> Fix event radius query

- packages/lesswrong/components/comments/RecentComments.tsx
- packages/lesswrong/lib/collections/comments/views.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203996026462350) by [Unito](https://www.unito.io)
> Hide comments on drafts from user profile

- packages/lesswrong/lib/collections/posts/views.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204090576844257) by [Unito](https://www.unito.io)
> Prevent events from being shown on the EA Forum frontpage

- packages/lesswrong/lib/collections/lwevents/collection.ts
Part 1 in #6692
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203977285912128) by [Unito](https://www.unito.io)
> EA PG LWEvents Part 2

- packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
- packages/lesswrong/components/ea-forum/TargetedJobAdSection.tsx
Before we wrap up the job ads, we wanted to test a couple jobs that will get shown to everyone who visits the forum, including logged out users. This is the first of those, and we will change this to another one in a couple weeks.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204107933868120) by [Unito](https://www.unito.io)
> [EA Forum only] test untargeted job ad

- README.md
- packages/lesswrong/components/comments/ReplyCommentDialog.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204102463318692) by [Unito](https://www.unito.io)
> Sidecomment titles should be 'New Comment', not post title

- packages/lesswrong/components/editor/Editor.tsx
- packages/lesswrong/components/editor/validation.ts
- packages/lesswrong/lib/pingback.ts
- packages/lesswrong/server/editor/mentions-notify.ts
- packages/lesswrong/themes/defaultPalette.ts
- packages/lesswrong/themes/themeType.ts
Follow-up to https://github.com/ForumMagnum/ForumMagnum/pull/6458
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204017758426122) by [Unito](https://www.unito.io)
> Give feedback to users when the pingback functionality won't work

- packages/lesswrong/components/common/PermanentRedirect.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204110208947611) by [Unito](https://www.unito.io)
> Fix absolute- vs relative-URLs issue with PermanentRedirect component

- packages/lesswrong/components/votes/AgreementVoteAxis.tsx
- packages/lesswrong/components/votes/OverallVoteAxis.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204140889070868) by [Unito](https://www.unito.io)
> Fix hidden karma for agreement votes

- packages/lesswrong/lib/collections/users/schema.ts
- packages/lesswrong/lib/pingback.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204133596478364) by [Unito](https://www.unito.io)
> Fix karma checking for canMention

- packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
- packages/lesswrong/components/ea-forum/TargetedJobAdSection.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204155599641062) by [Unito](https://www.unito.io)
> [EA Forum only] replace job ad

- packages/lesswrong/components/comments/CommentFrame.tsx
- packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
- packages/lesswrong/components/comments/CommentsListSection.tsx
- packages/lesswrong/components/common/LinkCard.tsx
- packages/lesswrong/components/common/TabNavigationMenu/FeaturedResourceBanner.tsx
- packages/lesswrong/components/ea-forum/EAHome.tsx
- packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
- packages/lesswrong/components/ea-forum/users/modules/EAUsersProfileTabbedSection.tsx
- packages/lesswrong/components/events/modules/EventCards.tsx
- packages/lesswrong/components/events/modules/HighlightedEventCard.tsx
- packages/lesswrong/components/events/modules/VirtualProgramCard.tsx
- packages/lesswrong/components/posts/PostsListSettings.tsx
- packages/lesswrong/components/recentDiscussion/RecentDiscussionSubscribeReminder.tsx
- packages/lesswrong/components/recentDiscussion/RecentDiscussionThread.tsx
- packages/lesswrong/components/sequences/CollectionsPage.tsx
- packages/lesswrong/components/sequences/LargeSequencesItem.tsx
- packages/lesswrong/components/sequences/SequencesGridItem.tsx
- packages/lesswrong/components/sequences/SequencesPage.tsx
- packages/lesswrong/components/spotlights/SpotlightItem.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersProfileInfo.tsx
- packages/lesswrong/components/tagging/AllTagsAlphabetical.tsx
- packages/lesswrong/components/tagging/EAAllTagsPage.tsx
- packages/lesswrong/components/tagging/TagPage.tsx
- packages/lesswrong/components/tagging/subforums/SubforumWikiTab.tsx
- packages/lesswrong/components/tagging/subforums/TagSubforumPage2.tsx
- packages/lesswrong/components/votes/AgreementVoteAxis.tsx
- packages/lesswrong/components/votes/OverallVoteAxis.tsx
- packages/lesswrong/themes/createThemeDefaults.ts
- packages/lesswrong/themes/siteThemes/eaTheme.ts
- packages/lesswrong/themes/themeType.ts
This PR adds some initial border radiuses around the site (tweaking will probably be necessary).
Home page:
Comments:
All posts:
All topics:
Tag pages:
Library:
Collections page:
Sequences page:
Events page:
User profile:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204105479601164) by [Unito](https://www.unito.io)
> EA Forum Border Radius

- packages/lesswrong/components/recentDiscussion/RecentDiscussionThread.tsx
I was browsing the new beta site, (woo!), and I felt strongly enough about bringing this in line with the rest of the refactor to go ahead and open a PR. I know we have further plans for this component, but in the name of not letting the perfect be the enemy of the good...
Old
New
cc @agnesstenlund
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204196635764351) by [Unito](https://www.unito.io)
> Sans serif titles in recent discussion

- packages/lesswrong/server/datadog/datadogMiddleware.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204203983918728) by [Unito](https://www.unito.io)
> Add IP to datadog traces (to help us find bots)

- packages/lesswrong/components/common/SettingsColumn.tsx
- packages/lesswrong/components/posts/AllPostsPage.tsx
- packages/lesswrong/components/posts/PostsPage/ContentType.tsx
- packages/lesswrong/lib/collections/posts/sortOrderOptions.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204203288274899) by [Unito](https://www.unito.io)
> EA All posts fixes

- packages/lesswrong/components/comments/CommentsListSection.tsx
- packages/lesswrong/components/ea-forum/EAHome.tsx
- packages/lesswrong/components/ea-forum/EAHomeCommunityPosts.tsx
- packages/lesswrong/components/ea-forum/EAHomeMainContent.tsx
- packages/lesswrong/components/form-components/MultiSelectButtons.tsx
- packages/lesswrong/components/posts/PostsHighlight.tsx
- packages/lesswrong/components/posts/PostsItemIcons.tsx
- packages/lesswrong/components/posts/PostsPreviewTooltip.tsx
- packages/lesswrong/components/posts/PostsTitle.tsx
- packages/lesswrong/components/recentDiscussion/RecentDiscussionThread.tsx
- packages/lesswrong/components/tagging/TagPreview.tsx
- packages/lesswrong/components/tagging/TagSmallPostLink.tsx
- packages/lesswrong/themes/siteThemes/eaTheme.ts
_Lighter grey_
_Sentence case_
_Sentence case + sans serif_
_Sans-serif_
_Recent discussion -> Recent comments_
_Community posts -> Posts tagged community_
_Blue icons_
_Preview title sans serif_
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204202884700890) by [Unito](https://www.unito.io)
> UI refactor: small touches

- packages/lesswrong/components/editor/EditTitle.tsx
- packages/lesswrong/components/posts/PostsTitle.tsx
- packages/lesswrong/components/recentDiscussion/RecentDiscussionThread.tsx
- packages/lesswrong/components/tagging/subforums/SubforumListSettings.tsx
- packages/lesswrong/components/tagging/subforums/SubforumSubforumTab.tsx
- packages/lesswrong/components/votes/PostsVote.tsx
- packages/lesswrong/components/vulcan-forms/FormGroup.tsx
A few things:
* Center-align karma vertically
* Font-weight and size for draft posts more like actual mosts
* Font-weight on these sections in the draft post
* Sentence case for collapsed/expanded
> Agnes follow-up UI refactor

- packages/lesswrong/components/sequences/ChaptersItem.tsx
- packages/lesswrong/components/sequences/SequencesPage.tsx
This PR exposes the existing chapter editing UI to the proper users.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204254699363093) by [Unito](https://www.unito.io)
> enable editing sequence chapters

- packages/lesswrong/components/comments/CommentsItem/CommentUserName.tsx
For request from @agnesstenlund
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204294242556571) by [Unito](https://www.unito.io)
> update sprout icon tooltip text

- packages/lesswrong/components/editor/EditTitle.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204303398717829) by [Unito](https://www.unito.io)
> Fix font-size of title on new/edit-post page

- packages/lesswrong/lib/collections/comments/schema.ts
Whoops.  (This only affected question posts.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204312630339307) by [Unito](https://www.unito.io)
> fix bad typing on formProps

- packages/lesswrong/components/common/Header.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204313398156429) by [Unito](https://www.unito.io)
> [Direct to EA-Deploy] Temporarily use a smaller mobile title for 4/1

- packages/lesswrong/components/common/Header.tsx
Reverts ForumMagnum/ForumMagnum#6879
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204315199110338) by [Unito](https://www.unito.io)
> Revert "[Direct to EA-Deploy] Temporarily use a smaller mobile title for 4/1"

- packages/lesswrong/lib/collections/comments/views.ts
- packages/lesswrong/lib/collections/users/views.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204314189796038) by [Unito](https://www.unito.io)
> Some fixes to indexes for mongodb's sake

- packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204330100463223) by [Unito](https://www.unito.io)
> Never skip cache for health check (fix for frontpage algorithm)

- packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
- packages/lesswrong/themes/siteThemes/eaThemeCS.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204330195052766) by [Unito](https://www.unito.io)
> [EA] Deploy fix for frontpage algorithm (health checks don't skip cache)

- packages/lesswrong/server/useractivities/cron.ts
Some rows are being deleted in prod for a reason I don't understand. Adding these logs to try and catch what's going on
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204348103974312) by [Unito](https://www.unito.io)
> Add more error logging to investigate prod bug in frontpage algorithm

- packages/lesswrong/integrationTests/integrationTestSetup.ts
- packages/lesswrong/server/serverStartup.ts
This is a tentative first step on the road to rid ourselves of Mongo.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204338876669805) by [Unito](https://www.unito.io)
> Don't connect to Mongo on the EA Forum

- packages/lesswrong/lib/collections/comments/views.ts
- packages/lesswrong/lib/collections/posts/views.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204357012046353) by [Unito](https://www.unito.io)
> remove index modifications

- packages/lesswrong/components/sunshineDashboard/SunshineReportedItem.tsx
- packages/lesswrong/server/database-import/database_import_new.ts
- packages/lesswrong/server/manualMigrations/2020-08-09-metaToCommunity.ts
- packages/lesswrong/server/scripts/exportPostDetails.ts
- packages/lesswrong/unitTests/mergeSelectors.tests.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204317219372476) by [Unito](https://www.unito.io)
> Fix usages of magic numbers for Posts.status

- packages/lesswrong/lib/collections/posts/schema.tsx
Currently, if you save a draft post with "submit to frontpage" set to true, then edit the draft to set "submit to frontpage" to false, then publish the post, the post will appear on the frontpage.
This happens because the default value for `frontpageDate` is set when the draft is created and is not updated when the post is edited. This means there's also another bug where the `frontpageDate` is actually the date the draft was created, which could be very different to the time it's actually published, which is also fixed by this PR.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204371928904490) by [Unito](https://www.unito.io)
> Fix bug where editing `submitToFrontpage` on drafts doesn't update `frontpageDate`

- packages/lesswrong/components/search/ExpandedCommentsSearchHit.tsx
- packages/lesswrong/components/search/ExpandedPostsSearchHit.tsx
- packages/lesswrong/components/search/ExpandedSequencesSearchHit.tsx
- packages/lesswrong/components/search/ExpandedTagsSearchHit.tsx
- packages/lesswrong/components/search/ExpandedUsersSearchHit.tsx
- packages/lesswrong/components/search/SearchPageTabbed.tsx
- packages/lesswrong/themes/siteThemes/eaTheme.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204347082443986) by [Unito](https://www.unito.io)
> Fix fonts on search page for EA forum

- packages/lesswrong/server/languageModels/modGPT.ts
When ModGPT decides we should intervene on a comment, add a moderation note to the user. Also remove the `displayName` from the PM that it sends, since that matches the copy that Lizka originally suggested anyway.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204394534144315) by [Unito](https://www.unito.io)
> [EA Forum only] ModGPT writes a mod note when it intervenes

- packages/lesswrong/components/seasonal/HomepageMap/acxEvents.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204406650146009) by [Unito](https://www.unito.io)
> Add hungary ACX everywhere meetup pin to map

- packages/lesswrong/lib/collections/advisorRequests/collection.ts
- packages/lesswrong/lib/collections/bans/collection.ts
- packages/lesswrong/lib/collections/emailTokens/collection.ts
- packages/lesswrong/lib/collections/featuredResources/collection.ts
- packages/lesswrong/lib/collections/gardencodes/collection.ts
- packages/lesswrong/lib/collections/legacyData/collection.ts
- packages/lesswrong/lib/collections/moderationTemplates/collection.ts
- packages/lesswrong/lib/collections/petrovDayLaunchs/collection.ts
- packages/lesswrong/lib/collections/podcastEpisodes/collection.ts
- packages/lesswrong/lib/collections/podcasts/collection.ts
- packages/lesswrong/lib/collections/reports/collection.ts
- packages/lesswrong/lib/collections/rssfeeds/collection.ts
- packages/lesswrong/lib/collections/spotlights/collection.ts
Part 2 for https://github.com/ForumMagnum/ForumMagnum/pull/6979
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204427227307250) by [Unito](https://www.unito.io)
> LW migrate trivial collections part2

- packages/lesswrong/components/Layout.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204445372867953) by [Unito](https://www.unito.io)
> hide frontpage acx map

- packages/lesswrong/components/posts/PostsItemMeta.tsx
- packages/lesswrong/components/posts/PostsUserAndCoauthors.tsx
The main PR was #7001 - I merged it into the wrong branch (not for the first time).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204469941655371) by [Unito](https://www.unito.io)
> Add new user sprout icon to posts in recent discussions (2)

- packages/lesswrong/server/resolvers/userResolvers.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204474851259382) by [Unito](https://www.unito.io)
> add arguments field for rateLimitNextAbleToComment

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
I'm adding this gated behind an instance setting so we can test it on staging, and then the beta site
This is what it would look like currently:
This is not necessarily what it will end up looking like, part of the testing is for Type III to fiddle with the styling to make it look better (probably making it smaller). Also this will not appear in production yet
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204487799390015) by [Unito](https://www.unito.io)
> Add type III embed code for testing

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/server/fmCrosspost/resolvers.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204490565162966) by [Unito](https://www.unito.io)
> Merge master into posts-page-recommendations

- packages/lesswrong/components/moderationTemplates/ModerationTemplatesPage.tsx
- packages/lesswrong/lib/collections/moderationTemplates/schema.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204474620911822) by [Unito](https://www.unito.io)
> Filter types on moderation template page

- packages/lesswrong/lib/collections/commentModeratorActions/collection.ts
- packages/lesswrong/lib/collections/comments/collection.ts
- packages/lesswrong/lib/collections/postRelations/collection.ts
- packages/lesswrong/lib/collections/posts/collection.ts
- packages/lesswrong/lib/collections/readStatus/collection.ts
- packages/lesswrong/lib/collections/revisions/collection.ts
- packages/lesswrong/lib/collections/tagFlags/collection.ts
- packages/lesswrong/lib/collections/tagRels/collection.ts
- packages/lesswrong/lib/collections/tags/collection.ts
- packages/lesswrong/lib/collections/userTagRels/collection.ts
- packages/lesswrong/lib/collections/votes/collection.ts
Part 1: https://github.com/ForumMagnum/ForumMagnum/pull/7022
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204491377175253) by [Unito](https://www.unito.io)
> LW migrate posts, etc part 2

- packages/lesswrong/server/resolvers/recentDiscussionFeed.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204486468519715) by [Unito](https://www.unito.io)
> Show community posts with <10 comments in the recent discussions section

- packages/lesswrong/lib/collections/conversations/collection.ts
- packages/lesswrong/lib/collections/images/collection.ts
- packages/lesswrong/lib/collections/localgroups/collection.ts
- packages/lesswrong/lib/collections/messages/collection.ts
- packages/lesswrong/lib/collections/moderatorActions/collection.ts
- packages/lesswrong/lib/collections/notifications/collection.ts
- packages/lesswrong/lib/collections/reviewVotes/collection.ts
- packages/lesswrong/lib/collections/sequences/collection.ts
- packages/lesswrong/lib/collections/subscriptions/collection.ts
- packages/lesswrong/server/scripts/migrateCollections.ts
Corresponding EA forum PR: https://github.com/ForumMagnum/ForumMagnum/pull/6403
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204492451238385) by [Unito](https://www.unito.io)
> LW migrate messages, conversations, groups, seqs, etc

- packages/lesswrong/components/questions/Answer.tsx
Adds a permalink button for answers. This is a regression from the UI redesign.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204491627257819) by [Unito](https://www.unito.io)
> [EA] Add permalink button for answers

- packages/lesswrong/lib/collections/cronHistories/collection.ts
- packages/lesswrong/server/scripts/migrateCollections.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204499009184451) by [Unito](https://www.unito.io)
> Cronhistories migration pt 1

- packages/lesswrong/lib/collections/cronHistories/collection.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204498831387439) by [Unito](https://www.unito.io)
> Switch cronhistories to pg

- packages/lesswrong/server/callbacks/rateLimits.ts
I factored this out from Sarah's request on a previous PR because I didn't want to re-test everything before shipping. 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204474102429517) by [Unito](https://www.unito.io)
> Coauthors aren't affected by rate limits on their coauthored posts

- packages/lesswrong/server/ckEditor/ckEditorCallbacks.ts
Going straight to lw-deploy because master has some rate-limiting stuff we want to test out.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204499278713679) by [Unito](https://www.unito.io)
> don't use addToSet for now

- packages/lesswrong/server/ckEditor/ckEditorCallbacks.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204499285933513) by [Unito](https://www.unito.io)
> change in master as well

- packages/lesswrong/lib/collections/databaseMetadata/collection.ts
- packages/lesswrong/server/scripts/migrateCollections.ts
Corresponding EA forum PR: https://github.com/ForumMagnum/ForumMagnum/pull/6645
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204508875197525) by [Unito](https://www.unito.io)
> lw pg databasemetadata part 1

- packages/lesswrong/lib/collections/conversations/collection.ts
- packages/lesswrong/lib/collections/images/collection.ts
- packages/lesswrong/lib/collections/localgroups/collection.ts
- packages/lesswrong/lib/collections/messages/collection.ts
- packages/lesswrong/lib/collections/moderatorActions/collection.ts
- packages/lesswrong/lib/collections/notifications/collection.ts
- packages/lesswrong/lib/collections/reviewVotes/collection.ts
- packages/lesswrong/lib/collections/sequences/collection.ts
- packages/lesswrong/lib/collections/subscriptions/collection.ts
Part 1 PR: https://github.com/ForumMagnum/ForumMagnum/pull/7065
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204499530972946) by [Unito](https://www.unito.io)
> lw pg messages, notifications, etc part 2

- packages/lesswrong/lib/collections/debouncerEvents/collection.ts
- packages/lesswrong/lib/collections/sessions/collection.ts
- packages/lesswrong/server/manualMigrations/migrationUtils.ts
- packages/lesswrong/server/scripts/migrateCollections.ts
EA Forum PRs:
https://github.com/ForumMagnum/ForumMagnum/pull/6636
https://github.com/ForumMagnum/ForumMagnum/pull/6685
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204509470394864) by [Unito](https://www.unito.io)
> lw pg debouncerevents and sessions part 1

- packages/lesswrong/lib/collections/databaseMetadata/collection.ts
Follow-up to https://github.com/ForumMagnum/ForumMagnum/pull/7084
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204508811918828) by [Unito](https://www.unito.io)
> Lw pg databasemetadata part2

- packages/lesswrong/components/common/CommentsListCondensed.tsx
- packages/lesswrong/components/ea-forum/EAHome.tsx
- packages/lesswrong/components/recentDiscussion/RecentDiscussionFeed.tsx
- packages/lesswrong/components/shortform/ShortformSubmitForm.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204522589816383) by [Unito](https://www.unito.io)
> Rename 'Recent comments' to 'Recent discussion', and move 'New shortform' button to shortform section of the frontpage

- packages/lesswrong/lib/collections/debouncerEvents/collection.ts
- packages/lesswrong/lib/collections/sessions/collection.ts
Part 1 PR: https://github.com/ForumMagnum/ForumMagnum/pull/7086
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204510003806367) by [Unito](https://www.unito.io)
> lw pg debouncerevents sessions part 2

- packages/lesswrong/client/reCaptcha.ts
- packages/lesswrong/components/common/CookieBanner/geolocation.ts
- packages/lesswrong/components/hooks/useCookiesWithConsent.ts
- packages/lesswrong/lib/collections/debouncerEvents/collection.ts
- packages/lesswrong/lib/collections/sessions/collection.ts
- packages/lesswrong/lib/cookies/callbacks.ts
- packages/lesswrong/lib/cookies/cookies.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204539135101459) by [Unito](https://www.unito.io)
> [EA] Deploy preferences cookie expiration date

- packages/lesswrong/server/callbacks/alignment-forum/callbacks.ts
- packages/lesswrong/server/repos/UsersRepo.ts
$pull wasn't implemented
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204566633558396) by [Unito](https://www.unito.io)
> implement query for pull operator used in af logic

- packages/lesswrong/lib/collections/users/schema.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204588243591108) by [Unito](https://www.unito.io)
> Fix typo in lateCareer label

- packages/lesswrong/lib/collections/users/collection.ts
Follow-up to https://github.com/ForumMagnum/ForumMagnum/pull/7091
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204592374137560) by [Unito](https://www.unito.io)
> lw pg users part 2

- packages/lesswrong/client/datadogRum.ts
- packages/lesswrong/components/hooks/useCookiesWithConsent.ts
- packages/lesswrong/lib/cookies/callbacks.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204610317932041) by [Unito](https://www.unito.io)
> [EA] Deploy fix for infinite loop when auto-updating users cookie preferences

- packages/lesswrong/components/posts/PostsPage/PostsPageCrosspostComments.tsx
Changing this based on user feedback
cc @darkruby501 this affects LW too
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204610303889212) by [Unito](https://www.unito.io)
> Make crosspost comment link take you to the comment section

- packages/lesswrong/lib/collections/clientIds/collection.ts
Part 1: https://github.com/ForumMagnum/ForumMagnum/pull/7000
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204623290169785) by [Unito](https://www.unito.io)
> lw pg clientIds part 2

- packages/lesswrong/components/recommendations/PostsPageRecommendationItem.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204628330797967) by [Unito](https://www.unito.io)
> Make it possible to right click recommendations to open in a new tab

- packages/lesswrong/server/recommendations/FeatureStrategy.ts
Sigh
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204653591503766) by [Unito](https://www.unito.io)
> Fix SQL syntax error in recommendations query

- packages/lesswrong/components/votes/NamesAttachedReactionsVoteOnComment.tsx
- packages/lesswrong/components/votes/ReactionIcon.tsx
- packages/lesswrong/components/votes/ReactionsPalette.tsx
- packages/lesswrong/themes/createThemeDefaults.ts
Fix dark-mode issues with reactions. Fix z-index of the reactions footer.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204659450189314) by [Unito](https://www.unito.io)
> Some fixes to the reactions prototype

- packages/lesswrong/components/recommendations/PostsPageRecommendationItem.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204671555576934) by [Unito](https://www.unito.io)
> Fix posts recommendations alignment

- packages/lesswrong/lib/collections/lwevents/collection.ts
Part 1: https://github.com/ForumMagnum/ForumMagnum/pull/7182
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204672214326436) by [Unito](https://www.unito.io)
> lw pg lwevents part 2

- migrate.js
- packages/lesswrong/lib/collections/userMostValuablePosts/collection.ts
- packages/lesswrong/lib/collections/useractivities/collection.ts
- packages/lesswrong/server/useractivities/cron.ts
Part 1 to switch these two collections (though LW doesn't use either, for now).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204680402877497) by [Unito](https://www.unito.io)
> switch useractivities and mostvaluableposts

- packages/lesswrong/server/callbacks/userCallbacks.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204606734728917) by [Unito](https://www.unito.io)
> Make LW welcome message send immediately

- packages/lesswrong/lib/collections/posts/schema.tsx
- packages/lesswrong/lib/voting/namesAttachedReactions.tsx
- packages/lesswrong/lib/voting/votingSystems.tsx
- packages/lesswrong/lib/vulcan-users/permissions.ts
Reverts ForumMagnum/ForumMagnum#7263
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204689265155360) by [Unito](https://www.unito.io)
> Revert "Allow LessWrong users to use react voting system"

- migrate.js
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204718196406419) by [Unito](https://www.unito.io)
> fix migrate file
