ForumMagnum/ForumMagnum

scripts/startup/buildUtil.js

@jimrandomh for later, in case you have a cleaner way of doing this
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204718641762303) by [Unito](https://www.unito.io)

fix build script... again

---

packages/lesswrong/server/voteServer.ts

Current situation in image. Change message to be more specific about vote karma if that's the reason.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204690577737351) by [Unito](https://www.unito.io)

Specific vote error message if you don't have enough karma

---

package.json
packages/lesswrong/server/sqlConnection.ts
yarn.lock

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204738711187553) by [Unito](https://www.unito.io)

Revert switch to pg-native

---

packages/lesswrong/lib/vulcan-core/default_mutations.ts
packages/lesswrong/lib/vulcan-core/default_resolvers.ts
packages/lesswrong/lib/vulcan-lib/callbacks.ts
packages/lesswrong/server/vulcan-lib/mutators.ts

...for maybe causing performance problems.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204753233030574) by [Unito](https://www.unito.io)

disable performance analytics

---

packages/lesswrong/lib/collections/userMostValuablePosts/collection.ts
packages/lesswrong/lib/collections/useractivities/collection.ts

Part 1: https://github.com/ForumMagnum/ForumMagnum/pull/7250
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204680540752169) by [Unito](https://www.unito.io)

lw pg last tables part 2

---

packages/lesswrong/server/updateScores.ts

Since the migration to postgres, LW occasionally becomes unresponsive. In the RDS performance insights section, this corresponds to a period where database queries get delayed for multiple minutes. This corresponds to the `updateScoreInactiveDocuments` cronjob running, which looks at every post (and comment), and updates its `score` field (magic sorting rank) to be a time-decayed version of its `baseScore` field (karma). This cronjob has two variants: one for "active" documents (stuff recent enough that a small amount of time passing has a significant effect on the time delay, recomputed every 30 seconds), and one for everything. This was originally implemented with some hacky mongodb aggregate pipelines, then rewritten as a hacky hybrid of SQL and mongodb query translation.
What happened …

Don't send an 86MB database query to set `inactive=true` on every comment

---

packages/lesswrong/lib/betas.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204769910851169) by [Unito](https://www.unito.io)

Temporary hack to enable elastic on EA forum staging

---

packages/lesswrong/components/messaging/ConversationPage.tsx

Super excited that @jimrandomh made new DMs appear right away, though the instant scroll felt jarring so I made it smooth
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204752572361084) by [Unito](https://www.unito.io)

smooth scroll to bottom of conversation page

---

packages/lesswrong/components/ea-forum/EAHomeMainContent.tsx

Request from Lizka on Slack
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204790500147136) by [Unito](https://www.unito.io)

Reorder EA Forum frontpage tabs

---

packages/lesswrong/components/sunshineDashboard/moderationLog/RejectedCommentsList.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204809798986418) by [Unito](https://www.unito.io)

Truncated comments in the moderation log rejected content section can be expanded

---

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
packages/lesswrong/components/comments/CommentsListSection.tsx
packages/lesswrong/components/comments/CommentsNewForm.tsx
packages/lesswrong/components/comments/DebateCommentsListSection.tsx
packages/lesswrong/components/questions/NewAnswerForm.tsx
packages/lesswrong/components/questions/PostsPageQuestionContent.tsx
packages/lesswrong/integrationTests/moderation.server.tests.ts
packages/lesswrong/lib/collections/comments/collection.ts
packages/lesswrong/lib/collections/users/helpers.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204828548938399) by [Unito](https://www.unito.io)

Fix not being able to reply to shortforms

---

.platform/nginx/nginx.conf

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204836594723024) by [Unito](https://www.unito.io)

Copy proxy settings into /api/notificationEvents in nginx config

---

packages/lesswrong/components/posts/PostsEditBotTips.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204857747000893) by [Unito](https://www.unito.io)

[EA Forum only] update criticism tip card copy

---

packages/lesswrong/components/common/ForumIcon.tsx
packages/lesswrong/components/dropdowns/posts/HideFrontpagePostDropdownItem.tsx
packages/lesswrong/components/dropdowns/posts/PostActions.tsx
packages/lesswrong/components/dropdowns/posts/PostActionsButton.tsx
packages/lesswrong/components/dropdowns/posts/SharePostActions.tsx
packages/lesswrong/components/dropdowns/posts/SharePostSubmenu.tsx
packages/lesswrong/components/ea-forum/users/EAUsersMetaInfo.tsx
packages/lesswrong/components/form-components/PrefixedInput.tsx
packages/lesswrong/components/hooks/useNotifyMe.ts
packages/lesswrong/components/icons/SocialMediaIcon.tsx
packages/lesswrong/components/posts/EAPostsItem.tsx
packages/lesswrong/components/posts/PostsItemTrailingButtons.tsx
packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
packages/lesswrong/components/posts/SharePostButton.tsx
packages/lesswrong/components/users/SocialMediaLink.tsx
packages/lesswrong/lib/components.ts

Add share buttons to the triple-dot menu.
Future work: Make a version where the Share button is top-level instead of inside the triple-dot menu (to be forum-gated to EA Forum, probably).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204846062839895) by [Unito](https://www.unito.io)

Share buttons

---

packages/lesswrong/server/repos/PageCacheRepo.ts
packages/lesswrong/server/utils/bundleUtils.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204858667824087) by [Unito](https://www.unito.io)

DB page cache merges based on server bundle hash, not client bundle hash

---

packages/lesswrong/lib/sql/PgCollection.ts
packages/lesswrong/lib/sql/sqlClient.ts
packages/lesswrong/lib/vulcan-core/default_resolvers.ts
packages/lesswrong/server/commandLine.ts
packages/lesswrong/server/partiallyReadSequences.ts
packages/lesswrong/server/recommendations.ts
packages/lesswrong/server/serverStartup.ts
packages/lesswrong/server/sqlConnection.ts
packages/lesswrong/server/updateScores.ts
packages/lesswrong/server/vulcan-lib/findbyids.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204871123466075) by [Unito](https://www.unito.io)

[EA] Deploy bot site reading from a read replica

---

packages/lesswrong/components/comments/CommentOnSelection.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204837456608195) by [Unito](https://www.unito.io)

Add analytics wrapper to comment-on-selection

---

packages/lesswrong/server/apolloServer.ts

The express-session middleware, with MongoStore providing it a collection to store stuff in, adds a `req.session` field to requests, with fancy accessors/setters. The only thing we actually use this for, however, is redirects that happen on return from an OAuth login. This is a bit sad, since it adds a webserver-to-database round trip to the start of every request. And sometimes, when it decides the expiration time of an entry in the `Sessions` collection needs updating, it adds *three* round trips instead.
Scope this middleware, so it only applies to requests to URLs under `/auth`. This completely removes the performance cost, with (I believe) no loss of functionality. I have tested that this doesn't break OAuth login redirecting back to the correct page for LW/Google login. Before this …

Scope the expressSession middleware to save a DB query roundtrip on each request

---

packages/lesswrong/lib/voting/reactions.tsx

Fixes a few minor typos in the descriptions of reacts.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204893626931211) by [Unito](https://www.unito.io)

Fix react typos

---

packages/lesswrong/client/serverSentEventsClient.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204928007961613) by [Unito](https://www.unito.io)

Slow down reconnect-attempts for server-sent events

---

packages/lesswrong/client/serverSentEventsClient.ts
packages/lesswrong/client/start.tsx
packages/lesswrong/components/hooks/useUnreadNotifications.ts
packages/lesswrong/components/messaging/ConversationPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204929071649114) by [Unito](https://www.unito.io)

Logged-out users don't connect to the server-sent events endpoint for notifications

---

packages/lesswrong/components/common/HomeLatestPosts.tsx
packages/lesswrong/lib/abTests.ts
packages/lesswrong/lib/collections/posts/views.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204923807063817) by [Unito](https://www.unito.io)

[EA] Enable slower frontpage for all logged in users

---

packages/lesswrong/components/common/HeadTags.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204960189904595) by [Unito](https://www.unito.io)

Fix crash on the 404 page.

---

packages/lesswrong/components/common/HeadTags.tsx
packages/lesswrong/server/vulcan-lib/apollo-ssr/renderUtil.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204962763583838) by [Unito](https://www.unito.io)

Use `toEmbeddableJson` for structured data

---

packages/lesswrong/components/common/HeadTags.tsx
packages/lesswrong/lib/utils/jsonUtils.ts
packages/lesswrong/server/vulcan-lib/apollo-ssr/renderUtil.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204963612250711) by [Unito](https://www.unito.io)

Move toEmbeddableJson into lib to prevent server import on client

---

packages/lesswrong/components/users/UsersMenu.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204962709072149) by [Unito](https://www.unito.io)

Forum-gate removing shortform in users menu for unreviewed users

---

packages/lesswrong/client/serverSentEventsClient.ts
packages/lesswrong/server/serverSentEvents.ts

Discussed in Slack: https://app.slack.com/client/T3ERD8FQT/C75BWSNBH/thread/C75BWSNBH-1688416046.540989?cdn_fallback=2
Adds a version number to the `/api/notificationEvents` endpoint, so that the server can distinguish requests coming from stale tabs. Adds a `disableServerSentEvents` database setting and a corresponding message-type in the notification events channel, which will cause a client to stop rerequesting entirely. Requests for logged-out users, using the old API version, will be answered slowly rather than quickly, to prevent retries.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204966386723029) by [Unito](https://www.unito.io)

Server-sent events: changes to deal with excess request-rate

---

packages/lesswrong/server/scripts/generateInflationAdjustedKarmaReport.ts

PR merge order left us with a broken import
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204972215166301) by [Unito](https://www.unito.io)

Fix karma inflation import in script

---

packages/lesswrong/lib/collections/users/helpers.tsx

LessWrong doesn't want to show the sprout icon for sufficiently old user accounts even if they don't pass the karma threshold.  (Actual cutoff in that case TBD; putting this PR up mostly to come back to it in the near future.  The logical structure is done, the only bit I expect might change is the actual interval.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204931719303850) by [Unito](https://www.unito.io)

don't show sprout icon for older low-karma users

---

packages/lesswrong/components/comments/CommentsItem/CommentsItemDate.tsx

See related discussion in [slack](https://cea-core.slack.com/archives/C03UWFM43T9/p1688385538798199)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204981260494064) by [Unito](https://www.unito.io)

[EA Forum only] restore the link on the comment date

---

packages/lesswrong/components/posts/TableOfContents/ToCColumn.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205003684049051) by [Unito](https://www.unito.io)

Fix crash in SSR in `shouldHideToggleContentsButton`

---

packages/lesswrong/components/votes/EAEmojisVoteOnComment.tsx
packages/lesswrong/lib/betas.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205096869457275) by [Unito](https://www.unito.io)

Enable EA emoji reacts on non-test servers

---

packages/lesswrong/integrationTests/editorUtils.tests.ts
packages/lesswrong/server/editor/conversionUtils.ts
packages/lesswrong/unitTests/editorUtils.tests.ts

Fixes https://github.com/ForumMagnum/ForumMagnum/issues/7392
I also moved the tests from the integration test file to the unit test file.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205102833023322) by [Unito](https://www.unito.io)

Exclude appendices from word count to improve read-time estimate

---

packages/lesswrong/server/search/elastic/ElasticQuery.ts

When searching on the forum we show a small snippet for each result, highlighting the relevant part of the text that matched the query, however, this is currently broken for advanced queries (ie; queries that use quotes). This is because these searches create nested `bool` queries which breaks elastic's ability to work out what it should be highlighting. We can fix this by just adding in a simple default query to define how to do the highlighting.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205126411187056) by [Unito](https://www.unito.io)

Fix advanced query highlighting for Elasticsearch

---

packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx

Reverts ForumMagnum/ForumMagnum#7554
On account of: https://github.com/ForumMagnum/ForumMagnum/pull/7554#issuecomment-1653385592
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205153419048172) by [Unito](https://www.unito.io)

Revert "fix  three dots menu in post header gets cropped in mobile"

---

packages/lesswrong/server/search/elastic/elasticSettings.ts
packages/lesswrong/server/voteServer.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205156868778028) by [Unito](https://www.unito.io)

Enable Elastic search (server side) for LW

---

packages/lesswrong/components/shortform/NewShortformDialog.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204993494994349) by [Unito](https://www.unito.io)

Un-forum-gate the fix for the Cancel button on the New Shortform dialog not working

---

packages/lesswrong/components/common/SubscribeWidget.tsx
packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205272642447876) by [Unito](https://www.unito.io)

simplify rss nav item

---

packages/lesswrong/components/ea-forum/EABestOfPage.tsx
packages/lesswrong/components/posts/PostsPage/PostsPodcastPlayer.tsx
packages/lesswrong/components/users/UserTooltip.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/routes.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205285774219518) by [Unito](https://www.unito.io)

[EA] Deploy MVP Best Of page

---

packages/lesswrong/server.ts
packages/lesswrong/server/scripts/generativeModels/autoSpotlight.ts

Makes a few changes to the description and art prompts that seem slightly better to me
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205236206314484) by [Unito](https://www.unito.io)

Auto spotlights prompt update

---

packages/lesswrong/lib/routes.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205292347154372) by [Unito](https://www.unito.io)

[EA] Change /bestOf url to /best-of

---

packages/lesswrong/components/ea-forum/EABestOfPage.tsx
packages/lesswrong/lib/routes.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205292700145999) by [Unito](https://www.unito.io)

[EA] Deploy adding document slugs to analytics on best of page

---

packages/lesswrong/components/books/Book2020Animation.tsx
packages/lesswrong/components/books/Book2020FrontpageWidget.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205299231939474) by [Unito](https://www.unito.io)

Fix styling on book mobile display

---

packages/lesswrong/server/resolvers/analyticsResolvers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205347246425260) by [Unito](https://www.unito.io)

Allow non-admins to view post analytics page

---

packages/lesswrong/components/common/TabNavigationMenu/NavigationStandalone.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205353395700802) by [Unito](https://www.unito.io)

Remove frontpage nav footer from EA Forum

---

packages/lesswrong/components/ea-forum/EAHomeCommunityPosts.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205365358024592) by [Unito](https://www.unito.io)

Remove personal blog from community posts by default

---

packages/lesswrong/components/seasonal/HomepageMap/acxEvents.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205368704741350) by [Unito](https://www.unito.io)

update acx event pins

---

packages/lesswrong/server/manualMigrations/2023-08-25-importACXMeetups-23-fall.ts

This updates the most recent migration, which will hopefully be copied as the base for the next ACX Meetups Everywhere
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205370521587995) by [Unito](https://www.unito.io)

Update ACX Migration to have reviewedbyUserId

---

packages/lesswrong/components/users/UsersMenu.tsx
packages/lesswrong/lib/collections/sequences/permissions.ts

This was received favorably by LessWrong on slack, so I'm not forum-gating it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205380443516612) by [Unito](https://www.unito.io)

Lower threshold for telling people they can create sequences

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/Error404.tsx
packages/lesswrong/components/messaging/InboxNavigation.tsx
packages/lesswrong/components/posts/PostsSingleRoute.tsx
packages/lesswrong/lib/vulcan-lib/routes.ts

We were incorrectly trying to access a property of a route that was null in the 404 case.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205400378507653) by [Unito](https://www.unito.io)

[EA] Fix 404 page

---

packages/lesswrong/components/spotlights/SpotlightItem.tsx

I'll be right back I promise
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205424610894936) by [Unito](https://www.unito.io)

Stopgap fix for Firefox SpotlightItem bug, disable application of native image fade

---

packages/lesswrong/components/events/modules/VirtualProgramCard.tsx

Follow up to https://github.com/ForumMagnum/ForumMagnum/pull/7677 - just removing the extra code
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205428596238872) by [Unito](https://www.unito.io)

[EA Forum only] remove the VP dates August exception

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205428840941920) by [Unito](https://www.unito.io)

Dialogues auto-load new dialogue comments for participants

---

packages/lesswrong/components/analytics/AnalyticsGraph.tsx
packages/lesswrong/components/analytics/AuthorAnalyticsPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205437527179485) by [Unito](https://www.unito.io)

clearer titles and minor formatting changes on author stats page

---

packages/lesswrong/components/votes/lwReactions/NamesAttachedReactionsVoteOnComment.tsx

Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205445870625185) by [Unito](https://www.unito.io)

Neaten reacter display

---

packages/lesswrong/server/manualMigrations/2023-08-25-importACXmeetups.ts

WARNING: UNTESTED
This is an exact copy of the migration from spring, with two changes. First, there's new data. Second, I switched from Name/initials/handle to just Name.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205356183469188) by [Unito](https://www.unito.io)

ACX Everywhere 2023-Fall

---

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
packages/lesswrong/components/comments/DebateResponse.tsx

Fixed: 
* useless parentheses
* naming of lwReactStyles
* delete unused analytics snippet
* simplify state hook to not use array since we're already inside of a debateResponse
Thanks Sarah for the feedback!
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205454331872499) by [Unito](https://www.unito.io)

Fix debateResponse sarah comments

---

packages/lesswrong/integrationTests/integrationTestSetup.ts
packages/lesswrong/integrationTests/sessions.tests.ts
packages/lesswrong/integrationTests/voting.tests.ts
packages/lesswrong/server/vendor/ConnectMongo/MongoStore.ts

The goal here is not really to fix all of them in one go, but to fix the most common ones and make it easier to pin down what is happening in the remaining ones.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205297820504110) by [Unito](https://www.unito.io)

Fix (some) flaky tests

---

packages/lesswrong/server/callbacks/conversationCallbacks.ts

Previously if someone left a conversation that was invisible, which could cause confusion, perhaps allowing for malicious use. Now we'll send a DM.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205470029497707) by [Unito](https://www.unito.io)

No sneaky leaving of conversations

---

packages/lesswrong/components/comments/DebateTypingIndicator.tsx
packages/lesswrong/components/posts/PostsPage/PostsPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205513697637941) by [Unito](https://www.unito.io)

only attempt to upsert typing indicators if dialogue participant

---

packages/lesswrong/components/posts/PostsItemIcons.tsx

Tiny fix for consistency.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205512189002412) by [Unito](https://www.unito.io)

fix text in dialogue icon tooltip

---

packages/lesswrong/components/comments/DebateResponse.tsx
packages/lesswrong/components/posts/PostsItemIcons.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205514053865531) by [Unito](https://www.unito.io)

Merge master into LW Deploy (margin-top for dialogueResponses)

---

packages/lesswrong/lib/routes.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205514944503792) by [Unito](https://www.unito.io)

[EA] Show event subtitle on sequences page

---

packages/lesswrong/themes/defaultPalette.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205523473387307) by [Unito](https://www.unito.io)

Change event header gradient for AI pause debate week 

---

packages/lesswrong/components/votes/useVoteColors.ts
packages/lesswrong/components/votes/voteColors.ts
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/themeType.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205518934132409) by [Unito](https://www.unito.io)

Remove green upvotes experiment

---

packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx

Type3 updated their feed URL
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205543607676117) by [Unito](https://www.unito.io)

[EA Forum only] update spotify link

---

packages/lesswrong/themes/defaultPalette.ts

(matching the banner)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205582632587731) by [Unito](https://www.unito.io)

Petrov day colors

---

packages/lesswrong/components/seasonal/petrovDay/PetrovDayPoll.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/routes.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205587664822417) by [Unito](https://www.unito.io)

Petrov Day Poll

---

packages/lesswrong/server/repos/CommentsRepo.ts

We'll probably tweak this more in the future, but this seems better than what we have at the moment.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205584825767239) by [Unito](https://www.unito.io)

Add new popular comments algorithm

---

packages/lesswrong/server/rss.ts

We recently had a request for a tag specific RSS feed. This PR makes this possible by parsing JSON passed in for `filterSettings`. I've not added any UI so this feature isn't at all discoverable, but it is at least possible.
The feed will be accessible with a URL like [https://forum.effectivealtruism.org/feed.xml?view=new&filterSettings={%22tags%22%3A[{%22tagId%22%3A%22QdH9f8TC6G8oGYdgt%22%2C%22tagName%22%3A%22Animal%20Welfare%22%2C%22filterMode%22%3A%22Required%22}]}](https://forum.effectivealtruism.org/feed.xml?view=new&filterSettings={%22tags%22%3A[{%22tagId%22%3A%22QdH9f8TC6G8oGYdgt%22%2C%22tagName%22%3A%22Animal%20Welfare%22%2C%22filterMode%22%3A%22Required%22}]}) (which will give a feed of posts tagged with animal welfare). …

Enable tag-specific RSS feeds on the backend

---

packages/lesswrong/lib/betas.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205437687074788) by [Unito](https://www.unito.io)

Remove beta gate from popular comments section on EA forum

---

packages/lesswrong/lib/collections/tags/schema.ts

Re: change introduced in https://github.com/ForumMagnum/ForumMagnum/pull/7858 seems to have broken tags in some contexts.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205636495175917) by [Unito](https://www.unito.io)

Fix tag recent comments resolver

---

packages/lesswrong/lib/htmlToText.ts
packages/lesswrong/server/tableOfContents.ts

Fixes #7938
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205662664361566) by [Unito](https://www.unito.io)

Fix spurious newlines in social previews of comments

---

packages/lesswrong/components/form-components/CoauthorsListEditor.tsx
packages/lesswrong/components/vulcan-forms/FormGroup.tsx
packages/lesswrong/lib/collections/posts/formGroups.ts
packages/lesswrong/lib/collections/posts/schema.tsx
packages/lesswrong/lib/types/schemaTypes.ts

Posts:
Dialogues:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205671289322408) by [Unito](https://www.unito.io)

Rename coauthors to participants for dialogues. 

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx

Makes a more prominent "subscribe to dialogue updates" button for dialogues
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205671900609608) by [Unito](https://www.unito.io)

Makes a more prominent "subscribe to dialogue updates" button for dialogues

---

packages/lesswrong/components/dialogues/DialoguesList.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205672164657884) by [Unito](https://www.unito.io)

Change link to new "Announcing Dialogues" post

---

packages/lesswrong/components/dialogues/DialoguesList.tsx
packages/lesswrong/components/dialogues/DialoguesPage.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/routes.ts

I made it so the frontpage dialogues 3-list links to an All Dialogues page
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205672067964934) by [Unito](https://www.unito.io)

Dialogues page

---

.github/actions/setupEnvironment/action.yaml

I _think_ this fixes the recent test failures in CI

Manually install node-gyp in CI

---

packages/lesswrong/components/editor/PostSharingSettings.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205679133791410) by [Unito](https://www.unito.io)

Use 'Share' icon for `PostSharingSettings` button

---

packages/lesswrong/components/comments/PopularComment.tsx
packages/lesswrong/components/comments/PopularCommentsList.tsx

Adds analytics contexts to `PopularComment` and `PopularCommentsList` - diff is ugly because of indentation changes.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205649338998788) by [Unito](https://www.unito.io)

Popular comments analytics

---

packages/lesswrong/components/posts/SharePostPopup.tsx
packages/lesswrong/lib/collections/posts/helpers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205711865433092) by [Unito](https://www.unito.io)

Add tracking URL param to posts shared from the share popup

---

packages/lesswrong/components/recentDiscussion/RecentDiscussionFeed.tsx
packages/lesswrong/lib/collections/revisions/fragments.ts
packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts

Hopefully fixes the tag-related issue(s) introduced for LW in https://github.com/ForumMagnum/ForumMagnum/commit/35babfa86383663328eff57cdd63b6a8bcf6646f#diff-35d51f84d332ead5985389880b1c8d87c7790bf2629c45f2d3ce0f01b8b5a400
(Robert note: I'm still somewhat confused about how this didn't break things for the EA forum.)
See https://lworg.slack.com/archives/CJUN2UAFN/p1696288887944959 for earlier discussion.

fix tag fragment issue

---

packages/lesswrong/lib/collections/comments/schema.ts
packages/lesswrong/lib/collections/conversations/schema.ts
packages/lesswrong/lib/collections/localgroups/schema.ts
packages/lesswrong/lib/collections/posts/schema.tsx
packages/lesswrong/lib/collections/tags/schema.ts
packages/lesswrong/lib/collections/users/schema.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205735884195321) by [Unito](https://www.unito.io)

Fix crash in users-list editor

---

packages/lesswrong/components/common/ErrorBoundary.tsx

Exceptions throw in React components are caught by the `ErrorBoundary` component which displays an ugly but functional message:
However, once this happens the message is stored in the `ErrorBoundary` forever which means you can only continue to use the site if you manually refresh the page to clear the React state. This PR changes this so the state is cleared by navigating to a different page, for instance, by clicking the site logo in the top left of the screen or the user profile button in the right.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205690421948814) by [Unito](https://www.unito.io)

Clear the state of `ErrorBoundary` when navigating to a different page

---

packages/lesswrong/server/sqlConnection.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205747219836909) by [Unito](https://www.unito.io)

Cache the vector OID type from Postgres

---

packages/lesswrong/components/ea-forum/EAPostMeta.tsx
packages/lesswrong/components/posts/TruncatedAuthorsList.tsx

Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205738981569676) by [Unito](https://www.unito.io)

Show author list for events in recent discussion

---

packages/lesswrong/components/common/useClickableCell.tsx
packages/lesswrong/components/posts/PostsPage/PostsPage.tsx

Adding a bit more here to help us with post page footer recommendation analytics
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205751003473114) by [Unito](https://www.unito.io)

add more analytics for post page footer recs

---

packages/lesswrong/server/callbacks.ts
packages/lesswrong/server/ckEditor/ckEditorWebhook.ts
packages/lesswrong/server/scripts/nullifyVotes.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205752948760379) by [Unito](https://www.unito.io)

add command to nullify votes by one user on a given target user, optionally within a date range

---

.github/workflows/deployBaserates.yaml
.github/workflows/deployEABeta.yaml
.github/workflows/deployEADev.yaml
.github/workflows/deployEAProd.yaml
.github/workflows/deployLWDevel.yaml

See https://github.com/ForumMagnum/ForumMagnum/pull/8094
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205817985803141) by [Unito](https://www.unito.io)

fix python versions for all workflows

---

packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
packages/lesswrong/components/ea-forum/giving-portal/ElectionCandidate.tsx
packages/lesswrong/components/ea-forum/giving-portal/Timeline.tsx
packages/lesswrong/components/ea-forum/giving-portal/hooks.ts
packages/lesswrong/lib/eaGivingSeason.ts
packages/lesswrong/server/posts/index.ts
packages/lesswrong/server/repos/ElectionCandidatesRepo.ts
packages/lesswrong/server/repos/index.ts
packages/lesswrong/server/tagging/tagCallbacks.ts

Merged #8093 into the wrong branch
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205833609452271) by [Unito](https://www.unito.io)

Election candidate tagged posts

---

packages/lesswrong/components/editor/CKPostEditor.tsx
packages/lesswrong/components/posts/dialogues/DialogueEditorFeedback.tsx
packages/lesswrong/lib/components.ts

New box!
-----
And then when you click on it:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205826244411176) by [Unito](https://www.unito.io)

Simple feedback pinger

---

packages/lesswrong/server/manualMigrations/2023-10-25-widgetizeDialogueMessages.ts

In our migration to widgetize, in testing before deploy we hit issues where ckeditor would not allow creating a new document. Empirically, calling delete twice and sleeping for 10 seconds before creating new document solves it, at least for the ~5 times we tried it.

Fix CkEditor replace document issues

---

packages/lesswrong/components/ea-forum/giving-portal/PreVoteButton.tsx
packages/lesswrong/components/tagging/EAPostsItemTagRelevance.tsx
packages/lesswrong/components/votes/EAReactsSection.tsx
packages/lesswrong/components/votes/EmojiReactionVoteOnComment.tsx
packages/lesswrong/components/votes/ReactBallotVoteOnComment.tsx
packages/lesswrong/components/votes/lwReactions/NamesAttachedReactionsVoteOnComment.tsx
packages/lesswrong/components/votes/votingProps.ts
packages/lesswrong/lib/eaGivingSeason.ts
packages/lesswrong/lib/voting/votingSystems.tsx

Adds a minimum account ago for pre-voting in the donation election (currently set to 2023-10-23).

Donation election pre-voting account age cutoff

---

packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205849115120827) by [Unito](https://www.unito.io)

Hide featured reading section in giving portal

---

packages/lesswrong/components/bookmarks/ReadHistoryTab.tsx
packages/lesswrong/server/resolvers/postResolvers.ts

https://lworg.slack.com/archives/CJUN2UAFN/p1698342627547529?thread_ts=1698342133.785079&cid=CJUN2UAFN
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205856186033350) by [Unito](https://www.unito.io)

fix read history

---

packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
packages/lesswrong/lib/eaGivingSeason.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205861399295022) by [Unito](https://www.unito.io)

Add Donation Election fundraiser link

---

packages/lesswrong/components/ea-forum/giving-portal/DonationOpportunity.tsx
packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
packages/lesswrong/lib/eaGivingSeason.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205861706553146) by [Unito](https://www.unito.io)

[EA] Deploy donation election fundraiser link

---

packages/lesswrong/components/common/HeaderEventSubtitle.tsx
packages/lesswrong/components/ea-forum/EAHomeMainContent.tsx
packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx
packages/lesswrong/components/ea-forum/giving-portal/DonationOpportunity.tsx
packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
packages/lesswrong/components/ea-forum/giving-portal/Timeline.tsx
packages/lesswrong/lib/eaGivingSeason.ts
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/themeType.ts
packages/lesswrong/themes/userThemes/darkMode.ts

[✓ Move topic "Effective giving" + restyle, also add Giving portal to Frontpage RHS](https://app.asana.com/0/1205806305763861/1205853147559158/f)
This PR moves the "Effective giving" topic tab to the front of the list and gives it the giving season colors. It also adds a link to the "Giving portal" to the home page right hand side and makes the resources links a giving season red, and adds a link to it to the site header.Light mode:
- - -
Dark mode:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205857534587803) by [Unito](https://www.unito.io)

Giving portal launch: link to it from the home page RHS and the header, and highlight "Effective giving" topic tab

---

packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx

- Use the same date cutoff as the frontpage (21 days)
- Tweak the algorithm weights to make it more recency biased (it should now be in basically reverse chronological order for the first few, but still downweight things with really low karma)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205862227948684) by [Unito](https://www.unito.io)

Make giving portal post list more recency biased

---

packages/lesswrong/components/ea-forum/giving-portal/DonationOpportunity.tsx
packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
packages/lesswrong/components/ea-forum/giving-portal/ElectionCandidate.tsx
packages/lesswrong/components/ea-forum/giving-portal/ElectionFundCTA.tsx
packages/lesswrong/components/ea-forum/giving-portal/PreVoteButton.tsx
packages/lesswrong/components/ea-forum/giving-portal/Timeline.tsx
packages/lesswrong/lib/eaGivingSeason.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205863372821550) by [Unito](https://www.unito.io)

Add analytics events for giving portal (plus a couple of other small bug fixes)

---

packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205863975323004) by [Unito](https://www.unito.io)

fix link to post in giving portal

---

packages/lesswrong/components/ea-forum/giving-portal/PreVoteButton.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205866211308486) by [Unito](https://www.unito.io)

Hacky attempt to fix pre-voting

---

packages/lesswrong/components/ea-forum/giving-portal/Timeline.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205885620278226) by [Unito](https://www.unito.io)

Fix dates on timeline being off-by-1 in timezones far from GMT

---

packages/lesswrong/components/tagging/EAPostsItemTagRelevance.tsx
packages/lesswrong/components/tagging/PostsItemTagRelevance.tsx
packages/lesswrong/components/tagging/TagRelCard.tsx
packages/lesswrong/components/tagging/TagVoteActivity.tsx
packages/lesswrong/components/votes/AgreementVoteAxis.tsx
packages/lesswrong/components/votes/OverallVoteAxis.tsx
packages/lesswrong/components/votes/PostsVoteDefault.tsx
packages/lesswrong/lib/collections/users/helpers.tsx
packages/lesswrong/server/voteServer.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205855719389451) by [Unito](https://www.unito.io)

reenable voting for low karma users

---

packages/lesswrong/components/users/DialogueMatchingPage.tsx

Oli helped to update optimisticResponse to work with useMulti, which had changed to since writing it before

Fix caching and box updating issue

---

packages/lesswrong/components/users/DialogueMatchingPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205892526245428) by [Unito](https://www.unito.io)

better wording

---

packages/lesswrong/components/users/DialogueMatchingPage.tsx
packages/lesswrong/server/repos/UsersRepo.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205892600715743) by [Unito](https://www.unito.io)

Better wording + replace setTimeOut with a different thing

---

packages/lesswrong/lib/routes.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205892563141420) by [Unito](https://www.unito.io)

Forum-gating Dialogue Matching to only be for LessWrong

---

packages/lesswrong/components/users/DialogueMatchingPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205892818009329) by [Unito](https://www.unito.io)

Fix reveal box default state

---

packages/lesswrong/components/users/DialogueMatchingPage.tsx
packages/lesswrong/lib/routes.ts
packages/lesswrong/server/repos/UsersRepo.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205892832877621) by [Unito](https://www.unito.io)

Forumgating and reveal check default state fix

---

packages/lesswrong/components/common/Header.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205892960638703) by [Unito](https://www.unito.io)

[EA Forum only] giving season header uses useCurrentTime

---

packages/lesswrong/components/common/Header.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205893089086803) by [Unito](https://www.unito.io)

[EA Forum only] giving season homepage banner uses utc

---

packages/lesswrong/server/resolvers/elicitPredictions.ts

Forum gate api call in MakeElicitPrediction

---

packages/lesswrong/components/votes/lwReactions/NamesAttachedReactionsVoteOnComment.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205903308085299) by [Unito](https://www.unito.io)

Fix missing vote buttons on non-inline reacts when there are no inline reacts

---

packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
packages/lesswrong/components/ea-forum/giving-portal/ElectionFundCTA.tsx

* slimmer progress bar
* sharp corners on the right of progress bar
* centered images
**Before**
**After**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205908705940180) by [Unito](https://www.unito.io)

Donate card UI fixes

---

packages/lesswrong/components/dialogues/DialoguesList.tsx

Leaving other code in codebase in case we want to place the box somewhere else
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205919784099487) by [Unito](https://www.unito.io)

remove opt in box from frontpage (it served its time!)

---

packages/lesswrong/components/search/SearchPageTabbed.tsx

Regression from #8108
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205909196568416) by [Unito](https://www.unito.io)

Fix scrolling on search page

---

packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/server/codegen/generateDbTypes.ts
packages/lesswrong/server/resolvers/paginatedResolver.ts

https://lworg.slack.com/archives/C04EEHKHRMF/p1698353914892499
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205856759791275) by [Unito](https://www.unito.io)

filter paginated resolver and better type checking

---

packages/lesswrong/components/ea-forum/giving-portal/GivingSeasonHeader.tsx
packages/lesswrong/lib/eaGivingSeason.ts

┆ Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205944265582325) by [Unito](https://www.unito.io)

Update giving season background image in frontpage banner

---

README.md
package.json
packages/lesswrong/integrationTests/testPreSetup.ts
packages/lesswrong/server/embeddings.ts
packages/lesswrong/server/languageModels/autoTagCallbacks.ts
packages/lesswrong/server/languageModels/languageModelIntegration.ts
packages/lesswrong/server/languageModels/modGPT.ts
packages/lesswrong/server/scripts/generativeModels/generateTaggingPostSets.ts
packages/lesswrong/server/scripts/generativeModels/testModGPTOnComments.ts
packages/lesswrong/server/tagging/tagCallbacks.ts
packages/lesswrong/unitTests/testSetup.ts
yarn.lock

So I can use the cool new toys :)
For this PR I ran the automated migration and then did a bunch of manual cleanup - see instructions [here](https://github.com/openai/openai-node/discussions/217). I only tested ModGPT to make sure that still works (since that one had the most changes) and it does.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205954493853402) by [Unito](https://www.unito.io)

Update to latest version of OpenAI (v4)

---

packages/lesswrong/components/users/DialogueMatchingPage.tsx

Fast follow on some code cleaniness for Robert
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205971982212984) by [Unito](https://www.unito.io)

Cleanup some conditional classes

---

packages/lesswrong/components/dialogues/DialoguesList.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205972952089726) by [Unito](https://www.unito.io)

Fix typo in alignmItems line

---

packages/lesswrong/components/users/DialogueMatchingPage.tsx
packages/lesswrong/server/repos/CommentsRepo.ts
packages/lesswrong/server/resolvers/commentResolvers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205974130075262) by [Unito](https://www.unito.io)

Add recommendation reasons

---

packages/lesswrong/components/dialogues/DialoguesList.tsx
packages/lesswrong/components/users/DialogueMatchingPage.tsx
packages/lesswrong/server/repos/CommentsRepo.ts
packages/lesswrong/server/resolvers/commentResolvers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205974568575387) by [Unito](https://www.unito.io)

Merge master into deploy

---

packages/lesswrong/components/users/DialogueMatchingPage.tsx

Oops, small error in my emoji PR :( It only triggered when you added custom topics

Fix submission failure

---

packages/lesswrong/lib/collections/votes/views.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205981827277560) by [Unito](https://www.unito.io)

Vote History tab on /bookmarks excludes self-votes

---

packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206005099480631) by [Unito](https://www.unito.io)

Use election fund total on frontpage RHS

---

packages/lesswrong/components/bookmarks/BookmarksList.tsx
packages/lesswrong/components/bookmarks/BookmarksPage.tsx
packages/lesswrong/components/bookmarks/BookmarksTab.tsx
packages/lesswrong/components/bookmarks/ReadHistoryTab.tsx
packages/lesswrong/components/bookmarks/VoteHistoryTab.tsx
packages/lesswrong/components/posts/DraftsPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205981716204302) by [Unito](https://www.unito.io)

Empty-list placeholders on Bookmarks page so it doesn't look broken on a new account

---

packages/lesswrong/components/messaging/FriendlyConversationItem.tsx
packages/lesswrong/components/messaging/FriendlyInbox.tsx

**Before**
**After**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206000542596820) by [Unito](https://www.unito.io)

DM page polish 💅 Decreasing font sizes + padding

---

packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206018455298642) by [Unito](https://www.unito.io)

Make 'Donate to the Election Fund' a link in frontpage RHS

---

packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206017851478900) by [Unito](https://www.unito.io)

Disable 'Add candidate' button on the giving portal

---

packages/lesswrong/components/comments/DebateResponse.tsx
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/globalStyles/globalStyles.ts
packages/lesswrong/themes/siteThemes/eaTheme.ts
packages/lesswrong/themes/themeType.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206012727590568) by [Unito](https://www.unito.io)

Add EA forum specific comment colors for dialogues

---

packages/lesswrong/server/emails/renderEmail.tsx
packages/lesswrong/server/emails/sendEmail.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206034816661413) by [Unito](https://www.unito.io)

Don't send emails to deleted users

---

packages/lesswrong/themes/globalStyles/globalStyles.ts

Stray character in https://github.com/ForumMagnum/ForumMagnum/pull/8295 broke dialogue message input display name colors
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206043859875444) by [Unito](https://www.unito.io)

fix dialogue message styling generator function

---

packages/lesswrong/lib/eaGivingSeason.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206046814799231) by [Unito](https://www.unito.io)

Update the giving season banner image post-donation-debate-week

---

packages/lesswrong/components/ea-forum/giving-portal/ElectionCandidate.tsx
packages/lesswrong/components/ea-forum/giving-portal/ElectionCandidatesList.tsx
packages/lesswrong/components/ea-forum/voting-portal/EAVotingPortalAllocateVotesPage.tsx
packages/lesswrong/components/ea-forum/voting-portal/EAVotingPortalComparePage.tsx
packages/lesswrong/components/ea-forum/voting-portal/EAVotingPortalSelectCandidatesPage.tsx
packages/lesswrong/components/ea-forum/voting-portal/EAVotingPortalSubmitPage.tsx
packages/lesswrong/components/ea-forum/voting-portal/ElectionAllocateVote.tsx
packages/lesswrong/lib/components.ts

_Note: this will be against master once https://github.com/ForumMagnum/ForumMagnum/pull/8309 is merged_
See [designs](https://www.figma.com/file/OWruitRTyWpmLJjaT4RedA/Voting-portal?node-id=21%3A14685&mode=dev)
In this PR:
- The main thing is adding the page for allocating votes, this is fairly straightforward, it just stores the vote allocation for each candidate in the `vote` json blob
- I have also added the footer to all the other pages, although I haven't been that careful about making sure all the links are enabled/disabled appropriately. I am going to come back and do that ([ticket](https://app.asana.com/0/725332454915663/1206027764335401/f)) at the end
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206039385100420) by …

[EA] Voting portal allocate votes page

---

packages/lesswrong/server/repos/UsersRepo.ts

This PR achieves two changes:
1. Notify people who have never checked anyone (this was currently failing and the COALESCE addresses it)
2. Notify every one with unseen incoming checks once, even if their incoming checks are old
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206063255234956) by [Unito](https://www.unito.io)

Notify users of incoming checks more effectively

---

packages/lesswrong/lib/notificationTypes.tsx

Small copy change
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206073303166399) by [Unito](https://www.unito.io)

Change incoming checks notification text

---

packages/lesswrong/lib/notificationTypes.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206074664010130) by [Unito](https://www.unito.io)

Clarify not a match

---

packages/lesswrong/components/ea-forum/voting-portal/EAVotingPortalComparePage.tsx
packages/lesswrong/components/ea-forum/voting-portal/EAVotingPortalSelectCandidatesPage.tsx
packages/lesswrong/components/ea-forum/voting-portal/EAVotingPortalSubmitPage.tsx
packages/lesswrong/components/ea-forum/voting-portal/ElectionAllocateVote.tsx
packages/lesswrong/components/ea-forum/voting-portal/VotingPortalIntro.tsx
packages/lesswrong/components/ea-forum/voting-portal/VotingPortalThankYou.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206078104222606) by [Unito](https://www.unito.io)

Copy changes + small font changes

---

packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx

Two small improvements:
* Decreased font size in top banner
* Linking Election fund in the header
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206079567000536) by [Unito](https://www.unito.io)

Giving portal when voting opens: Minor tweaks

---

packages/lesswrong/server/repos/CommentsRepo.ts

Tested in hex (reduced time from 2s to 0s and returns same results), and tested on dev db local server. Can't test on prod db because new EA forum migration in the way
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206081597344263) by [Unito](https://www.unito.io)

Changing a slow query to be fast on frontpage

---

packages/lesswrong/components/review/FrontpageReviewWidget.tsx
packages/lesswrong/components/review/PostsItemReviewVote.tsx
packages/lesswrong/components/review/ReviewPhaseInformation.tsx
packages/lesswrong/components/review/ReviewQuickPage.tsx
packages/lesswrong/components/review/ReviewVoteTableRow.tsx
packages/lesswrong/lib/collections/comments/views.ts
packages/lesswrong/lib/collections/posts/views.ts
packages/lesswrong/lib/reviewUtils.tsx

It's review time, baby! 
Robert and I tested out the UI fresh and made a number of sundry fixes to things that either broke with Postgres/were broken all along. Minor stuff.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206044071894812) by [Unito](https://www.unito.io)

Revive and Clean up Annual Review for 2023 (2022 Annual Review)

---

packages/lesswrong/components/dialogues/DialogueRecommendationRow.tsx
packages/lesswrong/components/dialogues/DialoguesList.tsx
packages/lesswrong/components/users/DialogueMatchingPage.tsx
packages/lesswrong/server/resolvers/userResolvers.ts

Showing opinions seemed to help. Unclear effect of showing recommendations on frontpage (but I have a prior, and like the feature, so don't want to remove yet).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206082808839622) by [Unito](https://www.unito.io)

End two AB tests that served their time. Add analytics for source of check.

---

packages/lesswrong/components/posts/dialogues/DialogueEditorFeedback.tsx
yarn.lock

The button at the bottom of dialogues that requests feedback, now opens intercom and sends the standard message and notifies Justis.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206098273997531) by [Unito](https://www.unito.io)

Dialogue Feedback Request Button hooked up to Intercom

---

packages/lesswrong/components/common/LWHome.tsx
packages/lesswrong/components/review/FrontpageReviewWidget.tsx
packages/lesswrong/components/review/ReviewVotingWidget.tsx
packages/lesswrong/lib/publicSettings.ts

Add setting to control review-widget visibility; defensive programming in progress-bar calculation; read review settings in the right place
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206099854991584) by [Unito](https://www.unito.io)

Review widget fixes

---

packages/lesswrong/components/review/FrontpageReviewWidget.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206099760475284) by [Unito](https://www.unito.io)

Don't filter for unnominated posts

---

packages/lesswrong/components/comments/CommentsItem/CommentsItemMeta.tsx

Fix spacing of review notice

---

packages/lesswrong/lib/publicSettings.ts
packages/lesswrong/lib/types/collectionTypes.ts
packages/lesswrong/server/analyticsWriter.ts
packages/lesswrong/server/apolloServer.ts
packages/lesswrong/server/perfMetrics.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206083095628754) by [Unito](https://www.unito.io)

insert gql strings with perf metrics

---

packages/lesswrong/components/users/DialogueMatchingPage.tsx

Add a pageContext with AnalyticsContext to the dialogueMatchingPage, to enable faster analytics queries, among other things
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206108343940238) by [Unito](https://www.unito.io)

Add analyticscontext to matching page

---

packages/lesswrong/components/users/DialogueMatchingPage.tsx

Teeny PR as a stopgap
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206108458524178) by [Unito](https://www.unito.io)

Encourage users to add a calendly on dialogue match

---

packages/lesswrong/server/analyticsWriter.ts
packages/lesswrong/server/perfMetrics.ts
packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206116465060438) by [Unito](https://www.unito.io)

now logging ssrs, also fix error from attempting to log nonexistent gql strings

---

packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
packages/lesswrong/components/ea-forum/giving-portal/PreVoteButton.tsx
packages/lesswrong/components/ea-forum/giving-portal/hooks.ts
packages/lesswrong/lib/voting/votingSystems.tsx
packages/lesswrong/server.ts
packages/lesswrong/server/repos/ElectionVotesRepo.ts
packages/lesswrong/server/repos/index.ts
packages/lesswrong/server/resolvers/electionVoteResolvers.ts

Some small updates based on discussion in slack
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206113294890957) by [Unito](https://www.unito.io)

[EA] Voting portal: disable pre-voting and show number of votes

---

packages/lesswrong/components/admin/AdminHome.tsx

Addresses internal user requests
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206129769608860) by [Unito](https://www.unito.io)

Make /admin link to the topics dashboard

---

packages/lesswrong/components/ea-forum/giving-portal/GivingSeasonBanner.tsx
packages/lesswrong/lib/collections/electionVotes/helpers.ts
packages/lesswrong/lib/utils/timeUtil.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206142485611766) by [Unito](https://www.unito.io)

[EA] Add countdown to frontpage vote banner

---

packages/lesswrong/components/votes/lwReactions/InlineReactHoverableHighlight.tsx

Don't underline zero-score inline reactions. You can still hover them (there just isn't a cue that you can hover there), and they'll be underlined if you highlight the reaction item in the footer.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206146420531277) by [Unito](https://www.unito.io)

Don't underline inline reactions if antireactions brought them to zero or less net score

---

packages/lesswrong/components/votes/lwReactions/InlineReactHoverableHighlight.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206146555407656) by [Unito](https://www.unito.io)

Fix missing underline styling for inline-reacts on answers

---

packages/lesswrong/components/comments/CommentsItem/CommentBottomCaveats.tsx

Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206154252781775) by [Unito](https://www.unito.io)

Change horiz positioning of Reply button when a comment is retracted

---

packages/lesswrong/lib/collections/users/schema.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206143485956829) by [Unito](https://www.unito.io)

Make previousDisplayName private

---

packages/lesswrong/components/common/Header.tsx
packages/lesswrong/server/serverSentEvents.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206167945191181) by [Unito](https://www.unito.io)

EA forum gating hotfixes for dialogues header

---

packages/lesswrong/components/tagging/TagPage.tsx

Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206142695899426) by [Unito](https://www.unito.io)

Fix spacing and alignment of tag page post list sorting

---

packages/lesswrong/components/books/Books2021SaleAnimation.tsx
packages/lesswrong/components/common/LWHome.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/cookies/cookies.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206166928468404) by [Unito](https://www.unito.io)

Add book banner for 2021

---

packages/lesswrong/components/dialogues/DialoguesList.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206178475636467) by [Unito](https://www.unito.io)

Fix timezone bug

---

packages/lesswrong/components/recentDiscussion/EARecentDiscussionElectionVote.tsx
packages/lesswrong/components/recentDiscussion/EARecentDiscussionItem.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionFeed.tsx
packages/lesswrong/lib/collections/electionVotes/fragments.ts
packages/lesswrong/lib/collections/electionVotes/schema.ts
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts
packages/lesswrong/server/resolvers/recentDiscussionFeed.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206163558712708) by [Unito](https://www.unito.io)

Show election votes in recent discussions

---

packages/lesswrong/server.ts
packages/lesswrong/server/analyticsWriter.ts
packages/lesswrong/server/prunePerfMetricsCron.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206177480138393) by [Unito](https://www.unito.io)

cron job to prune and sample old perf metrics

---

packages/lesswrong/server/prunePerfMetricsCron.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206186982375302) by [Unito](https://www.unito.io)

gate prune perf metrics job behind db setting

---

packages/lesswrong/components/posts/PostsItemTrailingButtons.tsx

Change icon and text between archiving and unarchiving a draft

---

packages/lesswrong/components/ea-forum/giving-portal/GivingSeasonBanner.tsx

Copy update requested by Lizka:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206202707032429) by [Unito](https://www.unito.io)

Update giving season banner subtitle post-donation-election

---

packages/lesswrong/components/ea-forum/giving-portal/hooks.ts

This reverts commit f77152faab3a5a15fa640da746b9c7bbcec7d334.
As requested on Slack
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206216329399729) by [Unito](https://www.unito.io)

Revert "Reenable giving season banner"

---

packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
packages/lesswrong/components/ea-forum/giving-portal/ElectionCandidate.tsx
packages/lesswrong/components/ea-forum/giving-portal/ElectionCandidatesList.tsx
packages/lesswrong/lib/eaGivingSeason.ts

Giving portal updates requested by Toby, preparing for the end of giving season.
- Various copy updates
- Add "Donate now" section to top of page
- Add description tooltips to election candidates
- Limit list of "other features candidates" to a specific set of 13 charities
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206230023489516) by [Unito](https://www.unito.io)

Giving portal updates 2023-12-22

---

packages/lesswrong/components/common/LWHome.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206234128697084) by [Unito](https://www.unito.io)

Remove book banner

---

packages/lesswrong/components/ea-forum/wrapped/EAForumWrapped2023Page.tsx
packages/lesswrong/components/posts/PostsByVote.tsx
packages/lesswrong/components/posts/PostsByVoteWrapper.tsx
packages/lesswrong/lib/collections/userMostValuablePosts/views.ts

Some UI and copy updates as requested on slack, and some changes to make the page load faster
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206255742312700) by [Unito](https://www.unito.io)

[EA Forum only] Wrapped: some UI updates and NoSSRs

---

packages/lesswrong/components/ea-forum/wrapped/EAForumWrapped2023Page.tsx

A few things here:
1. Make thank author DM input a scroll snap target so that it's easier to type into it on mobile
2. Make some placeholder text in child components always white instead of the default
3. Add more analytics (`pageSectionContext`)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206256822851959) by [Unito](https://www.unito.io)

[EA Forum only] Wrapped: make thank author input a scroll snap target

---

packages/lesswrong/components/ea-forum/EAHomeMainContent.tsx
packages/lesswrong/components/ea-forum/giving-portal/hooks.ts

End EA giving season 2023. This just disables the user facing features - there's still some code clean up to do but that can wait.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206263536155246) by [Unito](https://www.unito.io)

Disable giving season 2023

---

packages/lesswrong/server/voteServer.ts

If the rules ever get more complicated than this then a `forumSelect` is probably the way to go, but it seems like overkill for now.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206264154405702) by [Unito](https://www.unito.io)

Forum-gate strong-vote rate limits

---

packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx

More giving portal copy updates from Lizka (she also requested a couple of small design tweaks, but they're less important and can wait for another pull request).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206253146586524) by [Unito](https://www.unito.io)

Giving portal copy updates 2023-12-28

---

packages/lesswrong/lib/sql/sqlClient.ts
packages/lesswrong/server/callbacks.ts
packages/lesswrong/server/sqlConnection.ts
packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx

Three things that wound up in my `git stash` because they were too small for whole PRs:
* Add a `logResultSetSizes` option
* Use the `clearLoginTokens` function instead of a `rawUpdate`
* Some console-logging tweaks around SSRs
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206263264907907) by [Unito](https://www.unito.io)

Misc small things

---

README.md

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206257505648657) by [Unito](https://www.unito.io)

Remove outdated mentions to Mongo on Readme

---

packages/lesswrong/lib/betas.ts
packages/lesswrong/lib/instanceSettings.ts

Makes dialogues, side comments and comments toc into instance settings
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206259778366830) by [Unito](https://www.unito.io)

Make several beta's into instance settings

---

packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx
packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
packages/lesswrong/components/ea-forum/wrapped/EAForumWrapped2023Page.tsx
packages/lesswrong/components/search/UsersSearchHit.tsx
packages/lesswrong/server/notificationTypesServer.tsx
packages/lesswrong/server/scripts/sendWrappedNotifications.ts

Various small fixes, links to slack conversations:
1. [Remove scroll snapping from Wrapped](https://cea-core.slack.com/archives/C0680RXPL78/p1704195221474609)
2. Some cleanup around the Wrapped notifications
3. [Small updates to the Profile page](https://cea-core.slack.com/archives/C03R2G12W2K/p1704159211913879)
4. While I was there, also fixed the issue where the "Participation" tab can appear even if it's empty
5. [Add tracking for DMing a user via finding them in search autocomplete](https://cea-core.slack.com/archives/C03G0AQ925P/p1704158042160959)
6. [Added an ad for Wrapped in the home page RHS:](https://cea-core.slack.com/archives/C0680RXPL78/p1704195087560509)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206267635271657) by …

[EA Forum only] Small fixes for Wrapped and a couple other things

---

packages/lesswrong/components/events/modules/VirtualProgramCard.tsx

Quick update to match the [current dates](https://www.effectivealtruism.org/virtual-programs)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206285424768279) by [Unito](https://www.unito.io)

[EA Forum only] fix VP dates again

---

packages/lesswrong/lib/abTestImpl.ts
packages/lesswrong/lib/abTests.ts
packages/lesswrong/server/clientIdMiddleware.ts
packages/lesswrong/server/vulcan-lib/apollo-ssr/pageCache.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206290636562685) by [Unito](https://www.unito.io)

Improve performance when serving requests that hit the page cache

---

packages/lesswrong/components/sunshineDashboard/ModeratorActions.tsx
packages/lesswrong/components/sunshineDashboard/NewModeratorActionDialog.tsx
packages/lesswrong/lib/collections/moderatorActions/schema.ts
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/rateLimits/utils.ts
packages/lesswrong/server/rateLimitUtils.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206291881933182) by [Unito](https://www.unito.io)

Implement basic rate limit exception

---

packages/lesswrong/lib/rateLimits/utils.ts

Got a negation wrong, heh
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206322424373869) by [Unito](https://www.unito.io)

Tiny bug fix for rate limit display

---

packages/lesswrong/components/common/HomeTagBar.tsx
packages/lesswrong/components/ea-forum/EAHomeMainContent.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/utils/typeGuardUtils.ts

We're reusing it on WakingUP side
This also adds description on hover for tags (disabled by default)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206284705489328) by [Unito](https://www.unito.io)

Extract EA Home topics bar into it's own component

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/ForumIcon.tsx
packages/lesswrong/components/review/FrontpageReviewWidget.tsx
packages/lesswrong/components/review/ReviewVotingCanvas.tsx
packages/lesswrong/components/review/ReviewVotingProgressBar.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/reviewUtils.tsx
packages/lesswrong/server/repos/DatabaseMetadataRepo.ts
packages/lesswrong/server/resolvers/reviewVoteResolvers.ts
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/siteThemes/lesswrongTheme.ts
packages/lesswrong/themes/themeType.ts
packages/lesswrong/themes/userThemes/darkMode.ts

This adds background images to a few tabs, including the frontpage: 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206355051763436) by [Unito](https://www.unito.io)

Add LessWrong background image, default and vote

---

packages/lesswrong/components/review/ReviewVotingCanvas.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206370309371448) by [Unito](https://www.unito.io)

Small adjustment to what's shown to logged-out users

---

packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx

Removing [this ad](https://github.com/ForumMagnum/ForumMagnum/pull/8590) after it's been up for a couple weeks - I'll deploy this on Jan 17. (I branched off of a related PR that should be going out before then.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206353156178993) by [Unito](https://www.unito.io)

[EA Forum only] remove the homepage RHS Wrapped ad

---

packages/lesswrong/components/Layout.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206378633168826) by [Unito](https://www.unito.io)

Change overflow hidden to clip on App wrapper

---

.github/workflows/deployEABeta.yaml

I want this to do some performance testing
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206404254169510) by [Unito](https://www.unito.io)

[EA] Reset beta site to be up to date with prod

---

packages/lesswrong/components/Layout.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206424632404274) by [Unito](https://www.unito.io)

Fix super slow rendering performance on Safari

---

packages/lesswrong/components/posts/PostsPage/T3AudioPlayer.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206424135238397) by [Unito](https://www.unito.io)

Type3 audio player script has "defer" so it can't block FCP

---

packages/lesswrong/components/ea-forum/EAHomeMainContent.tsx
packages/lesswrong/components/form-components/FormComponentPostEditorTagging.tsx
packages/lesswrong/components/sunshineDashboard/SunshineNewUsersProfileInfo.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206451693606665) by [Unito](https://www.unito.io)

[EA] Deploy changes to support opportunities in the topic bar

---

packages/lesswrong/components/editor/EditorFormComponent.tsx

If you type a comment and save without ever pausing for long enough that the debounced auto-save runs, the comment text persists in the textbox after saving, rather than getting cleared like it should. This PR applies the solution we found on the Waking Up forum. The commit has a lengthy comment explaining what it does, though I fear it'll be hard to follow.
Related to https://github.com/ForumMagnum/ForumMagnum/pull/5607
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206479076397523) by [Unito](https://www.unito.io)

Fix comment text persisting bug

---

packages/lesswrong/server/analytics/analyticsCron.ts

[Cleanup item](https://github.com/ForumMagnum/ForumMagnum/pull/8640#discussion_r1453374453) from this [PR](https://github.com/ForumMagnum/ForumMagnum/pull/8640)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206509319770180) by [Unito](https://www.unito.io)

Change console.log()s in analyticsCron to logger()

---

packages/lesswrong/components/review/ReviewVotingPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206423772077349) by [Unito](https://www.unito.io)

Fix sort-by-karma-vote on the review-voting page

---

packages/lesswrong/lib/collections/posts/schema.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206560336763003) by [Unito](https://www.unito.io)

put manifold fields on posts into admin options form group

---

packages/lesswrong/server/apolloServer.ts

We currently fetch the current user when making calls to the search endpoint. This is a _blocking_ call - we can't even begin building the search query until we get the result back from Postgres, let alone send that query to elastic. However, we never actually use the current user in these search queries (permissions are handled when exporting to elastic) so we can safely remove this fetch to make searching feel a bit snappier.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206544331760042) by [Unito](https://www.unito.io)

Don't fetch the current user for the /api/search endpoint

---

packages/lesswrong/components/analytics/AnalyticsGraph.tsx
packages/lesswrong/components/analytics/AuthorAnalyticsPage.tsx
packages/lesswrong/components/analytics/PostsAnalyticsPage.tsx
packages/lesswrong/components/common/ForumDropdownMultiselect.tsx

* Made all titles the same color (were different greys on individual post pages) + thicker (like the Best of page)
* "View" instead of "view"
* Thinner lines and checkboxes
* Smaller icon in (all) dropdowns
* Consistent font sizes + weights
**Overview page before**
**Overview page after**
**Individual page before**
**Individual page after**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206568894403444) by [Unito](https://www.unito.io)

Post stats UI nitpicks

---

packages/lesswrong/components/posts/LWPostsItem.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206580619172231) by [Unito](https://www.unito.io)

Fix gap on right side of continue-reading sequence image

---

packages/lesswrong/server/ckEditor/ckEditorApi.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206513518282666) by [Unito](https://www.unito.io)

add method to reset ckeditor collab sessions

---

packages/lesswrong/server/callbacks/votingCallbacks.ts

The tags are too noisy at the tops of the posts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206608016187539) by [Unito](https://www.unito.io)

Remove annual review tags

---

packages/lesswrong/lib/collections/posts/schema.tsx

It's a little spammy
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206608569746840) by [Unito](https://www.unito.io)

Filter out review bot comments from recent discussion

---

packages/lesswrong/components/common/AnalyticsPageInitializer.tsx
packages/lesswrong/components/messaging/ConversationContents.tsx
packages/lesswrong/lib/analyticsEvents.tsx
packages/lesswrong/lib/collections/posts/schema.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206619210688500) by [Unito](https://www.unito.io)

Disable polling on DM pages

---

packages/lesswrong/components/votes/lwReactions/NamesAttachedReactionsVoteOnComment.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206626017401082) by [Unito](https://www.unito.io)

make react icons hover-only on mobile

---

packages/lesswrong/components/tagging/FooterTagList.tsx

Add margin to 'Show all tags'

---

packages/lesswrong/components/messaging/NewConversationDialog.tsx

Based on @agnesstenlund 's comment [here](https://github.com/ForumMagnum/ForumMagnum/pull/8615#issuecomment-1895537432) (copied below)
> Sorry I'm too late to this one, looks really good though! 🙌
>
>A few suggestions:
>
>Move the "Create conversation" button to the bottom of the modal, and change it to text instead of a Send message icon
>Tweak the chip Mui component to look slightly neater: Like reducing height of pills + use a simple x instead of circled x, increase font size, less rounded corners etc.
>(think the first is more important than the latter)
> ![image](https://github.com/ForumMagnum/ForumMagnum/assets/77623106/76ad49c8-eadf-48a6-ae28-a721cfc3738a)
Before/after:

Tweaks to NewConversationDialog

---

packages/lesswrong/server/migrations/20240228T000423.addReviewWinnerTables.ts

Tweak migration
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206710840324339) by [Unito](https://www.unito.io)

Review Winner tables migration tweak

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx

A few fast follows for the new leastwrong page
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206711075542259) by [Unito](https://www.unito.io)

Review tweaks

---

packages/lesswrong/components/comments/CommentsTableOfContents.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206711258444039) by [Unito](https://www.unito.io)

Hide comments ToC when no comments

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/components/posts/TableOfContents/MultiToCLayout.tsx
packages/lesswrong/components/posts/TableOfContents/TableOfContentsRow.tsx
packages/lesswrong/components/sequences/TopPostsPage.tsx
packages/lesswrong/lib/routes.ts

I might want to revert it again, but I want to try out the different name for a day or so. Just copy text is changed.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206719792454936) by [Unito](https://www.unito.io)

Replace "LeastWrong" with "Best of LessWrong"

---

packages/lesswrong/server/authenticationMiddlewares.ts
packages/lesswrong/server/posts/googleDocImport.ts

Hotfix for a bug in https://github.com/ForumMagnum/ForumMagnum/pull/8756

Use right credentials for signing in to google doc service account

---

packages/lesswrong/lib/vulcan-lib/utils.ts

https://github.com/ForumMagnum/ForumMagnum/pull/8756 Broke buttons (turned then back into regular links) by disallowing the classes that are set on them
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206737886259514) by [Unito](https://www.unito.io)

Fix buttons by making allowed classes more permissive

---

packages/lesswrong/server/editor/conversionUtils.ts

For reference here is an example of the html we get:
```
<body class=\"doc-content\" style=\"background-color:#ffffff;padding:72pt 72pt 72pt 72pt;max-width:451.4pt\">
<p
style=\"padding:0;margin:0;color:#000000;font-size:12pt;font-family:&quot;Calibri&quot;;line-height:1.15;orphans:2;widows:2;text-align:left\">
<span>This is some te</span><span>xt</span><sup><a href=\"#cmnt1\" id=\"cmnt_ref1\">[a]</a></sup></p>
<div style=\"border:1px solid black;margin:5px\">
<p
style=\"padding:0;margin:0;color:#000000;font-size:12pt;font-family:&quot;Calibri&quot;;line-height:1.0;text-align:left\">
<a href=\"#cmnt_ref1\" id=\"cmnt1\">[a]</a><span
style=\"color:#000000;font-weight:400;text-decoration:none;vertical-align:baseline;font-size:11pt;font-family:&quot;Arial&quot;;font-style:normal\">This
is a …
```

Strip comments from imported google docs

---

packages/lesswrong/components/Layout.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206761656805080) by [Unito](https://www.unito.io)

Deploy fixed vote image

---

packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx
packages/lesswrong/components/posts/TableOfContents/MultiToCLayout.tsx
packages/lesswrong/components/posts/TableOfContents/TableOfContentsRow.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206769810663925) by [Unito](https://www.unito.io)

More minor styling adjustments (this time to animation speed)

---

packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206771438259190) by [Unito](https://www.unito.io)

Fix infinite loop in ToC

---

packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206771713518555) by [Unito](https://www.unito.io)

Fix ToC image loading properly

---

packages/lesswrong/components/posts/PostsPage/PostsPageSplashHeader.tsx

As far as I can tell the "or" just broke the media query here, this fixes it

Fix posts splash page mobile

---

packages/lesswrong/components/posts/PostsPage/PostsPageSplashHeader.tsx
packages/lesswrong/components/posts/PostsSingle.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206799883277275) by [Unito](https://www.unito.io)

More fixes for broken links and mobile splash page

---

build.js
package.json
yarn.lock

Reverts ForumMagnum/ForumMagnum#8911 IDK
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206812163756917) by [Unito](https://www.unito.io)

Revert "Native node source map support"

---

packages/lesswrong/components/posts/PostsPage/PostsPageSplashHeader.tsx
packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx
packages/lesswrong/components/posts/TableOfContents/MultiToCLayout.tsx
packages/lesswrong/components/posts/TableOfContents/TableOfContentsRow.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206815956584701) by [Unito](https://www.unito.io)

fix toc height on short posts

---

packages/lesswrong/components/common/HeadTags.tsx
packages/lesswrong/components/sequences/TopPostsPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206827723906448) by [Unito](https://www.unito.io)

add dynamic dpr and width rescaling for review winner art on the best of LW page

---

packages/lesswrong/lib/collections/moderatorActions/schema.ts
packages/lesswrong/server/callbacks/votingCallbacks.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206845218402221) by [Unito](https://www.unito.io)

fix cooldown period for reapplying the senior downvoter mod action

---

packages/lesswrong/lib/betas.ts
packages/lesswrong/server/curationEmails/cron.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206873490852705) by [Unito](https://www.unito.io)

exclude curation email cron from test servers

---

packages/lesswrong/components/votes/lwReactions/UsersWhoReacted.tsx
packages/lesswrong/server/voteServer.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206862753572882) by [Unito](https://www.unito.io)

List of users who reacted has ellipsis in ReactionQuotesHoverInfo

---

packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx

We've already got answers in the Comments ToC, and having them in the post ToC messes with the progress bar and looks kinda weird.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206934939671744) by [Unito](https://www.unito.io)

remove answers from full-height toc

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/HomeLatestPosts.tsx
packages/lesswrong/components/icons/SettingsButton.tsx
packages/lesswrong/components/recommendations/LWRecommendations.tsx
packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx

Adds banner to LessWrong frontpage for LessOnline
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206937055038871) by [Unito](https://www.unito.io)

Less online banner

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/HeaderSubtitle.tsx
packages/lesswrong/components/common/HomeLatestPosts.tsx
packages/lesswrong/components/icons/SettingsButton.tsx
packages/lesswrong/components/posts/AllPostsPage.tsx
packages/lesswrong/components/recommendations/LWRecommendations.tsx
packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
packages/lesswrong/components/users/UsersMenu.tsx
packages/lesswrong/lib/routes.ts
packages/lesswrong/themes/siteThemes/lesswrongTheme.ts

Adds a black bar to the frontpage today: 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206946238565560) by [Unito](https://www.unito.io)

Blackbar and fix for frontpage buttons

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/HomeLatestPosts.tsx
packages/lesswrong/components/icons/SettingsButton.tsx
packages/lesswrong/components/posts/AllPostsPage.tsx
packages/lesswrong/components/recommendations/LWRecommendations.tsx
packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206946161064256) by [Unito](https://www.unito.io)

Replace color of SettingsButton with text-shadow

---

packages/lesswrong/components/common/HomeLatestPosts.tsx
packages/lesswrong/components/posts/RecombeeLatestPosts.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206946673678230) by [Unito](https://www.unito.io)

make recombee configuration hideable

---

packages/lesswrong/components/posts/TableOfContents/MultiToCLayout.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206927974020725) by [Unito](https://www.unito.io)

Adjust post centering

---

packages/lesswrong/components/posts/RecombeeLatestPosts.tsx
packages/lesswrong/components/posts/RecombeePostsList.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206955203329630) by [Unito](https://www.unito.io)

Include Sticky Posts and Curated Posts in Recombee recommendations

---

packages/lesswrong/components/posts/RecombeeLatestPosts.tsx
packages/lesswrong/components/posts/RecombeePostsList.tsx
packages/lesswrong/lib/collections/users/recommendationSettings.ts
packages/lesswrong/server/recombee/client.ts

Adds "Load More" functionality for recombee-sourced posts (and fixes an outstanding bug with whether the settings are visible for admins).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206955042176371) by [Unito](https://www.unito.io)

Recombee load more

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/HeaderSubtitle.tsx
packages/lesswrong/components/users/UsersMenu.tsx
packages/lesswrong/lib/routes.ts
packages/lesswrong/themes/siteThemes/lesswrongTheme.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206955711787371) by [Unito](https://www.unito.io)

remove black bar

---

packages/lesswrong/components/ea-forum/EABestOfPage.tsx

Since some posts in the list were over a year old, I updated the list based on Lizka's suggestions [here](https://docs.google.com/document/d/1LMQgJfZEtgA8_zXzMqYmTUvC_LK2jOVl3zXFEu30bNw/edit)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206956147629395) by [Unito](https://www.unito.io)

[EA Forum only] update Best Of past year list

---

packages/lesswrong/components/common/HomeLatestPosts.tsx
packages/lesswrong/components/common/LWHome.tsx
packages/lesswrong/components/common/TabPicker.tsx
packages/lesswrong/components/posts/PostsTitle.tsx
packages/lesswrong/components/posts/RecombeeLatestPosts.tsx
packages/lesswrong/components/posts/RecombeePostsList.tsx
packages/lesswrong/components/posts/RecombeePostsListSettings.tsx
packages/lesswrong/components/recommendations/LWRecommendations.tsx
packages/lesswrong/components/spotlights/DismissibleSpotlightItem.tsx
packages/lesswrong/components/tagging/TagFilterSettings.tsx
packages/lesswrong/lib/betas.ts
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/publicSettings.ts
packages/lesswrong/server/callbacks/postCallbacks.ts
packages/lesswrong/server/resolvers/postResolvers.ts

Continuing down the path of (Recombee) recommendations, starting to make nicer UI and reorganize the frontpage for recommendations.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206962450235052) by [Unito](https://www.unito.io)

Start Restyling LW Frontpage for Recommendations

---

packages/lesswrong/components/Layout.tsx

Update some music sources
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206974721112021) by [Unito](https://www.unito.io)

April fools

---

packages/lesswrong/server/scripts/backfillRecombee.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206955811474647) by [Unito](https://www.unito.io)

fix recombee user, read status, and vote backfill script

---

packages/lesswrong/lib/betas.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206976103303271) by [Unito](https://www.unito.io)

remove usage of ab tests for recombee

---

packages/lesswrong/components/Layout.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206977572285040) by [Unito](https://www.unito.io)

Subtler music player

---

packages/lesswrong/components/users/UsersMenu.tsx

https://github.com/ForumMagnum/ForumMagnum/pull/9023

[EA Forum only] revert user menu update

---

packages/lesswrong/components/comments/CommentsItem/CommentBody.tsx
packages/lesswrong/lib/collections/sequences/helpers.ts
packages/lesswrong/themes/createThemeDefaults.ts
packages/lesswrong/themes/themeType.ts

This reverts commit ad99a147824584ea64b5a1d0f01e3f2aa728f83a.
❤️
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206981146334970) by [Unito](https://www.unito.io)

Revert font troll

---

packages/lesswrong/lib/betas.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206984451554080) by [Unito](https://www.unito.io)

enable rec experiment through query param

---

packages/lesswrong/components/posts/RecombeeLatestPosts.tsx
packages/lesswrong/server/recombee/client.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206985305521416) by [Unito](https://www.unito.io)

Recombee filter out inactive tabs and remove oversampling

---

packages/lesswrong/server/authentication/auth0.ts

Currently, if you try to sign up for an account with an email address that is already used by another account you get a very unhelpful "Invalid signup" error message. This PR adds a special case to instead show "A user with this email already exists".
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206825549006658) by [Unito](https://www.unito.io)

Add a special-case error message if signing up with an existing email

---

packages/lesswrong/lib/collections/comments/views.ts
packages/lesswrong/lib/collections/users/schema.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207005112434289) by [Unito](https://www.unito.io)

[EA] deploy default to sending an email for new post notifications

---

packages/lesswrong/components/common/TabPicker.tsx
packages/lesswrong/components/posts/RecombeeLatestPosts.tsx
packages/lesswrong/components/posts/ResolverPostsList.tsx
packages/lesswrong/server/repos/PostsRepo.ts
packages/lesswrong/server/resolvers/postResolvers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207005560825397) by [Unito](https://www.unito.io)

Recombee iteration 20240404

---

packages/lesswrong/components/ea-forum/onboarding/EAOnboardingInput.tsx
packages/lesswrong/components/ea-forum/onboarding/EAOnboardingUserStage.tsx

- Pressing enter after typing a username now advances to the next onboarding stage
- Focus the name input when the onboarding popup first opens
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207046026288003) by [Unito](https://www.unito.io)

EA Onboarding name input improvements

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/components/posts/PostsPreviewTooltip/LWPostsPreviewTooltip.tsx
packages/lesswrong/components/tagging/FooterTagList.tsx
packages/lesswrong/components/tagging/TruncatedTagsList.tsx
packages/lesswrong/components/tagging/subforums/SidebarSubtagsBox.tsx
packages/lesswrong/lib/collections/posts/schema.tsx
packages/lesswrong/lib/collections/tags/helpers.ts
packages/lesswrong/unitTests/tagHelpers.tests.ts

_This will be against master once https://github.com/ForumMagnum/ForumMagnum/pull/8971 is merged_
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207009094433374) by [Unito](https://www.unito.io)

Posts page layout shift fixes: column width, tag reordering

---

packages/lesswrong/server/sideComments.ts

Speeds up `matchSideComments` by early-exiting on comments with no quote-shards, and hoisting a lot of the computation out of the per-comment loop. On [this post](https://www.lesswrong.com/posts/wAczufCpMdaamF9fy/my-objections-to-we-re-all-gonna-die-with-eliezer-yudkowsky), tested on my development laptop, the part of the pageload attributed to this function goes from ~430ms to ~120ms.
This function being slow was having a noticeable impact because side-comment caching wasn't working, possibly due to the new fragment-compilation code. That's fixed in
https://github.com/ForumMagnum/ForumMagnum/pull/8769 which splits the side-comments cache into its own table, so this isn't as necessary as it would be without that, but it'll still help with cases like when the cache gets populated for the …

Speed up side-comment matching

---

packages/lesswrong/components/common/HomeLatestPosts.tsx
packages/lesswrong/components/ea-forum/StickiedPosts.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207117302540003) by [Unito](https://www.unito.io)

[FriendlyUI] fix frontpage ghost loading state

---

packages/lesswrong/lib/routes.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207128036801392) by [Unito](https://www.unito.io)

change to headerSubtitle

---

packages/lesswrong/components/common/TabPicker.tsx
packages/lesswrong/components/posts/LWPlaceholderPostsItem.tsx
packages/lesswrong/components/posts/LWPostsItem.tsx
packages/lesswrong/components/posts/PostsList2.tsx
packages/lesswrong/components/posts/PostsLoading.tsx
packages/lesswrong/components/posts/RecombeeLatestPosts.tsx
packages/lesswrong/components/posts/RecombeePostsList.tsx
packages/lesswrong/components/posts/usePostsList.ts
packages/lesswrong/lib/components.ts
packages/lesswrong/server/recombee/client.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207094976273647) by [Unito](https://www.unito.io)

frontpage post tabs: post item placeholders, scrolling, etc

---

packages/lesswrong/server/apolloServer.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207149052531177) by [Unito](https://www.unito.io)

Add settings to experiment with cache-control settings on staging

---

packages/lesswrong/server/recombee/client.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207153172082152) by [Unito](https://www.unito.io)

change recombee scenarios used for hybrid recommendations

---

packages/lesswrong/server/apolloServer.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207164677002984) by [Unito](https://www.unito.io)

remove redirect

---

packages/lesswrong/server/resolvers/postResolvers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207176752492682) by [Unito](https://www.unito.io)

deploy flip vertex admin-gating

---

packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
packages/lesswrong/lib/betas.ts

This reverts commit 0e833c2a0e7a88b827aa205a11725e4a3d404b37.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207181135731419) by [Unito](https://www.unito.io)

[EA] Enable the people directory

---

packages/lesswrong/server/resolvers/postResolvers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207181243672829) by [Unito](https://www.unito.io)

[EA] Deploy enable the people directory

---

packages/lesswrong/components/peopleDirectory/PeopleDirectoryPage.tsx

As requested by Agnes
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207198743783389) by [Unito](https://www.unito.io)

Update people directory feedback link

---

packages/lesswrong/server/recombee/client.ts

https://lightconeteam.slack.com/archives/C06RT18AM0R/p1714516056470839
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207210109521523) by [Unito](https://www.unito.io)

set cascadeCreate to true to hotfix recombee outage

---

packages/lesswrong/server/google-vertex/client.ts
packages/lesswrong/server/perfMetrics.ts
packages/lesswrong/server/recombee/client.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207226863670849) by [Unito](https://www.unito.io)

add perf metrics for 3rd party recommendations

---

packages/lesswrong/components/peopleDirectory/PeopleDirectoryResultRow.tsx
packages/lesswrong/components/peopleDirectory/PeopleDirectoryUserCell.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207233814318825) by [Unito](https://www.unito.io)

[EA Forum only] add analytics for messages from People Directory

---

packages/lesswrong/components/common/LWHomePosts.tsx
packages/lesswrong/components/posts/RecombeePostsList.tsx
packages/lesswrong/lib/collections/users/recommendationSettings.ts
packages/lesswrong/lib/vulcan-core/default_resolvers.ts
packages/lesswrong/server/recombee/client.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207227902398194) by [Unito](https://www.unito.io)

use native latest posts for hybrid recommendations requests

---

packages/lesswrong/server/recombee/client.ts

Turns out that passing in an empty array to a `$nin` translates into something like `NOT (_id IN (SELECT NULL::VARCHAR(27)))`, which always(?) filters out everything.
Also, we want to continue to exclude the curated and stickied posts that we fetch on the first load from load mores.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207251222785686) by [Unito](https://www.unito.io)

fix load more for hybrid recommendations

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/LWHome.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207253855917155) by [Unito](https://www.unito.io)

Fooming Shoggoths concert

---

packages/lesswrong/components/Layout.tsx

Fixed
– fix feynman spelling
– add darkmode
– improve image

Fix shoggoth splash issues

---

packages/lesswrong/components/common/LWHomePosts.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207260882279739) by [Unito](https://www.unito.io)

[LW] Temporarily Switch  Recombee Scenario

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/LWHomePosts.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207260909416355) by [Unito](https://www.unito.io)

LW Deploy 2024-05-07 (switch recombee scenario)

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/admin/AdminHome.tsx
packages/lesswrong/components/admin/AdminViewOnboarding.tsx
packages/lesswrong/components/ea-forum/onboarding/EAOnboardingFlow.tsx
packages/lesswrong/components/ea-forum/onboarding/EAOnboardingStage.tsx
packages/lesswrong/components/ea-forum/onboarding/EAOnboardingUserStage.tsx
packages/lesswrong/components/ea-forum/onboarding/useEAOnboarding.tsx
packages/lesswrong/components/onboarding/BasicOnboardingFlow.tsx
packages/lesswrong/components/onboarding/OnboardingFlow.tsx
packages/lesswrong/lib/components.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207184864961542) by [Unito](https://www.unito.io)

Generalize OnboardingFlow and introduce BasicOnboardingFlow for non-EA forums #to-upstream

---

packages/lesswrong/components/common/LWHomePosts.tsx

Recombee improved performance and it's at least as good as recombee-personal now, but in any case we're building caching.

Switch Recommended Tab back to Recombee LessWrong Custom

---

packages/lesswrong/components/Layout.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207270980279194) by [Unito](https://www.unito.io)

Summer camp Splash image

---

packages/lesswrong/components/ea-forum/EAEmojisHeader.tsx
packages/lesswrong/themes/siteThemes/eaTheme.ts

- Fix onsite link URLs
- Fix the z-index of search results
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207271274658623) by [Unito](https://www.unito.io)

Emoji banner quick fixes

---

packages/lesswrong/components/posts/PostsItemDate.tsx

Small fix of something that got broken in a bad merge conflict resolution

fix new item bolding

---

packages/lesswrong/components/shortform/NewShortformDialog.tsx
packages/lesswrong/components/users/UsersMenu.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207289690244358) by [Unito](https://www.unito.io)

Don't close New Quick Take when you interact with the CkEditor toolbar

---

packages/lesswrong/components/Layout.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207291360119452) by [Unito](https://www.unito.io)

Final (haha!) LessOnline splash image (for now!)

---

packages/lesswrong/components/common/LWHome.tsx

accidentally used the wrong link (which I now fixed), and added analytics
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207310158559811) by [Unito](https://www.unito.io)

Fix analytics and link for LessOnline spotlight

---

packages/lesswrong/components/common/LWHome.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207310027240869) by [Unito](https://www.unito.io)

Bolder Button

---

packages/lesswrong/components/common/LWHome.tsx

There were some rendering issues for the banner on mobile. I also removed the "last day" emphasis since that's not explicitly true any more.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207317416419019) by [Unito](https://www.unito.io)

hotfix for banner

---

packages/lesswrong/components/common/LWHome.tsx

I had merged this branch into deploy to fix some broken rendering, now merging it into master to keep in sync.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207317719858485) by [Unito](https://www.unito.io)

Hotfix for banner master

---

packages/lesswrong/lib/collections/posts/helpers.ts
packages/lesswrong/lib/collections/posts/views.ts
packages/lesswrong/lib/collections/sequences/helpers.ts
packages/lesswrong/lib/collections/sequences/views.ts
packages/lesswrong/lib/collections/tags/helpers.ts
packages/lesswrong/lib/collections/tags/views.ts
packages/lesswrong/lib/routes.ts
packages/lesswrong/lib/vulcan-lib/routes.ts
packages/lesswrong/server/apolloServer.ts
packages/lesswrong/server/repos/SequencesRepo.ts
packages/lesswrong/server/repos/TagsRepo.ts
packages/lesswrong/server/repos/helpers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207293378530838) by [Unito](https://www.unito.io)

Tag and sequence routes have resource preloads

---

build.js
packages/lesswrong/server/apolloServer.ts
packages/lesswrong/server/styleGeneration.tsx
packages/lesswrong/server/utils/bundleUtils.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207319787694845) by [Unito](https://www.unito.io)

Brotli-compress allStyles (and refactor brotli-compression of bundle.js)

---

packages/lesswrong/components/posts/RecombeePostsList.tsx
packages/lesswrong/lib/collections/users/recommendationSettings.ts
packages/lesswrong/server/recombee/client.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207319769064292) by [Unito](https://www.unito.io)

implement caching for non-hybrid recommendations feed

---

packages/lesswrong/server/repos/helpers.ts

https://github.com/ForumMagnum/ForumMagnum/commit/1d66b2f5136b78e87e632518c8a0b4ecd560592d missed an `AND`

fix viewable tags selector

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/LWHome.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207339029054243) by [Unito](https://www.unito.io)

Restore spotlights to frontpage LW

---

packages/lesswrong/server/repos/PageCacheRepo.ts

cc @Will-Howard re: https://lworg.slack.com/archives/CJUN2UAFN/p1715988518775309?thread_ts=1715978897.240209&cid=CJUN2UAFN
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207349345704983) by [Unito](https://www.unito.io)

fix renderResult.renderedAt deserialization into date

---

packages/lesswrong/server/recombee/client.ts
packages/lesswrong/server/repos/PageCacheRepo.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207349662318493) by [Unito](https://www.unito.io)

[LessWrong] deploy cached renderedAt deserialization fix

---

packages/lesswrong/components/Layout.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207375593028553) by [Unito](https://www.unito.io)

Fix mispelling of Berkeley

---

packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
packages/lesswrong/components/community/Community.tsx
packages/lesswrong/components/ea-forum/StickiedPosts.tsx
packages/lesswrong/components/users/EditProfileForm.tsx
packages/lesswrong/components/users/FriendlyUsersProfile.tsx
packages/lesswrong/lib/routes.ts
packages/lesswrong/server/analytics/postgresConnection.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207396469406265) by [Unito](https://www.unito.io)

[EA] deploy pausing job ads, plus some small copy updates

---

packages/lesswrong/components/common/LWHomePosts.tsx
packages/lesswrong/components/posts/RecombeePostsList.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207396979365092) by [Unito](https://www.unito.io)

Recombee Changes: change rotation params and log generatedAt

---

packages/lesswrong/components/posts/RecombeePostsList.tsx

had a bug
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207397038222233) by [Unito](https://www.unito.io)

[Recombee] fix generatedAt type

---

packages/lesswrong/components/common/LWHomePosts.tsx
packages/lesswrong/components/posts/RecombeePostsList.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207397350036102) by [Unito](https://www.unito.io)

LW Deploy, 2024-05-23b

---

packages/lesswrong/server/recombee/client.ts

fix perf metrics for backfilled recombee requests

---

packages/lesswrong/components/ea-forum/EAHomeCommunityPosts.tsx

Requested by a user
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207421803354696) by [Unito](https://www.unito.io)

[EA] Make "hide from frontpage" apply to the community section too

---

packages/lesswrong/lib/voting/reactions.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207419946413471) by [Unito](https://www.unito.io)

Rewrite description of "locally invalid" react

---

packages/lesswrong/components/users/UserMetaInfo.tsx

Handles the case when there is 0 karma, posts, or comments

Minor Fix to new UserMetaInfo component

---

packages/lesswrong/components/common/MixedTypeFeed.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207463238107140) by [Unito](https://www.unito.io)

Revert change to the fetch-mode of Recent Discussion that may have sometimes caused a refresh loop

---

packages/lesswrong/server/recombee/client.ts

In the cases where we had posts recommended by recombee which we also got from our own latest posts query, we were incorrectly attributing both copies of the post to recombee.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207437527017883) by [Unito](https://www.unito.io)

fix misattribution of duplicate posts to recombee

---

packages/lesswrong/components/users/LWUserTooltipContent.tsx
packages/lesswrong/components/users/UserTooltip.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207475952532659) by [Unito](https://www.unito.io)

fix positioning of lw user tooltip, and hide follow button for users who shouldn't have it

---

packages/lesswrong/components/Layout.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207476098743140) by [Unito](https://www.unito.io)

remove lessonline banner from lw homepage

---

packages/lesswrong/server/callbacks/votingCallbacks.ts

Annoyingly I've not been able to test this because I get a 403 creating the market when running locally, even when I hardcode to the production key. Grr
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207474963905712) by [Unito](https://www.unito.io)

Shorter review bot comments

---

packages/lesswrong/components/common/LWHomePosts.tsx
packages/lesswrong/components/common/MixedTypeFeed.tsx
packages/lesswrong/server/repos/PostsRepo.ts
packages/lesswrong/server/resolvers/subscribedUsersFeedResolver.tsx
packages/lesswrong/server/resolvers/tagResolvers.ts
packages/lesswrong/server/utils/feedUtil.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207499338389001) by [Unito](https://www.unito.io)

fix loading more items when scrolling down subscribed feed

---

packages/lesswrong/themes/globalStyles/globalStyles.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207515105694679) by [Unito](https://www.unito.io)

[EA Forum only] tiny adjustment to "play from heading" styles

---

packages/lesswrong/lib/betas.ts

Oops, forgot this in previous PRs
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207545542044061) by [Unito](https://www.unito.io)

[LW] Set Subscribed tab to shipped

---

packages/lesswrong/components/common/LWHomePosts.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207565775141341) by [Unito](https://www.unito.io)

Remove an unnecessary expensive query on the front page

---

packages/lesswrong/components/ea-forum/EADigestPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207569235166824) by [Unito](https://www.unito.io)

fix on-site digest subscribe button

---

packages/lesswrong/components/common/LWHomePosts.tsx
packages/lesswrong/components/icons/SettingsButton.tsx
packages/lesswrong/components/subscriptions/SuggestedFeedSubscriptions.tsx
packages/lesswrong/server/resolvers/userResolvers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207555793739383) by [Unito](https://www.unito.io)

fix reloading when fetching more suggested users and wip show more

---

packages/lesswrong/components/users/FriendlyUsersProfile.tsx

https://cea-core.slack.com/archives/CJUN2UAFN/p1718603917158749
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207587441440197) by [Unito](https://www.unito.io)

[EA] Fix conditional for rendering tags on empty user profiles

---

packages/lesswrong/components/users/DialogueMatchingPage.tsx
packages/lesswrong/components/users/FriendlyUsersProfile.tsx
packages/lesswrong/components/users/UsersProfile.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207587389886281) by [Unito](https://www.unito.io)

Remove old `data-cy` DOM attributes, since we don't use Cypress any more

---

packages/lesswrong/server/voteServer.ts

Discussed with @jpaddison3 in the [mods slack](https://eaforummoderators.slack.com/archives/CCN287J49/p1718763235603659) and we've decided to remove the forum-gating for these
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207625714447880) by [Unito](https://www.unito.io)

un-forum-gate strong vote rate limits

---

packages/lesswrong/lib/collections/users/schema.ts

Broken by an incorrect refactor: https://github.com/ForumMagnum/ForumMagnum/commit/cd51ba60c338783bb12db3346fb1d7fcba97cfa4#diff-abce36aaf764a4f0dfd1cc7d51285cc91566cf65f3b4ad7e7c319859dc29b07cR590
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207635215229743) by [Unito](https://www.unito.io)

Fix ability to resend confirmation emails

---

packages/lesswrong/components/forumEvents/ForumEventPoll.tsx

Missed one place (for more context see https://github.com/ForumMagnum/ForumMagnum/pull/9457)

[EA Forum only] fix debate "view results" bug

---

packages/lesswrong/components/common/ForumIcon.tsx
packages/lesswrong/components/dropdowns/posts/HideFrontpagePostDropdownItem.tsx
packages/lesswrong/components/dropdowns/posts/useSetIsHidden.ts
packages/lesswrong/components/posts/LWPostsItem.tsx
packages/lesswrong/components/posts/PostsItemIcons.tsx
packages/lesswrong/components/posts/PostsTitle.tsx
packages/lesswrong/components/posts/RecombeePostsList.tsx
packages/lesswrong/lib/collections/posts/fragments.ts
packages/lesswrong/lib/collections/posts/helpers.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts
packages/lesswrong/server/recombee/client.ts

Upon hover on a post item, the Recommendation Sparkle becomes a Recommendation Not Interested
The Recommendation Not Interested Icon is clickable. Clicking adds the item to a user's "hidden post" list, causes it to disappear from the list, and sends a strong downvote to Recombee (but not to us)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207690539504914) by [Unito](https://www.unito.io)

Recommended Items have "Hide & Show Fewer Like This Button"

---

packages/lesswrong/server/callbacks/votingCallbacks.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207719773390950) by [Unito](https://www.unito.io)

fix flipped conditional

---

packages/lesswrong/components/ea-forum/EABestOfPage.tsx

Requested by Lizka via [slack](https://cea-core.slack.com/archives/C038J512SD8/p1719925474396899)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207828494390305) by [Unito](https://www.unito.io)

[EA Forum only] update "Best of" page monthly highlights link

---

packages/lesswrong/client/logging.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207848591360232) by [Unito](https://www.unito.io)

add missing utm params to page load events

---

packages/lesswrong/server/users/permanentDeletion.ts

There are some extra Mailchimp lists that are owned by the Online team but are not directly related to the forum (I think the only active one is the newsletter). This adds a flag to the account deletion script to also remove the user's email from these, as a convenience for GDPR deletion requests.
`./scripts/serverShellCommand.sh "Globals.permanentlyDeleteUserById('<userId>', {includingNonForumData: true})"`
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207893513109019) by [Unito](https://www.unito.io)

[EA] Add option to delete non-forum mailchimp data when deleting a user

---

packages/lesswrong/themes/globalStyles/globalStyles.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207935694218646) by [Unito](https://www.unito.io)

Fix a stray dot appearing near the comment editor

---

packages/lesswrong/server/type3.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207999323753157) by [Unito](https://www.unito.io)

Only send type3 regenerate requests for posts with audio

---

packages/lesswrong/server.ts
packages/lesswrong/server/callbacks/postCallbacks.ts
packages/lesswrong/server/fmCrosspost/requestHandlers.ts
packages/lesswrong/server/migrations/20240513T115214.normalize_posts_moderationGuidelines.ts
packages/lesswrong/server/migrations/20240729T183041.normalize_post_contents.ts
packages/lesswrong/server/migrations/meta/utils.ts
packages/lesswrong/server/repos/PostsRepo.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208060042485524) by [Unito](https://www.unito.io)

Undrafting a post ensures the latest contents revision is non-draft and has a non-0.x version number

---

packages/lesswrong/server/utils/feedUtil.ts

A temporary hack to prevent issues in Recent Discussion during the deployment, but before we've dropped the `contents` field.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208069185284871) by [Unito](https://www.unito.io)

Temporarily strip out the contents field from recent discussion results before the field is dropped

---

packages/lesswrong/server/utils/feedUtil.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208069235384712) by [Unito](https://www.unito.io)

undo hack for contents in recent discussion

---

packages/lesswrong/components/posts/PingbacksList.tsx

I had to click "load more" a bunch to see all the pingbacks for AGI Ruin: List of Lethalities.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206227333664580) by [Unito](https://www.unito.io)

Increase Pingbacks LoadMore size

---

packages/lesswrong/components/posts/PostsListSettings.tsx

Requested by Toby
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208090498394510) by [Unito](https://www.unito.io)

[EA] Minor copy change for curated posts tooltip

---

packages/lesswrong/server/apolloServer.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208107773007937) by [Unito](https://www.unito.io)

Add new healthcheck route

---

packages/lesswrong/server/vulcan-lib/apollo-ssr/pageCache.ts

In cases where we're under heavy load, SSRs will sometimes throw (i.e. because we've taken out too many db connections).  In those cases, we were leaking memory because we store in-progress requests for e.g. request merging, and then didn't clean up after ourselves in the case of errors thrown during SSR.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208108286741710) by [Unito](https://www.unito.io)

Delete in-progress renders from global state even if they throw

---

packages/lesswrong/components/posts/PostsPage/PostsPageTitle.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208144010322348) by [Unito](https://www.unito.io)

Reduce LW post page title

---

packages/lesswrong/components/hooks/useUnreadNotifications.tsx
packages/lesswrong/components/languageModels/LlmChatWrapper.tsx
packages/lesswrong/server/apolloServer.ts
packages/lesswrong/server/languageModels/anthropicClient.ts
packages/lesswrong/server/resolvers/anthropicResolvers.ts
packages/lesswrong/server/serverSentEvents.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208164805155275) by [Unito](https://www.unito.io)

LLM chat doesn't use server-sent-events (they didn't work in prod/multi-server)

---

packages/lesswrong/server/repos/CommentsRepo.ts

Requested on Slack.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208158005669268) by [Unito](https://www.unito.io)

Exclude comments on personal blogposts from popular comments section

---

packages/lesswrong/components/languageModels/LanguageModelChat.tsx
packages/lesswrong/components/languageModels/LlmChatWrapper.tsx
packages/lesswrong/lib/collections/llmConversations/schema.ts
packages/lesswrong/server/resolvers/anthropicResolvers.ts

New conversations were still using stale state.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208164792735167) by [Unito](https://www.unito.io)

fix llm conversations state management for new conversations

---

packages/lesswrong/components/languageModels/LanguageModelChat.tsx

(also I made the input textbox be able to expand  a bunch more)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208173766012629) by [Unito](https://www.unito.io)

LLM chat has submit button

---

.eslintrc.js
packages/lesswrong/components/ea-forum/users/EAGApplicationImportForm.tsx
packages/lesswrong/components/languageModels/LlmChatWrapper.tsx
packages/lesswrong/components/review/ReviewVoteTableRow.tsx
packages/lesswrong/lib/vulcan-lib/components.tsx
packages/lesswrong/server/languageModels/promptUtils.ts
packages/lesswrong/server/resolvers/anthropicResolvers.ts
packages/lesswrong/server/sql/InsertQuery.ts
packages/lesswrong/server/sql/Query.ts
packages/lesswrong/server/updateScores.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208174785446449) by [Unito](https://www.unito.io)

Stream llm message chunks

---

packages/lesswrong/components/languageModels/LanguageModelChat.tsx
packages/lesswrong/lib/collections/llmMessages/schema.ts
packages/lesswrong/server/resolvers/anthropicResolvers.ts

- don't show context used message to user when no context is used
- improve scrolling behavior (you can cause it to not scroll when streaming)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208175012281405) by [Unito](https://www.unito.io)

LLM Chat Further Improvements 2024-08-28

---

packages/lesswrong/components/tagging/TagPage.tsx
packages/lesswrong/components/tagging/subforums/SubforumWikiTab.tsx

Feature requested by Lizka, copy written by Toby
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208170045290513) by [Unito](https://www.unito.io)

Add tooltip explaining meaning of 'tag relevance'

---

packages/lesswrong/components/languageModels/LanguageModelLauncherButton.tsx
packages/lesswrong/components/languageModels/PopupLanguageModelChat.tsx

The cookie wasn't being set with global path and therefore was not being applied when opening different pages.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208218418716144) by [Unito](https://www.unito.io)

Fix LLM Chat Show cookie by setting path

---

packages/lesswrong/themes/siteThemes/lesswrongTheme.ts

So I was gonna have my second color option be "some kind of green" but man I just really think all the greens suck. They either look sickly yellow or are even lower contrast than the other grey one or are weird neon that is also not actually a good contrast.
So I ended up just finding a grey that's in-between grey[500] and grey[600] (which was barely distinguishable). The contrast ratio here is 3.45 (compared to the previous one's 2.67).

Visited link new color

---

packages/lesswrong/components/spotlights/SpotlightItem.tsx
packages/lesswrong/themes/siteThemes/lesswrongTheme.ts

non-hotfix version of this PR:
https://github.com/ForumMagnum/ForumMagnum/pull/9708
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208219047135105) by [Unito](https://www.unito.io)

Fix spotlight bottom [non-hotfix]

---

packages/lesswrong/components/linkPreview/FootnotePreview.tsx

This comes up in two known situations:
* On some old posts authored in raw HTML, where we aren't able to find the footnote body, such as [this one](https://www.lesswrong.com/posts/ACGeaAk6KButv2xwQ/the-halo-effect)
* On comments that are truncated in a way that removes the footnote contents
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208218877745086) by [Unito](https://www.unito.io)

Suppress sidenotes when we fail to find nonempty footnote contents

---

packages/lesswrong/components/comments/CommentsTableOfContents.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208218912927942) by [Unito](https://www.unito.io)

Don't hide the comments-ToC post title during pageload

---

packages/lesswrong/components/comments/SideCommentIcon.tsx
packages/lesswrong/components/form-components/LocationFormComponent.tsx
packages/lesswrong/components/posts/TableOfContents/MultiToCLayout.tsx
packages/lesswrong/components/sequences/TopPostsPage.tsx
packages/lesswrong/lib/consoleFilters.ts
packages/lesswrong/themes/createThemeDefaults.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208325748479704) by [Unito](https://www.unito.io)

Accumulated small fixes

---

packages/lesswrong/components/seasonal/petrovDay/OptIntoPetrovButton.tsx

improves the mobile experience for Petrov Opt In
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208396122551572) by [Unito](https://www.unito.io)

Mobile petrov opt in

---

packages/lesswrong/components/seasonal/petrovDay/OptIntoPetrovButton.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208402951605256) by [Unito](https://www.unito.io)

fix petrov opt-in confirmation message to say display name

---

packages/lesswrong/components/seasonal/petrovDay/OptIntoPetrovButton.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208402974644291) by [Unito](https://www.unito.io)

Merge master to lw-deploy 2024 09 25

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/server/serverSentEvents.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208414454073808) by [Unito](https://www.unito.io)

remove check for active collaborative session users

---

packages/lesswrong/components/seasonal/petrovDay/PetrovLaunchConsole.tsx
packages/lesswrong/components/seasonal/petrovDay/PetrovWarningConsole.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208414083257569) by [Unito](https://www.unito.io)

Petrov Color fixes

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/seasonal/petrovDay/PetrovGameWrapper.tsx
packages/lesswrong/lib/collections/petrovDayActions/views.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208414502246044) by [Unito](https://www.unito.io)

Citizen info

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/LWHome.tsx
packages/lesswrong/components/seasonal/petrovDay/PetrovAdminConsole.tsx
packages/lesswrong/components/seasonal/petrovDay/PetrovGameWrapper.tsx

This
– adds the Petrov Day spotlight
– adds better timestamps for PetrovAdmins
– updates the image for West Wrong

Petrov Fixes (adjust image size, add spotlight)

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/server/resolvers/petrovDay2024Resolvers.ts
packages/lesswrong/server/serverSentEvents.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208425538783048) by [Unito](https://www.unito.io)

Merge master into LW Deploy (Petrov Wrap-up)

---

packages/lesswrong/lib/betas.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208415055743032) by [Unito](https://www.unito.io)

Enable sidenotes on AF

---

packages/lesswrong/components/comments/CommentsTableOfContents.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208452424886271) by [Unito](https://www.unito.io)

Don't show usernames on deleted comments in comments-ToC

---

packages/lesswrong/server/repos/TweetsRepo.ts

Requested by Toby
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208456180462935) by [Unito](https://www.unito.io)

Don't tweet posts that are not allowed on the frontpage

---

packages/lesswrong/components/forumEvents/ForumEventPoll.tsx

I'm testing the banner on staging currently, I will add any fixes for minor bugs to this PR and then merge it when I'm happy the whole thing is ready
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208485416019992) by [Unito](https://www.unito.io)

[EA] Animal welfare debate week small fixes

---

packages/lesswrong/server.ts
packages/lesswrong/server/scripts/backfillGoogleVertex.ts
packages/lesswrong/server/scripts/backfillRecombee.ts
packages/lesswrong/server/scripts/exportAEStudiosData.ts

Having done it twice, seems worth just having a script for it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208471346620196) by [Unito](https://www.unito.io)

script to export data for ae studios

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx
packages/lesswrong/components/posts/TableOfContents/PostFixedPositionToCHeading.tsx
packages/lesswrong/components/posts/TableOfContents/TableOfContents.tsx
packages/lesswrong/components/posts/TableOfContents/index.ts

(LW-specific) Adds the post word count to the ToC.
(This PR is a draft because I'm not thrilled with how this looks in practice. If we decide this UI works, there might be refactoring to follow.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208290964440368) by [Unito](https://www.unito.io)

Show word count in ToC

---

packages/lesswrong/components/forumEvents/ForumEventPoll.tsx
packages/lesswrong/components/forumEvents/ForumEventResultIcon.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208522665006376) by [Unito](https://www.unito.io)

Allow expanding debate week result columns

---

packages/lesswrong/components/tagging/TagsTooltip.tsx

Fix tag hover previews not appearing on https://www.lesswrong.com/tags/all and https://effective-altruism.com/topics/all . These pages avoid prefetching hover-previewable tags because they have a huge number of links and the prefetch would be too slow; when prefetch is turned off, we weren't fetching them at all.
Also refactor so that `Title` isn't an inline component (which, even with `useCallback`, is still an antipattern and can cause loss of state).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208506438527062) by [Unito](https://www.unito.io)

Fix tag hover-previews on the All Tags page (/tags/all or /topics/all)

---

packages/lesswrong/components/posts/TableOfContents/PostFixedPositionToCHeading.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208523694727941) by [Unito](https://www.unito.io)

Replace word count with min read

---

packages/lesswrong/components/posts/PostsPage/PostBody.tsx

oops.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208631526937466) by [Unito](https://www.unito.io)

hide empty glossaries on posts

---

packages/lesswrong/components/posts/PostsUserAndCoauthors.tsx
packages/lesswrong/themes/siteThemes/lesswrongTheme.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208654809166407) by [Unito](https://www.unito.io)

Deploy font change

---

packages/lesswrong/server/autocompleteEndpoint.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208651797939937) by [Unito](https://www.unito.io)

Upgrade Claude model for autocomplete

---

packages/lesswrong/server/apolloServer.ts
packages/lesswrong/server/givingSeason/currencies.ts
packages/lesswrong/server/givingSeason/webhook.ts
packages/lesswrong/server/repos/DatabaseMetadataRepo.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208676556841376) by [Unito](https://www.unito.io)

Giving season 2024 donation total

---

packages/lesswrong/components/quickTakes/QuickTakesEntry.tsx

#9903 introduced several bugs:
1. The tag input is shown when the form is unexpanded (it shouldn't be)
2. The login flow is incorrectly triggered for friendly UI
3. The form crashes with an exception when the users finishes logging in
4. The new user message wasn't forum gated and the wording doesn't suit the EA Forum
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208672667512219) by [Unito](https://www.unito.io)

Fix various quick takes bugs introduced in #9903

---

packages/lesswrong/components/posts/PostsNewForm.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208673423554142) by [Unito](https://www.unito.io)

Changed fragment to include contents, so that event duplication works

---

packages/lesswrong/server/givingSeason/webhook.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208686759023718) by [Unito](https://www.unito.io)

Remove every.org verification

---

packages/lesswrong/components/common/HomeTagBar.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208686659799333) by [Unito](https://www.unito.io)

Fix forum event tag colors

---

packages/lesswrong/components/common/Header.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208686931626550) by [Unito](https://www.unito.io)

Add post page banner for giving season 2024

---

packages/lesswrong/components/posts/PostsTitle.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208686979539385) by [Unito](https://www.unito.io)

Fix color of forum event tags in post titles

---

packages/lesswrong/components/common/Header.tsx
packages/lesswrong/components/posts/PostsTitle.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208687253295370) by [Unito](https://www.unito.io)

[EA] Deploy fix for forum event tags in post titles

---

packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
packages/lesswrong/components/users/EAUserTooltipContent.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208706523442347) by [Unito](https://www.unito.io)

Show matched amount in Giving Season 2024 banner

---

packages/lesswrong/components/common/Header.tsx
packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
packages/lesswrong/components/forumEvents/useGivingSeasonEvents.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208706671457904) by [Unito](https://www.unito.io)

Update banner links for giving season 2024

---

packages/lesswrong/components/linkPreview/PostLinkPreview.tsx

Regression from commit 8897c0d4c9fad637a48cae5b77e11e9cd3e3a448 in #9882
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208708845820317) by [Unito](https://www.unito.io)

Fix broken link dots

---

packages/lesswrong/components/forumEvents/useGivingSeasonEvents.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208734256777803) by [Unito](https://www.unito.io)

Fix white header background if outside hard-coded event dates

---

packages/lesswrong/server/givingSeason/resolvers.ts
packages/lesswrong/server/repos/PostsRepo.ts

As discussed on Slack
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208740659614633) by [Unito](https://www.unito.io)

Add moderation/karma filters for giving season activity feed

---

packages/lesswrong/components/forumEvents/useGivingSeasonEvents.tsx

As requested on Slack by Toby.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208746796710488) by [Unito](https://www.unito.io)

Update copy for Funding Strategy Week 2024

---

packages/lesswrong/lib/collections/posts/schema.tsx

Regression from commit c920798 in PR #9966 (we should probably add a playwright test for this, but I don't have time right now)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208777177118655) by [Unito](https://www.unito.io)

Fix transfering posts to new accounts

---

package.json
packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/admin/AdminHome.tsx
packages/lesswrong/components/comments/CommentsNewForm.tsx
packages/lesswrong/components/common/Header.tsx
packages/lesswrong/components/forumEvents/votingPortal/AdminElectionCandidates.tsx
packages/lesswrong/components/forumEvents/votingPortal/DeleteElectionCandidateDialog.tsx
packages/lesswrong/components/forumEvents/votingPortal/EditElectionCandidate.tsx
packages/lesswrong/components/forumEvents/votingPortal/VotingPortalPage.tsx
packages/lesswrong/components/forumEvents/votingPortal/hooks.ts
packages/lesswrong/components/sequences/TopPostsPage.tsx
packages/lesswrong/components/users/FriendlyUsersProfile.tsx
packages/lesswrong/components/users/UserCommentMarkers.tsx
packages/lesswrong/lib/collections/electionCandidates/schema.ts
packages/lesswrong/lib/collections/users/fragments.ts
packages/lesswrong/lib/collections/users/schema.ts
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts
packages/lesswrong/lib/routes.ts
packages/lesswrong/lib/voting/reactions.tsx
packages/lesswrong/server.ts
packages/lesswrong/server/callbacks/electionCandidateCallbacks.ts
packages/lesswrong/server/givingSeason/resolvers.ts
packages/lesswrong/server/migrations/20241117T124649.add_giving_season_2024_voted_flair.ts
packages/lesswrong/server/repos/ElectionVotesRepo.ts
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/themeType.ts
schema/accepted_schema.sql
yarn.lock

Voting portal for 2024 giving season. [Relevant figma](https://www.figma.com/design/3WOTZHH10ZBXSZPWw9omM3/Giving-Season?node-id=1611-2021&node-type=text&m=dev).
The page is located at `/voting-portal`.
Heavy inspiration taken from #8305 and #8622.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208768815743164) by [Unito](https://www.unito.io)

Giving season 2024 voting portal

---

packages/lesswrong/components/common/HomeTagBar.tsx
packages/lesswrong/components/hooks/useCurrentForumEvent.tsx
packages/lesswrong/components/posts/PostsTitle.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208786957271716) by [Unito](https://www.unito.io)

Marginal funding week in tag bar

---

packages/lesswrong/components/forumEvents/votingPortal/VotingPortalPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208788492480947) by [Unito](https://www.unito.io)

Contain voting portal candidate logos

---

packages/lesswrong/components/common/Header.tsx
packages/lesswrong/components/forumEvents/votingPortal/VotingPortalPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208788660474629) by [Unito](https://www.unito.io)

[EA] Deploy voting portal candidate logo improvements

---

packages/lesswrong/components/forumEvents/votingPortal/hooks.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208791842638463) by [Unito](https://www.unito.io)

Increase voting portal candidate limit to 100

---

packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
packages/lesswrong/components/forumEvents/votingPortal/VotingPortalPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208804619490303) by [Unito](https://www.unito.io)

[EA] Deploy minor tweaks to voting banner

---

packages/lesswrong/components/forumEvents/useGivingSeasonEvents.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208812417454913) by [Unito](https://www.unito.io)

[EA] Show donation election leaderboard

---

packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
packages/lesswrong/components/forumEvents/useGivingSeasonEvents.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208812426003887) by [Unito](https://www.unito.io)

[EA] Deploy forcing showing the donation election leaderboard

---

packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208797989775979) by [Unito](https://www.unito.io)

Improve layout of donation election buttons on mobile

---

packages/lesswrong/components/forumEvents/DonationElectionLeaderboard.tsx
packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
packages/lesswrong/components/forumEvents/useGivingSeasonEvents.tsx
packages/lesswrong/components/forumEvents/votingPortal/VotingPortalPage.tsx
packages/lesswrong/server/givingSeason/resolvers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208817597539584) by [Unito](https://www.unito.io)

[EA] Deploy donation election improvements

---

packages/lesswrong/components/search/SearchPageTabbed.tsx

Fixes  #9991
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208818390064076) by [Unito](https://www.unito.io)

Fix search filters on mobile

---

packages/lesswrong/components/ea-forum/EAGBanner.tsx
packages/lesswrong/components/search/SearchPageTabbed.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208853967040427) by [Unito](https://www.unito.io)

[EA] deploy EAGxSingapore banner

---

packages/lesswrong/components/bookmarks/ReadHistoryTab.tsx
packages/lesswrong/components/posts/UserSuggestNominations.tsx
packages/lesswrong/components/review/FrontpageReviewWidget.tsx
packages/lesswrong/server/repos/PostsRepo.ts
packages/lesswrong/server/resolvers/postResolvers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208862557137071) by [Unito](https://www.unito.io)

Display posts you've read from a given year to be considered for review

---

packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
packages/lesswrong/components/forumEvents/votingPortal/VotingPortalPage.tsx
packages/lesswrong/lib/givingSeason/index.ts
packages/lesswrong/server/givingSeason/resolvers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208859175119155) by [Unito](https://www.unito.io)

[EA] Add setting to close voting in the donation election

---

packages/lesswrong/components/common/FundraisingThermometer.tsx
packages/lesswrong/components/common/Header.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208874540551990) by [Unito](https://www.unito.io)

overflow hidden undo

---

packages/lesswrong/components/common/FundraisingThermometer.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208874612058251) by [Unito](https://www.unito.io)

transition on loading stripe data

---

packages/lesswrong/components/ea-forum/EAHome.tsx
packages/lesswrong/lib/reviewUtils.tsx

Regression from #10060
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208888792279536) by [Unito](https://www.unito.io)

Remove review widget from EA forum home page

---

packages/lesswrong/components/common/HomeTagBar.tsx
packages/lesswrong/components/forumEvents/DonationElectionLeaderboard.tsx
packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
packages/lesswrong/components/forumEvents/useGivingSeasonEvents.tsx
packages/lesswrong/components/forumEvents/votingPortal/VotingPortalPage.tsx
packages/lesswrong/components/hooks/useCurrentForumEvent.tsx
packages/lesswrong/components/posts/PostsTitle.tsx
packages/lesswrong/lib/givingSeason/index.ts
packages/lesswrong/server/givingSeason/resolvers.ts

See https://cea-core.slack.com/archives/C03G0AQ925P/p1732637687034919
- Add the "hidden" banner for the intermission weeks and update styles for previous weeks
- Close voting and donating for the election
- Disable scrolling between weeks (it doesn't work very well now that one of the weeks makes the banner disappear)
Note that you can't easily test this on the prod DB as it requires the correct forum event to be active, but it should work correctly already on the dev DB.
This PR is pretty messy - there's a lot of stuff commented out that could probably be deleted just because I'm not 100% sure exactly what we'll want to bring back for the remaining weeks later in December.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208894175510790) by …

Giving season 2024 post-election banner

---

packages/lesswrong/components/ea-forum/onboarding/EAOnboardingUserStage.tsx
packages/lesswrong/components/form-components/LocationFormComponent.tsx
packages/lesswrong/components/hooks/usePostsListView.tsx
packages/lesswrong/components/notifications/NotifyMeButton.tsx
packages/lesswrong/components/posts/PostsList2.tsx
packages/lesswrong/components/posts/usePostsList.ts
packages/lesswrong/components/quickTakes/QuickTakesSection.tsx
packages/lesswrong/components/tagging/TagPage.tsx
packages/lesswrong/components/tagging/TagsListItem.tsx
packages/lesswrong/lib/publicSettings.ts

Various small improvements from http://modernswing.forum
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208694849062058) by [Unito](https://www.unito.io)

Misc fixes/improvements from new forum setup (batch #4)

---

packages/lesswrong/components/common/FundraisingThermometer.tsx
packages/lesswrong/components/common/LWHome.tsx
packages/lesswrong/components/posts/AllPostsPage.tsx
packages/lesswrong/components/posts/ExternalPostImporter.tsx
packages/lesswrong/components/posts/PostsByVote.tsx
packages/lesswrong/components/review/AnnualReviewPage.tsx
packages/lesswrong/components/review/FrontpageReviewWidget.tsx
packages/lesswrong/components/review/NominationsPage.tsx
packages/lesswrong/components/review/ReviewDashboardButtons.tsx
packages/lesswrong/components/review/ReviewPhaseInformation.tsx
packages/lesswrong/components/review/ReviewVotingPage.tsx
packages/lesswrong/components/review/ReviewVotingPageMenu.tsx
packages/lesswrong/components/review/ReviewsList.tsx
packages/lesswrong/components/review/ReviewsPage.tsx
packages/lesswrong/components/tagging/PostsTagsList.tsx
packages/lesswrong/lib/collections/posts/views.ts
packages/lesswrong/lib/reviewUtils.tsx
packages/lesswrong/lib/routes.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208907850941905) by [Unito](https://www.unito.io)

2023 Review UI Improvements

---

packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
packages/lesswrong/components/forumEvents/useGivingSeasonEvents.tsx

To be deployed on Thursday 5th December
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208896515739360) by [Unito](https://www.unito.io)

Giving Season 2024 intermission week banner

---

packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/routes.ts

Made a quick page that we can link to in our team's instagram bio, which links to some relevant posts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208908949916541) by [Unito](https://www.unito.io)

[EA Forum only] instagram landing page

---

packages/lesswrong/components/posts/PostsByVote.tsx
packages/lesswrong/lib/collections/posts/views.ts

Fixes the frontpage filtering, and adds nicer tooltips
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208917284736091) by [Unito](https://www.unito.io)

Fix filtering on PostsByVote page

---

packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx
packages/lesswrong/components/ea-forum/onboarding/EAOnboardingUserStage.tsx
packages/lesswrong/components/form-components/LocationFormComponent.tsx
packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
packages/lesswrong/components/forumEvents/useGivingSeasonEvents.tsx
packages/lesswrong/components/hooks/usePostsListView.tsx
packages/lesswrong/components/notifications/NotifyMeButton.tsx
packages/lesswrong/components/posts/PostsList2.tsx
packages/lesswrong/components/posts/usePostsList.ts
packages/lesswrong/components/quickTakes/QuickTakesSection.tsx
packages/lesswrong/components/tagging/TagPage.tsx
packages/lesswrong/components/tagging/TagsListItem.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/publicSettings.ts
packages/lesswrong/lib/routes.ts
packages/lesswrong/server/type3.ts

Branch lw-deploy-with-master merges master into lw-deploy. After this is merged, I can make a PR from lw-deploy into master
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208926250169003) by [Unito](https://www.unito.io)

Lw deploy with master

---

packages/lesswrong/components/common/FundraisingThermometer.tsx
packages/lesswrong/components/posts/PostsPage/PostsPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208926371362063) by [Unito](https://www.unito.io)

Add fundraising thermometer to fundraising post

---

packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208938748387830) by [Unito](https://www.unito.io)

[EA Forum only] add some Instagram links, including Allan AMA

---

packages/lesswrong/components/common/RecaptchaWarning.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208938936718063) by [Unito](https://www.unito.io)

[EA] deploy some new instagram links

---

packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208978081233436) by [Unito](https://www.unito.io)

[EA Forum only] IG update

---

packages/lesswrong/components/review/AnnualReviewPage.tsx
packages/lesswrong/components/review/FrontpageReviewWidget.tsx
packages/lesswrong/components/review/QuickReviewPage.tsx
packages/lesswrong/components/review/QuickReviewPage2022.tsx
packages/lesswrong/components/review/ReviewPhaseInformation.tsx
packages/lesswrong/components/review/ReviewProgressNominations.tsx
packages/lesswrong/components/review/ReviewProgressReviews.tsx
packages/lesswrong/components/review/ReviewVotingPage.tsx
packages/lesswrong/lib/components.ts
packages/lesswrong/lib/reviewUtils.tsx
packages/lesswrong/lib/routes.ts

Updates the Discussion Phase to handle the new AnnualReview component UI
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208982110402353) by [Unito](https://www.unito.io)

Review improvements

---

packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
packages/lesswrong/components/forumEvents/useGivingSeasonEvents.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208987761401189) by [Unito](https://www.unito.io)

Remove giving season 2024 intermission banner

---

packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsItem.tsx

Regression from commit 29972a4dce92893864075d502d3a9366bba93bcd in PR #10057
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208990441657279) by [Unito](https://www.unito.io)

Fix styles for post titles in sunshine side bar

---

packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209010697627046) by [Unito](https://www.unito.io)

[EA Forum only] more IG links

---

build.ts
jest.config.ts
packages/lesswrong/client/clientStartup.ts
packages/lesswrong/stubs/viteClient/viteReload.ts
packages/lesswrong/viteClient/viteReload.ts
tsconfig-client.json
tsconfig-server.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208997330749907) by [Unito](https://www.unito.io)

Fix warnings on startup about import.meta.hot

---

packages/lesswrong/server/ckEditor/ckEditorApi.ts

…and make html logging less noisy
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208513936484441) by [Unito](https://www.unito.io)

fix assignment to Globals.cke.log to respect references to 'this'

---

packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209028770918419) by [Unito](https://www.unito.io)

[EA Forum only] IG again

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/FundraisingThermometer.tsx
packages/lesswrong/components/common/LWHome.tsx
packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/lib/publicSettings.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209044024439794) by [Unito](https://www.unito.io)

New Thermometer and also Christmas orbs

---

packages/lesswrong/components/posts/ElicitBlock.tsx
packages/lesswrong/lib/collections/elicitQuestionPredictions/schema.ts
packages/lesswrong/server/migrations/20241230T051222.elicitQuestionPredictionNullable.ts
packages/lesswrong/server/resolvers/elicitPredictions.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209057907793616) by [Unito](https://www.unito.io)

Fix not being able to un-make predictions

---

packages/lesswrong/server/resolvers/googleVertexResolvers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209065491217811) by [Unito](https://www.unito.io)

Don't let Google Vertex exceptions crash the client

---

packages/lesswrong/components/ea-forum/EABestOfPage.tsx

I noticed that our "Best of" page was out-of-date so I've updated it, in particular I refreshed the "Highlights this year" list
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209063183320965) by [Unito](https://www.unito.io)

[EA Forum only] update Best of page

---

packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209067381278516) by [Unito](https://www.unito.io)

[EA Forum only] add another IG link

---

packages/lesswrong/components/ea-forum/wrapped/WrappedPersonalitySection.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209071461572853) by [Unito](https://www.unito.io)

[EA] Use raw video element to playback Wrapped animations

---

packages/lesswrong/components/ea-forum/wrapped/WrappedPersonalitySection.tsx
packages/lesswrong/components/ea-forum/wrapped/videos.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209071815915169) by [Unito](https://www.unito.io)

[EA]  Update Wrapped animation brightnesses

---

packages/lesswrong/components/ea-forum/wrapped/WrappedPersonalitySection.tsx
packages/lesswrong/components/ea-forum/wrapped/WrappedSummarySection.tsx
packages/lesswrong/components/ea-forum/wrapped/videos.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209071978388937) by [Unito](https://www.unito.io)

[EA] Deploy wrapped animation brightness updates

---

packages/lesswrong/components/ea-forum/wrapped/WrappedPersonalitySection.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209072325338585) by [Unito](https://www.unito.io)

[EA] Fix switching Wrapped video src in mobile safari

---

packages/lesswrong/components/ea-forum/wrapped/WrappedPersonalitySection.tsx
packages/lesswrong/components/ea-forum/wrapped/videos.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209072348520295) by [Unito](https://www.unito.io)

[EA] Deploy Wrapped mobile safari video fix

---

packages/lesswrong/components/ea-forum/wrapped/WrappedApp.tsx
packages/lesswrong/components/ea-forum/wrapped/WrappedPersonalitySection.tsx
packages/lesswrong/components/ea-forum/wrapped/WrappedSection.tsx
packages/lesswrong/components/ea-forum/wrapped/WrappedWelcomeMessage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209076200189188) by [Unito](https://www.unito.io)

EA Wrapped 2024 - More tweaks

---

packages/lesswrong/components/ea-forum/wrapped/WrappedPersonalitySection.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209076451113234) by [Unito](https://www.unito.io)

EA Wrapped 2024 even more tweaks

---

packages/lesswrong/components/ea-forum/wrapped/WrappedApp.tsx
packages/lesswrong/components/ea-forum/wrapped/WrappedPersonalitySection.tsx

Slowly losing my mind
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209077325482700) by [Unito](https://www.unito.io)

Even more iphone safari garbage stabs in the dark

---

packages/lesswrong/components/ea-forum/wrapped/WrappedApp.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209093079188499) by [Unito](https://www.unito.io)

Disable wrapped navigation arrows when typing in text box

---

packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx
packages/lesswrong/components/ea-forum/wrapped/WrappedApp.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209092855251743) by [Unito](https://www.unito.io)

[EA] Deploy wrapped arrow navigation fix

---

packages/lesswrong/components/ea-forum/wrapped/WrappedWelcomeMessage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209093285834615) by [Unito](https://www.unito.io)

[EA] Fix wrapped loading spinner getting cut in half

---

packages/lesswrong/components/ea-forum/wrapped/WrappedApp.tsx
packages/lesswrong/components/ea-forum/wrapped/WrappedWelcomeMessage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209093239221955) by [Unito](https://www.unito.io)

[EA] Deploy wrapped loading spinner fix

---

packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx
packages/lesswrong/components/posts/PostsPage/PostPageReviewButton.tsx

…hen they don't have the button
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209095743357724) by [Unito](https://www.unito.io)

Don't add whitespace for PostPageReviewButton to the start of posts when they don't have the button

---

packages/lesswrong/components/common/FundraisingThermometer.tsx
packages/lesswrong/components/common/HashLink.tsx
packages/lesswrong/lib/reactRouterWrapper.tsx

Add a countdown to the thermometer. Also add an easter-egg of when the countdown is less than 72 hours and you hover over the donate button for more than 2 seconds.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209102869715495) by [Unito](https://www.unito.io)

Add thermometer countdown

---

packages/lesswrong/components/common/FundraisingThermometer.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209120765165534) by [Unito](https://www.unito.io)

Fix broken front page SSR

---

packages/lesswrong/components/posts/PostsNewForm.tsx
packages/lesswrong/components/review/FrontpageReviewWidget.tsx
packages/lesswrong/components/tagging/TagPage.tsx
packages/lesswrong/lib/collections/posts/views.ts
packages/lesswrong/lib/reviewUtils.tsx

This PR adds the a "Longform Review" button to the frontpage, which takes you to a post page with the "2023 Longform Review" tag active.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209121709624657) by [Unito](https://www.unito.io)

Longform Review Button

---

packages/lesswrong/components/common/FundraisingThermometer.tsx
packages/lesswrong/lib/publicSettings.ts

Shoggoths!
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209146952468103) by [Unito](https://www.unito.io)

add next thermometer

---

packages/lesswrong/lib/abTests.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209128689613237) by [Unito](https://www.unito.io)

Delete unused A/B tests

---

packages/lesswrong/components/tagging/TagPageButtonRow.tsx
packages/lesswrong/components/votes/lwReactions/ReactionsAndLikesVote.tsx
packages/lesswrong/server/scripts/arbitalImport/arbitalImport.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209156141891979) by [Unito](https://www.unito.io)

Login popups for tag like button and new lens

---

package.json
packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/FundraisingThermometer.tsx
scripts/postinstall.sh
yarn.lock

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209165318753795) by [Unito](https://www.unito.io)

Resolve merge conflicts for lw-deploy into master

---

packages/lesswrong/components/common/Header.tsx
packages/lesswrong/components/common/LWHome.tsx
packages/lesswrong/components/review/FrontpageReviewWidget.tsx

Now:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209165170879504) by [Unito](https://www.unito.io)

Remove unnecessary padding in Frontpage Review Widget

---

packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsList.tsx

Added (but not gated) in #10249
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209168620860066) by [Unito](https://www.unito.io)

Forum-gate curation warning styles

---

packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx

Based on #10230. Related to, but not necessarily entirely solving #10224.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209168771138089) by [Unito](https://www.unito.io)

[EA] Sidebar copyright link

---

packages/lesswrong/components/review/ReviewVoteTableRow.tsx

Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209173600509121) by [Unito](https://www.unito.io)

fix commentIcon styling and add commentWrapper behavior

---

packages/lesswrong/components/analytics/AuthorAnalyticsPage.tsx
packages/lesswrong/components/comments/CommentsItem/useCommentLink.tsx
packages/lesswrong/components/linkPreview/HoverPreviewLink.tsx
packages/lesswrong/components/tagging/LWTagPage.tsx
packages/lesswrong/components/tagging/lenses/LensTab.tsx
packages/lesswrong/lib/arbital/useTagLenses.tsx
packages/lesswrong/lib/routeUtil.tsx
packages/lesswrong/lib/vulcan-core/appContext.ts
packages/lesswrong/lib/vulcan-lib/routes.ts

Arbital links are broken because we haven't actually run the import yet.  Undo the two changes responsible for that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209186037164455) by [Unito](https://www.unito.io)

Arbital import merged

---

packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx
packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx

Taking it down as a new event is starting on Monday. Also made some IG link updates.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209187501649530) by [Unito](https://www.unito.io)

[EA Forum only] remove rhs Wrapped ad

---

packages/lesswrong/components/tagging/SingleLineTagUpdates.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209189211191720) by [Unito](https://www.unito.io)

fix npe when accessing documentDeletions in SingleLineTagUpdates

---

packages/lesswrong/components/votes/lwReactions/ReactionHoverTopRow.tsx
packages/lesswrong/components/votes/lwReactions/UsersWhoReacted.tsx

Before: 
After: 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209190684579495) by [Unito](https://www.unito.io)

Fix React ballot alignment

---

packages/lesswrong/components/common/ContentItemTruncated.tsx
packages/lesswrong/lib/voting/namesAttachedReactions.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209197374592301) by [Unito](https://www.unito.io)

Fix truncation suffix appearing on content that's already expanded

---

packages/lesswrong/server/manualMigrations/2022-11-08-rehostPostImages.ts
packages/lesswrong/server/scripts/convertImagesToCloudinary.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209114188742667) by [Unito](https://www.unito.io)

Improve image mirroring to Cloudinary, including auto-recovery of images from archive.org if their original source no longer works

---

packages/lesswrong/lib/collections/tags/schema.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209294165459428) by [Unito](https://www.unito.io)

allow users to create wiki-only pages; forum gated

---

packages/lesswrong/components/review/FrontpageReviewWidget.tsx
packages/lesswrong/lib/reviewUtils.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209296425091730) by [Unito](https://www.unito.io)

Fix review end dates [hotfix]

---

packages/lesswrong/components/review/ReviewVotingCanvas.tsx
packages/lesswrong/lib/reviewUtils.tsx
packages/lesswrong/themes/zIndexes.ts

Here it is on the smallest screen before it disappears:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209300187498643) by [Unito](https://www.unito.io)

Make VotingCTA visible on smaller screens

---

packages/lesswrong/server/resolvers/paginatedResolver.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209197092623889) by [Unito](https://www.unito.io)

Fix createPaginatedResolver saving results even when cache is disabled

---

packages/lesswrong/server/scripts/arbitalImport/arbitalImport.ts
packages/lesswrong/server/scripts/arbitalImport/markdownService.tsx

- Fix garbled conversion of "[ text]" redlinks
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209346889441137) by [Unito](https://www.unito.io)

Follow-up Arbital fixes

---

packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx
packages/lesswrong/components/votes/OverallVoteAxis.tsx

I feel like the current "How much do you like this overall?" is not really the reason we want people upvoting, in particular because it invites people to upvote based on how much they agree (and downvote if they disagree). I've updated the wording to hopefully encourage people to upvote productive/valuable content even if they disagree with it.
[Lizka calls this the "appreciation vote"](https://forum.effectivealtruism.org/posts/Y8gkABpa9R6ktkhYt/forum-user-manual#Two_Factor_Voting), which I kinda like, so maybe we could go with "How much do you appreciate this?" instead.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209373602727550) by [Unito](https://www.unito.io)

[FriendlyUI only] update overall karma tooltip question

---

packages/lesswrong/components/common/LWTooltip.tsx
packages/lesswrong/components/common/withHover.tsx
packages/lesswrong/components/tagging/AllWikiTagsPage.tsx
packages/lesswrong/components/tagging/ArbitalLinkedPagesRightSidebar.tsx
packages/lesswrong/components/tagging/ConceptItem.tsx
packages/lesswrong/components/tagging/WikiTagGroup.tsx
packages/lesswrong/components/votes/lwReactions/ReactionsAndLikesVote.tsx
packages/lesswrong/lib/editor/mentionsConfig.tsx
packages/lesswrong/lib/routes.ts
packages/lesswrong/server.ts
packages/lesswrong/server/callbacks/multiDocumentCallbacks.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209347078278241) by [Unito](https://www.unito.io)

Arbital bug fixes 20250205

---

packages/lesswrong/components/tagging/history/TagHistoryPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209393003521684) by [Unito](https://www.unito.io)

Don't SSR the wiki history page

---

packages/lesswrong/components/tagging/TagPreview.tsx

…olded
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209404328343419) by [Unito](https://www.unito.io)

display tag title in tooltip if it's not present in opening text and bolded

---

packages/lesswrong/components/posts/LWPostsItem.tsx

Fixes bug from https://github.com/ForumMagnum/ForumMagnum/pull/10368
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209404211972804) by [Unito](https://www.unito.io)

fix the dismiss button on mobile post items

---

packages/lesswrong/server/scripts/arbitalImport/arbitalImport.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209403790470210) by [Unito](https://www.unito.io)

Fix backdating of imported Arbital comment lastEditedAt and likes votedAt

---

packages/lesswrong/server/scripts/arbitalImport/markdownService.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209403430095191) by [Unito](https://www.unito.io)

Fix some missing redlink placeholder pages

---

packages/lesswrong/components/tagging/TagPageButtonRow.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209413513919401) by [Unito](https://www.unito.io)

fix missing create lens menu item

---

packages/lesswrong/server.ts
packages/lesswrong/server/scripts/arbitalImport/arbitalImport.ts
packages/lesswrong/server/scripts/arbitalImport/postImportFixups.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209414104243278) by [Unito](https://www.unito.io)

Arbital post-import imported data fixes

---

packages/lesswrong/lib/collections/multiDocuments/collection.ts
packages/lesswrong/lib/collections/multiDocuments/helpers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209427993752470) by [Unito](https://www.unito.io)

Fix an N+1 select when loading tag previews

---

packages/lesswrong/server/resolvers/tagResolvers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209428352612070) by [Unito](https://www.unito.io)

Fix some denormalized fields after swapping lenses

---

packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209431742985124) by [Unito](https://www.unito.io)

[EA Forum only] IG DAW promo

---

packages/lesswrong/server.ts
packages/lesswrong/server/scripts/arbitalImport/arbitalImport.ts
packages/lesswrong/server/scripts/arbitalImport/markdownService.tsx
packages/lesswrong/server/scripts/arbitalImport/reconvertMarkdown.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209437969618619) by [Unito](https://www.unito.io)

Fix arbital markdown issues

---

packages/lesswrong/lib/arbital/useTagLenses.tsx
packages/lesswrong/lib/collections/tags/views.ts
packages/lesswrong/server/scripts/arbitalImport/arbitalImport.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209448332655242) by [Unito](https://www.unito.io)

show deleted tags to admins again, and add a couple fix scripts

---

packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx
packages/lesswrong/components/posts/usePostReadProgress.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209448617055878) by [Unito](https://www.unito.io)

make toc progress bar work on wiki pages

---

packages/lesswrong/lib/collections/posts/annualReviewMarkets.ts
packages/lesswrong/server.ts
packages/lesswrong/server/scripts/resolveReviewMarkets.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209380779041960) by [Unito](https://www.unito.io)

Add script for resolving review markets

---

packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209463256555635) by [Unito](https://www.unito.io)

[EA Forum only] add next IG link

---

packages/lesswrong/components/forumEvents/ForumEventPostPageBanner.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209489406496517) by [Unito](https://www.unito.io)

[EA] Only show post page event banner if there is a description

---

packages/lesswrong/components/admin/AdminMetadata.tsx
packages/lesswrong/components/admin/AdminSynonymsPage.tsx
packages/lesswrong/components/admin/migrations/MigrationsDashboard.tsx
packages/lesswrong/components/ea-forum/EADigestPage.tsx
packages/lesswrong/components/ea-forum/TargetedJobAdSection.tsx
packages/lesswrong/components/ea-forum/onboarding/EAOnboardingUserStage.tsx
packages/lesswrong/components/ea-forum/wrapped/hooks.tsx
packages/lesswrong/components/form-components/FMCrosspostControl.tsx
packages/lesswrong/components/forumEvents/ForumEventPoll.tsx
packages/lesswrong/components/forumEvents/ForumEventStickers.tsx
packages/lesswrong/components/hooks/useAnalytics.ts
packages/lesswrong/components/hooks/useExpandedFrontpageSection.tsx
packages/lesswrong/components/hooks/useForeignCrosspost.ts
packages/lesswrong/components/hooks/useMarkConversationRead.ts
packages/lesswrong/components/hooks/useRefreshDbSettings.ts
packages/lesswrong/components/notifications/NotificationsPage/useNotificationDisplays.ts
packages/lesswrong/components/peopleDirectory/usePeopleDirectory.tsx
packages/lesswrong/components/posts/ElicitBlock.tsx
packages/lesswrong/components/recommendations/useRecommendationsAnalytics.ts
packages/lesswrong/components/review/ReviewVotingCanvas.tsx
packages/lesswrong/components/users/CrosspostLoginPage.tsx
packages/lesswrong/components/users/account/UsersEditForm.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209491100558326) by [Unito](https://www.unito.io)

Components don't parse graphql on import, only on use

---

packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209505700727577) by [Unito](https://www.unito.io)

[EA Forum only] add IG link

---

packages/lesswrong/components/forumEvents/ForumEventFrontpageBanner.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209500083516100) by [Unito](https://www.unito.io)

Fix forum event frontpage banner getting stretched

---

packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx
packages/lesswrong/components/forumEvents/ForumEventFrontpageBanner.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209507914357512) by [Unito](https://www.unito.io)

[EA] Deploy forum event banner image fix

---

packages/lesswrong/components/common/ForumIcon.tsx
packages/lesswrong/components/users/UsersMenu.tsx
packages/lesswrong/themes/forumTheme.ts

See [designs here](https://www.figma.com/design/OXHicur1IuI6rxoYZqAALG/Author-experience?node-id=13-61&m=dev)
**Admin version:**
cc @agnesstenlund 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209434483825873) by [Unito](https://www.unito.io)

[EA] User menu update

---

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx
packages/lesswrong/components/posts/usePostReadProgress.ts
packages/lesswrong/lib/tableOfContents.ts

- fixes issue where first heading appears at top of ToC even when it's partway down the page
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209591807184144) by [Unito](https://www.unito.io)

Fix Fixed ToC positioning

---

packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209637041988134) by [Unito](https://www.unito.io)

[EA Forum only] add IG links

---

packages/lesswrong/server/search/elastic/ElasticClient.ts

Changes how search works when you @mention in CkEditor. This makes it go through the same path as regular search; in particular, this makes karma matter for sorting, which means that real accounts will tend to show up in search rather than in some cases being buried underneath 0-karma duplicate and test accounts.
The tuning is maybe still not great; in particular, this is sharing settings with the search-bar search, but @mention queries are typically more literal than search-bar searches, so it's probably not desireable to, for example, have posts show up where the search string matches in the author-name field or the body. But this is now at least good enough to work in the "exact name match on a high karma user that has similarly-named zero-karma test accounts" use case, which was …

Improve Mentions search

---

packages/lesswrong/server/resolvers/defaultMutations.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209648616981842) by [Unito](https://www.unito.io)

fix mutation defaults

---

scripts/createCollection.sh

whoops
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209661799876755) by [Unito](https://www.unito.io)

add create collection script

---

packages/lesswrong/components/spotlights/SpotlightItem.tsx

[EA] Round all corners on friendly UI spotlights

---

packages/lesswrong/components/forumEvents/ForumEventPostPagePollSection.tsx

[EA] Fix post page poll section colors

---

packages/lesswrong/components/posts/PostsNewForm.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209707245097923) by [Unito](https://www.unito.io)

Fix crash on /newPost if you have custom moderation guidelines

---

packages/lesswrong/integrationTests/emails.tests.tsx
packages/lesswrong/server/emails/renderEmail.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209707438739829) by [Unito](https://www.unito.io)

Fix relative links in emails

---

.github/workflows/deployEABeta.yaml
packages/lesswrong/components/forumEvents/ForumEventPoll.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209713500962924) by [Unito](https://www.unito.io)

[EA] Deploy banner question styling tweaks

---

packages/lesswrong/components/posts/PostsNewForm.tsx
packages/lesswrong/lib/collections/posts/schema.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209732563956019) by [Unito](https://www.unito.io)

Fix not being able to create new posts if you have moderation guidelines set but they're the empty string

---

packages/lesswrong/lib/collections/users/newSchema.ts

Missed integrating https://github.com/ForumMagnum/ForumMagnum/pull/10477 into the schema refactor PR due to review/merge timing misalignment.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209805150293106) by [Unito](https://www.unito.io)

add back EA forum onCreates for notification setting default overrides

---

packages/lesswrong/components/seasonal/LessOnline2025Banner.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209821031382406) by [Unito](https://www.unito.io)

Update banner styling

---

packages/lesswrong/lib/collections/users/views.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209779234036195) by [Unito](https://www.unito.io)

Don't show deleted users on the /community map

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/ea-forum/GlobalButtonBurst.tsx

https://github.com/user-attachments/assets/52cec3d6-b957-496d-b86e-f7bbc88477df
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209797666595669) by [Unito](https://www.unito.io)

[EA] Add Bulby button

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/common/MusicPlayer.tsx
packages/lesswrong/components/seasonal/LessOnline2025Banner.tsx
packages/lesswrong/themes/globalStyles/globalStyles.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209858546612389) by [Unito](https://www.unito.io)

Activate the music player yolo

---

packages/lesswrong/components/ea-forum/onboarding/EAOnboardingStage.tsx
packages/lesswrong/themes/zIndexes.ts

Adds the ability to log out during account creation.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209847649225326) by [Unito](https://www.unito.io)

[EA] Account creation logout

---

packages/lesswrong/lib/voting/vote.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209860505480691) by [Unito](https://www.unito.io)

Oops, also add the voting power to the server

---

packages/lesswrong/server/loot/unlocks.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209865273045404) by [Unito](https://www.unito.io)

fix reward indexing

---

scripts/repl.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209820960439411) by [Unito](https://www.unito.io)

Fix exception-swallowing in repl

---

packages/lesswrong/components/seasonal/loot/TwelveVirtues.tsx
packages/lesswrong/components/users/UsersNameDisplay.tsx
packages/lesswrong/lib/collections/users/newSchema.ts
packages/lesswrong/lib/loot/unlocks.tsx
packages/lesswrong/server/loot/unlocks.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209866132268479) by [Unito](https://www.unito.io)

Allow users to pin virtues to their profile

---

packages/lesswrong/components/recentDiscussion/RecentDiscussionTag.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionTagRevisionItem.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209778958564703) by [Unito](https://www.unito.io)

Fix borders for recent-discussion tag create and revision items

---

packages/lesswrong/server/scripts/resetVoteStrengths.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209874177494818) by [Unito](https://www.unito.io)

Add resetVoteStrengths script

---

packages/lesswrong/components/common/GlobalHotkeys.tsx
packages/lesswrong/themes/stylePiping.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209899850430759) by [Unito](https://www.unito.io)

Collapsible sections: Small styling fix; expand on Cmd+F

---

packages/lesswrong/lib/collections/chapters/newSchema.ts
packages/lesswrong/lib/collections/clientIds/newSchema.ts
packages/lesswrong/lib/collections/commentModeratorActions/newSchema.ts
packages/lesswrong/lib/collections/conversations/newSchema.ts
packages/lesswrong/lib/collections/digestPosts/newSchema.ts
packages/lesswrong/lib/collections/electionVotes/newSchema.ts
packages/lesswrong/lib/collections/emailTokens/newSchema.ts
packages/lesswrong/lib/collections/messages/newSchema.ts
packages/lesswrong/lib/collections/postEmbeddings/newSchema.ts
packages/lesswrong/lib/collections/postRecommendations/newSchema.ts
packages/lesswrong/lib/collections/postViewTimes/newSchema.ts
packages/lesswrong/lib/collections/postViews/newSchema.ts
packages/lesswrong/lib/collections/posts/newSchema.ts
packages/lesswrong/lib/collections/readStatus/newSchema.ts
packages/lesswrong/lib/collections/reports/newSchema.ts
packages/lesswrong/lib/collections/reviewWinners/newSchema.ts
packages/lesswrong/lib/collections/sideCommentCaches/newSchema.ts
packages/lesswrong/lib/collections/splashArtCoordinates/newSchema.ts
packages/lesswrong/lib/collections/spotlights/newSchema.ts
packages/lesswrong/lib/collections/subscriptions/newSchema.ts
packages/lesswrong/lib/collections/surveyResponses/newSchema.ts
packages/lesswrong/lib/collections/surveySchedules/newSchema.ts
packages/lesswrong/lib/collections/users/newSchema.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts
packages/lesswrong/unitTests/graphqlNullabilityTest.tests.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209891300653343) by [Unito](https://www.unito.io)

Add unit tests for graphql field nullability, fix nullability of some fields

---

packages/lesswrong/components/posts/PostsPage/BestOfLessWrong/BestOfLessWrongAnnouncement.tsx
packages/lesswrong/server/reviewVoteUpdate.ts

Adds a "view all" button that links to /bestoflesswrong page, and cleans up mobile styling.

Add button to BestOfLessWrongAnnouncement

---

packages/lesswrong/components/posts/PostsPage/BestOfLessWrong/BestOfLessWrongAnnouncement.tsx
packages/lesswrong/components/spotlights/SpotlightItem.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209944546912872) by [Unito](https://www.unito.io)

Fix mobile display of Best of LW

---

packages/lesswrong/lib/notificationTypes.tsx
packages/lesswrong/server/notificationTypesServer.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209918664609824) by [Unito](https://www.unito.io)

Notification types are not registered side-effectfully

---

packages/lesswrong/components/common/MixedTypeFeed.tsx
packages/lesswrong/components/spotlights/SpotlightFeedItem.tsx
packages/lesswrong/components/ultraFeed/UltraFeed.tsx
packages/lesswrong/components/ultraFeed/UltraFeedCommentItem.tsx
packages/lesswrong/components/ultraFeed/UltraFeedPostItem.tsx
packages/lesswrong/components/ultraFeed/UltraFeedSettings.tsx
packages/lesswrong/components/ultraFeed/UltraFeedThreadItem.tsx
packages/lesswrong/components/ultraFeed/ultraFeedTypes.ts
packages/lesswrong/lib/analyticsEvents.tsx
packages/lesswrong/server/resolvers/ultraFeedResolver.ts

what is says on the tin
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209965179896503) by [Unito](https://www.unito.io)

Add analytics to UltraFeed

---

packages/lesswrong/components/sequences/TopPostsPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209957334957878) by [Unito](https://www.unito.io)

UI fixes for Best of LessWrong

---

packages/lesswrong/components/ultraFeed/FeedItemWrapper.tsx
packages/lesswrong/components/ultraFeed/UltraFeedCommentItem.tsx
packages/lesswrong/components/ultraFeed/UltraFeedItemFooter.tsx
packages/lesswrong/components/ultraFeed/UltraFeedPostItem.tsx
packages/lesswrong/components/ultraFeed/UltraFeedThreadItem.tsx
packages/lesswrong/components/ultraFeed/ultraFeedTypes.ts
packages/lesswrong/lib/ultraFeed/ultraFeedThreadHelpers.ts
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/themeType.ts

The long process of making the UltraFeed good now begins
- make cards more separated
- clicking on "Replying to..." now opens a Post card above thread
- comment count on comments is number of direct descendents
- clicking comments count navigates to comment permalink
- hopefully made it so vote buttons have color but hard to test!!
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209966842109306) by [Unito](https://www.unito.io)

Ultrafeed improvements 2025 04 11

---

packages/lesswrong/server/editor/utils.ts
packages/lesswrong/server/resolvers/postResolvers.ts
packages/lesswrong/server/scripts/lowerGoogleDocsImportMajorVersions.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209984149398698) by [Unito](https://www.unito.io)

Fix docs import major versioning

---

packages/lesswrong/lib/collections/gardencodes/newSchema.ts
packages/lesswrong/lib/generated/gqlSchema.gql
packages/lesswrong/lib/generated/inputTypes.d.ts
packages/lesswrong/server/callbacks/tagCallbackFunctions.ts
packages/lesswrong/server/codegen/generateInputTypes.ts
packages/lesswrong/server/collections/arbitalTagContentRels/mutations.ts
packages/lesswrong/server/collections/bans/mutations.ts
packages/lesswrong/server/collections/dialogueMatchPreferences/mutations.ts
packages/lesswrong/server/collections/googleServiceAccountSessions/mutations.ts
packages/lesswrong/server/collections/lwevents/mutations.ts
packages/lesswrong/server/collections/notifications/mutations.ts
packages/lesswrong/server/collections/podcastEpisodes/mutations.ts
packages/lesswrong/server/collections/splashArtCoordinates/mutations.ts
packages/lesswrong/server/collections/tagRels/mutations.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209995303112842) by [Unito](https://www.unito.io)

fix types in mutator functions which relied on deleted graphql types

---

packages/lesswrong/lib/voting/getVotingSystem.ts
packages/lesswrong/server/scripts/recalculateDocumentScoresOnCollection.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209995394442669) by [Unito](https://www.unito.io)

Fix broken extendedScores on tags/multidocuments

---

packages/lesswrong/lib/collections/posts/newSchema.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209996215331245) by [Unito](https://www.unito.io)

Fix default post voting system

---

packages/lesswrong/components/hooks/useRecordPostView.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209996300838918) by [Unito](https://www.unito.io)

Don't send data to Recombee if logged in with a spambot account

---

packages/lesswrong/lib/generated/gqlSchema.gql
packages/lesswrong/lib/generated/inputTypes.d.ts
packages/lesswrong/server/collections/users/queries.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209996447388025) by [Unito](https://www.unito.io)

Add the ability to look up users by slug back into the graphql API (API users were using it)

---

packages/lesswrong/components/comments/CommentsItem/CommentShortformIcon.tsx
packages/lesswrong/components/comments/CommentsItem/CommentUserName.tsx
packages/lesswrong/components/comments/CommentsItem/CommentsItemDate.tsx
packages/lesswrong/components/common/ContentStyles.tsx
packages/lesswrong/components/ultraFeed/FeedContentBody.tsx
packages/lesswrong/components/ultraFeed/FeedItemWrapper.tsx
packages/lesswrong/components/ultraFeed/UltraFeedCommentItem.tsx
packages/lesswrong/components/ultraFeed/UltraFeedCommentsItemMeta.tsx
packages/lesswrong/components/ultraFeed/UltraFeedItemFooter.tsx
packages/lesswrong/components/ultraFeed/UltraFeedPostItem.tsx
packages/lesswrong/components/ultraFeed/UltraFeedThreadItem.tsx
packages/lesswrong/components/votes/AgreementVoteAxis.tsx
packages/lesswrong/components/votes/OverallVoteAxis.tsx
packages/lesswrong/themes/createThemeDefaults.ts
packages/lesswrong/themes/siteThemes/lesswrongTheme.ts
packages/lesswrong/themes/themeType.ts

A bunch of changes that are about creating different styles for desktop. 
- moving away from props passed to e.g. vote buttons and instead passing classes that can have breakpoint styles
Seems like it should be possible to unify better, but this gets things out to admins ASAP
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209997808261258) by [Unito](https://www.unito.io)

Ultrafeed improvements 2025-04-15 (Style for Desktop)

---

packages/lesswrong/components/comments/CommentsItem/CommentShortformIcon.tsx
packages/lesswrong/components/ultraFeed/UltraFeedPostItem.tsx

failed to commit these change in last PR
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210005923290974) by [Unito](https://www.unito.io)

Ultrafeed styling fixes 2025 04 16

---

.github/workflows/deployBaserates.yaml
.github/workflows/deployEABeta.yaml
.github/workflows/deployEADev.yaml
.github/workflows/deployEAProd.yaml
.github/workflows/deployLWAFProd.yaml
.github/workflows/deployLWDevel.yaml

Workaround for https://github.com/aws/aws-elastic-beanstalk-cli/issues/541
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210012396495564) by [Unito](https://www.unito.io)

Manually install `packaging` python package in deploy pipeline

---

packages/lesswrong/components/common/LWHome.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210090060711009) by [Unito](https://www.unito.io)

Revert best-of-lw from Frontpage

---

packages/lesswrong/components/tagging/subforums/SubforumSubforumTab.tsx
packages/lesswrong/lib/collections/users/newSchema.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210104560875029) by [Unito](https://www.unito.io)

[EA] Deploy others-help fix

---

packages/lesswrong/components/forumEvents/ForumEventPoll.tsx
packages/lesswrong/lib/collections/forumEvents/types.ts
packages/lesswrong/lib/generated/databaseTypes.d.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts
packages/lesswrong/lib/generated/gqlSchemaAndFragments.gql
packages/lesswrong/lib/generated/inputTypes.d.ts
packages/lesswrong/server/callbacks/commentCallbackFunctions.tsx
packages/lesswrong/server/collections/comments/mutations.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210108291735141) by [Unito](https://www.unito.io)

[EA] Require editing poll response text before submitting

---

packages/lesswrong/lib/collections/users/newSchema.ts

This must have been lost during a recent refactor
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210057347233271) by [Unito](https://www.unito.io)

[EA] Add GWWC diamond back in

---

packages/lesswrong/lib/collections/users/newSchema.ts

Embarrassing that I couldn't find this last night.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210115091853120) by [Unito](https://www.unito.io)

[EA] Fix control component for the "how I can help others" section

---

packages/lesswrong/components/users/account/UsersEditForm.tsx

oops
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210168283497950) by [Unito](https://www.unito.io)

fix bio editing

---

packages/lesswrong/components/hooks/useBookmark.tsx
packages/lesswrong/server/repos/BookmarksRepo.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210190327517154) by [Unito](https://www.unito.io)

fix column name in bookmarks upsert

---

packages/lesswrong/components/tanstack-form-components/helpers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210200899094334) by [Unito](https://www.unito.io)

Fix adding coauthors to posts

---

packages/lesswrong/components/sunshineDashboard/SunshineSidebar.tsx

don't know why you'd move this
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210214178837943) by [Unito](https://www.unito.io)

restore curated section to its rightful place

---

packages/lesswrong/components/common/ContentItemBody.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210213037999818) by [Unito](https://www.unito.io)

Fix horizontal scrolling of tables that aren't wrapped in <p> or <div>

---

packages/lesswrong/server/databaseIndexes/commentsDbIndexes.ts
packages/lesswrong/server/migrations/20250508T230604.fixSuggestForAlignmentCommentsIndex.ts
packages/lesswrong/server/resolvers/defaultResolvers.ts
packages/lesswrong/server/sql/SelectFragmentQuery.ts
packages/lesswrong/server/sql/SelectQuery.ts
packages/lesswrong/server/sql/sqlClient.ts
packages/lesswrong/server/sqlConnection.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210202286582182) by [Unito](https://www.unito.io)

Fix alignment suggested comments index

---

packages/lesswrong/components/material-ui/Drawer.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210214476927592) by [Unito](https://www.unito.io)

Fix positioning of notifications drawer

---

packages/lesswrong/lib/vulcan-lib/utils.ts
packages/lesswrong/server/apolloServer.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210118694291086) by [Unito](https://www.unito.io)

Fix AF->LW redirect for non-AF posts

---

packages/lesswrong/components/hooks/useStyles.tsx

Fix styles in vite-mode
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210232645116438) by [Unito](https://www.unito.io)

Fix missing styles in vite mode

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/hooks/useStyles.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210232602174641) by [Unito](https://www.unito.io)

More spurious rerender reduction

---

packages/lesswrong/server/callbacks/votingCallbacks.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210241242821623) by [Unito](https://www.unito.io)

flag recurring users less frequently for senior user downvoting ratio

---

packages/lesswrong/components/common/LWDialog.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210232765393643) by [Unito](https://www.unito.io)

Fix the width of the quick-takes dialog

---

packages/lesswrong/lib/collections/users/newSchema.ts
packages/lesswrong/server/migrations/20221213T153954.array_of_foreign_key_defaults.ts
packages/lesswrong/server/migrations/20250515T184541.remove_bookmarked_posts_metadata_from_users.ts

migration to remove the old field from table, plus change fields to have resolvers
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210266415187997) by [Unito](https://www.unito.io)

Bookmarks Changes Follow

---

packages/lesswrong/components/common/LWDialog.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210277653659699) by [Unito](https://www.unito.io)

Fix broken clickaway on footnote dialog

---

packages/lesswrong/lib/vendor/@material-ui/core/src/ButtonBase/TouchRipple.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210277414351397) by [Unito](https://www.unito.io)

Fix the submit button on the wiki edit form

---

packages/lesswrong/server/migrations/20250514T192027.updateCustomIndexes.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210255267683694) by [Unito](https://www.unito.io)

Add a migration to update custom indexes (particularly the AF-suggested-comments index)

---

packages/lesswrong/components/tagging/EditTagPage.tsx
packages/lesswrong/components/tagging/TagForm.tsx
packages/lesswrong/themes/stylePiping.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210333217192657) by [Unito](https://www.unito.io)

Fix tag-page buttons

---

packages/lesswrong/components/comments/CommentsListSection.tsx
packages/lesswrong/components/comments/CommentsTableOfContents.tsx
packages/lesswrong/components/hooks/useRecordPostView.tsx
packages/lesswrong/components/hooks/useScrollHighlight.ts
packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
packages/lesswrong/lib/crud/withMulti.ts

This PR identifies a bunch of causes of component rerenders that happen after loading a post page, and fixes them, which theoretically should translate into reduced client-side CPU usage.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210256514232293) by [Unito](https://www.unito.io)

Optimize React rendering on post pages

---

packages/lesswrong/components/comments/CommentForm.tsx
packages/lesswrong/components/comments/CommentsSubmitDropdown.tsx
packages/lesswrong/lib/abTestImpl.ts
packages/lesswrong/lib/collections/comments/views.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210402732376756) by [Unito](https://www.unito.io)

[EA] Deploy post-release fixes for draft comments

---

packages/lesswrong/components/ultraFeed/UltraFeed.tsx
packages/lesswrong/components/ultraFeed/UltraFeedItemFooter.tsx
packages/lesswrong/components/ultraFeed/settingsComponents/UltraFeedSettingsComponents.tsx
packages/lesswrong/components/ultraFeed/ultraFeedSettingsTypes.ts
packages/lesswrong/server/repos/PostsRepo.ts
packages/lesswrong/server/resolvers/ultraFeedResolver.ts
packages/lesswrong/server/ultraFeed/ultraFeedPostHelpers.ts

In advance of beta announcement, tweaking some of the defaults
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210396177994750) by [Unito](https://www.unito.io)

Adjust Some Default Values for Ultrafeed

---

packages/lesswrong/components/contents/ContentItemBody.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210405643281644) by [Unito](https://www.unito.io)

Fix infinite-loop crash when comments contain html/body tags

---

packages/lesswrong/server/apolloServer.ts
packages/lesswrong/server/databaseSettings.ts

Implementation borrowed from #9901

[EA] Redirect ?commentId=... to #... as a temporary bot protection measure

---

packages/lesswrong/components/comments/CommentsNewForm.tsx

Quick follow up to #10861 to try to attract more usage before posting about it

[EA] Allow draft quick takes

---

packages/lesswrong/components/pages/UltraFeedPage.tsx
packages/lesswrong/components/ultraFeed/UltraFeed.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210427502649089) by [Unito](https://www.unito.io)

Ultrafeed: hopefully fix overflow issues on some mobile devices

---

packages/lesswrong/components/form-components/MultiSelectButtons.tsx
packages/lesswrong/components/localGroups/CommunityMap.tsx
packages/lesswrong/themes/globalStyles/externalStyles.ts
packages/lesswrong/themes/siteThemes/eaTheme.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210430853087215) by [Unito](https://www.unito.io)

Remove remnants of Roboto font

---

packages/lesswrong/components/posts/PostForm.tsx
packages/lesswrong/components/sequences/ChaptersForm.tsx
packages/lesswrong/components/tanstack-form-components/helpers.ts
packages/lesswrong/lib/collections/posts/helpers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210478535050035) by [Unito](https://www.unito.io)

fix form field visibility for coauthors, crossposting, and some chapter fields, as well as fixing event duplication with coauthors

---

packages/lesswrong/server/repos/JargonTermsRepo.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210490498401684) by [Unito](https://www.unito.io)

fix jargon terms missing revisions breaking post pages

---

packages/lesswrong/lib/collections/posts/newSchema.ts
packages/lesswrong/server/mapsUtils.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210503294246742) by [Unito](https://www.unito.io)

Fix crashes in Google Maps API making users unable to edit/submit events

---

packages/lesswrong/server/repos/JargonTermsRepo.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210503596200539) by [Unito](https://www.unito.io)

Merge master to lw-deploy 2025 06 09

---

packages/lesswrong/server/editor/mentions-notify.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210506803073897) by [Unito](https://www.unito.io)

Fix mentions

---

packages/lesswrong/components/common/LWDialog.tsx
packages/lesswrong/lib/cookies/callbacks.ts
packages/lesswrong/lib/vendor/@material-ui/core/src/ButtonBase/TouchRipple.tsx
packages/lesswrong/server/migrations/20250514T192027.updateCustomIndexes.ts
packages/lesswrong/stubs/client/datadogRum.ts
packages/lesswrong/stubs/client/reCaptcha.ts
playwright/bookmarks.spec.ts

See: https://lworg.slack.com/archives/CJUN2UAFN/p1749580409934209

Fix reverted commits

---

packages/lesswrong/lib/routes.ts

See https://docs.google.com/document/d/1UgB5MpjL6ZgxjkHty93__4DWP0qLBbAFDGdkaXIYrOg/edit?tab=t.0
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210505148989044) by [Unito](https://www.unito.io)

[EA] Add EA Forum legacy routes

---

.github/CODEOWNERS

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210514778567410) by [Unito](https://www.unito.io)

Update list of forum magnum code reviewers

---

packages/lesswrong/server/vulcan-lib/apollo-server/helpers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210547650876791) by [Unito](https://www.unito.io)

fix types to not be backwards breaking for SelectorInput update functions

---

packages/lesswrong/components/notifications/NotificationsPopover.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210572862499842) by [Unito](https://www.unito.io)

[EA] Fix notifications disappearing while loading more

---

packages/lesswrong/themes/defaultPalette.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210594780334536) by [Unito](https://www.unito.io)

Fix Intercom button color after navigating from the If Anyone Builds It front page to a light-mode page

---

packages/lesswrong/components/seasonal/IfAnyoneBuildsItSplash.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210596238667097) by [Unito](https://www.unito.io)

Style the IABI opt-out button

---

packages/lesswrong/components/LWBackgroundImage.tsx
packages/lesswrong/components/seasonal/IfAnyoneBuildsItSplash.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210596271325073) by [Unito](https://www.unito.io)

Restore the orbs.

---

packages/lesswrong/components/common/LWHome.tsx
packages/lesswrong/components/seasonal/IfAnyoneBuildsItSplash.tsx
packages/lesswrong/components/themes/ThemePickerMenu.tsx
packages/lesswrong/components/themes/useTheme.tsx
packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210604091110860) by [Unito](https://www.unito.io)

Link splash status to spotlight hiding status

---

packages/lesswrong/components/common/FlashMessages.tsx
packages/lesswrong/components/form-components/FMCrosspostControl.tsx
packages/lesswrong/components/posts/PostForm.tsx

- Fix serif for flash messages
- Fix serif for crosspost checkbox
- Remove alignment forum checkbox on EA forum
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210571600515398) by [Unito](https://www.unito.io)

[EA] Fix some MUI serif

---

packages/lesswrong/components/users/UsersMenu.tsx

This is a prio candidate and it's literally a 1 minute change
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210636246163458) by [Unito](https://www.unito.io)

[EA] Add 'new question' to user menu dropdown

---

packages/lesswrong/components/hooks/useQueryWithLoadMore.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210652050880696) by [Unito](https://www.unito.io)

Fix missing load mores

---

packages/lesswrong/components/Layout.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210653150574647) by [Unito](https://www.unito.io)

Fix the header having a loading-state flash of the wrong state of gray, in dark mode

---

packages/lesswrong/components/ultraFeed/UltraFeedObserver.tsx
packages/lesswrong/components/ultraFeed/UltraFeedPostItem.tsx
packages/lesswrong/server/resolvers/ultraFeedResolver.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210664856996706) by [Unito](https://www.unito.io)

redesign header of post item

---

packages/lesswrong/themes/stylePiping.ts

https://app.intercom.com/a/inbox/wtb8z7sj/inbox/shared/all/conversation/215469607458020?view=List
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210665304605721) by [Unito](https://www.unito.io)

In the editor add scroll margin to the footnote reference

---

packages/lesswrong/components/ea-forum/onboarding/EAOnboardingThankYouStage.tsx

Requested on Slack by Toby:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210673069276527) by [Unito](https://www.unito.io)

[EA] Onboarding feedback group copy updates

---

packages/lesswrong/components/ultraFeed/UltraFeedItemFooter.tsx

I believe changing display of reacts changed the size of the tallest item in the footer, misaligning it all. I have made it more robust and fixed the alignments
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210712826491552) by [Unito](https://www.unito.io)

Ultrafeed Realign Icons Nth Time

---

packages/lesswrong/components/common/Header.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210709914288269) by [Unito](https://www.unito.io)

Add a background blur to the light-mode header

---

packages/lesswrong/components/common/FeedSelectorCheckbox.tsx
packages/lesswrong/components/recentDiscussion/RecentDiscussionFeed.tsx
packages/lesswrong/components/ultraFeed/UltraFeedSpotlightItem.tsx
packages/lesswrong/components/ultraFeed/ultraFeedSettingsTypes.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210713776860310) by [Unito](https://www.unito.io)

Ultrafeed fix bugs 20250703

---

packages/lesswrong/components/comments/FriendlyPopularComment.tsx
packages/lesswrong/components/keywords/KeywordResults.tsx
packages/lesswrong/components/keywords/KeywordResultsPage.tsx
packages/lesswrong/lib/fragments/allFragments.ts
packages/lesswrong/lib/generated/fragmentTypes.d.ts
packages/lesswrong/lib/generated/gqlSchemaAndFragments.gql
packages/lesswrong/lib/generated/inputTypes.d.ts
packages/lesswrong/lib/keywordAlertHelpers.ts
packages/lesswrong/server/keywordAlerts/keywordAlertsCron.ts
packages/lesswrong/server/keywordAlerts/keywordAlertsResolvers.ts
packages/lesswrong/server/keywordAlerts/keywordSearch.ts
packages/lesswrong/server/notificationTypesServer.tsx

Implements keyword alerts for comments.
- Results page:
- Onsite notifications:
- Email notifications (we display the comment text truncated to 50 characters):
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210730959128940) by [Unito](https://www.unito.io)

[EA] Keyword alerts for comments

---

packages/lesswrong/components/posts/PostsPage/LWPostsPageHeader.tsx
packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx
packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
packages/lesswrong/components/ultraFeed/UltraFeedPostDialog.tsx
packages/lesswrong/components/ultraFeed/UltraFeedPostItem.tsx
packages/lesswrong/components/ultraFeed/UltraFeedSpotlightItem.tsx
packages/lesswrong/lib/collections/posts/helpers.ts

- Spotlight Item titles are clickable
- Linkpost UI on UltraFeed Post Items
- slight styling changes
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210757533029774) by [Unito](https://www.unito.io)

Ultrafeed improvements 2025-07-09

---

packages/lesswrong/components/common/ErrorBoundary.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210712774935794) by [Unito](https://www.unito.io)

Fix the error boundary for the unread notifications query

---

packages/lesswrong/components/hooks/useDialogNavigation.ts
packages/lesswrong/components/ultraFeed/UltraFeedPostDialog.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210767380280097) by [Unito](https://www.unito.io)

Opening post dialog from feed replaces url with (but doesn't navigate) to post's url

---

packages/lesswrong/components/ultraFeed/UltraFeedPostItem.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210768216843171) by [Unito](https://www.unito.io)

Fix Wordcount Bug on UltraFeed Post Items

---

packages/lesswrong/components/common/ErrorBoundary.tsx
packages/lesswrong/components/notifications/NotificationsMenu.tsx
packages/lesswrong/components/notifications/NotificationsMenuButton.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210769360480195) by [Unito](https://www.unito.io)

Fix the error boundary for useUnreadNotificationCounts (again)

---

packages/lesswrong/server/notificationBatching.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210763809635962) by [Unito](https://www.unito.io)

[EA] Set utm_content as document id to be able to track individual email notifications

---

packages/lesswrong/server/apolloServer.ts
packages/lesswrong/server/sitemap.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210763997060392) by [Unito](https://www.unito.io)

[EA] Split sitemaps

---

packages/lesswrong/components/keywords/KeywordsPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210802330547708) by [Unito](https://www.unito.io)

Fix typo in keywords page info tooltip

---

packages/lesswrong/components/contents/ContentItemBody.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210805035777193) by [Unito](https://www.unito.io)

Fix crash when navigating away from pages containing certain comments written in markdown containing LaTeX

---

packages/lesswrong/components/forumEvents/ForumEventForm.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210809498569178) by [Unito](https://www.unito.io)

[EA] Fix isGlobal error and display error messages in new event form

---

packages/lesswrong/components/comments/AllComments.tsx
packages/lesswrong/components/comments/RecentComments.tsx
packages/lesswrong/components/review/Reviews2018.tsx
packages/lesswrong/components/review/Reviews2019.tsx
packages/lesswrong/components/review/UserReviews.tsx
packages/lesswrong/components/users/FriendlyUsersProfile.tsx
packages/lesswrong/components/users/UsersProfile.tsx
packages/lesswrong/lib/collections/comments/views.ts
packages/lesswrong/lib/generated/gql-codegen/graphql.ts
packages/lesswrong/lib/generated/gqlSchema.gql
packages/lesswrong/lib/generated/graphqlCodegenTypes.d.ts
packages/lesswrong/lib/generated/inputTypes.d.ts
packages/lesswrong/server/collections/comments/queries.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210653109227115) by [Unito](https://www.unito.io)

refactor RecentComments use of legacy CommentsViewTerms type to new CommentSelector and fix missing fields in gql input types

---

packages/lesswrong/lib/routes.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210844988984485) by [Unito](https://www.unito.io)

[EA] Update homepage description text

---

packages/lesswrong/lib/collections/sequences/views.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210867320921757) by [Unito](https://www.unito.io)

Exclude draft sequences from the default view

---

packages/lesswrong/components/notifications/NotificationsPopoverNotification.tsx
packages/lesswrong/components/posts/PostsItemTooltipWrapper.tsx
packages/lesswrong/components/posts/PostsPreviewTooltip/PostsTooltip.tsx
packages/lesswrong/components/review/LatestReview.tsx
packages/lesswrong/lib/analyticsEvents.tsx
packages/lesswrong/lib/collections/sequences/views.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210869840363016) by [Unito](https://www.unito.io)

[EA] Deploy tracking on-site notification hovers

---

packages/lesswrong/components/comments/CommentsListSection.tsx
packages/lesswrong/components/ultraFeed/UltraFeedPostDialog.tsx

- fixes ui issue where modal opens and you are scrolled to a single-line comment (now modal comments are fully expanded)
- fixes issue where comment highlighting fades to grey even when comment background should be white
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210874540947496) by [Unito](https://www.unito.io)

Ultrafeed Improvements 20250723

---

packages/lesswrong/components/linkPreview/PostLinkPreview.tsx
packages/lesswrong/components/tagging/useTag.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210885029128488) by [Unito](https://www.unito.io)

Don't SSR tag previews

---

packages/lesswrong/components/common/FeedSelectorCheckbox.tsx
packages/lesswrong/components/ultraFeed/UltraFeedCommentsItemMeta.tsx

- padding of quick take pill
- ultrafeed selector available to all
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210955744691721) by [Unito](https://www.unito.io)

Ultrafeed fixes 20250802

---

packages/lesswrong/components/themes/ThemeContextProvider.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210953723100645) by [Unito](https://www.unito.io)

Fix light/dark coloring of radio buttons and datepicker

---

packages/lesswrong/components/seasonal/Inkhaven2025.tsx
packages/lesswrong/components/themes/ThemeContextProvider.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210958012580797) by [Unito](https://www.unito.io)

Merge master to lw-deploy 2025 08 03

---

packages/lesswrong/lib/rateLimits/constants.ts
packages/lesswrong/lib/rateLimits/types.ts
packages/lesswrong/lib/rateLimits/utils.ts
packages/lesswrong/server/callbacks/commentCallbackFunctions.tsx
packages/lesswrong/server/callbacks/postCallbackFunctions.tsx
packages/lesswrong/unitTests/autoRateLimit.tests.ts
playwright/posts.spec.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210869428261014) by [Unito](https://www.unito.io)

[EA] Adopt LW rate limits for EAF

---

packages/lesswrong/components/editor/CKCommentEditor.tsx
packages/lesswrong/components/editor/CKPostEditor.tsx
packages/lesswrong/components/languageModels/LanguageModelChat.tsx
packages/lesswrong/lib/editor/mentionsConfig.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210970422583352) by [Unito](https://www.unito.io)

Fix mentions context

---

packages/lesswrong/components/hooks/useImageUpload.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210981284839197) by [Unito](https://www.unito.io)

Fix image uploader crash

---

packages/lesswrong/components/Layout.tsx
packages/lesswrong/components/ea-forum/EASurveyBanner.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210987257307269) by [Unito](https://www.unito.io)

[EA Forum only] enable 2025 survey banner

---

packages/lesswrong/components/ultraFeed/UltraFeedCommentItem.tsx
packages/lesswrong/components/ultraFeed/UltraFeedPostItem.tsx
packages/lesswrong/components/ultraFeed/UltraFeedThreadCommentsList.tsx
packages/lesswrong/components/ultraFeed/UltraFeedThreadItem.tsx
packages/lesswrong/themes/defaultPalette.ts
packages/lesswrong/themes/siteThemes/lesswrongTheme.ts
packages/lesswrong/themes/themeType.ts
packages/lesswrong/themes/userThemes/darkMode.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211012571879900) by [Unito](https://www.unito.io)

Ultrafeed fix background colors 2

---

packages/lesswrong/components/ea-forum/EABestOfPage.tsx

https://cea-core.slack.com/archives/C038J512SD8/p1755037582280139
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211044439573924) by [Unito](https://www.unito.io)

Update 'Highlights this year' posts list on best of page

---

packages/lesswrong/components/Layout.tsx

remove extra w in host check

---

packages/lesswrong/components/Layout.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211143714417690) by [Unito](https://www.unito.io)

change redirect from baserates-prod-test to baserates-test

---

packages/lesswrong/server/permissions/accessFilters.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211230154159286) by [Unito](https://www.unito.io)

undo temporary blocking of sensitive info from greaterwrong

---

packages/lesswrong/components/common/CloudinaryImage2.tsx
packages/lesswrong/components/contents/ContentItemBody.tsx
packages/lesswrong/components/form-components/ThemeSelect.tsx
packages/lesswrong/components/themes/ThemeContextProvider.tsx
packages/lesswrong/components/themes/ThemePickerMenu.tsx
packages/lesswrong/components/themes/useTheme.tsx
packages/lesswrong/components/users/account/UsersEditForm.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211187512718679) by [Unito](https://www.unito.io)

Fix SSR mismatches when the theme is auto and this resolves to dark mode

---

packages/lesswrong/components/comments/CommentsTableOfContents.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211318987056622) by [Unito](https://www.unito.io)

Comments ToC respects the hideAuthor flag

---

package.json
yarn.lock

This might have a surprising performance impact due to https://github.com/brianc/node-postgres/pull/3402 .
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211298325715631) by [Unito](https://www.unito.io)

Version upgrade pg-promise/pg

---

scripts/loadDbSettings.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211370575473537) by [Unito](https://www.unito.io)

[EA] Give the EA Forum dev database a databaseId to silence startup warning

---

packages/lesswrong/components/seasonal/meetupMonth/MeetupMonthBanner.tsx
packages/lesswrong/themes/defaultPalette.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211380102148897) by [Unito](https://www.unito.io)

Fix color issues for meetup month

---

packages/lesswrong/components/seasonal/meetupMonth/MeetupMonthBanner.tsx

Improve meetup month

---

packages/lesswrong/server/sqlConnection.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211391669606477) by [Unito](https://www.unito.io)

remove magic connection pool handling

---

packages/lesswrong/lib/collections/posts/newSchema.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211399569266628) by [Unito](https://www.unito.io)

unbreak post editors

---

app/layout.tsx
packages/lesswrong/components/next/SharedScripts.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211414848151343) by [Unito](https://www.unito.io)

add back isReturningVisitor logic to fix ssr mismatch for returning logged out users who should be getting the enriched tab

---

app/library/page.tsx
packages/lesswrong/components/alignment-forum/AFLibraryPage.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211415112934976) by [Unito](https://www.unito.io)

Fix AF library page

---

packages/lesswrong/components/review/RotatingReviewWinnerSpotlight.tsx

Fix missing spotlight on the AF front page under Firefox (but not under Chrome)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211415504501047) by [Unito](https://www.unito.io)

Fix missing spotlight on the AF front page under Firefox (but not under Chrome)

---

packages/lesswrong/components/events/modules/EventCards.tsx
packages/lesswrong/components/events/modules/HighlightedEventCard.tsx
packages/lesswrong/components/events/modules/PrettyEventDateTime.tsx
packages/lesswrong/server/emailComponents/EmailPostDate.tsx
packages/lesswrong/server/emailComponents/EventUpdatedEmail.tsx
packages/lesswrong/unitTests/prettyEventDateTime.tests.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211415507963539) by [Unito](https://www.unito.io)

Fix event-updated emails

---

app/robots.txt/route.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211432546936854) by [Unito](https://www.unito.io)

Forbid crawling out redirect links

---

packages/lesswrong/server/sql/sqlClient.ts
packages/lesswrong/server/sqlConnection.ts

https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-STATEMENT-TIMEOUT
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211433824708203) by [Unito](https://www.unito.io)

add statement_timeout to pg-promise connection initialization

---

packages/lesswrong/lib/collections/posts/helpers.ts
packages/lesswrong/lib/collections/posts/newSchema.ts
packages/lesswrong/lib/vulcan-lib/utils.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211434076756704) by [Unito](https://www.unito.io)

Don't redirect linkposts through /out

---

.github/workflows/runTests.yaml
packages/lesswrong/integrationTests/collections/users.tests.ts
packages/lesswrong/integrationTests/debouncer.tests.ts
packages/lesswrong/integrationTests/utils.ts
packages/lesswrong/integrationTests/voting.tests.ts
packages/lesswrong/lib/collections/users/newSchema.ts
packages/lesswrong/server/debouncer.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211458253930381) by [Unito](https://www.unito.io)

try fixing the integration tests

---

app/graphql/route.ts
packages/lesswrong/server/crossposting/cors.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211481699769899) by [Unito](https://www.unito.io)

set cors headers on responses from /graphql route if request is coming from the crosspost site host

---

packages/lesswrong/components/ClientRouteMetadataContext.tsx
packages/lesswrong/components/LWBackgroundImage.tsx
packages/lesswrong/components/common/LWHome.tsx
packages/lesswrong/components/seasonal/Inkhaven2025.tsx
packages/lesswrong/components/seasonal/petrovDay/petrov-day-story/petrovConsts.ts

Removes Petrov Day, adds a new Inkhaven banner
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211486014432799) by [Unito](https://www.unito.io)

Petrov Day -> Inkhaven

---

packages/lesswrong/lib/instanceSettings.ts
packages/lesswrong/server/collections/automatedContentEvaluations/helpers.ts
packages/lesswrong/server/collections/revisions/mutations.ts

Sapling's env variable didn't get setup properly in Next world. Here's a fix for that (using env variables directly rather than wrapper magic as it's a bit less indirect-y and Robert endorsed).

Sapling changes

---

app/graphql/route.ts
packages/lesswrong/lib/fmCrosspost/routes.ts
packages/lesswrong/server/crossposting/handlers.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211512587094987) by [Unito](https://www.unito.io)

fix origin comparison and return fmCrosspostUserId from new handler

---

packages/lesswrong/components/common/SearchBar.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211505919632064) by [Unito](https://www.unito.io)

Fix white-on-white text in the search box on AF

---

package.json
packages/lesswrong/server/collections/reports/mutations.ts
yarn.lock

This pings sunshines when something gets flagged on LW. Env variable lives only on Vercel; not sure what's intended these days
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211516134988140) by [Unito](https://www.unito.io)

Add a slack integration that posts to slack when something is flagged

---

AGENTS.md

We'll see if it helps 🤷
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211517735264804) by [Unito](https://www.unito.io)

Add agents file

---

packages/lesswrong/components/sequences/SequencesForm.tsx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211548766674497) by [Unito](https://www.unito.io)

hide the AF checkbox on sequence form if the user doesn't have permission to create AF sequences

---

packages/lesswrong/components/comments/CommentForm.tsx
packages/lesswrong/components/comments/CommentsDraftList.tsx
packages/lesswrong/components/comments/CommentsItem/CommentBottom.tsx
packages/lesswrong/components/comments/CommentsSubmitDropdown.tsx
packages/lesswrong/components/comments/SingleLineComment.tsx
packages/lesswrong/components/comments/commentTree.ts
packages/lesswrong/components/users/UsersProfile.tsx
packages/lesswrong/lib/betas.ts
packages/lesswrong/server/repos/CommentsRepo.ts
packages/lesswrong/server/repos/PostsRepo.ts
packages/lesswrong/server/repos/VotesRepo.ts
packages/lesswrong/server/repos/helpers.ts

Merged against the wrong branch: https://github.com/ForumMagnum/ForumMagnum/pull/11494
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211571263170398) by [Unito](https://www.unito.io)

Lw draft comments
