- packages/lesswrong/components/linkPreview/PostLinkPreview.tsx
Fixes a small regression from #7958 that causes links in posts to often appear on a new line instead of inline.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205742618831864) by [Unito](https://www.unito.io)
> Fix wrapping in post and comment links

- packages/lesswrong/components/comments/PopularComment.tsx
- packages/lesswrong/components/common/excerpts/ContentExcerpt.tsx
- packages/lesswrong/components/community/modules/CommunityMembers.tsx
- packages/lesswrong/components/posts/PostsTitle.tsx
- packages/lesswrong/components/recentDiscussion/EARecentDiscussionItem.tsx
- packages/lesswrong/components/recentDiscussion/EARecentDiscussionThread.tsx
Some of this was in the old "Recent discussion" components that got lost in the update, some is just labeling links more clearly
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205743349199139) by [Unito](https://www.unito.io)
> add more analytics for recent discussion and popular comments

- packages/lesswrong/components/editor/CKPostEditor.tsx
The previous settings were causing a broken display of the comment input on mobile & other narrower-width browsers.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205744587078150) by [Unito](https://www.unito.io)
> Fix ckeditor narrow window comment box

- packages/lesswrong/components/sequences/SequencesSmallPostLink.tsx
Slack request from Lizka to show author names in post hovers from sequences:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205747320687693) by [Unito](https://www.unito.io)
> [EA] Show authors in post hovers from sequences

- packages/lesswrong/components/common/ContentItemBody.tsx
Introduced in: https://github.com/ForumMagnum/ForumMagnum/commit/66aceddf873794d8ab7920fd5df83b4b52dca82b#diff-a101a2569ccb9f908354aff6d2587b8fa31dd7f3198f13509a94b545f2353cdaR420
When changing `contentItemBody` to not be using `dangerouslySetInnerHTML`, the line in `markHoverableLinks` which gets the children of the link changed to have side effects (removing the children, to be added back in later). If we then aborted the substitution because `linkIsExcludedFromPreview` returned true (which happens for links directly to images), we would fail to add it back.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205742676418659) by [Unito](https://www.unito.io)
> Fix link-hover-preview deleting contents of links when linkIsExcludedFromPreview() is true

- packages/lesswrong/components/form-components/FMCrosspostControl.tsx
Connecting an EA forum account to LessWrong or vice-versa requires generating a JWT token. This token is currently generated when the edit post page loads, but it expires after 30 minutes. This PR changes this behaviour to instead only generate the token once the user clicks the button to connect accounts which makes a timeout much less likely.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205770537716918) by [Unito](https://www.unito.io)
> Fetch crosspost user connect token on click to avoid timeout

- packages/lesswrong/components/ea-forum/EAHoverOver.tsx
- packages/lesswrong/components/posts/PostsPreviewTooltip/EAPostsPreviewTooltip.tsx
- packages/lesswrong/components/posts/PostsPreviewTooltip/PostsTooltip.tsx
- packages/lesswrong/components/users/EAUserTooltipContent.tsx
- packages/lesswrong/components/users/UserTooltip.tsx
- packages/lesswrong/lib/components.ts
This PR is just a refactor with no new functionality. It adds a unified `EAHoverOver` component to be used instead of `LWTooltip` for hover overs on the EA forum, allowing us to share the styles between the different components. It is currently only used by the user hover and the post hover, but will soon be used by the redesigns of the hovers for tags, sequences and collections as well.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205768219751172) by [Unito](https://www.unito.io)
> Unified EA hover over component

- packages/lesswrong/components/posts/NewDialogueDialog.tsx
Fixing an issue where users see the coauthor confirmation request for dialogues, despite that not being required/enabled in principle.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205772051405264) by [Unito](https://www.unito.io)
> dialogue participants are confirmed by default

- packages/lesswrong/lib/collections/comments/views.ts
Adds a minimum karma limit for quick takes to be shown on the frontpage:
- Quick takes younger than 2 hours must have at least -5 karma
- Quick takes older than 2 hours must have at least 1 karma
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205786821365219) by [Unito](https://www.unito.io)
> Add a minimum karma limit for quick takes on the frontpage

- packages/lesswrong/components/quickTakes/QuickTakesListItem.tsx
Quick takes with negative karma can be displayed on the frontpage. When a quick takes with negative karma is expanded its body will be collapsed which is annoying, and it can't be expanded as clicking the button just un-expands the quick take:
This PR forces the comment body to be expanded inline:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205787108216512) by [Unito](https://www.unito.io)
> Force expanded quick takes to be un-truncated and un-collapsed

- packages/lesswrong/components/posts/PostsPage/PostsPageTitle.tsx
The EA forum displays a linkpost icon after the post title on the posts page for link posts. When the title wraps, we want to keep the link icon with the last word of the title to avoid having the link icon orphaned on its own on a new line. This works but there's a couple of issues with the current implementation:
- It breaks if the post title ends in whitespace or if there's irregular whitespace inside the post title (see /posts/iuZgbCHYDTiizsiDR/this-is-a-test-link-post in the dev DB).
- Because we disable word-wrapping for the final word we can get some really horrible overflow if that word is longer than a line. This is obviously rare in English, but is very common in other scripts that don't use whitespace in the same way such as Japanese (see …
> Better post title wrapping

- packages/lesswrong/components/editor/CKPostEditor.tsx
- packages/lesswrong/components/editor/EditorTopBar.tsx
Currently dialogue participants have block ownership which makes editing pretty annoying.  This PR introduces a new collaboration mode (alongside commenting, editing) called "Editing (override)"
When in editing override, you stay in override until you select another mode. You can edit any block (including delete) and you can accept any proposed changes, including your own.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205799444411331) by [Unito](https://www.unito.io)
> Add collaboration mode that overrides Dialogue Block Ownership

- packages/lesswrong/components/votes/lwReactions/HoverBallotReactionRow.tsx
- packages/lesswrong/components/votes/lwReactions/NamesAttachedReactionsVoteOnComment.tsx
- packages/lesswrong/components/votes/lwReactions/ReactOrAntireactVote.tsx
- packages/lesswrong/components/votes/lwReactions/ReactionQuotesHoverInfo.tsx
There's currently no way to antireact to inline reacts.  If you do the obvious thing and try to antireact to one, you'll actually be antireacting to the top-level react on the entire document, rather than to the inline quote.  This will often produce confusing results, such as the top-level react having only antireacters (you), and the inline react hover not correctly displaying the net reaction count for that inline react.
To fix this, we do two things:
1. For existing reacts on documents which only have inline reacts (and no top-level reacts), we hide the top-level react ballot so as to prevent users from accidentally antireacting to the top-level react (which is probably not what they're intending to do in that situation.  We continue to show it as normal if a given react is used in …
> allow antireacting to inline reacts

- packages/lesswrong/components/votes/lwReactions/HoverBallotReactionRow.tsx
Fixing an issue with https://github.com/ForumMagnum/ForumMagnum/pull/8055 where inline-only reacts no longer showed the react ballot with the react icon & name.  Now we show that, and we only hide the voting buttons on the ballot (since those are for the top-level document, rather than for the inline section).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205809274810448) by [Unito](https://www.unito.io)
> show ballot description for inline-only reacts, just not vote buttons

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/ea-forum/giving-portal/Timeline.tsx
- packages/lesswrong/lib/routes.ts
Fixes 2 small bugs left over from the first giving portal PR that we skipped in order to create the feature branch:
- Remove the standalone nav from the giving portal page
- Fix some point dates not lining up correctly with span dates on the timeline
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205812842183524) by [Unito](https://www.unito.io)
> Giving portal UI small fixes

- .github/workflows/deployLWAFProd.yaml
Our deploy workflow uses the latest version >= 3.5.  3.12 apparently included a change which removed some parts of stdlib, and caused a bunch of issues (e.g. https://stackoverflow.com/questions/77274572/multiqc-modulenotfounderror-no-module-named-imp).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205818096937468) by [Unito](https://www.unito.io)
> try restricting python version to fix broken deploys

- packages/lesswrong/components/dialogues/DialoguesList.tsx
- packages/lesswrong/lib/abTests.ts
43 clicks for optIn and 13 for getHelp. Updating to display optIn for all users.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205824976026352) by [Unito](https://www.unito.io)
> Choose best performing opt in prompt

- packages/lesswrong/components/dialogues/DialoguesList.tsx
Because of some weird peculiarities of Apollo having a PostsPage fragment here broke the frontpage dialogue list, but only on the first load (😱)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205826551401385) by [Unito](https://www.unito.io)
> Replace the fragment for the dialogue list

- packages/lesswrong/themes/stylePiping.ts
The `<u>` tag exists from the dark days of HTML which just applies `text-decoration: underline` to whatever it surrounds. There's no way to manually add these tags from the text editor, but it seems it's possible to accidentally add it in some cases when pasting for some(?) sources. For instance, see [https://forum.effectivealtruism.org/posts/PNJ52f9WMoZNhoumy/magnus-vinding-s-shortform?commentId=o6SXynNQhQ2P77ztu](https://forum.effectivealtruism.org/posts/PNJ52f9WMoZNhoumy/magnus-vinding-s-shortform?commentId=o6SXynNQhQ2P77ztu). This looks pretty ugly and goes against the other styling we have in place so this PR just manually overrides this default to remove the underline.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205784392970920) by …
> Remove `text-decoration` from default styles for <u> tags

- packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
- packages/lesswrong/components/ea-forum/giving-portal/ElectionCandidate.tsx
- packages/lesswrong/components/ea-forum/giving-portal/Timeline.tsx
- packages/lesswrong/components/ea-forum/giving-portal/hooks.ts
- packages/lesswrong/lib/eaGivingSeason.ts
- packages/lesswrong/server/posts/index.ts
- packages/lesswrong/server/repos/ElectionCandidatesRepo.ts
- packages/lesswrong/server/repos/index.ts
- packages/lesswrong/server/tagging/tagCallbacks.ts
This implements the post count for posts tagged as relevant to the donation election. A post is considered relevant to a particular candidate if it is tagged with both that candidate's tag _and_ the overall donation election tag. The overall donation election tag doesn't exist yet, so for now it's just using the effective giving tag (ie; a post will be included in the post count for GiveDirectly if it is tagged both "GiveDirectly" and "effective giving"). This will be trivial to change once the tag is created.The post count is displayed as a link on the candidate on the giving portal page, but the link doesn't yet go anywhere for two reasons:
* I don't know where it's supposed to go.
* I don't want to make many changes to the `ElectionCandidate` component in this PR because there's some …
> Election candidate tagged posts

- packages/lesswrong/integrationTests/collections/comments.tests.ts
- packages/lesswrong/integrationTests/utils.ts
- packages/lesswrong/server/rateLimitUtils.ts
Unless I'm very confused, moderator-imposed rate limits for comments don't work. (It's plausible that I'm very confused? I'd have thought that this bug would be noticed sooner.)
The function `rateLimitDateWhenUserNextAbleToComment` is supposed to consider the lengths of the various kinds of rate limits (e.g. the one-per-eight-seconds rule that applies to everyone, and ones from ModeratorActions), but it omits the ones in UserRateLimits. My understanding of the history is that ModeratorActions existed first, and UserRateLimits replaced that system, or augmented it. In that transition, I suspect that the comment rate limits in UserRateLimits were missed.
This branch has two commits. The first commit, [Add integration test for mod-applied user comment rate …
> Fix comment rate limit

- packages/lesswrong/components/ea-forum/giving-portal/ElectionCandidate.tsx
- packages/lesswrong/components/ea-forum/giving-portal/PreVoteButton.tsx
- packages/lesswrong/lib/collections/electionCandidates/fragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/lib/vulcan-lib/fragmentTypes.json
Adds a tooltip to the post count for election candidates:
Also updates the styling of the vote button tooltip to match the new tooltip:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205834716696859) by [Unito](https://www.unito.io)
> Giving season post count tooltip

- packages/lesswrong/components/dropdowns/posts/PostActions.tsx
- packages/lesswrong/components/hooks/useNotifyMe.ts
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/lib/subscriptionUtil.ts
Stuff was missing types, things fell through the cracks.  I think `newDialogueMessages` is the only one of those which should be default-subscribed-to by the post author.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205744857404666) by [Unito](https://www.unito.io)
> add handling for default subscription state for missing subscription types

- packages/lesswrong/server/ckEditor/ckEditorApi.ts
Upgrading to ckEditor's v5 api made the `DELETE /document/{document_id}` API delete the entire document, including live collaborative session, comments, suggestions, etc.  Instead of doing that, let's only delete the document contents in storage, so that if someone reverts to a revision that has comment/suggestion markers in the html, those still have things to point to.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205848773438786) by [Unito](https://www.unito.io)
> ensure revert to revision doesn't delete comments and suggestions

- packages/lesswrong/components/dialogues/DialoguesList.tsx
- packages/lesswrong/components/dialogues/DialoguesPage.tsx
- packages/lesswrong/server/repos/PostsRepo.ts
- packages/lesswrong/server/resolvers/postResolvers.ts
This adds a section called "My Dialogues (only visible to you)" to the frontpage, and a big section called "My Dialogues (Drafts & Published)" to the /dialogues page.
[Coauthored with Ruby.]
Screenshots below.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205840999650931) by [Unito](https://www.unito.io)
> Add my dialogues to frontpage & dialogues page

- packages/lesswrong/components/common/CloudinaryImage2.tsx
- packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
Without this:
With this:
I've checked every other cloudinary image that sets `imageProps` and none seem to be affected
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205852590400821) by [Unito](https://www.unito.io)
> Fix giving portal image height

- packages/lesswrong/components/ea-forum/giving-portal/DonationOpportunity.tsx
- packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
- packages/lesswrong/lib/eaGivingSeason.ts
A few quick updates to the Giving Portal:
1. Add a link to Lizka's announcement post
2. Add section ids so that we can link to sections
3. Center align the text in the "other opportunities" card buttons
4. Make the whole top section of the "other opportunities" cards clickable to include the org logo
5. In the "other opportunities" section, link the word "more" to GWWC home page
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205857273827638) by [Unito](https://www.unito.io)
> Giving portal: add section ids, fix opportunity btn, link to Lizkas post

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
There was some logic in the ToC component that was clearly trying to account for the presence of the stuff in the right column, but it wasn't properly triggering. This fixes that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205857164218687) by [Unito](https://www.unito.io)
> Fix alignment of posts without ToC

- packages/lesswrong/components/ea-forum/giving-portal/PreVoteButton.tsx
People reported pre-voting on mobile being broken/janky. It's not clear what problem they were experiencing but some issues were:
- The hitbox for the heart button is quite small
- Hover doesn't work well on mobile (hover persists after you click, which means when you cancel a pre-vote the heart is still filled, which is confusing)
- On ios, you may have to click twice sometime to get it to work. I was able to reproduce this on browserstack (clicking once would sometimes only trigger a hover), although the free trial only allows a 1 minute test so I wasn't able to check that thoroughly
I've fixed the first two things. For the "ios issue", I think the problem may actually have been that the hitbox was so small that you could move out of the hitbox for the mouseup event, so only a hover …
> Improve pre-voting on mobile

- packages/lesswrong/themes/siteThemes/lesswrongTheme.ts
Before: 
After: 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205826172097625) by [Unito](https://www.unito.io)
> Make the comment bold less bold, since it's really quite intense

- packages/lesswrong/components/votes/PostsVoteDefault.tsx
Requested by @agnesstenlund via [slack](https://cea-core.slack.com/archives/C038J512SD8/p1698141627997159)
On mobile, you need to double tap to strong vote. The comment vote tooltip explains the desktop vs mobile difference, but the post vote tooltip doesn't. This PR just updates the tooltip text to explain both, to be consistent with the comment vote tooltip.
-----
(For reference, this is the comment vote tooltip, unchanged):
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205847890610733) by [Unito](https://www.unito.io)
> Update post vote tooltip text

- packages/lesswrong/lib/eaGivingSeason.ts
This PR changes to scaling of the giving season timeline to be linear throughout November and December as requested by Lizka. To fit everything in a bit better I've also changed the end date from 31st December to 20th December (obviously we can change this again if more events get added).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205885580168360) by [Unito](https://www.unito.io)
> Giving season timeline scale

- packages/lesswrong/server/tagging/tagCallbacks.ts
We don't currently update posts in Elasticsearch after editing tags which renders the tag filter on the search page relatively useless.
It's recommended (but not necessarily required) to run `Globals.elasticExportCollection('Posts')` after deploying this.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205886078182320) by [Unito](https://www.unito.io)
> Reexport posts to elastic after tag updates

- packages/lesswrong/components/dialogues/DialoguesList.tsx
No longer displaying an event post on frontpage for the dialogue party that has already occured.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205891949383711) by [Unito](https://www.unito.io)
> Remove party post from frontpage

- packages/lesswrong/server/repos/UsersRepo.ts
Previously, we were counting every vote with "extendedVoteType" = "agreement" regardless of whether that vote had been cancelled or not. This PR fixes that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205892280406519) by [Unito](https://www.unito.io)
> fixing agreement query so that it correctly filters out cancelled votes

- packages/lesswrong/server/repos/UsersRepo.ts
Follow up from ForumMagnum/ForumMagnum#8182, to address Robert's point that instead of IS FALSE we should have IS NOT TRUE
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205892299923209) by [Unito](https://www.unito.io)
> Fixes "fixing agreement query so that it correctly filters out cancelled votes"

- packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
This PR adds social meta tags for the giving portal page - most importantly, an `og:image` of the hero image with width 1200 and a 16:9 aspect ratio ([https://res.cloudinary.com/cea/image/upload/c_crop,g_custom/dpr_auto,ar_16:9,w_1200,c_fill,g_center,q_auto,f_auto/giving_portal_23_hero](https://res.cloudinary.com/cea/image/upload/c_crop,g_custom/dpr_auto,ar_16:9,w_1200,c_fill,g_center,q_auto,f_auto/giving_portal_23_hero)) which was what was recommended online.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205900179370418) by [Unito](https://www.unito.io)
> Add social head tags for the EA giving portal

- packages/lesswrong/lib/eaGivingSeason.ts
This PR fixes the timeline timezones again.
I've tested with the timezone set to Seoul, London and San Francisco and it was correct in all three cases.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205898493702866) by [Unito](https://www.unito.io)
> Fix timeline timezones again

- packages/lesswrong/components/votes/ReactionsPalette.tsx
Three of the most important reacts (thanks, empathy, changed my mind) were missing from grid view so I added them in, replacing v rare reacts (paperclip, a duplicate 'thumbs up', and 'I'm not planning to respond').
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205892699547435) by [Unito](https://www.unito.io)
> Changed grid reacts

- packages/lesswrong/lib/betas.ts
- packages/lesswrong/server/resolvers/elicitPredictions.ts
Elicit has been asking us to deprecate usage of their API for a while now.  Doing this forum-gated since the EA forum may want to test the manual migration for the import themselves.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205904106262119) by [Unito](https://www.unito.io)
> Forum gate elicit cutover

- packages/lesswrong/components/editor/CKPostEditor.tsx
- public/lesswrong-editor/src/ckeditor5-dialogue-comments/dialogue-comment-box.js
There's still a bug where pressing ctrl/cmd+enter in someone else's input will submit a message for you (and leave an additional newline in your input), because of the keystroke handling code in the plugin itself, but this at least should fix the behavior for what users are actually doing.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205892411017762) by [Unito](https://www.unito.io)
> handle cmd+enter submit for dialogue messages without leaving a newline in the input

- packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
This was hidden so it didn't show $0 while I was adding the right id to the db. I have added the id for the main fundraiser, for the others I don't have access to the CMS to get them so the number at the bottom won't automatically update atm, I've just manually added the amounts for now (I expect to be get access to add the ids later today)
Per [this comment](https://github.com/ForumMagnum/ForumMagnum/pull/8198#discussion_r1385272772), I'm going to force merge this PR
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205906994251066) by [Unito](https://www.unito.io)
> Show fundraiser amounts in UI

- packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
The donation goal is almost complete and the bar is in danger of overflowing before we update the goal amount. This change makes sure the bar never becomes more than 100% full.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205911861540021) by [Unito](https://www.unito.io)
> Hide progress bar overflow on EA giving portal page

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/components/recommendations/PostBottomRecommendations.tsx
PR #8147 fixed a bug where the post body is misaligned for posts with no table of contents. Bottom-of-post recommendations use this same logic and we therefore need to make a similar change in order for this to be aligned with the post body and comments above.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205911579203327) by [Unito](https://www.unito.io)
> Fix alignment of bottom-of-post recommendations when there is no ToC

- packages/lesswrong/components/hooks/useNotifyMe.ts
- packages/lesswrong/components/notifications/NotifyMeButton.tsx
We got a report that the "Subscribe to be notified when an event is added" link on the [group details page](https://forum.effectivealtruism.org/groups/TGgHpPNHnM4sS6Gcc) doesn't do anything when clicking as a logged out user. This fixes the link, so that it works the same as the other "notify me" actions - logged out users should get prompted to login/sign up.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205902635195180) by [Unito](https://www.unito.io)
> fix "notify me" action for logged out users

- packages/lesswrong/components/books/Book2018Landing.tsx
- packages/lesswrong/components/books/Book2019Landing.tsx
- packages/lesswrong/components/comments/CommentsList.tsx
- packages/lesswrong/components/comments/CommentsNode.tsx
- packages/lesswrong/components/common/ForumIcon.tsx
- packages/lesswrong/components/common/TemplateComponent.tsx
- packages/lesswrong/components/common/hocTypes.ts
- packages/lesswrong/components/messaging/ConversationItem.tsx
- packages/lesswrong/components/messaging/FriendlyInbox.tsx
- packages/lesswrong/components/posts/EAPostsItem.tsx
- packages/lesswrong/components/posts/PostsList2.tsx
- packages/lesswrong/components/posts/SubmitToFrontpageCheckbox.tsx
- packages/lesswrong/components/recommendations/LWRecommendations.tsx
- packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
- packages/lesswrong/components/review/ReviewQuickPage.tsx
- packages/lesswrong/components/spotlights/SpotlightItem.tsx
- packages/lesswrong/components/sunshineDashboard/CommentKarmaWithPreview.tsx
- packages/lesswrong/components/sunshineDashboard/PostKarmaWithPreview.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineListCount.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.tsx
- packages/lesswrong/components/tagging/TagDiscussionButton.tsx
- packages/lesswrong/components/votes/lwReactions/AddInlineReactionButton.tsx
Currently we declare a component with styles like this:
```
const styles = () => ({
root: {
background: "red",
},
})
const Component = ({classes}: {classes: ClassesType}) => {
return (
<div className={classes.root} />
);
}
```
This works fine, but it's error prone as `classes` is typed as a `Record<string, any>`. For instance, it's easy to accidentally type `classes.rooy` instead of `classes.root`, and these errors can be really annoying to debug.
This PR is totally backwards compatible so you can still write components like this, but you can now optionally add a type parameter to `classes` in the component definition:
```
const Component = ({classes}: {classes: ClassesType<typeof styles>}) => {
```
and now your `classes` object knows the names of the classes that is contains and …
> Make `classes` optionally strongly-typed

- packages/lesswrong/components/ea-forum/giving-portal/GivingSeasonBanner.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205945958561162) by [Unito](https://www.unito.io)
> Add left border radius to giving season banner timeline

- packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
- packages/lesswrong/lib/eaGivingSeason.ts
- Update link for marginal funding week
- Fix voting start date on timeline in non-UTC timezones
- Remove donation matching message as the match limit has been met
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205948748893770) by [Unito](https://www.unito.io)
> Giving portal updates 2023-11-14

- packages/lesswrong/components/recentDiscussion/RecentDiscussionMeetupsPoke.tsx
Fix a layout issue that affects (the narrowest subset of) phone screens.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205946193878689) by [Unito](https://www.unito.io)
> Fix location input overflowing its bounds in meetup-poke widget

- packages/lesswrong/components/hooks/useInitiateConversation.ts
- packages/lesswrong/components/messaging/NewConversationButton.tsx
Fixes this button:
The issue was that NewMessageButton requires an extra render cycle to navigate to the conversation, and it was being unmounted before that happened. Now it will stay rendered until the `navigate` event occurs. Note that if you click away after clicking it still won't work, but you'd have to do that very quickly for this to happen (I think this is near impossible on prod)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205970933616399) by [Unito](https://www.unito.io)
> Fix sunshine message button

- packages/lesswrong/server/scripts/convertImagesToCloudinary.ts
This was reported by Lorenzo via [slack](https://cea-core.slack.com/archives/C027Z3794F3/p1696758716846219):
> Images sometimes don't show up in comments after they're posted, but they come back if I click "edit" and then stay after I click "save"
Lorenzo also provided the img tag in slack. Seems like the issue is that, when we are mirroring images, we don't account for commas in the srcset URLs and accidentally insert extra spaces. I didn't actually find the right path to reproduce this issue but I think this should fix it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205848127005747) by [Unito](https://www.unito.io)
> Fix ckeditor mirrored img srcsets

- packages/lesswrong/components/community/modules/CommunityMembers.tsx
- packages/lesswrong/components/community/modules/CommunityMembersFullMap.tsx
- packages/lesswrong/components/community/modules/LocalGroups.tsx
- packages/lesswrong/components/community/modules/SearchResultsMap.tsx
- packages/lesswrong/server/repos/UsersRepo.ts
- packages/lesswrong/server/search/algoliaDocuments.d.ts
- packages/lesswrong/server/search/elastic/ElasticConfig.ts
- packages/lesswrong/server/search/elastic/ElasticQuery.ts
- packages/lesswrong/server/search/elastic/ElasticService.ts
- packages/lesswrong/server/search/elastic/SearchQuery.ts
- packages/lesswrong/unitTests/elastic/elasticService.tests.ts
This PR fixes the broken list of users on the community map page.
Deploying this is a bit annoying because we're changing the internal format of a pre-existing JSON field which isn't supported by our current tooling. If we're happy to have 1-2 minutes where users aren't searchable then the simplest thing to do is:
```
./scripts/serverShellCommand.sh --wait "Globals.elasticDeleteIndex('Users')"
./scripts/serverShellCommand.sh --wait "Globals.elasticConfigureIndex('Users')"
./scripts/serverShellCommand.sh --wait "Globals.elasticExportCollection('Users')"
```
Note that this has to be done _after_ deploying the new code.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205970566813638) by [Unito](https://www.unito.io)
> Fix sorting by location on the community map

- packages/lesswrong/components/common/IntercomWrapper.tsx
A higher z-index was overriding the one we set, causing it to show above the modal background. Intercom is loaded via a script so this could be a recent change. Before/after:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206001859433092) by [Unito](https://www.unito.io)
> Make z index for intercom important

- packages/lesswrong/components/posts/SharePostPopup.tsx
I noticed a lot of `sharePost` events were missing a `postId`. Also thought it would be good to add the context for the share post popup events.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205996764929706) by [Unito](https://www.unito.io)
> [EA Forum only] add some missing analytics for share post popup

- packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx
- packages/lesswrong/components/ea-forum/giving-portal/GivingSeasonHeader.tsx
- packages/lesswrong/lib/eaGivingSeason.ts
- Add new banner image for donation debate week
- Add "amount raised" section to the frontpage RHS section (not that we're currently over the goal so the progress bar looks weird - we probably need to raise the goal?)
- Fix gradient discontinuity on tablet sized screens
- Disable hiding half the banner on scroll on desktop
Note that there's still some preexisting bugs (such as the bar being kept open on scroll if you open the search input) but these can be fixed separately.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206002597472994) by [Unito](https://www.unito.io)
> Donation debate week 2023 banner

- packages/lesswrong/components/common/HorizScrollBlock.tsx
See: https://lworg.slack.com/archives/CJUN2UAFN/p1699661130370779
The original bug report was that on https://www.lesswrong.com/posts/7qGxm2mgafEbtYHBf/survey-on-the-acceleration-risks-of-our-new-rfps-to-study, a table shows a horiz-scroll indicator, but doesn't have any actual horizontal scrolling. This PR is a narrow fix, which hides the horizontal scroll indicator if it turns out to be unnecessary. This PR does _not_ address the rabbit hole that this uncovered; in particular that page still has a layout-shift on load, caused by inserting the `HorizScrollBlock` component.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205952629606437) by [Unito](https://www.unito.io)
> HorizScrollBlock no longer leaves a scroll indicator if its own insertion made horiz-scroll no longer necessary

- packages/lesswrong/components/ea-forum/EAHomeCommunityPosts.tsx
When you log in with a very inactive account, you current still see the [Nonlinear post](https://forum.effectivealtruism.org/posts/32LMQsjEMm6NK2GTH/sharing-information-about-nonlinear) because it has way higher karma than most other posts since then. This fixes that, here the section after the change:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206001535366448) by [Unito](https://www.unito.io)
> Use same date cutoff for Frontpage and community section

- packages/lesswrong/components/ea-forum/giving-portal/GivingSeasonBanner.tsx
Currently Donation Debate Week is cut off, this is a hacky fix for that:
The ideal fix would be making the timeline scrollable and starting scrolled to the right, but that wasn't that straightforward to do. I may have time to come back to it later in the week but I would rather get this out as it's only relevant when Donation Debate Week is active
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206001756365686) by [Unito](https://www.unito.io)
> Remove leftmost week on mobile version of giving season banner

- packages/lesswrong/components/editor/CKPostEditor.tsx
We don't currently ensure that the list of authors only contains unique authors when creating the dialogue post fixer. Having duplicate authors is unlikely, but it is physically possible by adding the main post author as a coauthor as well (this happened in testing as it isn't clear from the "New Dialogue" dialog that you don't need to add yourself as an author to be involved). Unfortunately, this causes an infinite loop and crashes the browser tab which is... bad.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206002337382300) by [Unito](https://www.unito.io)
> Filter unique authors when creating dialogue post fixer

- packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
- packages/lesswrong/components/quickTakes/QuickTakesList.tsx
- packages/lesswrong/lib/collections/comments/views.ts
- Change giving portal posts list tag from "Effective giving" to "Donation election 2023"
- Remove the "Contribute to the discussion" button under the posts list
- Add a list of quick takes tagged "Effective giving" from the last 30 days (this cut-off is configurable if we want to change it)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206004563317445) by [Unito](https://www.unito.io)
> Update giving portal posts lists

- packages/lesswrong/components/common/Header.tsx
When we move to a different page we will be positioned at the top of the page (unless the hash is set). Unfortunately Headroom doesn't run the callback to update the value of "unfixed" on navigation so the header thinks it is still scrolled. This can cause bugs like this:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206010469156983) by [Unito](https://www.unito.io)
> Update header "unFixed" value on page navigation

- packages/lesswrong/components/posts/PostsPage/PostsPageTitle.tsx
Add tooltips to the icons shown after post titles. No forum-gating is needed as the icons themselves are already forum-gated.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206018127847549) by [Unito](https://www.unito.io)
> Add tooltips to post title icons

- packages/lesswrong/server/callbacks/messageCallbacks.ts
- packages/lesswrong/server/notificationCallbacks.tsx
If a moderator sends a message in a conversation they're not part of we need to add them as a particpant in that conversation otherwise they won't be notified of future messages.
We also have a notification for users when they are added to a conversation. We need to change this to not send a notification to the user if they added themselves.
I've not forum-gated this.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206024017784729) by [Unito](https://www.unito.io)
> Add current user as a participant to conversations when messaging

- packages/lesswrong/server/tableOfContents.ts
Request from Lizka: change the minimum number of headings in a post to show the table of contents from 3 to 1. There's no need to forum gate this as `commentsTableOfContentsEnabled` is true for LW and AF.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206035227055159) by [Unito](https://www.unito.io)
> Change minimum number of headings to show the ToC from 3 to 1

- packages/lesswrong/components/sunshineDashboard/ModGPTDashboard.tsx
- packages/lesswrong/components/sunshineDashboard/moderationLog/ModerationLog.tsx
- packages/lesswrong/components/vulcan-core/Datatable.tsx
- packages/lesswrong/components/vulcan-core/datatableTypes.ts
- packages/lesswrong/integrationTests/emails.tests.tsx
- packages/lesswrong/lib/crud/withMulti.ts
- packages/lesswrong/lib/crud/withSingle.ts
Refactors `Datatable`, a (very lightly used) class from Vulcan, such that it no longer uses the HoC version of `withMulti`. Since this was the last usage of `withMulti` anywhere, we then make it hook-only (ie only `useMulti` exists).
(Some unused functionality from `Datatable` was dropped in the process, in particular clicking on columns and having it autogenerate view terms to sort by that column. This functionality was definitely unused and pretty unlikely to have been working.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205981278444645) by [Unito](https://www.unito.io)
> Clean up Datatable class, eliminating the last of the CRUD-HoCs

- packages/lesswrong/server/apolloServer.ts
Under some circumstances (I'm not sure exactly what the trigger is), the Chrome JS debugger tries to load a bunch of /node_modules/... paths (presumably for some sort of source mapping). If these were treated as normal pageloads, this would produce a ton of console-log spam, which is disruptive. So instead just serve a minimal 404.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205752432710886) by [Unito](https://www.unito.io)
> Don't produce lots of console-log spam when the Chrome debugger tries to fetch /node_modules/... paths

- packages/lesswrong/server/repos/UsersRepo.ts
Some weird situations (maybe account merges) can result in a `null` value for a user's `services`.  Coalesce in those cases.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205980469766080) by [Unito](https://www.unito.io)
> handle case when services field is null for password resets

- packages/lesswrong/themes/globalStyles/globalStyles.ts
We had a couple of reports that the vertical positioning of the submit button is wrong for dialogues on the EA forum. I've never been able to repro the bug, but I'm guessing that this probably fixes it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206045938959309) by [Unito](https://www.unito.io)
> Fix submit button position for EA dialogues

- packages/lesswrong/components/users/DialogueMatchingPage.tsx
- packages/lesswrong/lib/abTests.ts
The SSR for MatchingPage takes a looooong time. You can wait for ~10s to see anything if you navigate directly to `/dialogueMatching`. But without SSR, you see interesting things appear quickly and the rest gets populated over time.
Let's see if it makes a difference to use the non-SSR'd version.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206043358571072) by [Unito](https://www.unito.io)
> Try MatchingPage without SSR

- packages/lesswrong/components/users/DialogueMatchingPage.tsx
A simple PR that filters out the current user from the various lists displayed
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205982145384480) by [Unito](https://www.unito.io)
> Remove self matches on dialogue matching page

- packages/lesswrong/components/form-components/SelectLocalgroup.tsx
EAF now has >400 active groups, so increasing this now to prevent the list from getting cut off. The plan is to put localgroups in elasticsearch at some point to make them better searchable.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206044662665574) by [Unito](https://www.unito.io)
> increase localgroup select limit

- packages/lesswrong/lib/collections/comments/voting.ts
- packages/lesswrong/lib/reviewUtils.tsx
- packages/lesswrong/lib/utils/memoizeWithExpiration.ts
- packages/lesswrong/lib/utils/schemaUtils.ts
- packages/lesswrong/lib/vulcan-core/default_resolvers.ts
- packages/lesswrong/lib/vulcan-users/permissions.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
Assorted performance optimizations, generated by looking at profiler results for an SSR and looking for things that didn't look like they should take as much time as they do.
* Simplify permissions-check functions
* Memoize `getReviewPhase`
* Change the method used to clean up apollo-client after SSR is finished
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206042926745937) by [Unito](https://www.unito.io)
> Assorted performance optimizations

- packages/lesswrong/lib/collections/comments/schema.ts
- packages/lesswrong/lib/collections/gardencodes/collection.ts
- packages/lesswrong/lib/collections/localgroups/schema.ts
- packages/lesswrong/lib/collections/migrations/collection.ts
- packages/lesswrong/lib/collections/notifications/schema.ts
- packages/lesswrong/lib/collections/postRecommendations/schema.ts
- packages/lesswrong/lib/collections/posts/schema.tsx
- packages/lesswrong/lib/collections/rssfeeds/schema.ts
- packages/lesswrong/lib/collections/sequences/schema.ts
- packages/lesswrong/lib/collections/tags/schema.ts
- packages/lesswrong/lib/collections/users/schema.ts
- packages/lesswrong/lib/make_voteable.ts
- packages/lesswrong/lib/utils/schemaUtils.ts
This is a simpler solution to the same problem as https://github.com/ForumMagnum/ForumMagnum/pull/8318 .
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206052955339410) by [Unito](https://www.unito.io)
> Use schemaDefaultValue (or onCreate) to ensure fields are nonnull on insertion

- packages/lesswrong/components/ea-forum/giving-portal/ElectionCandidatesList.tsx
As described in [this PR](https://github.com/ForumMagnum/ForumMagnum/pull/8341) , there is a bug in the random sorting of candidates that results in names and logos getting mixed up. That PR didn't end up fixing it and I can't pin down what the problem is, so I'm setting the default sorting back to `mostPreVoted` temporarily as it's quite a serious bug
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206060645128442) by [Unito](https://www.unito.io)
> Revert giving portal default random sorting

- packages/lesswrong/components/dialogues/DialogueRecommendationRow.tsx
Fixes various edge cases that caused ugly behavior, including: 
* topics moved too far right when expanded
* some users didn't have any expand button for overly long topics
* some users had an expand button, but with no content below it
* some users had an expand button yet were in the "no topics shown" A/B test group
BEFORE
AFTER
(all of the above fixed)
> Tiny UI fixes to frontpage matches

- tsconfig.json
This gets rid of an eternal error in my VS Code `Problems` pane, and I think it's in fact the correct thing for use with ESBuild (e.g. `noEmit` referenced on the [ESBuild Typescript page](https://esbuild.github.io/content-types/#typescript)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206072790471269) by [Unito](https://www.unito.io)
> Add `noEmit: true` to tsconfig.json

- packages/lesswrong/components/dialogues/DialogueRecommendationRow.tsx
- packages/lesswrong/server/repos/CommentsRepo.ts
- packages/lesswrong/server/resolvers/commentResolvers.ts
We make a database query for "comments from the target user, with at least 8 karma, on posts you've read, sorted by how recently you read those posts". If we find any, we recommend them in the dialogues matching row 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206062637376128) by [Unito](https://www.unito.io)
> Add recommended comments to dialogues view on frontpage

- packages/lesswrong/server/repos/UsersRepo.ts
We check to see if we made a notification of this type in the last 12 hours, and avoid making another.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206074142154923) by [Unito](https://www.unito.io)
> Let's not ping people too often

- packages/lesswrong/server/dialogues/cron.ts
- packages/lesswrong/server/repos/UsersRepo.ts
This is kind of duplication over the top of our notification batching system, but it's quick and gets the job done and respects changed preferences
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206074729047544) by [Unito](https://www.unito.io)
> Only get new dialogue interest ping once a week

- packages/lesswrong/components/comments/CommentsNewForm.tsx
- packages/lesswrong/components/questions/Answer.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206059677274477) by [Unito](https://www.unito.io)
> Fix comments on answers being posted as top-level instead

- packages/lesswrong/components/common/Header.tsx
Fix a bug introduced in https://github.com/ForumMagnum/ForumMagnum/commit/b62b2e724a1a9381255075d4a0e1b12533b1f2b9 which made the search bar not open the first time you click it.
That commit changed `rightHeaderItemsNode` in the Header component. Befire it was a React fragment that looked like this:
```
const rightHeaderItemsNode = <div ...>
{/*...*/}
</div>
```
It changed into a locally-declared component like this:
```
const RightHeaderItems = () => <div>
{/*...*/}
</div>
```
This is a different component each time Header rerenders, because it isn't referentially-stable. This means that anything inside of it doesn't get merged with the previous render, so it loses its state.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206088298177247) by …
> Fix search bar not opening on the first click

- packages/lesswrong/server/callbacks/postCallbacks.ts
- packages/lesswrong/server/scripts/convertImagesToCloudinary.ts
We automatically mirror all images in each post to Cloudinary. This PR makes it so that, when we auto-select an image from the post to use as the social preview image, we use the mirrored version of the image.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206082747467575) by [Unito](https://www.unito.io)
> Post social previews should use mirrored version of auto-selected img

- packages/lesswrong/lib/collections/posts/schema.tsx
On the create-event form, don't show a social-preview image uploader on EA Forum because there's already an event-image uploader that users should use instead
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206082275749446) by [Unito](https://www.unito.io)
> Don't show duplicate image uploaders on create-event form

- packages/lesswrong/components/dialogues/DialoguesList.tsx
This code had an error where it would early return from rendering the dialogues list if the user had no potential matches (for example, if one is logged out).
This removes that early return.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206098987658641) by [Unito](https://www.unito.io)
> Remove early return for users without recommended partners

- packages/lesswrong/server/callbacks.ts
Bug: Make an account. Post a spam comment on a post with 0 other comments. Purge the spammer account. The `commentCount` field on the post is now -1.
Looking at log traces of this, we determined that there is some sort of subtle race condition happening between a mutation that happens when a callback cancels the spammer's self-vote on the comment, and the mutation that happens to mark the comment as deleted, such that the `comments.update.after` callback sees two changes (correct) but thinks that both changes include a change from `deleted:false` to `deleted:true` (incorrect). We fix this by making the nullify-votes and the delete-content parts of the spammer-purge operation happen sequentially, rather than happening in parallel. …
> Fix post having a negative comment count after purging commenter

- packages/lesswrong/components/common/hocTypes.ts
- packages/lesswrong/components/common/withHover.tsx
- packages/lesswrong/components/sunshineDashboard/AFSuggestCommentsItem.tsx
- packages/lesswrong/components/sunshineDashboard/AFSuggestPostsItem.tsx
- packages/lesswrong/components/sunshineDashboard/AFSuggestUsersItem.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewCommentsItem.tsx
- packages/lesswrong/lib/crud/withCreate.tsx
- packages/lesswrong/lib/crud/withDelete.tsx
- packages/lesswrong/lib/crud/withUpdate.tsx
Hookifies the last users and removes the HoC versions of `withCreate`, `withUpdate`, `withDelete`, and `withHover`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206061178693838) by [Unito](https://www.unito.io)
> Remove HoC versions of CRUD operations

- packages/lesswrong/lib/collections/posts/views.ts
Probably this worked with mongo.  Then we didn't catch it in dev because we'd run the nullability migration, which filled in all the `null` values with 0.  🤦
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206099132381867) by [Unito](https://www.unito.io)
> fix review views for null reviewCount

- packages/lesswrong/server/repos/CommentsRepo.ts
- packages/lesswrong/server/resolvers/commentResolvers.ts
Solving the bug as reported via intercom, where a user was a told a different person's topics belonged to them. 
Replicated the bug in dev, solvedf it, and then verified that it now correctly attributes topics both on frontpage recommendations, and in the topic modal. (Which are the two places this function is used)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206099881600098) by [Unito](https://www.unito.io)
> Hotfix for topic attribution bug

- packages/lesswrong/components/common/Header.tsx
- packages/lesswrong/components/ea-forum/giving-portal/EAGivingPortalPage.tsx
- packages/lesswrong/components/ea-forum/giving-portal/GivingSeasonHeader.tsx
I was surprised that the Giving Portal had a blue traditional header bar. I think it worked better before we put a red voting banner on there, but now looks kinda weird. It's a pretty quick change to make it red, so I did. I open the comments for discussion on whether we should actually merge this.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206098581403329) by [Unito](https://www.unito.io)
> [EA] Giving portal gets the red header treatment

- packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx
Currently if you click "Donate to the Election Fund" here the actual link to donate is below the fold, I've made it go to the "Donation election 2023" section
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206105675771341) by [Unito](https://www.unito.io)
> Make donation election link in home page RHS go to the #election element

- packages/lesswrong/components/common/LWTooltip.tsx
- packages/lesswrong/components/posts/TableOfContents/AnswerTocRow.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206099672854186) by [Unito](https://www.unito.io)
> Fix oversized images in answers-ToC tooltip (and other tooltips that use LWTooltip)

- packages/lesswrong/components/comments/CommentsItem/CommentsItemMeta.tsx
- packages/lesswrong/components/comments/SingleLineComment.tsx
Fixes a bug introduced in https://github.com/ForumMagnum/ForumMagnum/pull/8347
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206117279201886) by [Unito](https://www.unito.io)
> LW Deploy: fix implicit null/undef coercion that parent comment arrows were relying on

- packages/lesswrong/components/linkPreview/PostLinkPreview.tsx
For some reason comment hover previews stopped being clickable. My guess is to do with the recent EA Forum refactors in the space.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206118719276873) by [Unito](https://www.unito.io)
> Fix hover behavior of comment previews

- packages/lesswrong/components/dialogues/DialogueRecommendationRow.tsx
- packages/lesswrong/components/dialogues/DialoguesList.tsx
- packages/lesswrong/components/users/DialogueMatchingPage.tsx
- packages/lesswrong/lib/abTests.ts
- packages/lesswrong/lib/components.ts
- packages/lesswrong/server/repos/TagsRepo.ts
- packages/lesswrong/server/resolvers/userResolvers.ts
* Add a card to the dialogues match form containing recommended content by the other user (top tags, posts, comments)
* Restyle the whole dialogue match form to look cleaner given this
* Fix some dependency cycles that resulted
Before: 
After:
> Add recommended content to dialogue match form and restyle

- packages/lesswrong/components/users/DialogueMatchingPage.tsx
- packages/lesswrong/lib/abTests.ts
Simple AB Test. Tested it locally and works fine (slightly strange behaviour if you've already filled in a calendly link for a given match and then rematch but are now in the noShow group, but that will be no one so seems OK)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206126097974699) by [Unito](https://www.unito.io)
> AB Test the calendly

- packages/lesswrong/components/dialogues/DialoguesList.tsx
- packages/lesswrong/server/repos/UsersRepo.ts
* In order to not spam users on frontpage, we only show recommended dialogue users every other day (on even days). Seemed like a fair enough hack for now
* Also solves the bug where the same user used to appear twice in recommendations occasionally
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206126421437729) by [Unito](https://www.unito.io)
> Only show recommendations on even days, and fix the bug where same user shown twice

- packages/lesswrong/lib/reviewUtils.tsx
We had the annual review vote buttons showing up on all posts on AF because things weren't forum-gated correctly.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206145488842322) by [Unito](https://www.unito.io)
> make annual review behave the same way on AF as on LW

- packages/lesswrong/server/callbacks/alignment-forum/callbacks.ts
[https://github.com/ForumMagnum/ForumMagnum/commit/31c648667d6e835d053426cd97e2c53e71fbdd09#diff-f5ee8a7fae29435bf470a8[…]db6f279f31c0e1327756dc61R18](https://github.com/ForumMagnum/ForumMagnum/commit/31c648667d6e835d053426cd97e2c53e71fbdd09#diff-f5ee8a7fae29435bf470a8aabe2ff9a6cbf262c6db6f279f31c0e1327756dc61R18) had the wrong order of operations; it should be `(vote.afPower ?? 0) + sum` but instead it evaluates as `vote.afPower ?? (0 + sum)`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206145597082571) by [Unito](https://www.unito.io)
> Fix AF voting

- packages/lesswrong/components/users/DialogueMatchingPage.tsx
- packages/lesswrong/lib/collections/users/fragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
Adds an easier & more visible way to opt out of the "You have new checks" notification.
Adds that notification field to the CurrentUser fragment so that we can easily get the right initial state of the checkbox
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206146600623617) by [Unito](https://www.unito.io)
> Add check notification opt-out on matching page

- packages/lesswrong/components/users/DialogueMatchingPage.tsx
- packages/lesswrong/server/repos/UsersRepo.ts
Also no longer unions in users who just opted in to facilitation in that section. That was needed in the beginning when no one had been active, but now isn't necessary, and also breaks the sort.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206146945776876) by [Unito](https://www.unito.io)
> Sort recent users on dialogue matching in the other direction and move that section up

- packages/lesswrong/server/languageModels/autoTagCallbacks.ts
- packages/lesswrong/server/scripts/generativeModels/generateTaggingPostSets.ts
Given [this](https://openai.com/blog/gpt-4-api-general-availability), we fine-tuned a new model for the criticism tips card. We used `davinci-002` as the base and it performs about as well (maybe slightly better) than the old one, which was on `curie`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206051916184997) by [Unito](https://www.unito.io)
> [EA Forum only] fine-tune new model for criticism tips card

- packages/lesswrong/lib/collections/databaseMetadata/collection.ts
- packages/lesswrong/lib/collections/debouncerEvents/collection.ts
- packages/lesswrong/lib/collections/pagecache/collection.ts
- packages/lesswrong/lib/collections/readStatus/collection.ts
- packages/lesswrong/server/migrations/20231211T000000.dropOldIndexes.ts
- packages/lesswrong/server/testingSqlClient.ts
As a follow-up to https://github.com/ForumMagnum/ForumMagnum/pull/8045, we should:
1. replace the `ensureIndex` calls responsible for making the unique indexes used by various `ON CONFLICT` queries with `ensureCustomPgIndex`, since anyone starting a ForumMagnum instance from scratch might end up with the wrong indexes (the query builder may generate them with `COALESCE` calls that don't correctly correspond to the `ON CONFLICT` queries).
2. run the following SQL manually (since I can't figure out how to get `yarn migrate create --name=[...]` to work):
```
DROP INDEX "idx_DatabaseMetadata_name_old";
DROP INDEX "idx_DebouncerEvents_dispatched_af_key_name_filtered_old";
DROP INDEX "idx_PageCache_path_abTestGroups_bundleHash_old";
DROP INDEX "idx_ReadStatuses_userId_postId_tagId";
ALTER INDEX …
```
> replace old unique index declarations with custom ones

- packages/lesswrong/lib/collections/users/schema.ts
Previously we were gating on whether dialogues were enabled, but EA Forum now has dialogues enabled but not all of these features.
Move to a straightforward `isLW` forum gate
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206154738843853) by [Unito](https://www.unito.io)
> Forum gate notification settings

- packages/lesswrong/components/common/Header.tsx
- packages/lesswrong/components/ea-forum/giving-portal/GivingSeasonHeader.tsx
You need to double click items on the right of the header (such as the search bar) to activate them. #8402 fixed this for the normal header, but not for the giving season header. This PR just ports the change over to there too.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206162804290385) by [Unito](https://www.unito.io)
> Fix needing to double click items in giving season header

- packages/lesswrong/components/posts/PostsPage/PostsPagePostFooter.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
- packages/lesswrong/lib/instanceSettings.ts
This was added in WakingUp codebase originally and migrated upstream as a part of #7908 
But it's true for all the forums (and there is additional confusion about it in the WakingUp codebase) so I figured I'll remove it to simplify things. People with waking up access can see more context in https://app.clickup.com/t/8686p22dk
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206147485321757) by [Unito](https://www.unito.io)
> Removing `hasShareButtonsSetting`

- packages/lesswrong/themes/createThemeDefaults.ts
- packages/lesswrong/themes/globalStyles/globalStyles.ts
- packages/lesswrong/themes/themeType.ts
This PR makes the base font size configurable in theme files. We're using it at WakingUp.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206165895289748) by [Unito](https://www.unito.io)
> Add baseFontSize as a theme variable

- packages/lesswrong/lib/betas.ts
- packages/lesswrong/lib/collections/ckEditorUserSessions/collection.ts
- packages/lesswrong/lib/collections/ckEditorUserSessions/schema.ts
- packages/lesswrong/server/ckEditor/ckEditorWebhook.ts
- packages/lesswrong/server/repos/UsersRepo.ts
Fixing the bug whereby the server would error on receiving new ckeditor webhooks, due to the createMutator not being properly configured
Also, add indexes for the CkEditorUserSessions table
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206176719035771) by [Unito](https://www.unito.io)
> resolve webhook bug

- packages/lesswrong/lib/collections/votes/views.ts
- packages/lesswrong/server/migrations/20231211T000000.dropOldVoteIndex.ts
While investigating slow render times for `404`s (as part of a broader investigation around performance issues arising from a user accidentally DoSing us), we found that the `getKarmaChanges` query was attempting to use the `idx_Votes_authorIds_votedAt_userId_afPower` index, but was performing a bitmap index scan on it, and taking ~600 ms (for both of the individual queries that get called in that repo method).  My current best guess as to why is that it was a GIN index and trying to perform range comparisons (as with `votedAt`) just doesn't work.
So we're just replacing it with single-column GIN index on `authorIds`, and then the query takes on the order of 5-50 ms (tested with users who have ~2k and ~20k karma, respectively).
We need to drop the old index or postgres will continue to …
> replace index on votes used by getKarmaChanges query

- packages/lesswrong/components/dialogues/DialoguesList.tsx
- packages/lesswrong/server/callbacks/postCallbacks.ts
Want to avoid users' frontpage getting clocked up. Add the hiding "x" to matches, moved over from recommendations. 
Also, if a dialogue is published, we reset the hide preference on the check between those two users. 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206186979948630) by [Unito](https://www.unito.io)
> Allow hiding individual matches from frontpage

- packages/lesswrong/server/serverSentEvents.ts
Two line fix. You can ascertain by looking at the similar behavior in checkForNotifications and checkForTypingIndicators. 
Not sure how this slipped and ended up different, but fixed now.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206187235960568) by [Unito](https://www.unito.io)
> fix bug with iterating over undefined openConnections[userId]

- packages/lesswrong/components/review/FrontpageReviewWidget.tsx
- packages/lesswrong/lib/collections/posts/views.ts
This fixes the quick review page, which relies on the reviewVoteScore fields to be populated, but those are not yet populated (they require running a manual migration).
The migration seems a bit jank, so it seemed better to do this hotfix and fix the scores tomorrow.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206190048249065) by [Unito](https://www.unito.io)
> Hotfix to fix Quick review page

- packages/lesswrong/server/repos/perfMetricWrapper.ts
When running a `migrate` command, ts-node blows up when trying to set a new value for a function's `name` by direct assignment (as I was doing when wrapping repo methods with perf metrics) with "Cannot assign to read only property 'name' of function".  `Object.defineProperty` gets around this.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206200880317819) by [Unito](https://www.unito.io)
> rename wrapped function properly

- packages/lesswrong/lib/collections/moderatorActions/helpers.ts
This allows you to specify what would trigger initial user review as a DB setting
As this previously had an EA conditional: we need to add a setting override on EA side before merging this (adding `mapLocation` to the list of reasons that trigger review)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206155438046277) by [Unito](https://www.unito.io)
> Make reasonsForInitialReview configurable

- packages/lesswrong/server/search/elastic/ElasticQuery.ts
Elasticsearch is issuing warnings because we're using the `exclude` parameter which is now deprecated in favour of `excludes`. For our purposes they're functional identical, but this should make us more future proof in case the old version ever gets removed.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206202766402337) by [Unito](https://www.unito.io)
> Replace elasticsearch `exclude` parameter with `excludes`

- packages/lesswrong/components/comments/PopularComment.tsx
Long-standing feature request to add a posts tooltip to the post link in the title of popular comments on the frontpage.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206202949520172) by [Unito](https://www.unito.io)
> Add a `PostsTooltip` to the post title of popular comments

- packages/lesswrong/lib/collections/posts/schema.tsx
We have a long-standing bug where posts can sometimes end up with a negative comment count. It's possible that this is actually due to multiple bugs, but the most obvious and easily-reproducible case is when an unreviewed user creates a comment and then gets rejected. This case also has a sub-bug where the comment count will be 1 whilst displaying 0 comments as the unreviewed comment is hidden.
This fix here is just to add `authorIsUnreviewed` to the filter function for the denormalized count of references. Once this is merged you can run `./scripts/serverShellCommand.sh --wait "Globals.recomputeDenormalizedValues({collectionName: 'Posts', fieldName: 'commentCount'})"` to fix existing instances of this bug (note that this is pretty slow - you may want to increase the batch size in …
> Fix -1 `commentCounts` due to unreviewed users

- packages/lesswrong/server/apolloServer.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/pageCache.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
This makes it so that if a request waits in the request queue, but by the time its turn comes up the request's connection is already closed, then we don't do an SSR for that request. In theory, this should significantly improve recovery time after a server is overloaded with excessive requests, if the clients behind those requests close their connections before waiting for them to complete.
Tested by filling up a local development server's request queue with
```
for i in {1..50}; do wget "http://localhost:3000/?noCache=${i}" & done 
```
then while that's working, doing
```
wget localhost:3000/?distinctive-url
```
in another console and quickly cancelling it with ^C. I then searched a log file of the server's console output to check that the `?distinctive-url` request (and no others) had …
> Don't SSR if request is cancelled while waiting in the request queue

- packages/lesswrong/server/search/elastic/ElasticQuery.ts
Our custom highlighting doesn't play nicely with nearest-geographically sorting - in fact, it causes an exception inside elastic that aborts the search. We don't actually use or need and highlighting here though, so we can just disable it in this case.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206202929176531) by [Unito](https://www.unito.io)
> Fix community map keyword search

- packages/lesswrong/components/posts/PostSubmit.tsx
- packages/lesswrong/lib/publicSettings.ts
Requires a setting update on EA forum side, as we're migrating from ForumSelect that had an EA override
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206216596475507) by [Unito](https://www.unito.io)
> Make requestFeedbackKarmaLevel into a setting 

- packages/lesswrong/components/dialogues/ActiveDialogues.tsx
Upon Oli's request, make it clearer the "eye" icon can be interacted with.
> Tiny style fix to online users icon

- packages/lesswrong/lib/types/collectionTypes.ts
- packages/lesswrong/server/analyticsWriter.ts
- packages/lesswrong/server/apolloServer.ts
- packages/lesswrong/server/perfMetrics.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
(@b0b3rt edit) We also start logging a new analytics event that records the SSR queue state every five seconds (if it's not empty when the `setInterval` goes off).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206208473886837) by [Unito](https://www.unito.io)
> Add user user_id and render startedAt to perf_metrics logging

- packages/lesswrong/server/analyticsWriter.ts
Forgot to actually add this to the events being written 🤦
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206227187220140) by [Unito](https://www.unito.io)
> actually add queue_priority to perf metrics

- packages/lesswrong/components/editor/CKPostEditor.tsx
- packages/lesswrong/server/ckEditor/ckEditorCallbacks.ts
This PR fixes two issues:
1. the nullability PR accidentally broke anonymous link sharing by requiring that users be logged in for the `getLinkSharedPost` query
2. link sharing with users who aren't explicit collaborators didn't work for dialogues, because we were registering post fixers on the client side, and then manually writing a change to the document to trigger the post fixers.  When this was happening on the clients of link-shared users, CKEditor complained unless the link sharing setting was set to "edit", since it saw that the client of a user who didn't have "edit" authorization was trying to edit the collaborative document.  This blew up in the CKPostEditor `onInit`.  We fix this by only doing the post-fixer and manual change if the user has a sufficient access level.
┆Issue …
> fix both anonymous link sharing and link sharing for dialogues

- packages/lesswrong/server/repos/VotesRepo.ts
- packages/lesswrong/server/voteServer.ts
Adds a limit where you can only strong-vote 3 times on comments on a single post. The idea is that if someone is worked up about a controversy-thread, such that they would strong-vote on everything, they're limited to only 3 strong-votes, which reduces the degree to which they can control post-scores to something closer to the level of influence that more casual commenters have.
Also adds a limit of 10 strong-votes per hour, which is meant to discourage people from using strong-votes for all their voting.
(PR comments for the technical side; for the policy-discussion about these rate limits, use the Slack thread thread in forum-magnum-product.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206217785958930) by [Unito](https://www.unito.io)
> Add voting limits: 3 strong-votes on comments on the same post, 10 strong-votes in an hour

- scripts/loadDbSettings.ts
#8454 changed the way the unique index on DatabaseMetadata was created, from a unique `COALESCE("name", ''::TEXT)` to a unique `"name"`. As a consequence, our script for upserting our altered database settings was trying to match an out out of date index.
(cc @b0b3rt, FYI)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206208545657672) by [Unito](https://www.unito.io)
> [EA] Fix DB settings upsert script for new form of the unique index

- packages/lesswrong/components/ea-forum/digest/Digests.tsx
- packages/lesswrong/components/ea-forum/digest/EditDigestHeader.tsx
- packages/lesswrong/lib/collections/digests/helpers.ts
I just wanted to increase the limit to display more digests here, and I also ended up cleaning up the UI a bit to make it more readable.
Old:
New:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206215174297608) by [Unito](https://www.unito.io)
> [EA Forum only] cleanup the digests list

- packages/lesswrong/server/scripts/convertImagesToCloudinary.ts
`convertImagesToCloudinary` sometimes gets run on fields other than contents (eg, moderation guidelines), and those fields are often blank. This leads to scary but meaningless warnings that show up in logs and Sentry. DDon't warn in that case.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206262521077459) by [Unito](https://www.unito.io)
> Fix spurious warnings about missing revs in convertImagesToCloudinary

- packages/lesswrong/components/common/LWHome.tsx
Spotlight item width was wonky at certain page widths, due to having 100% width and not being in a container. Introduced in [49ddbd0180039928e759e9c9f89699ad08b89708](https://github.com/ForumMagnum/ForumMagnum/commit/49ddbd0180039928e759e9c9f89699ad08b89708) which added the `DismissibleSpotlightItem` without wrapping it in a `SingleColumnSection` (it was previously removed together with the rest of `RecommendationsAndCurated`, which wraps it that way, and which is temporarily removed to make room for the review)
> Fix spotlight item width

- packages/lesswrong/lib/vulcan-lib/utils.ts
From Intercom: 
**Jefftk:** 
I wonder whether allowing the <audio> element to pass through from RSS would be safe? For example, https://www.lesswrong.com/posts/NTdfTaumDFFz4oMC4/boston-solstice-2023-retrospective would be better with the inline mp3 player you can see on the https://www.jefftk.com/p/boston-solstice-2023-retrospective version
**Me:** 
Oh, yeah, don't see any particular reason why not
=====
Tested on this post: lesswrong.com/posts/NTdfTaumDFFz4oMC4/boston-solstice-2023-retrospective
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206261773462004) by [Unito](https://www.unito.io)
> Allow audio elements as part of RSS crosspost

- packages/lesswrong/components/comments/ModerationGuidelines/ModerationGuidelinesBox.tsx
- packages/lesswrong/lib/editor/ellipsize.tsx
- packages/lesswrong/lib/truncatise.ts
- packages/lesswrong/unitTests/truncatise.tests.ts
Truncatise is a library which takes HTML, and shortens it to a target character, word, or paragraph count. We vendored/forked this library long ago. It's not very fast; it's written as-if a Shlemiel the Painter algorithm (though I think V8 sneakily optimizes that away), and does a bunch of unnecessary memory-allocating and regexing. Rewrite it, simplifying the code, dropping the unused StripHTML feature, and greatly speeding it up. Performance improvement for the logged-out front page was about 30ms (5%) overall (using the profiler to look only at the highlightFromHTML and truncatise functions). Also add a few unit tests for it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206277096841119) by [Unito](https://www.unito.io)
> Speed up truncatise()

- packages/lesswrong/components/comments/CommentsTableOfContents.tsx
- packages/lesswrong/components/users/UsersNameDisplay.tsx
- packages/lesswrong/components/vulcan-forms/FormComponent.tsx
Fix excess padding on form checkboxes with tooltips. Prevent hover-flicker on short usernames when nokibitz is on. Apply nokibitz to comments-ToC.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206282700086884) by [Unito](https://www.unito.io)
> Nokibitz polish

- packages/lesswrong/lib/collections/users/schema.ts
Hides the following from the account settings page:
- `hideFrontpageBook2020Ad`
- `walledGardenInvite`
- `paymentEmail`
- `paymentInfo`
- `reviewForAlignmentForumUserId`
`paymentEmail` and `paymentInfo` are the only fields in the `Prize/payment info` group, so that entire group is no longer shown.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206287690771055) by [Unito](https://www.unito.io)
> Hide some LW/AF specific user settings on the EA forum

- packages/lesswrong/lib/collections/comments/views.ts
- packages/lesswrong/lib/collections/posts/views.ts
- packages/lesswrong/server/repos/CommentsRepo.ts
The new perf metrics for db_repo_methods indicated that both `getRecentlyActiveDialogues` and `getMyActiveDialogues` were abominably slow, given what they were doing.  As well they must have been, since neither `collabEditorDialogue` nor `mostRecentPublishedDialogueResponseDate` were indexed anywhere, and correspondingly the query plans indicated the dreaded `Seq scan on "Posts" p` was chewing up DB cycles.
This PR creates a partial index (only for dialogues) which orders by the same condition used by `getRecentlyActiveDialogues`, hopefully taking it from ~300ms (warm start) - 1s (cold start), to well under 1ms (at least if the reduction is similar to what it is on dev).  Initially I was also filtering on non-draft dialogues, but removing that part of the index condition also got …
> add indexes for some poorly performing queries

- packages/lesswrong/lib/rateLimits/constants.ts
- packages/lesswrong/lib/rateLimits/types.ts
- packages/lesswrong/lib/rateLimits/utils.ts
- packages/lesswrong/server/rateLimitUtils.ts
- packages/lesswrong/unitTests/autoRateLimit.tests.ts
Changing the previously overparameterised type signature, to one where each rateLimit instead just takes as input a boolean function, that determines whether it's active or not. 
Also renames the ambiguously named userRateLimits to some version of manualRateLimit in various places. 
This is the first step to then more easily add some new, somewhat more complicated rate limits. (In addition, TODO remains to remove the deprecated ModeratorAction rate limits, which should be replaced with the manual ones)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206292005425856) by [Unito](https://www.unito.io)
> Refactor autoRateLimits

- packages/lesswrong/components/linkPreview/HoverPreviewLink.tsx
- packages/lesswrong/components/notifications/NotificationsItem.tsx
- packages/lesswrong/components/vulcan-core/App.tsx
- packages/lesswrong/lib/routes.ts
- packages/lesswrong/lib/vulcan-core/appContext.ts
- packages/lesswrong/lib/vulcan-lib/routes.ts
- packages/lesswrong/server/adminRoutesMiddleware.ts
- packages/lesswrong/server/apolloServer.ts
- tsconfig.json
This also designates some example routes admin-only (without removing their in-component checks for now)
The original motivation for this is making some routes admin only on Waking-UP forum which are public on other forums, but I think this is generally probably a better approach vs having a check on each component.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206252214463774) by [Unito](https://www.unito.io)
> Create a middleware to allow making some routes admin-only

- packages/lesswrong/components/common/excerpts/PostExcerpt.tsx
- packages/lesswrong/components/hooks/useForeignCrosspost.ts
- packages/lesswrong/components/posts/EALargePostsItem.tsx
- packages/lesswrong/server/fmCrosspost/types.ts
Fixes two bugs in `EALargePostsItem` reported by Agnes:
Before:
After:
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206323640704667) by [Unito](https://www.unito.io)
> Bug fixes for `EALargePostsItem`

- packages/lesswrong/components/posts/PostsList2.tsx
- packages/lesswrong/components/posts/usePostsList.ts
Requested by Lizka (see discussion in slack [here](https://cea-core.slack.com/archives/C02N5PKL021/p1705001473570429))
> if it’s been over 5 days since the last curation, the curations are no longer ~pinned on the Frontpage (even for people who haven’t read them)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206332415188419) by [Unito](https://www.unito.io)
> [EA Forum only] hide frontpage curated section without recent curation

- packages/lesswrong/components/editor/EditorFormComponent.tsx
- packages/lesswrong/components/posts/PostsNewForm.tsx
- packages/lesswrong/components/vulcan-core/App.tsx
- packages/lesswrong/lib/routeUtil.tsx
- packages/lesswrong/lib/sql/PgCollection.ts
- packages/lesswrong/lib/vulcan-core/appContext.ts
- packages/lesswrong/server.ts
- packages/lesswrong/server/scripts/cleanUpDuplicatePostAutosaves.ts
The autosaving functionality had a very silly bug where `contents` was included in the dependency list of `saveRemoteBackup`, which meant that when it was throttled in `throttledSaveRemoteBackup`, the throttling didn't do much, since `saveRemoteBackup` kept getting re-created each time `contents` changed (every ~3 seconds, per another throttled function).  This resulted in users having a bunch of queued-up posts to be created after they'd been working on a new draft for five minutes.
The fix is to compare to a ref of the previous contents (from before the last successful autosave) without having that in the dependency list.
EDIT: since @jimrandomh is rewriting this component for the React 18 upgrade, I've gone ahead and instead commented out the code which actually invokes the autosave. …
> fix post autosave so it doesn't save a bunch of duplicates

- .github/workflows/unitTests.yaml
- packages/lesswrong/server/migrations/20231205T204412.make_fields_not_nullable.ts
We've had several instances recently (including by me) where we add migrations that accidentally break the process of bootstraping a new ForumMagnum instance. This PR adds a CI workflow that checks for this.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206349589246049) by [Unito](https://www.unito.io)
> Add Postgres bootstrap CI workflow

- packages/lesswrong/components/common/excerpts/PostExcerpt.tsx
- packages/lesswrong/components/posts/EALargePostsItem.tsx
I added `PostsPage` and `SunshinePostsList` to the list of supported fragments when making cross-site requests for crosspost bodies in #8619. However, these fragments couldn't actually be used until that PR was deployed to prod for both the EA Forum and LessWrong. This has now been done (in #8630 and #8634) so this PR makes the changes needed to actually use the correct fragments.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206338724786321) by [Unito](https://www.unito.io)
> Enable correct fragments for calls to `usePostContents`

- packages/lesswrong/components/ea-forum/DigestAd.tsx
- packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx
- packages/lesswrong/components/recommendations/PostBottomRecommendations.tsx
- packages/lesswrong/lib/components.ts
Most of this PR is just moving the homepage RHS digest ad to a separate file. This way I could reuse it in the post page footer. Based on [this comment thread](https://docs.google.com/document/d/1BmbGKMlkFAILwoc9298kEAM5DW2AGKb1ygu9z0vGQ6I/edit?disco=AAAA9u9CuSE).
-----
Maybe it looks better with a max width:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206324629482403) by [Unito](https://www.unito.io)
> [EA Forum only] digest ad in the post page footer

- packages/lesswrong/server/search/elastic/ElasticConfig.ts
Tested that the ranking was sensible and no reindexing is needed by searching for part of the name of a preexisting negative karma user, and seeing that they appeared in the results and were ranked behind a similarly-named positive-karma users.
(Specifically, searched for "GPT", which matches two novelty accounts from two different April Fools jokes on LW.)
Co-Authored-By: Sarah Cheng <sarah.cheng@centreforeffectivealtruism.org>
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206341654331959) by [Unito](https://www.unito.io)
> Negative karma users can show up in search

- packages/lesswrong/lib/collections/posts/fragments.ts
- packages/lesswrong/lib/collections/posts/schema.tsx
- packages/lesswrong/lib/collections/sequences/fragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
There's currently a bug on the EA best of page where the whole page will be reloaded when a sequence tooltip finishes loading the list of posts. This is because it refetches `PostsList` fragments which contain `socialPreviewData` which doesn't have a unique id, which makes the Apollo cache unable to merge the new data with the old data.
This PR adds an `_id` field to `SocialPreviewType` which is just a copy of the related post id, and allows the Apollo cache to perform a merge. I also added `_id`s to a couple of other fragments that I found along the way whilst investigating the bug.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206362866933342) by [Unito](https://www.unito.io)
> Include post id in `SocialPreviewType` to avoid breaking the Apollo cache

- packages/lesswrong/components/linkPreview/FootnotePreview.tsx
Footnote hover-preview didn't use <ContentStyles> so it didn't have a width limit for images, and missed some other misc bits of styling (eg hiding spoilers). Fix that. Also, there was complicated code to remove the backlink from the preview, which wasn't working; rewrite that to a much simpler thing.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206341522616742) by [Unito](https://www.unito.io)
> Fix footnote hover-previews having giant images, spoilers, backlink arrow

- packages/lesswrong/lib/collections/posts/schema.tsx
From examining our new perf metrics, it turns out that `PostRelationsRepo.getPostRelationsByPostId` makes up a good ~15% of named queries (i.e. those in Repos) talking to our database.  This seems a bit gratuitous when it's only used for question-posts, which are a tiny fraction of all posts.  (I assume there's a comparable volume of queries generated by `sourcePostRelations` as `targetPostRelations`.)  At first I tried to do this by factoring the two fields out of the `PostsDetails` fragment, but this proved fairly annoying, so I just gated it at the field resolver level, since in practice we only have one type of PostRelation and it's for question parent-child relationships.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206354838475658) by …
> only get post relations for questions

- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
The navigation items look visually best if they go from longest to shortest.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206343865812003) by [Unito](https://www.unito.io)
> Move the position of the dialogue matchmaking navigation item

- packages/lesswrong/components/Layout.tsx
The [latest deploy](https://github.com/ForumMagnum/ForumMagnum/pull/8650/files#diff-156855efcb3c86557cbcb3c72337d926e4c98516cb5bbb4785840cf50e89f7b6) messed up our homepage layout. Forum-gating the relevant class.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206366671237351) by [Unito](https://www.unito.io)
> fix EAF home layout

- packages/lesswrong/components/ea-forum/EAButton.tsx
Previously the `EAButton` component was just adding styling. This is to help us track things more easily by default.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206378000525956) by [Unito](https://www.unito.io)
> [EA Forum only] add default analytics to EAButton

- packages/lesswrong/components/recentDiscussion/useRecentDiscussionThread.ts
https://github.com/ForumMagnum/ForumMagnum/pull/8045 Made it so commentCount starts as 0 rather than null, which broke the logic we used to decide whether a post had never been commented on vs having comments that were now deleted.
I've updated it to check if `lastCommentedAt` is close to (or before) `postedAt`, and use that as the criterion for deciding whether to show a post or not. The case where we don't want to show a post is when it gets a spam comment long after posting which we then delete
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206143262749473) by [Unito](https://www.unito.io)
> Fix bug where new posts dont appear in recent discussion due to commentCount being non-null

- packages/lesswrong/components/users/NewUserCompleteProfile.tsx
This PR adds a link to the new user registration page that lets the user book a user interview call with a person on the EA Forum Team. In return we offer to answer any questions they have about EA or the Forum. We're trying this out as a way to generally do more user interviews.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206366933557753) by [Unito](https://www.unito.io)
> [EA Forum only] new users can book a call with an EAF team member

- packages/lesswrong/components/comments/CommentsNode.tsx
- packages/lesswrong/server/languageModels/modGPT.ts
I feel it's been too harsh on people more times than is acceptable, plus it's still not good at differentiating when a comment contains a quote. For now we are pausing the user-facing components, while we work on improving the prompt.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206385599216544) by [Unito](https://www.unito.io)
> [EA Forum only] temporarily pause ModGPT

- packages/lesswrong/lib/vulcan-lib/routes.ts
- tsconfig.json
https://github.com/ForumMagnum/ForumMagnum/pull/8568/files added a usage of `Array.findLast` which broke compatibility with older versions of Safari. After thinking this was likely fine, I found out Robert's laptop was in fact running an affected version, so versions that old are in fact still present in the wild.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206424808732263) by [Unito](https://www.unito.io)
> Fix older versions of Safari

- packages/lesswrong/server/apolloServer.ts
This prevents a potentially large number of http requests when you open a bunch of post pages, and when using the reaction palette, when those requests are destined to just be 304 Not Modified. (These requests may have contributed to some users going over the rate limit when opening lots of post pages as part of review-voting.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206424170685267) by [Unito](https://www.unito.io)
> Set cache-control header to make reaction images immutable

- packages/lesswrong/lib/collections/tags/permissions.ts
As mentioned in the discussion at [this issue](https://github.com/ForumMagnum/ForumMagnum/issues/8610), this PR fixes tag voting permissions so that tags for voting are hidden when they're intended to be.
@oetherington I think you liked this change as referenced there, so if you approve this PR then that makes it official.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206366048643641) by [Unito](https://www.unito.io)
> Fix tag voting permission check

- packages/lesswrong/components/admin/AdminHome.tsx
- packages/lesswrong/components/hooks/useRefreshDbSettings.ts
- packages/lesswrong/server.ts
- packages/lesswrong/server/resolvers/databaseSettingsResolvers.ts
Whilst debugging something else I wanted to change some database settings on a running staging server without waiting for them to automatically refresh.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206423468590199) by [Unito](https://www.unito.io)
> Add admin page link to force-reload DB settings

- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersProfileInfo.tsx
Currently it says "Expand". I just watched a mod go to a user page and not know how to get to the mod tools. This should remedy that, but telling the moderators what they should expand. I've left this in for LW, as it seems to make the process of onboarding new mods very cheaply better. cc @Raemon.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206445791546415) by [Unito](https://www.unito.io)
> Improve the wording of the collapsed moderator section on the user page

- packages/lesswrong/components/ea-forum/EAHomeMainContent.tsx
- packages/lesswrong/components/form-components/FormComponentPostEditorTagging.tsx
In this PR:
- Show it first in the topic bar
- Fix an issue where it appeared as both a core topic and a post type (when `core` was set on it)
_Crosspost of a slack comment for context_
> So, currently the thing that decides whether something is in the topic bar is whether it is a “core” topic. This also controls some other things, like whether it appears in the core topics section on the main topic page, and whether it appears as a core topic in the edit post page (note it would now appear twice as a post type and core topic, which is not ideal). (see 1st and 2nd image)
>
> Then there is a separate “Is subforum” option that controls the layout of the topic page itself, and when we did a refactor a while ago we made (approximately?) all the core topics have the subforum layout to reduce …
> Changes to support opportunities in the topic bar

- packages/lesswrong/components/ea-forum/users/EAUsersProfile.tsx
This copies the karma gating that the user dropdown menu uses for the "New sequence" button, to also hide it on the user profile page.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206454787729909) by [Unito](https://www.unito.io)
> [EA Forum only] karma gate "New sequence" button on user profile

- packages/lesswrong/server/analytics/analyticsCron.ts
- packages/lesswrong/server/repos/IncrementalViewRepo.ts
- packages/lesswrong/server/repos/PostViewTimesRepo.ts
- packages/lesswrong/server/repos/PostViewsRepo.ts
- packages/lesswrong/server/resolvers/analyticsResolvers.ts
There was a timezone bug in the cron job that populates the analytics data, this caused some posts (e.g. [this one](https://forum.effectivealtruism.org/postAnalytics?postId=fovDwkBQgTqRMoHZM)) to undercount views, and then this could mean they were inconsistent with reads and you end up with a negative bounce rate. This only affected days during British daylight savings time.
The job takes a while to rerun, so I'll fix the 2023 data today and then run the rest of the time range overnight tonight (update: I have now done this).
I also noticed that "Mean reading time" was way too high, because I forgot to calculate it and was just using the read count as a number of seconds 🤦‍♂️.
The bug was in this function:
```typescript
const results = await analyticsDb.any<
Omit<DbPostViews, "_id" | …
```
> Fix timezone bug in author analytics

- packages/lesswrong/components/sunshineDashboard/ReportForm.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineReportedContentList.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineReportedItem.tsx
- packages/lesswrong/lib/collections/reports/fragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
Request from Lizka in Slack. Make the user names for reported content clickable and hoverable in the sunshine side bar. Also, fix some broken fragments that were covered up by an `any`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206455416754554) by [Unito](https://www.unito.io)
> Clickable users in sunshine reports

- packages/lesswrong/lib/make_voteable.ts
- packages/lesswrong/lib/sql/ProjectionContext.ts
- packages/lesswrong/lib/sql/tests/testHelpers.ts
- packages/lesswrong/lib/types/collectionTypes.ts
- packages/lesswrong/lib/types/schemaTypes.ts
- packages/lesswrong/lib/utils/schemaUtils.ts
- packages/lesswrong/unitTests/sql/ProjectionContext.tests.ts
Adds some generic type constraints to various functions in the parent branch, so as to make life a bit easier & prevent typos/etc.
The main thing I'm not sure about here is the type of `on` in `SqlJoinBase`: `Partial<Record<FieldName<N>, string>>` technically allows `{ _id: undefined }`.   (The previous `Record<string, string>` did not.)
There isn't an easy way that I can find to represent a generic type constraint which allows an arbitrary selection of keys from a union type, where the value of those keys must not be undefined if the key is in the object (but any individual key is not required to be in the object).  https://github.com/microsoft/TypeScript/issues/13195 introduced `--strictOptionalProperties` but we can't enable that; too much stuff breaks.
I think it's worth the trade-off …
> add type constraints for various sql fragment functions

- packages/lesswrong/components/common/ErrorAccessDenied.tsx
For example, [http://localhost:3000/posts/7Pmv23kPH7oMvQsmZ](http://localhost:3000/posts/7Pmv23kPH7oMvQsmZ)
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206497054205242) by [Unito](https://www.unito.io)
> Add basic font styles for `ErrorAccessDenied` component

- packages/lesswrong/lib/sql/ProjectionContext.ts
- packages/lesswrong/lib/sql/Query.ts
- packages/lesswrong/lib/sql/SelectFragmentQuery.ts
- packages/lesswrong/lib/sql/SelectQuery.ts
- packages/lesswrong/lib/types/collectionTypes.ts
- packages/lesswrong/lib/vulcan-core/default_resolvers.ts
- packages/lesswrong/unitTests/sql/SelectFragmentQuery.tests.ts
Regression fix from #8314 - we're not currently compiling synthetic fields when we generate SQL projections. Thankfully this feature is very rarely used so the damage is limited - pretty much just showing empty post lists if you sort by inflation-adjusted karma.
It's probably now possible to simply rewrite the synthetic fields as resolver-only fields in the schema that define a SQL resolver, but for for the sake of expediency I just added the existing projection copmilation into the generation of `SelectFragmentQuery`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206506407197856) by [Unito](https://www.unito.io)
> Compile synthetic fields when generating SQL projections

- .github/workflows/deployEAProd.yaml
We deploy the main prod site and the API bot site at the same time. Currently, both deploys try to run the migrations. This usually works but occasionally it fails with a "deadlock detected" error. This doesn't cause any damage (you can just rerun the failed workflow) but it is annoying.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206499496449381) by [Unito](https://www.unito.io)
> [EA] Only run prod migrations on prod deploy, not when deploying API site

- packages/lesswrong/lib/collections/votes/schema.ts
The vote history page currently bypasses permission checks. This means it's possible to view, for instance, a post that has been moved to drafts as long as you voted on it whilst it was public (note that you can't actually view it on the posts page, but it will still show up in your vote history).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206506918313820) by [Unito](https://www.unito.io)
> Fix permissions for vote history page

- packages/lesswrong/components/notifications/NotificationsPage/NotificationsPageItem.tsx
Fixes a bug where the "link" button on the top right of preview comments on the notifications page links to the frontpage, instead of to the actual comment on the original post.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206486451079319) by [Unito](https://www.unito.io)
> Fix permalinks on notifications page comments

- packages/lesswrong/components/vulcan-forms/FormComponent.tsx
When editing your user profile, clicking on the "x" to clear the "Organizer of" field causes this error on submit: "null value in column "organizerOfGroupIds" of relation "Users" violates not-null constraint".
This is related to how we recently made a bunch of fields non-nullable in the DB, together with how `clearField()` works. Most form fields don't use the option to add the "x" to clear the field, but this particular one does, and clicking it would cause the form to set the value to `null`. So I've carved out an exception for the localgroup multiselect case. (When used as a single select, we still want it to set the value to `null`.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206501018414883) by [Unito](https://www.unito.io)
> fix clearing "Organizer of" profile field

- packages/lesswrong/server/datadog/tracer.ts
We got a high bill for custom metrics last month, which are billed per unique combination of tags. It looks like this was due to lots of distinct urls being counted, possibly the same but with different query strings (I can only see the count).
We only use custom metrics to count the cache hit rate, and I don't want to spend too much time looking into this, so I'm just reducing the sample rate for now which should hopefully help.
> Downsample datadog custom metrics

- packages/lesswrong/components/analytics/MyAnalyticsPage.tsx
- packages/lesswrong/components/users/UsersMenu.tsx
- packages/lesswrong/lib/collections/users/helpers.tsx
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/routes.ts
This will be useful for nudging people to use the page in comments/DMs etc
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206546611557954) by [Unito](https://www.unito.io)
> Add /my-stats url for going directly to your own stats page

- packages/lesswrong/components/posts/PostsItemMeta.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206531767374005) by [Unito](https://www.unito.io)
> Fix stray 0 in metadata line when an AF post has zero AF karma

- packages/lesswrong/server/vulcan-lib/apollo-ssr/pageCache.ts
I previously [reduced the sampling rate](https://github.com/ForumMagnum/ForumMagnum/pull/8724) of these events to save money. It's still relatively expensive to track them (will be >>$100/mo) and we don't really need them since they were mainly added to debug the db level page cache, which has been working for a while now, so I'm now disabling them completely
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206559950206558) by [Unito](https://www.unito.io)
> Disable custom metrics for cache hits

- packages/lesswrong/server/languageModels/autoTagCallbacks.ts
- scripts/fineTuneTagClassifiers.py
Updates autotagging to reflect API changes on OpenAI's end. In particular, the instructions no longer recommend their CLI tool (which doesn't work anymore), there's a Python script instead; and filter `<|endoftext|>` out of the training data, since that causes it to fail input validation.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206332167588435) by [Unito](https://www.unito.io)
> Update autotagging for OpenAI API changes

- packages/lesswrong/components/common/ContentItemBody.tsx
- packages/lesswrong/lib/hocUtils.tsx
This is a bit of cleanup I missed in https://github.com/ForumMagnum/ForumMagnum/pull/8704#discussion_r1476120430 , there was a comment in the ContentItemBody code about not using HoCs in components that might need to accept a ref. I didn't find any problems with doing this when testing the original PR, so I did add a `withTracking` HoC. Upon testing further, I have now found a console error that occurs as a result of this, and this will possibly break things like side comments that use a ref to the content of a post (EDIT: it appears side comments were not actually broken by the previous change).
In this PR I have made it so `hookToHoc` forwards a ref to the underlying component by default. At first I made this a separate function, but then I tried replacing the original and it appears it …
> Make all hookToHocs create a forward ref

- packages/lesswrong/components/editor/EditTitle.tsx
I was creating a new event and thought the placeholder text of "Post title" was confusing, so I updated it for events.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206567245247180) by [Unito](https://www.unito.io)
> Update event title placeholder text

- packages/lesswrong/components/quickTakes/QuickTakesSection.tsx
Clicking on the checkbox itself wasn't working to show/hide community posts, but clicking on the text did work. I would guess this was due to the tooltip, I've just moved the `onClick` up a level to cover both of these now
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206579760184880) by [Unito](https://www.unito.io)
> Make clicking on checkbox work for 'hide community' in quick takes section

- packages/lesswrong/components/ea-forum/TargetedJobAdSection.tsx
Based on mixed feedback, we're increasing this threshold
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206592895539782) by [Unito](https://www.unito.io)
> [EA Forum only] increase the read threshold for job ads

- packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
1. Job ads were missing an analytics context, so I added one
2. (Some) links in the job description weren't working because they were missing `InteractionWrapper`, so added those
3. Changed `<a>` tags to be `<Link>` to get the proper tracking
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206593257223106) by [Unito](https://www.unito.io)
> [EA Forum only] fix links in job ads, and add analytics context

- packages/lesswrong/components/ea-forum/digestAd/StickyDigestAd.tsx
I just noticed that the layout in the ad shifts when a logged in user subscribes, so I fixed it.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206593970809777) by [Unito](https://www.unito.io)
> [EA Forum only] small layout fix for sticky digest ad

- packages/lesswrong/lib/collections/tags/views.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206587517973553) by [Unito](https://www.unito.io)
> don't show deleted tags in the sunshine sidebar

- packages/lesswrong/themes/stylePiping.ts
https://github.com/ForumMagnum/ForumMagnum/pull/6322 caused the tables in https://www.lesswrong.com/tags/all to be too narrow:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206586512433147) by [Unito](https://www.unito.io)
> change width/etc to minWidth/etc for tables published from ckeditor to fix all tags display

- packages/lesswrong/components/comments/PopularComment.tsx
- packages/lesswrong/components/common/useClickableCell.tsx
Fixes a bug where clicking links in popular comments toggles the expansion of the comment rather than redirecting to the link.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206584319866139) by [Unito](https://www.unito.io)
> Make links in popular comments clickable

- packages/lesswrong/components/common/AnalyticsPageInitializer.tsx
- packages/lesswrong/lib/analyticsEvents.tsx
Sometimes we fire multiple analytics events right before, say, navigating to an external link. My understanding is that throttling causes only the first of those events to get saved, and the rest are lost. Hopefully this fixes that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206602976553623) by [Unito](https://www.unito.io)
> flush analytics events beforeunload

- packages/lesswrong/server/posts/annualReviewMarkets.ts
We're currently doing a whole bunch of useless-at-best lookups when we don't have a `manifoldReviewMarketId` on a post.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206617630005171) by [Unito](https://www.unito.io)
> skip looking up manifold cache entries when missing market id

- packages/lesswrong/lib/instanceSettings.ts
- packages/lesswrong/lib/vulcan-core/default_resolvers.ts
We limit the maximum offset (currently 2000) in the default multi resolver to prevent arbitrarily slow queries. This PR adds an instance setting to make this configurable so that we can allow larger offsets for the EA forum bot site where this doesn't matter as much.
I already updated the credentials repo to set the value to `null`, completely disabling the check. It might be better to set it to something like 100000 though.
> Add `maxAllowedApiSkip` instance setting

- packages/lesswrong/server.ts
- packages/lesswrong/server/analyticsViews.ts
These used to refresh automatically, but in the process of fixing a bug in them the other week this I broke this. This is apparently how they used to refresh, I'm not sure why it stopped working:
I've now added a cron job in the main code to refresh them. Possibly it would be more correct to add this to https://github.com/centre-for-effective-altruism/ForumAnalytics , but given that the code in there hasn't been touched for a long time I decided it wasn't worth the hassle of bringing it up to date
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206645219612302) by [Unito](https://www.unito.io)
> Add cron job to refresh analytics views

- packages/lesswrong/components/posts/LWPostsItem.tsx
On mobile, the post actions menu is currently to the left of various post icons (when they're present).  It should always just be next to the comment count icon, instead.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206618069911720) by [Unito](https://www.unito.io)
> move mobile post actions menu to be next to comment count

- packages/lesswrong/components/notifications/NotificationsPage/NotificationsPageKarmaChange.tsx
We'll check sentry in a week. An error was reported that karma changes weren't showing up, and this seemed like a potential culprit.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206698814981754) by [Unito](https://www.unito.io)
> [EA] Attempt to find the source of a bug by recording errors if karma changes are null

- packages/lesswrong/lib/collections/posts/views.ts
We use the filters to create a synthetic field to use for sorting called “score” which shadows the “score” field that exists in the database. When we recently implemented joins in the query builder we had to start qualifying the table name for fields in expressions, so `ORDER BY "score" DESC` became `ORDER BY "p"."score" DESC` which means we’re now sorting based on the actual field in the database instead of the synthetic field that it shadows. The simplest fix is to rename the synthetic field to avoid shadowing.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206709774495359) by [Unito](https://www.unito.io)
> Fix custom filtering from frontpage filter settings

- packages/lesswrong/components/icons/SettingsButton.tsx
- packages/lesswrong/components/posts/AllPostsPage.tsx
- packages/lesswrong/components/posts/TableOfContents/TableOfContentsRow.tsx
This makes it so that the full-height ToC shows the title when scrolled to the very top: 
Also fixes a small color bug with the settings button on the All Posts page
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206712423270567) by [Unito](https://www.unito.io)
> Show ToC when scrolled to the very top, and fix AllPostsPage SettingsButton

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
- packages/lesswrong/lib/collections/posts/schema.tsx
- packages/lesswrong/server/resolvers/reviewWinnerResolvers.ts
Follow up for #8717 which didn't get EA forum approval:
1. The main issue is the `flexDirection` in `PostsPagePostHeader` which breaks the post page pretty badly for posts with a lot of tags
2. Forum gate a load of LW only database calls on server startup and some resolver only fields in the posts schema
3. I also added an `isLWorAF` in `PostsPage` which maybe is strictly necessary but it's good for peace of mind
I also saw a bug where the table of contents would render too high and then get hidden by the page header if you scrolled down and then back up again, but I couldn't repro it when I looked again later. Possibly it only affects some posts, or maybe I just got the page in a bad state somehow, but we should keep an eye out for it in the future.
┆Issue is synchronized with this …
> Review post page forum gates

- packages/lesswrong/components/ea-forum/onboarding/EAOnboardingThankYouStage.tsx
I was testing out the onboarding flow and I noticed that my new users weren't subscribed to the digest, even though I didn't touch the toggle.
My understanding of the bug is: we were setting `subscribedToDigest` to `true` when the onboarding flow was first rendered (because all steps get rendered immediately), and then setting it back to `false` after the user submitted the first step, so if the user didn't touch the toggle in the last step then they wouldn't actually get subscribed to the digest in the end.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206700289058635) by [Unito](https://www.unito.io)
> [EA Forum only] fix onboarding digest subscription

- packages/lesswrong/components/sequences/SequencesTooltip.tsx
Introduced in: https://github.com/ForumMagnum/ForumMagnum/commit/b7d9c94de1989945d5b6308865617b5a8e98f1bb
Caused by a footgun in `LWTooltip`/`HoverOver`, where the `inlineBlock` attribute has arguably the wrong default value.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206721294852129) by [Unito](https://www.unito.io)
> Fix line-wrapping of links to sequences with hover-previews

- packages/lesswrong/themes/stylePiping.ts
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206719555766372) by [Unito](https://www.unito.io)
> [EA] Reduce size of footnotes in tables

- packages/lesswrong/lib/scoring.ts
In the HackerNews algorithm that we use for sorting LatestPosts, there's a parameter to add an offset to the age of posts. Having a positive value for this parameter means posts are always treated as older, and therefore very low karma posts won't appear on the frontpage (whereas they will briefly if there was no offset). 
We actually had a value of 2 hours, but LatestPosts actually seems better with a value of 6 given some quick testing.
This will also affect the karma posts get, further changing their visibility, so we should keep an eye on that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206732163779853) by [Unito](https://www.unito.io)
> change age offset of HN sort algorithm for LessWrong on frontpage

- packages/lesswrong/components/sunshineDashboard/SunshineGoogleServiceAccount.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206736881181969) by [Unito](https://www.unito.io)
> Make sidebar warning for google doc import only show for admins (not mods)

- .ebextensions/99datadog.config
This enables us to set the `DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED` environment variable to turn on [live processes monitoring](https://docs.datadoghq.com/infrastructure/process/?tab=docker) in datadog. This gives you the CPU and memory usage for every process running on the servers:
I found this very useful in debugging the issue described in [this PR](https://github.com/ForumMagnum/ForumMagnum/pull/8847). It costs $9/mo/instance though so I think we should have it turned off most of the time, and just turn it on when needed.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206738745400577) by [Unito](https://www.unito.io)
> Make datadog processes data collection configurable via a setting

- cypress/e2e/set_username.cy.js
- packages/lesswrong/components/ea-forum/onboarding/EAOnboardingStage.tsx
- packages/lesswrong/components/ea-forum/onboarding/EAOnboardingThankYouStage.tsx
This PR adds in the "Book a call with us" link that was in the old onboarding page.
This is branched off https://github.com/ForumMagnum/ForumMagnum/pull/8816 so that testing is easier. [Figma here](https://www.figma.com/file/IRUVQ5D2mKxoW0xZnhXIWv/2024-Q1?node-id=887%3A3181&mode=dev). I moved the "Go to the Forum" button into the footer so that the body can scroll, since it's taller now.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206709704343015) by [Unito](https://www.unito.io)
> [EA Forum only] add "book a call" link into new onboarding flow

- packages/lesswrong/components/questions/AnswersSorting.tsx
- packages/lesswrong/lib/collections/comments/views.ts
Currently sorting answers doesn't work at all. It seems like this was at least partly from the [giant "better stamp" PR](https://github.com/ForumMagnum/ForumMagnum/pull/7908), so doesn't have an explanation for the relevant changes made in there. This PR should fix it.
I think there is a more thorough version of a bug fix here but it's past 6 PM on Friday so I'm going to call it now. Maybe I'll look at this more next week.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206743075210627) by [Unito](https://www.unito.io)
> fix answers sorting functionality

- packages/lesswrong/components/tagging/FooterTag.tsx
https://github.com/ForumMagnum/ForumMagnum/commit/f1998c5a18caf05b4e6afe42e86a4fd5c4f3728c added top-margin to the `FooterTag` tooltip, creating a 6px gap between the button and its tooltip. This made it so you can't use the hover, since it will close when the cursor crosses the gap (unless you have a low-dpi mouse and cross the gap in a single frame).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206745318304678) by [Unito](https://www.unito.io)
> Fix tag-hover on LW

- packages/lesswrong/lib/sql/PgCollection.ts
Sometimes when making changes to to server startup or when server startup takes an unusually large amount of time for whatever reason you see an error message about calling `getIndex` on `undefined`. This happens when `ensureIndex` is called before Postgres tables are initialized. This PR adds a slightly more useful error message in this case.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206756461750242) by [Unito](https://www.unito.io)
> Warn when calling `ensureIndex` before initializing Postgres tables

- packages/lesswrong/components/posts/LWPostsItem.tsx
- packages/lesswrong/components/posts/usePostsList.ts
We already track each time a postItem is displayed. This PR adds the current score and baseScore of posts to the collected data in case that's helpful in making frontpage algorithm tweaks.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206760873835744) by [Unito](https://www.unito.io)
> add score and baseScore to postItemMount tracking

- packages/lesswrong/components/comments/CommentsTableOfContents.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPageSplashHeader.tsx
- packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx
- packages/lesswrong/components/posts/TableOfContents/MultiToCLayout.tsx
- packages/lesswrong/components/posts/TableOfContents/TableOfContentsRow.tsx
- packages/lesswrong/components/tagging/FooterTagList.tsx
Adds the date to the comment ToC for more consistency and to avoid having to shrink or grow it as much when the header comes down:  
Also fixes some spacing issues on very short posts where the ToC sticks out at the top: 
Also makes it so the post-ToC scrolls until the commentToC starts: 
Also some other smaller fixes
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206745368770974) by [Unito](https://www.unito.io)
> Various small styling adjustments for full-height ToC

- packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx
- packages/lesswrong/components/posts/TableOfContents/TableOfContentsRow.tsx
Recent changes me and Robert made causes the ToC to be slightly too tall when you are at the top of the post page, causing you to not see the bottom of it (and the number of comments)
This PR fixes that, in-exchange for the ToC being a bit short when you refresh while being scrolled down.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206761897051112) by [Unito](https://www.unito.io)
> Improve top of page ToC

- packages/lesswrong/components/common/LWHome.tsx
- packages/lesswrong/lib/betas.ts
- packages/lesswrong/lib/collections/posts/views.ts
- packages/lesswrong/lib/cookies/cookies.ts
- packages/lesswrong/server/useractivities/cron.ts
- packages/lesswrong/server/useractivities/getUserActivityData.ts
- packages/lesswrong/server/vulcan-lib/apollo-server/context.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
The EA forum build personalization of the HN parameters on frontpage but LW hadn't enabled this. We're enabling it now but with some changes to have it also active for logged-out users. Specifically, we'll show a slowed-down (slower drop-off) frontpage for any user who is visiting the frontpage for the first time. We have a new cookie that tracks visits to frontpage, we just look at whether that's set to determine first visit or not (can't used clientId cookie because it gets set on the first request).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206742386647781) by [Unito](https://www.unito.io)
> Set up a version of personalized latest posts sorting for LessWrong

- packages/lesswrong/themes/stylePiping.ts
Spacing on comment footnotes has been off since forever, this fixes that. 
Now: 
Before: 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206762330274709) by [Unito](https://www.unito.io)
> Fix comment footnotes

- .github/actions/uploadCkEditorBundle/lwAction.yaml
- .github/workflows/deployLWAFProd.yaml
- deployCkEditorBundle.js
- package.json
- packages/lesswrong/server/ckEditor/ckEditorApi.ts
We recently had some data loss caused by deploying without uploading an updated version of the ckEditor bundle.  This PR adds a github action which check if we need to upload the version which is specified in the codebase, and if so, attempts to upload it.  If this fails for any reason other than a 409 (conflict, because that version has already been uploaded), the action should fail and block the deployment.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206640359092494) by [Unito](https://www.unito.io)
> add github action to make uploading ckeditor bundle if needed a blocking step for deploys

- packages/lesswrong/components/sunshineDashboard/SunshineUserMessages.tsx
`NewConversationButton` was calling `embedConversation` with a `templateQueries` object created by `SunshineSendMessageWithDefaults`, while also depending on that same `templateQueries` object in the `useEffect` where that `embedConversation` was called.  _Something_ about this was (I suspect) causing `SunshineSendMessageWithDefaults` to rerender, meaning the `templateQueries` prop it was passing to `NewConversationButton` was referentially unstable, so calling `embedConversation` triggered an infinite loop.
This explanation doesn't seem quite right since `SunshineSendMessageWithDefaults` only depends on `user` and `embedConversation`, neither of which should have changed as a result of calling `embedConversation`.  Maybe embedding the conversation caused `SunshineUserMessages` itself to …
> fix infinite loop when creating a new message from a template in the admin dashboard

- packages/lesswrong/components/comments/SideCommentIcon.tsx
- packages/lesswrong/components/posts/PostsPage/CrosspostHeaderIcon.tsx
- packages/lesswrong/components/posts/PostsPage/PostBody.tsx
- packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx
- packages/lesswrong/components/posts/PostsPage/PostCoauthorRequest.tsx
- packages/lesswrong/components/posts/PostsPage/PostsAuthors.tsx
- packages/lesswrong/components/posts/PostsPage/PostsCoauthor.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPageCrosspostWrapper.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPagePostFooter.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPageTitle.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPageWrapper.tsx
- packages/lesswrong/components/posts/PostsPage/PostsRevisionMessage.tsx
- packages/lesswrong/components/recommendations/PostBottomRecommendations.tsx
- packages/lesswrong/lib/collections/comments/helpers.ts
- packages/lesswrong/lib/collections/posts/fragments.ts
- packages/lesswrong/lib/collections/tags/fragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
This branch makes `PostsPage` take two different versions of the post, `fullPost` and `postPreload`, with different fragments. The preload fragment is read from the Apollo cache by `PostsPageWrapper`, if present, but is not fetched. The practical upshot of this is that when you click on a post on the front page, part of the post (the title, text that was in the highlight, and most of the metadata) is visible immediately, without waiting for any response from the server.
In order to make this work, a lot of components that are used on the post page were modified to work with a `PostsListWithVotes` fragment rather than a `PostsWithNavigation` fragment. Some components of post pages, such as the table of contents, event RSVPs, and the Type3 audio player are not included in the preload, which …
> Post page can show a partial/preload state using cache entries from the front page

- packages/lesswrong/themes/globalStyles/globalStyles.ts
Small change slipped through; causes the font to change when a user focuses on e.g. a post title in the post editor.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206779290371381) by [Unito](https://www.unito.io)
> forum-gate font for global textarea:focus style

- packages/lesswrong/components/posts/PostsNewForm.tsx
https://github.com/ForumMagnum/ForumMagnum/pull/8582 removed `originalContents` from various editable fields fetched by `UsersCurrent`, and didn't realize that `EditorFormComponent` relied on `originalContents`.  So moderation guidelines stopped getting pre-populated for users by default.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206781604695620) by [Unito](https://www.unito.io)
> get user with fully hydrated moderation guidelines for prefilled props on a new post form

- packages/lesswrong/components/hooks/useImageUpload.tsx
We had an issue where a post's preview image was erroring, because the file was so large (8.5 MB) that Cloudinary wasn't able to transform it and returned a 400. I basically picked a random max file size (I tested out a 3.5 MB image, which was still giant, and Cloudinary handled it fine).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206791035060692) by [Unito](https://www.unito.io)
> add a max file size for image uploads

- packages/lesswrong/components/editor/CKPostEditor.tsx
- packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx
Noticed some errors in older safari versions on Sentry; turns out `.at` is an ES2022 api (which, [apparently unlike](https://github.com/ForumMagnum/ForumMagnum/pull/8683) `.findLast`, we can successfully use without bumping our tsconfig's `lib`?).  Switching back to using `.slice(-1)?.[0]` for fetching the last entry in an array in the two places where `.at` was used.
Unfortunately there doesn't seem to be e.g. a lint rule that'll warn on usage of ES-version-specific APIs, just syntax.  https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/no-unsupported-features/es-builtins.md is sort of that, but it doesn't have very good coverage.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206789826209823) by …
> don't use .at, it's an ES2022 api

- packages/lesswrong/lib/rateLimits/utils.ts
I have no idea how this happened.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206791401548147) by [Unito](https://www.unito.io)
> show active rate limits in mod dashboard

- packages/lesswrong/components/comments/CommentsNewForm.tsx
old:
new:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206791437052707) by [Unito](https://www.unito.io)
> remove asymmetric bottom padding for new comment buttons

- packages/lesswrong/lib/annualReviewMarkets.ts
- packages/lesswrong/lib/instanceSettings.ts
- packages/lesswrong/server/callbacks/votingCallbacks.ts
Moved the consts to instance settings and changed the probability threshold for highlighting posts to 25%.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206791319530799) by [Unito](https://www.unito.io)
> move review winner highlight threshold and minimum karma to settings,and change threshold default

- build.js
- package.json
- yarn.lock
Use native node source map functionality instead of the `source-map-support` library. This removes a CPU-bottleneck during server startup, and also considerably reduces memory usage.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206798881653550) by [Unito](https://www.unito.io)
> Native node source map support

- packages/lesswrong/lib/sql/Pipeline.ts
- packages/lesswrong/lib/vulcan-core/default_resolvers.ts
A follow-up to the [sqlFragments PR](https://github.com/ForumMagnum/ForumMagnum/pull/8718) had a bug in it which broke frontpage sorting, because it generated SQL which referenced the score field on posts by alias, rather than the "shadow" score field generated by the synthetic field selector.
The [fix](https://github.com/ForumMagnum/ForumMagnum/pull/8818) for that was to rename the synthetic field.  This caused `performQueryFromViewParameters` to begin to take the pipeline branch instead of the regular query branch, and the pipeline branch has had what looks like an extremely long-standing bug which ignores the offset if it's passed in via the query terms (since it references `parameters.options.skip`, while above we reassign `skip: terms.offset` to a new `options` object which we only …
> add skip logic to pipeline query compilation

- packages/lesswrong/components/common/ErrorAccessDenied.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPageWrapper.tsx
Currently, if a logged out user goes to a post page that is inaccessible (like a draft), then they will first get prompted to log in, and then after logging in the page will say that the post is inaccessible. This PR makes it so that logged out users don't get prompted to log in in this case, and only see the second message. Also I cleaned up the styling a bit.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206791495318768) by [Unito](https://www.unito.io)
> don't show the login prompt for an inaccessible post page

- packages/lesswrong/lib/collections/moderatorActions/schema.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/server/callbacks/moderatorActionCallbacks.ts
- packages/lesswrong/server/callbacks/votingCallbacks.ts
- packages/lesswrong/server/repos/VotesRepo.ts
https://github.com/ForumMagnum/ForumMagnum/pull/8635 but just flag those users for review with a moderator action rather than applying an automatic rate limit.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206826331160456) by [Unito](https://www.unito.io)
> flag users getting downvoted by senior users on net-negative comments

- packages/lesswrong/components/notifications/NotificationsPage/NotificationsPageNotification.tsx
The tooltip over the word "comment" is currently broken for notifications for new comments on a subscribed post.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206826043721506) by [Unito](https://www.unito.io)
> Fix comment id in tooltip for new comment notifications

- packages/lesswrong/components/forumEvents/ForumEventPostPageBanner.tsx
We currently have a live and nasty bug where some posts aren't shown as we have a derefence of `tagRelevance` without checking if it's null. Typescript doesn't catch this because `tagRelevance` is typed as `any` - probably we should add a way for blackbox types to define an explicit Typescript type (which should be `Record<string, number> | null` in this case).
> Fix null `tagRelevance` dereference in post page forum event banner

- packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx
- packages/lesswrong/components/posts/TableOfContents/TableOfContentsRow.tsx
ToCs that are larger than one viewport end up being messed up by `height: 100%`, while ToCs that are shorter need it in order to not collapse to the minimum necessary for the section headers.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206825483121036) by [Unito](https://www.unito.io)
> Manage long tocs

- packages/lesswrong/server/robots.ts
In order to reduce damage from Amazon bot without entirely blocking (LLMs should know about Alignment), blocking just user reply pages.
Also adding it changes to robots.txt that were made with database override, but as per comment in the code:
```// robotsTxt: Optional setting to entirely replace the contents of robots.txt,
// to allow quickly banning a bad crawler or a slow endpoint without a redeploy,
// if quick response is needed. If null (the default), robots.txt is generated
// from other settings and the function below instead.
//
// (If you use this setting, remember to convert the robots.txt update into a
// PR to this file, **and then set the setting back to null when it's merged,
// since the setting will override any future robots.txt updates**.)```
Emphasis added.
┆Issue is …
> Update robots.txt: No crawling /users/*/replies and also update from settings

- packages/lesswrong/lib/vulcan-lib/utils.ts
- packages/lesswrong/server/editor/conversionUtils.ts
Adding handling for internal links when importing Google docs broke the existing handling of footnotes. It didn't break in a way that is too critical, the links still work and the footnotes are readable, they just aren't in a separate box. This PR fixes that by making sure we handle footnotes before internal links
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206844821687466) by [Unito](https://www.unito.io)
> Fix footnotes in google doc import (handle them before internal links)

- packages/lesswrong/server/editor/conversionUtils.ts
This fixes double spacing by not allowing empty `<p>` tags in the top level of the document at all. People may actually want this sometimes, but I think this is a good simple rule to start with, which we can then change if we get any complaints
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206845019329483) by [Unito](https://www.unito.io)
> fix double spacing in imported google docs

- packages/lesswrong/server/editor/conversionUtils.ts
Docstring sums up the logic here:
```
/**
* In google docs nested bullets are handled through styling (each indentation level is actually
* a separate list, with a margin-left creating the effect of nesting). In ckeditor, nested bullets are
* actually <ul>s nested within each other. Convert this styling based nesting to genuine nesting
*/
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206845559949799) by [Unito](https://www.unito.io)
> Support nested bullets in imported google docs

- packages/lesswrong/components/comments/CommentsTableOfContents.tsx
Potential styling change of the comments table of contents in the side-bar, right-aligning the karma count. I think it makes it look less cluttered and makes it easier to visually scan.
| Current | Proposed |
| -------- | ------- |
| <img width="239" alt="image" src="https://github.com/ForumMagnum/ForumMagnum/assets/3543224/155c4471-fa21-4763-b80a-737a2799ecff"> | <img width="252" alt="image" src="https://github.com/ForumMagnum/ForumMagnum/assets/3543224/eebd0e26-4256-478a-bcbc-4d73cc30625d"> |
Note I'm not actually running a local version of the forum, I just tried out the styles in my browser:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206800170428896) by [Unito](https://www.unito.io)
> Right-align karma in CommentsTableOfContents

- packages/lesswrong/components/posts/TableOfContents/MultiToCLayout.tsx
IMO the centering is off for the new ToC layout. This centers it. 
Before: 
After: 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206847399948172) by [Unito](https://www.unito.io)
> Center full-height ToC page

- packages/lesswrong/components/ea-forum/TargetedJobAdSection.tsx
- packages/lesswrong/lib/collections/userJobAds/collection.ts
- packages/lesswrong/server/migrations/20240314T123630.dedup_UserJobAds.ts
There is some issue that is resulting in duplicate records in the `UserJobAds` table. There should only be a single record per user+job pair. Though we haven't gotten to the root issue, this should fix it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206844129699403) by [Unito](https://www.unito.io)
> Add a unique index on UserJobAds (underlying problem may still be there)

- packages/lesswrong/components/common/TabNavigationMenu/NavigationStandalone.tsx
- packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx
Per request via [slack](https://cea-core.slack.com/archives/C038J512SD8/p1710516623267249). This also fixes a tiny bug where the RHS toggle moves up and down when you open and close the RHS.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206853836717284) by [Unito](https://www.unito.io)
> [FriendlyUI] adjust the positioning of the home page center column

- packages/lesswrong/components/posts/PostsSingle.tsx
Some posts we imported from the AIAF has _id length 24. 17 and 24 are the only two ID lengths in the DB, so this should handle all cases. Probably will still want to remove this whole thing in a few weeks.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206882449789290) by [Unito](https://www.unito.io)
> Add additional special case for slug-based post redirect

- packages/lesswrong/components/ea-forum/digestAd/StickyDigestAd.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/lib/abTests.ts
The [previous version of the post page digest ad](https://github.com/ForumMagnum/ForumMagnum/pull/8740) got us [a few new subscribers per day](https://app.hex.tech/9e4abdcd-b18c-49ca-acfc-3ec5249ddb1a/app/b7b415b6-758a-4747-a851-0e1f565614ac/latest), but most people who saw it dismissed or ignored it. Based on the A/B test, users who saw the ad did not bounce at a higher rate, so it seems worth keeping.
For now, we are going to try only showing the ad after the user has viewed a few posts, so that we're more likely to show it to receptive users. I've also closed the A/B test, so now we are showing it on all clients.
And previously we did not show the ad on very small screens, but now that you need to read multiple posts before seeing the ad, I've enabled it on all screen sizes:
┆Issue is …
> [EA Forum only] only show post page digest ad after a few reads

- packages/lesswrong/server/inactiveUserSurveyCron.tsx
- packages/lesswrong/server/repos/UsersRepo.ts
The inactive user survey email seems to be running fine, but we haven't gotten many responses. So I'm decreasing the threshold to be considered "inactive" to 4 months, and sending it to a larger number of inactive users per day.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206925682300160) by [Unito](https://www.unito.io)
> [EA Forum only] decrease the inactive user threshold

- packages/lesswrong/components/events/modules/VirtualProgramCard.tsx
Once again I noticed that the VP card dates were off, so I updated them. Also fixed a small bug in the logic.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206934282572320) by [Unito](https://www.unito.io)
> [EA Forum only] another VP date update

- packages/lesswrong/components/dropdowns/comments/DeleteCommentDropdownItem.tsx
- packages/lesswrong/lib/collections/comments/fragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/server/callbacks/commentCallbacks.ts
Rewrites the server-side validation callback for comment-deletion, so that it now handles undeletion sensibly. Also fix the error handling, so that if the server sends you an access-denied error message you can see it.
(Note that much of the logic that determines whether deletion is allowed does not live here, it lives in the `moderateComment` mutator, which is in another file and isn't changed. That's why there's conspicuously no call to `userCanModerateComment` in either the old or the new version.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206928579919846) by [Unito](https://www.unito.io)
> Comments can only be undeleted by mods or the user who deleted them

- packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
Not sure why these two were wrong, maybe they were updated since I deployed them 🤷‍♀️
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206934935357214) by [Unito](https://www.unito.io)
> [EA Forum only] update some job deadlines

- packages/lesswrong/components/hooks/useRecordPostView.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/components/posts/usePostsItem.tsx
- packages/lesswrong/components/recentDiscussion/useRecentDiscussionThread.ts
- packages/lesswrong/components/review/ReviewVoteTableRow.tsx
- packages/lesswrong/server/callbacks/commentCallbacks.ts
- packages/lesswrong/server/mutationCallbacks.ts
- packages/lesswrong/server/recombee/client.ts
- packages/lesswrong/server/vulcan-lib/mutators.ts
This PR makes a few improvements to our Recombee implementation
- recording `detailView`, e.g. post-view now happens in useRecordView so it happens not just on visiting a post, but also expanding comments on the post item, etc
- We now sync `lastCommentedAt` field of posts to Recombee so it can be factored into the algorithm
- Recombee is still not filtering out read posts for us, so we're oversampling. To ensure we always have enough recommendations without ridiculously oversampling, now padding the list of returned recommendations with read posts if we don't have enough unread
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206954140264471) by [Unito](https://www.unito.io)
> Recombee improvement: record more post views, include lastCommentedAt, pad list with already read

- packages/lesswrong/components/common/TabNavigationMenu/NavigationStandalone.tsx
Currently the left sidebar on the core topic page is hidden behind the banner - this fixes that
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206956245206200) by [Unito](https://www.unito.io)
> [EA Forum only] fix core topic page sidebar

- packages/lesswrong/components/sequences/SequencesGridItem.tsx
- packages/lesswrong/components/sequences/SequencesPage.tsx
- packages/lesswrong/components/sequences/SequencesSummary.tsx
- packages/lesswrong/lib/collections/sequences/views.ts
This PR makes a couple sequence-related changes. I've gated them such that LW/AF are unaffected by these changes.
First, I made it so that the sequence grid image falls back to the banner image. This seemed to work fine in most cases, so seemed better than just directly falling back to the site-specific default image.
Before:
After:
Second, I've updated the query on the `/library` page so that sequences without a grid image set are no longer filtered out. I think showing the sequences with the fall back options (either the sequence banner image or the galaxy image) is better than secretly not showing them at all.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206955825869128) by [Unito](https://www.unito.io)
> sequence grid image falls back to banner image

- packages/lesswrong/components/common/HomeLatestPosts.tsx
So that it's no longer black on EAF
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206958932512781) by [Unito](https://www.unito.io)
> forum-gate SettingsButton color

- packages/lesswrong/components/users/UsersAccountMenu.tsx
This change was in a separate PR from the black PR changes, which is why my last PR to remove the black bar didn't catch it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206962332260385) by [Unito](https://www.unito.io)
> revert changes to login button

- packages/lesswrong/server/recombee/client.ts
Recombee enabled on their end what we need to prevent read posts being recommended for a user, so can remove the algorithm subverting oversampling. Single character change
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206973399091710) by [Unito](https://www.unito.io)
> Remove recombee oversampling

- packages/lesswrong/server/vulcan-lib/apollo-server/initGraphQL.ts
This PR adds automatic permissions checks using `accessFilterSingle` and `accessFilterMultiple` for DB objects returned by SQL resolvers. There are currently no fields that this affects, but this is required before we can merge #8769, otherwise that PR would introduce a vulnerability where the contents of deleted posts could be read by viewing the relevant side comments cache.
In the future we can (and probably should) expand this to include results of code resolvers as well, which should be a trivial addition. This would remove the need to use these filters manually in resolvers, which is often forgotten anyway.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206826435114499) by [Unito](https://www.unito.io)
> Add automatic permissions checks for SQL resolvers

- packages/lesswrong/components/posts/TableOfContents/TableOfContentsRow.tsx
I noticed this appearing when I navigated away from a post page, so I fixed it
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206976348620088) by [Unito](https://www.unito.io)
> fix ToC console error

- packages/lesswrong/components/votes/lwReactions/InlineReactSelectionWrapper.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206952431788580) by [Unito](https://www.unito.io)
> Fix a bug where the comment-on-select box would be covered by an invisible unclickable box when highlighting text near the bottom of a question

- packages/lesswrong/lib/collections/users/schema.ts
This PR changes the default setting for "new post by user" notifications, so that it notifies you both on-site and via email. I left it as on-site only for LW since they seemed to prefer that. [See discussion in slack](https://cea-core.slack.com/archives/CJY3ZKP62/p1712175682781679).
I think getting notified via email is what a user would expect, and it is particularly important for the EA Forum because we have a step in our onboarding flow that prompts users to subscribe to a select list of authors.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207005076465534) by [Unito](https://www.unito.io)
> non-LW sites default to sending an email for "new post by user" notifications

- .eslintrc.js
- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/comments/DebateBody.tsx
- packages/lesswrong/components/common/ForumNoSSR.tsx
- packages/lesswrong/components/ea-forum/EAHome.tsx
- packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx
- packages/lesswrong/components/ea-forum/EASurveyBanner.tsx
- packages/lesswrong/components/ea-forum/wrapped/EAForumWrappedPage.tsx
- packages/lesswrong/components/editor/DraftJSEditor.tsx
- packages/lesswrong/components/editor/PostCollaborationEditor.tsx
- packages/lesswrong/components/form-components/TagFlagToggleList.tsx
- packages/lesswrong/components/moderationTemplates/ModerationTemplateItem.tsx
- packages/lesswrong/components/posts/PostsEditForm.tsx
- packages/lesswrong/components/posts/PostsNewForm.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/components/quickTakes/QuickTakesListItem.tsx
- packages/lesswrong/components/recommendations/PostsPageRecommendationsList.tsx
- packages/lesswrong/components/review/ReviewVotingCanvas.tsx
- packages/lesswrong/components/sequences/SequencesGridItem.tsx
- packages/lesswrong/components/sequences/SequencesPage.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineNewUsersProfileInfo.tsx
- packages/lesswrong/components/users/DialogueMatchingPage.tsx
- packages/lesswrong/lib/betas.ts
- packages/lesswrong/lib/utils/componentsWithChildren.tsx
In this PR:
- Replaced all `NoSSR` with `ForumNoSSR` which allows conditional no-ssr-ing
- Wrapped the popular comments and recent discussion sections in `ForumNoSSR`, conditional on:
- The user being logged in (so the cached version still gets the SSR-ed sections)
- Settings for each section
I'm going to start with both settings turned on and see what the effect is on the number of queries and actual timing (plus see if I personally find it annoying that these sections don't show up immediately). Both tend to be among the slowest queries on the page so I am expecting them both to individually make a difference
> [EA] NoSSR recent discussion and popular comments

- packages/lesswrong/lib/collections/sideCommentCaches/collection.ts
We just deployed the new side comment cahes table. The collection has permission gates so there shouldn't be security issues, but this PR removes the default resolvers and mutations just to be safe (they're not needed as all accesses are done internally with direct SQL queries).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207035632365878) by [Unito](https://www.unito.io)
> Remove default resolvers and mutations for `SideCommentCaches` collection

- packages/lesswrong/components/sequences/SequencesPage.tsx
A quick PR to make the deleted sequence page look reasonable. The link goes to `/library`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207039562307456) by [Unito](https://www.unito.io)
> quick cleanup of deleted sequence page

- packages/lesswrong/components/hooks/useScrollHighlight.ts
On some posts, SSRing a post page gave me a crash:
```
ReferenceError: window is not defined
at getCurrentSectionMark (/Users/jbabcock/repositories/Lesserwrong/LessWrong2/packages/lesswrong/components/hooks/useScrollHighlight.ts:72:3)
at /Users/jbabcock/repositories/Lesserwrong/LessWrong2/packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx:214:17
at Array.map (<anonymous>)
at FixedPositionToc (/Users/jbabcock/repositories/Lesserwrong/LessWrong2/packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx:210:25)
at processChild (/Users/jbabcock/repositories/Lesserwrong/LessWrong2/node_modules/react-dom/cjs/
react-dom-server.node.development.js:3043:14)
at resolve (/Users/jbabcock/repositories/Lesserwrong/LessWrong2/node_modules/react-dom/cjs/react-dom-serve …
```
> Fix crash rendering ToC in SSR

- build.js
This option was added to our build script a long time ago to work around a problem with Algolia, which apparently had tree-shaking annotations in it that were incorrect. However, we are mostly not relying on Algolia anymore. Removing this annotation reduces the (minified, uncompressed) client bundle size by about 2%. We retested the client-side search UI and confirmed that it still works with this change.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207013246307760) by [Unito](https://www.unito.io)
> Remove treeShaking: "ignore-annotations" from build.js

- packages/lesswrong/components/themes/useTheme.tsx
- packages/lesswrong/server/styleGeneration.tsx
- packages/lesswrong/server/vulcan-lib/apollo-ssr/pageCache.ts
I noticed that an extra 2 requests for allStyles were being made after a page had loaded, which differed only in the ordering of the theme options in the url. Using json-stringify-deterministic makes the second pair of requests go away.
> Use json-stringify-deterministic in allStyles url

- package.json
- yarn.lock
Postgres-array is a dependency of pg-types which is a depndency of pg. It's responsible for parsing jsonb fields in the results of queries we run in postgres. This version upgrade causes us to get the changes in https://github.com/bendrucker/postgres-array/pull/16 , which makes that particular function ~2-3x faster. I observed that this function was ~2% of our server CPU time (on a benchmark where I was SSRing a post page with lots of comments in a loop), and after this upgrade I saw the time spent in it reduce accordingly.
The version is a major version only because they dropped compatibility with some old nodejs versions.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207051997219750) by [Unito](https://www.unito.io)
> Upgrade version of postgres-array

- packages/lesswrong/components/ea-forum/digestAd/StickyDigestAd.tsx
- packages/lesswrong/lib/collections/users/fragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
`experiencedIn` and `interestedIn` were used in the old job ads - now they are no longer used so I'll drop the fields
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207059617139817) by [Unito](https://www.unito.io)
> remove a couple old fields from UsersCurrent

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
This was causing text to overflow on mobile. Reverting for now while I find another way to fix it
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207067754036086) by [Unito](https://www.unito.io)
> Revert post width layout shift fix

- packages/lesswrong/lib/collections/users/fragments.ts
This adds the UsersCurrent fragment to the UsersEdit fragment (replacing UsersProfile – UsersCurrent is a superset of that).
This a) fixes an immediate bug where the "hide sunshine sidebar" admin setting can't be updated once you set it, and b)  hopefully prevents a class of errors where people add fields to UsersCurrent but forget to update them in UsersEdit
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206760138604346) by [Unito](https://www.unito.io)
> Add UsersCurrent to UsersEdit

- packages/lesswrong/components/comments/CommentsNewForm.tsx
- packages/lesswrong/components/forumEvents/ForumEventPostPageBanner.tsx
- packages/lesswrong/components/hooks/usePaginatedResolver.ts
- packages/lesswrong/components/hooks/useRecentOpportunities.ts
- packages/lesswrong/components/recommendations/PostBottomRecommendations.tsx
- packages/lesswrong/components/recommendations/RecommendationsList.tsx
- packages/lesswrong/components/recommendations/withRecommendations.ts
- packages/lesswrong/lib/crud/withMulti.ts
- packages/lesswrong/lib/crud/withSingle.ts
- packages/lesswrong/lib/helpers.ts
- packages/lesswrong/lib/postSideRecommendations.tsx
- packages/lesswrong/server/emailComponents/EmailFooterRecommendations.tsx
In this PR:
1. NoSSR recommendations section
2. NoSSR a comment rate limit query
3. Make it so ForumEventPostPageBanner only checks the post if there is an active event
The first two ran after the main queries to fetch the post and comments (which themselves run in parallel), so removing them removes a bottleneck. The last one ran in parallel so may not make a huge difference, but it will still help with CPU usage etc.
Testing on [this post](https://forum.effectivealtruism.org/posts/JWz7JjuoRKrsWTsrZ/summary-mistakes-in-the-moral-mathematics-of-existential), this reduced the number of db queries required to load the page from 62 to 30 (logged in as my user, with admin powers off)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207057247194303) by …
> Posts page SSR optimisations

- packages/lesswrong/server/languageModels/autoTagCallbacks.ts
The performance impact of this one isn't super high, but the pattern is interesting to watch out for.
The first time `getTagBotUserId` is called, it fetches a user by slug and returns its ID; on subsequent calls, it reuses the result of that fetch and returns the same ID. In the course of doing this, it creates a promise and stores it in a global variable (so subsequent calls can wait for the first call to finish, rather than starting their own DB fetches).
After everything is settled, that promise was retained in a global variable. It turns out, retaining the promise (even in a resolved state) retains everything captured by the promise's execution context, which means that the first call to this function takes its arguments (a ResolverContext) and leaks them. (When I found it in a heap …
> Fix `getTagBotUserId` retaining and leaking a ResolverContext

- packages/lesswrong/components/bookmarks/BookmarksList.tsx
- packages/lesswrong/components/common/LoadMore.tsx
- packages/lesswrong/components/common/queryStatusUtils.ts
- packages/lesswrong/components/posts/FriendlyPlaceholderPostsItem.tsx
- packages/lesswrong/components/posts/PostsLoading.tsx
- packages/lesswrong/lib/components.ts
- packages/lesswrong/themes/defaultPalette.ts
- packages/lesswrong/themes/themeType.ts
- packages/lesswrong/themes/userThemes/darkMode.ts
This PR adds a ghost loading state for the post list item. Right now it's only used in `BookmarksList` but we'll add it to more places in subsequent PRs. A bunch of this is borrowed from the `service-worker-prototype` branch, so hopefully the merge is not too bad.
Desktop, light mode:
https://github.com/ForumMagnum/ForumMagnum/assets/9057804/c9c4a5d6-f424-4196-a653-9dec943c55b7
Mobile, dark mode:
https://github.com/ForumMagnum/ForumMagnum/assets/9057804/d068c515-dbcb-4f2a-b4d1-92d97365b113
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207050154489980) by [Unito](https://www.unito.io)
> [FriendlyUI only] add posts item ghost loading state

- packages/lesswrong/components/comments/CommentsItem/CommentsItemDate.tsx
We've had some badly behaved bots/scrapers recently that hit `?commentId=` permalinks.  This change causes those to be NoSSR'd (forum-gated) while still SSRing the contents of the link that the user might see on initial page load (and the DOM rewrite should be basically instant since it's just replacing it with a link with the same contents, so no network requests).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207083109116559) by [Unito](https://www.unito.io)
> no ssr comment permalinks to mitigate bad scrapers

- packages/lesswrong/components/common/FormatDate.tsx
- packages/lesswrong/lib/collections/posts/schema.tsx
- packages/lesswrong/lib/collections/users/helpers.tsx
- packages/lesswrong/lib/utils/timeFormat.ts
- packages/lesswrong/unitTests/timeframeUtils.tests.ts
This introduces a replacement for momentjs's .from() (which is also used under the name .fromNow()), which was _remarkably_ slow for what it is. Also replaces some moment-based date calculations with `Date` instead.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207052695289780) by [Unito](https://www.unito.io)
> Avoid using slow momentjs functions

- package.json
- packages/lesswrong/lib/domParser.ts
- packages/lesswrong/unitTests/tableOfContents.tests.ts
- yarn.lock
In extractTableOfContents, we parse a post and find headings in it. Previously, this was done with cheerio. Recently it was modified to JSDOM so that the same code could run on the client (though in practice it's usually done server side). Unfortunately this was slower, especially on large posts; on an 11k-word real post, it was adding ~80ms of CPU time to per SSR (on my M1 Max).
There's a competing library linkedom which is a lot faster, with a similar API. Switch libraries, and smooth over a few small API differences.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207052305117059) by [Unito](https://www.unito.io)
> Use linkedom instead of JSDOM for ToC

- packages/lesswrong/components/comments/CommentFrame.tsx
- packages/lesswrong/components/comments/CommentsItem/CommentBody.tsx
- packages/lesswrong/components/comments/CommentsItem/CommentBottom.tsx
- packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
- packages/lesswrong/components/comments/CommentsItem/CommentsItemDate.tsx
- packages/lesswrong/components/comments/CommentsItem/CommentsItemMeta.tsx
- packages/lesswrong/components/comments/SingleLineComment.tsx
- packages/lesswrong/components/common/ContentItemTruncated.tsx
- packages/lesswrong/components/common/ContentStyles.tsx
- packages/lesswrong/components/common/LWTooltip.tsx
- packages/lesswrong/components/common/MetaInfo.tsx
- packages/lesswrong/components/common/Typography.tsx
- packages/lesswrong/components/users/UsersNameDisplay.tsx
- packages/lesswrong/components/votes/VoteArrowIcon.tsx
Slack thread: https://lworg.slack.com/archives/C75BWSNBH/p1713246308322869
This looks like an arbitrary choice of convention, but it turns out to have a performance impact. Switch usages of classNames from object-style to boolean-expression-style, saving a bunch of object allocations and hashmap operations.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207086122363931) by [Unito](https://www.unito.io)
> Switch classNames from object-style to boolean-expr-style in high-usage-frequency components

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/lib/collections/posts/helpers.ts
- packages/lesswrong/lib/routes.ts
- packages/lesswrong/lib/vulcan-lib/routes.ts
- packages/lesswrong/server/apolloServer.ts
- packages/lesswrong/server/repos/PostsRepo.ts
On the frontpage we already send the `<head>` tag with the urls for bundle.js and allStyles ahead of the main SSR body, so that these can be downloaded and parsed while the page is rendering on the server. We weren't doing this for the posts page, because sending these ahead means you have to lock in the status code you are going to send (to 200), which for posts we don't know for sure until the page is rendered (it may be a 404 or 301).
This PR adds the option to run a function in parallel to the main SSR to check what the status code will be, and then send the prefetch section if we are sure it will be a 200.
It's not 100% clear that the performance impact of this will be positive, there are these competing considerations:
- For non-cached loads of the posts page, there is generally at …
> Prefetch resources on most post pages

- packages/lesswrong/components/common/HomeLatestPosts.tsx
- packages/lesswrong/components/common/HomeTagBar.tsx
- packages/lesswrong/components/posts/AllPostsList.tsx
- packages/lesswrong/components/posts/PostsList2.tsx
- packages/lesswrong/components/posts/PostsPage/ContentType.tsx
- packages/lesswrong/components/posts/PostsTimeBlock.tsx
- packages/lesswrong/components/posts/usePostsList.ts
- packages/lesswrong/components/shortform/ShortformTimeBlock.tsx
- packages/lesswrong/components/tagging/TagEditsTimeBlock.tsx
This PR adds the [post item ghost loading state](https://github.com/ForumMagnum/ForumMagnum/pull/9091) to more places, primarily the "All posts" page and home page. It also adds a ghost loading state for the home page topic tabs.
https://github.com/ForumMagnum/ForumMagnum/assets/9057804/05e50323-40d3-4ab3-a91d-2db481f2a8ad
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207090516071320) by [Unito](https://www.unito.io)
> [FriendlyUI only] post item ghost loading state in more places

- packages/lesswrong/lib/collections/users/schema.ts
Currently, when an admin tries to edit a user other than themselves they get an error when they submit. This is because they don't have permission to read `hideSunshineSidebar`, so they inadvertantly try to assign a value of `null` to a field with a default value which is not allowed.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207118449498176) by [Unito](https://www.unito.io)
> Allow admins to read value of `hideSunshineSidebar`

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/common/GlobalHotkeys.tsx
- packages/lesswrong/lib/betas.ts
- packages/lesswrong/lib/components.ts
As the title says.  (Current not forum-gated, but happy to do that if the EA forum desires.)
Neither alt + shift + d nor alt + shift + s correspond to any shortcuts in Chrome, Firefox, and Safari, as far as we can tell.  This does make it impossible to type the two characters generated by those shortcuts, but they're weird unicode glyphs that people aren't going to be using anyways.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207095078173549) by [Unito](https://www.unito.io)
> implement global hotkeys for theme switching and toggling the sunshine sidebar visibility

- packages/lesswrong/lib/tableOfContents.ts
If the first usage of LaTeX inside a post falls inside of a section heading, the heading has the MathJax stylesheet embedded in it. Eg: https://www.lesswrong.com/s/Gmc7vtnpyKZRHWdt5/p/tCex9F9YptGMpk2sT . This was introduced in https://github.com/ForumMagnum/ForumMagnum/pull/8971 ; this rewrote ToC extraction code and in the process accidentally dropped the functionality of `elementToToCText` which would strip that out. Add the functionality back in (with JSDOM APIs). Also, as a general safeguard against misdetected ToC headings, limit them to 300 chars so that one bad heading can't fill up the entire ToC column.
(This is orthogonal to https://github.com/ForumMagnum/ForumMagnum/pull/9100 ; I have tested that the fix works both with and without 9100 merged in.)
┆Issue is synchronized with …
> Fix the ToC on posts with LaTeX in the first heading block

- packages/lesswrong/components/ea-forum/EAHome.tsx
I was planning to experiment with changing these to see the effect on Frontpage load speed, subject to it sometimes being annoying that they didn't load immediately. As it happens, I have never noticed it them not loading immediately, so I've decided it to keep them as is without doing any experiments
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207152083686618) by [Unito](https://www.unito.io)
> Remove nossr settings for frontpage sections

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
Improved version of the change that was reverted [here](https://github.com/ForumMagnum/ForumMagnum/pull/9109), which caused the post body to overflow on mobile.
The layout shift this is fixing is that on medium sized screens (where the toc and post body are competing for space), the post width increases once recommendations load. This makes it so it is always at full width
> Fix post width layout shift

- packages/lesswrong/components/common/LWHomePosts.tsx
- packages/lesswrong/components/recommendations/ContinueReadingList.tsx
- packages/lesswrong/components/recommendations/withContinueReading.ts
- packages/lesswrong/lib/publicSettings.ts
- packages/lesswrong/server/apolloServer.ts
- packages/lesswrong/server/recombee/client.ts
Under the current state of things, we have a frontpage tab that shows max of 3 posts. Not quite enough. This PR enables us to show 6, and allows us to vary them.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207155627262453) by [Unito](https://www.unito.io)
> Continue Reading accepts limit and shuffle params + recommendationsTab stickied posts

- packages/lesswrong/components/posts/RecombeePostsList.tsx
- packages/lesswrong/server/recombee/client.ts
- packages/lesswrong/server/resolvers/postResolvers.ts
Currently, we don't track which post comes from which scenario in the recombee hybrid scenario. This PR passes through info to let us do that
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207165353375749) by [Unito](https://www.unito.io)
> Recombee Hybrid: tracking each half

- cypress/e2e/posts/organizers_can_edit_posts.cy.js
- cypress/e2e/voting/vote_on_post.cy.js
The organizers_can_edit_posts test just got ([example](https://github.com/ForumMagnum/ForumMagnum/actions/runs/8828927122/job/24238869413?pr=9174)) the bug introduced [here](https://github.com/ForumMagnum/ForumMagnum/pull/9127#issuecomment-2064129535) which caused the first letter typed into the title to be ignored. I have added a short wait to that and one other test to fix it
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207169613638606) by [Unito](https://www.unito.io)
> Fix flaky cypress tests

- packages/lesswrong/components/common/LWHomePosts.tsx
- packages/lesswrong/lib/collections/users/recommendationSettings.ts
- packages/lesswrong/lib/instanceSettings.ts
- packages/lesswrong/server/recombee/client.ts
Production has live a recombee recommendation list that's 50-50 emulate hacker news algo + recombee:personal logic.
This PR adds a second tab for comparison that's 50-50 emulate hacker news + custom-for-lw-recombee-logic that they made for us (has some tweakable parameters too in Recombee admin config on their site)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207174902910582) by [Unito](https://www.unito.io)
> [LW] Second Recombee Hybrid Tab for Admins

- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
- packages/lesswrong/lib/betas.ts
Backfilling the `profileUpdatedAt` field is slower than expected so this commit hides all links to the people directory so we can deploy the code without advertising the new feature whilst running the migrations, then revert this commit after to release the feature.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207176193927785) by [Unito](https://www.unito.io)
> Temporarily hide links to the people directory

- packages/lesswrong/server/apolloServer.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
Introduced in: https://github.com/ForumMagnum/ForumMagnum/pull/9134
We inject a script tag into the page that sets `tabId` on `window` to a value that identifies the pageload, for analytics. That injected script tag needs to run before the client bundle does, or it will look for the tabId on initialization and it won't be there. The previous PR changed the client-bundle import from `defer` to `async`, which changed the execution order, and we started getting analytics events with `tabId` missing.
A similar workaround to this was already applied for `publicSettings`, but `tabId` was missed.
Tested by: Putting a `console.log` in `client/logging.ts` that reports `tabId`, observing that it was `undefined`, making the changes in this PR and rerunning the test, and getting a valued `tabId` at …
> Fix tabId being lost due to initialization-order issue with the client bundle

- packages/lesswrong/server/editor/make_editable_callbacks.ts
- packages/lesswrong/server/posts/annualReviewMarkets.ts
- packages/lesswrong/server/resolvers/postResolvers.ts
- skip cloudinary image upload attempt for fields that didn't update
- curry `marketInfoLoader` to give it a resolver context, so we can avoid doing a second round trip to the database to get the same list of posts we already fetched
The first was a blocking operation for any update on a collection with makeEditable fields, with each such field causing (even if the field itself wasn't changed):
1. a raw Collection.findOne for the record which was just updated
2. fetching the latest revision for that record
...in sequence, adding at least 2 round trips to the DB.  That wouldn't matter most of the time, but most relevant collections have several editable fields, which greatly increases the chances that one of those sets of operations runs into some random cause of additional latency.
The …
> Various perf fixes

- packages/lesswrong/server/serverSentEvents.ts
I just noticed the `TypingIndicatorsRepo.getRecentTypingIndicators` query being logged in my terminal, seems reasonable to forum-gate this since we don't use this feature.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207185031153009) by [Unito](https://www.unito.io)
> forum-gate checkForTypingIndicators

- packages/lesswrong/lib/instanceSettings.ts
- packages/lesswrong/server.ts
- packages/lesswrong/server/embeddings.ts
- packages/lesswrong/server/repos/CommentsRepo.ts
- packages/lesswrong/server/repos/PostsRepo.ts
- packages/lesswrong/server/repos/SequencesRepo.ts
- packages/lesswrong/server/repos/UsersRepo.ts
- packages/lesswrong/server/scripts/reindexDeletedUserContent.ts
- packages/lesswrong/server/search/elastic/elasticCallbacks.ts
This PR reindexes content for deleted users in order to show "[[anonymous]]" instead of their display name in search results to match the rest of the site.
After deploying it is required to run `./scripts/serverShellCommand.sh "Globals.reindexDeletedUserContent()"` in order to reindex content for users who have already been deleted (this takes about 1.5 minutes on the EA dev database).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207197951693956) by [Unito](https://www.unito.io)
> Reindex content in elastic for deleted users

- packages/lesswrong/lib/betas.ts
- packages/lesswrong/lib/collections/posts/collection.ts
- packages/lesswrong/lib/collections/users/helpers.tsx
Follow up to #9126 where we hid the options for the UI. Users who already set default moderation guidelines will still have those guidelines applied to their new posts - the changes in this PR make it so that we just ignore the moderation guidelines completely.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207205792361859) by [Unito](https://www.unito.io)
> [EA] Remove ability for authors to moderate posts

- packages/lesswrong/components/posts/EAPostsItem.tsx
- packages/lesswrong/components/posts/PostsListViewToggle.tsx
- Hide the "NEW" flag on small screens
- Load post bodies for foreign crossposts (note that this won't actually work until after the next LW deploy as `plaintextDescription` was only added to the `PostsList` fragment in the main card view PR which was only merged a couple of hours ago, after the last LW deploy)
- Load thumbnail images instead of fullsize images
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207213525046119) by [Unito](https://www.unito.io)
> [EA] Card view quick improvements

- packages/lesswrong/components/tagging/TagSmallPostLink.tsx
- packages/lesswrong/components/users/UsersName.tsx
- packages/lesswrong/components/users/UsersNameDisplay.tsx
- packages/lesswrong/components/users/UsersNameWrapper.tsx
Before:
After:
I think this probably broke in https://github.com/ForumMagnum/ForumMagnum/commit/60d76c065709d9f972ae24bbce54c372ff5c6ec7 . The issue is that flexboxes are sensitive to their immediate children, so wrapping something in a tooltip is not safe if it's the immediate child of a flexbox.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207217273113415) by [Unito](https://www.unito.io)
> Fix styling of TagSmallPostLink in tag hover preview

- packages/lesswrong/components/Layout.tsx
The splash art on the frontpage was previously limited by the existence of the image column. (i.e. people with slightly smaller screens or slightly lower resolution wouldn't see the image, at a screen size where there should clearly still be some image visible)
This PR changes the image to not use the image column. I think this probably means the image column is no longer in use. I'm not using the image column in my spotlights PR and don't think we really need it, so maybe should completely remove it, but I wasn't sure about all the ramifications.
Previous image:
Now:
Text appears as small as this:
Image continues to render as small as this:
At extremely wide/short screens there was some overlap so I added a gradient overlay:
I made sure the All Post image was still visible:
┆Issue is …
> Fix LW splash art positioning

- packages/lesswrong/components/common/ForumDropdownMultiselect.tsx
Previously the "Custom" date range modal on the user analytics page would close as soon as it is opened. I believe this was introduced recently because I was testing it the other day (for https://github.com/ForumMagnum/ForumMagnum/pull/9156), I think it was probably a side effect of the upgrade to React 18, specifically the vendoring of ClickAwayListener.
I don't understand the underlying cause here, I've made a [ticket](https://app.asana.com/0/628521446211730/1207255671655403/f) to look into that and see if we can find similar problems elsewhere. I checked a few obvious cases of dropdowns opening modals and didn't find anything similar.
Update: this appears to be part of a broader class of bug, although this does fix this specific case so I think it's worth merging still
┆Issue is …
> [EA] Fix for analytics custom date range modal closing immediately

- packages/lesswrong/components/notifications/NotificationsPage/NotificationsPageKarmaChange.tsx
- packages/lesswrong/lib/collections/users/karmaChangesGraphQL.ts
- packages/lesswrong/server/repos/VotesRepo.ts
We get the user display names here directly from a SQL query, which means we don't have the fields usually given by `UsersMinimumInfo`. Presumably this is why these weren't links in the first place.
I have added the user slug to the returned value, and made the names regular `Link`s to the user profile. This isn't ideal as it doesn't use `UsersNameDisplay` so this could introduce inconsistencies in future, also the user tooltip doesn't show on hover whereas it does for other notification types.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207265877686661) by [Unito](https://www.unito.io)
> [EA] Link to user profiles in react notifications

- packages/lesswrong/lib/vulcan-lib/utils.ts
Fixes it for future posts/messages; you have to edit/re-save for the fix to take effect.
Was caused by a missing style in the HTML sanitizer.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207234738980304) by [Unito](https://www.unito.io)
> Fix styling of Calendly embeds

- packages/lesswrong/components/ea-forum/EAEmojisHeader.tsx
- packages/lesswrong/server/repos/DatabaseMetadataRepo.ts
- packages/lesswrong/server/resolvers/eventEmojiResolvers.ts
- Only approved users can add emojis to the banner
- Emojis are anonymous
- This is slightly tricky because the code we borrowed from the banner in December uses the `displayName` to distinguish between the emoji that's being added client side and the pre-existing emojis returned by the server. For the sake of a quick fix, there's still a `displayName` field on the emojis returned from the server, but the name is always "a".
- Add a left margin so emojis can't be added underneath the text
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207275352966753) by [Unito](https://www.unito.io)
> More emoji banner tweaks

- packages/lesswrong/components/posts/RecombeePostsList.tsx
- packages/lesswrong/lib/collections/users/recommendationSettings.ts
- packages/lesswrong/server/recombee/client.ts
- packages/lesswrong/server/resolvers/postResolvers.ts
Caching recommendations sorta broke `Load More` (in the sense that it started returning purely latest posts), since recombee doesn't let you get NextItems on recommIds older than 30 minutes.  Work around this by:
- having the client pass back a list of post ids to exclude, in the case where we're currently showing cached recommendations which we can't fetch next items for.  We instead fetch a fresh set of recommendations with an additional filter to exclude the posts shown from the previous set.
- having the server pass back a `generatedAt` on each recommendation, so the client can figure out which recommIds are stale when the user clicks `Load More`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207310400301180) by [Unito](https://www.unito.io)
> make load more work for stale recommendations

- packages/lesswrong/components/editor/PresenceList.tsx
When link sharing is enabled, logged-out users can connect to collaborative editing sessions. When this happens, for CkEditor cloud purposes, they get a random ID in place of a user ID. In the presence list, we were taking that random ID and trying to look it up as though it was a user ID, resulting in a lot of console errors, and anonymous users not being shown in the presence-list indicator.
This change handles anon users in the presence list properly; they now show up in the presence list when connected, and don't produce console/Sentry errors.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207279756421270) by [Unito](https://www.unito.io)
> Fix error in PresenceList when logged-out (link-sharing) users are connected

- packages/lesswrong/components/editor/CKCommentEditor.tsx
- packages/lesswrong/components/editor/CKPostEditor.tsx
- packages/lesswrong/components/editor/EditorFormComponent.tsx
- packages/lesswrong/components/editor/ReactCKEditor.tsx
Hackily fix a crash in the CkEditor collaborative editor, which happens in a race-condition-like circumstance of some sort.
This works very hackily, by making the `ReactCKEditorWrapper` ignore downward-flowing changes to its `data` prop, if collaborative editing is enabled. This means that changes to the contents of the editor can't be initiated from outside the editor. It turns out that cases where collab-editing is enabled, and cases where we need to edit the editor contents from outside, don't overlap very much, so this should be ok.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207280033327637) by [Unito](https://www.unito.io)
> Fix collab-editor crash with realtimecollaborationclient-editor-setdata-and-editor-data-set-are-forbidden-in-real-time-collaboration

- packages/lesswrong/components/common/HomeLatestPosts.tsx
- packages/lesswrong/components/common/LWHomePosts.tsx
- packages/lesswrong/components/ea-forum/EAHomeCommunityPosts.tsx
- packages/lesswrong/components/ea-forum/TargetedJobAd.tsx
- packages/lesswrong/components/hooks/useRecentOpportunities.ts
- packages/lesswrong/components/posts/PostsItemDate.tsx
- packages/lesswrong/components/posts/PostsTimeframeListExponential.tsx
- packages/lesswrong/components/recommendations/CuratedPostsList.tsx
- packages/lesswrong/components/recommendations/RecommendationsSamplePage.tsx
- packages/lesswrong/components/recommendations/WelcomePostItem.tsx
Question: It is May 14, 16:50, Pacific time. What time was it 90 days ago? Answer: It depends what timezone you do the computation in! If it crosses a DST boundary, this will be 90\*24+1 hours ago instead of 90*24 hours ago.
This causes the `after` filter in `LWHomePosts` to be different when the client computes it (in the client timezone) than when the server computes it (in the server timezone), which causes the post list to display, then turn blank and refresh.
This is closely related to the bug that f549fdd777700193bbf7322a3f331a77d2940934 tried to fix.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207320124740510) by [Unito](https://www.unito.io)
> Fix SSR mismatch/rerender if 90-days-ago crosses a DST boundary

- packages/lesswrong/server/repos/PostsRepo.ts
When we start loading a post page, before we start rendering it in an SSR, we sometimes send the part of the header that tells the client to start downloading the stylesheet and javascript bundle. Before we can send that, we need to be sure the request is going to result in an http 200 (ie, not a 404 or a redirect). This is handled by `PostsRepo.postRouteWillDefinitelyReturn200`. However, this handled the AF flag incorrectly; rather than checking whether the user is loading a non-AF post on AF (which would trigger a redirect), it checks whether the user is loading an AF post (which can happen on either LW or AF, and will not trigger a redirect). This meant that AF posts didn't get the bundle/stylesheet preload, making them slower. …
> Fix bundle/stylesheet preload for AF-to-LW crossposts

- .github/workflows/deployBaserates.yaml
This fixes the github action config file for deploying LW's `baserates` testing/staging server by pushing to the corresponding branch. (It has already been tested by using this config on the `baserates` branch itself.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207110656210439) by [Unito](https://www.unito.io)
> Fix config for deploying the baserates branch

- packages/lesswrong/lib/collections/clientIds/schema.ts
- packages/lesswrong/server/migrations/20240513T135549.set_not_null_clientId.ts
- schema/schema_changelog.json
This caused a problem on prod when running the migration (see [here](https://github.com/ForumMagnum/ForumMagnum/actions/runs/9112568460/job/25052093377)). It appears `SET NOT NULL` always locks the table, I tried this [workaround](https://dba.stackexchange.com/questions/267947/how-can-i-set-a-column-to-not-null-without-locking-the-table-during-a-table-scan/268128#268128) but it didn't work (possibly due to running in a transaction) so I'm giving up and removing the constraint as it isn't actually required.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207335689112253) by [Unito](https://www.unito.io)
> Remove NOT NULL constraint for client ids

- packages/lesswrong/unitTests/useDebouncedCallback.tests.tsx
There's currently an ugly error message in the unit tests about this missing call to `act`. The test still passes so I'm not sure if it's actually necessary, but it seems worth it to keep the logs clean.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207345449323380) by [Unito](https://www.unito.io)
> Add missing `act` to `useDebouncedCallback` unit test

- packages/lesswrong/client/AppGenerator.tsx
- packages/lesswrong/lib/types/windowObjectExtensions.ts
- packages/lesswrong/lib/utils/timeUtil.ts
Not sure if it's a one-time issue for users with old clients, but https://github.com/ForumMagnum/ForumMagnum/pull/9204 seems to be causing a fair number of errors like `Cannot read properties of undefined (reading 'renderedAt')` in sentry.  In any case, it seems like there are empirically cases where there is no `ssrMetadata` on `window`, which causes some problems.
> Optional ssr metadata

- packages/lesswrong/server/analytics/postgresConnection.ts
Upgrading our dev analytics db from Postgres 11 to 16 resulted in errors like this:
```
Error: self-signed certificate in certificate chain
```
This PR adds the ability to use root certificate from RDS as described [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.CertificatesAllRegions). I have also added the certificate for us-east-1 to the EAF credentials repo.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207371599210654) by [Unito](https://www.unito.io)
> Add SSL settings + certificate for analytics db

- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
- packages/lesswrong/components/community/Community.tsx
- packages/lesswrong/components/ea-forum/StickiedPosts.tsx
- packages/lesswrong/components/users/EditProfileForm.tsx
- packages/lesswrong/components/users/FriendlyUsersProfile.tsx
- packages/lesswrong/lib/routes.ts
This PR has a handful of small changes:
1. Commenting out the job ad component for now, because I finally finished gathering data on the existing rounds. This will be re-enabled next octave with a new round.
2. Changed the LHS link "Groups" to be "Join a group" to see if that helps it get more clicks
3. Changed the title of that page to just be "Groups", since it's no longer called "Groups & people"
4. Changed the "Edit profile" link to be "Edit public profile", to try to be more distinct from "Account settings"
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207396388928561) by [Unito](https://www.unito.io)
> [EA Forum only] pause job ads, plus a few small copy changes

- packages/lesswrong/lib/collections/clientIds/schema.ts
- packages/lesswrong/lib/collections/posts/fragments.ts
- packages/lesswrong/lib/collections/posts/schema.tsx
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/server/cacheControlMiddleware.ts
For debugging purposes, we were checking a flag on individual posts to see if CDN caching was allowed. This isn't needed any more, and it has a small performance overhead (adds 1 round trip, probably ~10ms to all post page loads).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207382900715608) by [Unito](https://www.unito.io)
> Remove per-post setting for swr caching

- packages/lesswrong/components/comments/CommentsNewForm.tsx
- packages/lesswrong/components/comments/SideCommentIcon.tsx
- packages/lesswrong/components/common/ForumDropdownMultiselect.tsx
- packages/lesswrong/components/common/withDialog.tsx
- packages/lesswrong/components/editor/PostSharingSettings.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/components/sunshineDashboard/NewModeratorActionDialog.tsx
- packages/lesswrong/components/sunshineDashboard/RejectContentButton.tsx
- packages/lesswrong/components/users/UsersMenu.tsx
- packages/lesswrong/components/votes/lwReactions/NamesAttachedReactionsVoteOnComment.tsx
- packages/lesswrong/components/votes/withVote.ts
- packages/lesswrong/lib/vendor/react-click-away-listener.ts
This is the specific bug this is fixing (before), there were a couple of other bugs like this which have already been worked around:
https://github.com/ForumMagnum/ForumMagnum/assets/77623106/eddf785d-6196-443a-ae7d-05c3cc8b667f
The fix in this PR is essentially this line:
```typescript
// Events from MUI form components have the base event under the "nativeEvent" field
bubbledEventTarget.current = ('nativeEvent' in event) ? event.nativeEvent.target : event.target;
```
There are also some changes related to how `LWClickAwayListener` interacts with [portals](https://react.dev/reference/react-dom/createPortal) (where an element is created at the root level of the document rather than in the place it is instantiated) to hopefully make it a bit more robust.
This is the bit of code that …
> Fix clickaway bugs

- packages/lesswrong/server/callbacks/conversationCallbacks.ts
It seems like this code was incorrectly blocking users from creating more than `MAX_ALLOWED_CONTACTS_BEFORE_BLOCK` conversations, even if they were already reviewed.  (We only create the mod action indicating they were flagged if they weren't reviewed, and the error message in the block case suggests it should only apply to unreviewed users.)
cc @jpaddison3
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207499493581591) by [Unito](https://www.unito.io)
> don't block reviewed users from creating many conversations

- .github/workflows/deployEABeta.yaml
- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/themes/globalStyles/globalStyles.ts
A few fixes to the "play from heading" feature:
1. Only show the play buttons if the audio player is visible
2. Peter updated the styling on their side, so some CSS updates to match
Again you can preview on [this post](https://beta.effectivealtruism.org/posts/A7kDruJ4orqZw4uFv/beneficentric-virtue-ethics).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207508999754664) by [Unito](https://www.unito.io)
> [EA Forum only] fixes for audio "play from heading"

- packages/lesswrong/server/callbacks/votingCallbacks.ts
- packages/lesswrong/server/manualMigrations/2024-06-05-rewriteOldReviewBotComments.ts
A small fix that makes the migration actually idempotent.
I don't think the change in `votingCallbacks` has any meaningful affect, because I think the revision creation normalises the href to have quotes around it, but seemed nice for consistency.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207517414948462) by [Unito](https://www.unito.io)
> Normalise migration href quotes

- packages/lesswrong/server/resolvers/postResolvers.ts
Posts created via google doc import in the AF context would previously not be created with the appropriate AF fields: `af: true` if the user already had permission to post to AF, and `suggestForAlignmentUserIds` with the user's id if they didn't.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207517475938939) by [Unito](https://www.unito.io)
> fix google doc imports on the alignmentforum

- packages/lesswrong/components/users/ViewSubscriptionsPage.tsx
(this PR is built on my other Subscriptions PR, it should be merged after)
The manage subscriptions page was never really styled. I did a quick job to make it look a little better. 
- The largest change is not showing empty lists for subscription types a user doesn't have any subscriptions of. There are too many and it's cluttered and overwhelming.
- I've added an optional description for each subscription type
- I gave the subscription type new titles, focusing that most of them are notifications (to distinguish them from following/include in feed)
This work is not forum gated because I assume the EAF would like all these changes. Please confirm.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207534036460623) by [Unito](https://www.unito.io)
> Clean Up ManageSubscriptions page

- packages/lesswrong/server/repos/UsersRepo.ts
- packages/lesswrong/server/resolvers/userResolvers.ts
When people sign up via google oauth the created user already has their full name as its `displayName`, which previously resulted in an error if the person tried to set their exact name as their display name during sign up. This fixes that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207541518043883) by [Unito](https://www.unito.io)
> Exclude current user from isDisplayNameTaken

- packages/lesswrong/components/alignment-forum/AlignmentForumHome.tsx
- packages/lesswrong/components/common/HashLink.tsx
- packages/lesswrong/components/dropdowns/posts/DuplicateEventDropdownItem.tsx
- packages/lesswrong/components/dropdowns/posts/EditPostDropdownItem.tsx
- packages/lesswrong/components/dropdowns/posts/PostAnalyticsDropdownItem.tsx
- packages/lesswrong/components/localGroups/LocalGroupPage.tsx
- packages/lesswrong/components/posts/PostsTitle.tsx
- packages/lesswrong/components/posts/SpreadsheetPage.tsx
- packages/lesswrong/lib/reactRouterWrapper.tsx
See: https://x.com/ID_AA_Carmack/status/1787850053912064005
Adds a prop `doOnDown` to our `Link` component which, if true, makes the link navigate on press rather than on release. Currently we apply this only to `PostsTitle` (which is used in `PostsItem`). Also refactor the `Link` component so that the `to` field is always a string, replacing a few cases where it was an object and was relying on `react-router-dom` to do string-munging to turn it into a link.
If feedback on this is positive, we may wish to change the default value of `doOnDown` to `true`, so that it applies to all links, not just post links. For now we're not doing that because there's some risk that some weird link we're not paying attention to interacts badly with it, eg a link with a custom `onClick` handler.
┆Issue is …
> Some links navigate on press, rather than on release

- packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
- packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx
- packages/lesswrong/components/events/modules/VirtualProgramCard.tsx
- packages/lesswrong/components/hooks/useEAVirtualPrograms.ts
Based on [this figma](https://www.figma.com/design/qAHRGADVOGojqKpqbGMFFu/2024-Q2?node-id=255-15863):
1. Move Handbook and podcast links to the left side
2. Remove the Resources, Saved posts, and Podcasts sections from the RHS
3. Add a section for the VP Intro Program in the RHS
I also decided to reorganize the bottom links in the left side a bit since adding two new links made it rather long. I separated out the "Contact us" link because I think that's important, and I recently talked with an author who didn't know how to contact us. Honestly there are still a lot of links so maybe we should reorganize it another way. 🤷‍♀️ 
Left side:
Right side:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207510084217435) by [Unito](https://www.unito.io)
> [EA Forum only] update homepage RHS

- packages/lesswrong/components/hooks/useRecordPostView.tsx
- packages/lesswrong/components/recentDiscussion/FeedPostCommentsCard.tsx
- packages/lesswrong/components/recentDiscussion/useRecentDiscussionThread.ts
- packages/lesswrong/server/markAsUnread.ts
- packages/lesswrong/server/repos/ReadStatusesRepo.ts
This reintroduces functionality somewhat similar to what was removed in https://github.com/ForumMagnum/ForumMagnum/pull/6309, except only for the Subscribed feed, and if there isn't already a ReadStatus for a post we create it with `isRead: false` (since in the case where a user e.g. clicks on a comment on a feed item for a post that they haven't read yet, it'd be wrong to set `isRead: true`, while updating an existing ReadStatus should avoid changing the `isRead` value).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207556787974795) by [Unito](https://www.unito.io)
> update readstatus lastUpdated when users interact with comments in subscribed feed

- README.md
- packages/lesswrong/server/cache/README.md
Caching of post pages on the EA Forum has been up and running for about a month now. We haven't seen any problems with staleness, so I think this is stable enough that LW could adopt it now (cc @b0b3rt @jimrandomh )
For the EA Forum we're getting a hit rate of 60-70% for posts:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207551254749034) by [Unito](https://www.unito.io)
> Add notes on setting up CDN caching

- packages/lesswrong/components/tagging/FooterTag.tsx
- packages/lesswrong/components/users/FriendlyUsersProfile.tsx
- packages/lesswrong/lib/collections/users/fragments.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
Show interested tags on the user profile page ([Figma](https://www.figma.com/design/qAHRGADVOGojqKpqbGMFFu/2024-Q2?node-id=943-13756&m=dev)).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207496996688047) by [Unito](https://www.unito.io)
> [EA] Show interested tags on the user profile

- packages/lesswrong/components/common/ForumIcon.tsx
- packages/lesswrong/components/icons/CheckSmallIcon.tsx
- packages/lesswrong/components/peopleDirectory/PeopleDirectorySelectOption.tsx
New design for checkboxes in the people directory ([Figma](https://www.figma.com/design/qAHRGADVOGojqKpqbGMFFu/2024-Q2?node-id=809-1290&m=dev)).
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207496638063210) by [Unito](https://www.unito.io)
> [EA] Improve checkboxes in people directory dropdowns

- packages/lesswrong/components/peopleDirectory/PeopleDirectorySocialMediaCell.tsx
- packages/lesswrong/components/peopleDirectory/peopleDirectoryColumns.ts
The social media icons currently overlap on small screens for users with many different links.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207494034602426) by [Unito](https://www.unito.io)
> [EA] Fix social media icon wrapping in the people directory

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/components/votes/lwReactions/HoveredReactionContextProvider.tsx
- packages/lesswrong/components/votes/lwReactions/InlineReactHoverableHighlight.tsx
- packages/lesswrong/components/votes/lwReactions/NamesAttachedReactionsVoteOnComment.tsx
Previously, inline reacts had their highlight-on-hover split up by e.g. italics and links.  Now they are highlighted even when split up by italics/etc.
> Contents of inline reacts are highlighted even when split up by italics/etc

- packages/lesswrong/components/common/LWHomePosts.tsx
- packages/lesswrong/server/recombee/client.ts
Not typical behavior for stickies but seems better here
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207569509456797) by [Unito](https://www.unito.io)
> hide sticked posts on recombee posts list and in subscribed tab if read

- packages/lesswrong/components/common/ContentItemBody.tsx
- packages/lesswrong/components/linkPreview/FootnotePreview.tsx
- packages/lesswrong/components/posts/PostsPage/CollapsedFootnotes.tsx
- packages/lesswrong/lib/betas.ts
- packages/lesswrong/server/loadDatabaseSettings.ts
If you click a footnote in the body of a post whilst the footnotes section is collapsed we automatically open the footnotes section and scroll to the relevant footnote. However, there's a transition to open the footnotes section, so sometimes we scroll to the wrong footnote if the section is very large and takes a long time to open (especially on slow devices). The is easily reproducible in [this prod-db post](http://localhost:3000/posts/LpkXtFXdsRd4rG8Kb/reducing-long-term-risks-from-malevolent-actors), for instance.
This PR adds a timeout so we only scroll to the footnote after the animation is complete. This reproducibly fixes the bug, even with a 6x CPU throttle in dev tools.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207493910281102) by …
> Fix logic for scrolling to footnotes when section is collapsed

- packages/lesswrong/server/search/elastic/ElasticConfig.ts
Suggested changes to comment search relevance - see discussion at https://cea-core.slack.com/archives/CJUN2UAFN/p1716316808809109
Increases relevance for author name, and gives an extra boost to comments with more than 50 karma. Sadly, we don't currently have a better way of tracking whether or not this is an improvement than just looking at results and saying "this looks better" or "this looks worse", but I think this looks better.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207375767455968) by [Unito](https://www.unito.io)
> Comment search relevance tweaks

- packages/lesswrong/components/common/HashLink.tsx
#9394 introduced a bug for `linkClicked` analytics events, this PR fixes it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207594018081095) by [Unito](https://www.unito.io)
> fix link click tracking

- packages/lesswrong/server/exportUserData.ts
We just had another GDPR user data request and I noticed that quite a few collectionswere missing from the export script (mostly relatively new ones).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207599852252272) by [Unito](https://www.unito.io)
> Add more collections to the user data export script

- packages/lesswrong/components/common/HashLink.tsx
Run any custom onMouseDown logic, including event tracking (such as that passed in from `Link`) before checking for modifier keys. This is necessary to capture e.g. `linkClicked` events when cmd-clicking to open links in a new tab.
cc @jimrandomh
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207625879389503) by [Unito](https://www.unito.io)
> run custom onMouseDown logic before doing an early return for modifier keys

- packages/lesswrong/components/common/LWHomePosts.tsx
- packages/lesswrong/components/common/TabPicker.tsx
Default tab now selected based on property in json of available tabs.
Logged-out users put onto `forum-classic` superceding any other logic
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207625565196346) by [Unito](https://www.unito.io)
> improve frontpage default tab selection

- packages/lesswrong/components/comments/CommentsNewForm.tsx
- packages/lesswrong/components/recentDiscussion/FeedPostCommentsCard.tsx
- packages/lesswrong/components/recentDiscussion/useRecentDiscussionThread.ts
The new `markCommentsAsRead` functionality in the Subscribed tab made it impossible to click on either button in the comment submit form (cancel/submit), since the `SubmitComponent` relied on `cancelCallback`, which wasn't referentially stable and caused a rerender after `markCommentsAsRead` ran.  Fix in two parts:
1. Switch `markCommentsAsRead` from `onMouseDown` to `onMouseUp` (h/t @darkruby501), to both ensure that it doesn't run before any `onClick` handlers in child components (such as on the buttons), and also to ensure that any `preventDefault`/`stopPropagation` calls in children's `onClick` handlers don't stop it from running.
2. Add a `setTimeout(() => { ... }, 0)` wrapper to the functionality of `markCommentsAsRead`, since without that it still seems to cause the children to …
> Switch to onMouseUp with setTimeout to allow clicking on less stable child elements

- packages/lesswrong/server/callbacks/postCallbacks.ts
- packages/lesswrong/server/recombee/client.ts
@Discordius saw an unlisted post show up in his recommendations, probably because our logic to filter them out before sending them to recombee wasn't being consistently applied (it was missing from the voting callback).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207635388548991) by [Unito](https://www.unito.io)
> filter out posts from being sent to recombee more consistently

- packages/lesswrong/lib/analyticsEvents.tsx
Since https://github.com/ForumMagnum/ForumMagnum/pull/9134 there has been a race condition between the firing of the "pageLoadFinished" event (triggered by [load](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event)) and the initialization of `clientContextVars`. This has meant that `clientId` `tabId`, and `userId` are usually dropped from that event.
This PR makes it so that `clientContextVars` are also added when the events are submitted as a fallback. This was already intended to be the case, but because they were added in the wrong part of the event the values weren't being picked up
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207636000587413) by [Unito](https://www.unito.io)
> Fix race condition in pageLoadFinished event

- packages/lesswrong/server/recombee/client.ts
Not having `filterSettings` in the post view terms means that `filteredScore` ends up being an aliased `score` rather than the actual synthetic expression.  As an upside, adding them means that we obey the user's filter settings in the `Enriched` tab at least for the native latest posts half of it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207641529494082) by [Unito](https://www.unito.io)
> use filter settings for latest posts in enriched tab to fix filteredScore synthetic field

- packages/lesswrong/server/editor/conversionUtils.ts
- packages/lesswrong/unitTests/__snapshots__/googleDocImport.tests.ts.snap
- packages/lesswrong/unitTests/googleDocImport.tests.ts
`<ul>` and `<ol>` elements imported from Google docs come with a class like `lst-kix_gwukp0509sil-0`. Previously we were assuming that the id "gwukp0509sil" is a reliable indicator of which overall bullet list that a nested group of bullets belong to. However if you copy paste part of one list into another then the pasted portion keeps the _original_ id, which meant this portion would get inserted back in the original list when imported.
I have changed the logic to rely on only the ordering of elements to decide which list a nested group belongs to.
You can use [this doc](https://docs.google.com/document/d/1g3XRUdjfocOXdWn78IvuXygmEel_lejrr5XQh6XGL4w/edit) for testing (approximately matches what is in the unit test) …
> Google Doc import: handle bullets that have been copy-pasted from another list

- packages/lesswrong/server/emailComponents/EmailComment.tsx
- packages/lesswrong/server/emailComponents/EmailWrapper.tsx
- packages/lesswrong/server/emailComponents/NewPostEmail.tsx
I recently added some default styling to `EmailWrapper` but that messed up styling in some emails, like the line height in the post title of `NewPostEmail` was too small. So I'm cleaning up the styling in that email a bit:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207625673360730) by [Unito](https://www.unito.io)
> update styles in new post email

- packages/lesswrong/server/callbacks/votingCallbacks.ts
- packages/lesswrong/server/repos/VotesRepo.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207662890406947) by [Unito](https://www.unito.io)
> fix longterm senior downvoters check when no results

- packages/lesswrong/components/form-components/MuiTextField.tsx
- packages/lesswrong/components/notifications/CommentOnYourDraftNotificationHover.tsx
- packages/lesswrong/components/sequences/LargeSequencesItem.tsx
- packages/lesswrong/components/tagging/TagPreview.tsx
- packages/lesswrong/themes/createThemeDefaults.ts
- packages/lesswrong/themes/themeType.ts
- packages/lesswrong/themes/userThemes/darkMode.ts
A recent [PR](https://github.com/ForumMagnum/ForumMagnum/pull/9430) exposed an issue in our theme types, which permitted the implementation of a theme field which was missing across all of the base theme, site theme, and user theme (and so was missing in the final merged theme).  This caused a crash-on-start on the AlignmentForum when one attempted to access a _nested_ field within the missing field, since that access was not null-safe (due to the incorrect type assumptions).  In practice, we had a fair number of other missing fields, some of which were even used in our styles, but until now there was no access of a nested field which would cause a `cannot access property ${fieldName} of undefined` exception.
This PR fixes the types to separate the "inputs" to the theme from the "ouput" …
> Create separate NativeThemeType to prevent missing theme options

- packages/lesswrong/server/callbacks/votingCallbacks.ts
We keep getting users in the review queue who have stricter rate limits triggered for votes on content that they posted a long time ago (e.g. 15 years).  We... really don't need to be reviewing those users again.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207689465589028) by [Unito](https://www.unito.io)
> prevent votes on content >6 months old from putting users back in review

- packages/lesswrong/components/common/LWHomePosts.tsx
- packages/lesswrong/components/dropdowns/posts/DislikeRecommendationDropdownItem.tsx
- packages/lesswrong/components/dropdowns/posts/PostActions.tsx
- packages/lesswrong/components/posts/LWPostsItem.tsx
- packages/lesswrong/components/posts/PostsItemIcons.tsx
- packages/lesswrong/components/posts/PostsTitle.tsx
- packages/lesswrong/components/posts/RecombeePostsList.tsx
- packages/lesswrong/components/posts/usePostsItem.tsx
- packages/lesswrong/lib/components.ts
Only present on items being served as recommendations. Supercedes "hide from frontpage" when present since it includes that and that would be a bit redundant
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207712105098130) by [Unito](https://www.unito.io)
> Triple dot menu contains abilty to dislike recommendations

- packages/lesswrong/components/forumEvents/ForumEventFrontpageBanner.tsx
- packages/lesswrong/components/forumEvents/ForumEventPoll.tsx
- packages/lesswrong/components/forumEvents/ForumEventPostPagePollSection.tsx
- packages/lesswrong/components/posts/PostsList2.tsx
- packages/lesswrong/components/posts/usePostsList.ts
- packages/lesswrong/lib/collections/tags/schema.ts
Designs adapted from [this Figma](https://www.figma.com/design/qAHRGADVOGojqKpqbGMFFu/2024-Q2?node-id=1943-560&m=dev)
1. Add the placement number next to each "most influential post"
2. Add a way to view votes in each cluster, by hovering over it
3. Fix a broken link on the post page section (see https://github.com/ForumMagnum/ForumMagnum/pull/9457)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207708686884285) by [Unito](https://www.unito.io)
> [EA Forum only] debate week homepage banner improvements

- packages/lesswrong/server/twitterBot.ts
Fixes for a couple of issues I noticed after deploying:
- If an attempt to post a tweet fails for some reason it keeps retrying with the same post
- Using db level settings rather than instance settings meant other instances (e.g. the beta site or bot site) would try to post tweets too
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207725476625498) by [Unito](https://www.unito.io)
> [EA] Tweaks to twitter bot: proceed on error, use instance rather than db settings

- packages/lesswrong/components/hooks/useEAVirtualPrograms.ts
I noticed it was off by a week on the homepage, so updated the logic
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207730003598312) by [Unito](https://www.unito.io)
> [EA Forum only] VP dates are back to "normal"

- packages/lesswrong/lib/ckEditorUtils.ts
A user reported an issue when attempting to upload an image to a post they were editing.  Investigating in ckEditor's dashboard reveaeld that the token had passed its `maxAge`; inspecting the jwt itself revealed that it was ~6 days old (ckEditor tokens are only valid for 24 hours).
`lru-cache` does not actually have a default TTL, despite the previous comment.  I'm not sure how this is the first time the issue's come up since it's been a ~year since it was implemented, but I guess you'd need to get somewhat unlucky as a user to run into it - you'd need to hit a server instance you interacted with to generate a ckEditor token for the same post more than 24 hours ago (so that it'd still be cached).  This requires editing a post across multiple days with no deploys having gone out in the …
> set ttl for ckeditor tokens to prevent expired tokens from being used

- packages/lesswrong/themes/globalStyles/miscStyles.ts
Before/after:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207737669644744) by [Unito](https://www.unito.io)
> Fix for user mention UI appearing behind modals

- packages/lesswrong/components/quickTakes/QuickTakesListItem.tsx
Before/after:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207737702119003) by [Unito](https://www.unito.io)
> Fix quick takes hover sidebar overflowing

- packages/lesswrong/lib/collections/sequences/permissions.ts
A user reported an issue to us, where they could still see their sequence linked at the top of a post page even after they deleted the sequence. This was only visible to the sequence author and admins, but from the sequence author perspective this is really confusing.
When you delete a sequence, the UI implies that it's irreversible - if the user wanted a reversible version they could just move it back to draft. Given that, I think it's better to actually treat `isDeleted` as a soft delete that makes the sequence no longer visible to anyone on the site.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207781116103970) by [Unito](https://www.unito.io)
> hide deleted sequences across the site

- packages/lesswrong/server/callbacks/intercomCallbacks.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207805919863494) by [Unito](https://www.unito.io)
> When Intercom page-view event recording fails with a 401, don't fail the /graphql with a 401

- packages/lesswrong/components/common/ContentItemBody.tsx
- packages/lesswrong/lib/recombee/client.ts
The `ContentItemBody` change was a debugging diff incorrectly left in from a previously PR, and recombee is just pretty noisy when it comes to letting us know that it can't register some events because it doesn't know about the relevant user or post.  That happens often enough for innocuous reasons that we don't need to see it Sentry.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207817431807591) by [Unito](https://www.unito.io)
> clean up console and sentry log spam

- README.md
- build.js
I have recently been developing without the `--watch` flag, adding this variable so I don't have to keep editing the flags in `package.json` manually
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207824484965679) by [Unito](https://www.unito.io)
> Add FM_WATCH env var to allow turning off --watch CLI option

- packages/lesswrong/components/quickTakes/QuickTakesList.tsx
(In response to a bug report via [slack](https://cea-core.slack.com/archives/C038J512SD8/p1721226419147569))
This is to improve a specific case: when there are exactly 5 quick takes that qualify for the frontpage section, we show the "Load more" button but clicking it does nothing because we are showing them all already. If we `enableTotal`, then `useMulti()` properly accounts for this case.
> hide "Load more" if there are no more quick takes

- packages/lesswrong/components/users/UsersProfileImage.tsx
Exclude non-letter characters from fallback user profile images.
Some users have started including emoji characters in their user names and this renders incorrectly in profile image fallbacks:
This PR filters out these characters. See /users/felix-wolf for a relevant example.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207844723110042) by [Unito](https://www.unito.io)
> Exclude non-letter characters from user profile image initials fallback

- packages/lesswrong/integrationTests/collections/users.tests.ts
- packages/lesswrong/lib/collections/users/schema.ts
- packages/lesswrong/server/callbacks/rateLimitCallbacks.ts
- packages/lesswrong/server/repos/LWEventsRepo.ts
- packages/lesswrong/server/repos/index.ts
Previously users were permanently disallowed from changing their name after changing it once, now they can do so after 30 days (cc @jpaddison3 lowered from 90).
@darkruby501 @b0b3rt Do you want this for LW? It's currently forum gated.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207826607529489) by [Unito](https://www.unito.io)
> [EA] Allow users to change their displayName with a rate limit

- packages/lesswrong/components/common/SubscribeDialog.tsx
- packages/lesswrong/components/recentDiscussion/RecentDiscussionSubscribeReminder.tsx
- packages/lesswrong/components/users/UsersEmailVerification.tsx
- packages/lesswrong/lib/collections/users/helpers.tsx
- packages/lesswrong/lib/collections/users/schema.ts
- packages/lesswrong/lib/instanceSettings.ts
- packages/lesswrong/server/callbacks/userCallbacks.tsx
- packages/lesswrong/server/vulcan-lib/apollo-server/authentication.tsx
We had a case of our [bot site](https://forum-bots.effectivealtruism.org/) sending a verification email the other day, which shouldn't have happened as we have email verification disabled. I think this specific problem will already have been fixed by [Jim's change here](https://github.com/ForumMagnum/ForumMagnum/commit/39efbd507cd7c064fbfdc19c8e6a0f805c67e4be), but the code for deciding whether to send verification emails was (is) still a bit of a mess so I have cleaned up some other near-bugs.
There are 3 ways we have blocked sending verification emails over the years on the backend:
1. By checking `isEAForum`
2. This was superseded by `verifyEmailsSetting`
3. There was then a duplicate setting `assumeUserEmailVerifiedSetting` introduced
All of these were still being used in some places. …
> Cleanup email verification logic so EAF never sends verification emails

- packages/lesswrong/themes/createThemeDefaults.ts
- packages/lesswrong/themes/siteThemes/alignmentForumTheme.ts
- packages/lesswrong/themes/siteThemes/eaTheme.ts
- packages/lesswrong/themes/siteThemes/lesswrongTheme.ts
- packages/lesswrong/themes/stylePiping.ts
The font size in LW curation emails was gigantic (22.4px).
The underlying issue is that some (but not all) font-sizes are specified in `rem`, which is a unit which is a multiplier of the root-element's font size. On-site, that's theme.baseFontSize, which 13px and is the same across all site themes, so a size of 1.4rem, which is used for most post text, is 1.4*13px=18.2px. In email contexts, however, the root element isn't under our control, can vary between email clients, and in the case of gmail, is 16px, resulting in a post font size of 22.4px. This is too big, especially when juxtaposed with font sizes for post metadata that are specified in px.
Until recently, most site styles weren't being used in emails, which prevented this from coming up. However commit …
> Fix font size in email post-bodies

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/common/CookieBanner/geolocation.ts
- packages/lesswrong/components/ea-forum/EAGBanner.tsx
- packages/lesswrong/components/ea-forum/EAHome.tsx
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/cookies/cookies.ts
The Events Team is interested in seeing if they can get additional applications via a location-based banner on the Forum. This is an experiment, and based on the results we'll either remove this code or update it to work for future events.
See [slack thread](https://cea-core.slack.com/archives/C0342BY5TK8/p1720691346075829) for additional context, including messages from the Events Team.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207827404476789) by [Unito](https://www.unito.io)
> [EA Forum only] banner for upcoming EAG(x) near you

- packages/lesswrong/server/clientIdMiddleware.ts
- packages/lesswrong/server/repos/ClientIdsRepo.ts
- packages/lesswrong/server/vulcan-lib/apollo-server/authentication.tsx
Previously we only associated users with client ids on login, which was not 100% reliable. This changes it to associate them in the `clientIdMiddleware` which is hit on every request.
I removed the existing code to associate them on login because it should now be redundant.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207840614566295) by [Unito](https://www.unito.io)
> Ensure userIds are associated with clientIds every time a pair is newly encountered

- packages/lesswrong/components/comments/CommentPermalink.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
Fix for a bug introduced in https://github.com/ForumMagnum/ForumMagnum/pull/9522, when there is a hash in the url (e.g. a heading link) that doesn't match a comment there is a "Comment not found" message:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207881322317360) by [Unito](https://www.unito.io)
> Fix bug with 'Comment not found' appearing when navigating to heading

- packages/lesswrong/components/posts/EAPostsItem.tsx
- packages/lesswrong/components/posts/PostsItemTooltipWrapper.tsx
Agnes requested a few UI updates, [Figma here](https://www.figma.com/design/qAHRGADVOGojqKpqbGMFFu/2024-Q2?node-id=1346-1598&m=dev):
1. Bolder text (also for list view pinned posts, community posts, etc. when in card view)
2. Title wraps to two lines
3. Remove hover preview in card view (but not on the list view pinned posts + community etc.)
4. Make image wider and slightly taller
5. Reduce max-width for body text (both for with and without images)
Frontpage screenshot:
-----
A screenshot with a post with a long title:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207881660723932) by [Unito](https://www.unito.io)
> Improve card view UI

- packages/lesswrong/components/sequences/SequencesPage.tsx
I noticed that when I was in admin mode, sequence pages didn't have the "Notify me" button. I fixed that, and updated the edit button copy to "Edit sequence" which I think is clearer.
> [FriendlyUI only] sequence editors can also see the notification button

- packages/lesswrong/lib/collections/users/helpers.tsx
- packages/lesswrong/lib/collections/users/schema.ts
- packages/lesswrong/server/authentication/auth0.ts
- packages/lesswrong/server/callbacks/userCallbacks.tsx
`getAuth0Id` originally threw an error if the user wasn't using username/password login. In a [previous PR](https://github.com/ForumMagnum/ForumMagnum/pull/9466), I renamed this to `getAuth0IdIfUsernamePassword` and added a new `getAuth0Id` function that doesn't have this restriction. This PR merges these back together to clean things up and uses `getAuth0Provider` to check the login method in the cases where we care about that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207893550001357) by [Unito](https://www.unito.io)
> Merge getAuth0Id and getAuth0IdIfUsernamePassword

- packages/lesswrong/lib/collections/comments/schema.ts
- packages/lesswrong/server/languageModels/modGPT.ts
- packages/lesswrong/server/scripts/generativeModels/testModGPTOnComments.ts
The main bug that I fixed is that sometimes we were sending empty comment text to ModGPT. I also took this opportunity to update it to use GPT-4o, which should be better and significantly cheaper. CEA peeps can also see [this Hex dashboard](https://app.hex.tech/9e4abdcd-b18c-49ca-acfc-3ec5249ddb1a/app/534809f1-324f-46b9-abf9-1a0a6907eaba/latest) if they are curious.
The user-facing features are still turned off, because I want to check its accuracy before turning them back on.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207893428491254) by [Unito](https://www.unito.io)
> [EA Forum only] update ModGPT to GPT-4o, plus some bug fixes

- packages/lesswrong/components/common/excerpts/PostExcerpt.tsx
- packages/lesswrong/components/recentDiscussion/EARecentDiscussionThread.tsx
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207896177717233) by [Unito](https://www.unito.io)
> [EA] Use post contents rather than customHighlight as the excerpt in recent discussion

- packages/lesswrong/components/tagging/TagPage.tsx
I've copied over the "Quick takes" section from the core topic page (ex. [this one](https://forum.effectivealtruism.org/topics/global-health-and-development)) to the bottom of the standard topic/tag page. This is primarily so that quick takes associated with Forum events can be found on the relevant page, such as [AI Welfare Debate Week](http://localhost:3000/topics/ai-welfare-debate-week).
This section should almost never otherwise appear. Normally on the EA Forum, the list of core topics and the list of topics that you can tag your quick take with are equivalent. And I think LW doesn't allow users to tag their quick takes.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207893513719272) by [Unito](https://www.unito.io)
> show quick takes on tag pages

- packages/lesswrong/components/hooks/useInitiateConversation.ts
- packages/lesswrong/components/messaging/MessageUser.tsx
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/routes.ts
Requested by Toby, this makes it so going to `/message/:slug` will open/create a conversation with the given user as if you had pressed the "New message" button.
I'm adding this as a hidden feature initially, with the idea being that if other users notice and ask for it then we can add a way of getting the link in the UI somewhere.
Making the link copyable from the UI is easy for _other_ users (because we can make the message button a link), but not for your own user, we would likely have to add something to the profile page. I don't want to clutter that page too much, hence why I'm making this a hidden feature at first.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207908275624562) by [Unito](https://www.unito.io)
> Add link to DM a specific user

- packages/lesswrong/components/posts/TableOfContents/ToCColumn.tsx
- packages/lesswrong/themes/createThemeDefaults.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207909807330793) by [Unito](https://www.unito.io)
> Fix hide-ToC button on EA forum being unclickable due to z-index at some scroll positions

- packages/lesswrong/components/form-components/FormComponentNumber.tsx
These should only be used for class components (this is a functional component), and they produce an annoying console error with an enormous stack trace.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207941593204885) by [Unito](https://www.unito.io)
> Remove `childContextTypes` and `contextTypes` from `FormComponentNumber`

- .github/workflows/eaDailyDevReplica.yaml
We have a Github workflow that runs a daily cron job to create a dev replica DB for the EA forum. This has been failing for a long time (see https://github.com/ForumMagnum/ForumMagnum/actions/workflows/eaDailyDevReplica.yaml), and I get an annoying email every morning telling me that it's failed.
The only use of this replica is to support the "branch-db" feature that we never actually finished and have never used. This PR disables the failing cron workflow, but the scripts still exist so we can fix the issue if we ever want this in the future (and the job can still be triggered with the "workflow dispatch" button in the Github UI).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207920765499796) by [Unito](https://www.unito.io)
> Disable cron for EA daily dev replica workflow

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/ea-forum/EASurveyBanner.tsx
- packages/lesswrong/lib/cookies/cookies.ts
This PR preps the existing EA Forum survey banner for our [upcoming 2024 user survey](https://docs.google.com/document/d/1IOLoGJV9jDNKlwloOuCk0bUNuobNy0ujM9LSL9-sTmY/edit). I mostly kept it the same as before.
I plan to deploy this on August 1 when I publish the [announcement post](https://docs.google.com/document/d/1VPIg72__VQdZGqsDg2TnsWCcQ6phl1_5UQFs1mY03NY/edit). I'll remove it from the site when I close the survey, which depends on how many responses we get.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207936264586699) by [Unito](https://www.unito.io)
> [EA Forum only] update EA Forum survey banner

- package.json
- packages/lesswrong/server/embeddings.ts
- packages/lesswrong/server/recommendations/Feature.ts
- yarn.lock
Porting over some functionality from https://github.com/ForumMagnum/ForumMagnum/pull/8978.
I don't actually remember what motivated me to upgrade to `text-embedding-3-large`... I vaguely feel like I was running into some issues trying to do batch operations using `text-embedding-ada-002`, and didn't want to spend a full day running the backfill, but not confident.
Anyways, if we update the embedding model, that might require the EA forum to run `updateAllPostEmbeddings`, since I'm not sure embeddings generated by different models can be usefully compared.  If you'd prefer to not have the headache I can go back and see if the batch API works with `text-embedding-ada-002` (in which case I can just forum-select the embedding model name), and if not I'll do some rewriting to forum-gate at a …
> Switch to using text-embedding-3-large and batch operations for post embeddings

- packages/lesswrong/components/posts/NewPostHowToGuides.tsx
- packages/lesswrong/components/tagging/NewTagInfoBox.tsx
- packages/lesswrong/components/tagging/NewTagPage.tsx
- packages/lesswrong/lib/components.ts
Adds an info box to the new tag page for EA forum.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207941281084056) by [Unito](https://www.unito.io)
> [EA] Add new tag info box

- packages/lesswrong/components/ea-forum/EAGBanner.tsx
- packages/lesswrong/components/ea-forum/EASurveyBanner.tsx
We had some reports that the survey banner did not stay hidden
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207993811022135) by [Unito](https://www.unito.io)
> [EA Forum only] update "hide banner" cookies to include path

- packages/lesswrong/components/hooks/useExternalScript.tsx
- packages/lesswrong/components/posts/PostsPage/T3AudioPlayer.tsx
Our T3AudioPlayer component is responsible for loading an external script from embed.type.audio. As written, it would delete and re-add this script tag whenever you navigated to and from post pages, meaning the external script's initialization would run repeatedly, leaking memory each time. The practical upshot of that was that if you read the site by navigating to post pages and then using the back button, the tab would leak 5MB of memory (as measured by the Chrome devtools memory profiler) for each post you looked at.
Change the script loading so that once the T3 embed script is added to the page, it stays there and is never removed. This fixes the memory leak.
I tested on localhost by using a hack that intercepts the `fetch` function and replaces the localhost domain in type3 API calls …
> Fix memory leak on post pages

- packages/lesswrong/components/posts/EAPostsItem.tsx
Fixes a bug where the meta text can end up on top of the image in card view for posts with a lot of authors.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207988864724587) by [Unito](https://www.unito.io)
> Add max width to card post meta when there's an image

- packages/lesswrong/components/ea-forum/EASurveyBanner.tsx
Requested on Slack by Agnes:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207997922248612) by [Unito](https://www.unito.io)
> Tidy up mobile styles for EA survey banner

- packages/lesswrong/components/comments/CommentsItem/CommentOutdatedWarning.tsx
Ay a migration changed post version numbers from 0.x to 1.x, causing spurious "reply to previous version" notices.
> Fix spurious indicators of comments being replies to older versions

- packages/lesswrong/components/posts/PostsPage/LWPostsPageHeader.tsx
- packages/lesswrong/components/posts/PostsPage/LWPostsPageHeaderTopRight.tsx
Triple-dot menu for shortform posts was accidentally removed during the #9556 PR. This adds it back.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208082205791529) by [Unito](https://www.unito.io)
> Add triple-dot back to shortform posts

- packages/lesswrong/components/posts/PostsPage/LWPostsPageHeaderTopRight.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPagePostFooter.tsx
- packages/lesswrong/components/tagging/AddTagButton.tsx
- packages/lesswrong/components/tagging/FooterTagList.tsx
This removes tags from the bottom of LW posts, except for on mobile. It adds an "Add Tag" button in the LW Top Right area. It adds a tooltip to the Add Tag button for LW users.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208080020772499) by [Unito](https://www.unito.io)
> [LW] Remove bottom tags, add + to top tags

- packages/lesswrong/components/common/ForumIcon.tsx
- packages/lesswrong/components/posts/PostsPage/LWPostsPageHeader.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
- packages/lesswrong/components/posts/PostsPage/ReadTime.tsx
- packages/lesswrong/components/posts/PostsPage/index.ts
- packages/lesswrong/components/posts/TableOfContents/LWCommentCount.tsx
- packages/lesswrong/components/posts/TableOfContents/MultiToCLayout.tsx
- packages/lesswrong/components/posts/TableOfContents/index.ts
This reverts commit 630b9b177f3949a8bb1d5ba130f2a21e52cae572 (which was itself a revert of me accidentally merging this feature into master, then reverted the commit. Now to actually merge it in a PR it looks like I need to make a revert-of-the-revert)
This adds a "read time" and "comments" button to the mobile version of the new LW post page, because the Table-of-contents version of those features don't exist on mobile.
I felt like the solid-grey comment icon looked too intense next to the audio icon, so this also switches the comment icon to an outlined version. I think this looked reasonable in the bottom-left, so it also changes it there for consistency.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208079645799069) by …
> Show readtime and comments on LW Post Page mobile

- packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
Fixes a regression from #9594 where the logic for showing the read time in the posts header was reversed for the EA Forum. FYI @Raemon.
> Fix not showing post read time in posts page header

- packages/lesswrong/lib/collections/posts/views.ts
This changes the bug from "you can't see any of your drafts" to "the drafts are sorted by last modified instead of wordcount", which is less bad.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208108263500347) by [Unito](https://www.unito.io)
> Don't crash when sorting drafts by word count

- build.js
According to @jimrandomh's investigation, this seemed to be causing a lot of memory pressure, at times knocking instances over when they were in the process of standing up.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208107813901143) by [Unito](https://www.unito.io)
> Prevent estrella from running tsc as a lint step when deployed in production

- packages/lesswrong/components/posts/PostsPage/LWPostsPageHeaderTopRight.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPageSplashHeader.tsx
Previously, the title of a Best of LessWrong page had a bug where if you navigated using the table-of-contents, it would no longer show the title of the post at the top of the page. 
This was because we were hiding titles on pages with hashtags in the URL, since those often represented pages with CommentPermalink components rendered at the top. 
This moves the title to below the header area where the CommentPermalink gets rendered.
While working on this, I also noticed that the tags and audio icon on Splash Pages were too low-opacity. We'd set the opacity low based on how they looked on plain-white pages, but they need to be higher contrast on the splash-background.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208116219705486) by …
> Fix BestOfLW splash page title bug

- packages/lesswrong/components/posts/TableOfContents/MultiToCLayout.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208130807081240) by [Unito](https://www.unito.io)
> Fix ToC incorrectly appearing on hover over the gap between the post and the right column

- packages/lesswrong/components/posts/TableOfContents/MultiToCLayout.tsx
This fixes the thing where the commentToc shrinks weirdly when you scroll up. It was happening because another style ends up overriding the "top" css attribute.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208130834181675) by [Unito](https://www.unito.io)
> Fix comment toc height bug

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/ea-forum/EASurveyBanner.tsx
We're closing the survey at the end of today, so will take down the banner from the site. I'll just merge this in this evening.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208136274729732) by [Unito](https://www.unito.io)
> [EA Forum only] take down the Forum user survey banner

- packages/lesswrong/components/posts/PostsPreviewTooltip/LWPostsPreviewTooltip.tsx
The tags in the frontpage post tooltip feel more overwhelming than helpful. I experimented with getting rid of all of them, and ended up feeling like it was better to leave the top-two, since they probably do help you orient to "what type of of post is this?", and without them, the wordcount felt awkward/orphaned (and I've heard people talk about using the wordcount part).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208078980783052) by [Unito](https://www.unito.io)
> Only show top two tags in LW frontpage post tooltip

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
During various post-page refactors, we introduced an edge-case where comment permalinks with SingleLineComments would stretch to fill the whole screen. 
It turned out PostsPage-centralColumn needed a "maxWidth" set, which we'd removed because most of the time it seemed superfluous. This adds it back in.
> Fix Permalink Bug

- packages/lesswrong/components/common/LWHomePosts.tsx
https://github.com/user-attachments/assets/77fb9f8d-f8e0-4313-bbed-d98786a7704b
I have realigned the text and made it appear conditional on any tag filters having actually been used.
See the video to see what it looks like (ignore the misaligned 'enriched' tab which is not part of the code I shipped).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208097802366568) by [Unito](https://www.unito.io)
> realigned text, and now appears conditionally

- packages/lesswrong/components/votes/lwReactions/NamesAttachedReactionsVoteOnComment.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208138536601756) by [Unito](https://www.unito.io)
> Fix reaction-description sometimes showing "[object Object]" in the tooltip

- packages/lesswrong/components/posts/PostsPage/LWPostsPageHeader.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
This PR does 2 things:
1. You can now subscribe to a meetup group from any of the event pages for that group. Scroll to the bottom to see a subscribe-to-group button.
2. On event pages, the top of the page used to be confusing, in that it showed two dates: the publish date, and the event date. We removed the publish date, and now show it at the bottom of the post (it read "Posted at: <date>").
These changes are Forum Gated.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208172832071162) by [Unito](https://www.unito.io)
> Add group-subscriptions to event page & remove date from top of page

- packages/lesswrong/components/hooks/useCurrentForumEvent.tsx
`useCurrentForumEvent` is feature-flagged to EA Forum only, and the feature flag is checked in th `useMulti`, but it will wind up running this query anyways because `refetch` ignores `skip`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208129086277318) by [Unito](https://www.unito.io)
> Don't try to refetch a current forum event if it's feature-flagged off

- packages/lesswrong/server/embeddings.ts
[This commit](https://github.com/ForumMagnum/ForumMagnum/commit/69b45dafea1782a9d54cd48754f9ee93dc966e90) made it so trying to generate embeddings on the EA Forum would give the error: `This model does not support specifying dimensions`. This fixes that
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208169784750737) by [Unito](https://www.unito.io)
> Fix embeddings for EAF

- packages/lesswrong/components/ea-forum/onboarding/EAOnboardingThankYouStage.tsx
I was the person most interested in this and now I have much less time for it, so we are removing this option. We will probably add it back in some other place, such as in the email drip campaign.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208177700848000) by [Unito](https://www.unito.io)
> [EA Forum only] remove user interview prompt from onboarding

- packages/lesswrong/components/posts/PostsPage/LWPostsPageHeader.tsx
When making the recent #9597 "RSS style linkposts and AF post metadata" I accidentally made linkpost-indicators unclickable on posts. This fixes it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208184454697421) by [Unito](https://www.unito.io)
> Fix linkpost clickability

- packages/lesswrong/components/languageModels/LlmConversationsViewingPage.tsx
- packages/lesswrong/lib/collections/llmConversations/fragments.ts
- packages/lesswrong/lib/collections/llmConversations/schema.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
Helps us understand usage
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208185997035711) by [Unito](https://www.unito.io)
> character counts on llm conversation viewing page

- packages/lesswrong/components/languageModels/LanguageModelChat.tsx
- packages/lesswrong/components/languageModels/LlmChatWrapper.tsx
- packages/lesswrong/server/languageModels/promptUtils.ts
- packages/lesswrong/server/resolvers/anthropicResolvers.ts
This PR does two main things:
1. tries to make sure we don't go over a conversations token limit when creating the initial message context
2. more gracefully handles errors both before and after we start the streaming response
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208186588563023) by [Unito](https://www.unito.io)
> limit input tokens and handle errors via streams

- packages/lesswrong/components/contents/SideItems.tsx
- packages/lesswrong/components/linkPreview/FootnotePreview.tsx
Fixed a bug where side-items recomputed heights every frame, making the post page sluggish (especially but not exclusively under Safari) and using lots of CPU.
Also: Fix a breakpoint mismatch which made it so there was one breakpoint with neither footnote hover preview nor sidenotes.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208194963869095) by [Unito](https://www.unito.io)
> Fix side items resizeobserver loop

- packages/lesswrong/lib/vulcan-lib/utils.ts
- packages/lesswrong/server/editor/conversionUtils.ts
Right now, if you create a LW editor document with LaTeX or footnotes, the resulting markdown will be invalid markdown, because Turndown does not understand the relevant syntax.
This fixes that and allows for round-tripping for both LaTeX and footnotes. These implementations are not enormously robust, but worked well-enough for the cases I looked at.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208195326864904) by [Unito](https://www.unito.io)
> Fix turndown conversion of LaTeX and footnotes

- packages/lesswrong/components/comments/DebateResponse.tsx
- packages/lesswrong/components/votes/lwReactions/InlineReactHoverableHighlight.tsx
Old dialogues weren't using the hoverable inline react context, which led to them breaking at some point.  This adds the context provider.  (Separately, returning `null` from `InlineReactHoverableHighlight` when `InlineReactVoteContext` was missing also seemed to "fix" the issue, though I think made inline reacts unavailable.  It seems like a safer default than passing in `null` VoteProps to downstream components which break the entire page, but not sure.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208198561870999) by [Unito](https://www.unito.io)
> fix inline react context usage breaking old dialogues

- packages/lesswrong/server/repos/AbstractRepo.ts
- packages/lesswrong/server/repos/index.ts
The main `ResolverContext` type has a property called `repos` of type `Repos` (ie; a map from repo names to repo instances). However, _most_ requests do not use _most_ of the repos, and there's a lot of repos which need to be instantiated for every request. To avoid wasting resources we can instead replace the plain `repos` object with a proxy which intercepts accesses to repos and only instantiates repos as-and-when they're actually needed.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208179772907243) by [Unito](https://www.unito.io)
> Proxy the instantiation of repos

- packages/lesswrong/integrationTests/editorUtils.tests.ts
- packages/lesswrong/integrationTests/fetchFragment.tests.ts
- packages/lesswrong/lib/utils/schemaUtils.ts
- packages/lesswrong/server/fetchFragment.ts
- packages/lesswrong/server/sql/SelectFragmentQuery.ts
Currently, `fetchFragment` only returns resolver-only fields that have SQL resolvers. This PR implements executing the code resolvers for fields without SQL resolvers.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208173461130215) by [Unito](https://www.unito.io)
> Execute code resolvers in `fetchFragment` 

- packages/lesswrong/server/fetchFragment.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208205628277599) by [Unito](https://www.unito.io)
> Fix conflict in `fetchFragment` caused by order of PR merges

- packages/lesswrong/components/posts/PostsPage/LWPostsPageHeader.tsx
the "group types" on LessWrong events were looking slightly off. Changing the alignment from "center" to "baseline" seems to improve it and looks okay in non-event contexts.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208194296794068) by [Unito](https://www.unito.io)
> Fix alignment issues in authorAndSecondaryInfo

- packages/lesswrong/components/editor/EditTitle.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPageTitle.tsx
We changed the default size of post titles, just bringing the editor in line with it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208184398481332) by [Unito](https://www.unito.io)
> Fix EditTitle fontsize on LessWrong

- packages/lesswrong/components/spotlights/SpotlightItem.tsx
- packages/lesswrong/themes/siteThemes/lesswrongTheme.ts
In a previous commit, I made it so that admins could edit spotlights from the frontpage, but accidentally also exposed some metadata.
This PR updates it to properly only shows the editor (which is accessible only if you're an admin)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208218616097032) by [Unito](https://www.unito.io)
> Fix accidental display of spotlight metadata [hotfix]

- packages/lesswrong/components/votes/lwReactions/ReactionHoverTopRow.tsx
If a reaction description used up all of the allocated width, there would be no margin between it and the name of the user who reacted, resulting in a hover that looks like this:
Fix that by converting some of the min-width into margin. https://lworg.slack.com/archives/CJUN2UAFN/p1724707412485539
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208218960307276) by [Unito](https://www.unito.io)
> ReactionHoverTopRow: Guarantee margin between reaction description and user names

- packages/lesswrong/components/contents/SideItems.tsx
- packages/lesswrong/components/linkPreview/FootnotePreview.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208216772429901) by [Unito](https://www.unito.io)
> Don't hide footnote hover if sidenotes are enabled by have no column available

- packages/lesswrong/components/linkPreview/FootnotePreview.tsx
Example affected post: https://www.lesswrong.com/posts/YsFZF3K9tuzbfrLxo/counting-arguments-provide-no-evidence-for-ai-doom
When footnote links don't contain numbering metadata, we find the corresponding `<li>` element in the post footer, count the elements before it in the `<ol>`, and use that as its footnote number. However, if any `<span>`s got mixed into the `<ol>`, they will count as though they were numbered footnotes (even though they don't increment the CSS number counter), causing footnote numbering to be off by one. Fix this by only counting `<li>` elements in that case.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208216710916910) by [Unito](https://www.unito.io)
> Fix off-by-one in sidenote numbering on some posts

- packages/lesswrong/components/comments/SideCommentIcon.tsx
- packages/lesswrong/components/linkPreview/FootnotePreview.tsx
- packages/lesswrong/components/votes/lwReactions/InlineReactHoverableHighlight.tsx
* Inline reaction icons have a smaller hover area (not the full width of the side-item column)
* Fix the spacing of the "Click to pin" text on side-comments
* Inline reactions in comments no longer cause the text to be underlined
* List item bullets in sidenotes no longer have an oversized font
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208233130735022) by [Unito](https://www.unito.io)
> Various bits of polish on side-items

- packages/lesswrong/components/common/ForumIcon.tsx
- packages/lesswrong/components/languageModels/LlmChatWrapper.tsx
- packages/lesswrong/components/languageModels/PopupLanguageModelChat.tsx
- packages/lesswrong/lib/cookies/cookies.ts
Had a user complain that when they wanted to use the LLM chat without caring about the current post, it was annoying/difficult to have the width be so narrow. This PR adds a button to allow for increasing the width of the LLM chat.
(Also changes it so that upon load, a new chat is opened rather than the most recently updated one.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208250100344385) by [Unito](https://www.unito.io)
> Expand button for llm chat

- packages/lesswrong/server/serverStartup.ts
On prod, we have a primary process and two worker processes. If a worker process dies (such as by running out of memory), we previously wouldn't notice this, so if a server lost a worker process this way it would silently lose half its capacity. (Then if it lost its other worker, it would stop being able to service requests at all, and the load balancer would stop sending it any requests.)
NOTE: We (LW) got an error message from AWS that suggests we may be unable to start instances until we complete some sort of account verification. Do not deploy this until that's taken care of. https://lworg.slack.com/archives/C75BWSNBH/p1725557401746459
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208239145980945) by [Unito](https://www.unito.io)
> Auto-restart worker processes when they die

- packages/lesswrong/components/posts/PostsPage/LWPostsPageHeader.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
Fixes the padding of the welcome box.
I think we probably want to do something else with this because I think it shows up on either every lesswrong post for logged out users, or, some high percentage of them in an A/B test, and it kinda ruins the beautiful new page. But, will figure that out later.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208232599224147) by [Unito](https://www.unito.io)
> Welcome box margin top

- packages/lesswrong/server/migrations/20240906T192038.lwevents_ip_index.ts
This avoids an annoying deadlock because we're using `dbOutsideTransaction` (see https://github.com/ForumMagnum/ForumMagnum/actions/runs/10784644922/job/29913276692?pr=9733)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208270159114095) by [Unito](https://www.unito.io)
> Use `void` instead of `await` in lwevents_ip_index migration

- packages/lesswrong/server/repos/PostsRepo.ts
- packages/lesswrong/server/search/elastic/ElasticConfig.ts
I marked a user's post as "unlisted" per request, and I noticed that it still appeared in the search results. I'm guessing that's unintended.
I'm adding a filter on post search results, so sites will need to run `Globals.elasticExportCollection('Posts')` to populate the new field in order for any post search results to appear.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208239740974883) by [Unito](https://www.unito.io)
> Hide unlisted posts from site search

- packages/lesswrong/client/AppGenerator.tsx
- packages/lesswrong/components/dialogues/ActiveDialogues.tsx
- packages/lesswrong/components/vulcan-core/App.tsx
- packages/lesswrong/server/recombee/client.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/components/AppGenerator.tsx
* Save ~30ms of spurious rerendering on front page load by refactoring EnvironmentOverrideContext
* Don't rerender when receiving an active-dialogues server-sent event with no changes in it
* Front-page Enriched recommendations filter the Latest portion to the last 90 days
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208264399669790) by [Unito](https://www.unito.io)
> Performance optimizations

- packages/lesswrong/components/linkPreview/FootnoteDialog.tsx
- packages/lesswrong/components/linkPreview/FootnotePreview.tsx
- packages/lesswrong/components/linkPreview/HoverPreviewLink.tsx
- packages/lesswrong/lib/components.ts
- packages/lesswrong/themes/defaultPalette.ts
- packages/lesswrong/themes/themeType.ts
On large screens, footnotes render as sidenotes. On smaller screens, footnotes have a preview when you hover with a mouse. On _touch_ screens, however, you can't hover, so the only interaction left was that clicking on a footnote would scroll to it in the footer, which kind works but isn't great.
Change it so that when you tap on a footnote on mobile ("mobile" defined according to the `bowser` library, should pretty closely match devices with touchscreens), you get the footnote contents in a modal dialog with a clickaway, rather than scrolling.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208290385662944) by [Unito](https://www.unito.io)
> Better mobile footnotes

- packages/lesswrong/components/tagging/FooterTagList.tsx
Fixes a regression from #9749 (which I missed in code review 😬)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208334809094104) by [Unito](https://www.unito.io)
> Forum gate `annualReviewMarketInfo`

- packages/lesswrong/components/common/ForumIcon.tsx
- packages/lesswrong/components/votes/lwReactions/AddInlineReactionButton.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208298443616758) by [Unito](https://www.unito.io)
> Fix the add-inline-react button on Safari

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/common/TabNavigationMenu/NavigationStandalone.tsx
- packages/lesswrong/components/common/TabNavigationMenu/TabNavigationMenuFooter.tsx
- packages/lesswrong/lib/routes.ts
- packages/lesswrong/lib/vulcan-lib/routes.ts
Makes it so the LW Concepts and Community pages (which are linked to from the bottom-bar) have bottom-bars themselves.
(Note: this UI is forum-gated to LW/AF only. That forum-gating doesn't change in this PR.)
Disentangles the concept of "having standalone navigation", which referred to both having left-side ToC-style navigation options at larger breakpoints, and having a bottom-bar at smaller breakpoints. That didn't work for the Concepts and Community pages, which have their own tables of contents and want the bottom-bar without the ToC-style page navigation.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208278812832940) by [Unito](https://www.unito.io)
> Fix missing navigation footer

- packages/lesswrong/components/linkPreview/FootnotePreview.tsx
Turns on progressive enhancement (ie link previews) in sidenotes, by using `ContentItemBody`. As currently written, this doesn't seem to handle horizontally-scrollable blocks (everything is treated as not-scrollable, even if it's wide enough to get a scroller in the post body). It also doesn't handle inline reactions (if you inline-react to a footnote, it will show up at the bottom of the post, but not near the sidenote).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208337071824453) by [Unito](https://www.unito.io)
> Enable progressive-enhancement inside sidenote bodies; remove backlinkds from some sidenotes

- packages/lesswrong/components/quickTakes/QuickTakesSection.tsx
It said "sorted by recency", now it says "recency and karma"
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208306935927211) by [Unito](https://www.unito.io)
> Fix Quicktakes toooltip

- packages/lesswrong/components/common/ContentItemBody.tsx
User report at: https://www.lesswrong.com/posts/jvewFE9hvQfrxeiBc/open-thread-summer-2024#TfHC5X3aCF8Tg8HRf
Fix tested on Browserstack. Note that this replaces the obvious bug with a more subtle/minor one, which is that elements that _do_ need the scrollers (ie, wide tables/formulas) may not have them, if the tab loaded in mobile Firefox in the background.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208370639032602) by [Unito](https://www.unito.io)
> Fix a bug where on Firefox Mobile, posts opened in background tabs would have spurious horiz scrollers

- packages/lesswrong/components/titles/PostsPageHeaderTitle.tsx
EAF no longer generates a page title on the post page (LW doesn't seem to have this bug). This is especially annoying when linking to a post, because the social preview lacks a title. I'm not sure what caused this bug or when it started, but this PR seems to fix it, and changing the `fetchPolicy` from `cache-only` to the default (`cache-first`) doesn't seem that bad.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208365766907685) by [Unito](https://www.unito.io)
> fix post page titles

- packages/lesswrong/components/common/TabNavigationMenu/NavigationStandalone.tsx
- packages/lesswrong/components/dialogues/CalendlyIFrame.tsx
- packages/lesswrong/themes/globalStyles/miscStyles.ts
While debugging with pause-on-caught-exceptions, I noticed that our CSS minifier, csso, is parsing our CSS (mostly generated from JSS, with a little bit written raw), throwing an exception if there's a syntax error, and then swallowing that exception and continuing. I haven't figured out how to catch these parse errors properly (a unit test would be ideal), but I took the opportunity to fix the extant ones.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208337493126416) by [Unito](https://www.unito.io)
> Fix CSS syntax errors

- packages/lesswrong/components/votes/OverallVoteAxis.tsx
- packages/lesswrong/lib/voting/vote.ts
- packages/lesswrong/lib/voting/voteTypes.ts
- packages/lesswrong/server/callbacks/alignment-forum/callbacks.ts
- packages/lesswrong/server/callbacks/votingCallbacks.ts
- packages/lesswrong/server/voteServer.ts
Simplify AF karma handling. Fix a race condition that would cause votes to be double-counted towards user votes. Fix inversion of afPower in unvotes, which would mess up the karma-change notifier on AF.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208385854001989) by [Unito](https://www.unito.io)
> Fix bugs in AF voting

- .eslintrc.js
- packages/lesswrong/components/books/Book2019FrontpageWidget.tsx
- packages/lesswrong/components/books/Book2020FrontpageWidget.tsx
- packages/lesswrong/components/books/BookFrontpageWidget.tsx
- packages/lesswrong/components/comments/CommentsItem/CommentUserName.tsx
- packages/lesswrong/components/comments/ModerationGuidelines/ModerationGuidelinesEditForm.tsx
- packages/lesswrong/components/community/modules/CommunityMembers.tsx
- packages/lesswrong/components/localGroups/CommunityMapFilter.tsx
- packages/lesswrong/components/localGroups/LocalEventMarker.tsx
- packages/lesswrong/components/localGroups/LocalGroupMarker.tsx
- packages/lesswrong/components/localGroups/LocalGroupsList.tsx
- packages/lesswrong/components/posts/EAPostsItem.tsx
- packages/lesswrong/components/posts/PostsEditForm.tsx
- packages/lesswrong/components/posts/PostsNewForm.tsx
- packages/lesswrong/components/questions/NewAnswerForm.tsx
- packages/lesswrong/components/recentDiscussion/RecentDiscussionSubscribeReminder.tsx
- packages/lesswrong/components/recommendations/PostsPageRecommendationItem.tsx
- packages/lesswrong/components/review/ReviewPhaseInformation.tsx
- packages/lesswrong/components/tagging/FooterTagList.tsx
- packages/lesswrong/components/walledGarden/GardenCodeWidget.tsx
Turns on a lint rule for unstable components, which lose state on rerender. Rather than fix outstanding instances of the warning, this PR just marks them with FIXME and eslint-disable-next-line. I do believe a significant portion of those FIXMEs (though not all) are real bugs.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208393814310407) by [Unito](https://www.unito.io)
> Turn on react/no-unstable-components lint

- packages/lesswrong/components/hooks/useImageUpload.tsx
Someone asked about the min size requirement via Intercom. I don't know of any particular reason we chose 700 as the min width, and I think it's better for these params to be the same as `eventImageId`, so I just changed it to match that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208382591848804) by [Unito](https://www.unito.io)
> decrease social preview img min size

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/common/LWHome.tsx
Restores normal spotlight functionality, and the original side banner.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208423492274345) by [Unito](https://www.unito.io)
> Revert Petrov UI

- packages/lesswrong/lib/voting/vote.ts
- packages/lesswrong/server/scripts/createKarmaAward.ts
We're giving karma awards for Petrov Day 2024. For now, we're implementing a somewhat ad-hoc way of making the award. If we decide to give out more karma-awards later we may build a more dedicated KarmaAwards collection.
The solution here after chatting with @b0b3rt is to make two users who are hardcoded to give higher than usual vote power (100 and 1000, respectively), and then create some votes from them on some secret archived posts for each user.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208424072361637) by [Unito](https://www.unito.io)
> Allow karma awards of 100 or 1000

- packages/lesswrong/components/posts/PostsPage/LWPostsPageHeader.tsx
- packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx
- packages/lesswrong/components/posts/TableOfContents/MultiToCLayout.tsx
Previously: 
Now: 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208442479743102) by [Unito](https://www.unito.io)
> Fix audio player mobile display

- packages/lesswrong/components/comments/CommentPermalink.tsx
> Add Comment Permalink margin to avoid overflow

- packages/lesswrong/server/migrations/20240930T215249.drop_criticismTipsDismissed_from_Posts.ts
- schema/accepted_schema.sql
- schema/schema_changelog.json
Follow up to https://github.com/ForumMagnum/ForumMagnum/pull/9765 where we moved the field to the `Users` table
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208442339835962) by [Unito](https://www.unito.io)
> drop criticismTipsDismissed field from Posts table

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/common/CloudinaryImage2.tsx
LW has a background image in the top-right corner, which is visible only on desktop breakpoints. However, mobile browsers wind up downloading it anyways, because they can't tell that it's going to be hidden until the stylesheet has loaded, but they (usually) see the `<img>` tag before they finish downloading the stylesheet.
Add the attribute `loading="lazy"` to the background image. This defers loading until the image is actually visible. On mobile, where it will never be visible, this saves 615kb of download (cacheable, but quite a lot). On desktop, this delays the start of downloading the background image until later in the loading process--it starts after first paint, rather than when it's first seen in HTML. It doesn't delay first-contentful-paint; in the profiler timeline, the page …
> Avoid loading the LW background image on mobile

- packages/lesswrong/components/posts/PostSubmit.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsList.tsx
- There's reasonably often confusion about Justis' relationship to, for example, moderation decisions, so clarify that copy
- Make it so the curation sidebar links to the draft curation notices list
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208451366515052) by [Unito](https://www.unito.io)
> Some QOL tweaks

- packages/lesswrong/integrationTests/utils.ts
- packages/lesswrong/lib/collections/votes/schema.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/server.ts
- packages/lesswrong/server/callbacks/votingCallbacks.ts
- packages/lesswrong/server/scripts/createKarmaAward.ts
- packages/lesswrong/server/scripts/recomputeReceivedVoteCounts.ts
- packages/lesswrong/server/voteServer.ts
- packages/lesswrong/server/votingGraphQL.ts
There were a couple problems with the createKarmaAward function that Robert and I both missed.
One was that the new autogenerated posts we were creating/upvoting were generating ManifoldMarkets for the LW Review. This seems like a general problem where "draft posts that get 100 karma probably shouldn't get ManifoldMarkets", which I updated here.
I had also previously mistakenly listed the voteType as "upvote" instead of "smallUpvote" or "bigUpvote." At @b0b3rt's suggestion, In the process of fixing this I set the allowed values of the voteType field to be the specific vote types we use so this sort of error wouldn't happen again.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208426153151577) by [Unito](https://www.unito.io)
> fix bugs in createKarmaAward

- packages/lesswrong/components/common/HomeTagBar.tsx
- packages/lesswrong/components/posts/PostsTitle.tsx
- packages/lesswrong/themes/defaultPalette.ts
- packages/lesswrong/themes/themeType.ts
This PR adds some temporary code to style the Forum event tag with a custom gradient. I think we should just plan to undo it after because the baseline code uses the dark and light event colors which seems like a cleaner general solution.
Light mode:
Dark mode:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208472758549619) by [Unito](https://www.unito.io)
> [EA Forum only] use gradients for the tag for the upcoming Forum event

- packages/lesswrong/components/sequences/CollectionsPage.tsx
[Request from Slack](https://cea-core.slack.com/archives/C03R2G12W2K/p1728061504351019): sentence case the title on the collections page (currently only used on the EA Forum for the EA handbook). I also removed the bottom margin from the description as there's already padding on the container, so it looked a bit lop-sided.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208494255311976) by [Unito](https://www.unito.io)
> [EA] Sentence case for collections page title

- packages/lesswrong/server/fmCrosspost/crosspost.ts
[This commit](https://github.com/ForumMagnum/ForumMagnum/commit/5dcec9b19d12315b17a7d555a19074f8d6c15e75#diff-e67d84766759211a6929fccf5cb97fa677a35c528fc380e131481b19da8f25ac) seems to have resulted in a bug which drops any field updates performed by post callback hooks when the post is a crosspost; those updates are only persisted in `data`, which is the "iterator" (not in `newDocument`, which is a snapshot of the post-update document taken at the very start of the `updateMutator`).
One way this bug presented was by making updates to a post appear to mysteriously act as no-ops, because the post contents were being pulled from the `sideCommentsCache`, which only gets invalidated when `modifiedAt` is updated.  And `modifiedAt` is a denormalized field updated via an `onUpdate`.
┆Issue is …
> ensure we keep fields updated by callbacks when updating a crossposted post

- packages/lesswrong/lib/collections/users/helpers.tsx
Currently if you have an emoji in your name (which a lot of people on the EA Forum do, because of the 🔸 pledge diamond), you get an error when trying to create a quick take.
I'm not sure what the original reason was for disallowing emojis in post titles, but here I'm just filtering them out from the quick take post title.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208497921208421) by [Unito](https://www.unito.io)
> Filter out emoji's from Quick Take post title

- packages/lesswrong/components/quickTakes/useQuickTakesTags.ts
This generically allows it for any event which has a tag associated. Which, may not always be what we want but I think will be more often than not.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208500809756801) by [Unito](https://www.unito.io)
> Allow tagging quick takes with the current debate week tag

- packages/lesswrong/components/forumEvents/ForumEventCommentForm.tsx
- packages/lesswrong/components/forumEvents/ForumEventResultIcon.tsx
- Change `useIsAboveBreakpoint("md")` to `useIsAboveScreenWidth(POLL_MAX_WIDTH)` (there is a narrow range where these are different)
- Don't open the reply form when clicking "Go to thread"
- Clear all state from the hover tooltip when it is closed
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208501552566615) by [Unito](https://www.unito.io)
> [EA] Some debate week bug fixes

- packages/lesswrong/components/notifications/CommentOnYourDraftNotificationHover.tsx
- packages/lesswrong/components/notifications/NotificationsMenuButton.tsx
- packages/lesswrong/components/notifications/NotificationsPage/NotificationsPageKarmaChange.tsx
- packages/lesswrong/components/notifications/NotificationsPopover.tsx
- packages/lesswrong/components/notifications/NotificationsPopoverNotification.tsx
- packages/lesswrong/components/notifications/useNotificationsPopoverContext.tsx
- packages/lesswrong/lib/reactRouterWrapper.tsx
This fixes two bugs which were causing the popover to stay open when it should close:
1. Clicks on the notification bell triggered the clickaway listener, which closed the popover, and then triggered the `onClick` of the bell itself which re-opened it. This only happened intermittently and mainly (only?) on mobile. I've wrapped the bell button inside the `LWClickAwayListener` to fix this
2. Not all of the links in the popover closed it when clicked. I've added a `NotificationsPopoverContext` which exposes the `closeNotifications` function to make it easier to handle this in deeply nested components (and used it for all the links that are there)
A lot of the diff is due to changed levels of nesting, so it's probably best viewed side by side. …
> [EA] Fix bugs causing the notifications popover to stay open

- .github/workflows/runTests.yaml
Playwright tests started failing after Ubuntu 24.10 was released yesterday. I tried pinning the version to 24.04, but that was also broken (maybe related to https://github.com/microsoft/playwright/issues/30368) - I have no idea why it worked before. Pinning to 22.04 seems to work fine though, and I don't think there's really any downsides (for now at least).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208529312152495) by [Unito](https://www.unito.io)
> Pin ubuntu version to 22.04 for playwright tests CI

- packages/lesswrong/components/admin/AdminHome.tsx
- packages/lesswrong/components/admin/TwitterAdmin.tsx
- packages/lesswrong/lib/betas.ts
- packages/lesswrong/lib/components.ts
- packages/lesswrong/lib/instanceSettings.ts
- packages/lesswrong/lib/routes.ts
- packages/lesswrong/server/resolvers/postResolvers.ts
- packages/lesswrong/server/twitterBot.ts
This page shows posts that have recently crossed 35 karma, and lets you copy them in a format that can be pasted into [this spreadsheet](https://docs.google.com/spreadsheets/d/1eTwjesImB-LoW3a5p_-bS8zivW5EigEU9ZJt47dHfpw/edit?gid=0#gid=0). This is how I'm planning to track the tweets for the first week or so that I'm running the account manually
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208529110491626) by [Unito](https://www.unito.io)
> [EA] Create admin page to help with manually running the twitter bot

- packages/lesswrong/components/users/UsersProfile.tsx
- packages/lesswrong/lib/collections/posts/views.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208525977387878) by [Unito](https://www.unito.io)
> make sure user profiles don't crash on invalid post sort order query params

- packages/lesswrong/components/notifications/NotificationsItem.tsx
If a comment was a reply to a comment on a tag discussion page, the on-site notification would be lost (it's technically in the DB and makes the bell-icon show a notification number, but the notification itself renders as an empty component).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208506107217200) by [Unito](https://www.unito.io)
> Fix missing comment-reply notifications for comments on tag discussion pages

- packages/lesswrong/components/linkPreview/FootnotePreview.tsx
This was EA Forum specific because LW doesn't have collapse-footnotes enabled.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208581143152027) by [Unito](https://www.unito.io)
> Fix spurious scroll when opening footnotes on mobile

- packages/lesswrong/server/resolvers/postResolvers.ts
I added this because I thought it would be useful to see what posts are coming up, but in practice it's just annoying to not be able to copy the list as is
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208600573055511) by [Unito](https://www.unito.io)
> Remove 5 karma leeway from twitter admin karma cutoff

- packages/lesswrong/components/search/SearchPageTabbed.tsx
- packages/lesswrong/server/repos/PostsRepo.ts
- packages/lesswrong/server/search/elastic/ElasticConfig.ts
- packages/lesswrong/server/search/elastic/ElasticExporter.ts
- packages/lesswrong/server/search/elastic/ElasticQuery.ts
- packages/lesswrong/server/search/elastic/parseQuery.ts
- packages/lesswrong/server/search/searchDocuments.d.ts
Adds `user:name` and `tag:name` syntax to search queries. For both we accept a slug, name or id. Names with multiple words can be entered with quotes like `user:"jp addison"`.
Multiple filters of the same type are OR'd together. Multiple filters of different types are AND'd together.
After deploying, we need to run:
```
./scripts/serverShellCommand.sh "Globals.elasticDeleteIndex('Posts')"
./scripts/serverShellCommand.sh "Globals.elasticConfigureIndex('Posts')"
./scripts/serverShellCommand.sh "Globals.elasticExportCollection('Posts')"
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208571899474226) by [Unito](https://www.unito.io)
> Filter search by user or tag

- packages/lesswrong/server/search/elastic/ElasticConfig.ts
- packages/lesswrong/server/search/elastic/ElasticExporter.ts
We currently use "keyword" but this is limited to 32kb. Trying to index larger documents _throws an exception_ so the document doesn't get indexed at all. The "wildcard" type is similar to "keyword" functionally but has a maximum length a couple of orders of magnitude higher.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208610273521476) by [Unito](https://www.unito.io)
> Use "wildcard" type for the ".sort" field in elastic full text mappings

- packages/lesswrong/server/search/elastic/ElasticQuery.ts
Due to the way that tag names are indexed, the `topic:"Topic Name"` filter is currently case sensitive (I only realised this after reading the forum update post 😬). Thankfully this is easy to fix without reindexing. Usernames are indexed differently so they are already case insensitive.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208621743963048) by [Unito](https://www.unito.io)
> Make the tags search filter case insensitive

- .github/workflows/runTests.yaml
- packages/lesswrong/lib/forumTypeUtils.ts
- packages/lesswrong/lib/utils/schemaUtils.ts
- packages/lesswrong/server/migrations/20241025T181733.fix_ea_forum_default_theme.ts
- schema/accepted_schema.sql
- If a schema default value uses `DeferredForumSelect`, always use the "default" value for the database-level default in postgres (setting the forum-specific values is already handled by `onInsert`)
- Update the SQL schema and add a migration to fix the one field this currently affects (users theme on EA Forum)
- Update `checkCodeGeneration` CI workflow to fail if the SQL schema for EA Forum and LessWrong don't match (see https://github.com/ForumMagnum/ForumMagnum/actions/runs/11523803720/job/32082591746 for a hypothetical failure)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208630221796492) by [Unito](https://www.unito.io)
> Fix forum specific schemas

- packages/lesswrong/components/common/LWHome.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
Posts are currently missing a "text" field which is necessary for Google to take advantage of the structured data, and they were also missing comments, which were easy to add in the current architecture. 
Also imports the structured data generation that the EA Forum has for the frontpage
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208625293694237) by [Unito](https://www.unito.io)
> Update structured data generation for posts and LW frontpage

- packages/lesswrong/lib/collections/posts/annualReviewMarkets.ts
- packages/lesswrong/server/callbacks/votingCallbacks.ts
I haven't tested this but I think it's mergeable if tests pass (it's not so bad if this breaks for a little bit)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208631219390842) by [Unito](https://www.unito.io)
> Tweaks to the Manifold Markets bot

- packages/lesswrong/components/common/withHover.tsx
- packages/lesswrong/components/ea-forum/EASequenceOrCollectionCard.tsx
- packages/lesswrong/components/votes/lwReactions/InlineReactHoverableHighlight.tsx
- packages/lesswrong/components/votes/lwReactions/NamesAttachedReactionsVoteOnComment.tsx
Moves the hover-dialog for inline reacts from the central column to the icon.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208573174440502) by [Unito](https://www.unito.io)
> Hovering inline-reacted text in the central column doesn't highlight it

- packages/lesswrong/server/callbacks/postCallbacks.ts
- packages/lesswrong/server/resolvers/jargonResolvers/jargonTermMutations.ts
We were previously generating explanations for all the terms in parallel, which meant that the prompt caching wasn't doing anything except costing us extra money (ironically).  We now generate one explanation first, which primes the cache for when we generate the rest of the them in parallel.
> fix prompt caching for jargonbot and clean up jargon example params

- packages/lesswrong/components/comments/CommentsItem/CommentBottomCaveats.tsx
- packages/lesswrong/components/editor/RateLimitWarning.tsx
- packages/lesswrong/components/quickTakes/LWQuickTakesCollapsedListItem.tsx
- packages/lesswrong/components/quickTakes/QuickTakesEntry.tsx
- packages/lesswrong/components/quickTakes/QuickTakesSection.tsx
- packages/lesswrong/components/shortform/ShortformThreadList.tsx
- packages/lesswrong/components/users/UsersMenu.tsx
- packages/lesswrong/lib/collections/comments/views.ts
- packages/lesswrong/lib/vulcan-users/permissions.ts
Quick takes can be initiated in three places: (1) the frontpage collapsible quick takes section, (2) the user menu, (3) the quick takes page at /quicktakes
Previously: non-approved users are not shown any of these options, even though it's a good way to get into submitting (perhaps better than posting).
**This PR** makes it so they have these options. In fact, the submission box is shown to logged out users but triggers a log-in popup.
Quick takes submitted for non-approved users will appear only for them, marked as such.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208630308469816) by [Unito](https://www.unito.io)
> New users can quick take

- packages/lesswrong/components/posts/PostsUserAndCoauthors.tsx
Before: 
After: 
I also tested this at other sizes, and sanity-checked the differences between hidden and clip. Seems like we would generally prefer clip.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208651723178392) by [Unito](https://www.unito.io)
> Fix Android mobile author rendering

- packages/lesswrong/themes/siteThemes/lesswrongTheme.ts
Gill Sans Nova rendering seems broken on Windows. Use Calibri ahead of it to patch the problem until we can debug
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208654852372309) by [Unito](https://www.unito.io)
> Bump calibri up font stack

- packages/lesswrong/components/votes/AgreementVoteAxis.tsx
- packages/lesswrong/components/votes/VoteAgreementIcon.tsx
As reported by Sarah, click target was too large. I fixed it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208654044499435) by [Unito](https://www.unito.io)
> fix overly large click target

- packages/lesswrong/components/jargon/GlossaryEditForm.tsx
- packages/lesswrong/components/jargon/JargonEditorRow.tsx
- packages/lesswrong/components/jargon/JargonTooltip.tsx
I made the JargonEditorRow more like a dense glossary than like a postItem, so that it was easier to fit them all on the screen at once. On net, I think this is less overwhelming, although not strictly so.
(this post has more terms than we'd ideally like, which we are also working on cutting down, but, this shows the diff in how it feels for a larger glossary)
Adds icons to the "AI generated"
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208664504944264) by [Unito](https://www.unito.io)
> Streamlined GlossaryEditor, improved Tooltips

- packages/lesswrong/components/posts/PostsPage/LWPostsPageHeaderTopRight.tsx
Tested: The triple-dot menu is now clickable at the relevant screen size; the UI is still underneath all nearby things that it should be underneath, particularly the notifications sidebar, karma notifier popup, and user menu.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208645057903849) by [Unito](https://www.unito.io)
> Fix z-index of the top-right post UI on LW, which made the triple-dot menu unclickable at certain screen widths

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
It can be a bit jarring to post a comment and have it appear halfway down the list, this makes it so your own comments always appear at the top for 1 minute when using magic sorting. The other ways of sorting are too clearly defined for this fudging to be useful.
@jimrandomh @b0b3rt This is currently forum-gated but I could remove that
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208600556211827) by [Unito](https://www.unito.io)
> Show own user's recent comments first when using magic sorting

- packages/lesswrong/components/tagging/AddTag.tsx
Bug reported on slack where wiki only tags are showing up when searching for tags to add to a post. See #7861 for why this fix works.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208665081948043) by [Unito](https://www.unito.io)
> Use `facetFilters` instead of `filters` for `AddTag` wiki filter

- packages/lesswrong/themes/siteThemes/eaTheme.ts
Commit be9dbc077a8c868d760b938317e0dc96865fe8b2 deleted the `footerBar` class from the `NavigationStandalone` component. The EA forum theme has an old override for this class that is now causing an annoying console error on server startup. There's no actualy bug here though since the EA Forum disabled the footer bar a couple of years ago.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208663064913902) by [Unito](https://www.unito.io)
> Remove EA `footerBar` override for `NavigationStandalone`

- packages/lesswrong/server/callbacks/postCallbacks.ts
It was pointed out it wasn't super cool of us to start sending private drafts to LLMs. This reverts the callback for now.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208674133217526) by [Unito](https://www.unito.io)
> Remove jargon callbacks

- packages/lesswrong/components/dropdowns/DropdownItem.tsx
- packages/lesswrong/components/posts/NewDialogueDialog.tsx
- packages/lesswrong/components/users/UsersMenu.tsx
- packages/lesswrong/components/users/UsersProfile.tsx
On LW removed buttons from the long user menu that were not getting any use. We still need some way to make dialogues, so every user profile has a 'dialogue' button to start a dialogue with them. Made bookmarks only appear conditional on having at least 1 bookmark. Also fixed a bug in the menu where the bottom of the g of 'log out' was clipped. Forum gated, shouldn't affect EA Forum menu.
Before and after images here.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208672899210479) by [Unito](https://www.unito.io)
> Reduced size of user menu; added dialogue button to user profile

- packages/lesswrong/components/editor/LocalStorageCheck.tsx
This updates the LocalStorageCheck to look like this:
It uses htmlToTextDefault to convert it, which I'm not too familiar with but seemed to be available on the client.
It looks like `deserializeEditorContents` should automatically handle draftJS and I'm guessing htmlToTextDefault'll work fine with markdown, but I tried for 2 minutes to get markdown into my localStorage and it didn't quite work. My models say it should be fine, I can test harder if people think it's not fine.
I did do a horizontal resize test.
> LocalStorageCheck tells you upfront what text you'll be restoring

- packages/lesswrong/server/apolloServer.ts
Even if we wanted this, we would want to do it via the new EA Forum provided logic
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208625720861492) by [Unito](https://www.unito.io)
> Revert redirect commentID URLs

- packages/lesswrong/components/spotlights/SpotlightItem.tsx
- packages/lesswrong/lib/collections/spotlights/schema.ts
Spotlight items can have their images defined in one of two ways: as a URL, or as a Cloudinary ID. In both cases, there was a risk of using an image that's way too high resolution, slowing down the load time of the front page. Previously, the image for the current spotlight ("The Curse Of The Counterfactual") was 1.3MB.
I edited the URL for that spotlight in the prod DB to give it an explicit width of 500, using Cloudinary's URL syntax (it was entered as a URL rather than as a cloudinary ID). When Cloudinary IDs are used, load them with `w: 500`. Also add `loading="lazy"` to maybe deprioritize loading the image rather than the JS bundle and other things.
The width of 500 is approximate; we don't actually know how big it will be when it's displayed. This is both because of variation in …
> Spotlight images have explicit size, preventing them from being huge downloads

- .platform/nginx/nginx.conf
When I added Cloudfront as a caching proxy in front of an LW development staging server (baserates.org), it resulted in a redirect loop, because some request forwarding within AWS infra was http, even though the external connection was https. Looking at how our http->https redirects work in general, this redirector seems to be redundant; on all of LW, AF, and EA Forum, clients get redirected from http->https before the request gets far enough for nginx to see it; we can tell that the https redirection that's triggering is not this one, because that https redirection uses a 307 status code rather than 301.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208683768193994) by [Unito](https://www.unito.io)
> Remove http->https redirect from nginx config

- packages/lesswrong/components/linkPreview/FootnotePreview.tsx
- packages/lesswrong/lib/utils/rawDom.tsx
Affected test post: http://localhost:3000/posts/53b9woahSTPQFtB2i/notes-on-self-control
`FootnotePreview` was extracting the footnote contents from the DOM in its render function, which has a subtle timing issue: if render functions and effects run in a particular order, it could extract the footnote contents in between when link-previews in the footnotes get replaced by portals, and when previewable-links get rendered into those portals. The practical upshot of which is that on at least one post (but not the majority of posts), sidenotes are missing their links, at least until something causes them to rerender.
Fix this by moving the content insertion in `rawDomNodeToReactComponent` from `useEffect` to `useLayoutEffect`, guaranteeing that it will happen before any `useEffect`s happen, …
> Fix a weird timing-dependent issue where sidenotes could have their links missing

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
Adds a fallback to the schema.org creation if the post content is empty (such as in shortforms)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208682224251137) by [Unito](https://www.unito.io)
> Fix shortform Schema.org

- packages/lesswrong/themes/defaultPalette.ts
- packages/lesswrong/themes/themeType.ts
These palette colours are no longer used (they were added for an event in #9838)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208706493181580) by [Unito](https://www.unito.io)
> Remove old event palette colours

- packages/lesswrong/components/search/UsersSearchAutocompleteHit.tsx
- packages/lesswrong/lib/editor/mentionsConfig.tsx
This unifies Mention mechanism to suggest all different mentionable things when you type `@` as discussed in https://lworg.slack.com/archives/CJY3ZKP62/p1714432896659669
Also adds support for mentioning tags and improves display of user mentions (previously selected items were hard to see)
Demo: https://www.loom.com/share/173c93d928534f6c8715dc73dff82de7 
2 things I mention in the video I’m unhappy about:
1. rn the results are returned in the users > tags > posts order, ideally one would sort them based on relevance or smth, but I’m not sure if I have that information in the search result anywhere?
1. search would return results that are too fuzzy (in this case one probably wants direct name match 95%+ of the time) but probably other things get taken into account and so results are less …
> Unify mention experience to suggest users, posts and tags on `@` 

- packages/lesswrong/server/sqlConnection.ts
I found it quite annoying when there's a lost of Slow Postgres Query warnings on dev servers. I almost never take actions about it.
This PR truncates the response when `isDevelopment` is `true`. If you run into some slow queries on dev you want to debug better you can toggle it back.
It also increases the slow ms threshold somewhat on dev.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208645639301937) by [Unito](https://www.unito.io)
> Truncated "Slow postgres queries" on dev servers

- packages/lesswrong/components/hooks/useLocalStorageState.tsx
- packages/lesswrong/components/jargon/GlossaryEditForm.tsx
Save user-modified jargon bot prompts in local storage.  Also, we now have a hook to manage the pattern of "stick something into localStorage while also handling it as a piece of react state", which comes up sometimes.  It makes the marginally-opinionated choice to clear the value stored in LS if it gets set to whatever the "default" value is, in order to avoid the problem of users making some change and then undoing it, and then getting stuck on the old default in case we ever ship a new one.  (Which we might very well do with JargonBot.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208721580690974) by [Unito](https://www.unito.io)
> save updated jargon prompts in localstorage

- packages/lesswrong/lib/collections/posts/views.ts
A simple syntax error in the post views file was preventing the buffer from working.
This applied to anywhere the posts views 'events' 'nearbyEvents' and 'globalEvents' were called. It's supposed to still return events for a few hours after they've finished, but it wasn't.
—Ben Pace
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208645383686791) by [Unito](https://www.unito.io)
> fixed events not being shown for a few hours after they've finished

- packages/lesswrong/lib/collections/posts/annualReviewMarkets.ts
Turns out you the idempotency key has to be exactly 10 characters
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208730956991326) by [Unito](https://www.unito.io)
> Fix idempotency key

- packages/lesswrong/components/ea-forum/EAGBanner.tsx
- packages/lesswrong/components/ea-forum/EAHome.tsx
A quick PR to show this banner in the week before the EAGxVirtual application deadline. I'll add a task for myself to clean up this code after the deadline, to prep it for the next EAGx deadline ([Singapore](https://www.effectivealtruism.org/ea-global/events/eagxsingapore-2024)).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208730431249259) by [Unito](https://www.unito.io)
> [EA Forum only] show EAGxVirtual banner on home page

- packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
It currently appears above the left-hand-side menu on mobile. I can't remember why I added this z-index, but removing it doesn't _seem_ to break anything.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208726225389601) by [Unito](https://www.unito.io)
> Remove Giving Season banner event text z-index

- packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
- packages/lesswrong/components/forumEvents/useGivingSeasonEvents.tsx
- packages/lesswrong/themes/defaultPalette.ts
- packages/lesswrong/themes/themeType.ts
[Relevant figma](https://www.figma.com/design/3WOTZHH10ZBXSZPWw9omM3/Giving-Season?node-id=1611-1571&node-type=text&m=dev)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208741098245703) by [Unito](https://www.unito.io)
> Add mobile styles for election donation box in giving season 2024 banner

- packages/lesswrong/components/sequences/TopPostsPage.tsx
- packages/lesswrong/lib/collections/spotlights/fragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
Regression from #9742 due to not running `yarn generate`
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208786331208266) by [Unito](https://www.unito.io)
> Fix missing sequence chapters on top posts page

- packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
- packages/lesswrong/components/forumEvents/votingPortal/VotingPortalPage.tsx
- Prevent button overflow on election banner on mobile
- Prevent candidate logos being squished on mobile
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208796297145903) by [Unito](https://www.unito.io)
> More 2024 voting portal tweaks

- packages/lesswrong/components/forumEvents/GivingSeason2024Banner.tsx
- Make the left hand section a little wider so the text fits on two lines
- Show 5 recent discussion items
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208804554084896) by [Unito](https://www.unito.io)
> [EA] Minor tweaks to voting banner

- packages/lesswrong/components/forumEvents/DonationElectionLeaderboard.tsx
- packages/lesswrong/components/forumEvents/useGivingSeasonEvents.tsx
- packages/lesswrong/server/givingSeason/resolvers.ts
It looks like the resolver that calculates the vote counts is using a lot of resources (CPU probably), this adds caching with a 1 min timeout.
Because these are cached independently on different servers this does mean the counts can get out of sync (such that refreshing could give you a different count), but the rate of voting is low enough that I don't expect this to be a problem.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208817445133135) by [Unito](https://www.unito.io)
> [EA] Cache donation election vote counts

- packages/lesswrong/components/comments/CommentsSortBySelector.tsx
- packages/lesswrong/components/comments/RecentComments.tsx
- packages/lesswrong/components/posts/PostsListSettings.tsx
- packages/lesswrong/components/users/UsersProfile.tsx
- packages/lesswrong/lib/collections/comments/views.ts
Makes the user profile page let you sort comments by Magic (New & Upvoted). Also preserve scroll position and don't refresh posts when changing sort mode.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208721645261992) by [Unito](https://www.unito.io)
> User profile page lets you sort comments by Magic (New & Upvoted)

- packages/lesswrong/components/forumEvents/votingPortal/VotingPortalPage.tsx
Requested by Agnes on Slack. Clicking the button to view the comment will automatically save the current vote.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208818537574031) by [Unito](https://www.unito.io)
> Add flash message after successful voting portal comment submission

- packages/lesswrong/components/ea-forum/EAGBanner.tsx
After making [this update](https://github.com/ForumMagnum/ForumMagnum/pull/9994) for EAGxVirtual, I wanted to revert the code back to the standard location-based case. I set it up for EAGxSingapore, which has an application deadline in a few days.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208853819767467) by [Unito](https://www.unito.io)
> [EA Forum only] update EAG banner for EAGxSingapore

- packages/lesswrong/components/posts/PostsPage/PostsPageSplashHeader.tsx
The published date of annual reviews got lost in a redesign. Putting them back.
Before
After
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208730261355839) by [Unito](https://www.unito.io)
> Return "postedAt" to annual review posts

- packages/lesswrong/components/admin/TwitterAdmin.tsx
- packages/lesswrong/lib/collections/posts/fragments.ts
- packages/lesswrong/lib/collections/users/fragments.ts
- packages/lesswrong/lib/collections/users/schema.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/server/migrations/20241203T135759.add_twitterProfileURLAdmin.ts
- packages/lesswrong/server/repos/TweetsRepo.ts
- packages/lesswrong/server/resolvers/postResolvers.ts
- packages/lesswrong/server/twitterBot.ts
- schema/accepted_schema.sql
- Add standard tweet format to the output of the copy action
-  Add a field on users for admins to keep track of their twitter handles
- Use a limit + load more rather than a date cutoff
- Slightly better loading state
I added this section to account settings for keeping track of the twitter handle:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208895046089836) by [Unito](https://www.unito.io)
> [EA] Twitter admin tweaks

- packages/lesswrong/server/type3.ts
From Peter Hartree:
```
I've noticed that EA Forum sometimes sends "regenerate" requests for posts that have just been deleted. For example, we received "regenerate" requests for these in the last 24 hours:
https://forum.effectivealtruism.org/posts/kGkQtj6vjcrrAjK38/despair-about-ai-progressing-too-slowly
https://forum.effectivealtruism.org/posts/vuATadXMheRhBvXfi/sam-altman-safety-and-capabilities-are-not-these-two
https://forum.effectivealtruism.org/posts/CKCtnbu2s3gNzCGh6/tescreal-and-social-justice-a-synthesis
https://forum.effectivealtruism.org/posts/mKKoejaRQCFy4MN7W/cis-fragility
```
I believe the ideal behaviour here would be to delete the posts when they are converted to draft. This PR just prevents the spurious regenerate requests from being sent
┆Issue is synchronized with this …
> Stop sending Type 3 regenerate requests when posts are deleted

- package.json
- packages/lesswrong/lib/reviewUtils.tsx
- packages/lesswrong/lib/types/libraryTypes.ts
- packages/lesswrong/server/resolvers/importUrlAsDraftPost.ts
- yarn.lock
This library was throwing errors in our migrate.ts process, which go away when we switch to using require. I chatted through this with Robert.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208906183358560) by [Unito](https://www.unito.io)
> Change extractus to use "require"

- packages/lesswrong/components/review/AnnualReviewPage.tsx
- packages/lesswrong/components/review/NominationsPage.tsx
- packages/lesswrong/components/review/ReviewsLeaderboard.tsx
This:
– removes the "Reviews" tab during the Nominations phase. It seemed more complex than it was worth. I'll return it during the Discussion phase
– makes it so when you navigate to Voting page it removes all the AllPostPage specific query parameters
– makes it so on the Reviews page it doesn't show the "show more reviewers" if there's less than 10
– adds a larger limit to the All Posts page on Review, and makes sure it's sorted by karma
> Minor Tweaks to Review

- packages/lesswrong/lib/routes.ts
We currently have a bug where an extra 150px of empty space is shown underneath the recommendations sections on event pages and post pages for posts in a group (see attached screenshot). We already remove this space on normal post pages by adding `noFooter: hasPostRecommendations` to the route definition, but it seems we need to add this to all the other routes that use the `PostsSingle` component.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208903566788884) by [Unito](https://www.unito.io)
> Remove footer from all routes using `PostsSingle` component

- packages/lesswrong/components/review/AnnualReviewPage.tsx
I accidentally had made it so you couldn't scroll in the ReviewVoting page left column. This fixes that:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208941665582732) by [Unito](https://www.unito.io)
> Fix Review page left column scrollability

- packages/lesswrong/components/posts/LWPostsByVote.tsx
- packages/lesswrong/components/posts/PostsByVoteWrapper.tsx
- packages/lesswrong/lib/components.ts
I'd merged in some changes to PostsByVote without realizing EA Forum also uses that component.
We're both using it in somewhat opinionated review-y contexts and this seemed like a pretty good time to just split it into two separate components, which we could optimize separately.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208977766339379) by [Unito](https://www.unito.io)
> Forumgate Posts By Vote

- packages/lesswrong/components/forumEvents/votingPortal/VotingPortalPage.tsx
- packages/lesswrong/components/users/FriendlyUsersProfile.tsx
- packages/lesswrong/components/users/UserCommentMarkers.tsx
- packages/lesswrong/lib/collections/users/fragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
I have left the fields for now, they can be cleaned up when we do a big PR to remove everything giving season related
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208967124466733) by [Unito](https://www.unito.io)
> [EA] Remove user flairs from the 2024 donation election

- packages/lesswrong/server/apolloServer.ts
When vite is running the backend is proxied which means we have to enable CORS for API routes to work. Notably, logging in to the EA Forum is currently broken when vite is enabled because of this issue.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208998653377878) by [Unito](https://www.unito.io)
> Fix CORS errors on API routes when vite is enabled

- deployCkEditorBundle.js
Fixes the script to deploy updated ckEditor bundles in a github action when deploying to production.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209011779348913) by [Unito](https://www.unito.io)
> Fix deployCkEditorBundle script

- packages/lesswrong/components/localGroups/CommunityMap.tsx
- packages/lesswrong/lib/collections/users/fragments.ts
- packages/lesswrong/lib/collections/users/helpers.tsx
- packages/lesswrong/lib/collections/users/schema.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
The user-map-markers query on /community had a limit:500, but there are more than that in the DB, so some users would be missing (and adding yourself to the map would appear to fail). Fix that. Also, the download size of the page with the map was pretty chonky (4.3MB), because of the large list of users; solve that by trimming the UsersMapEntry fragment. In particular, the mapLocation field was a Google Maps API object with a bunch of random metadata about the location, but we only need the lat and lng, so make a resolver-only field that returns a minimal version of the location.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208994559672451) by [Unito](https://www.unito.io)
> Fix missing users on the community map, and drastically reduce download of /community

- packages/lesswrong/components/common/BotSiteBanner.tsx
Someone reported that the link to the main Forum site in the banner [here](https://forum-bots.effectivealtruism.org/) is broken, so adding a quick fix for that
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209019780461771) by [Unito](https://www.unito.io)
> [EA Forum only] fix bot site banner link

- build.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209020640373461) by [Unito](https://www.unito.io)
> In production (and when running 'build.ts -run' in general), don't leave an esbuild worker process running and consuming memory

- ckEditor/src/claims.ts
- packages/lesswrong/components/editor/CKPostEditor.tsx
- packages/lesswrong/components/editor/claims/CreateClaimDialog.tsx
- packages/lesswrong/lib/wrapCkEditor.ts
* Add the create-claim button is in the block toolbar, in addition to the selection toolbar
* Wrap claims in the editor in a CkEditor widget
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209057166140397) by [Unito](https://www.unito.io)
> Improve the Claims plugin

- ckEditor/src/claims.ts
- packages/lesswrong/lib/wrapCkEditor.ts
Adds a null check to the claim editor's call to `renderClaimPreviewInto`, in the editing downcast. In theory this should only run in the browser and only with a config that provides that function. In practice, for some reason it was sometimes missing, and an error on that line appeared at https://portal.ckeditor.com/organizations/c91893078825/subscriptions/d583d441fab3/environments?environmentId=rQvD3VnunXZu34m86e5f&environmentView=insights .
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209057368942166) by [Unito](https://www.unito.io)
> Fix crash when using Claims in the collab editor

- packages/lesswrong/components/comments/CommentsItem/CommentOutdatedWarning.tsx
- packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx
- packages/lesswrong/components/comments/CommentsItem/CommentsItemMeta.tsx
- packages/lesswrong/components/comments/CommentsList.tsx
- packages/lesswrong/components/comments/CommentsListMeta.tsx
- packages/lesswrong/components/comments/CommentsListSection.tsx
- packages/lesswrong/components/common/ForumIcon.tsx
- packages/lesswrong/components/common/Header.tsx
- packages/lesswrong/components/common/SearchBar.tsx
- packages/lesswrong/components/icons/SettingsButton.tsx
- packages/lesswrong/components/icons/speakerWaveIcon.tsx
- packages/lesswrong/components/notifications/NotificationsList.tsx
- packages/lesswrong/components/notifications/NotificationsMenu.tsx
- packages/lesswrong/components/posts/PostsItemIcons.tsx
- packages/lesswrong/components/posts/PostsTitle.tsx
- packages/lesswrong/components/sequences/BooksProgressBar.tsx
- packages/lesswrong/components/tagging/AddTagButton.tsx
- packages/lesswrong/components/tagging/FooterTagList.tsx
- packages/lesswrong/components/tagging/TagFilterSettings.tsx
* Fix there being a horiz scrollbar in the notifications menu, and terrible typography of its Load More
* Add a slight hover effect to buttons on the notifications menu
* Fix double-stacked tooltips on the Add Tag Filter button on the frontpage
* Fix the post-audio icon appearing much too bold on Safari when zoomed in
* Refactor ForumIcon, and add a comment explaining Safari icon-size issues
* Fix some (not nearly all) icons being the wrong size in Safari when zoomed in
* Fix a spurious vertical scrollbar appearing on the comments-section sorting line
* UI cleanup of the "Some comments are truncated" notice when on mobile
* Remove excessive top-margin on mobile on "Response to previous version" notice on old Sequences posts
* Fix spelling in "log[]in to trace progress"
┆Issue is …
> A bunch of UI smalls

- packages/lesswrong/components/jargon/GlossarySidebar.tsx
This just removes the number-of-jargon-terms for posts that don't have any approved terms, so it looks less like something you might need to click on.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209062460358330) by [Unito](https://www.unito.io)
> Remove jargonCount for unapproved glossaries

- packages/lesswrong/components/tagging/FooterTagList.tsx
Truncate the post page tags at 1 row instead of 3
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209062542386230) by [Unito](https://www.unito.io)
> [FriendlyUI only] truncate post tags further

- packages/lesswrong/lib/collections/users/helpers.tsx
CKEditor seems to be a good experience on mobile now, so we're removing this override. @b0b3rt happy to not forum-gate this if you want it too
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209002585788353) by [Unito](https://www.unito.io)
> use ckeditor by default for mobile comments

- packages/lesswrong/components/ea-forum/EAHomeRightHandSide.tsx
Adapted from last year (https://github.com/ForumMagnum/ForumMagnum/pull/8590). Separate PR so that we can deploy this after doing some testing on prod, if we want to.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209065480406948) by [Unito](https://www.unito.io)
> 2024 EA Forum Wrapped sidebar ad

- packages/lesswrong/components/ea-forum/onboarding/EAOnboardingUserStage.tsx
- packages/lesswrong/components/posts/PostsAcceptTos.tsx
The "agree to terms of use" checkboxes currently contain a link to the CC-BY **2.0** license, which is an older version of the license; however, the intent of #6029 was to have users agree to license their new content under CC-BY **4.0**.
Legally speaking, IANAL but users may have been agreeing to license their work under the wrong version of CC-BY this whole time (or dual-license under 2.0 and 4.0).
This PR changes all license URLs that were https://creativecommons.org/licenses/by/2.0/ to https://creativecommons.org/licenses/by/4.0/.
Optional cosmetic change: I have also written out "Creative Commons Attribution 4.0" instead of just "CC-BY"; this may be easier to understand for users who are unfamiliar with the jargon of CC licenses.
I think we should also prominently display the CC-BY …
> Correct link to CC-BY license on user flows

- packages/lesswrong/components/editor/ctaButton/EditCTAButtonSettings.tsx
- packages/lesswrong/components/posts/PostsNewForm.tsx
- packages/lesswrong/components/posts/SpreadsheetPage.tsx
- packages/lesswrong/components/revisions/TagPageRevisionSelect.tsx
- packages/lesswrong/components/seasonal/CoronavirusFrontpageWidget.tsx
- packages/lesswrong/components/tagging/PathInfo.tsx
- packages/lesswrong/components/tagging/RandomTagPage.tsx
- packages/lesswrong/components/tagging/RedlinkTagPage.tsx
- packages/lesswrong/components/tagging/SingleLineTagUpdates.tsx
- packages/lesswrong/components/tagging/TagPage.tsx
- packages/lesswrong/components/tagging/TagProgressBar.tsx
- packages/lesswrong/components/tagging/TagTableOfContents.tsx
- packages/lesswrong/components/tagging/TagsTooltip.tsx
- packages/lesswrong/components/tagging/subforums/TagSubforumPage2.tsx
- packages/lesswrong/lib/collections/tags/helpers.ts
- packages/lesswrong/lib/instanceSettings.ts
- packages/lesswrong/lib/notificationTypes.tsx
- packages/lesswrong/lib/routes.ts
- packages/lesswrong/server/callbacks/commentCallbacks.ts
- packages/lesswrong/server/callbacks/votingCallbacks.ts
- packages/lesswrong/server/scripts/arbitalImport/markdownService.tsx
This is accomplished by introducing a new optional instance setting for setting the base url.
As part of this PR, I refactored the tag routing to have less branching (i.e. single main branch that handles all configurations of what tags are named and what the base is.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209079151945853) by [Unito](https://www.unito.io)
> For LW, change the base of tag urls to 'w' from 'tag'

- packages/lesswrong/lib/notificationTypes.tsx
- packages/lesswrong/server/notificationCallbacksHelpers.tsx
- packages/lesswrong/server/wrapped/sendWrappedNotifications.ts
The wrapped notification has no user setting associated with it so it used the default settings which only includes an onsite notification and not an email. This PR overrides this to also send an email to relevant users. I've already sent the notifications on prod, this PR is just for the code.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209098693212612) by [Unito](https://www.unito.io)
> [EA] Fix wrapped notification emails

- packages/lesswrong/components/editor/PostCollaborationEditor.tsx
- packages/lesswrong/lib/collections/posts/schema.tsx
- packages/lesswrong/lib/notificationTypes.tsx
- packages/lesswrong/server/ckEditor/ckEditorWebhook.ts
- packages/lesswrong/server/notificationTypesServer.tsx
If a user leaves a comment on a shared post, and then someone else responds to that comment, the link in the notification going back to the post will be missing the linkSharingKey.  When followed, that link leads to the post collaboration form with no post in it, because:
1. `Posts.checkAccess` thinks the user has access to that post, since they'd been added to the `linkSharingKeyUsedBy` array from when they originally accessed the post,
2. They didn't have access to the `linkSharingKey` because of its read permissions, and so couldn't get redirected to the URL with that key in it by `PostCollaborationEditor`,
3. And therefore couldn't successfully get a token from ckEditor to access to collaborative session with that post. …
> Add linkSharingKey to the link in notifications for comments on draft posts

- packages/lesswrong/components/review/AnnualReviewPage.tsx
- packages/lesswrong/components/review/ReviewPostForm.tsx
- packages/lesswrong/components/review/ReviewVoteTableRow.tsx
- packages/lesswrong/components/review/ReviewVotingExpandedPost.tsx
- packages/lesswrong/components/review/ReviewVotingPage.tsx
I updated the 2-column layout to emphasize writing reviews. I think this is the main point of it.
– clicking the "expand" button now opens up a review box immediately
– it also changes the right column to lower opacity, so you can focus on the Review box
– clicking the comments-icon now opens a regular post-item comment box
> Two column layout emphasizes Reviews

- packages/lesswrong/unitTests/themePalette.tests.ts
Currently the test only checks styles registered through `registerComponent`, not styles that are created by `defineStyles` to be used with `useStyles`.
> Check styles created by `defineStyles` in the theme palette test

- packages/lesswrong/components/common/LWTooltip.tsx
A number of tooltips/popups are clickable. This is often good, because it's nice, for say, a post preview to have clickable links... but also it's annoying, because if you're just trying to move your mouse across a page it can snag on all kinds of random UI elements.
This PR makes it so clickable links take 200ms to become "stable and clickable", which seemed to behave the way I wanted when I experimented with it. We may need to experiment with it a bit in more realistic conditions to figure out the ideal lag time but it seemed like a good starting point.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209121349493967) by [Unito](https://www.unito.io)
> Delayed clickable tooltip

- packages/lesswrong/lib/collections/helpers/arbitalLinkedPagesField.ts
- was using wrong projection argument on mongo find
- introduce specific graphql type so doesn't get erroneously overwritten by cache
> Fix small bugs for Arbital Linked Pages

- packages/lesswrong/components/review/ReviewsPage.tsx
It doesn't work properly because "all" isn't a valid year. I just tried fixing it but actually it just loads crazy slowly and doesn't seem worth supporting it anymore.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209129534480852) by [Unito](https://www.unito.io)
> Remove "all" tab on Review Leaderboard

- packages/lesswrong/server/scripts/arbitalImport/arbitalImport.ts
If the summary is just the start of the main page, we don't need to import that as our preview code will grab it already (and keep it updated to boot)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209145896362200) by [Unito](https://www.unito.io)
> Exclude default summaries from Arbital Import

- packages/lesswrong/components/tagging/ConceptItem.tsx
- packages/lesswrong/components/tagging/TagPreview.tsx
- packages/lesswrong/components/tagging/TagPreviewDescription.tsx
Some hoverovers have no description or a description that doesn't contain the title. We do a basic check for whether the title is present in the description early on, otherwise, display a title (LW only).
This PR also fixes a bug that caused wikitags with no description but erroneously stored wordcounts > 0 from then displaying complete hovers.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209154734399668) by [Unito](https://www.unito.io)
> Restore Titles to Tag Previews and some other preview tweaks

- scripts/deploy.sh
We have hit this a couple of times recently, causing the deployment to appear to fail in GitHub but pass in EB
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209181024530778) by [Unito](https://www.unito.io)
> Increase deployment timeout

- packages/lesswrong/lib/helpers.ts
- packages/lesswrong/lib/random.ts
This fixes a bug where if a user changes their displayName to something unicode-only, resulting in a slug unicode-[ID], their profile page becomes unreachable (because their account's slug has an uppercase character in it, but while the route converts to lowercase).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209258273634202) by [Unito](https://www.unito.io)
> When adding a random ID to resolve slug collisions, don't use uppercase chars

- packages/lesswrong/server/apolloServer.ts
- packages/lesswrong/server/perfMetrics.ts
- packages/lesswrong/server/repos/perfMetricWrapper.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
Poking around in memory dumps, I found that a bounded (but significant) number of `resolverContext` instances were being leaked on startup, which is a problem because `resolverContext` includes a loader-cache which is meant to be ephemeral, and contains a signficant amount of data. The issue is that the internals of the `dataloader` library hold onto a resolved promise, which captures the `Context` that the `DataLoader` class was constructed in, which captures all associated async local storage.
The only thing the `resolverContext` in `AsyncLocalStorageContext` was being used for was as a source of a `trace_id`, put the same `trace_id` is also available via a different, smaller async local storage variable. I checked that the values from these two sources matched, then removed …
> Fix a subtle memory leak caused by putting a resolverContext into async storage

- .platform/nginx/nginx.conf
A user with a very long post got a 413 when saving when their post was a little over 1MB. This just so happens to be the default value of `client_max_body_size` in nginx. I ran an nginx proxy locally using approximately the same config as what we have on our cloud servers, and submitted a post slightly over 1MB in (uncompressed) size, and got the same error. I added `client_max_body_size 10m;` to `nginx.conf` and was then able to submit that post. (Post submission took 17s, which is a bit unfortunate, presumably because of some on-save callbacks that are O(n) in the size of the post.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209113740509841) by [Unito](https://www.unito.io)
> Raise max size of submitted POST requests (and hence max post size) from 1M to 10M

- build.ts
- package.json
- yarn.lock
Switch from using the `source-map-support` library to nodejs's built-in source maps with `--enable-source-maps`, because the built-in source maps use less RAM. This change was attempted before when we were on node 18, but crashed on staging/test servers because, although node 18's builtin source map support uses less RAM in steady-state, during startup it bursts to extremely high memory usage (enough that VM processes ran out and hung in a loop of garbage collecting forever.) I believe node 22 no longer has that problem (watching memory usage in a debugger, I'm able to see the memory usage spike under node 18, and don't see a similar spike in node 22.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209268071031797) by [Unito](https://www.unito.io)
> Switch from "source-map-support" to node builtin --enable-source-maps

- packages/lesswrong/themes/defaultPalette.ts
- packages/lesswrong/themes/globalStyles/globalStyles.ts
In CkEditor dialogues, the font is such that the space reserved for ascenders/descenders is large relative to the line height. This interacts badly with CkEditor side-comments, which add a yellow background highlight to text ranges; the background highlight of each line covers part of the line above it.
The ideal fix would be to create a stacking context and use z-indexes to put all of the text on top of all of the background, as in this stackoverflow thread: https://stackoverflow.com/a/76044890/274472 . However, in order to do this we would need an extra wrapper span inside the .ck-comment-marker span, and that's coming from a part of CkEditor that we don't control, so we have to make do with a less-clean solution. So instead we shrink the highlight vertically by 3px on the top and 3px …
> Fix CkEditor side-comment highlight covering up adjacent lines in dialogues

- packages/lesswrong/lib/collectionUtils.ts
- packages/lesswrong/lib/collections/books/schema.ts
- packages/lesswrong/lib/collections/comments/schema.ts
- packages/lesswrong/lib/collections/conversations/schema.ts
- packages/lesswrong/lib/collections/elicitQuestionPredictions/schema.ts
- packages/lesswrong/lib/collections/gardencodes/collection.ts
- packages/lesswrong/lib/collections/localgroups/schema.ts
- packages/lesswrong/lib/collections/moderatorActions/schema.ts
- packages/lesswrong/lib/collections/posts/schema.tsx
- packages/lesswrong/lib/collections/tagFlags/collection.ts
- packages/lesswrong/lib/collections/tags/schema.ts
- packages/lesswrong/lib/collections/users/schema.ts
- packages/lesswrong/lib/types/collectionTypes.ts
- packages/lesswrong/lib/types/schemaTypes.ts
- packages/lesswrong/lib/vulcan-forms/schema_utils.ts
- packages/lesswrong/lib/vulcan-lib/config.ts
- packages/lesswrong/server/callbacks/commentCallbacks.ts
- packages/lesswrong/server/callbacks/conversationCallbacks.ts
- packages/lesswrong/server/callbacks/jargonTermCallbacks.ts
- packages/lesswrong/server/callbacks/localgroupCallbacks.ts
- packages/lesswrong/server/callbacks/messageCallbacks.ts
- packages/lesswrong/server/callbacks/rateLimitCallbacks.ts
- packages/lesswrong/server/editor/make_editable_callbacks.ts
- packages/lesswrong/server/mutationCallbacks.ts
- packages/lesswrong/server/tagging/tagCallbacks.ts
- packages/lesswrong/server/utils/callbackHooks.ts
- packages/lesswrong/server/vulcan-lib/mutators.ts
Clean up (some) of the technical debt inherited via Vulcan's callbacks system. Removes the global callbacks-namespace (callback names are now limited to only being used in console.logs rather than being semantically meaningful). Merges onEdit with onUpdate, onInsert with onCreate, and newValidate with createValidate. Makes the type signatures of creation callbacks accurately reflect the fact that an _id might not be assigned yet. Rewrites the comments in `callbackHooks.ts` to not be lies.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209210599157677) by [Unito](https://www.unito.io)
> Refactor mutation-callbacks

- packages/lesswrong/components/common/ContentItemBody.tsx
- packages/lesswrong/lib/utils/rawDom.tsx
`toRange` can return a DOM range that, in addition to including the intended text, also includes empty nodes that are adjacent to it. In some cases (eg inline reactions on [this post](http://localhost:3000/posts/8wBN8cdNAv3c7vt6p/the-case-against-ai-control-research)), where two inline reactions touch (the start of one is the end of the next), this can result in the second inline reaction being mispositioned.
Fix by trimming earlier, and fixing a limitation of `reduceRangeToText` that it would only trim by one text element at a time.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209209654759531) by [Unito](https://www.unito.io)
> Fix occasional mispositioned side-items when the end of an inline reaction and the start of another inline reaction touch

- packages/lesswrong/components/review/FrontpageReviewWidget.tsx
- packages/lesswrong/lib/reviewUtils.tsx
The Voting Phase was supposed to end on Feb 1st, with the Results phase ending on Feb 6th, but I accidentally had made the Frontpage widget say the vote ended on the 6th. I'm going to extend it since we didn't do the Final Push yet.
Since I think it was actually kinda crazy to have the review end 6 days into February I'm slightly splitting the difference and setting the end of the voting phase to be the 5th, and will make sure the Voting Wizard goes live tomorrow (Saturday) so there's a reasonable amount of time.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209296388903107) by [Unito](https://www.unito.io)
> Fix LW Review end date

- packages/lesswrong/components/comments/CommentsNewForm.tsx
- packages/lesswrong/components/common/WarningBanner.tsx
- packages/lesswrong/components/ea-forum/EAHomeCommunityPosts.tsx
- packages/lesswrong/components/editor/RateLimitWarning.tsx
- packages/lesswrong/components/posts/PostsEditForm.tsx
- packages/lesswrong/components/posts/PostsNewForm.tsx
- packages/lesswrong/lib/rateLimits/constants.ts
- packages/lesswrong/server/callbacks/userCallbacks.tsx
I noticed when playing around with rate limits that our banner sometimes has incorrect messaging. So I've made it work more like LW's messaging (and added a link to the guide to Forum norms), and slightly cleaned up the UI.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209207223660098) by [Unito](https://www.unito.io)
> [FriendlyUI only] cleanup some rate limit messaging

- packages/lesswrong/components/search/SearchFilters.tsx
In #9879 we changed the schema of post tags in elasticsearch from an array of tag ids to an array or objects with tag `_id`, `slug` and `name` fields to enable searching for topics using a search string. However, we forgot to update the UI facet for selecting tags which is still trying to match the target tag id directly against items in the tag array, instead of checking the `_id` field so all searches return 0 results.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209295391217427) by [Unito](https://www.unito.io)
> Fix filtering for topics from the search UI

- packages/lesswrong/lib/crud/withMulti.ts
- packages/lesswrong/lib/crud/withSingle.ts
Due to a bug in older apollo-client versions (up to 3.6.3), when `skip: true` is passed to `useSingle` or `useMulti`, it returns `loading: true` forever if it was present during SSR. Work around this by enforcing that `loading` is false if `skip: true` is passed. (I will look at upgrading apollo-client separately)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209287157105712) by [Unito](https://www.unito.io)
> Fix a bug that would cause the New Tag page (on LW) to get stuck in a loading state if SSR'ed

- packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx
- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
Because we added a "Results" phase, the trigger for hiding the "review vote" UI on posts stayed up after the voting period was supposed to be over. This fixes that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209338762745749) by [Unito](https://www.unito.io)
> Hide review buttons after voting phase

- packages/lesswrong/components/tagging/TruncatedTagsList.tsx
I noticed this error when hovering over a post title on staging:
Seems like it was caused by https://github.com/ForumMagnum/ForumMagnum/pull/10324? We don't need tags in our post hoverover to be hoverable, because our post hoverover is not clickable. So I reverted the changes in this file and it fixed the issue.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209346435231720) by [Unito](https://www.unito.io)
> [EA Forum only] fix post title hoverovers

- packages/lesswrong/components/votes/lwReactions/InlineReactSelectionWrapper.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209347107481344) by [Unito](https://www.unito.io)
> Fix a bug which, depending on the ordering of component renders and useEffects, sometimes caused the inline-react button to not appear

- packages/lesswrong/lib/collections/reviewWinners/cache.ts
Our previous attempt at filtering review winners didn't actually prevent them from appearing styled fancily on Post Pages. This fixes that filter.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209372047186650) by [Unito](https://www.unito.io)
> Fix ReviewWinner filtering

- packages/lesswrong/components/common/ContentItemTruncated.tsx
- packages/lesswrong/components/posts/PostsHighlight.tsx
- packages/lesswrong/components/revisions/CompareRevisions.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209354283862163) by [Unito](https://www.unito.io)
> Don't show a (false, maybe zero) words-left cout when ContentItemTruncated is limited by height instead of wordcount

- packages/lesswrong/components/spotlights/SpotlightItem.tsx
- packages/lesswrong/unitTests/themePalette.tests.ts
This was using palette colors which invert in dark mode (normally correct), but overlayed on top of an image (which doesn't invert). The result wasn't illegible or anything, but looked kind of ugly.
I forum-gated this change because there was already some forum-gating on the `color` prop for `closeButton`, and I wasn't testing the interaction.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209346058503481) by [Unito](https://www.unito.io)
> Fix the color of the dismiss button on spotlight items, while in dark mode

- packages/lesswrong/components/LWBackgroundImage.tsx
I'm not actually sure what the intended Widescreen version is supposed to look like
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209372921047855) by [Unito](https://www.unito.io)
> Fix background image positioning

- packages/lesswrong/components/tagging/LWTagPage.tsx
- packages/lesswrong/lib/collections/tags/formGroups.ts
- packages/lesswrong/lib/collections/tags/schema.ts
Following the recent changes, the tag edit page had gotten unwieldy. This PR cleans it up by:
- hiding the Tag Flag pills since they're not actually in use by any one
- getting rid of the discussion section since also not really in use and clutters it up
- collapsing the summaries section by default – most pages will not have summaries and I don't think we're really encouraging people to write them
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209381996981152) by [Unito](https://www.unito.io)
> Declutter LW Tag Editing View

- packages/lesswrong/components/linkPreview/HoverPreviewLink.tsx
- packages/lesswrong/components/posts/PostsPage/CollapsedFootnotes.tsx
A post can link to other sections within the same post with `#section_title`, eg the "(more)" links in https://www.lesswrong.com/posts/hnJSm9AmA3dPEzPaC/what-is-malevolence-on-the-nature-measurement-and#Important_caveats_when_thinking_about_malevolence . Add a link hover preview to them (the same preview as when another post linked to the section; it already has support for starting the highlight excerpt at the right section.).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209354409124577) by [Unito](https://www.unito.io)
> Within-page links to post sections have link previews

- packages/lesswrong/components/posts/PostsItemTrailingButtons.tsx
When you're logged out, the triple-dot menu next to post items is hidden (because the stuff inside the menu is all only relevant for logged-in users). But the cursor:pointer style was still there on the spot where the menu would be, even when the menu was omitted. Move styles around to fix that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209345951361486) by [Unito](https://www.unito.io)
> Fix spurious cursor:pointer styles on hidden post-item triple dot menu

- packages/lesswrong/server/scripts/arbitalImport/arbitalImport.ts
...In which case we still import them into the DB as normal, but mark them as deleted, so that in the future when we make it so you can see the history of deleted wiki pages, they will be visible that way.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209404172268839) by [Unito](https://www.unito.io)
> Core-tag-assignments file marks some Arbital pages as excluded from import

- packages/lesswrong/server/sql/SelectQuery.ts
This story starts with noticing that, in the PG performance analyzer on AWS, the following query is in the #1 spot, despite having only 0.08 calls/sec:
```
-- Comments.recentComments(limit)
SELECT "Comments".* FROM "Comments"
WHERE ( "debateResponse" IS NOT TRUE
AND "rejected" IS NOT TRUE
AND (
("authorIsUnreviewed" IS NOT TRUE OR "postedAt" < '2023-04-04T18:54:35.895+00:00')
AND (("deleted" IS TRUE AND "deletedPublic" IS TRUE) OR "deleted" IS FALSE)
)
AND "score" > 0
AND "deletedPublic" IS FALSE
)
ORDER BY "postedAt" DESC NULLS LAST
LIMIT ?
```
This corresponds to the recentComments view; it's used in /allComments and an RSS endpoint. Running EXPLAIN ANALYZE on this reveals that it is indeed a slow query, but performance gets drastically better if you replace `ORDER BY "postedAt" DESC …
> Don't specify "NULLS FIRST"/"NULLS LAST" in PG sort on non-nullable fields

- packages/lesswrong/server/callbacks/commentCallbacks.ts
- packages/lesswrong/server/resolvers/jargonResolvers/jargonTermResolvers.ts
Fetching the site admin account was on the postgres slow query leaderboard, which was dumb. Cache it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209415992376607) by [Unito](https://www.unito.io)
> Speed up jargon-term resolver's check whether terms were bot-generated

- packages/lesswrong/lib/collections/posts/schema.tsx
- packages/lesswrong/server/repos/CommentsRepo.ts
- packages/lesswrong/server/repos/helpers.ts
- packages/lesswrong/server/sql/sqlClient.ts
The reviews resolver field was an n+1 query, which was particularly bad on the top posts page which was fetching hundreds of posts at the same time.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209418678673517) by [Unito](https://www.unito.io)
> Fix n+1 query fetching review comments on top posts page

- packages/lesswrong/components/tagging/AllWikiTagsPage.tsx
- packages/lesswrong/components/tagging/ConceptItem.tsx
- packages/lesswrong/components/tagging/TagPageButtonRow.tsx
- packages/lesswrong/lib/analyticsEvents.tsx
- packages/lesswrong/lib/collections/tags/fragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- fix concept item blank posts tooltip when tag is wikionly but still has some tagrels
- remove tagflags from edit tooltip for LW
- display some tags in the hover preview of core tags
- track search query and clicking on results when searching on Concepts page
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209414416707824) by [Unito](https://www.unito.io)
> Various Minor Wikitag Fixes

- packages/lesswrong/components/tagging/ContributorsList.tsx
- packages/lesswrong/components/tagging/LWTagPage.tsx
- packages/lesswrong/components/tagging/TagDiscussionButton.tsx
- packages/lesswrong/components/tagging/TagPageActionsMenu.tsx
- packages/lesswrong/components/tagging/TagPageButtonRow.tsx
- packages/lesswrong/components/users/LoginPage.tsx
- packages/lesswrong/components/votes/lwReactions/ReactionsAndLikesVote.tsx
- packages/lesswrong/lib/routes.ts
Went through Oli's list:
- Tag page title line-height is too high
- Parens around numbers in the top-right corner is bad
- Icons in the top-right corner have bad spacing
- The triple-dot menu should always be populated (instead hide it if completely empty)
- The last-updated date should be on the same line as the authors (when it fits), and the same font
- The ToC author list should be limited to at most two, with an “et al” or something
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209439178672681) by [Unito](https://www.unito.io)
> Wikitag styling fixes 20250218

- package.json
- yarn.lock
We have been intermittently getting "No data" from datadog tracing, I have talked to support and they suggest upgrading the package could fix it:
>Hi Will,
>
>Thank you for your patience while our engineering team investigated this issue.
>
>They've identified a bug that started in version v5.29+, which matches the behavior you’ve been experiencing. The good news is that a fix for this issue was released yesterday in version v5.36.0 of the tracer.
>
>Could you please upgrade to v5.36.0 and let us know if this resolves the issue? If the problem persists, we’d appreciate a fresh set of debug logs to help us continue troubleshooting.
>
>Let me know how the upgrade goes or if you have any questions!
> Upgrade dd-trace to fix 'No data' bug

- packages/lesswrong/server/datadog/tracer.ts
With [this upgrade](https://github.com/ForumMagnum/ForumMagnum/pull/10446) we lost the ability to filter out specific urls from the request duration metric, so `/api/notificationEvents` is now pulling up the average
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209455294596160) by [Unito](https://www.unito.io)
> Block '/api/notificationEvents' url from datadog

- packages/lesswrong/server/apolloServer.ts
- packages/lesswrong/server/autocompleteEndpoint.ts
- packages/lesswrong/server/clientIdMiddleware.ts
- packages/lesswrong/server/resolvers/anthropicResolvers.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/pageCache.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
We've had a lot of trouble with bots lately, and one unfortunate pattern is our site going down because some bot makes a lot of SSR-eligible requests, which make their way into our internal render queue, but not before the clientIdMiddleware has fired off an insert for each one (or attempted to do so).  With a sufficiently high volume of requests, this results in:
1. our database not being able to keep up with the write load
2. all of our server instances not having any available database connections to serve other traffic, since the overwhelming majority of requests in Node's stack will be bot-driven clientId requests
This PR aims to solve (or at least mitigate) the issue by removing the all-route clientIdMiddleware, and manually applying it to those routes where we actually need it …
> move clientId middleware logic inside of the render queue for SSR requests

- packages/lesswrong/server/utils/callbackHooks.ts
We want to get rid of our mutation callbacks (and replace them with functions that just run in order, probably defined on the collection mutation options).
Step one is to check whether any of them are throwing exceptions that we don't know about, since `ignoreExceptions` is true by default, so any exceptions that are currently being thrown on the non-"async" callbacks are being silently swallowed.  We probably don't want to keep silently swallowing them, but would be good to see what's happening in production before changing that behavior without knowing what's going on.
> Capture exceptions in our callback hooks prior to refactoring

- packages/lesswrong/components/hooks/usePublishedPosts.ts
- packages/lesswrong/lib/collections/posts/views.ts
Before the `wasEverUndrafted` field, we were querying LWEvents to check if a post was ever undrafted (and filtering it out if not) when showing mods which posts a user had, for privacy reasons.  This has scaled poorly (and/or there may have been some recent change which caused that query to behave much worse).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209468247509723) by [Unito](https://www.unito.io)
> switch to using wasEverUndrafted field in mod views for performance reasons

- packages/lesswrong/components/votes/lwReactions/UsersWhoReacted.tsx
Introduced in: https://github.com/ForumMagnum/ForumMagnum/pull/10301/files#diff-67a0ce2a609f1b8291f0880505b1e7e1c5f499b0bf4601b3cbd855b7d4617c68R9
Previous commit made `UsersWhoReacted-usersWhoReactedRoot` a flexbox, which was incorrect because it had two children and didn't actually want those children to flex-size themselves. Fixed by merging them into one child, which is not quite the original behavior but at least avoids fully hiding any data. (The original behavior was that there would be a guaranteed line-break between reacters and anti-reacters. The flexbox behavior tried to put reacters and anti-reacters into two columns, and additionally one of the columns could be near-zero-size. The new behavior just wraps the all together in one long comma-separated list.)
Before:
After: …
> Fix UsersWhoReacted hiding users who anti-reacted due to incorrect layout

- packages/lesswrong/components/ea-forum/wrapped/hooks.tsx
This fixes an import-order dependency in component imports.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209491449527009) by [Unito](https://www.unito.io)
> Don't take components out of the Components proxy on import, wait until actual render

- packages/lesswrong/themes/stylePiping.ts
footnotes right now change the line height in comments in ugly ways. This fixes this. I tested it on a few different pieces of content (both posts and comments), and I didn't see any issues, and saw it only improve things.
Before: 
After:  
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209190549316065) by [Unito](https://www.unito.io)
> Remove lineHeight from sup

- packages/lesswrong/components/tagging/ContributorsList.tsx
Unlike in the header, the contributor et al's users in the hover tooltip were not highlighting contributors when mousing over. 
The relevant spans were missing the handlers.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209492886770668) by [Unito](https://www.unito.io)
> Fix ToC Et Al Contributor Hover Highlighting

- packages/lesswrong/lib/utils/viewUtils.ts
- packages/lesswrong/lib/views/collectionViewSet.ts
Previously, requests with view names that we didn't have registered were just treated like requests that weren't specifying a view.  Some friendly 3rd party clients were using those.  Un-break that.
> No throw on unknown view

- packages/lesswrong/components/tagging/ArbitalLinkedPagesRightSidebar.tsx
Long children in linked pages weren't getting truncated due to a 'fit-content' css property. Now removed. Unclear why it was there (probably I wrote that code though).
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209505297912685) by [Unito](https://www.unito.io)
> fix lack of overflow truncation on tag page right sidebar

- packages/lesswrong/components/common/SingleLineFeedEvent.tsx
- packages/lesswrong/components/tagging/TagRevisionItem.tsx
- packages/lesswrong/components/tagging/history/LensRevisionItem.tsx
- packages/lesswrong/components/tagging/history/TagHistoryPage.tsx
The icons Jim added to cards are helpful on Tag History page in distinguishing history event types, but cause misalignment when those items appear in recent discussion and maybe elsewhere.
This PR makes it so the icons only show on the TagHistoryPage and are "opt in"
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209504166101150) by [Unito](https://www.unito.io)
> Only show tag/lens card Revision Icons on the tag history page

- packages/lesswrong/components/tagging/TagPageButtonRow.tsx
Spacing around the notification button (that only appears on tag pages) was messed up due to extra marginRight coming from MUI styling. Overriden here.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209517647007946) by [Unito](https://www.unito.io)
> Fix tag button row spacing

- packages/lesswrong/lib/collections/users/fragments.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209506386803222) by [Unito](https://www.unito.io)
> Fix issue that sometimes (unclear when) causes errors when loading users for the community-page map

- packages/lesswrong/server/logging.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/pageCache.ts
We had a check that, every 2s, checks the server-process's memory usage, and if it's over a threshold, logs a warning and calls a function `checkForMemoryLeaks`, which checks some global variables for signs of them having grown larger than they're supposed to. It turns out that checking those globals was itself a slow operation, and, since it's all in one uninterruptiple block of CPU time, it noticeably affected P75 latency. And it wasn't actually finding anything to warn about anyways.
Slow the interval from 2s to 10s, and remove the slow part.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209528638185965) by [Unito](https://www.unito.io)
> Remove function checkForMemoryLeaks which was using lots of CPU time in prod

- packages/lesswrong/components/tagging/lenses/LensTab.tsx
BEFORE:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209518108571421) by [Unito](https://www.unito.io)
> fix overflow by wrapping

- packages/lesswrong/components/posts/TableOfContents/LWCommentCount.tsx
- packages/lesswrong/components/posts/TableOfContents/MultiToCLayout.tsx
- packages/lesswrong/components/tagging/LWTagPage.tsx
Tag pages don't have a comment count in the bottom left, making the ToC seem like it doesn't take up the full height. This PR makes this adjustable with a prop into MultiToc
Because the value gets used in a number of places, trying out an approach using css variables.
BEFORE:
AFTER
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209519921348054) by [Unito](https://www.unito.io)
> adjust toc height based on presence of comment count

- packages/lesswrong/components/linkPreview/FootnotePreview.tsx
From Slack:
I have the following bug: Sidenotes on tag pages initially show the footnote number, but after a rerender (when you hover over them, or resize the page), the number disappears
The reason is because getFootnoteIndex uses document.getElementById to find the footnote definition at the bottom of the page, but instead of finding the <li> inside an <ol> that it expects, it finds... an <li> with the same id inside the hidden CkEditor instance that's created to enable quickly switching to the editor, which has a few unexpected extra elements in between that getFootnoteIndex doesn't know how to handle.
---
This solution checks for the correct parent type OL and not DIV
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209504930524397) by …
> fix disappearing footnote number issue on tag pages

- packages/lesswrong/components/tagging/ContributorsList.tsx
- packages/lesswrong/components/tagging/LWTagPage.tsx
previously:
now:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209518898236710) by [Unito](https://www.unito.io)
> fix wrapping behavior of contributor list and last updated

- packages/lesswrong/components/users/FriendlyUsersProfile.tsx
- packages/lesswrong/components/users/UsersProfile.tsx
If a user's `oldSlugs` contains their current `slug` then their profile page enters an infinite redirect loop. This is the symptom but not the cause of #10448.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209537275207472) by [Unito](https://www.unito.io)
> Fix infinite redirect when user `oldSlugs` contains `slug`

- packages/lesswrong/server/callbacks/postCallbacks.ts
- packages/lesswrong/server/search/elastic/elasticCallbacks.ts
- packages/lesswrong/server/serverMain.ts
- packages/lesswrong/server/voteServer.ts
- packages/lesswrong/server/vulcan-lib/mutators.ts
Just getting rid of some more callbacks.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209564715177881) by [Unito](https://www.unito.io)
> Explicitly call elastic sync in create and update mutator

- packages/lesswrong/components/ea-forum/auth/EALoginPopover.tsx
We are deprecating facebook login soon. Disabling new signups means we can export a list of users who are affected without needing to deal with stragglers later.
Note that this doesn't actually disable new signups, if you click the button from the login section it will still sign you up. But the rate of Facebook signups is about 3 a month so I'm hoping this will deter people until we cut it entirely (around ~1st April). I will re-check before removing the connection entirely that there aren't any new signups
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209596547100068) by [Unito](https://www.unito.io)
> [EA] Remove Facebook option from signup form

- packages/lesswrong/components/ea-forum/auth/EALoginPopover.tsx
This is to monitor for new errors that occur as a result of:
- Cutting Mongo
- Cutting Facebook login
I have created an [alert](https://centre-for-effective-altruism.sentry.io/alerts/rules/ea-forum/15843318/details/) in Sentry to forward errors to the #forum-auth-errors Slack channel
> [EA] Log detailed sentry exception when error occurs during signup

- packages/lesswrong/server/sql/sqlClient.ts
- packages/lesswrong/server/sqlConnection.ts
- packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
At the end of an SSR, there's an event "ssr" (sent to analytics db and also logged in the console) with a "timings" field. The timings in that field were prerenderTime, renderTime, and totalTime; but the prerender/render distinction doesn't actually make sense with our current setup, so this is really only provides a wall-time measurement. It'd be nice to have something more granular, particularly for when doing local development and optimizing.
Replace the timings with wallTime, cpuTime, and sqlBytesDownloaded. These represent the time from request start to completion, time spent not idle (ie, excluding database round trips), and size of (JSON stringified) database query result sets. Note that sqlBytesDownloaded does not account for compression and does not account for the actual wire …
> Improve metrics for time spent on SSR

- package.json
- packages/lesswrong/server/example.ts
- packages/lesswrong/server/logging.ts
- packages/lesswrong/server/serverMain.ts
- scripts/repl.ts
* yarn repl [script] quits properly if the script fails
* Don't send `serverStarted` event to analytics DB when creating a REPL
* Suppress the nodejs warning about punycode
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209616339478360) by [Unito](https://www.unito.io)
> Improve some things about the `yarn repl` command

- packages/lesswrong/components/forumEvents/ForumEventPoll.tsx
- packages/lesswrong/lib/collections/forumEvents/fragments.ts
- packages/lesswrong/lib/collections/forumEvents/schema.ts
- packages/lesswrong/lib/domParser.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/defaultFragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/server/migrations/20250312T131725.add_pollQuestion.ts
- schema/accepted_schema.sql
This allows admins to set the question with an editable field, where footnotes are then parsed into tooltips when rendering. The color used is "Accent color" in the form
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209655227498811) by [Unito](https://www.unito.io)
> [EA] Allow setting the question on polls

- packages/lesswrong/server/migrations/20250314T160703.update_fm_get_user_profile_updated_at.ts
Missing migration from PR #10522 which updated the function source
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209682108438930) by [Unito](https://www.unito.io)
> Add migration to update `fm_get_user_profile_updated_at`

- packages/lesswrong/server/migrations/20250314T190647.updateSqlFunctions.ts
Fixes breakage in https://github.com/ForumMagnum/ForumMagnum/pull/10522/files#diff-bc5842cb5e475c1a328750d4d17c1201eb3156b26307a1d64b213fc105f7239d, (field-changes table) which updated a SQL function but didn't call `updateFunctions`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209683777697274) by [Unito](https://www.unito.io)
> Add a migration that updates SQL functions

- packages/lesswrong/components/common/ContentItemBody.tsx
- packages/lesswrong/components/common/ErrorBoundary.tsx
- packages/lesswrong/components/common/withErrorBoundary.tsx
- packages/lesswrong/components/editor/Editor.tsx
- packages/lesswrong/components/forumEvents/ForumEventSticker.tsx
- packages/lesswrong/components/forumEvents/ForumEventStickers.tsx
- packages/lesswrong/components/peopleDirectory/peopleDirectoryColumns.ts
- packages/lesswrong/lib/analyticsEvents.tsx
- packages/lesswrong/lib/vulcan-lib/components.tsx
This PR attempts to make the React component debugger more usable (and maybe improve performance a bit) by reducing the number of unnecessary and anonymous HoCs in our component tree. In particular, there are many copies of `forwardRef` (outnumbering all other components combined), despite the fact that we only have two components (`ContentItemBody` and `Editor`) that can take a ref.
Remove `forwardRef` from most places where it isn't needed. Also give some anonymous HoCs names.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209632756591460) by [Unito](https://www.unito.io)
> Reduce excessive HoCs

- .github/workflows/deployEABeta.yaml
I have just scaled it down to save some money, adding this comment so the next person to use it isn't confused
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209711893744977) by [Unito](https://www.unito.io)
> [EA] Add comment about scaling beta site up and down

- packages/lesswrong/components/forumEvents/ForumEventPoll.tsx
To avoid one lonely word on the last line I increased the max-width slightly. Also slightly decreased the line-height.
**Before**
**After**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209712146042625) by [Unito](https://www.unito.io)
> Small tweak to debate week banner

- packages/lesswrong/lib/collections/conversations/views.ts
It's pretty annoying to have my LW inbox filled with moderator messages (from rejection DMs). This PR removes those (you can still get them in the `/moderatorInbox`. 
I'm not 100% sure if this affects EA Forum or not.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209706283062564) by [Unito](https://www.unito.io)
> Make default inbox exclude moderator messages

- packages/lesswrong/components/admin/CurationPage.tsx
- packages/lesswrong/components/recommendations/RecommendationsPageCuratedList.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsItem.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsList.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineSidebar.tsx
Thought I'd experiment with keeping the curation list a bit more visible when a curation isn't urgent, but we don't have any curation notice drafts
Also removes the curation button if it's not needed, in order to avoid people getting confused
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209683391690680) by [Unito](https://www.unito.io)
> Show curation sidebar when no curation drafts

- packages/lesswrong/lib/collections/users/schema.ts
- packages/lesswrong/server/migrations/20250225T125732.migrate_notification_format.ts
- packages/lesswrong/server/sql/PgCollection.ts
- packages/lesswrong/server/sql/Query.ts
- packages/lesswrong/unitTests/sql/SelectQuery.tests.ts
This will be against master once #10466 is merged
Notifications defaults changed for EAF:
- `notificationCommentsOnSubscribedPost` (newComment): realtime onsite, no email -> realtime onsite, daily by email
- `notificationRepliesToMyComments` (newReplyToYou): realtime onsite, no email -> realtime onsite, realtime by email
- `notificationRepliesToSubscribedComments` (newReply): realtime onsite, no email -> realtime onsite, daily by email
- `notificationKarmaPowersGained` (karmaPowersGained): realtime onsite, no email -> realtime onsite, realtime by email
@darkruby501 @Discordius lmk if you want to adopt any of these so I can remove the forum gating in those cases
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209498853393689) by …
> Migrate notification settings to new format, and update EAF defaults

- packages/lesswrong/lib/collections/comments/views.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209759253794939) by [Unito](https://www.unito.io)
> Fix crash due to empty $and in sunshineNewCommentsList

- packages/lesswrong/components/posts/PostsPage/PostsPageWrapper.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209706586376040) by [Unito](https://www.unito.io)
> Fix double-fetch of comments when navigating to a post page

- packages/lesswrong/lib/collections/posts/newSchema.ts
This was fixed but the fix was accidentally reverted by the schema-refactoring PR.
> Fix ability for users with custom moderation guidelines to create posts

- packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsList.tsx
During the "make SuggestCuration more noticeable" PR, it got this padding which made it stop matching the spacing that the rest of the sidebar had (which had some side effects of being more squished and also making it harder to mouse over the hoverover)
This removes that padding:
Old:
New:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209829755577684) by [Unito](https://www.unito.io)
> Remove incorrect padding for SuggestCuration list

- packages/lesswrong/lib/collections/multiDocuments/newSchema.ts
- packages/lesswrong/lib/collections/tags/newSchema.ts
One of the schema refactors involved using the new `outputType` as the default `inputType`.  Summaries previously had a required `graphQLtype` specified on their `resolverOnlyField` which got translated to that output type, but the initGraphQL logic wasn't treating that as an input type (in truth I'm not sure what the previous input type even was...).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209829771036858) by [Unito](https://www.unito.io)
> allow tags and multidocs to be created without requiring them to have summaries immediately

- packages/lesswrong/server/vulcan-lib/apollo-server/initGraphQL.ts
All recommendations are currently broken because the graphql resolvers don't get registered anywhere. Weirdly, there's no console error says the resolver can't be found - it just silently fails.
> Register missing recommendations graphql resolvers

- scripts/startup/autoRefreshServer.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209821086254315) by [Unito](https://www.unito.io)
> Fix an occasional crash in build script when auto-refresh connection closes while waiting for server to start

- packages/lesswrong/components/ea-forum/auth/EALoginPopover.tsx
- packages/lesswrong/lib/publicSettings.ts
- Adds a warning message encouraging people to switch login methods when attempting to use Facebook login
- There is an option to proceed to Facebook login anyway
- It is set up to remove Facebook as an option entirely on 7th April
In the email we sent to users we said it would be removed on the 2nd April, so this gives them a bit of leeway.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209828154278976) by [Unito](https://www.unito.io)
> [EA] Add warning notice about Facebook login being removed

- packages/lesswrong/server/loot/unlocks.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209863661433989) by [Unito](https://www.unito.io)
> Don't get inventory based on clientId for users that are logged in

- migrate.ts
- packages/lesswrong/server/migrations/20250225T125732.migrate_notification_format.ts
Needed to run it outside of a transaction (by changing `.tx` to `.task` in `migrate.ts`) even so, since it was otherwise locking the Users table for the duration of the script (~3 minutes).
> improve performance of notification format migration on lw

- packages/lesswrong/components/dropdowns/posts/SharePostSubmenu.tsx
The post triple-dot menu uses `navigator.canShare` to determine whether it has sharing Intents (ie, whether this is a phone where non-browser apps have registered intent handlers for sharing URLs). The intended behavior is that on a phone, clicking the Share button in the post triple-dot menu sends an intent, while on desktop, it opens a submenu with Copy Link and other options. However, `navigator.canShare` is a function, not a boolean, so this tried to use the mobile case on desktop (which didn't work).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209779066189669) by [Unito](https://www.unito.io)
> Fix the Share button in the post triple-dot menu doing nothing

- packages/lesswrong/components/posts/PostsPage/PostsPageWrapper.tsx
A previous performance optimization accidentally caused us to not load comments in the case where we already had the post preloaded and the query view terms between PostsPageWrapper and PostsPage were the same.  (`eagerPostCommentTerms` had a `postId` in the terms passed down to `PostsPage`, while the terms defined in `PostsPage` didn't _until_ users switched comment sorting.)
Now we just don't pass through `eagerPostComment` if we've skipped loading them, so there's no way we'll try to "use" a skipped query result.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209876619464301) by [Unito](https://www.unito.io)
> ensure we don't skip loading comments when a user changes the sorting

- packages/lesswrong/components/posts/PostsNewForm.tsx
- packages/lesswrong/lib/collections/revisions/newSchema.ts
- packages/lesswrong/lib/editor/make_editable.ts
Fix two issues with duplicating events:
1. the change to autocreate posts led to an issue where we were passing in the entirety of editable fields back into a useCreate, which failed simpleSchema validation
2. non-admin group organizers (incorrectly) didn't have permissions to read the originalContents of posts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209877567215397) by [Unito](https://www.unito.io)
> Fix broken event duplication

- package.json
- packages/lesswrong/client/useCkEditorInspector.ts
- packages/lesswrong/components/editor/CKPostEditor.tsx
- packages/lesswrong/lib/types/moduleTypes.d.ts
- packages/lesswrong/stubs/client/useCkEditorInspector.ts
- yarn.lock
This integrates the CkEditor inspector, and opens it when you press Ctrl+Shift+D while on a post page.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209804538724346) by [Unito](https://www.unito.io)
> Add hotkey Ctrl+Shift+D to open the CkEditor Inspector

- packages/lesswrong/server/recommendations/MoreFromAuthorStrategy.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209890442182736) by [Unito](https://www.unito.io)
> Fix duplicate recommendations in the "More from [author]" section on post pages, when the recommended post has coauthors

- packages/lesswrong/lib/notificationTypes.tsx
- packages/lesswrong/server/callbacks/commentCallbackFunctions.tsx
- packages/lesswrong/server/notificationTypesServer.tsx
We received some complaints from users who were confused about indirect replies using the wording "replied to you", this changes the wording to "replied to a thread you're in..." in those cases.
Note that I haven't tested actually sending the emails, because I have only changed the subject line.
Notification popover:
Emails (note only the subject line has changed):
Notifications page (there was a separate bug in this before, where it said `your <a>comment</a>` in the blurb but actually linked to the reply):
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209872896122292) by [Unito](https://www.unito.io)
> Distinguish between direct and indirect replies to threads

- packages/lesswrong/components/hooks/useStyles.tsx
- packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx
- packages/lesswrong/components/posts/TableOfContents/TableOfContentsDivider.tsx
- packages/lesswrong/components/posts/TableOfContents/TableOfContentsRow.tsx
- packages/lesswrong/server/styleGeneration.tsx
One of the obstacles to refactoring is that, when moving components around, there's a possibility of sneaky references to their stylesheet that weren't covered by the type system, in the form of styles that refer to `& .ComponentName-className`. This is particularly an issue with material-UI components, but also happens elsewhere.
This commit introduces an idiom for doing this in a type-safe way, with a type-only import. You define styles with `defineStyles` (it must be the hook version, not the HoC version), export the type of the styles, then in a stylesheet use
`.getClassName<StyleType>("ComponentName", "ClassName")`
This typechecks iff the mentioned styles have the right name and have a class by that name. …
> Make an idiom for type-safe cross-file classname references

- packages/lesswrong/components/posts/PostsPage/BestOfLessWrong/BestOfLessWrongAnnouncement.tsx
- packages/lesswrong/lib/collections/reviewWinners/views.ts
- packages/lesswrong/unitTests/themePalette.tests.ts
BestOfLessWrongAnnouncement had some colors that (incorrectly) changed in darkmode. This hardcodes them to always be the same.
Also, fixes some of the essays that were incorrectly listed as top-3 winners in their category.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209943739603874) by [Unito](https://www.unito.io)
> Fix colors and essays for BestOfLessWrongAnnouncement

- packages/lesswrong/components/posts/PostsPage/BestOfLessWrong/BestOfLessWrongAnnouncement.tsx
- packages/lesswrong/themes/createThemeDefaults.ts
This 
– adds a couple small improvements to the mobile styling
– adds a link to the Voting Results post
– updates the title to use a grey color that will properly invert in darkmode. (I think typography.title should have this across-the-board, but was scared to update it without doing more comprehensive testing than I have time for)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209952896029469) by [Unito](https://www.unito.io)
> BestOfLessWrongAnnouncement style + link update

- packages/lesswrong/lib/crud/cacheUpdates.ts
When you perform an update mutation, we have some code that attempts to find and update queries that would be affected by the change. However, if there is a query that would be affected by the change and it's still in an initial loading state, this crashes with a null-reference exception.
In practice this doesn't come up often, but one repro is that if you're logged in as a moderator and you open the notification tray while the Sunshine Sidebar new users list is loading, it will console-log an error and fail to clear your notification count.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209956367210344) by [Unito](https://www.unito.io)
> Fix Apollo error when updating cache entry or a query that is in an initial loading state

- packages/lesswrong/server/resolvers/defaultResolvers.ts
Views take an "offset" fragment for pagination, which skips the first N results. This is handled in performQueryFromViewParameters, but was not handled on the other branch in the default multi resolver. This isn't used in our own client code, but it is used by GreaterWrong, which uses it when fetching comments on posts after the first 500.
The symptom of this not working was that GW would fetch the first 500 comments on a post with more comments than that, ask for the next 500 comments and get the same 500 comments back, conclude that getting 500 meant there must also be a third page, and repeat until it eventually runs into an "Exceeded maximum value for skip" error.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209956460638780) by …
> Fix the "offset" option on views using compiled fragments

- packages/lesswrong/lib/collections/users/newSchema.ts
- packages/lesswrong/lib/generated/databaseTypes.d.ts
- packages/lesswrong/lib/generated/defaultFragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/lib/generated/fragments.gql
- packages/lesswrong/lib/generated/gqlSchema.gql
Adds a graphql resolver for the "profile" field, mainly so that issarice's reader doesn't clutter Sentry by making lots of requests involving a field it can no longer read.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209956389209329) by [Unito](https://www.unito.io)
> Add a graphql field resolver for "profile"

- packages/lesswrong/components/jargon/utils.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209973642393712) by [Unito](https://www.unito.io)
> Fix an infinite loop crash when glossary contains empty-string as a jargon term

- packages/lesswrong/lib/collections/revisions/newSchema.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209994903350058) by [Unito](https://www.unito.io)
> add resolvers for now-required revision fields which might be missing values in denormalized revisions

- build.ts
Workaround for intermittent downtime we are seeing on prod at the moment. I have set this to 30 mins (1800s) in the prod environment
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209996264189918) by [Unito](https://www.unito.io)
> [EA] Add envvar to trigger periodic restart of server

- build.ts
Merges #10746 into master, which will have no effect for LW if they don't have the `RESTART_INTERVAL` envvar set
Done as a cherry-pick to avoid a confusing commit history
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210012014968584) by [Unito](https://www.unito.io)
> [EA] Merge ea-deploy into master

- packages/lesswrong/components/widgets/Paper.tsx
- packages/lesswrong/components/widgets/TableCell.tsx
- packages/lesswrong/themes/createThemeDefaults.ts
- packages/lesswrong/themes/siteThemes/lesswrongTheme.ts
Fixes bug introduced in #10694. The symptom I found was the tables in the post analytics page looking off. Before/after of that:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210013117918732) by [Unito](https://www.unito.io)
> Re-apply lost theme overrides from MUI migration

- packages/lesswrong/lib/collections/posts/views.ts
- packages/lesswrong/server/emailComponents/PostsEmail.tsx
Event emails were broken by #10515, because that PR switched the email from using a `useSingle` to a `useMulti`, and the default view for posts filters out events.
This PR adds a term `exactPostIds`, when given this removes all other selectors from the default view so that the result is the same as if several `useSingle`s had been used (i.e. only filtering based on access checks)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1209989444903009) by [Unito](https://www.unito.io)
> Fix event emails

- packages/lesswrong/components/ea-forum/InstagramLandingPage.tsx
For easier management, I'm moving the post list over to a sequence. I think this is low risk so I'll plan to just merge it in at my EOD even with no code review.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210016043236330) by [Unito](https://www.unito.io)
> [EA] move IG posts over to a sequence

- packages/lesswrong/components/ea-forum/digest/EditDigest.tsx
- packages/lesswrong/components/ea-forum/digest/EditDigestTableRow.tsx
- packages/lesswrong/lib/collections/digests/helpers.ts
- packages/lesswrong/server/resolvers/postResolvers.ts
The backend can return null for digest post ids, but the frontend assumed they were always defined. The recent refactors turned this into a graphql error, and fixing this led to an avalanche of type errors that needed to be fixed as well.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210055564821419) by [Unito](https://www.unito.io)
> Fix nullability errors on digest edit page

- packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
Before/after:
The acute motivation for this is that I expect some people will create posts containing only polls, in which case we want them to fill out the full space
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210058520720442) by [Unito](https://www.unito.io)
> [EA] Make posts always fill full width

- packages/lesswrong/components/common/TabNavigationMenu/TabNavigationItem.tsx
- packages/lesswrong/components/dropdowns/DropdownDivider.tsx
Fixes several places where padding has been broken by recent MUI refactors:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210055828618358) by [Unito](https://www.unito.io)
> [EA] Fix missing MUI padding

- packages/lesswrong/components/common/MixedTypeFeed.tsx
- packages/lesswrong/components/ultraFeed/UltraFeed.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedPostItem.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedSettings.tsx
- packages/lesswrong/components/ultraFeed/ultraFeedSettingsTypes.ts
- packages/lesswrong/lib/generated/gqlSchemaAndFragments.gql
- packages/lesswrong/lib/generated/inputTypes.d.ts
- change network policy to avoid refreshing ultrafeed on navigate and back
- post titles can still be right- and middle-clicked even when being buttons for opening modals
- post titles opening modals now has a setting
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210087018151869) by [Unito](https://www.unito.io)
> Fix ultrafeed back navigation AND improve post title modal behavior

- packages/lesswrong/components/tagging/subforums/SubforumSubforumTab.tsx
Introduced here: https://github.com/ForumMagnum/ForumMagnum/commit/3814cb88219c20caf7bb90ec8f7a811016ced4f6#diff-60330ed47a029f73ab3e90855b949280e3686de0b3452282953e7465c980d35f
Subforums on the EA Forum now means the pages for the core topics, which are more focused on new posts than on the wiki article.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210102340130666) by [Unito](https://www.unito.io)
> [EA] Hotfix for broken subforum pages

- packages/lesswrong/components/forumEvents/ForumEventPoll.tsx
Based on the suggestion from Will A [here](https://forum.effectivealtruism.org/posts/pAYSK7voaNeDRDFCs/diy-debate-week-april-28-may-4th?commentId=G7C2AgpCFNEvhRMrv)
> [EA] Change from 9 to 10 buckets per side on polls to make agree % more readable

- packages/lesswrong/components/alignment-forum/AFApplicationForm.tsx
- packages/lesswrong/components/common/FlashMessages.tsx
- packages/lesswrong/components/common/hocTypes.ts
- packages/lesswrong/components/common/withMessages.ts
- packages/lesswrong/components/localGroups/CommunityHome.tsx
- packages/lesswrong/components/widgets/Snackbar.tsx
Fixes an issue introduced by material-UI refactoring, where the timer that closes the messages snackbar causes rerendering of the page, even when the snackbar isn't open.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210095012052351) by [Unito](https://www.unito.io)
> Rewrite Snackbar animation/timers to avoid spurious rerenders

- packages/lesswrong/components/linkPreview/FootnotePreview.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210212055377332) by [Unito](https://www.unito.io)
> Fix missing numbering of footnote side-items when post is Markdown and uses [^N] syntax

- packages/lesswrong/client/apolloClient.ts
- packages/lesswrong/client/start.tsx
When you load an SSRed page, there's an apollo-client cache included at the end, containing the results of all queries used in that page, which is used during hydration. We want queries that are in the cache to not then make network requests, even if they have a fetch mode of `cache-and-network` (cache-and-network is a fetch mode that would follow up with a network request, but which is intended for client-side navigation, not for SSR).
In order to prevent unnecessary extra network requests, we set the `disableNetworkFetches` option on apollo-client, and then unset it after hydration. At some point, this stopped working--most likely with the React 19 upgrade, but it might have been earlier. This doesn't slow down the time until the page is displayed, but does waste some bandwidth and …
> Prevent apollo-client from double-fetching queries that are in the preloaded cache after SSR

- packages/lesswrong/server/callbacks/messageCallbacks.ts
- playwright/crossposts.spec.ts
Previously, this worked either because we were passing in `currentUser` to the `updateMutator` that updated the conversation, or because we were skipping validation and `flagOrBlockUserOnManyDMs` (which threw an error for me when I sent a message to a conversation I wasn't a participant in) was a validation callback.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210231941863632) by [Unito](https://www.unito.io)
> Pass through the logged-in user's context when adding a new user to a conversation after they send a message

- packages/lesswrong/components/comments/CommentsEditForm.tsx
The recent form refactor forgot to include `fetchPolicy: 'network-only'` in at least one place where users might actually edit the same form more than once without refreshing the page (comments).  This might also be good to include for some other forms, but this is the most critical one (it's already set properly for posts).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210255846236910) by [Unito](https://www.unito.io)
> fix stale comments on edit

- package.json
On node v22.9.0 I was getting this error:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/wh/Documents/code/ForumMagnum-vite/node_modules/@stylistic/eslint-plugin-ts/dist/index.js from /Users/wh/Documents/code/ForumMagnum-vite/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported.
Instead change the require of index.js in /Users/wh/Documents/code/ForumMagnum-vite/node_modules/@eslint/eslintrc/dist/eslintrc.cjs to a dynamic import() which is available in all CommonJS modules.
at TracingChannel.traceSync (node:diagnostics_channel:315:14)
at ConfigArrayFactory._loadPlugin (/Users/wh/Documents/code/ForumMagnum-vite/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3433:42)
at /Users/wh/Documents/code/ForumMagnum-vite/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3304:33
at …
```
> Pin node version to fix ERR_REQUIRE_ESM error

- packages/lesswrong/components/messaging/MessagesNewForm.tsx
Before/after, this was broken at some point in [this](https://github.com/ForumMagnum/ForumMagnum/pull/10845) set of changes:
> [EA] Fix messages form styling

- packages/lesswrong/components/comments/CommentForm.tsx
Oops.  I'd previously been stripping out the `af` property from being submitted based on whether we were showing the `af` checkbox on LessWrong, as a proxy for whether users had permission to create/modify that field, but that obviously omitted the case where the comment was being submitted on the AF directly.
> don't strip out the af property if the comment is being submitted while on the alignment forum

- deployCkEditorBundle.ts
- package.json
- packages/lesswrong/components/common/ReCaptcha.tsx
- packages/lesswrong/components/ea-forum/auth/EALoginPopover.tsx
What was probably the recent components refactor broke the ckeditor bundle deployment script, because that script was doing a dynamic require of `ckEditorApi`, which probably now has a bunch of components in its import tree.  Some of those components were performing top-level access of database settings.  Generally that's a bit of an anti-pattern, but at least one of them (`postsListViewTypeSetting`, in `usePostsListView.ts`) looked non-trivial to fix, so I fixed the script to start a server before doing the dynamic import instead.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210266277309661) by [Unito](https://www.unito.io)
> Fix ckeditor bundle deployment script

- packages/lesswrong/lib/collections/posts/newSchema.ts
- packages/lesswrong/lib/generated/gqlSchemaAndFragments.gql
- packages/lesswrong/lib/generated/inputTypes.d.ts
- schema/accepted_schema.sql
At least one user reported being unable to edit a post because they were getting a 404 (caused by an error thrown in our graphql layer when it tried to return a null value for a required field).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210268894060158) by [Unito](https://www.unito.io)
> make imageId field in SocialPreview gql types optional to match actual data in database

- packages/lesswrong/lib/cookies/callbacks.ts
- packages/lesswrong/stubs/client/datadogRum.ts
- packages/lesswrong/stubs/client/reCaptcha.ts
During unit tests this warning appears:
```
Datadog Browser SDK: SDK is loaded more than once. This is unsupported and might have unexpected behavior.
```
This happens because lib/cookies/callbacks.ts imports "../../client/datadogRum", using a relative path (rather than @/client), and client/datadogRum imports @datadog/browser-rum, which is a side-effectful import. Fix by converting the ../client imports to @/client, so they get redirected to stubs.
Assigning to CEA to review because, while I don't think this breaks dataog (the file is also imported from `client/clientStartup`), that's maybe be worth testing.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210245009459391) by [Unito](https://www.unito.io)
> Fix a lib-to-client import

- packages/lesswrong/lib/collections/posts/annualReviewMarkets.ts
It's a new (undocumented) required field in the API
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210276898497926) by [Unito](https://www.unito.io)
> Add liquidityTier to createManifoldMarket function

- packages/lesswrong/server/callbacks/userCallbackFunctions.tsx
We're about to start recording the source of signups on effectivealtruism.org and centreforeffectivealtruism.org, so we should probably do the same on the forum as well.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210238164152619) by [Unito](https://www.unito.io)
> [EA] Add source field to mailchimp signups

- packages/lesswrong/components/common/LWDialog.tsx
`runCrosspostsTests` had this error in its output (without actually failing the test):
```
[WebServer] ReferenceError: document is not defined
at Component (/home/runner/work/ForumMagnum/ForumMagnum/packages/lesswrong/components/common/LWDialog.tsx:119:7)
```
This is because LWDialog uses a portal in such a way that it only works client-sided, and EALoginPopover tries to use it in an SSR context. Fix by making LWDialog not crash if SSRed (though it will wait til after it's hydrated to actually display anything).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210322768759340) by [Unito](https://www.unito.io)
> Fix some non-fatal crashes in SSR that happen during unit tests

- packages/lesswrong/components/LWBackgroundImage.tsx
Add LessOnline guy back to frontpage for a week:
I'm actually not 100% sure what we want to say in terms of when the price-increase is.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210324333823536) by [Unito](https://www.unito.io)
> Add lessonline splash back

- packages/lesswrong/components/comments/CommentsNode.tsx
In-context comment links are currently quite unreliable on navigation (they do seem to work on page load). I believe the change here was essentially a bug before (in the [original PR to use in-context comments](https://github.com/ForumMagnum/ForumMagnum/pull/9699)), as I intended it to always scroll to the comment at this point regardless of whether it was collapsed. Changing this seems to make it a lot more reliable (as far as I can tell it now works every time).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210342833116260) by [Unito](https://www.unito.io)
> Improve in-context comments

- packages/lesswrong/components/comments/CommentForm.tsx
- packages/lesswrong/components/comments/CommentsSubmitDropdown.tsx
- packages/lesswrong/lib/abTestImpl.ts
- packages/lesswrong/lib/collections/comments/views.ts
1. Fix quick takes list not appearing for logged in users (due to a bug in mergeSelectors which I haven't been able to fix, but have worked around)
2. Fix A/B test technically (but not actually) breaking caching for logged out users. I have made it always show the dropdown for logged out, and show the login popup if someone tries to save a draft
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210402712081516) by [Unito](https://www.unito.io)
> [EA] Post-release fixes for draft comments

- packages/lesswrong/components/editor/CKCommentEditor.tsx
There may have been some original justification for not doing this but I always find it annoying
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210421889926652) by [Unito](https://www.unito.io)
> [EA] Add imageUpload to comment toolbar

- packages/lesswrong/server/repos/CommentsRepo.ts
- packages/lesswrong/server/search/searchDocuments.d.ts
Search for comments is currently broken because the `draft` field is missing in elastic. We need to merge this then, after deploying, run `yarn repl prod packages/lesswrong/server/search/elastic/ElasticExporter.ts 'new ElasticExporter().configureIndexes()'`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210439244261294) by [Unito](https://www.unito.io)
> Export comments 'draft' field to elastic

- packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsItem.tsx
- packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsList.tsx
Currently, EA Forum mods can see the sunshine sidebar, and they can suggest individual posts for curation, but they don't see the list of "Suggested for Curated" posts. This PR just adds this list to their sidebar, to make it easier for them to +1 a suggestion.
Currently curation is only done by people on the Forum Team, so I've hidden the options to curate and remove a post from the list from non-admins on the EA Forum.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210427173769308) by [Unito](https://www.unito.io)
> [EA Forum only] mods can see posts that are suggested for curation

- packages/lesswrong/components/contents/ContentItemBody.tsx
- packages/lesswrong/server/utils/arbital/resources/bayesGuideMultipleChoice.html
The `ContentItemBody` refactor didn't play very nicely with the custom Bayes Rule Guide html (which is a pretty hacky one-off in our codebase).  Translate the necessary event handler attribute names to camelCase, parse the function strings, and set `for` on the input labels so that React knows what it's doing when you click on one of them.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210433761276445) by [Unito](https://www.unito.io)
> fix bayes guide custom html attribute handling in refactored ContentItemBody

- packages/lesswrong/components/comments/SideCommentIcon.tsx
- packages/lesswrong/components/comments/useComment.ts
- packages/lesswrong/components/linkPreview/LinkToPost.tsx
- packages/lesswrong/components/linkPreview/PostLinkPreview.tsx
- packages/lesswrong/components/posts/PostsPreviewTooltip/PostsPreviewTooltipSingle.tsx
- packages/lesswrong/components/posts/PostsPreviewTooltip/PostsTooltip.tsx
- packages/lesswrong/components/posts/usePost.ts
- packages/lesswrong/components/tagging/TagHoverPreview.tsx
- packages/lesswrong/components/tagging/TagSearchHit.tsx
- packages/lesswrong/lib/crud/useSingleWithPreload.ts
With the recent ContentItemBody rework, links embedded in posts SSR with their link-preview indicator circle present. However, a cost of this was that the server would fetch a preview of the post, in order to get it ready for hover and to get the user's read-status to decide whether to fill in the circle or not. This was a change from the previous behavior, where the post preview would be fetched by the client post-load.
This restores the earlier timing: the post preview is downloaded by the client after SSR is complete. However, the link-circle will be present immediately (but always unfilled), so that the SSR is visually consistent.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210426958049913) by [Unito](https://www.unito.io)
> NoSSR link previews and side-comments

- packages/lesswrong/lib/utils/viewUtils.ts
- packages/lesswrong/server/resolvers/allTagsActivityFeed.ts
- packages/lesswrong/server/resolvers/recentDiscussionFeed.ts
- packages/lesswrong/server/resolvers/tagHistoryFeed.ts
- packages/lesswrong/server/resolvers/tagResolvers.ts
- packages/lesswrong/server/utils/feedUtil.ts
This applies the default selector to tag edit blocks on the All Posts page, as well as some other places where it was missing, preventing comments from unreviewed users (which might be spam) from appearing there.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210383463652184) by [Unito](https://www.unito.io)
> Don't show unreviewed comments in all posts page tag history blocks, various feeds

- packages/lesswrong/components/common/LWHome.tsx
- packages/lesswrong/components/pages/UltraFeedPage.tsx
- packages/lesswrong/components/ultraFeed/UltraFeed.tsx
- packages/lesswrong/lib/cookies/cookies.ts
Makes it so that if you have visited the /feed page
- you always see the checkbox for enabling ultrafeed on the frontpage even if unchecked
- the ultrafeed is enabled on the frontpage for you automatically when you first visit (subsequent visits won't reenable it though)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210467483056631) by [Unito](https://www.unito.io)
> Ultrafeed improved checkbox

- packages/lesswrong/components/linkPreview/HoverPreviewLink.tsx
- packages/lesswrong/components/linkPreview/PostLinkPreview.tsx
- packages/lesswrong/lib/vulcan-lib/routes.ts
Pass the `className` through everywhere. I previously did this for this case:
```typescript
// Invalid link with no href? Don't transform it.
if (!href) {
return <a href={href} id={id} rel={rel} className={className}>
{children}
</a>
}
```
But I misread this as `if (href)`, so this had only fixed the case where there is no url.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210488932888499) by [Unito](https://www.unito.io)
> [EA] Fix CTA buttons (from rendering as regular links)

- packages/lesswrong/components/ultraFeed/FeedContentBody.tsx
- packages/lesswrong/components/ultraFeed/settingsComponents/UltraFeedSettingsComponents.tsx
Changes in expansion require a "read more" button that lineclamp doesn't currently have, so it breaks. This disables lineclamp until properly fixed.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210506976422667) by [Unito](https://www.unito.io)
> Remove line truncation

- packages/lesswrong/lib/tableOfContents.ts
- packages/lesswrong/unitTests/tableOfContents.tests.ts
We got a bug report that bold sections in footnotes were showing in the table of contents. I figure we should probably just exclude all headings in footnotes from the TOC.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210531421110531) by [Unito](https://www.unito.io)
> Exclude headings in footnotes from TOC

- packages/lesswrong/lib/collections/posts/newSchema.ts
- packages/lesswrong/lib/generated/gql-codegen/graphql.ts
- packages/lesswrong/lib/generated/gqlSchema.gql
- packages/lesswrong/lib/generated/graphqlCodegenTypes.d.ts
- packages/lesswrong/lib/generated/inputTypes.d.ts
There might still be an outstanding bug where the `socialPreview` field being rendered in the form automatically marks it as dirty (and causes it to be unnecessarily included in the update payload).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210538211526278) by [Unito](https://www.unito.io)
> Allow coauthors to update social preview and don't require an image id

- packages/lesswrong/components/tagging/EATagPage.tsx
- packages/lesswrong/components/tagging/TagPageUtils.tsx
- packages/lesswrong/components/tagging/subforums/SubforumWikiTab.tsx
- packages/lesswrong/lib/collections/users/newSchema.ts
@Will-Howard and I agreed that the default "relevance" sort is not useful (people rarely vote on relevance), so we're changing it to "top" (which is much more likely to be useful for new users).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210536206924354) by [Unito](https://www.unito.io)
> [EA Forum only] default sort tag page posts by top instead of relevance

- packages/lesswrong/lib/collections/posts/newSchema.ts
For posts, `readTimeMinutes` is calculated by first trying to use `readTimeMinutesOverride` and if that's not set then defaulting to taking the word count and diving by 250. The SQL resolver is currently returning incorrect results when `readTimeMinutesOverride` is set, as it's trying to also divide _this_ by 250, as if it were a word count instead of a read time.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210573117788090) by [Unito](https://www.unito.io)
> Fix read time minutes SQL resolver

- packages/lesswrong/components/votes/ReactionIcon.tsx
- packages/lesswrong/themes/defaultPalette.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210588829800038) by [Unito](https://www.unito.io)
> Fix reaction icons being white-on-white after navigating from theme-overridden front page to a light-mode post page

- packages/lesswrong/themes/userThemes/darkMode.ts
The color in the dark theme was "none", but this is an invalid color value, so it fell through to a light-mode color
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210595712702575) by [Unito](https://www.unito.io)
> Fix color of single-line comments after theme switch

- packages/lesswrong/lib/collections/posts/newSchema.ts
- packages/lesswrong/lib/generated/gql-codegen/graphql.ts
- packages/lesswrong/lib/generated/gqlSchema.gql
- packages/lesswrong/lib/generated/graphqlCodegenTypes.d.ts
- packages/lesswrong/lib/generated/inputTypes.d.ts
This was previously fixed, and accidentally reverted. See: https://lworg.slack.com/archives/CJUN2UAFN/p1750351999979259 ;  https://lworg.slack.com/archives/CJUN2UAFN/p1749581682746829?thread_ts=1749580409.934209&cid=CJUN2UAFN
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210596336715249) by [Unito](https://www.unito.io)
> Fix crash when editing some posts

- packages/lesswrong/server/robots.ts
When a user clicks the link in a link post they aren't redirected straight to that link. Instead, they go to `/out?url=...` which handles analytics, etc., and then forwards the user on to the link. It seems that google is currently indexing these `/out` urls, which we probably don't want - the search result looks like a page on the forum, but then you click it and get redirected to the other page. Also, for some reason google is indexing `/out` urls on the forum-bots site despite the fact that none of that site should be indexable, and this should fix that problem.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210612847044936) by [Unito](https://www.unito.io)
> Disallow crawling /out in robots.txt

- packages/lesswrong/components/common/Header.tsx
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210605959182228) by [Unito](https://www.unito.io)
> Fix light-mode header missing its drop shadow after navigation/theme-switch

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/components/bookmarks/BookmarksFeed.tsx
- packages/lesswrong/components/comments/CantCommentExplanation.tsx
- packages/lesswrong/components/hooks/useDialogNavigation.ts
- packages/lesswrong/components/hooks/useDisableBodyScroll.ts
- packages/lesswrong/components/ultraFeed/CondensedFooterReactions.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedCommentsDialog.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedItemFooter.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedPostDialog.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedPostItem.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedQuickTakeDialog.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedThreadItem.tsx
- packages/lesswrong/components/ultraFeed/ultraFeedTypes.ts
- packages/lesswrong/components/votes/ReactionsPalette.tsx
- packages/lesswrong/components/votes/UltraFeedReactionsPalette.tsx
- packages/lesswrong/components/vulcan-core/App.tsx
- packages/lesswrong/lib/collections/users/helpers.ts
- packages/lesswrong/lib/voting/curatedReactionsList.ts
- packages/lesswrong/server/repos/BookmarksRepo.ts
- packages/lesswrong/server/repos/CommentsRepo.ts
- packages/lesswrong/server/ultraFeed/ultraFeedBookmarkHelpers.ts
- packages/lesswrong/server/ultraFeed/ultraFeedThreadHelpers.ts
- Comments Modal is fullscreen. Properly closes on all navigate events
- UltraFeedItems now show "total descendent" count for comment count instead just immediate descendent
- Text in Post Modal is centered (via replicating the grid layout of PostsPage)
- We indicate when there are multiple react types on an item:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210632128623126) by [Unito](https://www.unito.io)
> Ultrafeed Improvements 20250623

- packages/lesswrong/server/repos/BookmarksRepo.ts
Thought I was restoring it to how it was, but nope
> Fix column name in query

- packages/lesswrong/components/notifications/NotificationsMenu.tsx
After some refactoring in `useUnreadNotifications` and `NotificationsMenu` driven by suspense, when you opened the notification sidebar, the badge on the Messages tab would trigger a refetch of the notification-counts query, which would cause the whole sidebar to suspend while it loaded, which would make the slide-in animation very janky. Fix by putting the badge on the Messages tab into its own suspense boundary.
(Most client-side things don't use suspense like this; `useUnreadNotifications` gets suspense because it uses `useBackgroundQuery`/`useReadQuery` rather than `useQuery`, which was necessary because it's a context provider.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210653110119877) by [Unito](https://www.unito.io)
> Fix jank in the animation when the notifications sidebar slides in

- packages/lesswrong/client/clientStartup.ts
- packages/lesswrong/components/notifications/NotificationsMenu.tsx
- packages/lesswrong/lib/types/windowObjectExtensions.ts
- packages/lesswrong/server/rendering/eventCapture.ts
- packages/lesswrong/server/rendering/renderPage.tsx
This PR solves the problem of clicks getting lost if they occur during pageload before `hydrateRoot` is called, particularly focused on the notifications bell icon but also fixing lost clicks for other things such as the home posts list tabs. It works by injecting a small script that captures click events, and replaying them after `hydrateRoot` is called.
This is kind of a hack, but there doesn't seem to be an idiomatic way to do this without delaying first contentful paint until `hydrateRoot` is called, which is much too long to delay without bundle splitting and is probably still too long to delay even _with_ bundle splitting. While there is documentation and references referring to React having an event-replay system aimed at a scenario that sounds kind of like this one, this is in …
> Improve the notifications button

- packages/lesswrong/components/common/LWHome.tsx
We had a special case for the spotlight item that hides it on desktop, because it duplicates the right-hand sidebar of the IABIED special theme. Remove that, since the IABIED event is no longer active
> Unhide the spotlight item on desktop

- .github/workflows/deployEADev.yaml
We are temporarily diverged from `master`, so I'm creating this branch to use for staging deploys instead
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210684356728062) by [Unito](https://www.unito.io)
> [EA] Deploy EA staging from ea-staging rather than master

- packages/lesswrong/components/ea-forum/EAPostMeta.tsx
- packages/lesswrong/components/posts/TruncatedAuthorsList.tsx
It's always annoyed me that, in post items, the tooltip for the post title is below the text but the tooltips for the author names are to the left of the text. This means that when you move your mouse over the post items all the tooltips quickly flick about in both directions. This PR is a quick change to move the author tooltips under the text as well, and I think it makes moving your mouse over the post items a lot tidier and less hectic.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210684488286564) by [Unito](https://www.unito.io)
> [EA] Move author hoverovers to `bottom-start` in post items

- .ackrc
- packages/lesswrong/components/form-components/TagFlagToggleList.tsx
- packages/lesswrong/components/tagging/TagFlagItem.tsx
- packages/lesswrong/components/tagging/TagsDetailsItem.tsx
- packages/lesswrong/lib/crud/useQuery.ts
- packages/lesswrong/server/resolvers/defaultResolvers.ts
* Improve error handling of default single resolver
We used to use the single resolver exclusively through `useSingle`, which will skip the query if the provided documentId is null. In most places where we converted this to `useQuery`, we either have a type-system guarantee that it isn't null or have a corresponding skip, but there were a few places where this wasn't the case. This led to a very-opaque exception from deep in the internals of the postgres query-generation code. Either allow a missing documentId, returning null, if the resolver was called with `allowNull: true`, or throw a better exception if not.
* Remove showNumber option from TagFlagItem
TagFlagItem had an option to show the number of tags with a given flag. It did this by downloading all of those tags, which was so slow …
> Assorted small changes

- packages/lesswrong/server/datadog/tracer.ts
Last month we had a big jump in the cost of custom metrics. This is resolved now, but given that we don't use custom metrics that much I think it's best to disable them until we have better cost alerting set up
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210696272047833) by [Unito](https://www.unito.io)
> [EA] Disable custom datadog metrics

- packages/lesswrong/server/keywordAlerts/keywordSearch.ts
In the last tweaks PR I switched to a phrase query, but forgot to change the fields to use the `.exact` version.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210727138676907) by [Unito](https://www.unito.io)
> [EA] Use 'exact' fields for keyword alert search

- packages/lesswrong/components/common/TabNavigationMenu/NavigationStandalone.tsx
There's currently a bug where trying to hide the sidebar on pages with standalone navigation enabled only shifts it left by 100px instead of completely off-screen.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210727380305819) by [Unito](https://www.unito.io)
> [EA] Fix standalone navigation slide

- packages/lesswrong/components/common/ExpandableSection.tsx
- packages/lesswrong/components/common/HomeLatestPosts.tsx
- packages/lesswrong/components/common/SectionTitle.tsx
- packages/lesswrong/components/ea-forum/EABestOfPage.tsx
- packages/lesswrong/components/ea-forum/EAHomeMainContent.tsx
- packages/lesswrong/components/recentDiscussion/RecentDiscussionFeed.tsx
Prio candidate. Adds a `large` prop to `SectionTitle` that uses the same styles as the titles on the /best-of page and uses these styles on the home page. Also migrates the titles on the /best-of page to use `SectionTitle` with this new option.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210710567533297) by [Unito](https://www.unito.io)
> [EA] Use best-of page title styles on the homepage

- packages/lesswrong/components/tagging/SingleLineTagUpdates.tsx
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210738476020886) by [Unito](https://www.unito.io)
> Fix AllPosts Tag Page username styles

- packages/lesswrong/server/resolvers/spotlightResolvers.ts
If the DB cache isn't warm this is an extra 600ms (though I guess that should rarely happen), and I don't know what the extra overhead is on actually grabbing 300+ spotlights from the DB.  I don't think there's actually any reason to get all of them since we're sorting them in the DB anyways.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210749466332782) by [Unito](https://www.unito.io)
> fetch only one spotlight from the database, instead of all of them, when getting the current spotlight

- packages/lesswrong/client/start.tsx
- packages/lesswrong/lib/index.ts
- packages/lesswrong/lib/vulcan-lib/components.tsx
- packages/lesswrong/server/styleGeneration.tsx
- packages/lesswrong/unitTests/components.tests.ts
- packages/lesswrong/unitTests/themePalette.tests.ts
We refactored away the `Components` table idiom, making `registerComponent` just a way of applying HoCs, and eliminating the need to import all components lest they be identified by string-name and used. But we didn't actually remove the import statement that imported all of them.
Remove the all-components import from `lib/index.ts`, so that the client no longer needs to import all components. (`styleGeneration.ts` on the server still uses it, to generate a merged stylesheet with every compnent's styles.)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210712763737476) by [Unito](https://www.unito.io)
> Don't import all components

- packages/lesswrong/components/LWBackgroundImage.tsx
The LW background image ("science orbs"), at medium breakpoint, was winding up in the post footer below the bottom of the infinite scroll, where it isn't visible.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210766444960627) by [Unito](https://www.unito.io)
> Make the LW background image visible at medium breakpoint

- packages/lesswrong/components/books/Book2018Landing.tsx
- packages/lesswrong/components/books/Book2019Landing.tsx
- packages/lesswrong/components/contents/ContentItemBody.tsx
- packages/lesswrong/components/hooks/useOnNavigate.tsx
- packages/lesswrong/components/recentDiscussion/EARecentDiscussionThread.tsx
- packages/lesswrong/components/recentDiscussion/FeedPostCommentsCard.tsx
- packages/lesswrong/components/recentDiscussion/RecentDiscussionFeed.tsx
- packages/lesswrong/components/recentDiscussion/RecentDiscussionTag.tsx
- packages/lesswrong/components/recentDiscussion/RecentDiscussionThread.tsx
- packages/lesswrong/components/recentDiscussion/RecentDiscussionThreadsList.tsx
- packages/lesswrong/components/recentDiscussion/useRecentDiscussionThread.ts
- packages/lesswrong/components/recentDiscussion/useRecentDiscussionViewTracking.ts
- packages/lesswrong/components/recommendations/ContinueReadingList.tsx
- packages/lesswrong/components/seasonal/HomepageMap/HomepageMapFilter.tsx
- packages/lesswrong/components/tagging/subforums/SubforumSubforumTab.tsx
- packages/lesswrong/components/themes/usePrefersDarkMode.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedCommentItem.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedCommentsItemMeta.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedPostDialog.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedThreadItem.tsx
- packages/lesswrong/components/ultraFeed/useSeeLess.ts
- packages/lesswrong/components/users/account/UsersEditForm.tsx
Many places in the codebase were erroneously importing captureEvent directly and not using it via hook, meaning the events don't get context from surround <AnalyticsContext>
Separately there was some issue with callbacks using captureEvent getting defined outside of the AnalyticsContext wrappers, and the solution being to pull the wrappers up higher. This dovetailed with removing the additional index props that had been added and weren't doing anything but be in the wrappers
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210769464637667) by [Unito](https://www.unito.io)
> Fix ultrafeed analytics (and in general)

- packages/lesswrong/server/ultraFeed/ultraFeedThreadHelpers.ts
We've still been showing negative karma comments, I think (1) definitely don't show threads where the first comment is negative, but maybe just don't bother showing negative at all (or their children)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210778325276105) by [Unito](https://www.unito.io)
> no negative karma comments in UltraFeed!!

- packages/lesswrong/components/common/AnalyticsPageInitializer.tsx
- packages/lesswrong/components/common/LWHome.tsx
- packages/lesswrong/components/hooks/useSessionManagement.ts
- packages/lesswrong/components/recentDiscussion/RecentDiscussionFeed.tsx
- packages/lesswrong/components/ultraFeed/UltraFeed.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedCommentsDialog.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedItemFooter.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedObserver.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedPostDialog.tsx
- packages/lesswrong/components/ultraFeed/ultraFeedTypes.ts
- packages/lesswrong/lib/analyticsEvents.tsx
- ultrafeed view events also logged to server
- sessionId for all tabs and events going on on a device at once
- inView tracking around the feeds
- track when dialogs close
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210805413907560) by [Unito](https://www.unito.io)
> Ultrafeed Better Analytics 20250714

- packages/lesswrong/components/common/LWHomePosts.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedCommentsDialog.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedPostDialog.tsx
- ckEditor toolbar interactions closed the ultrafeed modals, fixed by disabling outside clicks (they're full sceen anyway)
- failed to commit an AnalyticsInViewTracker in the last PR
> Ultrafeed fix ckeditor interactions closing modal

- packages/lesswrong/components/keywords/KeywordsPage.tsx
We have an `?add=` query parameter on the keyword page to automatically add a keyword when navigating to the page (this is used by the "notify me" button on the search page). Currently, we don't clear this parameter after adding the keyword which means it's impossible to then _remove_ that keyword unless you renavigate to the page without the query parameter, otherwise it just adds it again. This PR changes the logic to automatically remove the query parameter once we've consumed it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210808920631713) by [Unito](https://www.unito.io)
> Clear `add` param on keyword page after adding

- packages/lesswrong/components/recentDiscussion/useRecentDiscussionViewTracking.ts
- packages/lesswrong/components/ultraFeed/UltraFeedObserver.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedPostDialog.tsx
- packages/lesswrong/components/ultraFeed/ultraFeedSettingsTypes.ts
- fix a bug in the back navigation of ultrafeed modals introduced by unnecessary rerenders because a callback that wasn't stable
- adjust some values in the default settings and thresholds for triggering view events
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210838548771707) by [Unito](https://www.unito.io)
> Ultrafeed Fix Back Navigation & Constants Adjustment

- packages/lesswrong/server/repos/helpers.ts
This selector is used in two places in `SequencesRepo`, both of which are currently a bug:
- `sequenceRouteWillDefinitelyReturn200`
- `getSitemapSequences`
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210848348250168) by [Unito](https://www.unito.io)
> Exclude draft sequences from `getViewableSequencesSelector`

- packages/lesswrong/server/keywordAlerts/keywordAlertsCron.ts
- packages/lesswrong/server/notificationTypesServer.tsx
- Batch keyword alert notifications as displayed onsite
- Fix the display of batched keyword alert notifications in emails (caused by an early return)
- Display the batch time in emails (I think it's a bit confusing without it)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210849918338862) by [Unito](https://www.unito.io)
> Keyword alert notifications batching improvements

- packages/lesswrong/components/hooks/useSessionManagement.ts
without this fix, a tab waking after > 30 min delay will resume sending with the same sessionId because there's nothing causing a check.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210893827830920) by [Unito](https://www.unito.io)
> Fix Session Id  Management

- packages/lesswrong/lib/collections/reports/fragments.ts
- packages/lesswrong/lib/generated/fragmentTypes.d.ts
- packages/lesswrong/lib/generated/gqlSchemaAndFragments.gql
- packages/lesswrong/server/slack.ts
Forwarding reports to mod Slack currently only for for reported posts and reported comments. This PR expands this to also include reports directly of users.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210936586459273) by [Unito](https://www.unito.io)
> [EA] Fix user report slack forwarding

- packages/lesswrong/components/common/PermanentRedirect.tsx
- packages/lesswrong/server/repos/TagsRepo.ts
- packages/lesswrong/server/sitemap.ts
More updates from looking at google search console:
- I forgot to include tag pages in the sitemap 🤦
- Google recently discovered a bunch of `/tag/${slug}` pages which just redirect to `/topics/${redirect}`, but the redirect happens client side and there's no canonical tag so google is complaining about duplicate content. This PR adds a canonical tag to `PermanentRedirect` to fix this (you can check that the tag makes it to the statically rendered HTML using curl).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210962130009381) by [Unito](https://www.unito.io)
> Add tags to sitemap and add canonical tag to `PermanentRedirect`

- packages/lesswrong/server/search/elastic/ElasticConfig.ts
It turns out you do need to be able to find unreviewed users in search sometimes, in order to add coauthors.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210953605837844) by [Unito](https://www.unito.io)
> Don't filter unreviewed users out of search

- packages/lesswrong/components/contents/ContentItemBody.tsx
- packages/lesswrong/themes/userThemes/darkMode.ts
Affected this post: https://www.lesswrong.com/posts/FrBxFa3qMDvLypDEZ/ai-63-introducing-alpha-fold-3
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210970287317903) by [Unito](https://www.unito.io)
> Fix black-on-black text in dark mode when an RSS-synced post contains style="color: initial"

- packages/lesswrong/components/ultraFeed/UltraFeedCommentItem.tsx
- packages/lesswrong/components/ultraFeed/UltraFeedPostItem.tsx
Trying out the mobile styles for desktop too:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1210971271298617) by [Unito](https://www.unito.io)
> Ultrafeed mobile is desktop

- packages/lesswrong/components/recommendations/RecommendationsSamplePage.tsx
- packages/lesswrong/lib/collections/users/recommendationSettings.ts
- packages/lesswrong/lib/voting/eaEmojiPalette.ts
- packages/lesswrong/server.ts
- packages/lesswrong/server/cron/allCronJobs.ts
- packages/lesswrong/server/emailComponents/EmailInactiveUserSummary.tsx
- packages/lesswrong/server/emailComponents/EmailUsername.tsx
- packages/lesswrong/server/emailComponents/EmailWrapper.tsx
- packages/lesswrong/server/emails/inactiveUserSummaryCron.tsx
- packages/lesswrong/server/emails/renderEmail.tsx
- packages/lesswrong/server/recommendations/Feature.ts
- packages/lesswrong/server/recommendations/FeatureStrategy.ts
- packages/lesswrong/server/repos/PostsRepo.ts
- packages/lesswrong/server/repos/UsersRepo.ts
- packages/lesswrong/server/repos/VotesRepo.ts
- packages/lesswrong/server/wrapped/wrappedDataByYear.ts
[Figma](https://www.figma.com/design/vt5B6OD5AEcmzhjn9S0ps7/2024-Q4?node-id=244-9&m=dev)
You can generate some test emails (without actually sending them) with:
```
yarn repl prod "packages/lesswrong/server/emails/inactiveUserSummaryCron.tsx" "sendInactiveUserSummaryEmails(10, true)"
```
Then you can copy the HTML from the console output and paste it into [https://app.postdrop.io/](https://app.postdrop.io/) for a preview.
This PR also includes logic to load Inter and Merriwether, but very few email clients actually support this so most users will actually end up with Helvetica and Georgia which are the highest precedence web-safe fonts in our stack.
Below is an example email (this was generated with real data, so I've redacted the username and post title for the sake of the publicly …
> Send inactive user summary email

- packages/lesswrong/components/Layout.tsx
- packages/lesswrong/lib/cookies/cookies.ts
Adds a client-side redirect to baserates-prod-test for admins, so that we can more reliably shake out loose bugs.  Can be disabled by appending `?disableRedirect=true` to any lesswrong.com url, which leaves a cookie preventing the redirect.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211051506890193) by [Unito](https://www.unito.io)
> add temporary client-side redirect to baserates-prod-test for admins

- .github/workflows/runTests.yaml
Coveralls has had a couple of outages recently (and is often generally a bit unreliable) which causes our CI runs to fail. Since uploading the coverage report isn't actually very important, this PR changes it so that these steps can fail without failing the entire CI run.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211089141585082) by [Unito](https://www.unito.io)
> Allow coveralls upload to fail, without failing CI run

- packages/lesswrong/server/emails/inactiveUserSummaryCron.tsx
- packages/lesswrong/server/recommendations/FeatureStrategy.ts
Fixed a couple issues I noticed:
1. Posts in the email were not ordered by score desc
2. One person got an email with 3 posts, which is because some posts were recommended more than once
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211087412075252) by [Unito](https://www.unito.io)
> [EA Forum only] a couple small fixes for the inactive user summary email

- packages/lesswrong/server/emailComponents/EmailAnnualForumUserSurvey.tsx
- packages/lesswrong/server/repos/UsersRepo.ts
- packages/lesswrong/server/scripts/sendAnnualForumUserSurveyEmails.tsx
Updated for 2025, example email:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211085702006899) by [Unito](https://www.unito.io)
> [EA Forum only] update the annual survey reminder email

- packages/lesswrong/server/migrations/20250812T114600.cleanup_invalid_ReadStatuses_2025_08.ts
Prior to [this change](https://github.com/ForumMagnum/ForumMagnum/pull/8463#discussion_r2235789525), ReadStatuses could sometimes wrongly point to objects other than posts. This caused a discontinuity in our data, so we want to clean up these rows to make analytics based on ReadStatuses more consistent.
I ran a query on our prod database to find all the collections where there are examples of ReadStatuses pointing to them. This PR then adds a migration to delete these.
The reasons I'm deleting just these specific ones, rather than e.g. rows that don't point to a post are:
1. Posts may be deleted somehow (although I don't think we actually hard-delete them anywhere currently), which we still want to count for analytics purposes
2. There were other discrepancies in ReadStatuses, such as …
> Migration to delete invalid read statuses

- packages/lesswrong/components/common/LWDialog.tsx
Introduced in the material-UI refactor, when switching from MUI's <Paper> component to our own <Paper>.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211083290080769) by [Unito](https://www.unito.io)
> Fix missing vertical scroll in the post version history dialog (and presumably some other dialogs as well)

- packages/lesswrong/components/editor/CKPostEditor.tsx
Editing the description of a sequence confusingly uses the `CkPostEditor` component. Unfortunately that component (reasonably, given its name) always assumes that the document it's given is a post. This accidentally worked fine up until the recent change to coauthor handling, but it now throws an error when we try to spread `coauthorUserIds` which only exists on posts, not sequences. This PR changes `CkPostEditor` to be aware the it's document may be either a post or a sequence. This probably warrants a more thorough refactor in the future, but this will do for now.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211198257600507) by [Unito](https://www.unito.io)
> Fix editing sequences

- packages/lesswrong/components/linkPreview/PostLinkPreview.tsx
A graph on [this post](https://forum.effectivealtruism.org/posts/TLbctDQJEZtZhAAur/global-economic-inequality) was too squashed when using a height of 375px.
Before/after:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211244602014923) by [Unito](https://www.unito.io)
> Make OWID iframe bigger

- packages/lesswrong/lib/tableOfContents.ts
- packages/lesswrong/server/tableOfContents.ts
The `author` field on answers can be stale if someone changes their displayName. This adds an optional `userMap` to `getTocAnswers` to use before falling back to the denormalised `author` field.
An ideal solution here would fix `author` being stale, but this is just a quick workaround to fix the case that was reported.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211257937927292) by [Unito](https://www.unito.io)
> Fix stale answer displayNames

- packages/lesswrong/components/posts/TableOfContents/FixedPositionToC.tsx
Previously, clicking the title at the top of a postPage table of contents, would update your url to "https://lesswrong.com" instead of resetting the #hashtag of the post page url.
I'm not 100% sure why this is necessary, but I updated it to use the same query-preservation-formatting that we use for the rest of the anchor-clicking in the toc (which makes sense to want to use, to preserve the query, I just don't get why not-having-that would reset the whole url)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211462264653891) by [Unito](https://www.unito.io)
> Fix FixedToC title navigation bug

- packages/lesswrong/components/seasonal/petrovDay/petrov-day-story/PetrovDayStory.tsx
Previously, the standalone Petrov Page looked like this:
This makes it look ~reliably like this, where it's more obvious that there's more content if you scroll down:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211483837332565) by [Unito](https://www.unito.io)
> Make positioning of Petrov ceremony indicator "scroll down"

- packages/lesswrong/themes/stylePiping.ts
[This](https://github.com/ForumMagnum/ForumMagnum/pull/5805) PR removed custom bullet styles. This was to fix some relatively obscure bug in Google Doc copy-paste. We still have editor UI for custom bullet styles. Also, it seems that either Google or CKEditor has changed something underlying so that the original listed reproduction no longer produces the bug. 
I declare the cost of this isn't worth it. 
Beware, this might cause some historical posts to now change bullet list typing. I think this is worth the cost. I don't think it's worth running a whole big migration to fix all historical posts at their current bullet styling, but it might be worth it if we find some high-profile errors somewhere. …
> Restore bullet styling

- packages/lesswrong/server/migrations/20250926T140606.make_chapters_createdAt_not_null.ts
Our schema says that the `createdAt` field in `Chapters` should be non-nullable, but in all of our databases it _is_ nullable, and there are old records without a date. This causes graphql errors in unexpected places. No change should be needed except this migration.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211478474039043) by [Unito](https://www.unito.io)
> Add migration to make `Chapters.createdAt` non-nullable

- ecs/Dockerfile
- ecs/README.md
- ecs/fargate-dev-refresh.yml
- ecs/push_refresh_script_update.sh
- ecs/refresh_dev.sh
Also provides a script for updating the... script... which does the dump, if we ever want to e.g. exclude some more tables, or try parallelizing it, or something.  It does require you to have the aws cli (with some specific permissions) and docker installed locally.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211481878249472) by [Unito](https://www.unito.io)
> set up scheduled ecs task for dumping prod db contents into dev each night, with associated infrastructure

- packages/lesswrong/lib/fmCrosspost/routes.ts
- packages/lesswrong/server/crossposting/handlers.ts
https://cea-core.slack.com/archives/C75BWSNBH/p1758643850403319
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211508825562087) by [Unito](https://www.unito.io)
> [EA] Include `fmCrosspostUserId` in the response for `crossposterDetailsRoute`

- packages/lesswrong/server/attributeEdits.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211505678558883) by [Unito](https://www.unito.io)
> Don't crash in computeAttributions when no revs exist up to the specified version

- packages/lesswrong/lib/collections/moderatorActions/helpers.ts
- packages/lesswrong/server/callbacks/userCallbackFunctions.tsx
Note that this also requires adding "website" to the `reasonsForInitialReview` database setting. I've already done this on the dev DB, but it's not safe to do so on prod until the new code is deployed.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211467316758346) by [Unito](https://www.unito.io)
> Add users to queue if they set a website on their profile

- packages/lesswrong/components/quickTakes/QuickTakesSection.tsx
Sets quicktake count from "8" to "7."
If it still feels like too much might go down to 6.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211539053984085) by [Unito](https://www.unito.io)
> Remove one quicktake

- packages/lesswrong/lib/collections/posts/newSchema.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211548441693681) by [Unito](https://www.unito.io)
> remove onUpdate callbacks on all the sticky fields that were unsticky-ing posts whenever they were updated

- packages/lesswrong/components/comments/CommentForm.tsx
- packages/lesswrong/components/comments/CommentsDraftList.tsx
- packages/lesswrong/components/comments/CommentsItem/CommentBottom.tsx
- packages/lesswrong/components/comments/CommentsSubmitDropdown.tsx
- packages/lesswrong/components/comments/SingleLineComment.tsx
- packages/lesswrong/components/comments/commentTree.ts
- packages/lesswrong/components/users/UsersProfile.tsx
- packages/lesswrong/lib/betas.ts
- packages/lesswrong/server/repos/CommentsRepo.ts
- packages/lesswrong/server/repos/PostsRepo.ts
- packages/lesswrong/server/repos/VotesRepo.ts
- packages/lesswrong/server/repos/helpers.ts
On a profile page:
On a post page:
Relevant button differences with the EA forum:
- got rid of the divider
- reduced left-right padding on both the original submit button and the drop-down icon button push them closer together, since otherwise they looked too far apart without the divider (and with the same background color as the surrounding form)
- made the menu item padding much smaller to match the smaller combined width of our submit + drop-down
- kept our existing no-border and consistent background color between the submit button and the form its on
Other difference is that I implemented a different style on the profile page for the section title, to match our existing section titles (though smaller font size).
Go play around with it on the preview deployment.
Oh, also, I got rid …
> Enable draft comments for LessWrong

- .github/actions/runLWMigrations/action.yaml
- app/api/cron/every-five-minutes/route.ts
- app/api/cron/every-hour/route.ts
- app/api/cron/every-midnight/route.ts
- app/api/cron/every-minute/route.ts
- app/api/cron/every-ten-minutes/route.ts
- app/api/cron/update-missing-post-embeddings/route.ts
- packages/lesswrong/lib/generated/routeManifest.ts
- packages/lesswrong/server/analytics/analyticsViews.ts
- packages/lesswrong/server/cron/cronLock.ts
- packages/lesswrong/server/repos/PostsRepo.ts
- packages/lesswrong/server/ultraFeed/cron.ts
- vercel.json
…to run heavier operations sequentially, and implement advisory locks for the heavier ones that are on a fast schedule to prevent pileups if the db is nonresponsive.
Also fix the query for fetching posts without embeddings; it was previously returning ~2800 posts (and then fetching them in batches of 50, uselessly, since they were all posts that couldn't get embeddings for one reason or another).  Now it returns 4.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211549917832611) by [Unito](https://www.unito.io)
> refactor cron apis

- packages/lesswrong/components/votes/VoteAgreementIcon.tsx
When strong agree voting, sometimes you'd click and hold and it would abort the strong vote leaving a weak agree vote. This only happened on desktop, only for strong-agree, and only for part but not all of the clickable area.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211556770156841) by [Unito](https://www.unito.io)
> Fix a bug that sometimes made strong-agree-voting not work

- packages/lesswrong/lib/instanceSettings.ts
- packages/lesswrong/server/search/elastic/ElasticConfig.ts
- packages/lesswrong/server/search/elastic/ElasticExporter.ts
- packages/lesswrong/server/search/elastic/ElasticQuery.ts
This fixes totally pathological cases like being unable to find any users that have display names structured like `firstmlast` with search queries like `first`, `last`, or `first last`, and otherwise mitigates the huge search penalty that users receive for having no spacing or punctuation in their display names.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1211582637332572) by [Unito](https://www.unito.io)
> add ngram filter to enable search firstlast users by either name and prioritize older over newer users
