packages/lesswrong/components/comments/CommentsItem.jsx, packages/lesswrong/components/comments/CommentsList.jsx, packages/lesswrong/components/comments/CommentsNode.jsx, packages/lesswrong/components/comments/CommentsViews.jsx, packages/lesswrong/lib/collections/comments/callbacks.js, packages/lesswrong/lib/collections/comments/permissions.js, packages/lesswrong/lib/modules/fragments.js, packages/lesswrong/lib/modules/permissions.js, packages/lesswrong/lib/views.js, packages/lesswrong/styles/_colors.scss, packages/lesswrong/styles/_comments.scss
• CommentsItem has handleDelete function
• CommentsItem check for Users.canDo softRemove.all
• CommentsItem displays Delete or Undo Delete button
• CommentsList wrapped in withEdit
• CommentsList passes editMutation into CommentsNode
• CommentsNode passes editMutation to children
• CommentsViews displays Admin views if admin has softRemove access
• permissions.js includes sunshineRegiment
• lib/views now includes default view and deleted view
• deleted view shows all posts, with deleted posts flagged, sorted by deleted
=> Added a softDelete button

packages/example-forum/lib/server/rss.js
Using `htmlBody` instead of `body` adds the html to the feed.
=> Add text formatting to RSS feed (#83)

packages/vulcan-accounts/imports/ui/components/LoginForm.jsx, packages/vulcan-i18n/lib/modules/provider.js
`this.showMessage(this.context.intl.formatMessage({id: errorId}) || error.reason || error.message || 'accounts.error_unknown', errorId, 'error');` is passing `'error'` as the third arg, which is `clearTimeout`, thus instantly clearing some errors. Removing the `errorId` parameter fixed it.
=> Fixed bug in Vulcan login error messages

packages/lesswrong/styles/_tufte.scss
Following this discussion: https://www.lesserwrong.com/posts/iuNSrBoX2W5qHCAAo/notes-from-an-apocalypse/uEK8ypFh2reoooNx7
Note that I've tested the CSS changes in the browser devtools, but I haven't done the whole "get the site working locally" thing I'd need to properly test this change. It's conceivable that the change I've made here won't propagate to the CSS in the way I expect.
The -webkit-margin-left property is intended to work with direction: rtl. Unless there's some way to set direction:rtl on LW (or plans to do it in future), it's easier to just use margin. Plus, when I set direction: rtl manually with the old style, the blockquotes get double-indented on the right due to a 40px margin-right on "blockquote p" elements. The new style has equal margin on both sides, in both …
=> Indent blockquotes in firefox

.github/CONTRIBUTING.md
This contributing guide doesn’t talk about the LessWrong 2.0 project, but about the template that this project is based on. There is already a newer `CONTRIBUTING.md` in the project root.
This version of `CONTRIBUTING.md`, in `.github`, is the one that GitHub links new contributors to when they visit the [Issues page](https://github.com/Discordius/Lesswrong2/issues).
You may want to also move the existing `CONTRIBUTING.md` into `.github/CONTRIBUTING.md`, if you prefer that file path.
=> Delete redundant .github/CONTRIBUTING.md

packages/lesswrong/lib/modules/connection_logs.js, packages/lesswrong/lib/modules/forwarded_whitelist.js
The X-Forwarded-For header contains a list of IP addresses, each representing the client IP address as seen by successive proxies the request has been forwarded through. Since it's trivial for a client to add false information to the beginning of this list, normally the client IP address is determined by looking at a fixed position starting from the end of the list, as controlled by the HTTP_FORWARDED_COUNT environment variable, which represents the number of reverse proxies or load balancers in front of the server.
This PR adds a whitelist which effectively increases HTTP_FORWARDED_COUNT by one for selected clients. The whitelist is configured by forwardedWhitelist in settings.json as an array of hostnames (NOT IP addresses), for example:
"forwardedWhitelist": ["host1.com", "host2.com"] …
=> Add X-Forwarded-For whitelist.

packages/lesswrong/styles/_tufte.scss
The text of articles was right up to the edge of the screen on mobile which made text reading ever so slightly annoying. This will give the text some room to breath :)
Before:
After:
I couldn't get the dev environment working so this is untested other than fiddling the css on the page.
=> Add margin to text on mobile

packages/lesswrong/lib/index.js, packages/lesswrong/lib/scrollRestoration.js
The fix here ended up being fairly simple.
When the page unloads, set scroll restoration to "auto". The next time LessWrong is loaded, it will use the browser's default scroll restoration feature. Then when the JavaScript app runs, it will switch to using "manual" scroll restoration.
This way it only uses "auto" scroll restoration on the first page load, before the single-page app is initialized.
=> Remember scroll location on page reload. Fixes #295

README.md
Fix `github` link (which linked to #554 for some reason, not intentionally, I assume).
Replace `Discordius` with `LessWrong2` org.
=> Update github issue links in README

packages/lesswrong/components/async/AsyncEditorFormComponent.jsx
`.content-body` passes `font-size: 1.4rem` to the toolbar which results in a ~2px margin above buttons:
This PR fixes this problem.
---
The separator is still misaligned even with this patch, though:
Which is, as far as I can tell, partially because of LW2 styles, but not entirely. `inline-block` positioning sucks, it'd be better if inline-toolbar just used flexbox. Oh well.
=> fix InlineToolbar styles - don't inherit content-body styles

packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx, packages/lesswrong/components/comments/RecentCommentsItem.jsx, packages/lesswrong/components/comments/recentDiscussionThread.jsx, packages/lesswrong/components/posts/PostsCommentsThreadWrapper.jsx
Issue #568 
The ‘show parent’ button from RecentCommentsItem.jsx has been copied to CommentsItem.jsx, with the button only appearing when the comment has a parent that it isn’t already nested inside.
Taking advantage of this change, RecentDisscussionThread.jsx unflattens the recent comments it’s rendering, and displays them using CommentsNode components rather than RecentCommentsItem.
I’ve avoided touching the Sass files since apparently there are some major changes to them going on in another branch. Due to this, I’ve ended up using .recent-comments-node and .recent-comments-show-parent in places they weren’t quite meant for. It shouldn’t cause any problems but might be worth tidying up once the CSS has settled down.
When you click the ‘show parent’ button, it shows the parent as a …
=> Show-Parent-Comment for nested comments

packages/lesswrong/components/comments/CommentsListSection.jsx, packages/lesswrong/lib/events/callbacks_async.js, packages/lesswrong/lib/events/server.js
Fix two warnings that were spamming up the console/logs: a stack trace that showed up if you hadn't configured an Intercom API key (ie, on development installs), and a warning about missing keys in CommentsListSection.
=> Fix warnings

packages/lesswrong/components/common/Home.jsx, packages/lesswrong/components/common/Section.jsx, packages/lesswrong/components/common/SectionTitleLink.jsx, packages/lesswrong/lib/components.js, packages/lesswrong/themes/lesswrongTheme.js
Work from hackathon. Styles the sidebar on the posts page, but SectionTitleLink is envisaged as the base for the filter links underneath the 'Recent Posts' component
=> Refactor Section to use Material theme object, create SectionTitleLink component

packages/lesswrong/components/localGroups/CommunityMapFilter.jsx
This is not an ideal fix, and this is not the only bug related to those filters, but it's probably good enough for now.
(If you go to a specific-group page, and try using the filters, the currently-deployed version mangles the URI in a weird way. But that page shouldn't have the filters in the first place.)
=> Fix links when you click on filters on the front page map

packages/lesswrong/server/legacy-redirects/routes.js
Add a legacy route for `/rss/comments.xml`. Refactor the legacy routes file. Fix the legacy route for the post "Reversed Stupidity is Not Intelligence", which had the very unfortunate property that its ID in base36 was `lw` and this messed up URL parsing (#807 ).
=> Legacy route fixes

packages/lesswrong/components/common/HeadTags.jsx, packages/lesswrong/components/common/Home.jsx, packages/lesswrong/components/posts/PostsPage.jsx, packages/lesswrong/lib/components.js
The solution here:
* Create a copy of the HeadTags component.
* Remove the default image used for social media.
* Manually set the image for the homepate.
* All other pages do not have an image.
Testing:
* Use the facebook sharing debugger: https://developers.facebook.com/tools/debug/sharing/
* Verify that the homepage has the correct title, description, and has the same social media image
* Verify that posts have the correct title, description, but no social media image
* Verify that when testing with the facecbook sharing debugger, posts with images in them have that image used in the facebook preview.
=> Do not use a default image for social media sharing. Fixes #870

packages/lesswrong/components/posts/PostsPage.jsx
Pretty obvious, substring(300) does not do the same as substring(0,300).
=> Fix to description property for posts

packages/lesswrong/components/common/CloudinaryImage.jsx
This fixes the egregious styling problems introduced by the Cloudinary sizing refactor (images not staying inside their bounds), which was caused by accidentally replacing the `width` and `height` attributes on images with `width` and `height` attributes in CSS on the `style` attribute, which has higher precedence than regular CSS does.
There is still a significant glitch remaining, which is that the header images on sequences (eg `https://www.lesswrong.com/s/HXkpm9b8o964jbQ89`) should crop according to the browser width, but instead it's doing an aspect-ratio-changing scale. We could probably fix this using Cloudinary's client-hints support, as described [here](https://cloudinary.com/documentation/image_transformation_reference#width_parameter), but this isn't currently working; this may …
=> Fix sizing problems with CloudinaryImage

package.json, packages/lesswrong/components/common/CloudinaryImage.jsx
Having killed cloudinary-react meant losing some fancy size-detection stuff on sequences pages, which was fairly important. We can probably get that without the library (and get isomorphic SSR while we're at it), but the first attempt didn't do it, so revert temporarily until we figure that out.
=> Temporarily revert removal of cloudinary-react

packages/lesswrong/components/Layout.jsx, packages/lesswrong/components/common/HeadTags.jsx, packages/lesswrong/components/posts/PostsItem.jsx, packages/lesswrong/components/search/UsersAutoCompleteHit.jsx, packages/lesswrong/components/sequences/SequencesPage.jsx, packages/lesswrong/lib/collections/sequences/helpers.js, packages/lesswrong/lib/index.js, packages/lesswrong/lib/routes.js
Following the strategy of roaming around the site and code base looking for broken things that are quick to fix, and fixing them, without the overhead of going through the issue tracker or deciding whether they're worth it.
* Don't show "0 comments" on sequences (which can't be commented on)
* Remove accidentally-added rounding on PostsItem
* Adds a bunch of missing page titles
* Pointer style on users-search autocomplete
* Typography of sequence descriptions
=> Assorted fixes

packages/lesswrong/components/comments/recentDiscussionThread.jsx, packages/lesswrong/components/comments/recentDiscussionThreadsList.jsx
The intent here is that instead of displaying all recent posts, and then removing the ones with no comments, instead it only displays posts at all once the comments have loaded to avoid a weird flicker.
=> Recent Discussion posts loading should be less confusing

packages/example-forum/lib/components/posts/PostsDailyList.jsx, packages/lesswrong/lib/routes.js
Set page title. Enable SSR. When navigating (so SSR is unavailable), show a single loading indicator instead of a bunch of "No posts on <Date>" rows.
=> Fix Daily page jank

.meteor/versions, packages/lesswrong/package.js
Fix our ability to run CircleCI tests. Hopefully. Whether this PR is done is, funnily enough, indicated by CircleCI.
=> Hopefully fix CircleCI tests after Meteor upgrade

packages/lesswrong/components/Layout.jsx, packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx, packages/lesswrong/components/common/withDialog.jsx, packages/lesswrong/components/sunshineDashboard/ReportForm.jsx
A prototype in response to the architecture discussion we were having earlier. This adds a `withDialog` HoC, providing `openDialog` and `closeDialog` properties. Once a dialog is created, the component that created it can detach from the React tree, without affecting the dialog.
=> Add `withDialog` HoC and use it

packages/lesswrong/lib/collections/sequences/schema.js
Hides unintended sequences fields which showed `userId` fields to non-admin users
=> Adjust sequences form field visibility

packages/lesswrong/components/async/EditorForm.jsx
This disables SSR for the EditorForm, which I think is correct because it can cause various problems when rehydrated.
=> Hotfix for #1154

packages/lesswrong/lib/modules/callbacks.js
We are currently getting this error in the logs: 
Oct 23 08:05:11pm info Exception in defer callback: TypeError: Cannot read property 'length' of undefined at usersMatchingFilter.filter.u (packages/lesswrong/lib/modules/callbacks.js:238:29) at Array.filter (<anonymous>) at findUsersToEmail (packages/lesswrong/lib/modules/callbacks.js:236:42) at PostsCurateNotification (packages/lesswrong/lib/modules/callbacks.js:250:24) at packages/vulcan:lib/lib/modules/callbacks.js:179:18 at Array.forEach (<anonymous>) at packages/vulcan:lib/lib/modules/
I have no idea how that state could come to be, but this adds some defensive programming to avoid that.
=> Fix weird email bug?!?

packages/lesswrong/components/editor/EditorFormComponent.jsx, packages/lesswrong/components/form-components/MuiInput.jsx, packages/lesswrong/styles/main.scss
Fixes the height of the LaTeX editor in DraftJS. Fixes vertical alignment of inline LaTeX elements, at the cost of them being able to overflow and make the whole page scroll.
Fixes #1168. Fixes #1166.
=> LaTeX fixes

packages/lesswrong/components/users/UsersName.jsx, packages/lesswrong/lib/collections/users/custom_fields.js, packages/lesswrong/lib/modules/fragments.js
These changes make it so that when a full-name field is provided, it's displayed instead of the usual name on alignment forum (though the profile links and everything still go to the same place).
=> Add full name field for alignment forum import

packages/lesswrong/components/posts/PostsEditForm.jsx, packages/lesswrong/components/posts/PostsEditPage.jsx, packages/lesswrong/components/posts/PostsNewForm.jsx, packages/lesswrong/lib/components.js, packages/lesswrong/lib/routes.js
(Best viewed as squashed.)
Changes the post edit form submit button label to say "Publish" or "Publish Changes" (rather than "Save" in both cases) depending on whether it's a draft.
=> Editor publish label

packages/lesswrong/components/comments/CommentsItem/CommentBody.jsx, packages/lesswrong/components/comments/CommentsNode.jsx, packages/lesswrong/components/common/ContentItemBody.jsx, packages/lesswrong/components/posts/PostsPage.jsx, packages/lesswrong/lib/components.js
This patch makes it so that if a LaTeX block in a post or comment is wide enough to need a horizontal scrollbar, it gets expanded to a larger touch target and gets an indicator on the left/right sides to show that it's scrollable.
=> Add indicators for LaTeX horizontal scroll

packages/lesswrong/components/common/HeadTags.jsx
Works around a bug in react-helmet by giving `Helmet` a key that changes with every navigation, so that `Helmet.componentShouldUpdate` (which is crashy) doesn't get called. Fixes #865.
=> Fix crashes in Sequence navigation

packages/lesswrong/server.js
Based on slow GraphQL query times we've been seeing on Galaxy, I suspect that, although upgrading Meteor got us upgraded to node 8.12 on our local installs, Galaxy may still be giving us Node 8.11. Log `process.versions` during server startup so we can check.
=> Log node version during startup (to check if we're still on 8.11)

packages/lesswrong/lib/collections/comments/graphql.js, packages/lesswrong/lib/collections/comments/tests.js, packages/lesswrong/lib/collections/notifications/tests.js, packages/lesswrong/lib/collections/posts/tests.js, packages/lesswrong/lib/collections/users/tests.js, packages/lesswrong/lib/modules/alignment-forum/posts/tests.js, packages/lesswrong/lib/modules/alignment-forum/users/tests.js, packages/lesswrong/lib/modules/callbacks.js, packages/lesswrong/lib/search/utils.js, packages/lesswrong/testing/moderation/moderation.server.tests.js, packages/lesswrong/testing/utils.js
Fixes #1044 . This depends on a matching PR against our for of Vulcan, https://github.com/LessWrong2/Vulcan/pull/34 . This fixes flakiness in notification unit tests due to a race condition between tests and callbacks, and (on the Vulcan side) extends the API to make it easy to avoid similar race conditions in future unit tests.
=> Notification unit tests: fix race condition

packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx
=> Add tooltip for up-arrow on recent comments

packages/lesswrong/server/legacy-redirects/routes.js
This is an untested fix for LessWrong2#846. It seems not ideal that the new route is in the legacy-routes file.
=> Support /favicon.ico path

packages/lesswrong/components/posts/PostsItem.jsx, packages/lesswrong/styles/_clear-style.scss, packages/lesswrong/styles/_comments.scss, packages/lesswrong/styles/_global.scss, packages/lesswrong/styles/_localgroups.scss, packages/lesswrong/styles/_posts.scss, packages/lesswrong/styles/_sequences.scss, packages/lesswrong/themes/createThemeDefaults.js, packages/lesswrong/themes/stylePiping.js
Cleans up a lot of (but not all of) the weird CSS we have surrounding <a> tags. Fixes #1317, by no longer styling a:focus.
=> Anchor styles

packages/lesswrong/server/rss.js
The new format matches that of the tooltip that's displayed when you over the date on the post page. I think the time zone will usually be UTC for cloud RSS readers, though that's already the case.
Before: Published on Thu Nov 29 2018 09:32:54 GMT-0800 (PST)
After: Published on November 29, 2018 9:32 AM PST
I wonder whether there's a better way of getting the time zone in there.
=> RSS: Use a more-readable format for timestamps

packages/lesswrong/lib/collectionUtils.js, packages/lesswrong/lib/modules/connection_logs.js
Speeds up server startup, particularly the refresh that happens when you edit a file, by a modest amount. The gain is much larger if you're connected to a remote database.
=> Speed up server startup by preventing mongo from blocking

packages/lesswrong/components/Layout.jsx, packages/lesswrong/components/common/Footer.jsx, packages/lesswrong/lib/components.js
Fixes #1274. The purpose of this is to enable you to scroll a bit past the end, so you never have to read something jammed against the bottom of the screen.
=> Add the minimum viable page footer (150px whitespace)

packages/lesswrong/components/notifications/NotificationsMenu.jsx, packages/lesswrong/components/notifications/NotificationsMenuButton.jsx
Previously we didn't server-side render notifications, initially because everything was client-side only by default, and then because we thought there might be performance problems. This activates SSR for the notification bell, and the performance seems fine. (No slow queries, client-side scripts spend ~25ms on the notifications area during front page load.)
=> Server-side render notifications

packages/lesswrong/components/admin/AdminDashboard.jsx, packages/lesswrong/components/comments/CommentsNewForm.jsx, packages/lesswrong/components/posts/PostsNewForm.jsx, packages/lesswrong/components/questions/NewAnswerForm.jsx, packages/lesswrong/components/sunshineDashboard/AdminHome.jsx
Vulcan's `Components.ShowIf` is problematic in two ways. First, it has a `withCurrentUser`, hence a GraphQL queries, hence it's slow (on the order of 6ms per component instance). And second, it's confusing, and (in most of our usages), slightly wrong--it gets the number of arguments wrong in many cases, calling things like `Users.isAdmin(currentUser, currentUser)`behind the scenes. This doesn't have real consequences in any of our usages (extra arguments are ignored), but it's a trap.
Remove all usages of `Components.ShowIf`.
=> Eliminate all usages of Components.ShowIf

packages/lesswrong/lib/modules/alignment-forum/users/tests.js, packages/lesswrong/testing/server.tests.js
One file of unit tests (lib/modules/alignment-forum/users/tests.js) wasn't being imported, and thus wasn't being run. Also, it wasn't passing (due to a minor problem with the test, not with the thing being tested). Fix both of those.
=> Add and fix unit tests that weren't imported

packages/lesswrong/lib/collections/comments/callbacks.js, packages/lesswrong/lib/collections/comments/views.js, packages/lesswrong/lib/collections/notifications/views.js, packages/lesswrong/lib/collections/posts/custom_fields.js, packages/lesswrong/lib/collections/posts/views.js, packages/lesswrong/lib/collections/sequences/callbacks.js, packages/lesswrong/lib/collections/sequences/views.js, packages/lesswrong/lib/modules/alignment-forum/comments/callbacks.js, packages/lesswrong/lib/modules/alignment-forum/comments/views.js, packages/lesswrong/lib/modules/alignment-forum/posts/views.js
This is the followup to an earlier PR which gave boolean fields default values. It requires running the migration function from that PR (even if it was run after that earlier PR, because this one nonnullable-ifies another field).
=> Switch views from $in:[false,null] to false

packages/lesswrong/components/common/Home.jsx, packages/lesswrong/components/common/Meta.jsx, packages/lesswrong/components/posts/AllPostsPage.jsx, packages/lesswrong/components/posts/HomePostsViews.jsx, packages/lesswrong/components/posts/PostsList.jsx, packages/lesswrong/components/posts/PostsViews.jsx, packages/lesswrong/components/users/UsersProfile.jsx, packages/lesswrong/lib/collections/posts/views.js, packages/lesswrong/lib/components.js, packages/lesswrong/lib/i18n-en-us/en_US.js, packages/lesswrong/styles/_other.scss
Includes:
– updated PostsViews component, which lets users sort in different ways, and filter in different ways
– after some reflection, I left the curated/frontpage/all distinction as it current is, rather than trying to be clever with the new "toggle personal posts" checkbox. We can do that when we actually are ready for a major UI overhaul, for now it seemed least confusing to stick with the current paradigm
– I also added it to the /allPosts page (still currently not linked to from anywhere, but now is a pretty well-functioning page)
– I added a view for "recentComments" which sorts by lastCommentedAt. This was something I could imagine wanting with some frequency to see which of my own posts were recently discussed, and on the allPosts page would let you keep up with recent …
=> Sorting Posts (UserProfile + AllPosts)

packages/lesswrong/lib/collections/comments/callbacks.js, packages/lesswrong/lib/collections/posts/callbacks.js
The post/comment schemas we inherited from Vulcan/Example-Forum already had fields for a referrer and a user agent, but they weren't being filled in. The reason they weren't being filled in was because the Vulcan mutator callbacks weren't providing callbacks with the necessary information.
This is a pair of commits/PRs, one against Vulcan which adds that information, and one against LessWrong which uses it to fill in referrer and userAgent fields on posts and comments. This isn't used anywhere on the site directly, but is something we want for analytics; most notably, we want to know where comments/posts are posted from so we can better distinguish between LessWrong users and GreaterWrong users.
=> Record user-agent and referrer with posts

packages/lesswrong/testing/voting.tests.js
Fix #1244. The unit test Voting/batchUpdating/updates if post in the future was failing in a way where it would output the failure to stderr, rather than actually fail the tests. Also, the test was incorrect--its assertion that future posts should have their score updated was incorrect (they shouldn't have their score updated).
=> Kill a unit test that was pseudo-failing

packages/lesswrong/lib/collections/notifications/views.js, packages/lesswrong/lib/collections/posts/views.js
This (hopefully) fixes indexing issues introduced in/noticed after our last deploy to master.
=> Update posts default index, and a missing Notifications index

packages/lesswrong/lib/collectionUtils.js
Modifies ensureIndex so that if there's a preexisting index with the same name, but different keys, the old index gets dropped.
=> Handle index name conflicts

packages/lesswrong/themes/eaTheme.js
This just makes it so the EA forum doesn't get the "copy pasted text is bold" like we used to have.
=> Fix EA theme

package.json, packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx
ESLint got confused by (this.props.nestingLevel||1) as a default-value-for-missing-variable idiom, assuming that the expression was being used as a boolean rather than as an arithmetic value. Since the version of ESLint is unpinned, this was causing lint failures on CircleCI (but not on our dev machines, which were all still on a slightly out of date ESLint version which didn't have this warning).
=> Upgrade ESLint, fix a spurious warning

packages/lesswrong/lib/collections/users/callbacks.js
This makes the first user created on an empty database automatically (a) approved, and (b) a Sunshine. This gives a better development start-up experience (eg #1529 is someone getting tripped up by lack of this.)
=> Make first created user automatically approved and Sunshine

packages/lesswrong/lib/collections/comments/views.js, packages/lesswrong/lib/collections/posts/custom_fields.js, packages/lesswrong/lib/collections/posts/views.js
Requires matching Vulcan PR: https://github.com/LessWrong2/Vulcan/pull/58 , to make it possible to use `field: null` queries in Vulcan views and have them actually reach Mongo.
=> Views don't use $in:[false,null]

packages/lesswrong/lib/collectionUtils.js, packages/lesswrong/server/migrations/2019-01-30-migrateEditableFields.js, packages/lesswrong/server/migrations/2019-02-04-addSchemaVersionEverywhere.js
Updates to schema version stuff, in preparation for the content fields migration
=> Updates to schema version stuff

packages/lesswrong/lib/collectionUtils.js, packages/lesswrong/server/indexUtil.js, packages/lesswrong/server/migrations/2019-02-04-addSchemaVersionEverywhere.js, packages/lesswrong/server/migrations/index.js
Add schema-version migration script and reset-on-edit callback. This PR is against master, not devel, in preparation for our upcoming migration.
=> Add schema-version migration script, reset-on-edit callback

package-lock.json, package.json
Update Mingo to 2.2.11. This should fix a crash on iPhone 6S, #1570, with [this PR](https://github.com/kofrasa/mingo/pull/98).
=> Update Mingo to 2.2.11, fix #1570

packages/lesswrong/components/posts/PostSubmit.jsx
- events no longer have the option to submit for mod promotion (and correspondingly, won't have 'move to frontpage' on the sidebar, although in weird edge cases where we want something on frontpage we can still move it manually after the fact). Goal is to streamline the decisions a user (and sunshine) are expected to make, since events generally just don't go on frontpage anyhow
– clean up the styling for the new PostSubmit widget
=> Events can't be submitted to frontpage

packages/lesswrong/lib/collections/comments/callbacks.js, packages/lesswrong/lib/modules/alignment-forum/comments/callbacks.js, packages/lesswrong/lib/modules/alignment-forum/posts/helpers.js, packages/lesswrong/lib/modules/callbacks.js
Vulcan's mutation functions have a named argument "validate", which was never meant to be optional. However, due to the way it's used (as a boolean with truthiness), it was effectively treated as an optional parameter with a default value of false. No code within Vulcan relies on this, but some code within LessWrong does. Fix that dependency, by always providing the argument to `validate`. Paired with a Vulcan PR, which will change the default value from falsy to truthy.
=> Don't omit 'validate' option in various mutator calls

packages/lesswrong/components/sequences/BottomNavigationWrapper.jsx, packages/lesswrong/components/sequences/SequencesNavigation.jsx, packages/lesswrong/lib/collections/chapters/callbacks.js
– Removing a post from a sequence chapter will now properly remove that post's canonicalSequence data
– added withErrorBounary to sequence navigation components
=> Fix Removing Posts from Sequences

packages/lesswrong/components/users/UsersSingle.jsx, packages/lesswrong/lib/collections/users/helpers.js, packages/lesswrong/lib/routes.js
You can now reach a user's user page via /u/<slug> or /user/<slug> (rather than just /users/<slug>). If you type something which isn't a slug (in the sense of Utils.slugify), it will be slugified. All non-canonical URLs are Javascript redirects to the canonical URL.
Fixes #1619.
=> More flexible format for user page URLs

packages/lesswrong/lib/collections/posts/validate.js, packages/lesswrong/server.js, packages/lesswrong/server/scripts/validateDatabase.js
Adds a mechanism to extend `validateDatabase` with arbitrary custom validation functions. Adds one such validation function, which checks that every post with a `canonicalSequenceId` is contained in its canonical sequence.
=> Validate that posts are contained by their canonical sequence

packages/lesswrong/lib/editor/ellipsize.jsx
Utils.sanitize is stubbed out on the client, which is where this code mostly runs. This can cause SSR client render mismatches, and also causes a wrong impression of the html being sanitized on the client, when it isn't.
=> Remove all the useless sanitization in ellipsize.jsx

packages/lesswrong/components/posts/PostsCommentsThread.jsx
There was a bug where sometimes (maybe due to 503's?) the Comments query would return `null` for results instead of an empty array. This caused a bunch of bugs with sometimes empty comment sections taking forever to load, until you refresh the page. This makes it so that it renders more robustly when it gets null instead of an empty array.
=> Properly render comment section when no comments are returned

packages/lesswrong/lib/karmaChanges.js
`lastOpened` is actually the end-date of the range that was shown the last time the karma-change notifier was opened, which, if you're in daily mode, is likely to be the last daily reset time. So to do the batch-preservation thing, we need a `>=` comparison rather than `>`.
Also, if you've picked realtime mode and never opened it before, show 24h of karma changes rather than all time. (After the first time you dismiss, it goes back to showing "changes since you last opened it")
=> Karma change date ranges: fix batch-rollover, limit first realtime to 24h

packages/lesswrong/components/posts/PostsItem2.jsx, packages/lesswrong/components/posts/PostsItemComments.jsx
Note: this just copies over stuff from old PostsItem, which I think was in turn mostly copied over from PostsPage (with a small amount of cleanup). It really feels like the plumbing for "marking a post as read" should live in a HoC and I shouldn't have to do more than just call a function that the HoC adds a a prop.
Can talk through that on Monday.
But meanwhile, the above code seems to work. (Haven't rigorously thought it through, although have tested the obvious use cases)
=> PostsItem2 comments marks as viewed / turns grey

packages/lesswrong/lib/collections/posts/tableOfContents.js
Inspired by noticing a janky table of contents on [this post](https://www.lesswrong.com/s/HXkpm9b8o964jbQ89/p/ENBzEkoyvdakz4w5d), a heading-styled block which has no text can't be a heading.
=> ToC: Empty blocks can't be headers

packages/lesswrong/components/localGroups/CommunityHome.jsx, packages/lesswrong/lib/collections/users/custom_fields.js, packages/lesswrong/lib/modules/fragments.js
Remove the allPostsView from the user profile form (it isn't meant to be exposed this way, and doesn't have an appropriate widget). Add missing notification settings to the `UsersProfile` fragment, so that their true state is shown and it's possible to set them to false.
=> User profile form fixes

packages/lesswrong/server/posts/out.js
Currently our #2 slow query is in the linkpost redirector. When you click on the outgoing link in a linkpost, it goes to lesswrong.com/out?url=... which records the click and forwards you to the destination. This is a feature we inherited from vulcan-starter/example-forum.
At some point, the link-post URL generation must have been broken and not URL-encoded the destination URL, because the redirector is designed to handle URLs which haven't been escaped properly. Where "designed to handle" means "searches the database for link-posts which fuzzy-match the destination URL". The fuzzy-matching is quite resistant to indexing, and also completely unnecessary. Remove that.
=> Fix a pointlessly slow query in /out redirector

.meteor/versions, packages/lesswrong/server/cronUtil.js
Fixes #1659. Also reduces the rate of score-update queries from 2/min/server to 2/min.
The story here is that `synced-cron` switched maintainers, and so `percolatestudio:synced-cron` was stuck on the last version by `percolatestudio`. Which was from 2014, and was missing a number of important bug fixes. Migrate to the new version, under the new maintainer.
Requires a synchronized Vulcan PR.
=> Upgrade synced-cron across a maintainer change

packages/lesswrong/server.js, packages/lesswrong/server/robots.js, public/robots.txt
Vary robots.txt based on a setting, because we want development servers (lessestwrong.com, baserates.org) to not be indexed by search engines. This should be accompanied by a config change on those development servers.
=> Vary robots.txt based on a setting

packages/lesswrong/components/comments/CommentsNewForm.jsx
There is a current IE11 and Edge 17 (not the latest version) bug that causes forms to fail. I don't think we can easily fix it, but this at least prevents the bug from exploding the whole page.
=> Add error boundary around new-comment form

packages/lesswrong/lib/collections/notifications/custom_fields.js, packages/lesswrong/lib/modules/fragments.js, packages/lesswrong/server/callbacks.js
It was useless because it included spam, and it was on-site notifications, when you could just go to the allPosts page and get a similar thing but much better organized.
Also remove the "Notifications for new users" setting, which was admin-only and literally did nothing.
=> Remove useless "Notifications for new posts" setting

packages/lesswrong/server/scripts/algoliaExport.js, packages/lesswrong/server/search/utils.js
The main change here is that `algoliaCleanIndex` now uses `browseAll`, an export API rather than the query API. Using the query API for this didn't work, because you couldn't get more than 1000 results that way. However, `browseAll` doesn't support pagination, so this requires holding the entire index (and some transformations of it) in RAM at once, which might turn out to be a problem.
Lightly tested by creating and removing posts and inspecting the index on a small DB.
=> Algolia indexing scripts: fix cleaning to work on large DBs, more logging

packages/lesswrong/server/posts/out.js
In a previous PR, I modified the `/out` redirector so that its query would be indexable. In this PR, I... actually add the index.
=> Add index for posts out redirector

package.json, packages/lesswrong/components/async/localStorageHandlers.js, packages/lesswrong/components/editor/EditorFormComponent.jsx
Makes it so that the code which saves unfinished posts and comments to localStorage works with all the editors (DraftJS, markdown, HTML) rather than just DraftJS. Also strips away a wrapper library around localStorage, and changes error handling so that browsers not having localStorage is only a `console.warn` rather than a `console.error` (because the wide variety of ways of reporting that there's no localStorage, was polluting Sentry).
=> Local storage: save markdown/HTML, don't pollute Sentry

packages/lesswrong/components/editor/EditorFormComponent.jsx
Admins used to have a form-field that allows them to directly edit the HTML of posts. We removed that with the form-rework, and this now adds an admin-only dropdown menu that allows you to select from the different document format options and choose whichever one you want to edit.
=> Add an admin-only editor-type-select menu to Form components

.github/CONTRIBUTING.md
This saves newcomers to the project from having to read irrelevant information before they create an issue or pull request.
=> Delete VulcanJS-specific contributing guidelines

packages/lesswrong/components/search/UsersSearchAutoComplete.jsx, packages/lesswrong/components/search/UsersSearchInput.jsx, packages/lesswrong/lib/collections/users/custom_fields.js
– REQUIRES CORRESPONDING VULCAN PR
– removes unused scss class
– adds a tooltip to the bannedPersonalUsersIds field on users
=> BannedUsers tooltip

packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx, packages/lesswrong/components/comments/RecentCommentsItem.jsx, packages/lesswrong/components/posts/MoveToDraft.jsx, packages/lesswrong/components/posts/PostsDailyList.jsx, packages/lesswrong/components/posts/PostsDay.jsx, packages/lesswrong/components/votes/withVote.js, packages/lesswrong/lib/collections/comments/tests.js, packages/lesswrong/lib/collections/users/tests.js, packages/lesswrong/lib/components.js, packages/lesswrong/lib/modules/alignment-forum/posts/tests.js, packages/lesswrong/lib/modules/alignment-forum/users/callbacks.js, packages/lesswrong/testing/metatest.tests.js, packages/lesswrong/testing/moderation/moderation.server.tests.js
There's a false-positive Deepscan issue in `components.js`, which keeps appearing on PRs as "1 fixed, 1 new" because its line number changes. Move it to the top so its line number stops changing. Also fix a few other random easy Deepscan issues.
=> Fix Deepscan issues that keep resurfacing

packages/lesswrong/lib/collections/users/custom_fields.js
Currently anyone is allowed to access someone else's vote-counts. This seems mildly bad, so this fixes it.
=> Don't allow guests to see user's votecounts

packages/lesswrong/lib/collections/revisions/resolvers.js
Recently introduced defensive programming in `dataToDraftJS` caused it to throw an exception when `data` and `type` were null/undefined. Put in a special case so that doesn't happen.
=> Fix a crash on null revisions, seen in devel

packages/lesswrong/components/common/SubscribeWidget.jsx
Under some uncommon circumstances, `SubscribeWidget` renders its icons in the wrong font size. This is because of sensitivity to precedence order between `font-size` attributes in its builtin styles (controlled by a prop) and the material-icons class. Make this consistent by moving it all to JSS and adding a `!important`.
=> Fix a CSS load-order dependency in SubscribeWidget

packages/lesswrong/styles/_editor.scss
See commit messages for details.
I didn’t run the site locally to test these changes, since it was hard to set up. These changes and screenshots are based on editing the CSS live using Firefox’s Inspector.
> <img width="736" alt="before" src="https://user-images.githubusercontent.com/79168/55432793-d37ec500-5561-11e9-8aaa-1f031c877734.png">
> <img width="737" alt="after" src="https://user-images.githubusercontent.com/79168/55432796-d5488880-5561-11e9-9d29-26362e031585.png">
=> Improve new comment placeholder message

packages/lesswrong/server/debouncer.js, packages/lesswrong/server/notificationCallbacks.js
Curation emails go through the debouncer, introducing a 20-minute delay. Servers with the `testServer` configuration option set don't handle debouncerEvents, so curation emails reliably get sent from the production server (rather than the dev server, which can't actually send emails.)
Fixes #1786.
=> Test server email handling

packages/lesswrong/components/editor/EditorFormComponent.jsx
Fix a server-side exception in EditorFormComponent, introduced by my previous autosaving PR. It doesn't have any obvious symptoms, but is easy to fix.
=> Fix an SSR crash in EditorFormComponent

packages/lesswrong/components/Layout.jsx, packages/lesswrong/components/common/Home2.jsx, packages/lesswrong/components/sunshineDashboard/SidebarActionMenu.jsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.jsx
This makes it so:
– sunshine sidebar only appears on the home page (where it's least 'in the way' of whatever else I'm trying to do on LessWrong)
– reverts some of the previous changes I'd made to the sidebar to make it easier for me to process spam, making it require juuuust enough attention that I can't accidentally get into a rhythm where I purge things accidentally (this should only affect admins who've enabled 'show post preview by default' in the sidebar, which presumably is just me)
=> SunshineSidebar on home only

packages/lesswrong/server/voteServer.js
When you're rate-limited, you can still self-upvote and cancel votes. Throw a better error type if you try to vote while not logged in.
=> Voting rate limit tweaks

packages/lesswrong/components/editor/EditorFormComponent.jsx
Fixes #1835. The bug was introduced in https://github.com/LessWrong2/Lesswrong2/pull/1709 .
=> Fix EditorFormComponent emptying when changing editor type

packages/lesswrong/components/comments/CommentsViews.jsx, packages/lesswrong/components/posts/PostsNewForm.jsx, packages/lesswrong/server/debouncer.js
PR https://github.com/LessWrong2/Lesswrong2/pull/1838 replaced the AlignmentForum setting with a forumType setting, but missed four places that needed updating. This broke unit tests, but CircleCI was broken for us that day to a problem on CircleCI's end, so we didn't notice.
=> Fix AlignmentForum->forumType setting change

packages/lesswrong/components/posts/PostsPage/PostsAuthors.jsx, packages/lesswrong/components/posts/PostsUserAndCoauthors.jsx, packages/lesswrong/components/users/UserNameDeleted.jsx, packages/lesswrong/components/users/UsersName.jsx, packages/lesswrong/components/users/UsersNameDisplay.jsx, packages/lesswrong/lib/components.js
Refactors user-name display handling a little bit, in the process making UsersNameDisplay and UsersName null-safe where they weren't before.
Observed Sentry crash: https://sentry.io/organizations/lesswrong/issues/976402041/?environment=production&project=1301611&query=is%3Aunresolved&statsPeriod=14d&utc=true
=> Fix Sentry crash with null user

packages/lesswrong/components/posts/TableOfContents/TableOfContentsList.jsx
Some browsers support scrollTo, but not with an options object like we are providing. This wraps the relevant call in a try-catch and makes sure not to call `preventDefault` when the call to scrollTo fails
=> Scroll to fallback

packages/lesswrong/lib/collections/notifications/tests.js
Hopefully this fixes the intermittent unit test failure we were seeing in this test. Not tested locally, and because this is a stochastic failure we won't know for sure whether it worked for awhile, but since the change is only in a test it's very low risk.
=> Fix race condition that intermittently caused unit test failures

packages/lesswrong/components/common/Section.jsx, packages/lesswrong/components/posts/PostsPage/PostsPage.jsx
This makes it so that when we don't have a ToC for a post, we center the post at small screens instead of weirdly offsetting it to hold space for a ToC that isn't there. 
The best way of doing this would be with flexboxes, but this was the smallest change that I could find that would make it work without having to rewrite all of our section-related code.
=> Properly center posts without ToCs

packages/lesswrong/server/voteServer.js
This query was selecting on `{documentId, userId}` when our index was for `{documentId, userId, cancelled}`. The latter makes more sense anyways, so update the query.
=> Tweak cancel-votes mongo query to better use indexes

packages/lesswrong/lib/collections/posts/views.js
The default view checks whether the `userId` term is set and, if so, adds `hideAuthor: false` to the selector. This means that, any time you would want `userId` in an index, you also want `hideAuthor`.
=> Put hideAuthor field in indexes that have userId

packages/lesswrong/components/users/UsersAccountMenu.jsx
When you don't have a ReCAPTCHA API key (eg, a dev install), make the user menu not crash.
=> Disable ReCaptcha instead of crashing when not configured

packages/lesswrong/themes/stylePiping.js
Posts have a font height of 18.2px and a line-height of 26.0px, for a font-height-to-line-height ratio of 0.7. Post highlights and answers, on the other hand, had a font height of 16.25px but the same line-height of 26.0px, a ratio of 0.625. This adjusts the line-height from 1.6em to 1.8rem (note the change of units), making the new line height 23.4px and the font-to-line-height ratio 0.69.
=> Change line-height of post highlights, answers

packages/lesswrong/components/common/HomeLatestPosts.jsx
`HomeLatestPosts` had some DOM nesting violations (`<p>` in `<p>`, and `<ul>` in `<p>`). This didn't cause any symptoms in production, but did cause a pile of noisy console errors in development. Fix those.
=> Fix nesting errors in HomeLatestPosts

package.json
When trying to run unit tests locally, I was getting
```
Error: ENOENT: no such file or directory, open '/home/jbabcock/repositories/Lesserwrong/alt-LessWrong2/node_modules/bcrypt/build/Release/.deps/home/jbabcock/repositories/Lesserwrong/alt-LessWrong2/node_modules/bcrypt/lib/binding/bcrypt_lib.node.d'
```
Upgrading bcrypt to the latest version (from 3.0.1 to 3.0.6) and running npm install seemed to fix it.
=> Upgrade bcrypt dependency to 3.0.6

packages/lesswrong/lib/editor/utils.js
This changes our draftJS to HTML conversion to work properly with empty paragraphs and move it closer to the WYSIWYG paradigm. 
I intentionally made a change that would not change historical document rendering, just to avoid all the pain associated with that. 
I tested this with the following edit operations: 
+ Add an empty paragraph
+ Add an empty paragraph with only an image
+ Add an empty paragraph with only LaTeX
+ Add a non-empty paragraph
+ Add a non-empty paragraph with LaTeX
+ Add an empty heading (this does not actually follow WYSIWYG, but it never did and this doesn't make it worse) 
+ Add an empty divider
=> Render whitespace for newly edited draftJS documents

packages/lesswrong/components/sequences/SequencesGrid.jsx
This HoC loads the top 10 sequences (with the default view, no filters). But the component is taking a set of sequences to render directly, not getting them via the HoC, so this query's results aren't going anywhere.
Remove the unnecessary query, slightly speeding up library and user pages.
=> Don't randomly load and throw out the top 10 sequences

packages/lesswrong/components/comments/recentDiscussionThread.jsx, packages/lesswrong/components/common/withRecordPostView.jsx, packages/lesswrong/components/posts/PostsItem.jsx, packages/lesswrong/components/posts/PostsItem2.jsx, packages/lesswrong/components/posts/PostsPage/PostsPage.jsx
The function `handleMarkAsRead` and its associated pile of support HoCs was copy-pasted four times: in `PostsItem`, `PostsItem2`, `recentDiscussionThread`, and `PostsPage`. That copy-pasted code was built on Redux, which goes away with the Apollo 2 upgrade. So before doing that part of the migration, we need to undo this bit of technical debt.
Adds a HoC `withRecordPostView`, and uses it to replace the four copy-pastes. The interface is slightly awkward; it adds a bunch of HoCs plus a pseudo-method, which takes a props object to get the props that the other HoCs added. It'll get mostly-rewritten with Apollo 2 anyways, so there's not much point micro-optimizing the interface just yet.
=> Factor four copy-pastes of post-view recording into a HoC

packages/lesswrong/components/posts/PostsPage/PostsTopSequencesNav.jsx
Sequence top-navigation can go between sequences in a collection again. Fixes a bug introduced in https://github.com/LessWrong2/Lesswrong2/pull/1537 . (Sequence *bottom* navigation still can't, tragically.)
=> Top-navigation can go between sequences in a collection

packages/lesswrong/lib/collectionUtils.js, packages/lesswrong/server/cronUtil.js
This defers index-building and cron-job setup until 15 and 20 seconds after server startup, respectively. This is mainly for the benefit of test environments, where you want the server to be responsive to a page load as soon as possible after initiating a rebuild.
=> Slightly faster test cycle

packages/lesswrong/components/questions/PostsPageQuestionContent.jsx
Turns out by default we only render 10 answers. We don't seem to have run into this problem before, but it's visible on the open problems in rationality question, so seems important to fix
=> Increase number of answers rendered by default

packages/lesswrong/lib/collections/posts/callbacks.js
=> scoreExceeded30 is unused, scoreExceeded30Date is correct

packages/lesswrong/components/common/Meta.jsx, packages/lesswrong/lib/collections/posts/views.js
Meta page use PostList2 — fixes text overflow issue.
Exclude Meta posts from sunshine sidebar.
Y'all have meta posts, so I'm surprised you haven't seen the second error at least.
=> Meta bugfixes

packages/lesswrong/components/posts/PostsNewForm.jsx, packages/lesswrong/components/users/AccountsResetPassword.jsx, packages/lesswrong/components/users/LoginPage.jsx, packages/lesswrong/components/users/LoginPopupLink.jsx, packages/lesswrong/components/users/UsersAccountMenu.jsx, packages/lesswrong/components/users/WrappedLoginForm.jsx, packages/lesswrong/lib/collections/users/callbacks.js, packages/lesswrong/lib/components.js
This adds a "Subscribe to curated posts" checkbox to the signup form. Requires matching Vulcan PR, https://github.com/LessWrong2/Vulcan/pull/75 , to add the extension point for custom fields to `vulcan-accounts`.
The signup checkbox sets the value of the existing "Email me new posts in Curated" setting. Regardless of whether you check the subscribe box, you will now get an email verification request email on signup. Users need to click the verification link to actually start getting emails.
Important decision: What is the default value of the checkbox? What is the wording of the label on the checkbox?
Less important, but still todo: Make the checkbox label use a nicer font (rather than just the browser default).
=> Add a "Subscribe to curated posts" checkbox to the signup form

packages/lesswrong/components/posts/PostsItem2.jsx
Same as the last PR, except this one is against master instead of devel.
=> Hotfix: Abbreviate long coauthor lists in PostsItem2

packages/lesswrong/components/posts/PostsListSettings.jsx, packages/lesswrong/components/users/UsersProfile.jsx
Fixes two bugs: 
+ Broken all posts page on Alignment Forum because we didn't specify filters
+ Broken user pages for some select users who have an account with a duplicate slug
=> Alignment Forum allposts and user-profile pages hotifx

packages/lesswrong/server/editor/make_editable_callbacks.js
Fixes error that happened on login. This was disabled in
https://github.com/LessWrong2/Lesswrong2/commit/a403c705db7ca1ef95471e10096a3a70c07b9e5a#diff-f9f3038a8715bba754e6ce9d49adba11R88
but I don't see it causing test failures now and suspect it maybe have been in error.
=> Reenable skipping of async function in user creation

packages/lesswrong/components/sunshineDashboard/SunshineNewUserCommentsList.jsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUserPostsList.jsx, packages/lesswrong/lib/modules/fragments.js
Previously due to fragment bug you couldn't actually turn this feature on and off without Robo3T.
I also optimized the rendering of the content sample slightly so that I could skim it, click on a link to the post/comment if I wanted, *without* that link looking "green" (which was the heuristic I used to detect spam when skimming the sunshine sidebar)
=> Improve Ray's Special Snowflake Sunshine Options

packages/lesswrong/lib/modules/accounts/configuration.js
Before: When you log in with the form, your login token gets a date-stamp. If it's older than 90 days, you have to log in again. Visiting the site with a saved login does not reset the date-stamp.
After: As above, but replace "90 days" with "100 years". Tested by editing the database to back-date login tokens into the distance, expired past.
Fixes #1908.
=> Login tokens no longer expire after 90 days

packages/lesswrong/server/scripts/exportPostDetails.js
`exportPostDetails` is the function written to get the Forum Prize candidates every month, which may be useful elsewhere. This month it had some spam, because it was including posts by unreviewed authors. I believe it is generally more useful when exporting a list of posts to have the authors be reviewed, so I think this should be the default.
=> exportPostDetails only reviewed

packages/lesswrong/components/comments/CommentsNode.jsx, packages/lesswrong/components/comments/recentDiscussionThreadsList.jsx
I found myself slightly annoyed sometimes when browsing recent discussion in braindead mode, that a) a lot of things have no text, b) as soon as I click an unread thing and then refresh the page it disappears, c) somewhat too much stuff going on for each post.
This shifts the SingleLineComments admin mode so that it only shows up to 4 comments, but one of them is always expanded, which changes the feel back to something closer to what it was originally
=> RecentDiscussion Tweak

packages/lesswrong/lib/collections/posts/custom_fields.js, packages/lesswrong/server/partiallyReadSequences.js, packages/lesswrong/server/recommendations.js
Merge only after the `denormalizeReadStatus` migration has been run.
=> Use ReadStatuses collection for faster post-read-status queries

packages/lesswrong/server/search/utils.js, packages/lesswrong/server/search/utils.tests.js, packages/lesswrong/testing/server.tests.js
addOrUpdateIfNeeded used to return any errors encountered, but now throws them. Patch a fix with a try catch around it. This was written to get me through the post export, but seems somewhat useful.
=> Fix problems with algolia exporting

packages/lesswrong/components/common/LinkCard.jsx, packages/lesswrong/components/sequences/SequenceTooltip.jsx, packages/lesswrong/components/sequences/SequencesGridItem.jsx, packages/lesswrong/lib/components.js
Adds a hover-over tooltip to SequencesGridItem, containing a truncated version of the sequence description. Fixes #2080.
=> Sequences grid hover

packages/lesswrong/components/questions/RelatedQuestionsList.jsx, packages/lesswrong/lib/collections/posts/views.js
Related questions now appear in your draft section on userProfile
Drafts were also rendering weird on a posts's related questions list. Our query doesn't filter out drafts. It probably should, but also seemed like the related questions list shouldn't bother trying to render posts that you aren't allowed to see for whatever reason
=> related questions in draft, fix draft-bug in list

packages/lesswrong/lib/collections/users/views.js, packages/lesswrong/server.js, packages/lesswrong/server/scripts/oneOffBanSpammers.js
Add script to ban users who meet some selection criteria, which I imagine I might be a desire someone might have in the future.
More likely to be used change: if user has a bio, include them in review. Spammers seem to be using their bio to advertise spam, and currently it won't get reviewed.
=> Script for one-off spam ban, include bio hackers in review

packages/lesswrong/components/common/TabNavigationMenu.jsx
Changes the name because Archive sounds old and fuddy duddy and too much like "Library" and not at all like "keep up with daily stuff"
=> Archive to All Posts

packages/lesswrong/components/posts/PostsPage/PostActions.jsx, packages/lesswrong/lib/collections/comments/schema.js, packages/lesswrong/lib/collections/comments/views.js, packages/lesswrong/lib/collections/posts/callbacks.js, packages/lesswrong/lib/collections/posts/fragments.js, packages/lesswrong/lib/collections/posts/schema.js, packages/lesswrong/lib/collections/users/callbacks.js
Adds a new bit of admin-only UI to PostActions to make a post be the short-form feed for a user. Adds a shortform flag on posts and comments, and callbacks to keep it up to date.
(This will be followed up with UI that makes a shortform page, puts shortform stuff on All Posts, and a front-page comment-box for short-form writing which makes you a shortform post if you don't already have one.)
=> Shortform flags

packages/lesswrong/components/sequences/SequencesGrid.jsx, packages/lesswrong/components/sequences/SequencesGridItem.jsx
This fixes some small issues with the mobile rendering of sequences grid items. In particular an overflow that can happen at smaller device sizes.
=> Fix mobile rendering of sequences grid items

packages/lesswrong/lib/routes.js
In Vulcan, if you create a route with a name that collides with an existing route, this silently replaces removes that route. This is a bug in Vulcan, but we weren't triggering it before. Recently we added a `/faq` route, but it was created using a copy-paste that was incompletely edited, so it had a name conflict with the existing `about` route.
=> Fix broken `/about` route

packages/lesswrong/components/posts/AllPostsPage.jsx
[This commit](https://github.com/LessWrong2/Lesswrong2/commit/cbea1c9bd8d88c3a4eff075b9d79a8d3da431481#diff-cfbff8e7785fd5fe676d53f66d057485) removed the `settingsIcon` class from `AllPostsPage` when it still had references pointed to it, which resulted in console errors on that page and a minor bit of broken styling (its color no longer changed with hover-over). Put the class back to fix that.
=> Fix error message and hover-color of all-posts-page settings icon

packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx, packages/lesswrong/components/comments/RecentCommentsItem.jsx, packages/lesswrong/components/comments/ShowParentComment.jsx, packages/lesswrong/styles/_comments.scss
Puts back a couple lost features: the tooltip, active styling. Makes `RecentCommentsItem` use it, so it's un-diverged from `CommentsItem`. Untangle and document a very complicated boolean expression.
=> Refactor around `ShowParentComment`

packages/lesswrong/components/comments/CommentsNewForm.jsx, packages/lesswrong/lib/collections/comments/callbacks.js
This is a bug we inherited from Vulcan's example-forum, which made `topLevelCommentId` a form field instead of filling it in server side.
=> Fill in topLevelCommentId in a callback instead of client-side

packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx
As a consequence of eliminating RecentCommentsItem, parent-comments gained the ability to be truncated sometimes. But they *didn't* gain the corresponding ability to click to expand, and, being truncated is not a desirable feature in that context. So, parent-comments are now never truncated.
=> Fix parent-comments sometimes being truncated and not expandable

packages/lesswrong/lib/collections/posts/views.js
On the all-posts page, sorting by Daily first groups by day, then sorts by something. Before, it was sorting within days by `score`, which is a sort of time-discounted karma. But this doesn't make sense because age is already accounted for in the grouping, so it winds up just being confusing--older days are sorted by karma, while recent days are sorted sort-of by karma but with glitches.
Change the within-day sort to baseScore, so it's no longer confusing.
=> Daily view: within days sort by baseScore, not score

packages/lesswrong/lib/collections/users/custom_fields.js
The sort-order of fields is on the Edit Account page is now slightly less ridiculous.
=> Change order of fields on Edit Account page

packages/lesswrong/lib/collections/users/views.js
Sunshine sidebar users used to be sorted by `createdAt`, then it was changed to sort by whether they've commented and/or posted, but this accidentally lost the createdAt tiebreak from the default view. Put that back, so that when the list of unprocessed users is longer than the maximum list size (which it is, because we don't have a snooze-review button), we can see newly created accounts that haven't posted.
=> Sunshine sidebar users are sorted by createdAt

packages/lesswrong/components/titles/PostsPageTitle.jsx
Bug introduced by me in the Apollo 2 branch. I'm surprised eslint wasn't able to catch this one; "not all paths return a value" is a super-standard warning.
=> Fix in subtitle on some pages

packages/lesswrong/components/posts/PostsTimeframeList.jsx
PostsTimeframeList was
> setting the after prop at the same time as the timeframe, but the state is dirty and takes a few milliseconds to catch up, during which time the PTL has asked for 1200 days worth of posts.
Now we store the relevant information on the state so the updates are synchronous.
=> [hotfix] TimeframeList - store timeframe and before on state to match after

packages/lesswrong/components/users/UsersEditForm.jsx
I saw an intercom exchange where Aaron tried to reset a user's password and them saying that they hadn't gotten it. I had a sense of regret when I realized what must have happened, and thought "That button is bad and we should feel bad."
On UserEditForm, `currentUser` will not be the user being edited in the case where the current user is an admin. The component does not have access to the user email at all in admin mode unfortunately. In the fullness of time we could fix that, currently we disable it
=> Remove broken password reset button in admin view

packages/vulcan-lib/lib/client/apollo-client/apolloClient.js
When you load the front page (or any page, really), the response you get from the server includes an initial state for the Apollo cache, which is sufficient to rerender the page without any further involvement from the server. However, Apollo would re-fetch the results anyways, performing a duplicate query and doubling the server-side cost of most things. We couldn't fix this in Apollo 1, but in Apollo 2, we can, with the `ssrForceFetchDelay` option.
This changes the behavior of the `network-only` and `cache-and-network` fetch modes so that, if a component uses them during the first 500ms since Apollo initialized, it will skip the network request and use the cache.
(My very-noisy measurement is that this reduces client-side Javascript front page execution time by 8%, server-side by much …
=> Prevent duplicate queries after SSR

packages/lesswrong/components/Layout.jsx
Saves the time zone in a cookie. This prevents post-load changes on the allPosts page, and also saves the compute cost of some rerendering (about 100ms on the front page, development mode).
=> Save timezone in a cookie

packages/lesswrong/server/callbacks.js, packages/vulcan-lib/lib/modules/callbacks.js
Vulcan's `removeCallback` expects a function name, rather than a function reference. This is a crazy API that doesn't play nicely with anonymous functions. Make it expect references, rather than names.
=> removeCallback cleanup

packages/lesswrong/components/comments/CommentsNode.jsx
I'd recently changed SingleLineComments so that they always were expanded if they were unread. This resulted in sad experiences for Oli when he'd click on one of them and then all the others would suddenly collapse.
Most of the reason I made the change was to improve the reading experience on the Post Page. At some point we should do a more extensive refactor of how SingleLineComments and truncation work, and meanwhile this was the simplest change.
=> improve Oli's expanding comment experience

.meteor/packages, .meteor/versions
A previous PR removed vulcan:routing but left it in .meteor/packages, which, depending on your environment, may result in picking up and trying to use an outdated version from the path, and crashing on startup.
=> Update packages list to reflect removed vulcan:routing

packages/lesswrong/components/editor/EditTitle.jsx, packages/lesswrong/components/users/UsersMenu.jsx
This improves rendering on small devices for users with big usernames by having their username line-break, and also makes the post-title break again, which stopped for someone reason at some point in the last few weeks
=> Make Post title and username break

packages/lesswrong/components/shortform/ShortformPage.jsx
Bug introduced in https://github.com/LessWrong2/Lesswrong2/pull/2228/files - tried to make the page narrower, but made it fixed-width in a way that made it wider than the screen on mobile.
=> Fix shortform page width on mobile

packages/vulcan-lib/lib/modules/callbacks.js, packages/vulcan-lib/lib/server/mutators.js
Fixes two bugs in Vulcan's callback handling that were preventing some callbacks from being run properly: 
* Passing in the newDocument instead of the old document for sync callbacks
* Not formatting the async-hooknames correctly, such that mixed-case async hooks would not properly run
=> Fix Vulcan callback handling

packages/vulcan-lib/lib/server/apollo-server/apollo_server.js
I don't think we should have this in a setting, and the setting was also not registered. 
This fixes editing of some very large posts.
=> Increase body parser memory limit

packages/lesswrong/components/alignment-forum/AlignmentForumHome.jsx
Alignment Forum has two copies of the Recent Discussion section title. Introduced by an incorrect refactor in https://github.com/LessWrong2/Lesswrong2/commit/7fa2d41b968459279d77589b37765ad39f120a89#diff-e3f6859f8e2781d48964be2176e5f96b .
=> Fix double header on AF

packages/lesswrong/lib/components.js, packages/vulcan-lib/lib/modules/components.js
Overlaps https://github.com/LessWrong2/Lesswrong2/pull/2317 but also handles the comment box (which was tricker).
=> Component splitting fixes

package.json, packages/vulcan-lib/lib/modules/intl_polyfill.js, packages/vulcan-lib/lib/server/intl_polyfill.js
Fixes a crash-on-start which was a byproduct of `intl-locales-supported` moving to Typescript, and accidentally changing their API in a minor version, combined with Vulcan code importing it in a nonstandard way. Vulcan imports with `require('intl-locales-supported')` and expects to get a function. v1.0 of that package did a `module.exports = areIntlLocalesSupported`. v1.4.5 did something that compiles to `export default function areIntlLocalesSupported...`, which makes the require call return an object with a field named default, instead of a function.
Change the import to modern style, and pin v1.4.5. Requires an `npm install`.
=> Fix import of intl-locales-supported and update it

packages/lesswrong/components/comments/CommentsItem/CommentShortformIcon.jsx, packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx, packages/lesswrong/components/comments/SingleLineComment.jsx
I think it's important for the shortform Icon to always appear (even on singleLine comments or the "shortform post"), so that users can more easily learn what it means.
I notice a potential hackiness-sense here, where this (as well as a previous edit I made to Components.UsersNameDisplay) are moving towards a pattern of "the 'simple' prop means 'remove tooltips and links and stuff'"
The main purpose of this is so that you can easily re-use stylings of components on SingleLineComment. 
It feels a bit hacky partly because the name doesn't actually tell you what it's for, and partly because if we start using this pattern all over the place it might get harder to change. It's only the second instance of it so far so maybe we can wait for third-time-to-refactor, but seemed like it warranted …
=> always show shortform icon

packages/lesswrong/components/posts/PostsItemIcons.jsx
Note: this is definitely a place where I suspect that the correct solution is to revamp how the OmegaIcon actually works so that it doesn't require weird special cases everywhere. I'm wary of getting sucked into that rabbit hole. If people think it's highish priority I can do that tho.
=> OmegaIcon on PostsItemIcons

packages/lesswrong/components/sunshineDashboard/AFSuggestPostsItem.jsx
This partially fixes the Move to Alignment sunshine-sidebar bug. Unfortunately there's a weird _additional_ bug, wherein clicking the button triggers this error:
```
VM2632 modules.js:168846 Error: Invalid query operator '$near' detected
at err (VM2632 modules.js:139714)
at assert (VM2632 modules.js:139619)
at Query._processOperator (VM2632 modules.js:142251)
at VM2632 modules.js:142239
at each (VM2632 modules.js:139736)
at VM2632 modules.js:142238
at each (VM2632 modules.js:139736)
at Query._compile (VM2632 modules.js:142226)
at new Query (VM2632 modules.js:142214)
at belongsToSet (VM2683 vulcan_lib.js:353)
at handleUpdateMutation (VM2688 vulcan_core.js:3282)
at VM2688 vulcan_core.js:3209
at Array.forEach (<anonymous>)
at updateEachQueryResultOfType (VM2688 vulcan_core.js:3192)
at VM2688 …
```
=> remove incorrect field from AFSuggestPostsItem

packages/vulcan-core/lib/modules/components/App.jsx
If the route is unparseable, that's a 404. Only log this in Sentry if we're on the client, not if this is SSR. This is a compromise between catching broken links, and spam in Sentry; crawlers and bots that try lots of invalid URLs generally won't execute Javascript (especially after getting a 404 status), so this should only log when someone reaches a 404 with an actual browser.
Unfortunately that also means it doesn't look broken resource links (ie images), but we can't really distinguish between "post contained a broken image link and it mattered" and "bot tried a weird URL and it didn't resolve to anything".
=> Only report 404s (from unparseable route) on client, not from SSR

packages/lesswrong/components/comments/CommentWithReplies.jsx, packages/lesswrong/components/comments/CommentsItem/CommentsItemDate.jsx, packages/lesswrong/components/shortform/ShortformPage.jsx, packages/lesswrong/lib/collections/comments/fragments.js, packages/lesswrong/lib/collections/comments/views.js, packages/lesswrong/lib/collections/posts/permissions.js
Notes:
adds withErrorBoundaries for defensive-programming-reasons, and also fixes the immediate issues that caused the defensive programming to be needed
Admins (and now sunshines) can see shortform comments from shortform posts that have been set to draft, but it'll at least be a bit more clear because the post title on the commentsItem will now say "[Draft]"
"testLimit" wasn't used anywhere, pretty sure we don't need, I assume I put it there for some testing related reason and shouldn't have merged it
=> fix various bugs relating to shortform and permissions

packages/lesswrong/components/async/CKCommentEditor.jsx, packages/lesswrong/components/async/CKPostEditor.jsx
Fixes a crash that can sometimes happen when you submit a post, and makes comment editors properly initialize with the comment data when editing
=> Two small fixes for CKEditor

packages/lesswrong/lib/modules/utils/schemaUtils.js
In the last Vulcan/Apollo upgrade, the meaning of the `document` argument to `<collection>.update.after` changed from referring to the old document (without the update applied), to referring to the new document. This broke the callback in `denormalizedCountOfReferences`, which tries to compare the old and new versions of a document to see if the new one counts while the old one didn't, and uses this to update users' post counts. The API change meant that it was comparing the new version of the document to itself, instead, so posts didn't get added to users' post count when edited to no longer be drafts.
Tested: Without this patch, post counts don't increment/decrement when undrafting and re-drafting posts; with this patch, they do.
After applying, we'll want to run
``` …
```
=> Fix incremental update of denormalized-count fields (broken in Vulcan/Apollo upgrade)

packages/vulcan-users/lib/modules/permissions.js
The way Users.owns was written, if the user is null (logged out), it will dereference null, throw an exception, and then immediately catch it. This is a mildly expensive operation, and Users.owns gets called a lot of times. The practical upshot of which is that, for logged out users, the server was spending 350ms of front-page server-side rendering time just in Users.owns, throwing and catching internal exceptions.
Convert that into a proper null check, reducing the time spent in this function to approximately zero.
=> Speed up logged-out SSR

packages/lesswrong/components/comments/CommentsNode.jsx, packages/lesswrong/components/linkPreview/PostLinkPreview.jsx
This fixes two issues with the new comment previews:
1. Comment previews were (in some cases) defaulting to rendering as a SingleLine instead of full comment
2. comment permalinks (a la "?commenId=blahblah") weren't working because I was calling them from params instead of query.
3. I had accidentally passed the "to" field into an 'a' tag instead of 'href', so defaultLinkPreviews weren't actually working as links
=> commentPreview bug fixing

packages/lesswrong/components/posts/PostsItem2.jsx, packages/lesswrong/components/posts/PostsItemTooltipWrapper.jsx, packages/lesswrong/components/posts/PostsTitle.jsx, packages/lesswrong/lib/components.js
Fixes:
– the thing where the new hoverPreview was visible when hovering over expanded comments in the PostsItem2 (now, the hover target area is only the top row of the component)
– when the PostsTitle expands, it no longer extends it's grey background beyond the edge of the component
=> Posts item updates

packages/lesswrong/server/draftConvert.jsx, packages/lesswrong/server/editor/make_editable_callbacks.js, packages/lesswrong/themes/stylePiping.js
This for now just improves the handling of spoiler tags added with draft-js and leaves everything else the same. Implemented by just wrapping those adjacent spoiler tags into a wrapping element and then copying the greaterwrong CSS for handling spoiler tags.
=> Improve how we handle spoiler tags

packages/lesswrong/components/linkPreview/PostLinkPreview.jsx, packages/lesswrong/components/posts/PostsPreviewTooltip.jsx
– replaces "LW" and "EA" with a degree symbol (°)
– adjusts the breakpoints for hiding and shrinking the home page post previews
– adjusts spacing of the titles on tooltips
=> PostPreview style tweaks

packages/lesswrong/components/async/CKCommentEditor.jsx, packages/lesswrong/themes/stylePiping.js
First pass attempt the style ckEditor to match our theme. Oli and I had some disagreements about the best way to interface with ckEditor's theme (in most cases I found it much easier to just work directly with the css classes, rather than trying to use ckEditor's variables). 
I expect some followup discussion about the best way to proceed here.
=> ckEditor Styling Tweaks

packages/lesswrong/server/editor/make_editable_callbacks.js, packages/lesswrong/themes/stylePiping.js
This one was surprisingly difficult, largely because of differences between the API I was expecting (jQuery) and the API provided by cheerio (a weird partial reimplementation of jQuery, where not everything works), leading to several false starts. Alas. But it works now.
=> Fix wrapSpoilerTags

packages/lesswrong/themes/createThemeDefaults.js, packages/lesswrong/themes/lesswrongTheme.js, packages/lesswrong/themes/stylePiping.js
This PR simplifies how spoiler tags work, while ensuring that they work on codeblocks
It makes a somewhat opinionated decision to not fully support the old spoiler styles (you now have to hover over each individual block to see it, rather than seeing all of it at once), because I thought the upkeep of maintaining the old style wasn't worth it.
...
The Great Sundering of the Fancy Links
I also noticed that Jim's recent update to spoiler backgrounds (leaving the "hovered over" spoiler light-grey to distinguish it from nearby non-spoiler text), didn't work nicely with our dotted-line-links. In a fit of rage, I removed the dotted line links, because they just really didn't seem like they were worth all the headache they've caused.
I experimented with some alternate link-colorings that …
=> improve spoiler tags (also incidental purging of the fancy links)

packages/lesswrong/components/posts/PostsPage/PostActions.jsx, packages/lesswrong/components/posts/SubmitToFrontpageCheckbox.jsx, packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.jsx, packages/lesswrong/lib/collections/users/helpers.js, packages/lesswrong/themes/eaTheme.js
- Moderators may promote get's a few extra words[1] and css styling is changed
- EA Forum gets a "move to community" button in the classification sidebar
- If you want to classify a post through the post menu items, there's now a warning if the user doesn't want that
- Not related to submitToFrontpage, the EA Forum gets a check so that people can moderate their personal blog without moderating the Community page
[1] My guess is that y'all would have had the full "Moderators may submit to frontpage" if it weren't for how ugly it looked to have it wrap below the checkbox. I fixed it so it doesn't wrap below the checkbox, so I have submitted the suggested new wording, feel free to revert it.
=> Small fixes to submitToFrontpage

packages/lesswrong/lib/collections/databaseMetadata/collection.js, packages/lesswrong/lib/collections/databaseMetadata/schema.js, packages/lesswrong/lib/index.js, packages/lesswrong/server.js, packages/lesswrong/server/startupSanityChecks.js
This adds a `databaseMetadata` collection, which can contain a database ID, and an `expectedDatabaseId` config setting, which can also contain a database ID. If either is present, both must be present and they must match, or else the server will abort on startup.
=> Add databaseMetadata collection and expectedDatabaseId config setting

packages/lesswrong/lib/index.js, packages/vulcan-core/lib/modules/default_resolvers.js, packages/vulcan-users/lib/modules/resolvers.js
So, turns out that for import-order reasons, the users collection has a completely separate resolver file, that doesn't share any code with the default resolvers, causing it to not respect the checkAccess function. This hasn't been an issue until now, until I tried to fix the problem where we don't want to show deleted users, and that not working reliably for some reason. 
Ideally we would factor out all the resolver code to also use the default resolvers, but this is the minimal fix that addresses the current problem.
=> Make the user resolvers respect the checkAccess function

packages/lesswrong/server/emailComponents/NewPostEmail.jsx
In `NewPostEmail`, there was a missing check for null. The post is never null, but the `withDocument` can in principle be in a loading state. Prior to the Apollo major version upgrade, this never happened; prerendering got the document and provided it on the first pass. After the Apollo major version upgrade, it seems this broke.
This should have been very obvious in Sentry; `sendPostByEmail` in `notificationCallbacks.js` calls `Sentry.captureException` once per failed email, which should be a lot. But somehow, this only generates a single Sentry error, so it blended in; I was able to find it by searching by time range for exactly when the email should've gone out. (Here it is: https://sentry.io/organizations/lesswrong/issues/1167078516/events/22a7a559afb444709a3cae38aa9f1806/?end=2019-10- …
=> Maybe fix curation emails

packages/lesswrong/components/linkPreview/PostLinkPreview.jsx
Left-aligns hover-previews, rather than center-aligns, so that it's always technically possible to mouse over them (even when split awkwardly over two lines)
This will be important once we put bookmark-buttons on hover previews
=> Multi line hover preview bug

packages/lesswrong/components/recommendations/RecommendationsList.jsx, packages/lesswrong/lib/registerSettings.js, packages/lesswrong/server/emailComponents/EmailWrapper.jsx, packages/lesswrong/server/emailComponents/PrivateMessagesEmail.jsx, packages/lesswrong/server/emails/renderEmail.js, packages/lesswrong/server/notificationCallbacks.js, packages/lesswrong/themes/stylePiping.js
Emails on the EA Forum were coming out green. We now pull email theming from the forumTheme file through the stylePiping file.
Also introduce a `siteNameWithArticle` setting. To quote:
> Your site name may be referred to as "The Alignment Forum" or simply "LessWrong". Use this setting to prevent something like "view on Alignment Forum".
**Note that this requires y'all to set this setting for the Alignment Forum**
Finally, I was surprised to learn that only admins are receiving the message notification emails. Given that they're pretty useful for users who don't check the site as often as the most core power users, I suggest through this PR that we enable them for all users.
=> Add theming to emails

packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx, packages/lesswrong/components/comments/CommentsItem/CommentsItemDate.jsx, packages/lesswrong/components/common/SearchBar.jsx, packages/lesswrong/components/editor/EditUrl.jsx, packages/lesswrong/components/messaging/ConversationPage.jsx, packages/lesswrong/components/posts/ShowOrHideHighlightButton.jsx, packages/lesswrong/components/search/UsersSearchInput.jsx, packages/lesswrong/components/sunshineDashboard/SunshineCommentsItem.jsx, packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsItem.jsx, packages/lesswrong/components/sunshineDashboard/SunshineNewCommentsItem.jsx, packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.jsx, packages/lesswrong/lib/collections/posts/custom_fields.js, packages/lesswrong/lib/collections/users/custom_fields.js, packages/lesswrong/styles/_forms.scss, packages/lesswrong/styles/_sequences.scss, packages/lesswrong/themes/stylePiping.js, packages/vulcan-forms/lib/components/FormGroup.jsx, packages/vulcan-forms/lib/stylesheets/style.scss
Removes the right/left padding from default form groups. Instead, you now have the option of passing default form groups a "paddingStyle" attribute if it's appropriate for the form you're building.
Unrelatedly migrates a bunch of icons from the old style to the new style
=> Form UI rework + migrating icons away from font

packages/lesswrong/components/editor/EditorFormComponent.jsx
– makes the "you last edited in a different editor" red, so that the "click here" button can actually stand out as a click-target. (I'm not attached to this color scheme, it was just the easiest one I could do that worked with minimal changes)
– I added the editor type to the handleEditorOverride function, so that it'd actually fetch the corresponding editor data instead of deleting everything. But this seems like a weird thing to have existed in the first place and I notice I'm confused. @Discordius thoughts?
=> Fix editor switching bugs

packages/lesswrong/components/comments/CommentsItem/CommentsItemDate.jsx, packages/lesswrong/components/posts/ShowOrHideHighlightButton.jsx, packages/lesswrong/components/search/UsersSearchInput.jsx, packages/lesswrong/components/sunshineDashboard/AFSuggestUsersItem.jsx, packages/lesswrong/components/sunshineDashboard/SidebarAction.jsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.jsx, packages/lesswrong/components/sunshineDashboard/SunshineReportedItem.jsx
I took a look at each spot where I had previously changed something from `"<Icon>[text]</Icon>"` to "<NameOfIcon/>", looking for any issues that may have come up.
Classes of things that came up:
– places where previously it'd been necessary to specify "!important" on icon-styles were no longer necessary, and I removed that after doublechecking it rendered correctly
– Sunshine viewable <SidebarAction> was still rendering things inside a nested "`<Icon>`" component, which worked okay but I removed to avoid any potential future issues of colliding styles, while also removing the overriding fontSize.
– after removing the nested `<Icon>` from `<SidebarAction>`, I found a few sunshineSidebar icons that I hadn't actually switched from old `<icon>text</icon>` style icons. I then did so, and …
=> go over icon changes

packages/lesswrong/components/posts/BookmarkButton.jsx, packages/lesswrong/components/posts/BookmarksList.jsx, packages/lesswrong/components/recommendations/RecommendationsAndCurated.jsx, packages/lesswrong/components/users/UsersMenu.jsx, packages/lesswrong/lib/collections/users/custom_fields.js, packages/lesswrong/lib/modules/fragments.js, packages/lesswrong/lib/modules/utils/schemaUtils.js
Changes bookmarkedPostIds to bookmarkPostsMetadata (moving from an array of string ids to objects, so that we can add future metadata such as snooze)
=> bookmarkMetadataSchema

packages/lesswrong/components/users/UsersProfile.jsx
Fixes issue #2474 by allowing you to uncheck 'show low karma posts' on a user's profile page.
- AllPostsList, where the equivalent checkbox works correctly, has the ‘Show Low Karma’ checkbox switches `query.karmaThreshold` between `DEFAULT_LOW_KARMA_THRESHOLD` and `MAX_LOW_KARMA_THRESHOLD`, and decides whether it's checked based on `query.karmaThreshold`. 
I’ve implemented a similar behavior in UserProfile, but defaulting to showing low karma (where AllPostsList defaults to not doing so).
Question: what if `query.karmaThreshold` is some other value that `DEFAULT_LOW_KARMA_THRESHOLD` or `MAX_LOW_KARMA_THRESHOLD`? A user can change the url by hand easily enough. For now I went with the conservative option of just matching the behavior we have in AllPostsList.
Also, I noticed that for the …
=> UsersProfile gets currentShowLowKarma from query

packages/lesswrong/components/sunshineDashboard/SunshineNewUserCommentsList.jsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUserPostsList.jsx, packages/lesswrong/lib/collections/posts/views.js
In SunshineNewUserPostsList and SunshineNewUserCommentsList, fixes:
– comments now show a post title, and link properly to the comment in question (instead of just linking to the top-level post)
– shows when comments have been deleted
– Includes events in SunshineNewUserPostsList
=> Fix sunshine NewUser links in the expand-by-default mode

packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx, packages/lesswrong/components/comments/CommentsNode.jsx, packages/lesswrong/components/comments/ShowParentComment.jsx
Addressing a few UI concerns of Ruby's:
– single line comments are now spaced out a bit
– "show parent" buttons now change to say "hide parent" with a rotated arrow to be a bit more clear
=> Tweaks to Recent Discussion UI

packages/lesswrong/components/comments/CommentsItem/CommentsMenu.jsx, packages/lesswrong/components/comments/CommentsItem/ReportCommentMenuItem.jsx, packages/lesswrong/components/localGroups/LocalGroupPage.jsx, packages/lesswrong/components/notifications/SubscribeTo.jsx, packages/lesswrong/components/posts/PostsPage/PostActions.jsx, packages/lesswrong/components/posts/ReportPostMenuItem.jsx
Adds an optional icon for the subscribe buttons, which changes from "outlined" to "filled" depending on subscription status.
Also re-arranges the subscription icons slightly so they aren't above "edit" menu items.
=> Subscription Icons

packages/lesswrong/components/async/CKPostEditor.jsx, packages/lesswrong/components/editor/EditorFormComponent.jsx
I accidentally pushed a commit directly to devel instead of making a PR
This commit undoes the changes from that commit.
The commit was intending to fix the issue where ckEditor sometimes gets access to old drafts from DraftJs. This was because when you switch editors, at the time it checks for drafts, it hasn't actually updated the editorType yet. (This may have been causing other errors?)
I fixed that by a) manually passing through the new editorType, and b) to be safe, also in CkPostEditor manually checking that "data" was a string.
=> revert accidental devel PR

packages/lesswrong/components/editor/EditorFormComponent.jsx
It was accidentally targeting multiple ckEditor type-boxes, and unfortunately the ckEditor css classes didn't offer natural additional specificity.
=> Fix overly large reply box in ckEditor comments

packages/lesswrong/components/async/CKPostEditor.jsx, packages/lesswrong/components/editor/EditorFormComponent.jsx
This fixes a bug where ckEditor would sometimes offer you the chance to load a saved draft from localstorage, but it'd be a saved draft from another editor-type (generally ckEditor). This was because at the moment you switch editors it's still in the process of switching editors and doesn't have access to the new editor type.
This PR fixes the bug, and adds some defensive programming around it:
1) initializeText now takes an "editorType" parameter that overrides which editor the localstorage should refer to (preventing the bug)
2) ckEditor checks that the data it's been passed is actually a string before using it to initialize, so if in the future it gets passed an object or whatever it won't choke on it.
=> Ck editor won't use DraftJS saved data

packages/lesswrong/styles/_sequences.scss, packages/lesswrong/themes/alignmentForumTheme.js, packages/lesswrong/themes/eaTheme.js, packages/lesswrong/themes/lesswrongTheme.js, packages/vulcan-forms/lib/components/FieldErrors.jsx, packages/vulcan-forms/lib/components/FormErrors.jsx
Fixed a weird mis-application of the sequence-editor-title style (which was getting applied to post-editor-title field)
Also made all errors red, and started migrating them towards JSS in the process
=> improve styling for errors

packages/lesswrong/components/form-components/MuiTextField.jsx, packages/vulcan-ui-bootstrap/lib/components/forms/FormComponentInner.jsx
The form fields were shifting to a "mobile" looking layout much earlier than necessary.
The "clear" button for select forms also needed some extra room, so shrinking the width.
Also removed a "javascript:void(0)" that was causing a harmless but annoying error message
=> Form Updates

packages/lesswrong/server/draftConvert.jsx, packages/lesswrong/themes/lesswrongTheme.js, packages/lesswrong/themes/stylePiping.js, packages/vulcan-lib/lib/server/utils.js
– sanitization no longer removes figures, and lets figures set their style attribute (allows for ckeditor image resizing)
– removed some of the ckEditor styling on images so that they look more similar between the editor and postPage
=> image resizing works in ckeditor

packages/lesswrong/components/editor/EditorFormComponent.jsx
We had previously made ckEditor clear itself upon submit, so that when people submit shortform posts they don't see a dangling copy of their post.
This triggered errors when in collaborative mode, which is supposed to never manually set it's data.
This PR makes it so that the editor only clears itself when in non-collab mode.
=> fixSetDataError

packages/lesswrong/components/editor/EditorFormComponent.jsx
Pretty self explanatory. This adds localStorage to ckEditor. 
In practice, this means that localStorage works normally for *non*-collaborative ckEditor. For collaborative ckEditor, it'll get overridden by the latest cloud version of the document. But, if you want to replace whatevers-on-the-cloud with whatevers-in-localStorage, you can un-share the document and it'll revert to a non-cloud version.
Also fixes what I assume would have been a (rare) bug where the markdown localstorage was comparing itself to the html localstorage. (I think in practice the "oldVersion == newVersion?" check always returns true because it's only triggered on an "onChange", and the contents are basically never identical. But seemed worth fixing while I was at it)
=> Implement localStorage for ckEditor

packages/lesswrong/server/pingbacks.js
htmlToPingbacks was accidentally using lodash instead of underscore for a utility function, and throwing an error due to  a mismatch of syntax. This was causing PostSubmit to fail.
The error was only being thrown on the client, and less conveniently formatted than usual. 
This PR replaces the "_.find" with an "array.includes", and also adds a try/catch with error logging so any future errors in htmlPingbacks don't break post submission
=> Pingbacks bug

packages/lesswrong/components/posts/PostsPage/PostsPage.jsx
Since there is currently no way of accessing read time and word count on mobile, due to that information currently being primarily displayed on hover-over effects, I think we should display that info at the top of the post-item.
=> Show read time for posts on mobile

packages/lesswrong/components/notifications/NotificationsItem.jsx
Previously, when you clicked on a notification, the `onClick` handler would override the usual `onClick` handler of the `Link` component, causing the component to behave like a native `a` tag, instead of a `Link` tag. 
This PR completely replaces the navigation with manual history operations, restoring the intended functionality.
=> Fix bug in notification scrolling

packages/lesswrong/themes/stylePiping.js
Previously, ckEditor used pBody style, which removes botto-margins from the last p-block in a list. For some reason this resulted in ckEditor having a weird "inner scrollbar", presumably because ckEditor's height was set expecting a slight bottom margin on the final element.
=> ckEditor fix weird inner-scrolling bug

packages/lesswrong/components/editor/EditorFormComponent.jsx
CkEditor was behaving sluggishly when the post you're editing got long. I moved the "setCkEditor" function behind a _.throttle
=> Throttle setCkEditor

packages/lesswrong/lib/collections/revisions/resolvers.js, packages/vulcan-lib/lib/server/utils.js
The previous attempt to remove blockquotes via "sanitize" didn't work because they had to be removed from the allowedTags, as well as added to nonTextTags. 
This new version is a bit simpler – I'm fairly confident it only needs to do remove blockquotes and images. (It turns out images are not included by default in sanitizeHtml, so they were automatically removed when I streamlined the setup here to use sanitizeHtml.defaults.allowedTags)
Codeblocks are fine to include because we just wanted to strip the formatting, which htmlToText already does.
=> remove blockquotes from singleLineComments

packages/lesswrong/server/emailComponents/EmailComment.jsx, packages/lesswrong/server/notificationTypesServer.jsx
Fix crash in comment-email rendering. Caused by insufficient testing after the last round of last-minute changes.
=> Fix crash in comment-email rendering

packages/lesswrong/components/common/HeadTags.jsx, packages/lesswrong/components/titles/PostsPageTitle.jsx, packages/lesswrong/lib/routes.js
This PR does three things: 
+ Restore a default behavior of the HeadTags component to properly handle a passed `title` property
+ Have the sequence route use the PostsPageHeaderTitle component
+ Modify the PostsPageHeaderTitle component to deal with the parameter names from the sequences route
Together these three changes fix invalid `title` tags that were present on the `s/sequenceId/p/postId` routes and the `rationality/slug`, `hpmor/slug` and `codex/slug` routes.
=> Fix route, title and subtitle handling for sequences posts

packages/lesswrong/lib/notificationTypes.jsx
The bug here was that the `newEvent` notification type wasn't attached to its config setting, so notifications of that type always used the global default setting, which is onsite-only.
=> Fix event-notification emails

packages/lesswrong/lib/collections/posts/callbacks.js, packages/lesswrong/lib/collections/posts/fragments.js, packages/lesswrong/lib/collections/posts/schema.js, packages/lesswrong/lib/collections/posts/views.js, packages/lesswrong/server/migrations/2019-11-04-postsModifiedAtField.js
It was getting annoying to find drafts I had recently worked on but created awhile ago, so I added a "modifiedAt" field to posts and now sort drafts by it.
=> sort drafts by modifiedAt

packages/lesswrong/components/Layout.jsx, packages/lesswrong/components/notifications/NotificationEmailPreviewPage.jsx
I realized right after merge that the previous PR still had a question for the reviewer in the comments. And apparently there was another one in there too.
=> Remove pr questions in TODOs

packages/lesswrong/server/editor/make_editable_callbacks.js
Previously, the post-version-incrementor was sorting the existing revisions by version
=> version incrementer uses editedAt

packages/lesswrong/components/comments/ModerationGuidelines/EAModerationGuidelinesContent.js, packages/lesswrong/components/comments/ModerationGuidelines/LWModerationGuidelinesContent.js
Follow LW and move to commenting guidelines that fit in a reasonably sized preview box without truncation.
=> Slim EA commenting guidelines

packages/lesswrong/components/editor/EditorFormComponent.jsx, packages/lesswrong/themes/eaTheme.js
If we're branding the editor as LessWrong Docs, don't show ckEditorMarkup to the user. I also use the name EA Forum Docs depending on forumType.
=> Display names for editors

packages/lesswrong/server/migrations/2019-05-01-migrateSubscriptions.js
This migration caused LW to have to recover from backups. The EA Forum would like to run this migration without using backups. @jimrandomh you were close, instead of `documentId`, it was `itemId`.
=> Fix subscription migration

packages/lesswrong/components/posts/AllPostsPage.jsx, packages/lesswrong/components/posts/PostsTimeframeList.jsx
Adds a few optional parameters to the AllPosts page (which later we can add proper UI for)
– Restores the karmaThreshold parameter on AllPosts (which used to work, and I then I think was accidentally replaced with hardcoded constants)
– adds an optional "reverse" parameter, which reverses the ordering of the timeblocks (used in conjunction with the recently added "after" and "before" parameter, which lets you specify the range of timeblocks to display)
– adds a "includeShortform" option which can be set to false, to hide shortform posts
=> Update AllPosts options

packages/lesswrong/components/Layout.jsx, packages/lesswrong/components/comments/CommentsItem/CommentsItem.jsx, packages/lesswrong/components/comments/RecentDiscussionThreadsList.jsx, packages/lesswrong/components/comments/SingleLineComment.jsx, packages/lesswrong/components/common/SectionFooter.jsx, packages/lesswrong/components/common/TabNavigationMenu/menuTabs.jsx, packages/lesswrong/components/localGroups/LocalGroupPage.jsx, packages/lesswrong/components/posts/Nominations2018.jsx, packages/lesswrong/components/posts/PostsItem2.jsx, packages/lesswrong/components/posts/PostsList2.jsx, packages/lesswrong/components/recommendations/Recommendations2018Review.jsx, packages/lesswrong/components/recommendations/RecommendationsAlgorithmPicker.jsx, packages/lesswrong/components/recommendations/RecommendationsAndCurated.jsx, packages/lesswrong/components/recommendations/RecommendationsList.jsx, packages/lesswrong/components/users/UsersProfile.jsx, packages/lesswrong/lib/collections/posts/views.js, packages/lesswrong/lib/components.js, packages/lesswrong/server/recommendations.js
– CommentsItem-Nomination UI now links to the /nominations page
– /nominations page now has a RecentDiscussion section
– /nominations page now displays nomination counts, default sorted by "fewest"
– Frontpage replaces "From the Archives" with "The LessWrong 2018 Review" section
=> 2018 Review UI updates

packages/lesswrong/components/editor/EditTitle.jsx, packages/lesswrong/components/editor/EditorFormComponent.jsx
Fix some visual/layout problems with forms, particularly the `EditTitle` component.
* Replaced double-bottom-border in `EditTitle` with single-bottom-border, to match post pages
* Got rid of spurious vertical scroll arrows
* Changed vertical sizing of the ask-a-question dialog to prevent overlap
Before:
After:
=> Visual fixes to EditTitle

packages/lesswrong/components/tagging/AddTag.jsx, packages/lesswrong/lib/collections/tagRels/views.js
Sort tags by descending relevance on post pages and in post footers. In the add-tag search popup, hide the search results until you start typing a query. Autofocus the search box when you click Add Tag (this one turns out to be surprisingly complicated).
=> Tagging tweaks

packages/lesswrong/server/notificationTypesServer.jsx
=> In shared-on-draft email notification, use correct link if post is a linkpost

packages/lesswrong/lib/editor/ellipsize.jsx
At some point during a truncation-refactor, it lost the ability to check if the truncated comment was actually long enough to warrant truncation. This adds a check for that back in.
=> fix truncation

package.json
When the webserver talks to mongodb, it uses a protocol called BSON (Binary jSON). By default, it parses and serializes this protocol using Javascript, which involves lots and lots of slow memory allocations. But there's a native-code library for doing that, which is significantly faster. Depending on `bson-ext` is sufficient without any code changes; the mongodb driver detects that it is available and uses it.
=> Add bson-ext, a native-code library for faster mongodb protocol serialize/deserialize

packages/lesswrong/components/localGroups/LocalGroupsItem.jsx, packages/lesswrong/styles/_editor.scss, packages/lesswrong/themes/alignmentForumTheme.js, packages/lesswrong/themes/createThemeDefaults.js, packages/lesswrong/themes/lesswrongTheme.js
This override's ckEditor's z-index, so that it works properly on MuiModal components. 
During the process of creating this, I originally tried making changes to MuiModal's JSS overrides, which then resulted in a minor refactor of how we handle shared overrides between LW, EA and AF, and removed some (AFAICT?) no longer used JSS. 
I ended up keeping those changes since they seemed net positive.
=> fix modal zIndex, refactor sharedOverrides

packages/vulcan-core/lib/modules/components/App.jsx
Fix sending of navigation events. What was happening here was, `subscribeLocationContext` didn't actually have the reference-stability properties it was supposed to, because it was using the same incrementally-updated object as `locationContext`, and `locationContext`'s update would happen first.
=> Fix navigation-event sending

packages/lesswrong/themes/createThemeDefaults.js, packages/lesswrong/themes/stylePiping.js
ckEditor blockquotes were having trouble with looking the correct size, in the editor, because ckEditor had been imposing some of it's own styles.
This was tricky to fix because our custom ckEditor styles could _either_ be layered on top of postStyles, or commentStyles, which manually applied different styles to blockquotes. But... that styling doesn't _appear_ to be necessary?
Not sure about chesterton's blockquote styling.
=> ckEditor blockquotes

packages/lesswrong/components/posts/PostsPage/PostsPage.jsx, packages/lesswrong/components/posts/PostsPage/PostsPageDate.jsx
The comment-count info on mobile post pages were being split over multiple lines, which was hard to read and click. I made all the secondary-info into inline-blocks so that "no wrap" worked properly, and then rearranged them slightly:
=> rearrange mobile secondary postPage info

packages/lesswrong/components/comments/RecentComments.jsx, packages/vulcan-core/lib/modules/containers/withMulti.js
For certain lists, it's pretty important that when you click on a link, and then press back, you can scroll back to the place in the list that you previously were located at. This was previously prevented by us resetting the limits on various lists when the component unmounts, but this PR adds an option to instead save that state in a URL parameter, allowing that state to be preserved between navigations.
=> Add option to make loadMore work with query parameters

packages/lesswrong/components/form-components/PostsListEditor.jsx, packages/lesswrong/components/search/PostsSearchAutoComplete.jsx, packages/lesswrong/components/search/SearchAutoComplete.jsx, packages/lesswrong/components/search/SequencesSearchAutoComplete.jsx, packages/lesswrong/components/search/UsersSearchAutoComplete.jsx, packages/lesswrong/components/tagging/AddTag.jsx, packages/lesswrong/components/tagging/FooterTagList.jsx, packages/lesswrong/lib/components.js, packages/lesswrong/styles/_posts.scss
In order to test an alternative post-footer layout with pingbacks and prev/next sequence navigation, I wanted to create a sequence on my local dev instance. But putting posts into a sequence uses `PostsSearchAutoComplete` which doesn't work without Algolia, which I didn't have on that particular local test server. This issue has bothered me enough times in enough contexts that I decided to fix it.
There are three autocomplete-using components that were copy-paste-modified from each other, `{Posts,Sequences,Users}SearchAutoComplete`, and a similar but not copy-pasted `AddTag`. I refactored the three components to share code, via a new component `SearchAutoComplete`. For all four components I added a simple fallback where, if you don't have Algolia enabled, it provides a janky text box into …
=> Refactor auto-complete form components

packages/lesswrong/components/comments/CommentsNode.jsx, packages/lesswrong/components/comments/RecentComments.jsx, packages/lesswrong/components/review/Reviews2018.jsx, packages/lesswrong/lib/collections/comments/views.js
– was accidentally sorting "top" comments in reverse order
– fixed some mobile jank
– truncated comments in the nominations/reviews section, which required fixing some issues with how truncation and single-line comments interacted
=> UI fixes for review page

package.json, yarn.lock
Upgrade from `popper.js` 1.15 to 1.16, triggered by an indirect dependency via `react-bootstrap`, introduced a bug: hovers with `bottom-end` placement (including, prominently, on PostsItem) are offset by the size of the thing they're a hover on. Pinning to 1.15 fixes the issue.
=> Pin popper.js to 1.15 to work around their regression

package.json, yarn.lock
Note that the yarn.lock is important here; absent a yarn.lock, `^3.0.0` can be satisfied by 3.1.2 (the broken one). We can't just pin an old version because there are a bajillion subpackages and we haven't identified which subpackage is responsible.
=> Revert Apollo upgrade to un-break comments

packages/vulcan-users/lib/modules/resolvers.js
This prevents a duplicate load/unnecessary database roundtrip later.
=> Use loader for currentUser

packages/lesswrong/components/questions/AnswersList.jsx
Broken by me during hookification, as I used `useList` which doesn't exist instead of `useMulti` and eslint can't catch broken cross-package imports. Oops.
=> Fix AnswersList

packages/lesswrong/components/editor/EditorFormComponent.jsx
This was broken by commit 34b5958a728a4ff2bce76ee13841a2ae4b6d2bda . The issue is that, unlike `setHtml`, `setMarkdown` and `setCkEditor`, `setDraftJs` is setting a state which contains not just the document being edited, but also some internal details of the editor (including the set of loaded plugins). This refactor added a check for spurious changes, by comparing the editor contents, but draftJS was calling its `onChange` on initialization to add its plugins.
=> Fix broken draftJS editor

packages/lesswrong/components/comments/RecentDiscussionThread.jsx, packages/lesswrong/components/posts/PostsItem2.tsx
This just captures the data on where a post-view event is clicked, just so we can differentiate between the different events in the future.
=> Capture post-view event type

packages/lesswrong/components/common/HomeLatestPosts.jsx, packages/lesswrong/components/common/LWTooltip.jsx, packages/lesswrong/lib/components.js
Material UI Tooltips have a bug that prevents poppers from closing properly. I've created a LWTooltip which is built on LWPopper, and applied it to a couple existing mui Tooltips.
I created this as part of a more experimental PR, and then decided it was important to get this bit of tech built regardless of whether the experiment panned out so created a separate PR for it.
=> Add LWTooltip

packages/lesswrong/components/posts/BookmarkButton.jsx, packages/lesswrong/components/posts/BookmarksList.jsx, packages/lesswrong/components/posts/BookmarksPage.jsx, packages/lesswrong/lib/routes.js
This PR does some very minor fixes to bookmarks.
- Changes sorting to be most-recently-added first.
- Displays "must sign in" when on /bookmarks and logged out instead of error. (Styling isn't good, but it's better than an error message.
- Fix up issue of subtitle and tab title being username of random user.
=> Fix bookmarks list sorting

packages/lesswrong/lib/analyticsEvents.js
use Effect shouldn't return null. Cause an error.
=> Remove return null from useEffect

packages/lesswrong/components/users/ReviewVotingPage.tsx
This PR add analytics tracking for pretty much all actions on the votesReview page except for vote button presses which are already logged in Mongo DB. Tracking includes:
- show instructions click
- vote resort click
- clicking on vote table row
- clicking on review and nomination singleLines
- hovering on items (but not voteTableRows -> that has an error when trying to capture)
=> Add analytics tracking to Review Voting page

packages/lesswrong/components/common/TabNavigationMenu/NavigationDrawer.jsx
Fixes a small UI issue on small screens (especially landscape) where the navigation drawer can be taller than the screen without being scrollable.
=> Navigation drawer can scroll on small/landscape screens

package.json, packages/lesswrong/components/Layout.tsx, packages/lesswrong/components/common/BatchTimePicker.jsx, packages/lesswrong/components/common/CalendarDate.jsx, packages/lesswrong/components/common/FormatDate.jsx, packages/lesswrong/components/posts/PostsItemDate.jsx, packages/lesswrong/components/posts/PostsPage/PostsRevisionSelector.jsx, packages/lesswrong/components/posts/PostsTimeBlock.jsx, packages/lesswrong/components/posts/PostsTimeframeList.jsx, packages/lesswrong/components/posts/timeframeUtils.js, packages/lesswrong/components/users/KarmaChangeNotifierSettings.jsx, packages/lesswrong/components/votes/CommentsVote.jsx, packages/lesswrong/lib/karmaChanges.js, packages/lesswrong/lib/moment-timezone.js, packages/lesswrong/lib/utils/timeUtil.ts, packages/lesswrong/server/debouncer.js, packages/lesswrong/server/emailComponents/EmailFormatDate.jsx, packages/lesswrong/server/emailComponents/EventInRadiusEmail.jsx, packages/lesswrong/server/emails/renderEmail.js, packages/lesswrong/server/rss.js
The version of `moment-timezone` we get from npm includes a 1MB database of changes to time zone definitions throughout all of history. This is not useful. Replace it with a version of moment-timezone with a reduced timezone definitions database (covering only 10 years), which is much smaller. From https://momentjs.com/downloads/moment-timezone-with-data-10-year-range.js , lightly modified to pass lint.
=> Replace moment-timezone (npm version) with vendored version, with less data

packages/lesswrong/components/review/FrontpageVotingPhase.jsx
(accidentally introduced extra whitespace, which might cause merge conflicts due to the corresponding hotfix)
=> remove whitespace

packages/lesswrong/lib/fragments.ts, packages/vulcan-core/lib/modules/components/App.jsx
In a refactoring PR, I removed the "locale" field from user objects, which we inherited from Vulcan and which would let users set their language (except that we had disabled it). However, I missed a fragment reference to that field, which apparently broke quite a bit more than you'd expect.
(Interestingly, some prototype typescript-for-fragments code I was working on today caught the fragment-field-with-no-backing-collection-field issue here, though I didn't realize it was serious.)
=> Fix crash on login

packages/lesswrong/components/users/UsersNameDisplay.jsx
userId value given to analytics context overrode global userId value.
=> Fix field name clash in userNameDisplay tracking

packages/lesswrong/components/sunshineDashboard/AFSuggestCommentsList.jsx, packages/lesswrong/components/sunshineDashboard/AFSuggestPostsList.jsx, packages/lesswrong/components/sunshineDashboard/AFSuggestUsersList.jsx, packages/lesswrong/components/sunshineDashboard/LastCuratedDate.jsx, packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsList.jsx, packages/lesswrong/components/sunshineDashboard/SunshineListTitle.jsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUsersList.jsx, packages/lesswrong/components/sunshineDashboard/SunshineSidebar.jsx, packages/lesswrong/lib/collections/users/views.js
Divides the sunshine sidebar into two sections:
**Inbox:** Always shown, includes new users, new posts, and flagged content
**Optional:** Includes Suggested Curation, Alignment Forum stuff and the Underbelly. (I'm not sure about the right way to handle alignment forum stuff)
The idea being that most of the time the sidebar should be empty, it should almost always be achievable to _make_ it empty (now that we can snooze new users), so it should only show stuff that is relevant.
=> Sunshine cleanup

packages/lesswrong/components/posts/PostsItem2.tsx
We currently have the ability to turn off the importing of local-event-specific code. If we do so, event components cannot be destructured from the Components object, except after a check for the presence of events. The current pattern we've used is to (in mixed events and non-events use components) access the event components off the Components object at their use. Their use will be behind a check for something like `post.isEvent` that serves to ensure that events are being used by this forum instance.
=> Access EventVicinity from Components to protect from unimported case

packages/lesswrong/components/common/HomeLatestPosts.tsx, packages/lesswrong/components/posts/PostsListSettings.tsx, packages/lesswrong/components/recommendations/ConfigurableRecommendationsList.jsx
The EA Forum's changing the name of some of our homepage sections. I'm submitting this upstream because HomeLatestPosts gets changed enough, I'd rather not have to deal with the merge conflicts.
I'm guessing my reviewer has just as much pursed lips as I do about those ternaries. But given that we're in the world where it's definitely just 2.5 users of this codebase for the foreseeable future, I think it's the best option.
=> Text changes for the EA Forum

packages/lesswrong/components/ea-forum/EASequencesHome.tsx, packages/lesswrong/components/posts/PostsPage/PostsAuthors.tsx, packages/lesswrong/components/posts/PostsPage/PostsPage.tsx, packages/lesswrong/components/posts/PostsPage/PostsTopSequencesNav.tsx, packages/lesswrong/components/sequences/BottomNavigationItem.jsx, packages/lesswrong/components/sequences/SequencesPage.jsx, packages/lesswrong/lib/components.js, packages/lesswrong/lib/routes.js, packages/lesswrong/themes/alignmentForumTheme.js, packages/lesswrong/themes/createThemeDefaults.js, packages/lesswrong/themes/eaTheme.js, packages/lesswrong/themes/lesswrongTheme.js
And change some fonts away from Times
The largest LW change here is the part where I noticed several times where LW was using Times as a default font. I thought in all those cases I'd rather the EA Forum use a sans serif stack. I introduce a uiSecondary typography, that LW sets to its serifStack and the EA Forum sets to its sansSerifStack.
I suggest using the sans serif stack for the Alignment Forum. I think it looks better in the context of the alignment forum theming. That's what I've put in the theme file, feel free to ask me to change.
=> EA Sequences

packages/lesswrong/components/comments/CommentsNode.tsx
The answer border-jss was overriding the "unread comment" border-jss. Fixed specificity.
Also fixed a random typescript warning
=> Fix "Unread Answer" left-green bar

packages/lesswrong/components/posts/PostsPreviewTooltip.tsx
– slightly larger preview-boxes (I think I went overboard making them too small)
– slightly smaller versions of the "expanded preview" option, because it was TOO HUGE
=> improve new postHovers

packages/lesswrong/components/posts/LinkPostMessage.tsx, packages/lesswrong/components/posts/PostsPage/PostsPage.tsx, packages/lesswrong/themes/createThemeDefaults.js
I felt like the spacing on my mobile view of a linkpost was wrong, specifically that it was uneven. I've made some changes that I think will help mobile LessWrong as well. The changes regularize the spacing between the bottom divider line of the title section, content notice, start of text, and spacing between paragraphs.  See before and after below. Obviously feel free to tell me to put them into `eaThemes.js`.
=> Small spacing improvement

packages/lesswrong/lib/collections/posts/fragments.js
After you edited a post, if that post had a ToC, you would see the client-side cached pre-edit version of the post.
This is a hacky fix. The real fix is deeper in our Apollo code: when a result comes back from a mutation, it should kick everything with the same ID out of the cache, not try to merge the mutated object with cached objects.
=> Fix an issue where after editing a post with a ToC, the edits don't preview until refresh

packages/lesswrong/server/emailComponents/PrivateMessagesEmail.jsx
On LW this is a no-op, as both the title and siteName with article are "LessWrong". But on the EA Forum, and possibly the AlignmentForum, if you've implemented it, the PM emails will no longer sound like a Russian speaking without articles.
=> Use siteNameWithArticle for "view on the forumName"

packages/lesswrong/components/comments/CommentPermalink.tsx, packages/lesswrong/components/comments/CommentWithReplies.tsx, packages/lesswrong/components/comments/CommentsItem/CommentsItemDate.tsx, packages/lesswrong/components/comments/CommentsItem/CommentsMenu.tsx
Makes it so comments-date-links are permalinks.
(Note that this does add an extra step for people who are navigating to the comment via recentDiscussion, since those people may be looking for context on the comment. But I think it's worth it overall because the hash-links make for really bad links, and most people just don't know about the permalink option. 
I think we should improve the overall experience later on by making proper SSR-loaded comments, but I expect that to take awhile)
=> Comments use permalinks all the time

packages/lesswrong/client.js, packages/lesswrong/lib/vulcan-lib/callbacks.ts
First bug: Failed to import vulcan-core's client code in the right order; all files but one were imported elsewhere, the one missing populated Utils with some functions used only on certain mutations.
Second bug: When adding types to formatHookName, made it no longer accept null, because passing it null would be crazy, but it in fact gets passed null. Oops.
=> Fix crashes introduced by Vulcan unpackaging and TS refactor

packages/lesswrong/lib/crud/withCreate.tsx
When Typescriptifying, I made some components use `useCreate` instead of `withCreate`. Unfortunately `useCreate` wasn't used anywhere else and wasn't tested, so it had a bug (incorrect calling convention for the create function itself).
=> Fix useCreate calling convention

packages/lesswrong/components/comments/CommentsItem/CommentOutdatedWarning.tsx, packages/lesswrong/components/comments/CommentsItem/CommentShortformIcon.tsx, packages/lesswrong/components/comments/CommentsList.tsx, packages/lesswrong/components/common/FormatDate.tsx, packages/lesswrong/components/common/LWTooltip.tsx, packages/lesswrong/components/common/TabNavigationMenu/TabNavigationCompressedItem.tsx, packages/lesswrong/components/common/TabNavigationMenu/TabNavigationFooterItem.tsx, packages/lesswrong/components/common/TabNavigationMenu/TabNavigationItem.tsx, packages/lesswrong/components/editor/EditorFormComponent.tsx, packages/lesswrong/components/localGroups/TabNavigationEventsList.tsx, packages/lesswrong/components/posts/PingbacksList.tsx, packages/lesswrong/components/posts/PostsItem2.tsx, packages/lesswrong/components/posts/PostsItemIcons.tsx, packages/lesswrong/components/posts/PostsItemMeta.tsx, packages/lesswrong/components/posts/PostsListSettings.tsx, packages/lesswrong/components/posts/PostsPage/ContentType.tsx, packages/lesswrong/components/posts/PostsPage/PostsPage.tsx, packages/lesswrong/components/posts/PostsPage/PostsPageDate.tsx, packages/lesswrong/components/questions/QuestionsPage.tsx, packages/lesswrong/components/recommendations/ConfigurableRecommendationsList.tsx, packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx, packages/lesswrong/components/review/FrontpageNominationPhase.tsx, packages/lesswrong/components/review/FrontpageReviewPhase.tsx, packages/lesswrong/components/review/FrontpageVotingPhase.tsx, packages/lesswrong/components/review/Reviews2018.tsx, packages/lesswrong/components/sunshineDashboard/SidebarAction.tsx, packages/lesswrong/components/users/LoginPopupButton.tsx, packages/lesswrong/components/votes/CommentsVote.tsx
Migrates some material-ui Tooltips to LWTooltips
Also gives LWTooltip a max-width of 300 (matching the existing material-ui max-width)
=> Migrate some tooltips to lw tooltips

packages/lesswrong/lib/collections/users/helpers.ts, packages/lesswrong/lib/registerSettings.ts
A user reported a very buggy experience when they shared a post with another user.
While I'm at it, register some missing settings.
=> Only show collaborative editing option to admins

packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUsersList.tsx, packages/lesswrong/lib/collections/users/views.ts, packages/lesswrong/lib/fragments.ts
– Sorts underbelly first by "reviewedAt" date, then createdAt
– Extends the truncate height more to make it easier to evaluate what sort of post you're looking at in new user content
– Sunshine New Users loads 60 additional users when you click "load more"
– Underbelly displays "reviewedAt", "reviewedByUserId", and "banned" status
=> Improve Sunshine Underbelly

packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsList.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUsersList.tsx
– adds loadMore to sunshine curated (which has sometimes needed it)
– loadMore only appears when needed
Also changes the truncate height for the "show user content" feature large enough that I'm pretty confident it'll be an identical experience to before I added the truncate-option, which I'm also pretty confident will fix my problem with false positives.
=> conditional sunshine loading, fix height

packages/lesswrong/components/common/TabNavigationMenu/TabNavigationMenu.tsx, packages/lesswrong/components/common/TabNavigationMenu/TabNavigationSubItem.tsx
I'm not sure about the right approach here (seems plausible that the TabNavigationMenu could use a simplification rework).
LWTooltip creates an inline-block wrapper for it's object, to prevent a weird flickering effect. This has worked mostly fine so far, but disrupts the CSS cascade for the TabNavigationMenu (it no longer inherits a width properly)
=> TabMenuSubItem width / lwTooltip fix

packages/lesswrong/components/common/LWTooltip.tsx, packages/lesswrong/components/ea-forum/EAHomeHandbook.tsx, packages/lesswrong/components/sunshineDashboard/SidebarAction.tsx, packages/lesswrong/server/callbacks/commentCallbacks.ts
Fix assorted type errors on devel, from other developers not yet having type-checking as part of their workflow. One of these (incorrectly named import of a function in commentCallbacks) was a real bug, causing comments to not un-snooze users. The missing props on LWTooltip were a very minor bug, causing a font-size modifier and 200ms delay to not get applied on the Sunshine Sidebar.
=> Fix assorted type errors

packages/lesswrong/components/common/TabNavigationMenu/TabNavigationFooterItem.tsx
The LWTooltip has some weird side-effects when used on components that were relying on some particular cascading styles or flex-box interactions. I haven't figured out how to fix it yet but meanwhile am reverting usages of it where that mattered.
=> replace LWTooltip with mui one

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx, packages/lesswrong/server/resolvers/revisionResolvers.ts
Currently posts that don't have a body (typically shortforms) have the string `'undefined'` as the OpenGraph description, because the HTML-text parser calls `.toString()` somewhere. This fix:
- Short circuits the resolved `plaintextDescription` field if there's no HTML body in the post
- Adds a `getDescription` field to add a nicer OG description to shortform posts
=> Fixes description = 'undefined' on shortform

packages/lesswrong/components/ea-forum/EAHomeHandbook.tsx
I'm not rightly clear why this worked before or what changed. But this does seem to be the correct api now. Perhaps I was developing against an older version of react-cookies when I make this? Unclear.
=> Use useCookies api correctly

packages/lesswrong/components/posts/PostsItemDate.tsx, packages/lesswrong/components/users/UsersNameDisplay.tsx, packages/lesswrong/components/votes/CommentsVote.tsx
The posts-list was sometimes leaving orphaned hover-over cards (it turns out that while LWTooltip was a significant improvement over MUITooltip in terms of this bug, it's not sufficient). 
Moving the tooltips to the left/right instead of top alleviates the bug (since it's much harder to mouseover multiple tooltips while wiggling your cursor around)
Also reverts some LWTooltips in the CommentsVote that weren't quite working right.
=> fix posts-list hoverover bugs

packages/lesswrong/components/questions/NewRelatedQuestionForm.tsx, packages/lesswrong/components/questions/RelatedQuestionsList.tsx
Related questions are now expanded by default (showing the most recent comments), and the "hiddenRelatedQuestion" field is false instead of true by default.
=> More visibility on related questions

packages/lesswrong/components/localGroups/CommunityHome.tsx, packages/lesswrong/components/posts/PostsPage/PostsPageEventData.tsx, packages/lesswrong/components/seasonal/Covid19Notice.tsx, packages/lesswrong/lib/components.ts
Adds a COVID-19 warning to the Community section and to event pages. Styling could maybe use some tweaks, but is unimportant compared to the text. Text is pretty minimal in what it says; it'd be nice to have a suitable post to link to.
=> Add a COVID-19 warning to the Community section and to event pages

packages/lesswrong/components/recommendations/RecommendationsAlgorithmPicker.tsx, packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx, packages/lesswrong/components/seasonal/CoronavirusFrontpageWidget.tsx, packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/lib/components.ts
Replaces "From the Archives" with a "Coronavirus Tag" widget, which shows the top 3 most relevant coronavirus tagged posts.
Includes links to the coronavirus tag page, and the ability to toggle it off.
=> Coronavirus frontpage widget

packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx, packages/lesswrong/components/posts/PostsItemKarma.tsx, packages/lesswrong/components/seasonal/CoronavirusFrontpageWidget.tsx
Moves karma-tooltip to the left, so it doesn't clash with the Coronavirus Tag tooltip. Also makes it smaller.
Also:
– tweaks positioning of Coronavirus Tag tooltip
– removes Coronavirus from the Nav Menu (don't think it's necessary anymore)
=> Karma tooltip + Coronavirus Cleanup

packages/lesswrong/components/comments/CommentsNode.tsx
If you've read a post, and then seen comments in Recent Discussion or PostsItem, I think the comments should just always be expanded.
=> new comments always expanded

packages/lesswrong/components/common/Header.tsx, packages/lesswrong/lib/react-headroom/index.js
Fixes a bug which made the Headroom header not appear when scrolling up, introduced by me (in the process of fixing a slow relayout during pageload). This preserves the performance improvement, but makes it appear properly.
Note that this works by passing Headroom information about its height (64) in a way which ignores a breakpoint (on small phones the height is 56). Theory predicts that this slightly changes the sensitivity to scroll gestures, but it isn't changed in a way I was able to notice by playing with it.
=> Fix bug which made React Headroom not appear when scrolling up

packages/lesswrong/components/common/HomeLatestPosts.tsx, packages/lesswrong/server/migrations/2020-03-11-denormalizeTagRelevance.ts, packages/lesswrong/server/migrations/2020-03-11-updateFrontpageFilterSettings.ts
If the user migration hasn't been run, so the user doesn't have filter settings, use the default filter settings rather than crash on a null pointer.
Add awaits and console.logs to the migration scripts, so that you can tell when they're finished (they were running fine, but in the background, and you couldn't tell from server console output whether they were done).
=> Filter-by-tag: Progress feedback in migration script; don't crash if user-migration not run

packages/lesswrong/components/tagging/TagSearchHit.tsx
On mobile, when you tapped on a tag in the Add Tag list, the following would happen faster than you could see:
* A mouse-hover event gets sent to the TagSearchHit, causing a hover preview of that tag to appear
* The hover preview covered the tag, including the spot you just tapped
* A mouse-click event gets sent to the hover preview
* Which a ClickAwayListener interprets as a cue to close the whole tagging menu
* And no tag is applied.
Fixed by adding a minimum screen width for the hover-preview in TagSearchHit.
=> Fix Add Tag button on mobile

packages/lesswrong/components/posts/SpreadsheetPage.tsx
Initially I had thought the overflow:scroll was necessary. Getting rid of it does change how the intro page works, but probably mostly for the better.
=> Fix scrollbars

packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx, packages/lesswrong/components/tagging/CoreTagsChecklist.tsx, packages/lesswrong/lib/collections/tags/collection.ts, packages/lesswrong/lib/collections/tags/fragments.ts, packages/lesswrong/lib/collections/tags/views.ts, packages/lesswrong/lib/components.ts, packages/lesswrong/server/tagging/tagsGraphQL.ts
Adds a field "core" to tags, and modifies the Unreviewed Posts queue so that before you decide whether to frontpage a post or not, you go through a checklist of core tags.
A minor UI problem this has right now is the hover disappearing if the mouse strays outside the boundaries, which can happen while you're going through the checklist. A possible solution to this is to pin the hover open if you clock on the SunshineNewPostsItem or if you check off one of the tags.
=> Sunshine Sidebar: Sunshines go through checklist of core tags when reviewing posts

packages/lesswrong/components/common/HomeLatestPosts.tsx, packages/lesswrong/components/posts/PostsList2.tsx, packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/collections/posts/schema.ts, packages/lesswrong/lib/collections/posts/views.ts, packages/lesswrong/lib/generated/databaseTypes.d.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts, packages/lesswrong/lib/vulcan-lib/fragmentTypes.json
This reworks the TagPage to use the new tagRelevance field to fetch and sort post-items, rather than doing client-side sorting.
This is in preparation for some further work that lets you sort the page in different ways.
Note: I'm not sure how to properly index this.
=> Refactor Tag Page Sorting

packages/lesswrong/components/posts/PostsList2.tsx, packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/lib/collections/posts/views.ts
The tag page was (apparently) already able to filter itself when passing in the "filter=questions" parameter, but wasn't able to change the sort-order because the tagRelevance view overrode the sortedBy parameter. This allows the sortedBy parameter to instead override the tagRelevance sorting. 
(I'm not quite sure if this should be handled in the tagRelevance view, or instead in the TagPage component)
Meanwhile, also fixing a bug wherein some PostsLists failed to load properly when not passed in a tagId
=> Tag Sorting + Bugfix

packages/lesswrong/components/comments/CommentPermalink.tsx, packages/lesswrong/components/comments/CommentWithReplies.tsx, packages/lesswrong/components/comments/CommentsNode.tsx
Robby had asked if linked to a specific comment could result in that comment always being expanded. This PR makes it so.
=> permalinked comments are always expanded

packages/lesswrong/server/resolvers/revisionResolvers.ts
See https://github.com/LessWrong2/Lesswrong2/issues/889
Note: I have not tested this
This changes improves the experience of sharing links to posts on platforms that scrape descriptions (e.g. Discord).
=> Improve post meta description by omitting links

packages/lesswrong/components/comments/ModerationGuidelines/ModerationGuidelinesBox.tsx, packages/lesswrong/components/form-components/SequencesListEditorItem.tsx, packages/lesswrong/components/posts/PostsPage/PostsRevisionsList.tsx, packages/lesswrong/lib/crud/withSingle.ts
Fixes a crash in `ModerationGuidelinesBox`, caused by a missing `fragmentName` argument on a new `useSingle` call. The bug was introduced in https://github.com/LessWrong2/Lesswrong2/pull/3028 when I made `ModerationGuidelinesBox` re-load its post with a different fragment, to fix type errors and to fix a bug where the moderation guidelines fail to appear when commenting some non-post-page contexts.
Also added type annotations to `useSingle` to prevent this class of bug, and fixed a few minor things exposed by those type annotations.
=> Fix moderation guidelines crash

packages/lesswrong/lib/collections/books/collection.ts, packages/lesswrong/lib/collections/chapters/collection.ts
Fixes the annoying bug where every time you go to any sequences page, admins get notifications to restore some random local storage state
=> Add better local storage ids for sequences and books

packages/lesswrong/lib/collections/notifications/tests.ts
They've been failing frequently enough that I don't think we would actually notice it if these were firing for real, so let's deactivate them for now.
=> Deactivate the notification tests

packages/lesswrong/server/recommendations.ts
Replaces [this PR](https://github.com/LessWrong2/Lesswrong2/pull/2972) which was accidentally based on a branch that has been on hold for awhile. Changes the R:A-Z starting post to Scope Insensitivity (the first non-preface post).
(Going forward, I think this is something we should be A/B testing hard. But in the mean time, this seems like a decent substitution.)
=> Better R:AZ starting point

packages/lesswrong/components/comments/ModerationGuidelines/ModerationGuidelinesEditForm.tsx, packages/lesswrong/components/localGroups/GroupFormDialog.tsx, packages/lesswrong/components/questions/NewQuestionDialog.tsx, packages/lesswrong/components/shortform/NewShortformDialog.tsx, packages/lesswrong/components/tagging/EditTagsDialog.tsx
For the Edit Tags modal and the New Question modal, by default the modal was enforcing an auto-focus on the modal which was preventing some other features from working.
I'm not sure what purpose the autofocus is supposed to be serving, it's possible this should just be disabled all-around by default (currently modals default to 'steal focus')
=> Fix modal autofocus

packages/lesswrong/lib/collections/posts/views.ts
Bug introduced by me, because I assumed that because `...` spreading is null-safe in objects, that it would also be null-safe in arrays. It isn't.
=> Fix crash with some personal blogpost filter settings

packages/lesswrong/components/posts/BookmarksList.tsx
The Javascript core library function `Array.reverse` is tricky: it returns a reversed array, but also reverses the array in-place. This is horrible, and if you use it on an array you got from Apollo, subtle bad things will happen because the array order reverses on each rerender. This caused bookmarks in the front-page bookmarks widget to link to the wrong bookmark (the first entry linking to the last bookmarked post and vise versa, etc).
Introduced in https://github.com/LessWrong2/Lesswrong2/pull/2779 .
=> Fix links in bookmarks being broken

packages/lesswrong/components/common/HomeLatestPosts.tsx
`HomeLatestPosts` computes a 3-month date cutoff, rounded to the nearest day. Unfortunately the rounding depended on time zone, so if the client and server time zones are different, the client would start with an Apollo store with a query with a slightly-different query in it, and respond to this by putting the Latest Posts list into a loading state while it reran the query.
I tested this fix using Chrome client-side timezone emulation, which was added to Chrome in October 2019 and is hidden in the Sensors tab (if you pick a fake geolocation, it will also add a fake time zone to match).
Bug was introduced by me along with soft filters.
=> Fix a timezone-related issue where the Latest Posts list would sometimes blank and then reload after page load

packages/lesswrong/components/linkPreview/PostLinkPreview.tsx, packages/lesswrong/components/tagging/TagHoverPreview.tsx
Straightforwardly copies the existing hover-link styles
=> circle after tagPreview

packages/lesswrong/components/posts/PostsItemMeta.tsx, packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
ESRogs mentioned 'tagging on shortform should be hidden if it's not being used'. Meanwhile, we'd also discussed hiding karma on shortform. This PR cleans up shortform post pages a bit, as well as shortform Recent Discussion threads.
I also removed the horizontal bar, because it didn't seem right for what a shortform page should be. (The following screenshot only has an "asdfasdf" text body because there's apparently also a bug right now preventing me from editing posts bodies to become empty. The idea is supposed to be that it's basically just the post title, for most people and most shortforms)
=> hide ui elements on shortform

packages/lesswrong/client/ga.ts
While I'm not sure this will fix the problem, if you have a problem with two google tag managers, preventing your gtmInit function from making duplicates seems like a good start.
=> Attempt to prevent duplicate google tag managers

packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
also hides "from the archives" from logged out users, as a partial preparation for the recommendations-rework
=> swap coronavirus for archives

packages/lesswrong/components/recommendations/RecommendationsAlgorithmPicker.tsx, packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
This...
a) replaces the "Coronavirus Frontpage checkbox" with a "From the archives" checkbox. 
b) removes the "settings" option for logged out users, because some settings only applies after you were logged in, and generally it was more confusing than helpful.
=> Replace covid-checkbox with archives-checkbox

packages/lesswrong/components/linkPreview/HoverPreviewLink.tsx, packages/lesswrong/components/linkPreview/PostLinkPreview.tsx, packages/lesswrong/lib/components.ts
First (and easiest) part of adding metaculus embeds to LW, which is to simply have an iframe that displays on hover.
Biggest uncertainty I have about the PR is whether we should use the small circle in the link or not. I think it's helpful to communicate that it has a fancy preview, but it also seems a bit bad because it has so far only communicated "onsite link". 
Maybe the ideal thing would be to have a very small metaculus logo, but that seems kind of hard to style, and looked bad when I tried it for 2 minutes.
=> Add link preview for metaculus question links

packages/lesswrong/components/common/SubscribeWidget.tsx, packages/lesswrong/components/common/TabNavigationMenu/TabNavigationSubItem.tsx, packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx, packages/lesswrong/components/posts/PostsItemIcons.tsx, packages/lesswrong/components/posts/PostsTitle.tsx, packages/lesswrong/components/recommendations/ContinueReadingList.tsx, packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx, packages/lesswrong/server/migrations/2019-04-10-confirmLegacyEmails.ts
This removes some buttons from the Recommendations section:
1. The "Login" button under Core Reading is just gone
2. The "View All Curated" button is replaced by the "Curated Icon" on posts being a link (as well as most such post-item-icons being links)
3. The Subscribe buttons are moved over to the Nav Bar
This also removes the Open Questions Nav Item, which wasn't really pulling it's weight (currently you can get to the /questions page via clicking on the Question icon on PostItems)
=> Partial Recommendations Rework

packages/lesswrong/components/comments/RecentDiscussionThread.tsx
Recent discussion's breakpoint for removing the left-indent triggered too early. Changed it to md instead of lg
=> change breakpoint for recent discussion indent

packages/lesswrong/components/posts/PostsListPlaceholder.tsx, packages/lesswrong/components/tagging/FilterMode.tsx, packages/lesswrong/components/tagging/TagFilterSettings.tsx, packages/lesswrong/components/tagging/TagPreview.tsx, packages/lesswrong/lib/collections/tags/collection.ts, packages/lesswrong/lib/collections/tags/helpers.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
note: this is having some kind of fragment/type issue that I didn't quite grok, could use help with.
```
packages/lesswrong/components/tagging/TagPreview.tsx:82:29 - error TS2345: Argument of type 'TagPreviewFragment' is not assignable to parameter of type 'DbTag'.
Property 'schemaVersion' is missing in type 'TagPreviewFragment' but required in type 'DbTag'.
82       <Link to={Tags.getUrl(tag)}>{tag.postCount} posts</Link>
```
=> Show number of tagged posts on tag hover-preview

packages/lesswrong/components/common/HomeLatestPosts.tsx, packages/lesswrong/components/posts/PingbacksList.tsx, packages/lesswrong/components/posts/PostsPage/PostsPage.tsx, packages/lesswrong/components/tagging/AddTagButton.tsx, packages/lesswrong/components/tagging/EditTagsDialog.tsx, packages/lesswrong/components/tagging/FilterMode.tsx, packages/lesswrong/components/tagging/FooterTag.tsx, packages/lesswrong/components/tagging/FooterTagList.tsx, packages/lesswrong/components/tagging/TagFilterSettings.tsx, packages/lesswrong/components/votes/VoteButton.tsx
- capture better context of events in tagFooter
- capture display of tags (and pingbacks) whether or not they're clicked
- track votes from within app so we know where people took action (only that they voted)
- track adding, removing, and modifying frontpage tag filters
- tracking what filterSettings are when frontpage loads + whether they're visible
- track addTag button + when tags added to posts
=> Additions to tagging analytics

packages/lesswrong/components/sunshineDashboard/SunshineSidebar.tsx, packages/lesswrong/lib/collections/posts/views.ts
Reverses the Suggest Curated order so that the above-the-folder suggestions are actually fresh and hopefully exciting.
Cuts down the limit from 10 to 7 because it seemed like "about the number of posts I want to actually consider most of the time."
=> reverse Suggest Curated order

packages/lesswrong/components/common/TabNavigationMenu/TabNavigationSubItem.tsx, packages/lesswrong/components/localGroups/TabNavigationEventsList.tsx
I haven't figured out exactly what's going on with the padding for the TabNavigationSubItems (it looks like there's a bit of a spaghetti tower that I started and that JP layered on top of). But, this fix  adds right-padding back to the Event items, without disrupting the Subscribe menu item
=> fix nav event padding

packages/lesswrong/components/tagging/TagPreview.tsx
I accidentally removed all PostItem bottom-borders from some TagPreviews. Fixed now.
=> fix tagPreview bottom-borders

packages/lesswrong/components/editor/EditorFormComponent.tsx, packages/lesswrong/lib/betas.ts
I... think this might be all that needs to happen to move CkEditor into beta? (it adds a new UserHasCkCollaboration field, which is required for a doc to be ckCollaborative. I haven't yet done a dutiful search to make sure all the possible ways one could conceivably activate collaboration)
=> CkEditor Beta (remove collab)

packages/lesswrong/components/tagging/FooterTag.tsx, packages/lesswrong/components/tagging/FooterTagList.tsx
If we don't do this check then users who can't see admin-only tags get an error on any pages with admin-only tags, which obviously is very bad.
=> Tag hotfix

packages/lesswrong/styles/main.scss
Intercom updated the className of their component on mobile, so it avoided the CSS we had in place to hide it on mobile. This fixes that.
I think this is reasonably urgent to merge, so maybe we want to make it a hotfix, since it makes the bottom-navigation unusable on mobile and looks pretty broken.
=> Re-hide Intercom on mobile

packages/lesswrong/components/common/TabNavigationMenu/TabNavigationSubItem.tsx
Corresponds to https://github.com/LessWrong2/Lesswrong2/pull/3156
I'm guessing the deepscan errors here are spurious, and stem from the PR being based off master, which is currently quite different from devel
=> Hotfix tab navigation ui bug

packages/lesswrong/themes/createThemeDefaults.ts
While reading Zack's latest post, I noticed it was hard to read because of code wrapping around lines. Then I noticed that the font for the codeblocks was just Very Large, period. This feels more natural looking to me, as well as making it easier to parse longer lines.
Compare old:
vs new:
=> smaller code font

packages/lesswrong/components/common/BatchTimePicker.tsx, packages/lesswrong/components/users/KarmaChangeNotifierSettings.tsx
Fixes https://github.com/LessWrong2/Lesswrong2/issues/3167
I'm not 100% sure what the preferred way of handling users who are missing timezone information is. Defer to Jim on whether the PR should early-escape from the render function, or just get wrapped in a withErrorBoundary so it doesn't destroy the entire UsersEdit component (or some third thing)
=> defensive programming for timezone components

packages/lesswrong/components/users/ViewSubscriptionsPage.tsx
If a /manageSubscriptions SubscribedItem doesn't exist for some reason, it loads indefinitely. 
This fixes that.
=> Fix /manageSubscriptions loading bug

packages/lesswrong/lib/collections/posts/custom_fields.ts, packages/lesswrong/server/tableOfContents.ts
Fixes #2962 . Currently when a (DraftJS) post has LaTeX in a section heading, the stylesheet ends up embedded in the section title, which looks ridiculous and effectively breaks the ToC; this filters <style> nodes out. Also improves the error handling of the ToC so that a crash in ToC extraction won't break the page (not that that has ever happened).
=> Fix ToC LaTeX

packages/lesswrong/components/tagging/FooterTag.tsx
Fix #3190: Footer tags overlapping when they wrap. The separation between rows of wrapped tags is now the `marginBottom`, rather than being negative.
=> Fix FooterTags overlapping when they wrap

packages/lesswrong/server/tableOfContents.ts
Fix #3187: ToC generation removes headers from the source document. The Cheerio API is subtle, and is mutate-by-default. Apparently `cheerio.load`, which I thought would clone an element, transfers ownership of it instead (removing it from the source document).
=> Fix ToC generation removing headers [approved with caveats]

packages/lesswrong/components/sequences/SequencesGridItem.tsx
I introduced a bug during the Frontpage Recommendations Rework PR, where I had removed the "LinkCard" component (this was part of a general attempt at simplifying the SequenceGridItem so I could actually understand all the moving parts)
This re-introduced the bug that LinkCard was invented to solve, and then I forgot about it while trying to debug that reintroduced bug.
=> Fix SequenceGridItem flickering

packages/lesswrong/components/titles/SequencesPageTitle.tsx, packages/lesswrong/lib/collections/sequences/fragments.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
Work around an Apollo bug that breaks SSR on sequences pages, by making the fragment in the `cache-only` request in `SequencesPageTitle` different from the fragment in `SequencesPage`. This should also fix #3188 (sequence pages don't have a working Facebook preview).
The Apollo bug, as I currently understand it: If the page contains a `useSingle` with `fetchPolicy: 'cache-only'` and another `useSingle` with the same fragment and a different fetch policy somewhere else, then in the SSR (but not in the client render), the second `useSingle` will fail to load. This suggests that the second query is inheriting the fetch policy of the first, rather than the fetch policies being reconciles by taking the one that gets the data. Upgrading to newer versions of various Apollo libs did not seem to …
=> Work around an Apollo bug that broke SSR on sequence pages

packages/lesswrong/components/sunshineDashboard/SunshineNewUserCommentsList.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUserPostsList.tsx
When evaluating snoozed sunshine users, it'd be helpful to easily see the karma of their individual comments.
┆Issue is synchronized with this [Trello card](https://trello.com/c/QDDKcJ0D) by [Unito](https://www.unito.io/learn-more)
=> Add post/comment karma to sunshine sidebar

packages/lesswrong/components/users/UsersProfile.tsx
This makes the page forwarding more robust by explicitly referencing the oldSlugs array, as opposed to forwarding everything that doesn't match.
┆Issue is synchronized with this [Trello card](https://trello.com/c/PzIZb8B8) by [Unito](https://www.unito.io/learn-more)
=> Fix user page navigation

packages/lesswrong/lib/fragments.ts
This being included in a fragment prevented me from editing myself on devel. Not sure why, but I don't think it should be part of the UsersEdit fragment, since it's hidden in the edit form.
┆Issue is synchronized with this [Trello card](https://trello.com/c/Rin1Ar59) by [Unito](https://www.unito.io/learn-more)
=> Remove recommendationSettings from fragments

packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx, packages/lesswrong/components/sequences/SequencesGrid.tsx, packages/lesswrong/components/sequences/SequencesGridItem.tsx, packages/lesswrong/components/sequences/SequencesGridWrapper.tsx
This is partly in preparation for an overall frontpage redesign
┆Issue is synchronized with this [Trello card](https://trello.com/c/C3hoocEj) by [Unito](https://www.unito.io/learn-more)
=> SequencesGridItem has new styling (removing padding)

package.json, yarn.lock
Add a reinstall-ckeditor script to more clearly communicate that you do actually have to reinstall ckeditor, as a form of documentation. 
Originally I wanted to add this as a `postinstall` script, but that gave me an infinite loop, since the `yarn add` command runs the `postInstall` hook, which runs `yarn add`, etc. So it's just a separate command for now.
┆Issue is synchronized with this [Trello card](https://trello.com/c/xL3R94VM) by [Unito](https://www.unito.io/learn-more)
=> Add reinstall-ckeditor script

packages/lesswrong/lib/routes.ts
This commit fixes
1) an incorrect 'LW' branding in an EAF page title (see https://github.com/centre-for-effective-altruism/EAForum/pull/90)
and
2) removes excessive 'LW' branding in a LW page title (2x 'LW', 1x 'LessWrong')
Screenshots of page titles in status quo. Didn't run anything locally so can't screenshot my change.
=> Streamline page title

.eslintrc.js, packages/lesswrong/client/vulcan-core/AppGenerator.tsx, packages/lesswrong/components/common/HashLink.tsx, packages/lesswrong/components/common/HeadTags.tsx, packages/lesswrong/components/common/HeaderSubtitle.tsx, packages/lesswrong/components/common/PermanentRedirect.tsx, packages/lesswrong/components/ea-forum/EASequencesHome.tsx, packages/lesswrong/components/messaging/InboxWrapper.tsx, packages/lesswrong/components/posts/SpreadsheetPage.tsx, packages/lesswrong/components/vulcan-core/App.tsx, packages/lesswrong/components/vulcan-core/Card.tsx, packages/lesswrong/components/vulcan-core/ScrollToTop.tsx, packages/lesswrong/components/vulcan-forms/FormWrapper.tsx, packages/lesswrong/lib/reactRouterWrapper.tsx, packages/lesswrong/lib/routeUtil.tsx, packages/lesswrong/lib/routes.ts, packages/lesswrong/lib/vulcan-core/appContext.ts, packages/lesswrong/lib/vulcan-lib/routes.ts, packages/lesswrong/server/vulcan-lib/apollo-ssr/components/AppGenerator.tsx
Adds type-checking to `addRoute`. As part of making this work, the type-signature is changed from taking a route-or-array, to taking varargs.
Also add a lint rule against bypassing reactRouterWrapper, and make things pass it.
=> Type-checking for routes

packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx, packages/lesswrong/components/posts/PostsPage/PostsPagePostFooter.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewPostsList.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.tsx, packages/lesswrong/components/tagging/CoreTagsChecklist.tsx, packages/lesswrong/components/tagging/FooterTagList.tsx, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/collections/users/views.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
This makes several improvements to the sunshine sidebar
New Posts
– now include full body of post
– tagging section is condensed
– post information is more clearly separated from the "admin actions" section (i.e. tags and frontpage/personal/delete are clustered together at the top)
New Users
– users who have never been reviewed are sorted to the top
– unreviewed users with a postCount are sorted to the top (since they are highest priority to review)
– unreviewed users with a postCount get a little post icon to help draw your attention to them
– users who HAVE been reviewed no longer show an email address (this is because I wanted some way to distinguish them from unreviewed users, and because the email address is most useful for classifying them as spam when they are first reviewed)
=> Sunshine UI Changes

packages/lesswrong/components/sunshineDashboard/SunshineSidebar.tsx
I had created a prop to manage this, but forgot to use it.
=> SuggestCurated always appears properly in the "show all" section of Sidebar

packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx, packages/lesswrong/components/tagging/CoreTagsChecklist.tsx, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
In my previous Sunshine UI PR, I changed a fragment from PostsList to PostsWithNavigation because the type-checking was yelling at me. This broke the SunshineNewPostsItem.
Now I've changed it back, and... type checking _isn't_ yelling at me, and I notice I'm kinda confused about this. It appears to work fine though. 
I _do_ get an error now about "$near" when I move a SunshiNewPostsItem to frontpage, but I think I recall that happening before.
=> Fix sunshine new post fragment

packages/lesswrong/components/sequences/SequencesGridItem.tsx
In the recent SequencesGridItem UI rework I accidentally broke it's appearance on mobile.
This PR fixes it by giving it a new (fixed) height on smaller screens. I did a horizontal resize test. Currently the image starts stretching on _very_ teeny screens, but I'm not sure this even will come up on modern mobile devices.
=> SequencesGridItem's image height changes appropriately on mobile

packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.tsx
Users that have been snoozed at least once will be banned for 3 months if you click the "ban" button, rather than purged.
=> Sunshine: Reviewed Users are banned, not purged

packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx, packages/lesswrong/components/tagging/CoreTagsChecklist.tsx, packages/lesswrong/server/editor/make_editable_callbacks.ts
Fix a bug (introduced by me in the revision history viewer PR) which made it so that, if you edited a post without changing its body, such as undrafting or re-drafting it, then denormalized revision fields wouldn't be filled in correctly. This would cause the post to appear blank (though the contents would still be there on the editor form). Currently lessestwrong/staging is affected, but production is not.
=> Fix missing revision denormalizations

packages/lesswrong/components/sequences/BottomNavigation.tsx, packages/lesswrong/components/sequences/BottomNavigationItem.tsx, packages/lesswrong/components/sequences/SequencesNavigationLink.tsx, packages/lesswrong/components/sequences/useUpdateContinueReading.ts
Fix a crash on sequence pages, which would happen when a post has prev/next links to posts that don't have a canonical sequence. Also add an error boundary, and use `<Link>` instead of `<a>` because open-in-new-tab was broken.
=> [HOTFIX] Fix crash in post page sequence nav links

packages/lesswrong/components/tagging/PostsItemTagRelevance.tsx, packages/lesswrong/components/tagging/TagRelCard.tsx, packages/lesswrong/components/tagging/TagVoteActivity.tsx, packages/lesswrong/components/votes/CommentsVote.tsx, packages/lesswrong/components/votes/PostsVote.tsx, packages/lesswrong/components/votes/VoteButton.tsx, packages/lesswrong/components/votes/withVote.ts, packages/lesswrong/lib/voting/vote.ts, packages/lesswrong/server/callbacks/commentCallbacks.ts, packages/lesswrong/server/callbacks/postCallbacks.ts, packages/lesswrong/server/tagging/tagCallbacks.ts, packages/lesswrong/server/voteServer.ts, packages/lesswrong/server/votingGraphQL.ts
Voting on comments on a post-page with a lot of comments was very slow. On a 500-comment post, clicking a vote button could cause 4+ seconds of script execution time, giving noticeably bad responsiveness and also kind of breaking the strong-vote interaction. The reason for this was that voting triggered two rerenders of every comment. When you clicked the vote button, it would first do an optimistic-response, and rerender every comment with one of the comments having a different `currentUserVotes`; then the response to the query would come back, and it would rerender every comment *again*. There were some hacky attempts to fix this in the past, based around using `shouldComponentUpdate` to ignore prop changes that might be spurious, but they broke at some point and are pretty doomed …
=> Improve JS performance of voting

packages/lesswrong/themes/stylePiping.ts
I'm not entirely sure why I originally made blockquote > p blocks have no margins, but it results in this:
It looks like removing the special styling fixes the problem. I'm not sure if it causes some other problem somewhere else, but for now am happy to re-roll on styles.
=> Fix padding on small post blockquote paragraphs

packages/lesswrong/components/common/HeadTags.tsx, packages/lesswrong/components/posts/AllPostsPage.tsx, packages/lesswrong/components/posts/PostsPage/PostsPage.tsx, packages/lesswrong/components/posts/SpreadsheetPage.tsx, packages/lesswrong/components/sunshineDashboard/ModerationLog.tsx, packages/lesswrong/lib/routes.ts, packages/lesswrong/lib/vulcan-lib/utils.ts
The default canonical url should not be the homepage, but should not just be the currently-visited url. It should use the "base" path without the query or hash. With this change we don't need the `url` prop any more, so we remove it and its usages. PostsPage does do some fancy customization, so we add the `ogUrl` prop to prevent regression.
Additionally:
* Add `noindex` to moderation log to compensate for its loss of a cannonical url to the homepage
* Add some utility functions for URL manipulation
* Move the coronavirus link database route behind a LW-AF-only conditional.
=> Fix canonical url of user pages and others

packages/lesswrong/server/callbacks/commentCallbacks.ts
Fixes a crash introduced in https://github.com/LessWrong2/Lesswrong2/pull/3261 , which changed the type signature of `comments.moderate.async` without changing the call in `CommentsEditSoftDeleteCallback`. This crash shows up in unit tests, but the exception gets printed and swallowed without actually making the test fail.
=> Fix crash when deleting comments

packages/lesswrong/components/sunshineDashboard/SunshineSidebar.tsx
Fixed a bug introduced in the Grey Hoverover rework.
=> Logged out users no longer see a partial Sunshine Sidebar

packages/lesswrong/components/comments/RecentDiscussionThread.tsx, packages/lesswrong/components/posts/LinkPostMessage.tsx
On unread linkposts, previously, it had just had an awkward space where the "Link Post" message was supposed to be. Now it appears:
=> RecentDiscussion Link Post Message

packages/lesswrong/components/tagging/AddTagButton.tsx, packages/lesswrong/components/tagging/TagFilterSettings.tsx
Previously, if you clicked the frontpage "add tag" button in the gap between the "+" and the edge of the button, nothing would happen. This expands the click-target to match the obvious UI intuitions.
=> Add Filter Button is more clickable

packages/lesswrong/lib/routes.ts
After the Grey Background Rework, some pages ended up with grey backgrounds that shouldn't (or at least, shouldn't until we put more work into optimizing them). This fixes that by giving a bunch of pages white backgrounds.
=> Make more page backgrounds white

packages/lesswrong/components/posts/PostsPreviewTooltip.tsx, packages/lesswrong/components/tagging/FilterMode.tsx, packages/lesswrong/components/tagging/TagPreview.tsx, packages/lesswrong/components/tagging/TagSmallPostLink.tsx, packages/lesswrong/themes/lesswrongTheme.ts
(this inadvertently fixes the "tag previews don't always go away when you mouseLeave" bug, by virtue of moving the post-hover off to the side instead of underneath. But it doesn't solve the underlying problem with that bug, and is mostly focused on making the tag previews simpler to look at)
=> Steamline Tag Hover Previews

packages/lesswrong/components/sunshineDashboard/SunshineSidebar.tsx
A part of the sunshine sidebar was exposed to logged in users, accidentally.
=> Fix exposed sunshine curated list

packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/lib/collections/tags/fragments.ts, packages/lesswrong/lib/collections/tags/schema.ts, packages/lesswrong/lib/generated/databaseTypes.d.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
This sets Tag Page truncation to be based on paragraphs instead of characters, and lets you manually specify the paragraph count.
=> Tags can manually set truncation count

packages/lesswrong/components/tagging/TagsListItem.tsx
Previously, long tags looked ugly on the /tags/all page. Now they look pretty natural:
=> fix word wrap on all tags

packages/lesswrong/components/vulcan-accounts/LoginFormInner.tsx
Vulcan-Accounts (inherited via Vulcan, but originally written by studiointeract) is spaghetti code. An important user is having the login form crash on open; we can't reproduce it locally, while for him it reproduces consistently even after refresh and even in incognito windows.
Vulcan-Accounts uses localStorage, but not for any good reason; it saves partially-filled-in new-account forms, which is pointless since our new-account form only has username, password and email fields. But localStorage creates the possibility of weird-broken data *in* localStorage, which is not a possibility we want. So, rip out all usages of localStorage by vulcan-accounts. This is kind of a longshot for the bug itself, but worth ruling out as a cause of the current problem and as a source of future problems.
=> Remove sketchy localStorage usage from vulcan-accounts

packages/lesswrong/components/shortform/ShortformSubmitForm.tsx
Changes shortform form style to match comments (instead of weirdly grey)
=> shortform submit styling

packages/lesswrong/components/users/UsersProfile.tsx
UserProfile options weren't wrapping correctly, which was stretching the page
=> Fix width on UsersProfile

packages/lesswrong/components/tagging/TagsListItem.tsx
The Tag-Hover-Previews were more annoying than helpful on the all-posts page. 
(it's possible hover-previews should just be generally disabled on mobile?)
=> Hide all-tag previews on mobile

packages/lesswrong/components/tagging/TagsListItem.tsx
I added this field into the TagsListItem for debugging, and then accidentally left it in. Removing from master.
Paired with non-hotfix PR https://github.com/LessWrong2/Lesswrong2/pull/3311
=> [Hotfix] remove reviewed by user

packages/lesswrong/components/Layout.tsx
I think it's just necessary to have it closer to the center on smaller screens. I changed it to 1.4 (still slightly better than 1.5 like it used to be on larger screens. @Discordius if you know how to get it to work nicely at multiple screen sizes feel free to change more)
=> Change Layout Grid to center non-admin-users

packages/lesswrong/components/tagging/TagRelCard.tsx, packages/lesswrong/components/tagging/TagRelevanceButton.tsx, packages/lesswrong/lib/components.ts, packages/lesswrong/server/callbacks/alignment-forum/callbacks.ts
Currently, this makes a "cancel vote" button appear on the TagRelCard if there is exactly on smallUpvote cast by the currentUser. 
The TagRelevanceButton could potentially be used to generally replace the tag relevance voting widget, but currently does not.
=> Cancel Vote button

packages/lesswrong/components/sequences/SequencesGridItem.tsx
There were a bunch of sketchy things going on with the sequences tooltip, with two tooltip components, one of them being completely inaccessible. This removes one of them and adds a length limit to the current tooltip.
=> Fix sequences tooltip

packages/lesswrong/components/comments/CommentsNewForm.tsx
Kind of as a bit of a hotfix for long comment submissions, and also as a general quality-of-life improvements, this makes it so that when you submit a comment the form enters into a loading state that allows you to more properly track what is happening with comments that take a long time to be submitted.
=> Add a loading indicator to comment submissions

packages/lesswrong/components/comments/CommentsItem/CommentBottomCaveats.tsx, packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx, packages/lesswrong/components/questions/Answer.tsx, packages/lesswrong/lib/components.ts
Due to duplication between `CommentsItem` and `Answer`, answers couldn't be retracted (even though they had the menu item and the field), and moderator-blocking replies wouldn't display the notice.
=> Fix retraction and banning-replies-on Answers

packages/lesswrong/components/recommendations/ContinueReadingList.tsx, packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx, packages/lesswrong/components/recommendations/withContinueReading.ts, packages/lesswrong/components/recommendations/withDismissRecommendation.ts, packages/lesswrong/lib/collections/comments/fragments.ts, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/collections/votes/fragments.ts, packages/lesswrong/lib/fragments.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts, packages/lesswrong/server/recommendations.ts
Shrinks the size of the front page. The largest-effect-size thing here is trimming down fragments, which saves ~75kb of duplicate comment text. Also load the only the next post (which is displayed) for continue reading entries, don't also load the last-read post (which is not displayed); for me this was ~40kb.
Hookifies RecommendationsAndCurated/ContinueReadingList, because I thought I might also make it not do the query if the continue-reading section is hidden and/or apply the limit-3 in a way that saves downloading, but I didn't get to that yet.
=> Frontpage size optimizations

packages/lesswrong/client/vulcan-core/start.tsx, packages/lesswrong/client/vulcan-lib/apollo-client/apolloClient.ts, packages/lesswrong/components/comments/RecentDiscussionThread.tsx, packages/lesswrong/components/comments/RecentDiscussionThreadsList.tsx, packages/lesswrong/components/common/AnalyticsClient.tsx, packages/lesswrong/components/common/withRecordPostView.tsx, packages/lesswrong/components/posts/PostsCommentsThread.tsx, packages/lesswrong/components/posts/PostsItem2.tsx, packages/lesswrong/components/posts/PostsList2.tsx, packages/lesswrong/components/questions/AnswerCommentsList.tsx, packages/lesswrong/components/questions/AnswersList.tsx, packages/lesswrong/components/sequences/SequencesGridWrapper.tsx, packages/lesswrong/components/tagging/TagFilterSettings.tsx, packages/lesswrong/lib/analyticsEvents.tsx, packages/lesswrong/lib/crud/withCreate.tsx, packages/lesswrong/lib/events/withNewEvents.ts, packages/lesswrong/lib/vulcan-lib/components.tsx
Client-side Javascript execution recently regressed pretty severely (from front-page logged-out execution time ~4s, to ~10s). This fixes a bunch of things that were causing rerenders, bringing performance back to where it used to be, and adds infrastructure for memoizing components.
=> Fix client-JS performance issues

packages/lesswrong/client/themeProvider.tsx, packages/lesswrong/lib/vulcan-lib/components.tsx, packages/lesswrong/server.js, packages/lesswrong/server/styleGeneration.tsx, packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
Previously, we re-generate JSS styles with each request, and embed them into the page header, then recompute them again client-side on hydration. This is bad because it adds a lot to the SSR and client Javascript time, and because styles embedded in the page header this way can't be cached by the browser, adding to the size of the page download.
This PR makes it so that instead, we do all the JSS processing once on server startup, making a static stylesheet which is served from `/allStyles?hash=...`. The hash allows setting aggressive caching options in http headers, and there is handling for the case where a page requests static styles from a server running a different version of the app; in that case, it rejects the request, and a fallback handler generates the styles client-side like …
=> Static stylesheet generation

packages/lesswrong/server/rss-integration/cron.ts
This fixes a bug in RSS imports that caused some fraction of RSS imports to not properly run, because the changes in [this commit](https://github.com/LessWrong2/Lesswrong2/commit/79609dbe3e885ad44bcbcb189b24342da2431225) made it so that it would break the loop if it errored on any of the feeds, and we have some feeds whose feed URLS are no longer valid, so everything that was usually parsed after that was no longer being imported.
After testing, I can verify that the only RSS feed impacted by this was the AI Alignment Newsletter, which is why I didn't notice this earlier.
=> Fix RSS Imports by adding better catch statements

package.json, packages/lesswrong/components/comments/ModerationGuidelines/ModerationGuidelinesBox.tsx, packages/lesswrong/lib/editor/ellipsize.tsx, packages/lesswrong/lib/truncatise.ts
Best viewed commit-by-commit, as the first and last commits are bulk changes, while the middle commit does the actual speedup.
This reduces the amount of time spent in truncatise for a front-page SSR render from ~431ms to ~67ms (single measurements), speeding up overall SSR time by the same amount, by hoisting some config setting parsing that shouldn'tve been in the inner loop, out of the inner loop.
=> Fix performance problems with the `truncatise` library

packages/lesswrong/components/posts/PostsPage/ContentType.tsx, packages/lesswrong/components/tagging/FilterMode.tsx, packages/lesswrong/components/tagging/FooterTag.tsx, packages/lesswrong/components/tagging/FooterTagList.tsx
Sort core tags and the frontpage/personal marker to the end of the tag list in post headers/footers, and style them differently. This makes it easy to see which tags are non-core tags, which are likely to be the most interesting ones.
(Feel free to suggest different colors.)
=> Distinguish tag types with styling

packages/lesswrong/components/tagging/AddTag.tsx, packages/lesswrong/components/tagging/AddTagButton.tsx, packages/lesswrong/components/tagging/TagSearchHit.tsx
It seemed to work basically fine to just show all tags immediately when users click the "all tags" button. Only issue is that they're not sorted alphabetically, and probably should be. (I think it should be alphabetical once you're showing all, but sorted by postCount if you're not)
This also tries out a thing where tags without descriptions show up as grey, so you don't try to hover over them and get disappointed. The current implementation feels a little wonky (because it takes awhile for them to load and check if a description exists). 
Create Tag now works within editor, and automatically adds the tag afterwards.
=> Create Tag and Show All Tags now display within the AddTag dropdown menu

packages/lesswrong/components/tagging/TagSmallPostLink.tsx, packages/lesswrong/components/tagging/TagsDetailsItem.tsx
Adding the karma to the TagSmallPostLink resulted in some weird behaviors. This cleans up a few stylistic errors.
=> Fix styling of TagSmallPostLink

packages/lesswrong/components/posts/PostsItemKarma.tsx, packages/lesswrong/components/tagging/AllTagsAlphabetical.tsx, packages/lesswrong/components/tagging/AllTagsPage.tsx, packages/lesswrong/components/tagging/TagHoverPreview.tsx, packages/lesswrong/components/tagging/TagPreview.tsx, packages/lesswrong/components/tagging/TagSmallPostLink.tsx, packages/lesswrong/components/tagging/TagsListItem.tsx
Makes a number of changes for the All Tags page:
– TagSmallPostsLinks have karma to the right instead of left (makes it easier to read)
– the alphabetical section shows 6 posts instead of 3 (this comes along with adding more spacing, since it's harder to parse larger numbers of posts otherwise)
– added a "create tag" button to the Tag Details section, which was a bit easier to find. (I'm not sure how to put it at the very top of the page without looking weird)
I think there should also be 6 tags instead of 3 for in the Concepts Portal section, but wasn't sure if there should be 6 posts when you encounter a tag-link in the wild on a post page. I went ahead and changed it for now because I don't expect it to come up that often, and I added a little infrastructure to make it easier to change …
=> All Tags Tweaks

packages/lesswrong/components/tagging/AddTag.tsx
The new Create Tag form that lived in the AddTag dropdown didn't have the right width, and admins got an ugly "Advanced Options" section that just made things annoying rather than really helping. 
This PR fixes the width and gets rid of the Advanced Options box (admins can go edit it afterwards on the proper tag page if it's important)
=> Fix styling issues for the new Create Tag form

packages/lesswrong/server/vulcan-lib/apollo-server/context.ts
When you make a request, we look up your user object based on the login token. Save that user object to the dataloader, so that when the currentUser resolver runs, it doesn't have to make a roundtrip to the database. Speeds up SSR by one database roundtrip time (significant in development, less significant in production).
=> When loading the logged-in user for resolver context, reuse it for currentUser

packages/lesswrong/components/editor/EditorFormComponent.tsx, packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/components/tagging/TagPageTitle.tsx, packages/lesswrong/lib/collections/tags/fragments.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
This PR: 
+ Improves the "Change Description" help text to make it more useful
+ Makes it so that logged out users don't just go to a broken edit-tag page when they click on the big "Edit Wiki" button
+ Properly populates the description and title meta HTML tags to improve search results and shareability of tag pages
=> Small improvements to tag page

packages/lesswrong/lib/collections/posts/custom_fields.ts
Makes it so you can edit the curatedDate field and metaDate field by manually setting them to be a datetime component. (By default Vulcan was rendering them as some kind of confused Text input)
=> Fix curatedDate edit field

packages/lesswrong/server/callbacks/alignment-forum/callbacks.ts, packages/lesswrong/server/tagging/tagCallbacks.ts
Fixes a crash in the callback when cancelling votes. This causes subsequent callbacks to not run, so cancelling a vote didn't undo its effect on a user's karma.
Introduced in https://github.com/LessWrong2/Lesswrong2/pull/3278 , but the root cause of this is bad design in Vulcan's callbacks system. Callbacks are ambiguous as to whether they are events with no return value, or are returning a chain of successive updates to a variable. Vulcan disambiguates the two based on whether the return value of a callback is undefined; if it's not-undefined, the return value is passed to the next callback, and if it's undefined, the original argument is passed. But the promise returned from an async function that has no return value, is not undefined; so it gets misinterpreted as an updated value, …
=> Fix crash in cancel-votes callback

packages/lesswrong/lib/collections/posts/views.ts
This is a reasonably performant way to do a query for posts without core tags. Created for review and discussion (also, note that this is being merged into the `tagProgressBar` PR).
=> Add fancy Mongo expression

packages/lesswrong/components/tagging/TagPreview.tsx, packages/lesswrong/components/tagging/TagSmallPostLink.tsx, packages/lesswrong/themes/alignmentForumTheme.ts, packages/lesswrong/themes/eaTheme.ts, packages/lesswrong/themes/lesswrongTheme.ts
I played around with making the links a little greener. (I initially tried using the existing primary and lwTertiary colors and those felt too hard to read. I then made a darker variant of lwTertiary, and then the author/karma felt a little anemic next to that so I made them slightly greener too)
=> TagPreview post links a little greener

packages/lesswrong/lib/routes.ts
Possibly the /tags/all page should be formally changed to /concepts, but meanwhile seemed good to have /concepts at least point _somewhere_.
=> Add /concepts redirect

packages/lesswrong/components/tagging/FilterMode.tsx, packages/lesswrong/components/tagging/TagPreview.tsx, packages/lesswrong/components/tagging/TagSmallPostLink.tsx
This makes post-lists more involved on the PostPage tags, but removes them from the frontpage filter tags.
=> more tags on post page, plus styling

packages/lesswrong/components/common/SeparatorBullet.tsx, packages/lesswrong/components/tagging/TagProgressBar.tsx, packages/lesswrong/lib/collections/posts/views.ts
The progress bar query was slow. But, also, I wasn't even that sure it was good to directly encourage people to tag every single post with an Oddly Specific Tag. So we didn't bother fixing the slowishness, instead just switching to a direct "untagged" query.
I still do want people to think about about adding specific tags, though, so I also had it link to two different /allposts filters. (One of which is the somewhat slower "non-core tags" query, but Oli and I thought it'd be fine to do as long as it wasn't on the frontpage)
=> Progress Bar update

packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
Apparently I put in a gap conditional on whether users were logged in. I'm... not 100% sure what it was originally doing. I think it might have been there to help make the various configurable bookmarks / continue-reading / etc look reliably good? But, I feel like it's probably better to just always have a gap.
We can remove it if it turns out to look weird after we remove the ProgressBar
=> Logged out users see TagProgressBar gap

packages/lesswrong/lib/collections/posts/custom_fields.ts
This makes it so that you can go arbitrarily back in recent discussion without stuff just kind of not having comments anymore, and also weirdly breaking.
=> Set the recentComments cutoff relative to lastCommentedAt date

packages/lesswrong/components/posts/PostsPreviewTooltipSingle.tsx, packages/lesswrong/components/search/PostsListEditorSearchHit.tsx
This makes it so the AddPostsToTag search function includes hoverovers for the posts, which display the existing tags. 
(notes for followup work: we have a lot of duplicate search-item components which I'm not sure are pulling their weight)
=> Tag Post Search hover

packages/lesswrong/lib/routes.ts
Previously I had accidentally put this in the section of the routes under "EAForum", so it didn't work for us. It is not in what I'm _pretty sure_ is the general routes section. And it seems to work correctly.
=> fix /concepts route

packages/lesswrong/server/notificationBatching.tsx, packages/lesswrong/server/notificationCallbacks.tsx
When we wrote the original notification system, we failed to properly handle the case of on-site only notifications to get properly batched. The notification system was making an assumption that all batched notifications are emailed, which this PR fixes, restoring the functionality of batched on-site notifications.
While this bug has been present for over a year, not many people use the batched on-site notifications (and those who do usually also get email notifications, which compensates for a bunch of the problems). Only about 4 users were affected by this.
=> Fix on-site batching

packages/lesswrong/components/revisions/RevisionSelect.tsx, packages/lesswrong/components/revisions/TagPageRevisionSelect.tsx, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
Previously, I had moved lastPromotedComment from PostsBase to PostsList at Jim's suggestion, and then didn't check for type errors before merging. This turned out to cause a bunch of type errors.
edited to add:
The problem is that PostsList had been implicitly being treated as a subfragment of other larger fragments like PostsDetails, but that wasn't being enforced. After talking it over, habryka and I decided to split out a new subfragment called PostsListBase, which is also used by PostsDetails.
Meanwhile, there were some other random type errors relating to the TagRevisionItem, which I addressed with some refactoring.
=> Fix Various Type Errors

packages/lesswrong/components/notifications/TagRelNotificationItem.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewTagsItem.tsx, packages/lesswrong/components/tagging/TagPreview.tsx, packages/lesswrong/components/tagging/TagsDetailsItem.tsx
Fixes a crash when tag hover-overs (and some other places) would show a tagged post in the top 6, but the post is a draft and you don't have access. This showed up in Sentry, and I think we had a mention of it in #bugs-channel; it completely broke a couple tags, except that admins are unaffected.
I used nullability typechecking from a different PR to mark tagRel.post as though it were nullable, fixed all the resulting type errors, and made this separate PR based on that.
=> Fix crash in tag hover-over when a tagged draft post is in the top 6

packages/lesswrong/components/posts/PostsPage/PostActions.tsx
(This is the simplest version of this PR. I briefly looked into improving the Edit Tags option on the triple-dot-menu, but it was fairly annoying, and it seemed better to at least ship this incremental improvement)
It does include a styling switch to make it more harmonious with other menu items. (I prefer the old tag-styling myself, but others kept saying they disliked that)
=> All users can edit tags on Triple-Dot-Menu

packages/lesswrong/components/posts/PostsPreviewTooltip.tsx, packages/lesswrong/components/tagging/FooterTagList.tsx
This re-orders the tags on a PostsPreviewTooltip to match the ordering in FooterTagList
=> PostsItemPreview tag sort order

packages/lesswrong/components/common/HashLink.tsx
HashLink was annotated using React prop-types as having `children: PropTypes.node`, but sometimes its children would be an array of several nodes instead. This worked fine, but produced an error in the browser console in debug mode.
=> Fix a prop-types warning on the tag portal

packages/lesswrong/components/sunshineDashboard/SunshineSidebar.tsx
I accidentally removed that ability while reworking the sunshine sidebar recently.
=> AF admins can see sidebar again

packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/components/tagging/TagPreview.tsx
Previously, TagPreview was using TagRels, which doesn't let you sort by post karma. Switches to fetch posts using the same algorithm the TagPage does.
=> Tag Preview posts match TagPage posts

packages/lesswrong/server/tagging/tagCallbacks.ts
[Previous attempt](https://github.com/LessWrong2/Lesswrong2/pull/3382) to fix this got one of the async callbacks, but there were two.
=> Fix (another) crash in vote-cancel callback

packages/lesswrong/components/sequences/SequencesGridItem.tsx
Specific to zoomed out views (eg 80% zoom) and low DPI, but reproduces in both Firefox and Chrome.
Left: before. Right: after.
=> Fix a visual artifact where the top pixel of sequences grid titles is truncated

packages/lesswrong/lib/algoliaUtil.ts, packages/lesswrong/server/scripts/algoliaExport.ts, packages/lesswrong/server/tagging/tagsGraphQL.ts
`algoliaCleanIndex` takes a collection **name**, while `algoliaCleanAll` previously passed it a full collection. Fixed, and thought it would be nice for the type checker to help with that, so I added some extra typing. Unfortunately, TypeScript didn't work like I thought it did*, so the new type is only marginally useful. Still, it seems more descriptive of the thing that the code is doing, so I left it in. Also includes some slightly more helpful logs.
* See comment, it's mildly interesting.
=> Bugfix for algoliaCleanAll, add some related type improvements

packages/lesswrong/components/ea-forum/EAHome.tsx, packages/lesswrong/components/recommendations/ConfigurableRecommendationsList.tsx, packages/lesswrong/components/recommendations/RecommendationsAlgorithmPicker.tsx, packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx, packages/lesswrong/components/recommendations/RecommendationsList.tsx, packages/lesswrong/lib/collections/users/recommendationSettings.ts, packages/lesswrong/lib/routes.ts, packages/lesswrong/server/recommendations.ts
Move the EA Forum to use RecommendationsAndCurated. This allows us to get Continue Reading and Bookmarks. Also change it such that we sample posts on the frontpage for logged in users.
While we're at it, I noticed that we had functionality to apply default settings to different recommendationsSettings based on the settings name. Unfortunately, we were overwriting the result of those defaults. Given that they hadn't been used in a year and were now serving just to confuse, I removed said functionality. I could also imagine moving the logic away from being set in the RecommendationsAndCurated component. However, I wasn't sure what legacy settings users would have in their user.recommendationSettings.frontpage settings, which would no longer be overruled. So I went with the simple refactor, …
=> EA Recommendations rework + slight refactor

packages/lesswrong/components/tagging/NewTagsList.tsx, packages/lesswrong/components/tagging/TagVoteActivity.tsx, packages/lesswrong/lib/collections/tags/fragments.ts, packages/lesswrong/lib/collections/tags/views.ts, packages/lesswrong/lib/components.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts, packages/lesswrong/lib/routes.ts
In response to some user feedback during the Tagging Session, I've added a list of newly created tags to the tagVoting page. I've also made it so "/tagVoting" and "/tagActivity" both link to the same place (since some people including myself found myself reaching more naturally for the word "tag activity".
=> New Tags on TagActivity

packages/lesswrong/server/callbacks/userCallbacks.ts
Fix an issue in A/B test key handling that caused a lot of non-failure error log output in unit tests, and might potentially break something like API account creation via GW.
=> Fix an issue in A/B test key handling during unit tests

packages/lesswrong/lib/collections/users/custom_fields.ts
Move the A/B test key override setting to the admin options section on user profile pages. It's only visible to admins, but it was defaulting to being the first field on the form, which was conspicuous and ugly.
=> Move the "A/B test key" setting to the admin options section of the user profile

packages/lesswrong/lib/collections/comments/views.ts
In https://github.com/LessWrong2/Lesswrong2/pull/1996, the `authorIsUnreviewed` field is added to the index-prefix for comments; whether that field is part of the default query depends on a config setting, which is on for EA Forum and off for LW. Because MongoDB is super brittle, putting a field which is not part of a query into an index-prefix breaks indexing. However, this change didn't break anything immediately, because the existing indexes were all still there, and would only be removed if we did so manually (which we didn't). However, it broke the *new* index for comments-on-tag, causing some significant performance problems..
=> Fix indexing issue with comments.hideAuthorIsUnreviewed

packages/lesswrong/components/tagging/TagDiscussion.tsx, packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/lib/components.ts
This PR aims to clean up the Tag Page header, via:
1. gets rid of WikiTagGrade, because I don't think it's currently providing much value and adds a bit too much clutter
2. Moves the TagDiscussion button off to the right
3. TagDiscussion button is now a hoverover so you can see a few comments without having to click through.
=> Tag page header tweaks

packages/lesswrong/server/tableOfContents.ts
Fixes (probably) a bug which completely broke the comments section on https://www.lesswrong.com/posts/H3wdw2cLNLpcF8pXA/social-capital-paradoxes .
=> Fix React key-duplication issue on answer pages with ToCs

packages/lesswrong/components/tagging/FilterMode.tsx, packages/lesswrong/components/tagging/TagFilterSettings.tsx, packages/lesswrong/lib/collections/users/custom_fields.ts
Fixes the bug where clicking "Required" on a tag filter doesn't highlight "Required", and makes it so that clicking on a filter-button that's already been clicked reverts the filter to "0"
=> Tag Filter UI improvements

packages/lesswrong/components/tagging/TagProgressBar.tsx
Currently the progress bar shows as completed during loading. This PR just hides it during loading, which seems better.
=> Hide progress bar during loading

packages/lesswrong/components/common/HeadTags.tsx, packages/lesswrong/lib/instanceSettings.ts, packages/lesswrong/server/scripts/invites.ts, sample_settings.json
Awhile ago, I recall a conversation where we said that at some point we should drop the "2.0" from "LessWrong 2.0", to just be "LessWrong" again, since old-LessWrong no longer exists concurrently, and it's a weird thing to have in our branding. This PR does that renaming (on the code side, in conjunction with a [second PR](https://github.com/LessWrong2/LessWrong-Credentials/pull/30) against the credentials repo, which does it on the config-gile side).
=> Remove the "2.0" from "LessWrong 2.0"

packages/lesswrong/lib/collections/comments/views.ts
Mostly hasn't come up before, but there was one recently, and seeing a deleted-comment entry in the All Posts page context was ugly and weird.
=> Don't show [deleted comment] entries in shortform section on All Posts page

packages/lesswrong/themes/stylePiping.ts
This fixes a visual discrepancy between the WYSIWYG editor view and the rendered posts. Some historical posts might be affected, but when I checked a few randomly sampled ones, things looked fine.
=> Don't make tables full-width

packages/lesswrong/server/scripts/algoliaConfigureIndexes.ts
This activates support for the verbatim search syntax, which sure seems important
=> Activate advanced search on all Algolia indexes

packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
I think the progress bar might be causing some performance problems, and also I think it clutters up the frontpage too much during Petrov Day, so I vote to remove it.
=> Temporarily remove tagging progress bar for Petrov day

packages/lesswrong/components/localGroups/GatherTown.tsx
At some point the GatherTown widget was properly gated, but then either Oli or me (probably me) accidentally un-gated it. This limits it to people with the walledGardenInvite setting again.
=> Properly gate the garden

packages/lesswrong/components/common/ContentItemBody.tsx, packages/lesswrong/components/linkPreview/HoverPreviewLink.tsx, packages/lesswrong/components/linkPreview/PostLinkPreview.tsx, packages/lesswrong/server/vulcan-lib/utils.ts
From Jeff Kauffman on Intercom: 
> I noticed that when my posts are copied over rel=nofollow is removed from links? For example, my RSS feed has "&lt;a rel=&quot;nofollow&quot; href=&quot;https://www.consumerreports.org/car-seats/how-to-fit-child-car-seats-three-across/&quot;&gt;on&lt;/a&gt;"
> This isn't critical, but I put rel=nofollow on these links because while I wanted to link them to demonstrate that the topic has been widely discussed I didn't want to endorse them specifically (they're kind of spammy).
This fixes this.
=> Allow rel="nofollow" links to work right

packages/lesswrong/server/editor/make_editable_callbacks.ts
We briefly had some code to detect if MathJax fails to return a result, which was accidentally deleted in https://github.com/LessWrong2/Lesswrong2/pull/2691 .
=> Detect timeouts of MathJax processing

packages/lesswrong/components/localGroups/GatherTown.tsx, packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
Wraps the <a> tag in an AnalyticsTracker component. Very simple.
Also rename AnalyticsContext to camelCase
=> Track clicks to external GT

packages/lesswrong/components/tagging/FilterMode.tsx
Pursuant to a [discussion](https://cea-core.slack.com/archives/CJZ7QMY5V/p1603374484065300) on slack:
Since suggestedAsFilter can diverge from core tags, just have suggestedAsFilter be the ones that aren't removable
=> Only default filter tags are unremovable

packages/lesswrong/components/localGroups/GatherTown.tsx
Fix the GatherTown link in the front page widget. This happens because the `Link` component only works with on-site URLs; given an absolute URL it improperly treats it as relative.
=> [Hotfix] Fix broken GatherTown link in front page widget

packages/lesswrong/server/gatherTownCron.ts
The GatherTown widget now incorrectly shows zero users connected, because we have a hardcoded server name in the API call. Make that configurable, and also update it to the new correct server name.
=> [Hotfix] Make GatherTown bot server ID configurable (and update it)

packages/lesswrong/components/walledGarden/GatherTownIframeWrapper.tsx, packages/lesswrong/components/walledGarden/PomodoroWidget.tsx, packages/lesswrong/components/walledGarden/PortalBarGcalEventItem.tsx, packages/lesswrong/components/walledGarden/WalledGardenEvents.tsx, packages/lesswrong/components/walledGarden/WalledGardenPortal.tsx, packages/lesswrong/components/walledGarden/WalledGardenPortalBar.tsx, packages/lesswrong/themes/createThemeDefaults.ts
Among other things, changes how the portal/iframe flexbox works so that it works on Firefox. This isn't quite optimal and isn't a strict improvement (it leaves more dead space on large monitors probably). But, I think it's better than status quo. The PortalBar still expands to take up more space when it gets bigger.
Another noteworthy thing: at Ruby's request I made this change:
``` 
useEffect(() => {
iframeRef.current.focus()
}, [iframeRef])
}, [iframeRef, iframeRef.current])
```
Which aims to fix a focusing issue. I haven't yet tested it or thought through exactly what it does.
=> Various Garden Portal Improvements

packages/lesswrong/server/gatherTownCron.ts
Tested by: adding `getGatherTownUsers` to `Globals` and calling it from a `meteor shell`, while typing in the GatherTown username box in another window.
=> gatherTownCron: Fix duplicate users when names change during check

packages/lesswrong/components/walledGarden/GatherTown.tsx, packages/lesswrong/components/walledGarden/GatherTownIframeWrapper.tsx, packages/lesswrong/components/walledGarden/WalledGardenPortalBar.tsx
This makes the frontpage widget link to the new /walledGardenPortal. It also provides an emergency link that can act as a fail-safe for the next week or so while we work out various bugs.
=> Ungate garden portal

packages/lesswrong/lib/collections/tags/schema.ts
Form validation was broken for awhile. During that time, a bunch of fields were added to tags that should've been marked optional for forms purposes, but weren't. Then we fixed validation, and it became impossible to create tags (because some admin-only fields are required).
=> [HOTFIX] Unbreak tag creation

packages/lesswrong/client/vulcan-lib/apollo-client/updates.ts, packages/lesswrong/lib/crud/cacheUpdates.ts
Looks like Apollo, in the shift from 2 to 3, made the data object in the cache immutable, which is an eminently sensible choice, though I wish javascript had some kind of runtime warning about trying to modify frozen objects. This makes it so that we copy the relevant data array. Since we are only doing one level of copying, I think we shouldn't run into any reference stability issues, but might be worth double-checking.
=> Fix apollo update query

packages/lesswrong/components/walledGarden/PortalBarGcalEventItem.tsx, packages/lesswrong/components/walledGarden/WalledGardenPortal.tsx
What the title says. Regarding the URL parsing. The URL object returned does not have a URLParams field (empty) so I still had to use `new URLParams`
=> [HOTFIX] Add technical guidance to Portal Onboarding Page + Slight Code Clean of Link Parsing

packages/lesswrong/components/walledGarden/FrontpageGcalEventItem.tsx, packages/lesswrong/components/walledGarden/PortalBarGcalEventItem.tsx
The google calendar event descriptions were actually HTML, not plain text, and needed to be formatted as such. This PR does that and also makes the frontpage events have hover-over-descriptions.
=> Garden event description formatting

packages/lesswrong/components/common/TabNavigationMenu/TabNavigationItem.tsx, packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
The only UX change is on the EA Forum side, but this adds an ability for `HashLink`s to be external, which is shared functionality.
=> Update EA Forum links 

packages/lesswrong/themes/stylePiping.ts
Hide tiny green circle from `PostLinkPreviewWithPost-link` link elements within spoilers.
=> Hide tiny green circle within spoilers.

packages/lesswrong/lib/collections/posts/custom_fields.ts
Fixes some errors in the permissions, preventing some users from submitting posts. 
This will also prevent users from banning other users from their posts, but that is of course a much smaller group of people.
=> Fix bannedUserIds blocking post submission

packages/lesswrong/components/posts/PostsItemNewCommentsWrapper.tsx
This makes it so that when you expand the comments in a PostsItem, it doesn't refresh, causing all the comments to be collapsed. I really don't know why it had this fetch-policy in the first place, and couldn't break it after playing around for a bit, so I am pretty sure this is fine.
=> Fix fetch policy for new comments wrapper

packages/lesswrong/server/tableOfContents.ts
Some posts failed to generate tables of contents; these failures were showing up in Sentry. The symptom was that the post wouldn't have a ToC, but would otherwise render fine. Here's an example of a post which had its ToC missing: https://www.lesswrong.com/posts/bZ2w99pEAeAbKnKqo/optimal-exercise . This was caused by incorrect handling of blocks which would be eligible for being treated as headings, but which are empty.
=> Fix bug that occasionally broke ToC generation

packages/lesswrong/components/posts/ElicitBlock.tsx
Not sure how to test, but this is copying the same logic from when to darken a slice.
I'm making this PR since Ought wants people to be able to contact us to associate their Elicit account with their LW account, and in testing I discovered that the bucket darkening logic didn't work when a user's LW display name is different from their Elicit display name; the slice darkening still works.
=> Determine darkening of Elicit histogram bucket based on ID rather than display name

packages/lesswrong/components/posts/PostsTimeBlock.tsx
Fixes https://github.com/LessWrong2/Lesswrong2/issues/3695 .
In `PostsTimeframeList`, `componentDidUpdate` sets a `dim` state when the requested list has changed, and expects one of its children (a `PostsTimeBlock`) to call its `timeBlockLoadComplete` callback to signal that it's done loading. But `PostsTimeBlock` only does this if it either remounted or it actually went into a loading state; if the `PostsTimeBlock` was updated in place and gets results from the cache, it skips the loading state and never invoked the callback.
Fix by removing the dependencies-list from the `useEffect`.
=> Fix the all-posts list staying dim/loading after some settings changes

packages/lesswrong/components/posts/BookmarkButton.tsx, packages/lesswrong/server.js, packages/lesswrong/server/bookmarkMutation.ts
The `BookMarkButton` component updates the current user's list of bookmarks. Unfortunately, it was doing this by taking the list of bookmarks client-side from the currentUser object, applying the update there, and then setting the whole list of bookmarks to the resulting object. This means that if you open a bunch of posts in new tabs, then bookmark each of them from its own tab, they will overwrite each others' changes, resulting in only the last post being bookmarked at the end.
Fix this by creating a `setIsBookmarked` mutation, which runs server-side so it is at less risk of using a stale user object. It's still theoretically possible to get bookmarking operations to overwrite each other, since this isn't using atomic mongodb operations, but you'd probably have to send the mutation …
=> Fix bookmarking posts un-bookmarking posts that were bookmarked in another tab

packages/lesswrong/server/rss.ts, packages/lesswrong/server/styleGeneration.tsx
This might fix an issue where, under rare circumstances on Oli's machine, the static stylesheet is interpreted as ISO-8559-1, causing the degree-symbol used to mark hoverable links to be render as mojibake.
=> Specify character set in RSS feed and static stylesheet

packages/lesswrong/components/recentDiscussion/RecentDiscussionTag.tsx
It currently uses the same font as recent-discussion-posts, which makes them hard to tell apart. I think they should probably be even more distinct than this, but this seemed like an incremental improvement.
=> Fix font for recent-discussion-tag

packages/lesswrong/lib/vulcan-lib/collections.ts
Turns out `Utils.deepExtend` had the accidental undocumented side-effect of deleting keys with the value `undefined`, and we were relying on this for Mingo client-side updates. %@#$%#$@%.
=> Fix client-side update of comments

packages/lesswrong/components/posts/PostsTimeBlock.tsx, packages/lesswrong/components/review/FrontpageReviewPhase.tsx, packages/lesswrong/components/shortform/ShortformTimeBlock.tsx
Make the link to the all-of-2019 list default to sort by top, not magic. Make Load More load more at a time.
=> Tweaks for the 2019 review

packages/lesswrong/components/common/TabNavigationMenu/TabNavigationFooterItem.tsx
Same fix as #3645 but for the footer menu items. Reviewed in the EA forum as PR https://github.com/centre-for-effective-altruism/EAForum/pull/123
=> Fix hub link in footer

.eslintrc.js, packages/lesswrong/components/alignment-forum/AFApplicationForm.tsx, packages/lesswrong/components/comments/CommentActions/DeleteCommentDialog.tsx, packages/lesswrong/components/comments/ModerationGuidelines/ModerationGuidelinesEditForm.tsx, packages/lesswrong/components/common/DialogGroup.tsx, packages/lesswrong/components/common/LWDialog.tsx, packages/lesswrong/components/common/SubscribeDialog.tsx, packages/lesswrong/components/localGroups/EventNotificationsDialog.tsx, packages/lesswrong/components/localGroups/GroupFormDialog.tsx, packages/lesswrong/components/localGroups/SetPersonalMapLocationDialog.tsx, packages/lesswrong/components/messaging/ConversationTitleEditForm.tsx, packages/lesswrong/components/questions/NewQuestionDialog.tsx, packages/lesswrong/components/review/NominatePostDialog.tsx, packages/lesswrong/components/shortform/NewShortformDialog.tsx, packages/lesswrong/components/sunshineDashboard/ReportForm.tsx, packages/lesswrong/components/tagging/EditTagsDialog.tsx, packages/lesswrong/components/tagging/TagCTAPopup.tsx, packages/lesswrong/components/tagging/TagFlagEditAndNewForm.tsx, packages/lesswrong/components/users/LoginPopup.tsx, packages/lesswrong/lib/components.ts
Fixes an issue where you couldn't create links in the popup comment editor when nominating posts, and in several other places.
The material-UI `Dialog` component tries to enforce the input focus being inside itself. This breaks when CkEditor pops up a toolbar, and attaches the toolbar to the root rather than making it a child of the editor component. The solution is to pass the `disableEnforceFocus` prop. But needing to always pass this prop makes using the `Dialog` component directly a footgun. So wrap it in an `LWDialog` component, and add a lint rule against using `Dialog` directly.
=> Wrap material-UI Dialog to avoid breaking CkEditor link toolbar

packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx, packages/lesswrong/components/localGroups/CommunityHome.tsx, packages/lesswrong/components/localGroups/TabNavigationEventsList.tsx, packages/lesswrong/components/posts/PostsPage/PostsPage.tsx, packages/lesswrong/components/users/UsersMenu.tsx, packages/lesswrong/lib/collections/posts/views.ts
This PR fixes some issues that were getting in the way of Online Events working nicely:
1. On the community page, there are now separate lists for online and in-person events.
2. On the left navBar (where there were already two lists of online and geographic events), I updated the geographic events to exclude online events.
3. On the left navBar, I _also_ added to the total number of events. This is the boldest change, raising the total to six events. I recognize this is a pretty bold change. I think it is the right call, at least as an experiment. People have been complaining about it being impossible to find events and I think we should just spend a chunk of time erring on the side of "you can definitely find them."
4. I moved the "create event" button into the UsersMenu, so you don't …
=> Online event updates

packages/lesswrong/lib/collections/users/schema.ts
Currently oAuth users can't receive subscription emails, because they don't have a verified email address because the `emails` field just never gets populated. This fixes that by just assuming oAuth emails are verified and adding them to the emails array
=> Automatically verify email address for oAuth users

packages/lesswrong/components/common/withDialog.tsx
This had a significant loading-time performance impact on posts with lots of comments
=> Hookify DialogManager and make its context referentially stable, fixing some spurious rerenders

.eslintrc.js, .meteor/versions, package.json, packages/lesswrong/lib/executionEnvironment.ts, packages/lesswrong/meteor-imports.d.ts, packages/lesswrong/package.js, packages/lesswrong/server/cronUtil.ts, packages/lesswrong/server/debouncer.ts, packages/lesswrong/server/emails/emailCron.ts, packages/lesswrong/server/gatherTownCron.ts, packages/lesswrong/server/posts/cron.ts, packages/lesswrong/server/rss-integration/cron.ts, packages/lesswrong/server/search/algoliaCron.ts, packages/lesswrong/server/vendor/synced-cron/LICENSE-PercolateStudioSyncedCron, packages/lesswrong/server/vendor/synced-cron/README-PercolateStudioSyncedCron.md, packages/lesswrong/server/vendor/synced-cron/synced-cron-server.js, packages/lesswrong/server/vendor/synced-cron/synced-cron-server.ts, packages/lesswrong/server/votingCron.ts, yarn.lock
When we leave Meteor, we must be free of Meteor-using libraries. One such library is `synced-cron`, whose source code lives at https://github.com/percolatestudio/meteor-synced-cron and is MIT licensed. Vendored it, making it no longer an external dependency.
=> Vendor synced-cron

packages/lesswrong/components/tagging/TagSearchHit.tsx
=> When a tag has no posts, in tag-search results say "Tag (0)" instead of "Tag ()"

packages/lesswrong/components/review/FrontpageReviewPhase.tsx
It now properly links to /reviews, which AFAICT properly displays posts with 2+ nominations from the 2019 review
=> Fix reviews button [hotfix]

packages/lesswrong/themes/eaTheme.ts
Now that headers are better about reporting their true size, it's not needed, and was causing an unwanted small grey background.
=> Remove EA header spacing override for Layout

packages/lesswrong/server/gatherTownCron.ts
There was an unhandled string field: next to the status, users can pick an emoji, which is represented by a Unicode string.
=> Fix GatherTown bot again

packages/lesswrong/server/rss-integration/cron.ts
Every so often in development, the RSS-sync cronjob runs, and produce so much log output that you lose any log information from before. This fixes that.
=> Fix spammy logging in RSS feed sync

packages/lesswrong/server/vulcan-lib/utils.ts
The `<ol>` tag is allowed to have `start`, `reversed` and `type` attributes. Stripping `start` caused an issue (misnumbered lists) in the RSS crosspost of https://www.lessestwrong.com/posts/n8PEMJNrns4d3FjY5/covid-12-31-meet-the-new-year .
=> Sanitizer allows the start,reversed,type attributes on <ol> tags

packages/lesswrong/components/users/ReviewVotingPage.tsx
This PR
– factors out year-specific strings on the reviewVoting page into a few top-level variables
– removes the anonymous comment option
– slightly improves the Review button on the reviewVoting page.
– increases the limit from 100 to 200 because not being able to see all the posts seems really annoying.
I tried to make the "reviews2019" view also just inherit from the YEAR variable, but then ran into typecheck errors where "view" doesn't accept an arbitrary string. This didn't seem important enough to figure out how to do, but if someone happens to know, that seems convenient.
This also changes the year from "2018" to "2019." I... think that might just be fine to do now, without advertising it much, but I can change it back if people disagree.
NOTE: Merging into master because I wasn't …
=> Review Page updates [hotfix]

.gitignore, .meteorignore
=> Fix Meteor failing to start if there's a "build" directory leftover from having used the express branch

packages/lesswrong/components/common/LWTooltip.tsx, packages/lesswrong/components/tagging/FilterMode.tsx, packages/lesswrong/components/tagging/TagFilterSettings.tsx
This increases the visibility of the personal-blog-filter for logged in users, who currently have it set to Hidden.
A change that might have wider ramifications: I made it so LWTooltip doesn't set it's width to 300 if the "tooltip" param is false. I checked for uses of this and *think* all the uses I could find were fine after the change, but it is possible I missed something.
I think the UI happens to look a bit janky when we have a CTA Voting button right above it, but that won't be true most of the year I think.
=> More visibility on show personal blogposts

packages/lesswrong/components/review/FrontpageReviewPhase.tsx
=> Make the Review timeline look good on mobile

packages/lesswrong/components/comments/CommentWithReplies.tsx, packages/lesswrong/components/review/PostReviewsAndNominations.tsx
This uses the tools we built to show some (but not all) children of shortform comments to make the Voting page more legible. (i.e. if there's been a huge thread on a given review-comment, you won't see all 20 replies, but you'll see the most recent 3 replies, and see that there are more you can view)
=> Show (some) children of reviews on voting page

packages/lesswrong/client/vulcan-lib/apollo-client/links/error.ts, packages/lesswrong/components/vulcan-forms/FormErrors.tsx, packages/lesswrong/lib/vulcan-lib/intl.ts, packages/lesswrong/server/vulcan-users/callbacks.ts
Three bugs:
* Need to null check the strange copy of error locations.
* If no internationalization message is found, return the default message.
* Guard against empty list when updating emails.[1]
[1] It took me too long to memorize these so I'll repeat them here for helpfulness:
```
0: falsey
"": falsey
[]: truthy
{}: truthy
```
=> Fix bugs discovered while investigating user form issue

packages/lesswrong/components/posts/PostsHighlight.tsx, packages/lesswrong/components/recentDiscussion/RecentDiscussionThread.tsx
Makes recent discussion highlights smaller if you've already read them, and sets the maxHeight to 500 instead of 1000px.
(note: at some point someone should fix highlights such that if they have a bunch of images, the "show more" button doesn't get crowed out below the max-height)
=> visitedAt recent discussion items are smaller

packages/lesswrong/components/sunshineDashboard/SunshineNewUserCommentsList.tsx, packages/lesswrong/components/sunshineDashboard/SunshineReportedItem.tsx
I found it hard to tell when a reported item was a post, or comment. Also I usually care about seeing the parent comment if there is one. I switched it from using a custom sunshine component to using the usual CommentsNode
=> SunshineReportItem-hover-over uses CommentsNode

packages/lesswrong/lib/collections/posts/custom_fields.ts, packages/lesswrong/server/callbacks/postCallbacks.ts
```
// For posts without comments, update lastCommentedAt to match postedAt
//
// When the post is created, lastCommentedAt was set to the current date. If an
// admin or site feature updates postedAt that should change the "newness" of
// the post unless there's been active comments.
```
The motivating factor is Aaron's desire to ad a bunch of old posts without them clogging up recent discussion.
=> Update lastCommentedAt for commentless posts on new postedAt

packages/lesswrong/components/tagging/TagHoverPreview.tsx, packages/lesswrong/lib/routeUtil.tsx
Before: Links to tags with showPostCount=true are bare in the SSR, then switch to having a degree symbol, then switch a second time to having a post count. This removes the second of those three states.
Also, if a tag link has query parameters that influence the preview, ie `showPostCount` and `useTagName`, leave them out of the link target.
=> No intermediate degree symbol on tags

packages/lesswrong/components/sunshineDashboard/SunshineSidebar.tsx
I'm not sure whether this is longterm good, but I've been missing the "something needs curating" message fairly frequently and it seemed worth experimenting with moving the curated-list to the top. (shouldn't affect most of our day-to-day since it's usually hidden)
=> Move suggest curated to top of sidebar

packages/lesswrong/components/users/UsersProfile.tsx
I'm not sure I did this right, but the idea is:
Sometimes users make bios that look _plausibly_ spammy, but not overdeterminedly spammy, before they make their first post. We mostly don't want to have to evaluate those bios. It'd be nice if they just didn't give the spammer any credit for existing, so we didn't have to worry about them. I'm not sure this is actually sufficient to discourage spammers but seemed like an improvement over status quo.
=> noIndex for users with no posts, comments or karma

packages/lesswrong/components/common/ContentItemTruncated.tsx, packages/lesswrong/components/posts/PostsHighlight.tsx
Fixes the issue in recent discussion where large images would hit the max-height of a postHighlight, and then prevent the "show all" button from appearing.
=> fix max height recent-discussion bug

packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx, packages/lesswrong/components/posts/PostsItemMeta.tsx, packages/lesswrong/components/posts/PostsPage/ContentType.tsx, packages/lesswrong/components/posts/PostsPreviewTooltip.tsx, packages/lesswrong/components/posts/PostsTimeBlock.tsx, packages/lesswrong/components/tagging/FooterTagList.tsx, packages/lesswrong/lib/instanceSettings.ts
Changes to make the Frontpage/Personal thing easier to understand/more legible.
* Frontpage/Personal buttons in the tag-list are links to a post about the distinction
* The Frontpage/Personal/Curated status is shown in Recent Discussion
* Posts are not marked as Personal Blog in their tag list or hover preview if they have not yet been reviewed
=> Frontpage personal tag improvements

packages/lesswrong/components/walledGarden/GardenCodesList.tsx, packages/lesswrong/components/walledGarden/GatherTown.tsx, packages/lesswrong/components/walledGarden/WalledGardenHome.tsx, packages/lesswrong/components/walledGarden/WalledGardenPortal.tsx, packages/lesswrong/lib/collections/gardencodes/collection.ts, packages/lesswrong/lib/collections/gardencodes/views.ts
Fixes a bug that hid all Walled Garden events on the front page, except from their creator. Removes obsolete mentions of a Walled Garden password. Adds a `hidden` field, so that a particular AI Impacts link with a month-long date range can be made to not permanently fill the top slot.
=> [HOTFIX] Walled garden fixes

packages/lesswrong/lib/collections/posts/custom_fields.ts
Before: If both canonicalNextPostSlug/canonicalPrevPostSlug and canonicalSequenceId are present, then for purposes of finding the next/prev post, canonicalSequenceId is ignored. If the canonical next/prev slug points to a post that doesn't exist or is inaccessible (such as a draft), then is no next/previous link.
After: canonicalSequenceId takes precedence over canonicalNextPostSlug/canonicalPrevPostSlug, which are only meant to be used for bridging the gaps at the start and end of sequences which connect to each other. If canonicalSequenceId is invalid or can't be used to find a next/prev post.
=> Change handling of canonicalSequenceId to fix some broken sequence navigation

packages/lesswrong/lib/editor/ellipsize.tsx, packages/lesswrong/themes/stylePiping.ts
`pBodyStyle` in `stylePiping.ts` has a `&:first-child` selector which removes the top-margin from the first paragraph. But there might be a MathJax stylesheet mixed into the post text, and if there is, that stylesheet is the first child, not the paragraph. `truncate` removed the styles from the beginning and put them back at the end, rather than the beginning, so it changes the vertical position. This made it so that if a post has MathJax, clicking See More on it would cause it to shift vertically, which is pretty disorienting.
=> Fix text vertically shifting when expanded in Recent Discussion

packages/lesswrong/components/walledGarden/GatherTown.tsx, packages/lesswrong/server/gatherTownCron.ts
Detects various errors that can happen when the GatherTown bot tries to get a list of connected users. Makes it so that if the last user check encountered an error, users are told that we couldn't autodetect whether users are connected, rather than telling them that no one is online.
Handles HTTP error status codes during initialization and connection failure of the websocket (in theory should cover the case where the server URL no matches the database setting, but not tested). Handles the case where the server sends a "reload" message and nothing else, which is what it does if the version number we send does not match the current version number.
=> [HOTFIX] Disable broken GatherTown user tracking

packages/lesswrong/components/books/BookAnimation.tsx, packages/lesswrong/components/books/BookFrontpageWidget.tsx, packages/lesswrong/components/review/BookCheckout.tsx, packages/lesswrong/lib/collections/posts/custom_fields.ts
Currently our Amazon page works for the US, but mostly not for other countries. For US orders, selling through Amazon is preferable because (a) people can leave Amazon reviews, and (b) Jacob doesn't have to do a manual process to get them their book.
Replace the Pre-Order button with two Buy buttons, one for the US (which goes to Amazon) and one for International (which goes to Stripe).
=> Add a second Buy button which goes to Amazon instead of Stripe

packages/lesswrong/server/ckEditorToken.ts
The `/ckeditor-token` endpoint returned binary without a MIME type. Firefox would attempt to parse it as XML, producing a console error. (This didn't break anything conspicuous, but would probably break collaborative editing, and a console error is a console error.)
=> Fix console error under Firefox due to ckEditor token not having a MIME type

packages/lesswrong/server/search/utils.ts
Broken in this commit: 98e19da08807002c8eadc633ca5ef684a71184de . Valid type error foolishly suppressed in this commit: 5884a20784d8ae9b77b9b92437d3f8a52f1f99ce .
=> Fix broken Algolia index updating

packages/lesswrong/lib/random.ts
In the process of migrating away from Meteor, we wrote our own versions of some Meteor random-ID-generation functions, including the `randomSecret` function. This function is used for generating token links in emails (for password reset and unsubscribe) and nothing else. Unfortunately, in node's `crypto` library, "base64" uses the `+` and `/` characters, which are not URL-safe. (There is a different variant of base64 which uses - and _, which would have been fine; see https://en.wikipedia.org/wiki/Base64.) The practical upshot is that we sent out some emails where the token link was broken, and clicks on those links showed up as errors in Sentry.
=> Fix broken email-token links

packages/lesswrong/server/notificationTypesServer.tsx
Introduced in https://github.com/LessWrong2/Lesswrong2/pull/3158 and discovered in Sentry: https://sentry.io/organizations/lesswrong/issues/2218600431/?environment=production&project=1301611&query=is%3Aunresolved&statsPeriod=14d .
=> Fix bug that made new-tag-post notifications not emailable

packages/lesswrong/lib/collections/posts/schema.ts
Allow admins to edit the post setting `canonicalSource`, allowing them to set the `rel="canonical"` tags on linkposts that are not auto-posted through RSS.
=> Make canonicalSource admin-editable

packages/lesswrong/components/editor/EditorFormComponent.tsx
Fix spurious "you have unsaved changes" warning when you type into an input and then delete all of it. Introduced in 4172241a03746a9d02d20d02164ac40b3715d9ce.
=> Fix spurious unsaved-data warnings when you edit and then clear an input

packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx
The EA Forum a few months ago made the decision to automatically categorize posts as frontpage unless marked otherwise. There was a bug in our approach, in that marking posts as personal using the sunshine sidebar did not categorize them as personal. This is due to the fact that LW does not need to mutate the frontpageDate field on personal categorization. The field is already null, and you leave it null. However, we need to explicitly set it to null. This PR does so. I don't foresee an issue with it for LW. I've thought about it, and I can't think of a time where you'd want to click the icon that says "Personal" and not set the frontpageDate field to null, even if it did somehow manage to be in the sidebar while also having frontpageDate set.
I've tested that the behavior is correct …
=> Make categorizing posts as personal remove frontpageDate

packages/lesswrong/server/forwarded_whitelist.ts
The X-Forwarded-For HTTP header contains a comma-separated list with the real client IP address first, followed by the IP addresses of any intermediate proxies https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For). A bit of code copied from StackOverflow was taking this header and taking the last item in the list (which is a proxy) rather than the first item in the list (which is the desired client IP). Introduced while converting from Meteor accounts passportjs, in commit e74a2fa7396ad5e6b1a1ed2ff260eeea8066b9c8.
=> Fix IP-address tracking

packages/lesswrong/server/resolvers/elicitPredictions.ts, public/lesswrong-editor/src/ckeditor.js
We're moving the current elicit.org to forecast.elicit.org. These changes should be all that LW needs to do to accomodate this.
=> Change elicit.org to forecast.elicit.org

packages/lesswrong/components/linkPreview/PostLinkPreview.tsx
On Firefox (not in Chrome), on first render (goes away when the browser is horizontally resized), the degree symbol after links that have a hover-preview is mis-positioned. This seems to be because of an interaction between a bug in Firefox, and a weird CSS hack in the implementation of that degree symbol. But AFAICT the CSS hack doesn't seem to do anything; I'm not sure why it's there, and everything seems to work if I take it out.
=> Fix mis-positioned degree-sign marker on links in Firefox first render

packages/lesswrong/components/tagging/AllTagsPage.tsx
Does what it says on the tin. Page is redundant with Tagging Dashboard and just clutters things up.
=> Remove TagDetails sections from Concepts Page

packages/lesswrong/themes/stylePiping.ts
=> Fixes the footnote quote scaling discussed in issue 3962

packages/lesswrong/lib/analyticsEvents.tsx
This PR adds documentation about how AnalyticsContext wrappers are to be used. Will shortly be accompanied by use of type enforcement.
=> Add documentation for AnalyticsContext

packages/lesswrong/components/common/Home2.tsx
Makes the frontpage redirect to lesswrong.substack.com.
Only does it on SSR. When you navigate to it from a post-page, it doesn't redirect. 
The redirect can be circumvented by adding `?avoidAprilFools=true` to the URL.
=> Implement redirect for April Fools

packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUsersProfileInfo.tsx, packages/lesswrong/components/users/UsersProfile.tsx, packages/lesswrong/lib/collections/users/custom_fields.ts, packages/lesswrong/lib/components.ts
Factors out the SunshineNewUsersItem hoverover into a new component, which can then be displayed on the UserProfile page to admins. This makes it easier for moderators to link each other to "edge case" users, and discuss them.
I'm experiencing a weird bug. In a previous recent PR I added an "Input" field to SunshineNewUsersItem. It renders normally in the sunshine sidebar:
But on the UserProfile page, there are two extra "textarea" fields which are supposed to be hidden, but aren't:
=> SunshineUserInfo in profile

packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.tsx, packages/lesswrong/lib/collections/users/custom_fields.ts, packages/lesswrong/lib/collections/users/fragments.ts, packages/lesswrong/lib/collections/users/views.ts, packages/lesswrong/lib/generated/databaseTypes.d.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
Adds the "sunshineFlagged" field to new users, which bumps a user to the top of the sunshine queue and gives a small visual indicator.
Also fixes some permissions and default field errors in the sunshine sidebar.
=> Sunshine flag

packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx
Previously, the "review" button got hidden instead of being disabled, which made it hard to use muscle memory to know what button to click.
=> Disable review button instead of hiding it

packages/lesswrong/components/posts/PostsPreviewTooltip.tsx
In a few different contexts (most recently Sunshine Sidebar) I've found myself wanting to know if a post was old or new. Adding a small date to the hoverover seemed nice.
=> Include date in post tooltip

packages/lesswrong/components/posts/PostsTitle.tsx, packages/lesswrong/components/sunshineDashboard/CommentKarmaWithPreview.tsx, packages/lesswrong/components/sunshineDashboard/PostKarmaWithPreview.tsx, packages/lesswrong/components/sunshineDashboard/SidebarHoverOver.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUserPostsList.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUsersItem.tsx, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
I found myself wanting to more easily skip past the flagged users (since those are users I already thought about and now I'm waiting for someone else to comment on), so adding a more noticeable visual indicator.
Also fixes other things like:
1. mousing off the hoverover saves your notes instead of discarding them
2. the drafts don't all say "[shared]"
3. I recently started making drafts more prominent in the sunshineNewUsersInfo, but then they ended up kinda _too_ prominent, and now it shows only the titles, not the bodies.
=> red sunshineFlagged background

packages/lesswrong/lib/utils/browserProperties.ts
Log to our postgres analytics DB whether a user has Google Analytics and Google Tag Manager blocked.
Among the US population, ~27% use adblock: https://www.statista.com/statistics/804008/ad-blocking-reach-usage-us/ . uBlock Origin blocks Google Analytics by default (I checked), and I think most other adblock does too (but I didn't check).
Use of adblock is strongly correlated with general internet-sophistication, which means that among our userbase, it may be a lot higher, and among the subset of users we care most about, I expect it to be higher still. This means Google Analytics may be specifically measuring the least-sophisticated subset of our users, which would be pretty bad.
=> Log to postgres analytics whether Google Analytics is blocked

packages/lesswrong/components/linkPreview/PostLinkPreview.tsx
Showed up in Sentry. Example affected comment: https://www.lesswrong.com/posts/5vogC4eJ4gXixX2KJ/should-i-believe-what-the-siai-claims?commentId=m9ZrS8immMiueFPyJ .
=> Fix crash in link-preview for malformed links

packages/lesswrong/components/common/AnalyticsClient.tsx, packages/lesswrong/lib/analyticsEvents.tsx, packages/lesswrong/lib/vendor/colorHash.ts
While Ray and I were trying to figure out the referrer of a bad user in the Sunshine sidebar, I noticed that our SQL analytics events aren't logging client IDs properly. This is caused by a dumb typo, introduced by me. Oops, sorry about that. But the actual root issue is that the outgoing analytics events are hard to look at and test, so I went ahead and addressed that.
Problem: Analytics events don't get much testing, because they're hard to see, creating data-quality issues. But dumping them all to the browser console would be really spammy and hard to read. Ideally there would be a way to look over the analytics events going by which is formatted in a way that's compact, and  makes it easy to parse what's going on.
Solution: Fancy browser console-logging APIs. We show analytics events …
=> Fix missing clientIDs in analytics, and better logging surrounding analytics events (approved with caveats)

packages/lesswrong/lib/collections/sequences/schema.ts
The `chapters` resolver on the `Sequences` collection was removed as unused in e006210833e2908094a38079a6b1de55e1eca9e3, but started generating Sentry errors, suggesting an external usage. Put the resolver back.
=> Put back an internally-unused resolver that's being used externally

packages/lesswrong/components/users/ViewSubscriptionsPage.tsx
From Pablo: 
Steps to reproduce:
1. Open [this link](https://forum.effectivealtruism.org/tag/certificates-of-impact/discussion)
2. Click on three vertical dots, 'Subscribe to comment replies'
3. Go to your profile, 'Manage subscriptions'
4. Under 'Subscribed to comment replies', follow the link 'author: MichaelA post:'
The URL should point to MichaelA's comment, but instead points to forum.effectivealtruism.org
(I noticed this because I would like to subscribe to comment replies as a way of keeping track of the comments I still haven't responded to.)
=> Fix tag comment subscription management

packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx
Hopefully fixes the issue where if someone else updates a sunshine-user-notes, and then I accidentally mouseover it before reloading my own page, it overrwrites their work.
=> fix bug with overwriting sunshineNotes

packages/lesswrong/lib/globalStyles.ts
Found myself annoyed by thoughtsaver iframe styling and wanted to slightly improve it. Current version has drop shadows because I like them, and because I think the color of grey is juuuuust a bit too hard too hard to see (causes some eyestrain).. But, I think it also works okay if we remove the drop shadow.
option 1:
option 2:
=> thoughtsaver slightly prettier

.dockerignore, Dockerfile, package.json, packages/lesswrong/components/posts/PostsPage/ContentType.tsx, packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx, packages/lesswrong/components/users/UsersMenu.tsx, packages/lesswrong/lib/collections/tags/views.ts, packages/lesswrong/server/vulcan-lib/apollo-server/authentication.tsx, scripts/postinstall.sh
The main interesting change is that the Docker build can be greatly sped up. This is valuable when you're making changes locally and testing a deploy from your local machine, which isn't that common. However, when you do want to do so, it's a world of difference. The idea is that Docker tries to cache the results of previous builds. However when an input changes, all further caches are invalidated. The implication of that is that you want to delay `COPY . .` as long as possible. Specifically, try to do it after the yarn install. In an even more impactful move, we add .meteor to the dockerignore file, to avoid copying over the whole freaking database.
=> Fixes discovered during merge

packages/lesswrong/components/users/UsersNameDisplay.tsx, packages/lesswrong/lib/analyticsEvents.tsx, packages/lesswrong/lib/collections/comments/helpers.ts, packages/lesswrong/server/emailComponents/NewPostEmail.tsx, packages/lesswrong/server/loginTokens.ts, packages/lesswrong/server/vulcan-lib/apollo-server/authentication.tsx, packages/lesswrong/server/vulcan-lib/apollo-server/context.ts
* New-post emails show if it's a linkpost
* Enforce bans on existing user login tokens
* Fix warning during startup about trying to get analytics-debug config setting before it's loaded
* Fix truncated coauthor lists on PostsItem2
* Fix broken links to comments in emails due to adding the prefix twice
=> Bugfix roundup

packages/lesswrong/components/Layout.tsx, packages/lesswrong/components/common/TabNavigationMenu/NavigationDrawer.tsx, packages/lesswrong/components/posts/PostsPage/PostsPage.tsx, packages/lesswrong/components/posts/TableOfContents/TableOfContents.tsx, packages/lesswrong/components/posts/TableOfContents/TableOfContentsList.tsx, packages/lesswrong/components/posts/TableOfContents/TableOfContentsRow.tsx, packages/lesswrong/components/posts/TableOfContents/ToCColumn.tsx, packages/lesswrong/components/posts/TableOfContents/index.ts, packages/lesswrong/components/questions/NewAnswerCommentQuestionForm.tsx, packages/lesswrong/components/questions/NewRelatedQuestionForm.tsx, packages/lesswrong/components/questions/PostsPageQuestionContent.tsx, packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/components/tagging/TagPageButtonRow.tsx, packages/lesswrong/lib/collections/comments/helpers.ts, packages/lesswrong/lib/collections/posts/custom_fields.ts, packages/lesswrong/lib/collections/tags/fragments.ts, packages/lesswrong/lib/collections/tags/schema.ts, packages/lesswrong/lib/components.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts, packages/lesswrong/lib/generated/viewTypes.ts, packages/lesswrong/lib/vulcan-lib/utils.ts, packages/lesswrong/server/tableOfContents.ts
Tag pages have tables of contents. Various changes to ToC code to make it able to handle things that aren't posts. Tag descriptions aren't usually long enough to need ToCs, but this provides a place to put the contributor-list, which will come in a future PR.
=> Tag pages have table of contents

package.json, yarn.lock
Having added `@types/react-jss` caused `react-jss` to be upgraded across a major version boundary, mostly breaking it. Remove that.
=> Remove @types/react-jss, which broke JSS functionality

packages/lesswrong/server/authenticationMiddlewares.ts
I think this is the right way to prepopulate the email field. The old way was definitely wrong and caused terrible bugs.
=> Fix google auth emails field populating

packages/lesswrong/components/common/Home2.tsx, packages/lesswrong/lib/collections/users/custom_fields.ts
Walled Garden widget isn't currently working, and I think it just makes sense to remove unless we consciously decide to prioritize it.
=> Remove walled garden from frontpage

packages/lesswrong/components/users/UsersProfile.tsx, packages/lesswrong/lib/collections/users/custom_fields.ts, packages/lesswrong/lib/collections/users/fragments.ts, packages/lesswrong/lib/generated/databaseTypes.d.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts, packages/lesswrong/server/authenticationMiddlewares.ts, packages/lesswrong/server/callbacks/revisionCallbacks.ts, packages/lesswrong/server/editor/make_editable_callbacks.ts, packages/lesswrong/server/migrations/2021-06-05-fillWikiEditCount.ts, packages/lesswrong/server/migrations/index.ts
To give feedback to users who make wiki edits, we wanted to showcase their contributions on their profile. @s-cheng joined us on this one.
This PR was _almost_ dead simple. It looked like she had it after figuring out that tagRevisionCount could be a denormalizedCountOfReferences. However, the way denormalizedCountOfReferences works is that it registers callbacks on the foreign collection to increment the count. Unfortunately, Revisions are created without going through the normal mutator flow that would involve running those callbacks. Instead the new revisions are directly inserted inside of make_editable_callbacks.
Which brings us to our proposed refactor: the make_editable_callbacks can very easily be refactored to call createMutator instead of Connectors.create. I've examined …
=> Add number of wiki edits to user profiles

packages/lesswrong/components/ea-forum/EAHome.tsx, packages/lesswrong/components/ea-forum/StickiedPosts.tsx, packages/lesswrong/components/posts/PostsItem2.tsx, packages/lesswrong/components/posts/PostsTitle.tsx, packages/lesswrong/lib/collections/posts/constants.ts, packages/lesswrong/lib/collections/posts/views.ts, packages/lesswrong/lib/components.ts, packages/lesswrong/themes/eaTheme.ts
Also by @jcmustin. Should only affect the EA Forum. Allows us to pin more posts without it feeling too crowded, and also adds a decoration to pinned AMAs, Open Threads, and the Start Here post.
=> Give Stickied posts their own status on the frontpage

packages/lesswrong/components/posts/TableOfContents/TableOfContentsRow.tsx, packages/lesswrong/components/tagging/RandomTagPage.tsx, packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/lib/components.ts, packages/lesswrong/lib/routes.ts, packages/lesswrong/server/resolvers/tagResolvers.ts, packages/lesswrong/testing/debouncer.tests.ts
Adds a Random Tag link to the ToC sidebar, which takes you to a randomly selected tag or wiki page (via `/tags/random`).
=> Add Random Tag link to tag page ToC sidebar

packages/lesswrong/components/users/WrappedLoginForm.tsx, packages/lesswrong/lib/collections/users/custom_fields.ts, packages/lesswrong/server/vulcan-lib/apollo-server/authentication.tsx
Fixes the password field on the login form being mislabeled. Fixes the terrible internal-error message you get when you attempt to sign up with a username or email that's already taken. Fixes crash when a Sunshine who isn't an Admin attempts to edit a user. Fix incorrect permissions on the Legacy field, which leaked all imported password hashes.
=> Fix bugs in user handling

packages/lesswrong/components/posts/TableOfContents/ToCColumn.tsx, packages/lesswrong/components/tagging/AllTagsPage.tsx
Moves the scrollbar for tables of contents back to the left. Adds some Firefox-specific styling to pair with the preexisting WebKit-specific styling. Makes the [+] button next to the words New Tag clickable on the Concepts page.
=> Fix ToC scrollbar styling; fix clickability of the + button next to New Tag

packages/lesswrong/server/emailComponents/EmailFooterRecommendations.tsx, packages/lesswrong/server/emailComponents/EmailWrapper.tsx, packages/lesswrong/server/emailComponents/NewPostEmail.tsx
Developed while pairing with @jimrandomh . Jim's preferred problem, my driving.
If you read a post in your email client, and you reach the end, you're currently offered to view the discussion, but if you're not a "view discussion" kinda person, there's no further call to engagement. This PR adds a list of recommended posts to further read if the reader is interested in continuing.
We use the same recommendations logic that powers the frontpage and /recommendations. We apply some styling updates to get consistent vertical spacing.
We did *not* send ourselves an actual email this way, which should probably be done before deploying.
Future work could involve:
* Prioritizing the list better, perhaps by using the motivation tag
* Using the referrer to count clicks
* Building email AB testing
=> Include post recommendations at end of curation email

packages/lesswrong/components/tagging/TagContributorsList.tsx, packages/lesswrong/lib/collections/tags/fragments.ts, packages/lesswrong/lib/collections/tags/schema.ts, packages/lesswrong/lib/generated/databaseTypes.d.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts, packages/lesswrong/server/resolvers/tagResolvers.ts
The score in contributor lists has a hover-over which shows the total score, number of votes included in that score (ie with only one self-vote), and number of edits.
=> Tag contributor score has hover-over with vote count, num commits

packages/lesswrong/components/comments/CommentPermalink.tsx, packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
This PR updates the head tags used by social previews (e.g. on Facebook or Twitter) for comment permalinks, such that the description displayed comes from the comment rather than the post. At present the format of the description is "Comment by {username} - {comment text}", though I'm very open to suggestions on that if people would prefer a different syntax.
=> Customize Social Preview Description for Comment Permalinks

packages/lesswrong/lib/analyticsEvents.tsx
It does in fact force the database setting to need to have a space in it.
=> Remove extra space from analytics-debug database setting

.github/workflows/unitTests.yaml
Add a step for running lint to the Github test yaml. Was discussed on slack. It adds about 100s to the testing time, which is unfortunately, but in my view worth it.
=> Run lint on Github CI

packages/lesswrong/lib/collections/messages/schema.ts
#4093 made it so that users could now set the `userId` of messages they were sending, which isn't intended behavior, and also makes the form look weird and broken. This fixes this.
=> Hide userId field in PM form

packages/lesswrong/lib/collections/posts/schema.ts
Aaron uses this extensively. It's unfortunate that it's not a better user experience, but it's important that he can do it.
The capability to do so was (inadvertently?) removed in this PR: https://github.com/LessWrong2/Lesswrong2/pull/4093/files .
I've tested that the editing works.
=> Allow Admins to Edit Author ID

.eslintrc.js, packages/lesswrong/components/common/Typography.tsx, packages/lesswrong/components/ea-forum/EASequencesHome.tsx, packages/lesswrong/components/recommendations/RecommendationsList.tsx, packages/lesswrong/components/review/ReviewVotingPage.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUsersInfo.tsx, packages/lesswrong/components/tagging/TagFilterSettings.tsx, packages/lesswrong/components/users/NewUserCompleteProfile.tsx, packages/lesswrong/components/walledGarden/GardenCodeWidget.tsx, packages/lesswrong/components/walledGarden/WalledGardenHome.tsx, packages/lesswrong/components/walledGarden/WalledGardenPortalBar.tsx
Importing `@material-ui/core` causes unused parts of material-UI to get included in the bundle. Don't do that. Reduces (uncompressed, unminified) bundle size from 12.37 to 12.15MB (~2%).
=> Fix material-UI being imported in a way that breaks tree-shaking

.github/workflows/unitTests.yaml, packages/lesswrong/components/common/hocTypes.ts, packages/lesswrong/components/users/UsersAccountMenu.tsx, packages/lesswrong/components/users/WrappedLoginForm.tsx, packages/lesswrong/lib/analyticsEvents.tsx, packages/lesswrong/lib/vulcan-lib/components.tsx, packages/lesswrong/server/apolloServer.ts, packages/lesswrong/server/authenticationMiddlewares.ts
Currently:
* You're looking at a great post you want to upvote
* You upvote the post or you click the login button in the top-right
* You log in with google/facebook/github/EA.org
* You're redirected to the homepage, and have to navigate back to the post
This PR saves a desired redirect in the session, so that when you get back to /auth/[oauth]/callback, we can redirect you to the right place. It uses a query parameter in the link to /auth/[oauth] to determine the desired redirect.
The PR **does not** implement this for LW. LW does not currently use express-session, and I don't know if y'all wanted to (and it was work), so I also didn't make query parameters for y'all. If you would like to use it, you'll need to:
* Add expressSessionSecret to your database server settings
* Add query …
=> Redirect upon return from OAuth provider

packages/lesswrong/lib/collections/posts/views.ts
Added this to make it easier to query for potential posts to curate. It's currently just a secret additional filter we can enter into the allPosts url parameters.
=> Add an uncurated filter to allPosts

packages/lesswrong/lib/collections/users/views.ts, packages/lesswrong/server/authenticationMiddlewares.ts
When users sign in/up for the first time using the new login system, we take their email address and attempt to match it against an existing user in the DB. In the case of a match, we merge the accounts. Historically, the Forum used case-sensitive email address, like LW, probably because it was easier. Un(?)fortunately Auth0 downcases the users email address. So even if the users puts their uppercase email into Auth0, we'll always get a lowercase email from Auth0 once their authenticated. So now comes the time where we need to do case-insensitive email lookups.
The way to do case-insensitive lookups is to specify the collation option to the mongodb find command. You could use a regex for it, but there's no way to create an index (see below) for the regex search. The strength of the …
=> New Auth0 users are checked against existing users by a case-insensitive email search

packages/lesswrong/components/localGroups/CommunityMap.tsx, packages/lesswrong/components/localGroups/LocalGroupsList.tsx, packages/lesswrong/components/localGroups/StyledMapPopup.tsx, packages/lesswrong/components/posts/PostsItemDate.tsx
* On event postitems, show year if it's not the current year
* Fix there being a horizontal scrollbar on the community page
* Fix spurious scrollbars on Mapbox click popups
* Remove a spurious bullet after the Load More link on the local groups list
=> Community page fixes

packages/lesswrong/components/search/CommentsSearchHit.tsx, packages/lesswrong/components/search/PostsSearchHit.tsx
Fixes bug whereby search preview extends outside of div.
=> fix-search-word-break

package.json, yarn.lock
Upgrades `@shelf/jest-mongodb` across a major version, dropping compatibility with old node versions that we don't care about, and adding compatibility with Apple M1 hardware. This upgrade triggers an upgrade of dependency library `uuid` from v7 to v8, which breaks `@google/maps`, so pin it at v7. (Based on https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md it doesn't look like anything was added in v8 that actually matters for compatibility, but there's some risk as many other libraries also depend on uuid.)
=> Upgrade jest-mongodb library for compatibility with M1 hardware

packages/lesswrong/lib/collections/bans/collection.ts, packages/lesswrong/lib/collections/books/collection.ts, packages/lesswrong/lib/collections/chapters/collection.ts, packages/lesswrong/lib/collections/collections/collection.ts, packages/lesswrong/lib/collections/comments/collection.ts, packages/lesswrong/lib/collections/gardencodes/collection.ts, packages/lesswrong/lib/collections/localgroups/collection.ts, packages/lesswrong/lib/collections/messages/collection.ts, packages/lesswrong/lib/collections/notifications/collection.ts, packages/lesswrong/lib/collections/postRelations/collection.ts, packages/lesswrong/lib/collections/posts/collection.ts, packages/lesswrong/lib/collections/readStatus/collection.ts, packages/lesswrong/lib/collections/reports/collection.ts, packages/lesswrong/lib/collections/rssfeeds/collection.ts, packages/lesswrong/lib/collections/rssfeeds/schema.ts, packages/lesswrong/lib/collections/sequences/collection.ts, packages/lesswrong/lib/collections/tagFlags/collection.ts, packages/lesswrong/lib/collections/tags/collection.ts, packages/lesswrong/lib/collections/users/collection.ts, packages/lesswrong/lib/collections/users/custom_fields.ts, packages/lesswrong/lib/editor/make_editable.tsx, packages/lesswrong/lib/types/collectionTypes.ts, packages/lesswrong/lib/types/schemaTypes.ts, packages/lesswrong/lib/utils/schemaUtils.ts, packages/lesswrong/lib/vulcan-lib/collections.ts, packages/lesswrong/server/fieldChanges.ts, packages/lesswrong/server/vulcan-lib/mutators.ts
This is motivated by occasionally seeing things in weird states, and wanting to know the history of user/moderator actions. Eg, was this post moved back to drafts by the user, or by a moderator, and if a moderator then which one? Has this user had their name/slug changed? Did this wiki-tag used to have a different name, and who renamed it?
This solves the problem in general, by logging most changes (that go through mutators) to fieldChange events in the LWEvents collection. Fields that are marked as denormalized are excluded, as are content fields (which are already versioned through the Revisions collection) as are a few other miscellaneous things.
No user interface is provided for viewing this information, it's just database logging (for now).
=> Log field changes to LWEvents

packages/lesswrong/components/tagging/EditTagPage.tsx, packages/lesswrong/components/tagging/TagPage.tsx
Just add in resetStore as suggested.
Note, this quick PR has turned up other issues with editing on the Tag Dashboard page, not addressed here.
=> Fix How Tag Edits Don't Show Until refresh

packages/lesswrong/server/vulcan-lib/utils.ts
This got broken by a CkEditor upgrade, which changed the way it expresses the `style` attribute on `table`, `td` etc to use a different subset of the CSS `border-*` attributes. The new styling would generate the same appearance, except that some of the attributes aren't in the HTML validator whitelist, so they got strippedo ut on save. So add `border`, `border-color`, and `border-style` to the HTML validator whitelist so they go through. The appearance of the Concepts page will be fixed on the next edit-and-resave after this merges.
=> Fix styling on the Concepts page

packages/lesswrong/components/posts/PostsEditForm.tsx, packages/lesswrong/components/posts/PostsNewForm.tsx
Fixes the fact that saving to draft causes popup and submission.
=> Make it so popup and submission only occur when posting, not drafting.

packages/lesswrong/lib/collections/revisions/collection.ts
There was an unsuccessful fix attempt for this same bug previously: https://github.com/LessWrong2/Lesswrong2/commit/8d669cb967bb32d184ede3070d1a93930e8d1e27.
=> Fix imported wiki/tag revisions being hidden from non-admins

packages/lesswrong/lib/collections/users/helpers.ts, packages/lesswrong/lib/vulcan-users/helpers.ts, packages/lesswrong/server/emailComponents/EmailWrapper.tsx, packages/lesswrong/server/emails/renderEmail.tsx, packages/lesswrong/server/emails/tests.tsx, packages/lesswrong/server/notificationBatching.tsx, packages/lesswrong/server/notificationCallbacks.tsx
Makes it so that comments on event posts get emailed to people who have RSVPed to the event. Most of the complexity here is dealing with the fact that people can RSVP without logging in, and a bunch of existing email stuff had the assumption baked in that emails go to an existing user.
TODO: Unsubscribing is currently not handled if you don't have an account.
=> Email comments on event posts to RSVPed users

packages/lesswrong/components/posts/PostsEditForm.tsx, packages/lesswrong/components/questions/NewQuestionDialog.tsx, packages/lesswrong/lib/alignment-forum/posts/custom_fields.ts
Without this PR, the AF non-member popup and submission will occur on every save. This fixes that.
Also hides "Suggested for Alignment" from the post options since it shows for non-admins but they need to be able to edit that field (as part of submitting). I'm unsure what the actual best fix for this is.
=> Prevent AF-Non-Member submission handling from happening upon edit

packages/lesswrong/server/authentication/auth0Accounts.ts, packages/lesswrong/server/authenticationMiddlewares.ts, packages/lesswrong/server/vulcan-lib/apollo-server/authentication.tsx
This PR works to solve recent login issues by:
- not creating a duplicate account uses oAuth with an email that's already associated with an account
- not throw an error where trying to use a password to log in with an oAuth-only account
=> Prevent creation of duplicate accounts with oAuth

packages/lesswrong/lib/betas.ts
We had an unfinished integration with CkEditor collaborative editing, enabled for admins only. Which was bad for admins who accidentally stumbled their way into it, because it wasn't ready to ship even to admins.
=> Fully disable the collaborative editor

packages/lesswrong/components/Layout.tsx, packages/lesswrong/components/posts/PostSubmit.tsx
Makes it so requesting feedback saves the draft. I wanted it that it would save without taking you out of the editor, but I haven't figured out our forms enough to do that.
=> Fix feedback button saving

packages/lesswrong/lib/alignment-forum/comments/custom_fields.ts
=> Fix "suggested for alignment user ids" showing up in AIAF edit form

packages/lesswrong/components/localGroups/CommunityHome.tsx
Bug introduced by EA Forum. Accidentally inverted boolean and at wrong level in the tree.
=> Fix Resources list

packages/lesswrong/components/recentDiscussion/RecentDiscussionSubscribeReminder.tsx, packages/lesswrong/components/users/SignupSubscribeToCurated.tsx
This PR makes some updates to the CTA in the Recent Discussion feed that reminds users to subscribe to the curated posts email (it's hidden on the Alignment Forum and uses the weekly digest email on the EA Forum). Mostly this is to make sure it appears to users who are not admins, and I also made some UI tweaks.
Original EA Forum PR: https://github.com/centre-for-effective-altruism/EAForum/pull/187
=> add a curated posts subscription reminder to the Recent Discussion feed

packages/lesswrong/server/notificationCallbacks.tsx
Thanks for keeping my useful changes when you reverted the email verified PR (https://github.com/LessWrong2/Lesswrong2/pull/4169/files). I looked into this today expecting to have to rescue those changes myself and was pleasantly surprised. From reviewing the code, it looks like there's one place where the EA Forum still needs custom behavior. This PR introduces that change.
=> [Tiny fix] Email unverified users on the forum

packages/lesswrong/lib/collections/posts/schema.ts, packages/lesswrong/lib/collections/reports/schema.ts, packages/lesswrong/server/callbacks.ts
Fixed a bug which made it so that Sunshines who are not also admins could not properly purge spam; ie, if they clicked the purge-user button on the Sunshine sidebar, the user would be banned but their posts would not be deleted correctly.
=> Fix Sunshines/moderators being unable to purge spam

packages/lesswrong/components/localGroups/CommunityHome.tsx, packages/lesswrong/server/resolvers/recentDiscussionFeed.ts
This PR removes the word "beta" from the Community page, and it excludes newly created in-person events from the Recent Discussion section. A **comment** on an event will make it appear in Recent Discussion. Online events still appear in Recent Discussion.
=> Remove "beta" from Community page, and hide newly created in-person events in Recent Discussion

packages/lesswrong/components/linkPreview/PostLinkPreview.tsx, packages/lesswrong/components/posts/PostsPreviewTooltip.tsx, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/collections/revisions/schema.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts, packages/lesswrong/server/extractHighlights.ts, packages/lesswrong/server/resolvers/revisionResolvers.ts, packages/lesswrong/server/utils/serverGraphqlUtil.ts, packages/lesswrong/testing/extractHighlights.tests.ts
This makes it so that if a link to a post includes the anchor of a section heading, the excerpt that you see when you hover over it starts at that section, rather than at the top of the post. Partially addresses https://github.com/LessWrong2/Lesswrong2/issues/4072 . Current limitations:
* Currently only section headings have anchors (the anchors are inserted by the table of contents code), so you can only point this at sections that start with a large-font header, not at arbitrary paragraphs
* You'll get a brief loading spinner while it roundtrips to the server, before seeing the excerpt
* The excerpt is clipped by length in the same way as an excerpt from the start of the post, so if the section is short enough, it'll be followed by the start of the next section
=> Hover-highlight for link to a section in a post shows excerpt starting at that section

packages/lesswrong/components/comments/CommentPermalink.tsx, packages/lesswrong/components/comments/ModerationGuidelines/ModerationGuidelinesBox.tsx, packages/lesswrong/components/linkPreview/PostLinkPreview.tsx, packages/lesswrong/components/notifications/TagRelNotificationItem.tsx, packages/lesswrong/components/posts/PostsAnalyticsPage.tsx, packages/lesswrong/components/posts/PostsPreviewTooltipSingle.tsx, packages/lesswrong/components/revisions/PostsRevisionSelect.tsx, packages/lesswrong/components/tagging/AllPostsPageTagRevisionItem.tsx, packages/lesswrong/components/tagging/FilterMode.tsx, packages/lesswrong/components/tagging/TagRevisionItemWrapper.tsx, packages/lesswrong/components/users/BannedNotice.tsx, packages/lesswrong/lib/crud/withSingle.ts, packages/lesswrong/server/emailComponents/EventInRadiusEmail.tsx, packages/lesswrong/server/resolvers/analyticsResolvers.ts
This is a PR building on top of: https://github.com/LessWrong2/Lesswrong2/pull/4208 . It fixes a bug with that PR causing an extraneous error with post analytics in certain situations. You'll want to change the base branch of this PR to `master` and merge, soonish after merging #4208 . (No rush, as it would only affect admins on LW.)
Already reviewed in: https://github.com/centre-for-effective-altruism/EAForum/pull/206 .
---
Correctly return that the document returned might be undefined when an error is set or when it's loading (fixes run-time bugs with reloading graphql data when navigating between pages).
=> Correctly type return of useSingle

packages/lesswrong/components/tagging/FilterMode.tsx
Recently FilterMode.tsx was changed to return null if tagId is missing. This makes sense except FilterMode is also used for Personal Blogpost within the FrontpageFilter Settings.
This PR changes FilterMode to use a skip statement within useSingle to fix the type and use some null checks, but otherwise lets the component render for the non-tag case.
=> Fix useSingle typing in FilterMode

packages/lesswrong/components/localGroups/CommunityHome.tsx, packages/lesswrong/components/localGroups/LocalGroupPage.tsx, packages/lesswrong/lib/collections/localgroups/views.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
A few small updates around online groups:
1. Only show up to 5 on the main Community page
2. Order them alphabetically instead of by date created
2. Fix the top margin on the Group Page on mobile
=> a bit of cleanup around online groups

packages/lesswrong/components/common/TabNavigationMenu/FeaturedResourceBanner.tsx
This PR adds analytics tracking to the sidebar banner. Following the CTA link creates an event with a pageElementContext of `featuredResourceLink`, and adds `resourceName` and `resourceUrl` props.
=> Featured resource analytics

packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx, packages/lesswrong/components/sequences/CoreReading.tsx
This sequence now exists: https://forum.effectivealtruism.org/s/isENJuPdB3fhjWYHd , so we should link to it.
Note that this won't work on dev and staging. I think we should just re-clone dev and staging soon, which would make this work.
=> Links to most important century now go to new sequence page

packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
This PR makes so that the bookmarks section in the Recommendations section on the frontpage increases from 3 slots to 6 when Continue Reading and From the Archives are closed.
=> When other sections are closed, bookmarks limit increases to 6 from 3

packages/lesswrong/server/search/utils.ts
We currently split each post into paragraphs and index each paragraph separately, to avoid algolia's maximum text size limit. We recently encountered a post with a paragraph with more than 20 kB of data though, this handles that case by just truncating the paragraph.
[This branch](https://github.com/ForumMagnum/ForumMagnum/tree/split-algolia) has a better fix for this (indexes each chunk of 20 KB separately) but Oli [convinced me](https://cea-core.slack.com/archives/CJZ7QMY5V/p1637270655100400) it's not worth us accidentally breaking some algolia feature.
=> Limit algolia text size

packages/lesswrong/lib/collections/posts/views.ts, packages/lesswrong/lib/collections/revisions/views.ts, packages/lesswrong/lib/collections/users/views.ts
Tweak some mongodb indexes to address performance issues, which I believe were causing 502s.
These have already been applied to the production DB. Note that we had issues with being over the maximum number of indexes on the posts collection; EA forum will likely run into the same issue. To fix this, you'll want to drop some indexes that are in the intersection of <1 usage/min reported in Atlas (in mongodb cloud, Browse Collections>posts>Indexes), and appearing as an "extra index" (ie exists in DB but not in code) on `servername.com/admin`.
=> Tweak indexes to address mongodb performance issues

package.json, yarn.lock
On the theory that this might resolve out-of-memory failures happening in GitHub Actions unit tests, and certainly can't hurt.
=> Upgrade Jest to the latest version

packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
We already displayed post reading time, but only on mobile. Aaron asked me to display it on desktop as well.
=> display post reading time on desktop

packages/lesswrong/components/form-components/FormComponentDateTime.tsx
This is to reduce the confusion around event timezones. Here I'm assuming that all datetimes submitted with this component use the browser's timezone and get converted to UTC before being saved to the db, since this happens for event start/end times.
=> display browser timezone in datetime input label

Dockerfile
EA Forum production deploys intermittently time out during the docker build step. Speed up docker to address the issue.
The timeout of the build as a whole can be adjusted with a configuration variable, however the timeout of the docker build step seems to be pinned at 5 minutes. Our builds seem to take around 5:20. I have a support ticket open with AWS about this.
Most of the time is spent right after the yarn install step. It's after the yarn command returns and before the next command starts. All evidence points to the slow piece being saving the layer diff. When we use the fancy new [buildkit](https://docs.docker.com/develop/develop-images/build_enhancements/), docker build saves layer diffs at the end, and sure enough we observe the extra time moving to the end.
With the guess that …
=> Speed up docker to fix build issue

packages/lesswrong/components/Layout.tsx
Ran into a bug updating my timezone where we tried to read `_id` of null. This was my second time noticing that Layout mis-typed currentUser, so I fixed it.
=> currentUser should be an optional parameter in Layout

packages/lesswrong/components/comments/CommentsListSection.tsx, packages/lesswrong/components/posts/PostsNewForm.tsx, packages/lesswrong/lib/collections/posts/custom_fields.ts, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/collections/posts/schema.ts, packages/lesswrong/lib/generated/databaseTypes.d.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
This PR adds the `globalEvent` flag to the posts collection. This is based on feedback that it's confusing to see online events hosted by local groups advertised to everyone on the forum, when many of them likely don't intend for people outside of their local area to attend.
I added the `globalEvent` field, which defaults to checked when creating a new event within an online group, but otherwise defaults to unchecked.
Although the tooltip says we only advertise online events locally, that's not yet the case - I plan to make that change in an upcoming PR.
I also made a couple other related improvements, including defaulting the "Enable RSVPs for this event" checkbox to `true`, adding a tooltip for it, and displaying this note when a user adds a comment to an event with RSVPs:
=> add global event field for posts

packages/lesswrong/components/review/ReviewVotingExpandedPost.tsx, packages/lesswrong/components/review/ReviewVotingPage.tsx
Makes it so the left column on the ReviewVotingPage is static, so if you've scrolled down a bunch on the giant post-list you can still see the post data
=> sticky leftColumn on ReviewVotingPage

packages/lesswrong/components/review/ReviewVoteTableRow.tsx
gets rid of this functionality, which was kinda annoying to use and has now been replaced by the left-column:
=> Remove old post expand button on ReviewVotingPage

packages/lesswrong/components/posts/AllPostsPage.tsx, packages/lesswrong/components/posts/PostsListSettings.tsx, packages/lesswrong/components/users/UsersProfile.tsx, packages/lesswrong/lib/collections/posts/views.ts, packages/lesswrong/lib/collections/users/custom_fields.ts, packages/lesswrong/lib/collections/users/fragments.ts, packages/lesswrong/lib/generated/databaseTypes.d.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
In this PR, I'm excluding events from the list on the "All Posts" page by default, and adding a checkbox in case people want to include them.
I also added the "Events" filter to the EA Forum (which already existed on LW) and fixed a bug with that filter.
=> enable filtering out events from "All Posts" page

packages/lesswrong/components/posts/AllPostsPage.tsx, packages/lesswrong/lib/collections/posts/views.ts
I noticed that events had stopped appearing in the Recent Discussion feed, and realized that my recent PR https://github.com/ForumMagnum/ForumMagnum/pull/4323 updated the default posts view such that events were excluded by default. So I flipped the logic in the view.
=> fix a bug that hid events by default everywhere

packages/lesswrong/components/review/FrontpageReviewWidget.tsx
Fix some errors in the browser console on the front page, if DB settings for the review aren't set (eg on the development database).
=> Don't have console errors on front page if DB config settings for review aren't set

packages/lesswrong/components/posts/PingbacksList.tsx
Setting this from false to true. I'm not sure if there are any chesteron-fence ramifications I'm missing.
=> enableTotal on PingbacksList

packages/lesswrong/components/review/ReviewVotingPage.tsx
If I'm not going to fix ReviewVotingPage to be able to load more today*, we should make sure we aren't cutting off posts. Increase the limit to 600. By my estimation, this'll make the loading of the page go from 3.5 to 5.6 seconds. Not great, but probably better than randomly missing posts.
\* I'm not.
=> Temporarily increase ReviewVotingPage post limit

packages/lesswrong/components/review/ReviewVotingPage.tsx
Previously: https://github.com/ForumMagnum/ForumMagnum/pull/4345
After implementing the fix, the repeatable bug went away. Apparently that was just random chance, the function was in fact still vulnerable to null input. Shoulda listened to Sam. I have a [draft PR](https://github.com/ForumMagnum/ForumMagnum/pull/4336) open to rip out the offending function, but the function was still live and I should have fixed it.
=> Better Nullsafe Fix

.github/workflows/unitTests.yaml, packages/lesswrong/testing/testMain.ts
The out-of-memory errors in unit tests were caused by two separate issues each of which leaked lots of memory, adding up to just barely reach the threshold of where things would fail (by increasing slightly every time we added more tests, until it started breaking so we noticed it). The first is https://github.com/facebook/jest/issues/10550, which leaks about 50MB per test file (about 1GB total). The second was a double-initialization of `jest-mongodb` which leaks a subprocess and some metadata with each test file (about 200MB total).
There is no proper fix for the Jest module caching leak, but downgrading from nodejs 15+ to nodejs 14 is an effective mitigation which reduces the size of the leak by an order of magnitude. So I've changed the nodejs version in …
=> Fix unit test memory leak

packages/lesswrong/server/recommendations.ts
I think this might have gotten obviated by a recent CEA PR (which filtered out events at a higher level), but I'm not sure. I recently have seen events show up in the Review Recommendations and wanted that to not happen anymore.
=> Remove events from review recommendations

jest.config.ts, package.json, yarn.lock
I replaced ts-jest and babel-jest with esbuild-jest in Jest's config. esbuild is much faster, though it doesn't do type-checking. Presumably we all have IDEs that do type-checking, so this should be fine?
Before this change, runs of `yarn test` took 239.82, 73.83, 85.51, 94.756, and 73.379 seconds on my 2018 MacBook. (I'm surprised and confused by the variance.)
After the change, runs of `yarn test` took 30.269, 30.505, 29.87, 29.572, and 30.368 seconds.
=> Use esbuild-jest to compile faster for tests

packages/lesswrong/components/review/FrontpageReviewWidget.tsx, packages/lesswrong/components/review/LatestReview.tsx, packages/lesswrong/components/review/ReviewVotingPage.tsx
This makes the Voting on Nominations button available on mobile, and streamlines various bits of text on mobile to make it fit better.
Makes the Big Review Header link to the /reviewVoting page instead of the post, because that's what I kept intuitively expecting and wanting.
Adds the FrontpageReviewWidget back to the mobile view, since it felt a bit weird without it. I may experiment further with the optimal header.
=> Mobile review buttons

packages/lesswrong/lib/collections/posts/custom_fields.ts, packages/lesswrong/lib/collections/posts/schema.ts, packages/lesswrong/lib/collections/sequences/schema.ts, packages/lesswrong/server/bookmarkMutation.ts, packages/lesswrong/server/resolvers/tagResolvers.ts, packages/lesswrong/server/rsvpToEvent.ts
I went through all our resolvers looking for missing `accessFilterSingle`/`accessFilterMutiple` usage, since omitting that would mean field-level access permissions aren't enforced. Most of these are minor (collections that don't actually have much in the way of field-level permissions *to* enforce), but one is more significant (could leak a user's email address).
=> Fix missing access-filtering in some resolvers

packages/lesswrong/components/review/FrontpageReviewWidget.tsx, packages/lesswrong/components/review/ReviewVotingPage.tsx, packages/lesswrong/lib/collections/posts/views.ts, packages/lesswrong/server/recommendations.ts
* Hide review CTA button on non-frontpage uses of the FrontpageReviewWidget 
* Update EA Forum text for this phase
* Hide quadratic voting for yet another phase
* Increase threshold for appearing on ReviewVotingPage to 2 positive votes
* Make frontpage recommendation section work for review phase
=> Fixes for Review Phase of the 2020/Decade Review

packages/lesswrong/server/notificationCallbacks.tsx
I had previously tried to prevent users from getting nominated multiple times about the same nomination, but I accidentally was filtering on "nominationType" instead of "type" (which is the actual correct field)
This is fixing a live bug that's pretty bad and so will be merging now and getting a review after-the-fact
=> fix post nomination notification bug

packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx, packages/lesswrong/components/review/PostsItemReviewVote.tsx, packages/lesswrong/components/review/ReviewVoteTableRow.tsx, packages/lesswrong/components/review/ReviewVotingPage.tsx, packages/lesswrong/lib/reviewUtils.ts
Covers a bunch of cases when Review and Voting buttons should be shown/hid. Also tweaks the UI styling of the PostsItemReviewVoting component.
New styling:
3 cases where users are eligible to vote (where they have voted, not voted, and can't vote on a post)
Makes it so all users can now look at the /reviewVoting page (because it's how you track reviews), and instead non-vote-eligible-users just don't have the voting UI:
During the Review Phase, voting buttons only appear on post-items for posts that got at least one positive vote.
compared to during Nominations phase, where all Paul's 2020 posts are voteable:
During Nominations phase, PostsPages show voting buttons and review buttons for all 2020 posts:
During Review phase, they only show those buttons if the post has at least one upvote: …
=> Properly Show/Hide Review Voting Buttons

packages/lesswrong/components/posts/PostsItem2.tsx, packages/lesswrong/components/posts/PostsPage/PostBodyPrefix.tsx, packages/lesswrong/server/recommendations.ts
This PR makes PostItems have a Review button instead of a Vote button during the Review Phase
I've tested that 
– the Review button works
– if you switch to the NOMINATIONS phase the vote button returns.
– on the UsersProfile page, if I scroll down till I see the 2020 posts, posts that have a nomination show the Review button, and posts without a nomination do not.
=> Review button on PostsItem

packages/lesswrong/components/review/PostsItemReviewVote.tsx
I was finding it difficult to scan the /reviewVoting page for posts that were low-ranked, but which I had strong upvoted. This seemed like an important way to check for posts worth writing review for.
This PR adds colors to help your votes be more skimmable.
=> Colored vote buttons

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx, packages/lesswrong/components/review/ReviewVoteTableRow.tsx, packages/lesswrong/components/review/ReviewVotingButtons.tsx, packages/lesswrong/components/review/ReviewVotingWidget.tsx, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
When I recently added the ReviewVotingButtons to the bottom of CommentsItem, I forgot to exclude it from old review comments on previous years.
This PR makes it so that it only appears on comments reviewing the current REVIEW_YEAR, and only while the review is active.
I have tested
– That an old post's reviews does NOT show voting-buttons (while getReviewPhase returns a string)
– That a current-review-year comments DOES show voting-buttons (while getReviewPhase returns a string)
– That a current-review-year-comment does NOT show voting buttons (While getReviewPhase returns undefined)
=> Review voting no longer displays on old review CommentItems

packages/lesswrong/server/notificationCallbacks.tsx
Caused by doing a shallow comparison on `mongoLocation` which needs to be a deep comparison. Introduced in: 0458d3930eee3f141d9c02402b3fc40040fd61ba (which fixed one problem in a line which had two problems in it).
=> Fix spurious event-location-changed notification happening with every RSVP

packages/lesswrong/server/migrations/2021-12-13-updateQuadraticVotes.ts
Fixes breaking bug with `updateQuadraticVotes` migration.
---
Let's talk about how forEach works. It has a bunch of values in an array. You pass it a callback. It takes the first element of the array and passes it to your callback. Then it moves on to the next one, and so on, until it has finished calling your functions with each of its elements.
Now, let's think carefully about what happens when your function is async. When async functions are called, they return a promise at the first await. So the question becomes, will forEach function await the promise? At this point we can google it, however I leave it as an exercise to the reader to see how the code could not have worked as written.
The answer is: no forEach does not await the promise. So all of the functions will be called …
=> Replace foreach with for loops to fix async issue

packages/lesswrong/lib/collections/revisions/collection.ts, packages/lesswrong/lib/notificationTypes.tsx
I've gotten reports from multiple users who have received a blank email regarding a new event posted on the forum (and I've received those emails too).
JP and I discovered that this happens when we are trying to render the email. When we query for the event/post data, if `Revisions.checkAccess()` is called on a revision with the event/post's `documentId` but the revision has no `collectionName`, that causes an error that prevents the email body from rendering properly.
In our production database, we have 161,750 revisions and 84,318 of them have no `collectionName`. Not sure why there are revisions with no `collectionName`?
=> stop sending blank emails for new events

packages/lesswrong/components/comments/CommentsNode.tsx, packages/lesswrong/components/comments/SingleLineComment.tsx, packages/lesswrong/components/comments/commentTree.ts, packages/lesswrong/components/review/FrontpageReviewWidget.tsx, packages/lesswrong/components/review/SingleLineReviewsList.tsx, packages/lesswrong/lib/components.ts
This replaces the FrontpageReviewWidget's post-list with a reviews list after the nominations phase has ended, to help encourage engagement with reviews.
Things I tested:
– if I set reviewPhase to "NOMINATIONS", I still get the nominations-phase post list
– if I set reviewPhase to "REVIEWS" I get the list of singleline comments
– for the single-line-comments in the FrontpageReviewWidget, where singleLineLargePreview is true, you can click on the hoverpreview to expand the preview (without expanding the original single line comment)
– for other single-line-comments in the RecentDiscussionSection, clicking them expands the original single-line-comment
(I changed how clicking works because it seemed like I wanted different behavior on the FrontpageReviewWidget – in that case a core feature …
=> Reviews on frontpage

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx, packages/lesswrong/components/comments/CommentsNode.tsx, packages/lesswrong/components/comments/SingleLineComment.tsx, packages/lesswrong/components/comments/commentTree.ts, packages/lesswrong/components/review/SingleLineReviewsList.tsx
I'm not thrilled with my current implementation of this, but, this makes it so that you can click to expand the single-line-comments on the frontpage. 
Previously I had delibarely not enabled this because it resulted in a large, permanently expanded single-line-comment at the top of the home page, which seemed undesireable. But a) I found it annoying that I couldn't expand the singleLineComments the way I was used to, and, b) on mobile the hoverover option didn't even work so the component was basically broken.
This makes it so you can expand then, and then also collapse them. My shoulder Oli is warning me about spaghetti code of special-cases for comments though, and thinks maybe we want to reflect on that.
=> Collapsible Frontpage SingleLineComments

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx, packages/lesswrong/components/review/ReviewVotingButtons.tsx, packages/lesswrong/components/review/ReviewVotingWidget.tsx
I hadn't properly hidden the votes of non-eligible users on CommentItems. This PR fixes those permissions in multiple places (because I expect to use different components in different combinations and it seemed better to err on the side of thoroughness)
=> Hide voting for non-eligible people more reliably

packages/lesswrong/components/linkPreview/PostLinkPreview.tsx
Sometimes, a link-preview takes awhile to load, and then it doesn't initially display anything. This looks confusing. This PR makes it so it always displays the innerHTML even if the fancy hovers haven't loaded yet.
=> display default innerHTML for link previews

packages/lesswrong/components/posts/PostsEditForm.tsx
Sets the title of your browser window to be the post-title, while editing a post.
(I'm not 100% sure how HeaderTags works under the hood but seemed to be the right component to do the job)
=> post editor sets post title in browser

packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
It's a little bad that the title in the sidebar is so long, sticking slightly awkwardly out underneath HPMOR. If anyone has suggestions for a shorter name, lemme know.
I think it might be reasonable to cut out the "Open Questions" menu item to preserve complexity, although it does still get ~600 (900?) clicks a month)
=> Makes a link to the Best of LessWrong collection

packages/lesswrong/components/common/TabNavigationMenu/menuTabs.tsx
Implements the name change Ruby had meant to imply in the previous PR
=> "Best of" title

packages/lesswrong/components/review/FrontpageReviewWidget.tsx, packages/lesswrong/lib/collections/posts/views.ts
In retrospect, this is probably better than showing reviews themselves – show nominated posts sorted by "lastCommentedAt", which a) lets you see when a new review is posted, b) lets you catch up on other discussion. I was surprised I had missed some previous discussion because I'd just been looking at reviews. 
Somewhat controversially also adds a loadMore. To make it work I had to resort to a less elegant CTA Button.
It's possible I should make the latest review use the "top comment" UI, a la:
(but I have not currently done so)
Curious if JP thinks any of this is actually an improvement
=> FrontpageReviewWidget shows posts, sorted by lastCommentedAt

packages/lesswrong/components/linkPreview/HoverPreviewLink.tsx
Footnote hover previews on mobile run offscreen. Removing these for now.
=> Add isMobile check to footnote hover preview

packages/lesswrong/lib/collections/users/custom_fields.ts
We'll never need the 2018 hide book option again, so removing it from the UserEdit form
=> remove old "hide book" from UsersEdit

.github/workflows/cypress.yaml, .github/workflows/deployBaserates.yaml, .github/workflows/deployEADev.yaml, .github/workflows/deployEAProd.yaml, .github/workflows/deployLWAFProd.yaml, .github/workflows/deployLWDevel.yaml, README.md
One hypothesis for what is going wrong with cypress tests is that they are running at the same time and doing conflicting operations in the database. We can force the workflows to run one after another to prevent this.
When making that change we can realize that we should obviously do the same thing with deploys which currently just fail if they run concurrently. Which leads to inconsistencies between the code on master and what's running on staging, for example.
=> Queue jobs that should not be run concurrently

packages/lesswrong/components/tagging/TagPageButtonRow.tsx
React has a gotcha when using && syntax.
- `{false && <Foo/>}` returns false, which doesn't get rendered
- `{null && <Foo/>}` returns null, which doesn't get rendered
- `{undefined && <Foo/>}` returns undefined, which doesn't get rendered
- `{'' && <Foo/>}` returns '', which doesn't get rendered
But!
- `{0 && <Foo/>}` returns 0, which **does** get rendered
RIP
JP making final changes to a PR and not testing carefully enough.
=> Cast number to boolean when conditioning on it in react

packages/lesswrong/lib/reviewUtils.ts
This PR makes it so that once we're in Final Voting phase, users can no longer vote or review posts that don't have at least one review.
=> hide unreviewed-post-Review UI during voting phase

packages/lesswrong/lib/publicSettings.ts
I had previously edited the public database to have the correct end-times, but a) it's not consistently working, and b) it still seems good for the codebase to have the correct version.
=> update review database end times

packages/lesswrong/components/editor/EditorFormComponent.tsx
Currently, the conversion between markdown and CkEditor is not perfect. This is especially frustrating for wiki posts, which can be edited by multiple people. This PR enforces using CkEditor when changing any tag.
See [this slack thread](https://cea-core.slack.com/archives/C01Q279LKCK/p1642026060001500) for more discussion.
Code written with @s-cheng
=> Tags can only be edited using CKEditor

packages/lesswrong/components/posts/PostsPage/PostsPageEventData.tsx, packages/lesswrong/server/emailComponents/EventUpdatedEmail.tsx, packages/lesswrong/server/emailComponents/NewPostEmail.tsx, packages/lesswrong/server/notificationCallbacks.tsx
I realized I forgot one of the CSS props for displaying the join event link in a single line with ellipsis. Also updated the join event link in emails to be an actual link.
=> fix event join link wrapping, add link in event email

packages/lesswrong/components/messaging/ConversationPreview.tsx
#4475 introduced a bug where PM previews could take up the full width of the page. This css works in both the notification sidebar, and the inbox page.
=> Fix the width of private messages previews

packages/lesswrong/lib/publicSettings.ts, packages/lesswrong/lib/reviewUtils.ts
Aligns us with the UI and things I've written.
I've tested this locally. We only use the getReviewPhase function when choosing behavior, which is fortunate. The other uses of these dates are for display, and reflect the intended behavior.
=> Include phase ending dates in review phase

packages/lesswrong/components/review/ReviewVotingPage.tsx, packages/lesswrong/lib/collections/posts/views.ts
Previously we had needsReview as the main sorting option for the review phase. This creates the default sorting option for the voting phase, which is "posts I haven't voted on, followed by posts I have voted on sorted by vote-weight".
=> needsFinalVote sort option

packages/lesswrong/components/review/ReviewVoteTableRow.tsx
In the Review Phase, the "you can't vote on your own posts" text had changed to a greyed out "Vote" button, which you couldn't search for with Cmd-F. This makes it more searchable, so you can find your own posts.
=> Change text to "can't vote"

packages/lesswrong/components/review/ReviewVotingPage.tsx
This makes it so "needsReview" sorting prioritizes your own posts if they don't have reviews (people can't vote on their own posts, so they don't otherwise get promoted to a user's attention as needing review)
Basically too late to matter but figured I might as well merge it with a few hours remaining.
=> sort your posts to top of needsReview

packages/lesswrong/components/review/ReviewPostComments.tsx
The comments on /reviewVoting take a while to load. We might like to show our standard `<Loading/>` component, but that would involve seeing 10 on your screen at once, which would be too much. So instead we were showing an empty box. According to me, that was insufficient evidence of loading. So I added a non-moving indication of loading:
Also looks fine on LW.
=> Minimal loading indication for review post comments

packages/lesswrong/components/review/ReviewVotingPage.tsx
Previously: https://github.com/ForumMagnum/ForumMagnum/pull/4498
After discussion with @Raemon, I'm somewhat convinced that we should include it, but I think we'd need to figure out how many users have gone over-budget, and make it somewhat less broken. For now, our Forums can diverge in this one UI element.
=> Hide budget from top bar on the EA Forum

packages/lesswrong/components/review/ReviewVotingPage.tsx
We know what causes the Review Sorting Bug – somehow postsResults doesn't load, or gets lost. Why? Who knows. But meanwhile we can let people know to refresh.
(This bug also now causes the vote total to fail to display, since it has no posts to build itself out of)
=> The Hackiest Fix for the Sorting Bug [gives a warning label when postsResults fails to load]

packages/lesswrong/components/tagging/TagPageButtonRow.tsx
Mirrors the behavior of the edit button. As discussed with @darkruby501, we're fixing this obvious bug, but not returning to the previous behavior of a modal as well.
=> [LW-only] Make the Tag Edit CTA text a clickable button

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx, packages/lesswrong/components/common/LWHelpIcon.tsx, packages/lesswrong/components/review/FrontpageReviewWidget.tsx, packages/lesswrong/components/review/ReviewAdminDashboard.tsx, packages/lesswrong/lib/components.ts
I found myself wanting to know which people were voting the most and what the distribution was like, more than I wanted to know what the top-karma users were doing. Also, you could already get the top-karma users from the second half of the users-votes-list (which includes all users with 1000+ karma, sorted by karma)
So, this PR changes the initial sorting of the users-section to be based on vote-count, rather than karma. Does some minor styling changes. (I think it looks kinda ugly but this page isn't very important so not prioritizing it)
=> change sort on review admin page

packages/lesswrong/components/review/ReviewVotingExpandedPost.tsx, packages/lesswrong/components/review/ReviewVotingPage.tsx, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
The "sorting failure" bug and the "post contents stop appearing in the 'expanded post view' bug both seem to be due to some fragment mismatches, where loading a single post (via the PostsTitle hoverover) with the HighlightWithHash classes with the existing PostsListWithVotes fragment.
This PR makes some changes that fixes the bugs.
See this slack convo:
https://lworg.slack.com/archives/C01GXLMPU2C/p1642389171115800
=> Fix postsResults dropping bug on ReviewVotingPage

packages/lesswrong/components/recentDiscussion/RecentDiscussionFeed.tsx, packages/lesswrong/components/recentDiscussion/RecentDiscussionTagRevisionItem.tsx, packages/lesswrong/components/tagging/TagEditsTimeBlock.tsx, packages/lesswrong/lib/components.ts
Pablo and his assistant Leo have been on a tear of wiki edits recently. It's overwhelming the frontpage with housekeeping tag updates, which aren't helpful for ~anyone to read. I decided I wanted to cut them two off specifically, letting Pablo's edits through if they're more than 600 characters.
I happened to get complaints about it today in a user interview, so that'll be nice.
I also clean up the allPosts page. It currently doesn't limit the number of wiki edits that show up, and if there are 20 in a day it's a bad experience.
=> Tag rampage sanity

packages/lesswrong/components/linkPreview/PostLinkPreview.tsx
Link anchors with special characters could crash footnote preview, breaking some links in posts such as http://localhost:3000/posts/ttjebJSR7HsLDbqky . Also there was an XSS in the transform that removed the footnote backlink.
=> Fix a crash and XSS in FootnotePreview

packages/lesswrong/lib/collections/posts/custom_fields.ts
Just noticed that the event image upload appears on the new post form on production - this is to hide it.
=> hide the event image field on the new post form

packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx, packages/lesswrong/components/comments/commentTree.ts, packages/lesswrong/components/review/ReviewPostComments.tsx, packages/lesswrong/components/review/ReviewVoteTableRow.tsx
Two quick UI nice-to-haves:
– the single line comments are now collapsible after expanding them (useful for giant ones you might not have realized were so giant)
– removed the voting UI because it was redundant/confusing in this context.
=> ReviewVoteTableRow singleLineComment UI improvements

packages/lesswrong/lib/betas.ts, packages/lesswrong/lib/collections/users/helpers.ts
Currently users who are shared on drafts can get into a broken collaborative ckeditor state.
Quoting myself from slack:
> One might expect that userHasCkeditor is used for enabling the editor itself, while userHasCkCollaboration  (currently set to disabled) is used to enable collaboration. Upon checking, it looks like one would be wrong.
This fixes that.
=> Fix bug that allowed broken collaborative editor to be shown

packages/lesswrong/lib/reviewUtils.ts
I had disabled the ability to review posts without at least 1 review during the Voting Phase. The idea was that voters wouldn't have to scan for new posts, and reviewers would have a stronger deadline.
But in practice... I think it's just been kinda annoying not to be able to review some other posts I hadn't had time for, or which I hadn't finished thinking about. So I think I'd like to revert this change.
Interested in @jpaddison3 and @darkruby501's thoughts.
=> Make all posts reviewable again

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx, packages/lesswrong/components/posts/PostsTitle.tsx, packages/lesswrong/server/notificationCallbacks.tsx
This PR fixes a couple small issues:
1. Spacing between comment and event image for event comment permalink
2. Sending too many "event updated" emails
I saw this on production today:
Here is the updated spacing:
=> two small event-related fixes

packages/lesswrong/components/posts/PostsPage/PostsPageTitle.tsx
This simply makes it so that a post-page title is a link to the canonical post page. This may seem a bit silly, but I've wanted it for two reasons:
1) I'm often on a weird version of a post (such as a link to a specific comment on the post, or a sequence version of a post, etc). And I want to quickly get to the simple, original version of the post to grab the url and link to it (or something like that). And it's oddly annoying.
2) I wanted to re-use the PostsPagePostHeader on the reviewVoting page (in ReviewVotingExpandedPost), so I could get all the convenient metadata and have a convenient link to the post as well. This isn't the first time I wanted to use it in a different context.
I think #1 is worthwhile even if we didn't care about #2.
=> PostsPage title link

packages/lesswrong/components/common/TemplateComponent.tsx, packages/lesswrong/components/payments/AdminPaymentsPage.tsx, packages/lesswrong/lib/collections/users/views.ts, packages/lesswrong/lib/components.ts, packages/lesswrong/lib/generated/viewTypes.ts, packages/lesswrong/lib/routes.ts
This creates a simple page for admins to view users who have a paymentEmail or paymentInfo, to make that easier to track.
It also adds a TemplateComponent which can be copied to get a minimal bare-bones component setup.
=> Payment Admin Page + TemplateComponent

packages/lesswrong/components/comments/CommentsListSection.tsx, packages/lesswrong/components/posts/PostsCommentsThread.tsx, packages/lesswrong/components/questions/AnswerCommentsList.tsx
Remove the lastEvent prop on CommentsListSection, which was untyped (type any) and was never doing anything because a Date was being passed but the function was trying to use it as an LWEvent. Then split the "Highlighting new comments since [date]" message/widget into three branches: Either
* Highlighting [n] new comments since [date]
* New new comments since [date]
or
* Click to highlight new comments since: [now]
=> Add count to "Highlighting [n] new comments since [date]" on post page

packages/lesswrong/components/users/WrappedLoginForm.tsx
Fix the word wrapping issue shown in this screenshot. This is specific to something about the afffected users's system fonts/dpi settings/something, and I can't reproduce it directly, but tested the fix by tweaking the font size.
=> Fix login form word wrapping

packages/lesswrong/components/review/PostsItemReviewVote.tsx, packages/lesswrong/components/review/ReviewVoteTableRow.tsx, packages/lesswrong/components/review/ReviewVotingButtons.tsx, packages/lesswrong/components/review/ReviewVotingPage.tsx, packages/lesswrong/components/review/ReviewVotingPage2019.tsx, packages/lesswrong/components/review/ReviewVotingWidget.tsx, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/collections/posts/schema.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts, packages/lesswrong/lib/reviewUtils.tsx, packages/lesswrong/server/resolvers/reviewVoteResolvers.ts
This PR makes it so that
a) when you click on a vote button on the /reviewVoting page, it updates the vote-cost-total
b) when your vote-cost-total is over 500, your vote-weights are reduced.
It does not yet make it so that the vote-weights are visibly reduced in other parts of the site. 
It currently accomplishes A) via changing currentUserReviewVote into an object that includes the _id of the reviewVote, so that updating the reviewVote updates the the datastructure. But, it seems kinda sluggish and inconsistent and I'm not sure this is actually better than the previous solution of "you just have to refresh the page."
It accomplishes b) via passing down the costTotal of the votes and using that to do math to the point-values. 
**Some underlying philosophy:** Initially, I was going to …
=> Voting Weight

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
We try to prevent very short descriptions by concatenating multiple paragraphs. But we don't want to make a really long description either, so we only want to concatenate if the resulting concatenation is <150 characters.
The bug: Previously if the first paragraph was <40 characters, and the next paragraph was > 110 characters, we would search through all the paragraphs in the plaintextDescription for another paragraph that was <110 characters, and then concatenate it with the first.
=> Fix bug in post description, add more ellipsis

packages/lesswrong/components/review/ReviewVotingPage.tsx
While fix a bunch of other bugs and weird UI experiences, Oli and I introduced this bug where the posts on /reviewVoting don't load if you navigate there from the frontpage. 
We had removed the postsResults argument from the useEffect hook that sorts the page, to avoid resorting every time we changed a vote. We were testing on a normal page load, where postsResults is available the first time the resort function is called. 
To get the best of both worlds I moved the "canInitialResort" variable further up the file so it can be used to detect when postsResults has first loaded.
=> Fix PostsResults loading bug on /reviewVoting page

packages/lesswrong/components/review/ReviewVoteTableRow.tsx, packages/lesswrong/components/review/ReviewVotingPage.tsx
Previously, logged out users simply hadn't seen any posts on the /reviewVoting page. This was originally to prevent them from voting (and we showed them a giant "you can't use this page" warning). But, we've since been optimizing it more so other people can follow along, and this makes a couple stylistic tweaks to improve that experience. Now they see this, instead of a blank posts-list:
=> Improve logged out review experience

packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
I think this fixes the error seen here: https://www.lesswrong.com/posts/8rYxw9xZfwy86jkpG/on-the-importance-of-less-wrong-or-another-single
=> fix postDescription bug

packages/lesswrong/components/posts/PostsEditForm.tsx, packages/lesswrong/components/posts/PostsNewForm.tsx, packages/lesswrong/lib/collections/posts/custom_fields.ts, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/generated/databaseTypes.d.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts, packages/lesswrong/lib/instanceSettings.ts, packages/lesswrong/server/debouncer.ts, packages/lesswrong/server/eventReminders.tsx
This PR makes it so that if a document has been edited in collaborative mode, it can only be edited on LessestWrong/test server. This lets us start testing with some users and have them use LessestWrong without the issues if they tried to also edit on LessWrong.
=> Docs with Collaborative Editing enabled are only editable on test server (LessestWrong)

packages/lesswrong/lib/reviewUtils.tsx
This makes it so review-UI doesn't appear on the Alignment Forum. (Someday we might want to integrate the review into AF, but we haven't put any optimization into it and I think it's more confusing than helpful)
=> Only LW and EAforum have review

packages/lesswrong/server/notificationCallbacks.tsx
Gordon recently experienced some random notifications for his posts being nominated, and then more recently so did I. It's possible this was simply because I introduced the reviewVote notification after his/my posts had already gotten some upvotes, and then we never got upvoted again until just recently. But I don't have time to think about it right now, so am turning it off for now.
=> Turn off ReviewVote notification

packages/lesswrong/components/review/ReviewVotingPage.tsx
I had accidentally reversed the required sort-mechanism for "Sort By Your Vote". This fixes that. Also changes the name of the sort because it's no longer directly matching a field name
=> Fix Sort By Your Vote

packages/lesswrong/components/review/FrontpageReviewWidget.tsx
I've personally felt annoyed *as the person nominally in charge of everything* that it was very hard to tell exactly how much time was remaining. This adds an element that lets you know when there's less than 24 hours left, exactly how much time is remaining.
I'm not 100% sure on styling, the current option is here:
And I could imagining something like this being good instead:
=> Add voting countdown

packages/lesswrong/components/review/FrontpageReviewWidget.tsx, packages/lesswrong/components/review/ReviewVotingButtons.tsx, packages/lesswrong/lib/reviewUtils.ts, packages/lesswrong/lib/reviewUtils.tsx
This replaces https://github.com/ForumMagnum/ForumMagnum/pull/4510.
This PR makes it so voting buttons stop working after the Review ends, and makes it so the review ends (more intuitively, for me), at exact time of the voteEndDate, rather than a day later.
=> End the review for LessWrong

packages/lesswrong/components/review/ReviewAdminDashboard.tsx, packages/lesswrong/lib/routes.ts
This makes three changes
– The first list of users is sorted by "number of votes" instead of karma, so that we can more quickly scan for "how many users are actually voting a lot?"
– There's a "count" for the users, also to make it easy to count how many users cast 1 vote, 2 votes, 10 votes, etc,
– Instead of relying on REVIEW_YEAR for grabbing the votes, it takes in a url parameter so that we can compare vote metrics from multiple years.
– increase limit on votes to 10000 so that we don't miss any. I just realized I'd been looking at artificially low voting metrics because we were only looking at the most recent 2000 votes. 
(I'm not including a screenshot since the data is private)
=> Updates to ReviewAdminDashboard

cypress/integration/comments/create_comment.spec.js, cypress/integration/comments/edit_comment.spec.js, cypress/integration/messages/create_message.spec.js, cypress/integration/moderation/ban_user.spec.js, cypress/integration/moderation/move_post_to_draft.spec.js, cypress/integration/posts/edit_post.spec.js, cypress/integration/set_username.spec.js
The Cypress `should('be.visible')` assertion checks whether an element is visible on the page, not just whether it exists in the DOM. `set_username.spec.js` was failing from a change that affected page scroll behavior, which I suspect isn't something we want to flag as a test failure. This PR fixes the issue by swapping out all `be.visible` assertions for `exists` assertions.
=> Replace 'be.visible' with 'exists'

packages/lesswrong/components/posts/PostsPage/PostsPageEventData.tsx
Forgot to check events without a type before merging into `master`, though luckily I caught it on staging.
=> fix event type bug

packages/lesswrong/components/posts/PostsSingleSlugRedirect.tsx, packages/lesswrong/lib/components.ts, packages/lesswrong/lib/routes.ts
This makes a generic /posts/slug/:slug route, so that occasionally when we need to link to a post by slug there's a cleaner way to do it. (Previously this only worked for /hpmor/:slug, /codex/:slug and /rationality/:slug, which were all oddly specific sequences)
=> posts.slug.single route

packages/lesswrong/components/sequences/SequencesPage.tsx, packages/lesswrong/themes/createThemeDefaults.ts
The previous PR introduced at least one zIndex bug (by setting a number of zIndexes explicitly, where the ordering had previously done implicitly)
=> Fix zIndex for Sequence Pages

packages/lesswrong/components/sequenceEditor/EditSequenceTitle.tsx, packages/lesswrong/themes/createThemeDefaults.ts
This was another casualty of the recent zIndexes changes (you couldn't click into the editSequenceTitle input). Streamlining some more zIndexes fixes the issue.
=> Fix EditSequenceTitle bug 

packages/lesswrong/components/events/EventsHome.tsx, packages/lesswrong/lib/collections/posts/custom_fields.ts, packages/lesswrong/lib/collections/posts/views.ts, packages/lesswrong/themes/eaTheme.ts
In this PR, I'm adding a filter on the Events page for the `eventType` field. I refer to it as "event format" because I think "event type" is too vague, but I'm not totally sold on "event format" being the right term for this either. [Eventbrite](https://www.eventbrite.com/d/ma--boston/all-events/) uses the term "format" for a similar filter.
The "format" filter allows you to select multiple values. I also took this opportunity to use this orange again, to represent the selected values (the grayer orange is the hover state).
On mobile, I decided to just hide the "format" filter.
=> add event type filter to Events page

packages/lesswrong/components/posts/PostsEditForm.tsx, packages/lesswrong/components/spuriousChange.ts
Makes it so the save as draft button still says save as draft for non-collab documents
=> Save as Draft button adapts to collab/non-collab

packages/lesswrong/components/review/FrontpageBestOfLWWidget.tsx
This puts the "prizes for 2020 Review" as a sticky in the FrontpageBestOfLWWidget. I chose to leave the "Voting results" post as well because I figured people's eyes would just glaze over the prizes post if it were in the exact same place, without any other changes in the widget. (i.e. hoping that showing both of them together makes it more clear there is a new post)
=> Prizes review update

packages/lesswrong/lib/routes.ts
The new /events page is designed with a bunch of EA Forum aesthetic choices that don't feel right to me on LessWrong – we haven't had time to reflect on it, for now seemed better to turn it off.
Currently live on production, the page looks like this:
=> move /events page to EA Forum only route

packages/lesswrong/components/vulcan-forms/FormGroup.tsx, packages/lesswrong/lib/collections/posts/custom_fields.ts
The Collab Editing PR removed the existing "Share with Users" button leaving users with no way to share drafts. I've put that button back. If users use it now, it will make their post collaborative (meaning they become testers of the new collab editor
.
=> [LW only] Restore share drafts button

packages/lesswrong/components/form-components/PostsListEditor.tsx, packages/lesswrong/components/form-components/SequencesListEditor.tsx
Introduced in the `collabEditing` branch and fixed here, so merging into `lw-deploy` rather than `master`. Refactoring some hacky list-editor components so that they could be used in both the old and new forms system, accidentally broke the sequences post-list editor by mishandling a HoC prop.
=> Fix crash in sequences editor

packages/lesswrong/components/events/EventsHome.tsx, packages/lesswrong/components/events/modules/EventCards.tsx, packages/lesswrong/components/events/modules/VirtualProgramCard.tsx, packages/lesswrong/lib/components.ts
In a previous PR I created a special card for the Intro VP. Here I'm adding another one for the two more advanced VPs. Each half of the card is separately clickable. I'm not totally sold on the coloring, especially the orangey color - please let me know if you have suggestions.
Also for logged in forum users, they now only see the advanced VPs card:
=> special card for advanced VPs on the Events page

packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/lib/collections/tags/fragments.ts, packages/lesswrong/lib/collections/tags/schema.ts, packages/lesswrong/lib/generated/databaseTypes.d.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
Tag pages take their first step towards the [sprint prototype](https://www.figma.com/file/lYIUu1lWDFpjJKp4nLqny7/Forum-topics-Design-Sprint-Prototype?node-id=267%3A425) by getting a banner image. (LessWrong should read [this document](https://docs.google.com/document/d/1WbrFoDPoAba8J-jegGc2WMmHFIc7VP3Nl0WS6pjVF-E/edit) if you haven't yet.) Images were one of the most positive pieces of  feedback we got from the prototype interviews.
The main reason to have the white background encompass the title (deviating from the design) comes down to:
1. It's easier to deal with the TOC. (Otherwise we'd have to substantially refactor the component to allow the grid layout to lower it.)
2. It's easier to deal with the menu items, which require some conceptual thinking to get right.
I recommend viewing …
=> Tag Page Banner Images

packages/lesswrong/components/community/Community.tsx, packages/lesswrong/components/events/EventsHome.tsx
I just deployed the [new Community page](https://forum.effectivealtruism.org/community), and I noticed that the location field was acting weird - it wasn't respecting my account settings. Turns out there was a small bug related to SSR, which I introduced late in development.
=> fix small Community page bug

packages/lesswrong/components/tagging/TagPage.tsx
Was previously, for at least Lizka, sometimes not showing up as 100% width. I believe Cloudinary should have been taking care of that, but we can ensure it happens via CSS.
Thinking about it, I realize I don't actually know how Cloudinary figures out your screen size to size your images correctly. Since we are relying on them being at least as wide as your screen*, if they serve us a smaller image, we were previously screwed. Seems not that surprising they would sometimes serve us smaller images than necessary?
* Otherwise the div is not as wide as your screen.
Actually, maybe as I'm editing this description with more context, I'm convincing myself to add `width: 100%` to the LocalGroups page from which I copied? @s-cheng any reason not to?
=> Fix image width on tag banner image

packages/lesswrong/components/form-components/ImageUpload.tsx, packages/lesswrong/components/localGroups/LocalGroupPage.tsx, packages/lesswrong/lib/collections/localgroups/schema.ts
The screen-wide banner image at the top of the group details page isn't the best, especially on wide screens where it becomes way shorter than it is long. I heard some concerns from group organizers as well, so I went ahead and copied [Facebook's](https://www.facebook.com/help/212144952271305) group cover image sizing - the image keeps the same aspect ratio for all screen sizes.
=> Update group banner img layout

packages/lesswrong/lib/types/collectionTypes.ts, packages/lesswrong/server/callbacks/postCallbacks.ts, packages/lesswrong/server/scripts/mergeAccounts.ts, packages/lesswrong/server/vulcan-lib/validation.ts
I tightened the typechecking around MongoModifier, and this turned up two bugs: One in the `clearCourseEndTime` callback, the other in the `mergeAccounts` script.
(In the `clearCourseEndTime` case, the result was that the callback did nothing. For the `mergeAccounts` script, which is only used when run manually by an admin, the effect of the bug was to clobber the old account rather than put it into the intended deleted state.)
=> Fix bugs in clearCourseEndTime and mergeAccounts

packages/lesswrong/server/resolvers/arbitalPageData.ts
Fix broken Arbital links in hover-preview when using [-id] markdown link format. An affected example was the link to "moral uncertainty" in the hover-over of the link to "problem of fully updated (non-)deference" on https://www.lesswrong.com/posts/7im8at9PmhbT4JHsW/ngo-and-yudkowsky-on-alignment-difficulty which would render as a non-link text of the destination page ID.
=> Fix broken Arbital links in hover-preview when using [-id] markdown link format

packages/lesswrong/components/common/LoadMore.tsx, packages/lesswrong/components/events/modules/EventCards.tsx, packages/lesswrong/components/form-components/ImageUpload.tsx, packages/lesswrong/components/localGroups/LocalGroupPage.tsx, packages/lesswrong/components/notifications/NotifyMeButton.tsx, packages/lesswrong/components/posts/PostsGroupDetails.tsx, packages/lesswrong/components/posts/PostsList2.tsx
Since we created event cards for the Events page, we are now updating the group details page to list the group's events using those cards as well.
Past events are desaturated, and events without a start date (very rare) get their own section, due to the fact that mongo won't let us order them at the end of the "Upcoming Events" list.
=> [EA Forum only] use event cards on the group details page

packages/lesswrong/components/community/Community.tsx, packages/lesswrong/components/community/modules/LocalGroups.tsx, packages/lesswrong/components/community/modules/OnlineGroups.tsx, packages/lesswrong/components/localGroups/CommunityMap.tsx, packages/lesswrong/components/localGroups/CommunityMapWrapper.tsx
I added simple keyword search functionality to each of the groups lists on the new Community page. It filters both the lists and the icons on the map.
If there are no results, we also link the user to the Events page:
=> [EA Forum only] enable searching each groups list on the new Community page

packages/lesswrong/components/recentDiscussion/RecentDiscussionSubscribeReminder.tsx, packages/lesswrong/components/users/WrappedLoginForm.tsx, packages/lesswrong/server/resolvers/recentDiscussionFeed.ts
Based on Lizka's suggestions:
1. Updated the text, to stop referring to Aaron
2. Moved it up in Recent Discussion, to appear after 3 items rather than after 6 items
3. Made the "Sign Up" button primary
4. Made the envelope icon teal instead of black
=> [EA Forum only] updates to the EA Forum Digest reminder in recent discussion feed

packages/lesswrong/components/common/SectionFooter.tsx, packages/lesswrong/components/localGroups/LocalGroupPage.tsx
In this PR, I'm replacing the tiny icons at the top of the current group details page with more prominent buttons that go to their external links. Also it looks like we currently don't even show the group's email address even though we collect it.
The "Contact Us" section only appears if the group has any of the relevant info, and the small map only appears if it's a local group that has a banner image (no banner image means the map is at the top of the page instead).
I made all the buttons "contained" except for the website and email the organizer buttons, since I considered those two to be more secondary. Open to feedback on this.
-----
Logged in users will still see the "subscribe" prompts, and admins & group organizers will still see the "New event" and "Edit Group" buttons.
----- …
=> Redesign group details page external links

packages/lesswrong/server/fieldChanges.ts
`logFieldChanges` records to the `LWEvents` collection when some fields of some other collections change, which isn't used in the UI anywhere but can be useful for reconstructing past events, eg I recently used it to find out the history of an author changing a post's title after it was frontpaged.
Make it deep-compare the old and new values, rather than shallow-compare, so that it doesn't produce spurious log entries for array- and object-typed fields that haven't actually changed.
=> Suppress spurious field-change logging for things that haven't actually changed

packages/lesswrong/components/posts/PostsPage/PostsPageEventData.tsx
In this PR, I'm adding a version of the existing CTA button on the event details page that links to the event on Facebook or Meetup. The existing links next to the post author will remain, since we still want them to be accessible even if another CTA takes precedence.
I decided to make it a version of the existing CTA (rather than a separate button) so that there wouldn't be multiple competing actions for the user, but maybe I should consider making it a separate button that is less prominent than the "Register" button. I'm not sure which is best here - open to suggestions.
=> add button on event details page to see the event on Facebook (or Meetup)

packages/lesswrong/components/community/Community.tsx, packages/lesswrong/components/community/modules/LocalGroups.tsx
In this PR, I updated the local groups keyword search on the Community page to also match on locations, and started tracking some data on what people search for.
EDIT: I also added a link to the Events page at the bottom of the Community page:
=> [EA Forum only] update Community page search

packages/lesswrong/components/localGroups/CommunityMap.tsx
I forgot to update the filtering on the map to match the local groups list, so I'm updating it here.
=> fix Community page map keyword filtering

packages/lesswrong/components/community/modules/DistanceUnitToggle.tsx, packages/lesswrong/components/events/EventsHome.tsx
I noticed a weird bug on the prod Events page. Moving the default distance filter logic to `useEffect` seems to have fixed it (I think it was an SSR issue).
=> [EA Forum only] fix bug on Events page that caused an extra event card to appear

packages/lesswrong/components/common/ContentItemBody.tsx, packages/lesswrong/components/linkPreview/HoverPreviewLink.tsx, packages/lesswrong/components/tagging/AllTagsPage.tsx, packages/lesswrong/components/tagging/TagHoverPreview.tsx, packages/lesswrong/components/tagging/TagPreview.tsx
The All Tags page on LessWrong and the EA Forum is a slow experience. On a fast macbook LessWrong's is an acceptable page, but on an older computer or a phone, it's pretty bad (>10 seconds till interactive), and the EA Forum's ranges from "noticeably slow" to "unusable garbage".
When you hover your mouse over a tag, you get a preview of that tag. I suspected that the slowness of the allTags page was due to the prefetching, which Jim & I confirmed. The problem lies entirely in the previews fetched by the Wiki Portal *description*, not the all tags list. The description is sent inside ContentItemBody, which only fetches its previews on the client, and does so in 500 individual apollo queries. We could not find out why 500 queries is enough to kill peg the CPU for 7 seconds, but it is. It is …
=> Disable prefetch of tag hover preview on all tags page

packages/lesswrong/components/common/LoadMore.tsx, packages/lesswrong/components/sequences/ChaptersItem.tsx, packages/lesswrong/components/sequences/ChaptersList.tsx, packages/lesswrong/components/sequences/SequencesPostsList.tsx, packages/lesswrong/components/tagging/TagIntroSequence.tsx, packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/lib/collections/tags/fragments.ts, packages/lesswrong/lib/collections/tags/schema.ts, packages/lesswrong/lib/components.ts, packages/lesswrong/lib/generated/databaseTypes.d.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
The goal of this is to give newbies a curated "here's where to start". It probably still needs a load more, and I want to think about if I want to bother deploying this without any intro sequence selected, but the code is basically there.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1201981539334652) by [Unito](https://www.unito.io)
=> Intro Sequences for Tags

packages/lesswrong/components/ea-forum/StickiedPosts.tsx
This PR removes extra padding from the desktop view of the EA homepage caused by the heading at the top. The result is the same top padding that exists on other pages.
<div>
</div>
=> Remove extra headroom from EA homepage

packages/lesswrong/components/linkPreview/PostLinkPreview.tsx
Fixes a bug introduced in e93a738bed3c9aa5ba30d895b2fe0ad8a3796e58 which was an incorrect fix for a bug introduced in 002974c9011b421d29562f99229f349612c414f4.
=> Fix loading state of post-link previews

packages/lesswrong/components/common/CloudinaryImage2.tsx, packages/lesswrong/components/tagging/TagPage.tsx
The bug briefly showed a broken image icon while loading the image. Instead of figuring that one out, I went ahead and switched to the better component, which we want to do anyway.
I'd be interested in feedback on my introduction of a `header` flag to CloudinaryImage2. Header banners are common, and I was thinking they'd need custom srcsets and it seemed worth making a special case, but I could be talked out of it.
=> TagPage now uses CloudinaryImage2 to prevent loading bug

packages/lesswrong/components/seasonal/AprilFools2022.tsx, packages/lesswrong/components/users/UsersNameDisplay.tsx, packages/lesswrong/components/votes/OverallVoteAxis.tsx, packages/lesswrong/components/votes/PostsVote.tsx
This turns off UI for the Good Heart Project (aka LW April Fools 2022) by default unless the databasemetadata field "enableGoodHeartProject" is true.
This *doesn't* currently turn off the UserProfile heart, because that was only merged into lw-deploy, not master, and I didn't deal with it yet.
=> Add enableGoodHeartProject setting

.gitignore
This is based on my current understanding of the new way to run a local mongodb instance, which is to run
```
mkdir myLocalDatabase
mongod --dbpath ./myLocalDatabase
```
=> Add myLocalDatabase to .gitignore

packages/lesswrong/components/posts/PostsEditForm.tsx
Adds a check to PostsEditForm, allowing admins to access the page even if they are not shared on it.
=> Admins can bypass sharing permission requirements

packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/server/search/utils.ts
This PR increases our limits to index the first 18,000 characters of tags and comments, and also doesn't show "read more" on the EA Forum.
For testing: [this tag](http://localhost:3000/tag/anti-aging-research) has >18,000 characters on the EA dev DB.
=> Index long tags and comments

packages/lesswrong/components/questions/Answer.tsx
Fixes some broken wrapping in the headers of Answers, at narrow page widths (or with very long author names).
.
=> Fix flexbox wrapping in Answer header

packages/lesswrong/lib/collections/localgroups/schema.ts
I had meant to make this field optional, and noticed that it was not.
=> make group category optional

packages/lesswrong/components/notifications/NotificationsMenu.tsx
This is just a small refactoring/cleanup change. Explanations are inline. Please view the diff with "hide whitespace".
=> Cleanup: Remove extraneous state from NotificationsMenu

packages/lesswrong/lib/collections/localgroups/schema.ts
EA Forum added a 'categories' field to localgroups which feels a bit redundant on LessWrong (it's similar to our "types" field, which is hidden on EA forum). This PR just hides it on LW.
=> Remove categories from LessWrong localgroups

packages/lesswrong/server/akismet.ts
Quoting myself on slack:
> Does anyone know what purpose is served by akismet reviewing posts for spam? We still review posts that are marked as spam, so it doesn't save labor. And we don't show posts to users until after review, so it doesn't save time of spam on the frontpage. All that it seems to do is introduce an annoying problem where we have to manually fix posts that have been marked as spam. We could fix it so that if users are approved their posts are retroactively marked as not-spam, but instead it seems easier to just remove the entire check, as it is entirely without utility. Unless I'm missing something.
https://cea-core.slack.com/archives/C75BWSNBH/p1649971224115419
Gonna hold off on merging to give a chance for people to tell me I'm missing something.
=> Don't use akismet to review posts for spam

packages/lesswrong/components/community/modules/CommunityMembers.tsx
I realized that the default number of results was 20. We should show more than that (currently we have about 40 people on the map).
I just made some small styling adjustments to the default pagination component, might revisit later.
=> show more people on the Community Members tab

packages/lesswrong/components/community/modules/CommunityMembers.tsx, packages/lesswrong/components/community/modules/SearchResultsMap.tsx, packages/lesswrong/server/search/algoliaDocuments.d.ts, packages/lesswrong/server/search/utils.ts
I thought it would be fine to use the `bio` field, but on prod it was a bit confusing when the `bio` and `htmlBio` (used on the actual profile page) were formatted differently, ex. links turn into long URL strings.
=> [EA Forum only] Use html bio for community members tab

packages/lesswrong/components/users/UsersMenu.tsx, packages/lesswrong/lib/collections/conversations/schema.ts, packages/lesswrong/lib/collections/users/custom_fields.ts, packages/lesswrong/lib/collections/users/formGroups.ts, packages/lesswrong/lib/vulcan-i18n-en-us.ts
As I will be adding more fields to the Edit Account form, I wanted to clean it up a bit first. Worked with @jpaddison3 on this so he already pre-approved it. :)
Basically we moved some things into "Site Customization" and now all the sections are collapsed by default, so you might actually be able to see the "Submit" button when the page loads (prevents people from losing their changes by assuming this auto-saves).
=> collapse Edit Account form groups by default

packages/lesswrong/client/AppGenerator.tsx, packages/lesswrong/client/start.tsx, packages/lesswrong/components/comments/CommentsItem/CommentBottomCaveats.tsx, packages/lesswrong/components/comments/CommentsItem/CommentsItem.tsx, packages/lesswrong/components/comments/CommentsListSection.tsx, packages/lesswrong/components/common/FormatDate.tsx, packages/lesswrong/components/vulcan-core/App.tsx, packages/lesswrong/lib/utils/timeUtil.ts, packages/lesswrong/server/apolloServer.ts, packages/lesswrong/server/vulcan-lib/apollo-ssr/components/AppGenerator.tsx, packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
We display a lot of timestamps relative the current time; eg a comment's age may be displayed as `4m` for 4 minutes ago. However, using the system clock (with `new Date()` or `moment()`) breaks the rule that React components must always return the same thing when you rerun them; if the time that passes in between calls happens to cross from 3:59 to 4:00, the result will be different. This creates React SSR mismatches. It's particularly likely to happen when serving logged-out users from the page cache, which may be up to 90 seconds old. The symptoms of this aren't especially severe, but it creates a lot of console-log and Sentry spam, since it affects the logged-out front page.
To fix this, we attach a timestamp to renders, embed that in the page, and put that timestamp in a …
=> Prevent React SSR mismatches from timestamps

packages/lesswrong/components/community/modules/CommunityMembers.tsx, packages/lesswrong/lib/generated/databaseTypes.d.ts
Sadly for everyone, Safari doesn't handle [line clamping](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) mixed with nested HTML very well. [Adding an extra `div`](https://stackoverflow.com/questions/57546280/clamping-lines-with-line-clamp-and-nested-p-tags) seems to make it look not broken on Safari, and still works fine for other browsers, so I went with that solution.
=> [EA Forum only] fix Community Members tab in Safari

packages/lesswrong/components/community/Community.tsx, packages/lesswrong/components/events/EventsHome.tsx, packages/lesswrong/components/form-components/LocationFormComponent.tsx, packages/lesswrong/components/localGroups/CommunityHome.tsx, packages/lesswrong/components/localGroups/EventNotificationsDialog.tsx, packages/lesswrong/components/localGroups/SetPersonalMapLocationDialog.tsx, packages/lesswrong/components/recentDiscussion/RecentDiscussionMeetupsPoke.tsx, packages/lesswrong/lib/collections/posts/custom_fields.ts, packages/lesswrong/lib/collections/users/custom_fields.ts
Changes Google Maps loading and field-name handling in LocationFormComponent
so that having multiple location fields on the page at once works properly.
Slightly changes the location-input styling (there is now a label,
separate from the placeholder, so you can tell the two fields apart).
Co-Authored-By: Sarah Cheng <sarah.cheng@centreforeffectivealtruism.org>
=> User profile page shows both location fields

packages/lesswrong/server/callbacks/userCallbacks.ts
In an effort to reduce the number of spam accounts that appear on our [map of users](https://forum.effectivealtruism.org/community#individuals), I'm flagging users who add themselves to the map as `needsReview` if they haven't already been reviewed. For now I'm not hiding them from the list/map while they are in this state, since I'm assuming users marked as `needsReview` tend to get reviewed within a few days, and most accounts who go through this process are not spam.
Currently, our database has around 10K users who have been reviewed and 7.5K who have not, so I would prefer not to filter out all users who have not been reviewed.
=> mark users who add themselves to the map as "needs review" if they haven't been reviewed

packages/lesswrong/server/callbacks.ts
We want to give all users one chance to change their usernames themselves (although this is not explained anywhere). After that they would need to contact us to make further changes.
On the EA Forum, we randomly assign new users a username like `new_user_#` and immediately prompt them to change it, which means they use up that one chance right away. (See below for an admin view of a new user's account.) This PR is for us to ignore this initial step of setting up the username.
=> [EA Forum only?] fix bug that prevented new users from changing their usernames

packages/lesswrong/components/comments/UserCommentsReplies.tsx, packages/lesswrong/components/common/TabNavigationMenu/FeaturedResourceBanner.tsx, packages/lesswrong/components/notifications/NotificationsMenuButton.tsx, packages/lesswrong/components/posts/PostsByVoteWrapper.tsx, packages/lesswrong/components/posts/PostsCommentsThread.tsx, packages/lesswrong/components/posts/PostsItemNewCommentsWrapper.tsx, packages/lesswrong/components/posts/PostsList2.tsx, packages/lesswrong/components/review/ReviewPostComments.tsx, packages/lesswrong/components/review/ReviewVotingPage2019.tsx, packages/lesswrong/components/sunshineDashboard/SunshineCuratedSuggestionsList.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUserCommentsList.tsx, packages/lesswrong/components/sunshineDashboard/SunshineNewUserPostsList.tsx, packages/lesswrong/components/tagging/CoreTagsChecklist.tsx, packages/lesswrong/components/tagging/PostsPageTopTag.tsx, packages/lesswrong/components/tagging/TagDiscussion.tsx, packages/lesswrong/components/tagging/TagDiscussionSection.tsx, packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/components/users/UsersProfile.tsx, packages/lesswrong/lib/crud/withMulti.ts, packages/lesswrong/lib/filterSettings.ts
After twice implementing a new component and running into a bug that was due to the incorrect typing of useMulti, I have finally fixed it. useMulti can absolutely return undefined results (ie: when loading, or when there's an error).
This is a risky PR. The previous [similar PR](https://github.com/ForumMagnum/ForumMagnum/pull/4213), applying this treatment to the useSingle hook, has been the cause of a few bugs. I was the author of that PR, while pairing with the (in an unrelated status update, now departed from GWWC) Jasper. That one we were pretty aggressive about returning null at the first sign of trouble. In this PR I've spent significantly more time on it, and tried to match existing behavior, or, where I thought the existing behavior was to throw an error, to read code pretty …
=> Make type of useMulti result include possibility of undefined 

packages/lesswrong/lib/collections/localgroups/schema.ts, packages/lesswrong/lib/collections/posts/custom_fields.ts
When we updated the `LocationFormComponent`, we forgot to update all the necessary fields to match.
=> fix bug that stopped populating location fields

packages/lesswrong/components/community/modules/SearchResultsMap.tsx
On our current [Community Members map](https://forum.effectivealtruism.org/community#individuals), users who pick exactly the same location will overlap each other. This PR slightly shifts all markers a random amount, to make it easier to see how many markers are in a given area.
This only affects this one map right now, but we should probably do something similar with the Local Groups map as well.
=> [EA Forum only] disambiguate map markers with exactly the same lat/lng on the Community Members tab

packages/lesswrong/components/users/UsersProfile.tsx
Oli made changes to the UsersProfile component for April Fools 2022,. The change was only made off the lw-deploy, not master. This should be merged before https://github.com/ForumMagnum/ForumMagnum/pull/4756 is merged into lw-deploy, so that we don't end up with user profile pages with missing UI elements.
=> Remove good heart UI from user profile (lw-deploy) 

packages/lesswrong/server/callbacks/userCallbacks.ts
Based on this [slack thread](https://cea-core.slack.com/archives/CB5D60VSB/p1652096500081429), we are running a test to see if it's reasonable for us to review all unreviewed users who add a bio.
=> [EA Forum only] review all unreviewed users who add a bio

cypress/integration/messages/create_message.spec.js, packages/lesswrong/components/users/EditProfileForm.tsx, packages/lesswrong/components/users/UsersEditForm.tsx, packages/lesswrong/components/users/UsersMenu.tsx, packages/lesswrong/components/users/UsersProfile.tsx, packages/lesswrong/lib/routes.ts, packages/lesswrong/lib/vulcan-i18n-en-us.ts
This PR provides a way for admins to edit other users' profiles.
EDIT: Ok, decided to go ahead and move the "Message" button up. All this is still EA Forum only.
-----
~~Unfortunately now there are too many links here, which causes one to wrap. I was hoping this would be quick, but I think I'll have to figure out how to update this part of the page to fix it. Maybe I will just go ahead and move the "Message" button above the rest.~~
=> [EA Forum only] allow admins to edit other users profiles

packages/lesswrong/components/posts/AllPostsPage.tsx, packages/lesswrong/components/posts/PostsListSettings.tsx, packages/lesswrong/components/posts/PostsListSortDropdown.tsx, packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/lib/collections/posts/schema.ts, packages/lesswrong/lib/collections/tags/fragments.ts, packages/lesswrong/lib/collections/tags/schema.ts, packages/lesswrong/lib/generated/databaseTypes.d.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
This PR lets you set the default sort order of a tag/topic page's posts list.
Based on a request from Lizka: https://cea-core.slack.com/archives/C038J512SD8/p1652364522576919
=> add an option to set the default sort order of a tag page's posts list

packages/lesswrong/components/tagging/TagPage.tsx, packages/lesswrong/components/users/UsersProfile.tsx
Follow up to https://github.com/ForumMagnum/ForumMagnum/pull/4914
Now the posts actually get sorted.
=> tag page posts default sort order should actually sort the posts

packages/lesswrong/components/form-components/FormComponentDate.tsx, packages/lesswrong/components/form-components/FormComponentDefault.tsx, packages/lesswrong/components/form-components/FormComponentNumber.tsx, packages/lesswrong/components/form-components/MuiTextField.tsx, packages/lesswrong/components/vulcan-forms/Form.tsx, packages/lesswrong/lib/collections/users/custom_fields.ts, packages/lesswrong/lib/types/schemaTypes.ts, packages/lesswrong/lib/vulcan-forms/schema_utils.ts
Mostly I was focused on understanding how the component worked, and added some types as I read, specifically reading through the construction of the `field` object.
I also changed MUITextField to be a functional component. My eventual goal is to make it so the custom `control` components have their props typed, among other things.
The most interesting part of this PR was me (and Sarah) looking at `schema_utils.ts`, and noticing how many of the keys it expected to be there were declared in `CollectionFieldSpecification`. I decided to remove many of them as they were otherwise completely unmentioned in the codebase. However other keys looked like they were still supported by the form system, and we were merely not utilizing them. So I added them to `CollectionFieldSpecification`.
=> Small maintenance to SmartForm component

packages/lesswrong/components/form-components/FormComponentDateTime.tsx
A user sent in this bug report around setting the time of an event
=> fix time picker css

packages/lesswrong/components/posts/PostSubmit.tsx
Now that we have the capacity we're going to try enabling this again. Starting out with a higher karma requirement to make sure we can take the load.
=> [EA] Reenable request feedback button on post create/edit page

packages/lesswrong/client/apolloClient.ts, packages/lesswrong/client/publicSettings.ts, packages/lesswrong/client/start.tsx, packages/lesswrong/components/common/ReCaptcha.tsx, packages/lesswrong/components/form-components/LocationFormComponent.tsx, packages/lesswrong/components/posts/PostSubmit.tsx, packages/lesswrong/components/themes/ThemePickerMenu.tsx, packages/lesswrong/lib/executionEnvironment.ts, packages/lesswrong/lib/types/windowObjectExtensions.ts, packages/lesswrong/lib/vulcan-lib/components.tsx, packages/lesswrong/server/vulcan-lib/apollo-ssr/renderUtil.ts
Type-check when we add things to the client's `window` object, so that we aren't casting it to `any` everywhere. (This came up in a pairing session with @jpaddison3 and was living in my git stash.)
=> Type-annotate our extensions to the Window object

packages/lesswrong/components/events/modules/EventCards.tsx, packages/lesswrong/components/posts/PostsPage/PostsPage.tsx, packages/lesswrong/components/posts/PostsPage/PostsPageEventData.tsx, packages/lesswrong/server/notificationCallbacks.tsx
1. Higher quality event images
2. Icons next to event metadata
3. Event location link is link-colored now
4. When someone adds a comment to an event that is associated with a group, the group's organizers also get notified (this is especially useful for the EA Forum, where we have a contractor posting many events for groups)
=> Some small event-related improvements

packages/lesswrong/server/migrations/2022-03-10-oauthCleanup.ts
Previously: https://github.com/ForumMagnum/ForumMagnum/pull/4673
(The tl;dr of which is that some data in the database was in the wrong shape due to a bug. The PR fixes it with a migration.)
When reviewing that PR, I thought it didn't affect Auth0. I saw an account today that had the bug. So apparently it did. Add Auth0 to the list of services that we run the fix-it migration against.
=> Auth0 also gets OAuth data fix

packages/lesswrong/components/common/ContentStyles.tsx, packages/lesswrong/server/styleGeneration.tsx, packages/lesswrong/themes/colorUtil.ts, packages/lesswrong/themes/createThemeDefaults.ts, packages/lesswrong/themes/themeType.ts, packages/lesswrong/themes/userThemes/darkMode.ts
I thought I had this in the `themePicker` branch (and mentioned it in the announcement post), but then I looked at my working directory and discovered pieces of it in a side branch and pieces of it in my git stash. Whoops. This is interesting enough that it's probably worth reviewing separately, though, so here it is.
(This is the same as the block comment in `darkMode.ts`):
CkEditor allows users to provide colors for table cell backgrounds and
borders, which get embedded into the HTML looking like this:
```
<td style="background-color: rgb(1,2,3)">
```
User-provided colors can be in any format that CSS accepts, and may set
the `background-color` and `border` properties on `<table>` and `<td>`
elements.
We don't have any theme-specific HTML postprocessing, so this poses a bit of
a …
=> Theming: Override post-provided colors

packages/lesswrong/lib/utils/viewUtils.ts, packages/lesswrong/lib/vulcan-core/default_resolvers.ts, packages/lesswrong/lib/vulcan-lib/collections.ts
Add `$comment` to the selector of all queries going through the view system, containing the name of the view and a list of terms that were attached.
This doesn't directly fix any performance problems, but should make interpreting the mongodb cloud profiler much easier.
=> Add `$comment` to queries using views

packages/lesswrong/components/posts/PostsPreviewTooltip.tsx
This fixes a minor styling bug where list item text in tooltip previews was larger than the other text in those tooltip previews.  Modified the styling in `PostsPreviewTooltip` to avoid impacting Question answer styling.
Before
After
=> make font size of text in list items in tooltip previews the same as other text in the tooltips

packages/lesswrong/server.ts, packages/lesswrong/server/apolloServer.ts, packages/lesswrong/server/staticRoutes/debugHeaders.ts, packages/lesswrong/server/vulcan-lib/apollo-server/context.ts, packages/lesswrong/server/vulcan-lib/apollo-ssr/renderPage.tsx
Used for debugging why some logs have what look like what might be load-balancer IPs in them rather than end-user IPs. Changes some middleware ordering so that static routes can use `getUserFromReq` to enforce the admin-only bit.
Change which IP-address-forwarding header is used, so that we get the real external IP address instead of an internal load-balancer IP.
=> Add an admin-only static endpoint that echoes back your HTTP headers and IP

packages/lesswrong/lib/types/collectionTypes.ts, packages/lesswrong/server/callbacks/votingCallbacks.ts
Oli noted that this PR didn't have the right behavior:
> Alas, we'll likely have to revert this PR. It is quite important that the vote totals are directly derivable from nothing but the vote table, so that we can rerun vote totals from time to time, so any change to how karma gets allocated also needs to change the code for rerunning vote totals.
Reverts ForumMagnum/ForumMagnum#4976
=> Revert "Share karma among co-authors"

packages/lesswrong/components/posts/Pingback.tsx
Previously, tooltips would overflow the bottom of the screen in all cases.  Undesirable behavior!  Now they match the post preview tooltip behavior.
Before:
After:
=> remove broken flip behavior in pingback tooltip

packages/lesswrong/components/common/HomeLatestPosts.tsx, packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx, packages/lesswrong/components/recommendations/RecommendationsPage.tsx, packages/lesswrong/lib/routes.ts
Over a year ago we moved the curated section to the Latest Posts section temporarily (I think during Review Season when the Recommendations section was removed or moved lower on the page). This PR finally moves it back. It also adds a longer Curated to the Recommendations page, so that when you click on the "Recommendations" link it takes you to a page that roughly matches the formatting of the frontpage RecommendationsAndCurated section.
The curated section sorts by curation date instead of postedAt, which is an improvement over the previous All Posts solution for the curated posts list.
(The curated section on the /recommendations page only appears on LessWrong, so EA forum and AF don't have a weird empty section)
Also adds a "/curated" link that redirects to "/recommendations" on …
=> Return curated to recommendations-section, add to rec page

packages/lesswrong/components/comments/CommentActions/DeleteCommentDialog.tsx, packages/lesswrong/lib/utils/schemaUtils.ts, packages/lesswrong/server/callbacks/commentCallbacks.ts, packages/lesswrong/server/resolvers/commentResolvers.ts, packages/lesswrong/server/vulcan-lib/mutators.ts
And add a logger for denormalized updater callbacks.
Comment deletion goes through a custom resolver. The resolver was previously calling `Comments.rawUpdateOne`, this PR converts it to use updateMutator, which ensures it calls all the callbacks registered on the Comments collection.
This caused `deletedReason` to no longer be optional. From my experience, it's valuable to have people write the reason why they're deleting their own comments, so I decided to leave it required, as a callback intended, and not as the frontend claimed.
=> Fix decrementing of commentCount on comment deletion

packages/lesswrong/lib/collections/users/fragments.ts
Pairing with Jim. Problem was the fragment was missing the information necessary to populate ckeditor.
=> Fix editing bio on LessWrong

packages/lesswrong/components/search/CommentsSearchHit.tsx, packages/lesswrong/components/search/PostsSearchHit.tsx, packages/lesswrong/components/search/SearchBarResults.tsx, packages/lesswrong/components/search/SequencesSearchHit.tsx, packages/lesswrong/components/search/TagsSearchHit.tsx
Tweaks the UI for quick search. Some principles:
– removed the lines in between each item, instead having lines between in section so that it's easier to skim for which section you're looking for
– hides empty sections (instead of seeing a janky border-bottom with a bit of padding)
– shifts the positioning of the icon for posts higher, so that it's easier to use it as the anchor-point of where to start reading the PostsSearchItem
(previous version:)
=> Improve Quicksearch UI

packages/lesswrong/components/sunshineDashboard/SidebarHoverOver.tsx
The new LWPopper resulted in sunshine sidebar hoverovers positioning themselves unpredictably, and sometimes trying overlapping with the site header. This restores their functionality to the previous version, where they are always aligned with the top of the parent sunshine item.
=> sunshine hoverovers allow overflow

packages/lesswrong/components/vulcan-core/App.tsx
We're updating our site image (Mississippi river) to a new stylised version. This is effectively done with a DB change, but also updating the default value in the code here.
=> update site image for social media [LW]

packages/lesswrong/components/shortform/ProfileShortform.tsx, packages/lesswrong/components/users/UsersProfile.tsx, packages/lesswrong/lib/components.ts
Not sure this is the best possible implementation of shortform-on-user-profiles, but it's what I could implement quickly, and I think is better than not-existing.
=> User profile shortform

packages/lesswrong/components/community/modules/CommunityMembers.tsx, packages/lesswrong/lib/collections/users/custom_fields.ts, packages/lesswrong/server/notificationCallbacks.tsx
I initially misunderstood how "default subscribed" to notifications worked - hopefully the logic is correct now.
I also fixed a small bug with the EA Forum's community map.
=> fix a bug around "new comment" notifications for group organizers

packages/lesswrong/components/walledGarden/WalledGardenHome.tsx, packages/lesswrong/lib/routes.ts
The route garden.lesswrong.com previously directed to lesswrong.com/walledGardenPortal, which is an iframe housing our gather.town instance. Gather.town no longer lets us do an iframe, and we're not really supporting Walled Garden anyway. But it's occasionally used (John Wentworth is using it soon for SERI MATS), so it seemed worth briefly cleaning it up.
This PR redirects it to lesswrong.com/walledGarden, a page that just provides a text overview of what the garden is about, and a link that goes to https://gather.town/app/aPVfK3G76UukgiHx/lesswrong-campus
The PR also updates the text a bit to be more up-to-date
=> Redirect /walledGardenPortal

packages/lesswrong/server/vendor/synced-cron/synced-cron-server.ts
Cron jobs were not running due to a bug where after #4966, nested onStartup calls now fail. Removed the onStartup call from `SyncedCron.start`, which is already called inside an onStartup.
=> Fix cron jobs

packages/lesswrong/server/styleGeneration.tsx
In particular, the snackbar background color was still white, and I think some buttons were still the wrong color. We'd probably need to add more styles to register-mui-styles to get it working.
=> actually colors were not all fixed

packages/lesswrong/components/posts/PostsList2.tsx, packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
The recent "hide posts from frontpage" PR broke the intended curated functionality. This restores and slightly refactors it
=> Restore curated hidden functionality

packages/lesswrong/components/votes/AgreementVoteAxis.tsx, packages/lesswrong/components/votes/OverallVoteAxis.tsx, packages/lesswrong/lib/collections/posts/schema.ts
This sets the default voting system for LessWrong and AlignmentForum to two-axis. It sets it for LW and AF specifically so that things like Progress Forum aren't affected, and it sets it via the defaultValue instead of some of the other functions that handled default-voting-system-setting so that it only applies to future posts.
Also slightly updated the UI. I still really don't like the X and checkmark icons, but don't know what better thing to do.
=> default non-EA voting is twoAxis

packages/lesswrong/components/common/HeadTags.tsx
I updated the content value from "summary" to "summary_large_image" as defined in the Twitter Cards documentation.
=> Adjusted Twitter meta tags for large image preview as requested in issue #4814

packages/lesswrong/components/recentDiscussion/RecentDiscussionTagRevisionItem.tsx
Lizka is about to drop a huge update on the wiki main page. I want it not to blow up recent discussion, which it totally would. I think this is a change that should happen anyway.
@darkruby501 please let me know monday if you don't want this on LW.
=> Filter out admin-only Topic updates from recent discussion

packages/lesswrong/server/debouncer.ts
Without setting the arg to a default, you'd have to call it like
```
❯ ./scripts/serverShellCommand.sh 'Globals.forcePendingEvents({})'
```
Now you can call it like
```
❯ ./scripts/serverShellCommand.sh 'Globals.forcePendingEvents()'
```
Clearly a big improvement.
(But seriously, it would be annoying for people to run it the way they were used to and then get an error and have to figure out why. Also it is just kinda lame.)
=> Allow running of forcePendingEvents without passing in any optional args

packages/lesswrong/lib/collections/posts/schema.ts
Change the default voting system on LW and AF to two-axis.
(https://github.com/ForumMagnum/ForumMagnum/pull/5090 tried to do this but it didn't work because it was only changing the default value of a form-field with moderator-only permissions).
=> Change the default LW voting system to two-axis (for real this time)

packages/lesswrong/components/common/LinkCard.tsx, packages/lesswrong/components/linkPreview/PostLinkPreview.tsx, packages/lesswrong/components/posts/PostsPage/PostsTopSequencesNav.tsx, packages/lesswrong/components/sequences/SequencesGridItem.tsx, packages/lesswrong/components/sequences/SequencesHoverOver.tsx, packages/lesswrong/lib/collections/posts/fragments.ts, packages/lesswrong/lib/collections/sequences/fragments.ts, packages/lesswrong/lib/components.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts, packages/lesswrong/lib/routes.ts
This adds Sequence hoverovers both for SequencesGridItem and for links (i.e. in the body of posts).
It uses the SequencesPageFragment for the post hoverpreviews, which I'm pretty sure is a fine amount of data to be querying but worth doublechecking.
Currently, the link-preview for SequencesGridItem has "clickable" activated so you can mouse over it. This is useful to clicking on the posts, but might be kinda annoying since it means mousing over a SequencesGridItem list is overwhelming with hard-to-get-rid-of-previews
=> Sequence hover over

packages/lesswrong/server/notificationCallbacks.tsx
Fix bug in `PostsNewNotifyUsersSharedOnPost` caused by null `shareWithUsers` being returned from post object.
Seems like the ideal fix in preventing this kind of thing is deeper typing solution.
=> Fix Bug in Sharing New Posts due to notificationCallbacks changes

packages/lesswrong/components/community/modules/CommunityMembers.tsx, packages/lesswrong/components/posts/PostsPage/PostAuthorCard.tsx
Again [Safari is messing up my line-clamps](https://stackoverflow.com/questions/70679732/css-line-clamp-does-not-work-in-safari-on-inner-block-level-elements). :(
I think just cutting off the text using `truncatise()` is the solution that works best overall.
=> [EA Forum only] replace line-clamp with truncatise for CKEditor fields

packages/lesswrong/components/form-components/MuiInput.tsx, packages/lesswrong/lib/collections/users/schema.ts
Because the functionality to change a user's email address is not fully built out, we've decided to stop supporting it for now. We will re-enable this once we have properly integrated Auth0 to manage email address changes.
=> [EA Forum only] disallow email address changes

packages/lesswrong/components/sunshineDashboard/SunshineNewPostsItem.tsx
This adds a small vote widget to the SunshineNewPostsItem, so moderators can easily upvote/downvote things as they process them.
=> Vote on sunshine new posts

packages/lesswrong/components/sequences/LargeSequencesItem.tsx, packages/lesswrong/lib/collections/books/fragments.ts, packages/lesswrong/lib/collections/sequences/fragments.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts
This PR makes the new collections page load all posts at once, so that you don't have to wait for them to appear.
=> Load chapters with collection page

packages/lesswrong/lib/collections/posts/schema.ts
The use-case of mixed link-poster and actual-author usernames as co-authors seems incredibly confusing to me. Link-poster status and actual author status are very different things, but listing them both as authors makes it seem like they wrote it together – and worse, the link-poster will be the first author!
Made a PR to remove the encouragement of that use-case by default, but left the existing text for EA Forum.
I do like having a popup that gives instructions about link posts though! People not inserting any text, just the link, has been a failure mode that's come up enough times.
=> Have different link-post hint text for different forums

packages/lesswrong/components/tagging/FilterMode.tsx
Fixes #5016 
This is a quick fix. I also fixed the width of the input which was cutting off the "r" in "Other".
Before:
After:
=> Fix margin for 'Show Personal Blogposts' settings

packages/lesswrong/server/notificationCallbacks.tsx
Currently there's a bug with our fix of coauthor notifications, don't want any spurious notifications, so disabling
=> Disable co-author notification due to bugs

packages/lesswrong/components/sunshineDashboard/ModerationLog.tsx, packages/lesswrong/lib/collections/users/helpers.ts
Most users are unaware that their moderation actions are public. Indeed, `/moderation` isn't linked to anywhere in the site UI. It seems bad that that page lists moderation actions like "Bob banned Sue from their posts", when Bob wasn't expecting that to be public. So this PR hides it.
I speculate that LW will not want this change, so I've made it EA-only. It can easily applied to LW of course.
This PR does NOT hide that info from a properly constructed GraphQL query, because end-user moderation has only been used 4 times ever, so if you really want to see that information, fine. I don't think it's worth the dev time to fix, and I'm slightly nervous about making it viewable by mods-only and breaking something.
Submitted against `fix-moderation-log` for the avoidance of merge-conflicts.
=> [EA] Hide user moderation actions from non moderators

packages/lesswrong/components/common/TabNavigationMenu/TabNavigationItem.tsx
You're not going to believe me, but the presence of a single `a` tag in sidebar links caused the whole sidebar to fail to register taps. Only on iOS. This is why the issue only affects the EA Forum. We have an external link (which causes the a tag) in our sidebar. LW does not. Comment out the external link and the sidebar works.
This is a rather hacky solution to that. I swear to god it fixes the bug.
I believe this to be the actual cause of a mis-diagnosed: https://github.com/ForumMagnum/ForumMagnum/issues/4950. I need to test that in a few more places before I'm sure. But first I need to run for tonight.
=> Fix EA Forum Drawer Nav on iOS

packages/lesswrong/components/posts/PostsPage/PostsAuthors.tsx, packages/lesswrong/components/posts/PostsPage/PostsCoauthor.tsx, packages/lesswrong/components/posts/PostsUserAndCoauthors.tsx, packages/lesswrong/components/users/UsersNamePending.tsx, packages/lesswrong/lib/collections/posts/custom_fields.ts, packages/lesswrong/lib/collections/posts/helpers.ts, packages/lesswrong/lib/components.ts, packages/lesswrong/server/callbacks/postCallbacks.ts, packages/lesswrong/server/notificationTypesServer.tsx
There's several very closely related fixes/changes in this PR:
- "This person has agreed to coauthor this post" is now the default when creating a post (there's an Asana ticket for this, but there doesn't seem to be a Github issue).
- Fixes #5111 the email subject now shows the name of the post author.
- Fixes another bug I found where draft posts which requested a coauthor would sometimes be inadvertently published when they were updated due to checking `!post.draft` instead of `post.draft === false`, where `post.draft` could be `undefined`.
- Fixes #5071 which is the majority of this PR and includes some UI changes which are described below.
We now display unconfirmed coauthors when viewing a draft post (UI suggestions are welcome!):
This is only viewable by the post author - coauthors …
=> Show pending coauthors

packages/lesswrong/components/alignment-forum/AFNonMemberInitialPopup.tsx, packages/lesswrong/components/alignment-forum/AFNonMemberSuccessPopup.tsx, packages/lesswrong/components/comments/CommentActions/DeleteCommentDialog.tsx, packages/lesswrong/components/comments/ModerationGuidelines/ModerationGuidelinesEditForm.tsx, packages/lesswrong/components/common/withDialog.tsx, packages/lesswrong/components/form-components/ImageUploadDefaultsDialog.tsx, packages/lesswrong/components/messaging/ConversationTitleEditForm.tsx, packages/lesswrong/components/posts/PostsPage/RSVPForm.tsx, packages/lesswrong/components/recentDiscussion/RecentDiscussionSubscribeReminder.tsx, packages/lesswrong/components/review/NominatePostDialog.tsx, packages/lesswrong/components/sunshineDashboard/ReportForm.tsx, packages/lesswrong/components/tagging/EditTagsDialog.tsx, packages/lesswrong/components/tagging/SubscribeButton.tsx, packages/lesswrong/components/tagging/TagFlagEditAndNewForm.tsx, packages/lesswrong/components/users/LoginPopup.tsx, packages/lesswrong/components/users/WrappedLoginForm.tsx
Fixes #5023 
This adds a login/sign up prompt when clicking "Subscribe" on a topic whilst logged out.
I also added a small amount of padding for the dialog as mentioned in the issue:
This same component is also used on the post analytics page:
and on the email subscription form, where I added a little negative margin to even things up:
These changes also shouldn't cause any issues for LessWrong:
=> Login prompt when subscribing

packages/lesswrong/components/editor/EditUrl.tsx
Reports exist that chrome on windows falls afoul of the link disappearing before the click goes through. I could not get the repro there. But I could on Firefox. So apparently my beautiful theory of how the system dynamics work has been destroyed by ugly data.
As a hack for now, add a 300 millisecond delay before clearing the link. That's about the upper limit of what feels natural.
=> Fix link clicking on link post hint text

packages/lesswrong/components/posts/PostsPage/PostsCoauthor.tsx
Currently co-authors are always shown on the homepage, but on the post page they are only shown to the author and other co-authors.
The logic should now be:
* If the user is the author or a co-author (either confirmed or pending) then all co-authors will be shown
* otherwise only confirmed co-authors will be shown.
=> Fix coauthors not being shown to non-author users

packages/lesswrong/components/posts/PostsPage/PostAuthorCard.tsx, packages/lesswrong/lib/collections/posts/schema.tsx
I don't think it makes sense for events to be a linkpost, since there are multiple other event-specific fields to add external links. So I'm hiding that option for events.
Also made a small EA Forum only update, to truncate the post author card bio by word instead of character.
=> hide the linkpost option for events

packages/lesswrong/components/common/SectionTitle.tsx, packages/lesswrong/components/common/Typography.tsx, packages/lesswrong/components/tagging/AllTagsAlphabetical.tsx
[Asana task](https://app.asana.com/0/628521446211730/1202465710122588/f)
This approach automatically creates an anchor for any section title where this is trivial, ie; when the title is a string. The existing code allows the title to be an arbitrary React element and, whilst is would be possible to extract some text from this, it could be expensive so we probably don't want to automatically do this for every current and future title on the site.
I also added the ability to specify a custom anchor - this is actually needed for "All Topics", otherwise it would include the total number of topics (like `#all-topics-597`) which obviously isn't stable. The link for the all topics section will now be `/topics/all#all-topics`.
In the end, I decided against turning the titles into clickable links …
=> Create section title anchors

packages/lesswrong/components/tagging/AllTagsPage.tsx, packages/lesswrong/lib/collections/tags/fragments.ts, packages/lesswrong/lib/collections/tags/schema.ts, packages/lesswrong/lib/generated/fragmentTypes.d.ts, packages/lesswrong/server/callbacks/revisionCallbacks.ts, packages/lesswrong/server/resolvers/tagResolvers.ts, packages/lesswrong/server/tableOfContents.ts, packages/lesswrong/server/tagging/updateDenormalizedHtmlAttributions.ts
This solution is less hacky than the previous, but should still be superceded by a fix in the editor (I still kind of wanted to implement this, if only for the GraphQL practice).
If there's still any big issues/questions then maybe we can jump on a call as you suggested.
There's an argument to be made that this could be more strongly integrated with the existing tag description, but I think it's better to keep some level of separation since this is a temporary solution.
=> Add anchors to "All topics" subheadings

packages/lesswrong/lib/collections/messages/schema.ts, packages/lesswrong/server/callbacks/commentCallbacks.ts, packages/lesswrong/server/callbacks/userCallbacks.tsx
Co-Authored-By: Sarah Cheng <sarah.cheng@centreforeffectivealtruism.org>
When users create a new account, send a welcome email, as both a PM conversation with the admin account, and as an email. This uses the database server setting `welcomeEmailPostId` to find the message to send (if not configured, nothing is sent).
* TODO for EA forum: Write a welcome post, mark it unlisted, and put its ID into the database setting.
* TODO for LW: Check over the pinnned "welcome to Less Wrong" post and make sure nothing about it is weird and bad if it's converted to an email instead of a post. Then put its ID into the database setting.
* TODO for AIAF: I think AF accounts always start as LW accounts that get promoted, but if that's wrong we need two different welcome posts.
(No emails get sent until …
=> Send a welcome PM and email 1 hour after a new account is created

packages/lesswrong/server/tableOfContents.ts
This is thankfully an easy fix. Cheerio objects are a kind of pseudo-array, so when there's no results for `cheerio(tag).closest('p')`, we don't get `null` or `undefined`, we actually get an object with a `length` property equal to 0.
=> Fix footnotes being added to the table of contents

packages/lesswrong/server/utils/httpUtil.ts
This should fix the issue where AB test assignments were lopsided, due to the `clientId` being cast to `"undefined"` on a device's first request (before the cookie had a chance to be set in the browser for future requests).
I'm not sure this is the best way to do it, but it was the minimally-invasive solution.
Biggest uncertainty: `getCookieFromReq` is used in a bunch of places.  In theory, the change I made would only ever affect other cookies if they were for some reason being set in `req.cookies` rather than `req.universalCookies` while the latter existed, and as far as I can tell the clientIdMiddleware is the only thing that does that.  I'm not familiar with the historical context around meteor/etc; if there's a better way to handle this let me know.
=> fix clientId cookie assignment for first logged out per-device requests

packages/lesswrong/components/common/LinkCard.tsx, packages/lesswrong/components/sequences/LargeSequencesItem.tsx, packages/lesswrong/components/sequences/SequencesHoverOver.tsx, packages/lesswrong/components/sequences/SequencesSmallPostLink.tsx
– Fixes an issue where the description of a sequence had a blurry gradient
– Adds total wordcount to the large sequence items as well as the sequence hoverovers.
– Makes the image in large sequence items into a link.
– increase opacity for large sequence item images.
=> improve sequence styling

packages/lesswrong/components/recommendations/RecommendationsAndCurated.tsx
In a previous PR I accidentally created multiple sequence-recommendations on mobile for logged out users and non-ideal-looking sequence recommendations for logged in ones. This fixes that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202565676154469) by [Unito](https://www.unito.io)
=> Fix mobile frontpage sequences
